\chapter{Why Vote for School Board?}
\label{chap:turnout}
\chapterstyle{deposit}

<<rsetup, results='hide', echo=FALSE, message=FALSE, warning=FALSE>>=
#setwd("../../../Data/Raw Files/Election Data")
#setwd("../Data/Raw Files/Election Data")
# source("dataclean.R")
# source("mappingfunctions.R")
# source("k8uhs.R")
opts_chunk$set(fig.width=8, fig.height=6, message=FALSE, error=FALSE, 
               fig.path="../../phd_figs/chap4-",
               warning=FALSE, echo=FALSE, dev='pdf')
@


\section{Introduction}
Since \citet{Downs57} political scientists have been asking the question: why vote? 
Voters in local school board elections may have been asking this question even 
earlier. Despite the fact that in general school boards are in charge of levying 
a substantial share of many citizens' tax bill through property taxes and 
collectively manage expenditures annually equivalent to the budget of the US 
Department of Defense, when school board elections are held off-cycle turnout 
and voter interest in them appears to be remarkably low \citep{RefWorks:333, RefWorks:321}. 
This despite the fact that the community stake in quality education is large, not 
just for parents of the students, but for the social, economic, and political 
impacts that high or low quality schools can have on a community. %citation needed

We know that voter turnout even in national on-cycle elections in the US remains 
lower than many other democracies \citep{BlaisTurnout2006}. We also have an extensive 
literature seeking to explain patterns in turnout between years and within years 
between social groups \citep{ParticAnnReview2004, econvoting2007, Galston2001, EconandOutcomes2000}.
The specific puzzle of voter turnout in school board elections has even spawned 
its own set of theories with empirical tests \citep{RefWorks:311,RefWorks:243,RefWorks:340}.

Despite this rich ground, much work remains to be done to adequately test the 
mechanisms at play in predicting turnout in off-cycle, local, non-partisan elections 
like school board elections. Furthermore, theories of participation in on-cycle and 
higher profile elections benefit from examining the limits of their generalizability and 
exploring the mechanisms that contribute to this. In this paper I seek to explore 
voter turnout in school board elections through the lenses of the major theories of 
voter turnout. I begin by reviewing these theories. Then, I move into a discussion 
of school boards and the contribution a study of school boards can bring to 
the understanding of these theories. Then I discuss the unique panel dataset of 
school board results that I have collected and the methods with which I will test 
these competing theories on the data. Finally, I conclude with an assessment of 
the performance of each of the theories and the foundations for future work. 


\section{Why Vote?}

Setting aside important though largely settled issues of access to the polls, 
enfranchisement laws, administrative and cognitive barriers to casting a ballot, and 
freedom from intimidation -- all thankfully of minimal concern in American school 
board elections -- there remains a wealth of intricate and interrelated factors 
which shape a voter's decision to cast a ballot.%CITATION needed here
I broadly group this literature 
into three major strands and include the theories that have sprung up uniquely 
around school boards as a fourth category. My aim is not to fully summarize this 
rich theoretical ground, but to reframe these debates in light of the particular 
challenge of school board elections. As prologue, I succinctly summarize the 
unique case against voting in school board elections as follows:

\begin{itemize}
  \item I don't know when the election is, or I forgot. (salience)
	\item I don't know who is running. (attention)
	\item I don't have a choice - no one is challenging the incumbent. (opportunity)
	\item I don't care which candidate wins. (lack of partisan cues)
	\item I'm satisfied with my schools. (lack of impetus)
	\item I don't care how schools perform or what the property tax is (salience)
	\item My vote won't matter
\end{itemize}

These concerns of our average potential voter are important to keep in mind as 
the major strands of voter participation theory are sketched out in the next 
sections. The turnout literature asks two fundamental questions -- why does 
anyone vote in the first place, and why do some people vote sometimes, and others 
do not? This chapter will attempt to answer these questions for off-cycle 
school board elections in Wisconsin. 

\begin{itemize}
	\item Rational Choice
	\item Socialization and Education
	\item Dissatisfaction and Protest
\end{itemize}

\subsection{Rational Choice}

\citet{Downs57}'s elegant statement of the problem of voting as a question of 
why anyone would vote when their vote has such a small probability of influencing 
the outcome presented political scientists with a challenge of understanding why 
people do vote. The now famous formal statement of the problem as given by Downs:

\[ R = PB - C > 0 \]

R is the net expected utility of voting, P is the probability of influencing the 
election, B is the difference in the expected utility of the policies of the 
two candidates, and C refers to the cost of voting. \citet{VoteCalculus68}'s 
refined the equation further by adding the D term:

\[ R = PB - C + D > 0 \]

which was intended to capture the benefit of self-expression associated with voting -- 
either self-expression of candidate preference, or self-expression of the utility of 
voting. However, the D-term merely shifted the debate - the probability of benefit 
from an individual vote still remained zero, so voters would only vote when $D > C$ - 
that is, when the benefit of self-expression was greater than the cost of voting 
\citep{nonvoting74, feddersenreview}.\footnote{\citet{Dowding2005} places an interesting 
wrinkle on this by questioning why voters care about being the decisive vote when 
politicians so often seek large victories to ensure a safe seat or to earn a mandate. 
This seems less germane to the present case - school board members and the community 
are unlikely to interpret a substantial victory as a mandate.} 
While the D term did not solve the puzzle posed by \citet{Downs57}, it 
did touch off a decades long research project to uncover why the D term varies 
among voters, and the functional form of this benefit of self-expression.\citep[see:][]{KanYang2001, 
Dowding2005,feddersenreview,Schuessler1} 

%%%%%%%%%%% CITES %%%%%%%%%%%%%%%%%

While I will not attempt to summarize this theoretically rich debate here 
\citep[see instead:][]{feddersenreview,geysreview}, I do want to highlight that most empirical 
tests of these voter turnout theories have focused on large-scale electorates such 
as state or national elections. There exists a class of voter turnout theories that 
predict very different behaviors for differently sized electorates. School board 
elections are typically comprised of small electorates (STATISTIC NEEDED) where 
P is much higher than other elections.\footnote{P can be calculated following the 
method of (CITATION) for school board races.} It remains to be seen if B is indeed 
higher in such cases, as we shall see the policy preferences of candidates for 
board are not always easily discovered by voters. Yet, game theoretic and social 
mobilization theories of turnout expect that in smaller electorates the collective 
behavior of the electorate or social group could spur turnout to be higher. 

% Game theoretic

In the game theoretic case the argument is that if everyone pursues the optimal 
strategy of not voting, then the value of PB increase. This sets of a strategic 
game amongst voters where the value of P is determined by the strategies selected by 
all other voters in the electorate \citep{Palfrey83, Palfrey85,Ledyard84}. In order for positive turnout to emerge from 
such a game, voters are expected to have certainty about the costs of voting and 
the preferences of other voters -- an unrealistic assumption in large electorates that 
hurts the case for such an approach \citep{Mueller3, aldrich1993}. This approach 
is often called the pivotal-voter model, and it has been explicitly tested in 
small-scale elections and found that while it predicts overall turnout sufficiently, 
it does not give an accurate reflection of the margins of victory \citep{Coate2008582}

%%%%%%%%%%% CITES %%%%%%%%%%%%%%%%%

% Group mobilization

Social networks and group organization might also help explain voter turnout. \citet[p.23]{geysreview}
states the key of the group-based models:

\begin{quote}
First, groups are likely to have larger beneﬁts than individuals from political participation. 
The reason is that politicians may provide groups with extra beneﬁts – in terms of 
policies that come closer to the group’s optimum – to win the support of the group \citep{Lapp99}. 
Second, as the political inﬂuence of a social group can be assumed to be proportional to its size
\citep{SchrWinden1991}, the group as a whole is more likely to have a 
non-negligible impact on the election outcome. 
\end{quote}

The group approach appears to more accurately reflect the modern political environment 
and campaign strategy of mobilization and targeted messaging to voters \citep{Lapp99}. 
The theory is more nuanced because it allows for the case where the optimal strategy 
for a group is to abstain from voting \citep{geysreview, Fowler2005}. 
Crucially, such group-based mobilization relies on the group being able to enforce 
the voting norm within the group. This enforcement has been shown to depend on 
factors that seem especially reflected within small-scale local elections. 
\citet[p.25]{GrossmanHelpman} identify three such factors: the 
frequency of interactions within the group, the risk of social isolation resulting 
from deviating from the group's behavior, and the ability of group members to 
monitor one another. These factors are essential to preventing free riding \citep[see][]{Olson65}.  
\citet{SchrWinden1991} identifies opinion leaders within these groups as a key 
transmitter of social pressure. These leaders have incentives to increase turnout such 
as increasing their influence with elected officianls, and voters wanting to build 
credibility with these leaders find that turning out to vote is important. In the case 
of school board elections such local effects might be amplified in communities with 
strong local organizations where monitoring costs are low. \footnote{\citet{Morton91} finds that there is an equilibrium 
with positive turnout if at least one leader has a strict preference for a single candidate.}


% Information
An important addition to this theoretical base came by adding the influence of 
limited voter information to voter turnout \citep{Matsusaka}. Voters' uncertainty 
around the B term, the policy difference between candidates, makes voting a riskier 
decision even for voters with a high predisposition for voting. The better informed 
a voter is, the more certainty they have that their vote will increase the likelihood 
of their policy preferences being realized. Partisan cues play an important role 
in this framework by reducing the cost of acquiring certainty about policy preferences and
at times drawing clear distinctions between them \citep{aldrich1993}.\footnote{
\citet{Larcinese} adapted \citet{Matsusaka} by showing that non-partisan citizens are most 
likely to acquire information, and thereby increase their likelihood to vote. WHY?!?!} 

An important feature of this school of thought is that much of the empirical testing 
of these theories has been done in situations where voters have a high chance of being 
incidentally, that is without incurring costs, exposed to information about the election 
because of the high profile nature of these races \citep{aldrich1993}. The informational 
cues provided by partisan signals in such races even further reduces this. School board
races, for the most part, feature neither of these cost reducing features. It seems unlikely 
that these higher costs are accompanied by higher benefits in such elections. Though 
voters are assured a higher likelihood of casting the deciding vote, they are much less certain 
that the election of candidate A over candidate B will make much of a difference in 
their quality of life in the immediate or medium term. 

School boards may prove to be the electoral unit for which the Downsian hypothesis 
is the most strained. In many state school boards are sub-county administrative 
entities without partisan office holders and who often elect multiple members in 
one election cycle. Furthermore, the low level of information about school board 
candidates, their positions on issues, their likely vote share in an election, and 
the voters' own feelings on issues facing the school board make this environment 
dramatically different than the presidential election. What's more, the likelihood 
that the vote of any single voter matters in a school district is orders of 
magnitude larger than for state wide or nation wide office. 

%%%%%%%%%%% CITES %%%%%%%%%%%%%%%%%

\subsection{Socialization}

Other scholars have found that the D term can be endogenous for individuals from 
election to election \citep{Plutzer2002}. Experimental 
evidence has found that ``Voting and abstention, in other words, are habit forming'' 
\citep[p.540]{Gerber2003} This is related to the group mobilization arguments 
above because social groups may well be the mechanism by which the habit is 
formed \citep{Kanazawa2000}. Particularly in groups that interact frequently or 
in tight knit communities social rewards may be found for voting and sanctions 
may be made for those who abstain \citep{Fowler2005}. Then, citizens who are 
rewarded for their vote (via the election of their preferred candidate) or punished for their abstention
(through the election of a less-preferred candidate) acquire an increased prefer-
ence for voting. In contrast, if their voting is punished or their abstention is
rewarded, they lose some of their preference for voting

In school boards there is evidence that such socialization has occurred in the case of 
conservative Christians \citep{RefWorks:240}, unionized teachers \citep[chapter 5]{RefWorks:249, RefWorks:207}, 
and suggestions about the role institutions may play in deepening or weakening 
such socialization among ethnic minorities \citep{RefWorks:195}. Evidence of socialization 
is occurring might be found by observing ``stickiness'' in voter turnout 
in school board elections year to year, independent of other factors. \citet{RefWorks:248} 
called this the social conditioning model of school board turnout and found it held 
explanatory power in California school board election voter registration rates, 
but not rates of voter turnout. If members of the community vote at a higher 
average level after a high turnout election, this may provide evidence that the 
influx of turnout in the prior election has influenced the current election. 


\subsection{Summing Up}

Major questions that can be explored by analyzing small scale elections in WI:
- Does the closeness of the election/margin relate to turnout ala \citep{Coate2008582}
- Does the size of the electorate affect turnout? 
- Does relative group size affect the turnout? (Can investigate traditional partisanship, but not other methods)
- Is turnout sticky?

Throw the bums out. Dahl to Alsbury. 

Dissatisfaction theory is the closest link in the school board literature to 
larger political science theories of voter turnout. 

\section{School Boards and Voter Turnout}

The current project adds importantly to the puzzle of voter turnout in two important ways. 
First, it provides an important update to the prior literature on school board 
election participation by explicitly measuring voter turnout in school board 
elections and investigating several hypothesized drivers of voter participation 
in such elections \citep{RefWorks:311,RefWorks:243,RefWorks:340}. Second, this study 
explores the linkage between state level politics and local electoral participation. 
Thus, the study represents an attempt to estimate the causal effect of a state 
level policy shock on voter turnout in local elections by leveraging the unique 
conditions in Wisconsin from 2010-2012. The present study presents an important 
oppotunity to test theories of participation and cross-level linkages in a federal 
system that previously were not available to political scientists. 

\subsection{Voter Turnout in School Board Elections}

While some rational choice models have been adapted to the school board contest, 
there exist no large scale studies of voter turnout in school board elections 
that have empirically tested these theories 
\citep{RefWorks:243, RefWorks:340, RefWorks:339}. Instead, studies have focused 
predominantly on candidates for school board, why they run, and if their races 
are competitive \citep{RefWorks:311, RefWorks:321, RefWorks:322, RefWorks:207}. 
Yet, it might be argued, that such studies are jumping the gun. The conventional 
wisdom about school board elections is that they are minor affairs, settled on 
obscure issues, and conducted among large public apathy. Off-cycle school board 
elections are decidedly low turnout affairs. If boards have competitive elections 
that lead to consequential decisions like superintendent turnover (ala Dissatisfaction 
Theory \citep{RefWorks:297}), what does it matter if those hotly contested electoral 
defeats of incumbents came at the hand of 10\% of the electorate? The overwhelming 
majority has indeed cast a vote of indifference. 

By leaving out the question of turnout, Dissatisfaction Theory has left out an 
important strategic actor in the act of expressing dissatisfaction with the 
direction of the schools -- the voter \citep{RefWorks:243}. The current study 
rectifies this by providing a descriptive analysis of voter turnout over an extended 
number of election cycles at hundreds of school districts within Wisconsin simultaneously. 
Naturally it is not expected to find school board races to be high turnout affairs 
year in and year out. But, if Dissatisfaction Theory is to be saved from criticism 
that it ignores voters in favor of focusing on board-superintendent relationships, 
some cases of heightened turnout must be identified. The current study is fruitful 
ground for examining voter turnout trends in school board elections as well as exploring 
possible opportunities for voters to express dissatisfaction with academic, fiscal, 
or the policy performance of the local school district. 

\subsection{Exogenous State Level Policy Shocks and Voter Decisions}

There is one specific theory about voter turnout that this data can test is the 
linkage between voter turnout in school board elections and state level policy 
shocks. While there has recently been more attention on the linkage between 
national political trends and state level election returns (CITATION NEEDED), these 
studies have not been extended to the local level. However, the local level provides 
an interesting level of analysis because local elections are much more diverse than 
their state level counterparts in terms of the timing, partisanship of office, and 
structure of the elections. Where it is difficult to disentangle relationships between 
national legislature and state legislature composition from national trends in 
partisanship and strategic redistricting (CITATION NEEDED), the diversity of local 
elections allows more opportunities for exogenous variation to explore the causal 
transmission of voter preferences at the state level being expressed in local 
elections. 

Wisconsin from 2010-2012 provides an ideal test case for the transmission of 
state level political preferences to local non-partisan office. As discussed in 
Chapter \ref{chap:theoryreview} and illustrated in Figure \ref{fig:wiscotimeline} 
the election of Scott Walker to Governor and the subsequent passage of Act 10, the 
2011-13 biennial budget, and the mass protests in Madison, WI, state level politics 
in Wisconsin became suddenly extremely polarized. In addition to the sudden 
polarization, much of the rhetoric, protest, and contentiousness surrounding 
the Walker administration was focused squarely on education politics and labor 
relations - issues that school boards have great local influence over. In fact, 
Act 10 represented a sweeping expansion of the power of school boards away from 
local teachers' unions. Thus, the composition of the school board mattered more 
than ever after Act 10. Importantly, the passage of Act 10 was completely unforeseen 
by political observers and the public and represent an exogenous shock to the 
state political system. \footnote{This last point is somewhat disputed by some 
political observers and Scott Walker himself, but the consensus has been that 
this was not the case according to the \href{http://www.politifact.com/wisconsin/statements/2011/feb/22/scott-walker/wisconsin-gov-scott-walker-says-he-campaigned-his-/}{Milwaukee Journal Sentinel}.}

This paper leverages the unexpected passage of Act 10 as providing a natural 
experiment of the effect of state level policy shocks on local level electoral 
participation. In fact, in this case, the policy shock and surrounding political 
polarization was directly related to the powers of school boards, a locally 
elected non-partisan office. Even more interestingly, school board elections are 
held off-cycle in Wisconsin in the spring on the $2^{nd}$ Tuesday each April. This 
combination of non-partisan off-cycle elections and a wide and deeply salient policy 
shock provide an ideal test of whether or not state level policy actions can spur 
voters in local elections. If there is no impact on voter turnout in the wake 
of such a broad expansion of school board power over an issue as polarizing as 
collective bargaining rights for local employees, we would expect smaller policy 
shocks to have no effect either. 

\subsection{How School Board Elections are Different}

- Off-cycle
- Non-partisan
- Low salience
- Low campaign activity


\section{Data and Methods}

%% Standard data writeup here
%% Write up the method for the descriptive analysis
%% Write up method for causal analysis


\section{Results}


\section{Conclusion}
