\chapter{Why Vote for School Board?}
\label{chap:turnout}
\chapterstyle{deposit}

<<rsetup, results='hide', echo=FALSE, message=FALSE, warning=FALSE>>=
opts_chunk$set(fig.width=8, fig.height=6, message=FALSE, error=FALSE, 
               fig.path="../../phd_figs/chap4-",
               warning=FALSE, echo=FALSE, dev='pdf')

setwd("../../")
source("data/dataAssemble.R")
#source("data/dataMerge.R")
source("R/thesis_functions.R")
library(scales)
library(xtable)
library(eeptools)

options(xtable.include.rownames = FALSE, xtable.table.placement = "ht")
load("data/cache/DataMergeVAP.rda")
load("data/cache/fullDataSep2014.rda")


distAttr <- tmp[, c("distid", "year", "TotalPopulation", "NonSDMill", "AdjPopulation",
                    "PopWhiteAlone", "median_income", "total_levy", "genaid", "per65o", 
                    "PerBachelorOrAbove", "OOH_share", "millrate", "median_income", 
                    "COUNTY", "CESA", "ATHLETIC_CONF_NUMBER", "eqv_member", 
                    "total_levy", "genaid", 
                    "balance_lag", "member_aidyear", "member_delta", "millrate_delta", 
                    "locale2", "member_lag", "ref_share")]

source("data/cleanandprep_DPIADMIN.R")
rm(tmp)

distAttr$per_white_all <- distAttr$PopWhiteAlone / distAttr$TotalPopulation
distAttr$white_count <- NULL
distAttr$PopWhiteAlone <- NULL
distAttr$TotalPopulation <- NULL
@


\section{Introduction}

In most jurisdictions, school board elections are an annual event. Each year voters 
are asked who they would like to lead the direction of their local schools including 
the setting of property tax rates, management of strategic priorities, and 
negotiating compensation with employees. In making this decision, voters have 
precious little information to go on given the low level of campaign activity and 
the lack of involvement by parties. Even worse, voters may have little way to 
retrospectively rate the performance of the school board. Even if they have children
in school, the information costs of evaluating school board performance remain 
high. Given these difficulties, it is a wonder that anyone bothers to vote in 
such elections. 

Indeed, ever since \citet{Downs57} political scientists have been asking the question: why vote? Despite the fact that in general school boards are in charge of levying 
a substantial share of many citizens' tax bill through property taxes and 
collectively manage expenditures annually equivalent to the budget of the US 
Department of Defense, when school board elections are held off-cycle turnout 
and voter interest in them appears to be remarkably low \citep{RefWorks:333, RefWorks:321}. 
This despite the fact that the community stake in quality education is large, not 
just for parents of the students, but for the social, economic, and political 
impacts that school quality can have on a community. 

Voter turnout even in national on-cycle elections in the US remains 
lower than many other democracies \citep{BlaisTurnout2006}. There is an extensive 
literature seeking to explain patterns in turnout between years and within years 
between social groups \citep{ParticAnnReview2004, econvoting2007, Galston2001, EconandOutcomes2000}.
The specific puzzle of voter turnout in school board elections has even spawned 
its own set of theories with empirical tests \citep{RefWorks:311,RefWorks:243,RefWorks:340}.

Despite this rich ground, much work remains to be done to adequately test the 
mechanisms at play in predicting turnout in off-cycle, local, non-partisan elections 
like school board elections. Furthermore, theories of participation in on-cycle and 
higher profile elections benefit from examining the limits of their generalizability. In this paper I seek to explore 
voter turnout in school board elections through the lenses of the major theories of 
voter turnout. I begin by reviewing these theories. Then, I move into a discussion 
of school boards and the contribution a study of school boards can bring to 
the understanding of these theories. Then I discuss the unique panel data set of 
school board results that I have collected and the methods with which I will test 
these competing theories on the data. Finally, I conclude with an assessment of 
the performance of each of the theories and the foundations for future work. 

%% Significance of school boards
%% - as a share of elections they are dominant
%% - they have tremendous consequences to parents and tax payers 
%% - they are very different structurally, more variation, richer ground for theory


\section{Why Vote?}

Setting aside important though largely settled issues of access to the polls, 
enfranchisement laws, administrative and cognitive barriers to casting a ballot, and 
freedom from intimidation -- all thankfully of minimal concern in American school 
board elections -- there remains a wealth of intricate and interrelated factors 
which shape a voter's decision to cast a ballot. I broadly group this literature 
into three major strands and include the theories that have sprung up uniquely 
around school boards as a fourth category. My aim is not to fully summarize this 
rich theoretical ground, but to reframe these debates in light of the particular 
challenge of school board elections. 
% As prologue, I succinctly summarize the 
% unique case against voting in school board elections as follows:
% 
% \begin{myitemize}
%   \item I don't know when the election is, or I forgot. (salience)
% 	\item I don't know who is running. (attention)
% 	\item I don't have a choice - no one is challenging the incumbent. (opportunity)
% 	\item I don't care which candidate wins. (lack of partisan cues)
% 	\item I'm satisfied with my schools. (lack of impetus)
% 	\item I don't care how schools perform or what the property tax is (salience)
% 	\item My vote won't matter
% \end{myitemize}

The turnout literature asks two fundamental questions -- why does 
anyone vote in the first place, and why do some people vote sometimes, and others 
do not? This chapter will attempt to answer these questions for off-cycle 
school board elections in Wisconsin. 

\begin{myitemize}
	\item Rational Choice
	\item Group Mobilization
	\item Information
  \item Habits and Socialization
\end{myitemize}

Other researchers studying subnational municipal or provincial elections have 
found support for these explanations of turnout \citep{Hajnal01052003, PPIC2002}. 


\subsection{Rational Choice}

\citet{Downs57}'s elegant statement of the problem of voting as a question of 
why anyone would vote when their vote has such a small probability of influencing 
the outcome presented political scientists with a challenge of understanding why 
people do vote. In the formal statement of the problem as given by Downs:

\[ R = PB - C > 0 \]

$R$ is the net expected utility of voting, $P$ is the probability of influencing the 
election, $B$ is the difference in the expected utility of the policies of the 
two candidates, and $C$ refers to the cost of voting. Voters should not vote 
unless their expected benefit from having their preferred candidate elected multiplied 
by the chance of their vote being the decisive vote exceeds the costs of voting. A first attempt to answer the empirical observation that many more voters vote than 
should be expected under this model came from \citet{VoteCalculus68}'s 
further refinement of the problem:

\[ R = PB - C + D > 0 \]

The addition of the $D$ term is intended to capture the benefit of self-expression associated with voting -- either self-expression of candidate preference, or self-expression of the utility of voting. However, this $D$ term merely shifted the debate - the probability of benefit 
from an individual vote still remained zero, so voters would only vote when $D > C$ - 
that is, when the benefit of self-expression was greater than the cost of voting 
\citep{nonvoting74, feddersenreview}.\footnote{\citet{Dowding2005} places an interesting 
wrinkle on this by questioning why voters care about being the decisive vote when 
politicians so often seek large victories to ensure a safe seat or to earn a mandate. 
This seems less germane to the present case - school board members and the community 
are unlikely to interpret a substantial victory as a mandate.} 
While the $D$ term did not solve the puzzle posed by \citet{Downs57}, it 
did touch off a decades long research project to uncover why the $D$ term varies 
among voters, and the functional form of this benefit of self-expression.\citep[see:][]{KanYang2001,Dowding2005,feddersenreview,Schuessler1} 

While I will not attempt to summarize this theoretically rich debate here 
\citep[see instead:][]{feddersenreview,geysreview}, I do want to highlight that most empirical 
tests of these voter turnout theories have focused on large-scale electorates such 
as state or national elections. There exists a class of voter turnout theories that 
predict very different behaviors for differently sized electorates. As shown 
in \ref{chap:wisco} school board 
elections are typically comprised of small electorates where 
P is much higher than other elections.\footnote{$P$ can be estimated using the 
Blais-Lago calculation for the competitiveness of elections under various configurations of open seats and number of winners \citep{blaislago}.} It remains to be seen if 
$B$ is indeed 
higher in such cases, as we shall see the policy preferences of candidates for 
board are not always easily discovered by voters. Yet, game theoretic and social 
mobilization theories of turnout expect that in smaller electorates the collective 
behavior of the electorate or social group could spur turnout to be higher. 

% Game theoretic

In the game theoretic case the argument is that if everyone pursues the optimal 
strategy of not voting, then the value of $PB$ increase. This sets of a strategic 
game among voters where the value of $P$ is determined by the strategies selected by 
all other voters in the electorate \citep{Palfrey83, Palfrey85,Ledyard84}. In order for positive turnout to emerge from 
such a game, voters are expected to have certainty about the costs of voting and 
the preferences of other voters -- an unrealistic assumption in large electorates that 
hurts the case for such an approach \citep{Mueller3, aldrich1993}. This approach 
is often called the pivotal-voter model, and it has been explicitly tested in 
small-scale elections and found that while it predicts overall turnout sufficiently, 
it does not give an accurate reflection of the margins of victory \citep{Coate2008582}. 
Other scholars find size to be an important factor in local elections, but do not 
tie this to a particular theory of voter turnout \citep{Frandsen2002}.\footnote{The size 
question is a curious one, because at its extreme it would predict that lower-level 
elections should thus exhibit higher turnout than national elections - a phenomenon 
described by \citet{Horiuchi2001} as the ``turnout-twist.'' Evidence of this in 
Wisconsin will be explored later.}

%%%%%%%%%%% CITES %%%%%%%%%%%%%%%%%

\subsection{Group Mobilization}

Social networks and group organization might also help explain voter turnout. \citet[p. 23]{geysreview} states the key of the group-based models:

\begin{quote}
First, groups are likely to have larger benefits than individuals from political participation. The reason is that politicians may provide groups with extra benefits – in terms of 
policies that come closer to the group’s optimum – to win the support of the group \citep{Lapp99}. 
Second, as the political influence of a social group can be assumed to be proportional to its size
\citep{SchrWinden1991}, the group as a whole is more likely to have a 
non-negligible impact on the election outcome. 
\end{quote}

The group approach appears to more accurately reflect the modern political environment 
and campaign strategy of mobilization and targeted messaging to voters \citep{Lapp99}. 
The theory is more nuanced because it allows for the case where the optimal strategy 
for a group is to abstain from voting \citep{geysreview, Fowler2005}. 
Crucially, such group-based mobilization relies on the group being able to enforce 
the voting norm within the group. This enforcement has been shown to depend on 
factors that seem especially of interest in small-scale local elections. 
\citet[p.25]{GrossmanHelpman} identify three such factors: the 
frequency of interactions within the group, the risk of social isolation resulting 
from deviating from the group's behavior, and the ability of group members to 
monitor one another. These factors are essential to preventing free riding \citep[see][]{Olson65}.  
\citet{SchrWinden1991} identifies opinion leaders within these groups as a key 
transmitter of social pressure. These leaders have incentives to increase turnout such 
as increasing their influence with elected officianls, and voters wanting to build 
credibility with these leaders find that turning out to vote is important. In the case 
of school board elections such local effects might be amplified in communities with 
strong local organizations where monitoring costs are low.\footnote{\citet{Morton91} finds that there is an equilibrium 
with positive turnout if at least one leader has a strict preference for a single candidate.}

Notably missing from this summary is the influence that candidates and campaigns 
have on voter turnout. While there is some evidence that education messages used 
by candidates and campaign expenditures in local elections can play in mobilizing voters \citep{SidesKarch2008, Holbrook15072013}, 
the impact of these in school board elections is likely marginal. In the most recent survey of school board members, over 
two-thirds of board members report their last election as being ``easy'' or ``somewhat 
easy'', and in small districts this percentage is even higher \citep{RefWorks:322}.\footnote{Moreover, it is hard to know how much mobilization or advertising 
candidates can do when nearly 75\% of survey respondents report spending less than 
\$1,000 on their last campaign, and in small districts over 95\% of candidates 
reported spending less than \$1,000 on their campaign.\citep{RefWorks:322}}

\citet{anzia11} finds that off-cycle elections confer greater benefits to organized 
interest groups than larger on-cycle elections. Teacher unions have a greater 
advantage in low turnout low information off-cycle elections and therefore can 
use this advantage to influence school board members to provide higher salaries 
than among boards elected with a broader on-cycle electorate \citep{anzia11}. This 
falls in line with the work of \citet{RefWorks:207,RefWorks:218} that organized 
interest groups like teacher unions play an outsized role in off-cycle low turnout 
school board elections. 

\subsection{The Role of Information}
An important addition to this theoretical base came by adding the influence of 
limited voter information to voter turnout \citep{Matsusaka}. Voters' uncertainty 
around the policy benefits, due to a dearth of information on the policy difference between candidates, makes voting a riskier 
decision even for voters with a high predisposition for voting. The better informed 
a voter is, the more certainty they have that their vote will increase the likelihood 
of their policy preferences being realized. Partisan cues play an important role 
in this framework by reducing the cost of acquiring certainty about policy preferences and
at times drawing clear distinctions between them \citep{aldrich1993}.\footnote{
\citet{Larcinese} extended the work of \citet{Matsusaka} by showing that non-partisan citizens are most likely to acquire information, and thereby increase their likelihood to vote.} 

An important feature of this theory is that much of the empirical testing 
has occurred in situations where voters have a high chance of being 
incidentally, that is without incurring costs, exposed to information about the election because of the high profile nature of these races \citep{aldrich1993}. The informational cues provided by partisan signals in such races even further reduces 
information gaps among voters. School board races, for the most part, feature neither of these cost reducing features. It seems unlikely 
that these higher costs are accompanied by higher benefits in such elections. Though 
voters are assured a higher likelihood of casting the deciding vote, they are much less certain 
that the election of candidate A over candidate B will make much of a difference in 
their quality of life in the immediate or medium term. 

Interestingly, some studies of local elections have found that voters in these 
elections -- though fewer -- are much more informed and engaged than non-voters 
\citep{oliver12}. The causal direction of this relationship is not clear, but 
there is some suggestion that the electorate in these non-partisan local races 
has a stronger estimate of the expected benefit of their candidate winning than 
non-voters.

School boards are a fascinating lens through which we can explore the Downsian 
hypothesis and its extensions. In many states school boards are sub-county 
administrative entities without partisan office holders and who often elect multiple members in 
one election cycle. Furthermore, the low level of information about school board 
candidates, their positions on issues, their likely vote share in an election, and 
the voters' own feelings on issues facing the school board make this environment 
dramatically different than the presidential election. What's more, the likelihood 
that the vote of any single voter matters in a school district is orders of 
magnitude larger than for state wide or nation wide office. 

\subsection{Voter Socialization}

Other scholars have found that the D term can be endogenous within individuals from 
election to election \citep{Plutzer2002}. Experimental 
evidence has found that ``voting and abstention, in other words, are habit forming'' 
\citep[p.540]{Gerber2003} This is related to the group mobilization arguments 
above because social groups may well be the mechanism by which the habit is 
formed \citep{Kanazawa2000}. Particularly in groups that interact frequently or 
small communities with low monitoring costs, social rewards may be found for 
voting and sanctions 
may be made for those who abstain \citep{Fowler2005}. Then, citizens who are 
rewarded for their vote (via the election of their preferred candidate) or punished for their abstention
(through the election of a less-preferred candidate) acquire an increased preference for voting. Conversely, if their voting is punished or their abstention is
rewarded, they lose some of their preference for voting. This has been considered 
in other cases by political scientists as well \citep{ParticAnnReview2004}.\footnote{
Other scholars have found that not just the depth and frequency of interactions with 
voters matters, but also the nature of those interactions, the ideological 
composition of those groups, and socio-economic status
\citep{Mutz2002, classpart04, classbias92}.}


In school boards there is evidence that such socialization has occurred in the case of 
conservative Christians \citep{RefWorks:240}, unionized teachers \citep[chapter 5]{RefWorks:249, RefWorks:207}, 
and suggestions about the role institutions may play in deepening or weakening 
such socialization among ethnic minorities \citep{RefWorks:195}. Evidence of socialization 
is occurring might be found by observing ``stickiness'' in voter turnout 
in school board elections year to year, independent of other factors. \citet{RefWorks:248} 
called this the social conditioning model of school board turnout and found it held 
explanatory power in California school board election voter registration rates, 
but not rates of voter turnout. If members of the community vote at a higher 
average level after a high turnout election, this may provide evidence that the 
influx of turnout in the prior election has influenced the current election. 

\subsection{Dissatisfaction Theory}

In Chapter \ref{chap:intro} I introduced dissatisfaction theory as the 
dominant theoretical paradigm for understanding school board elections.
This theory traces its roots back to \citet{RefWorks:348}'s concept of critical 
elections and \citet{RefWorks:319}'s conception of pluralism. It describes an electoral system with relative stability and little 
involuntary incumbent turnover punctuated by periods of citizen 
dissatisfaction, contentious elections, and incumbent defeats \citep{RefWorks:297,RefWorks:271}. 
Figure \ref{dissatdiag} displays the sequence of events in the model. Missing from 
empirical tests of dissatisfaction theory to date are indicators of voter participation. 
Implied throughout the dissatisfaction theory literature is that incumbent defeat 
is accompanied by an upwelling in citizen dissatisfaction and presumably voter 
participation in the election. Incumbents are defeated because new voters enter 
the game. Yet, until now, voter turnout in school board elections has not been 
used to test dissatisfaction theory explicitly, though it has received limited 
attention in understanding other phenomena of local education politics \citep{RefWorks:248, 
RefWorks:249, RefWorks:207, RefWorks:218}.\footnote{Taxpayers also have another 
option for expressing their dissatisfaction, which is to move jurisdictions \citep{MinkoffLyons}. 
In Wisconsin, yet another option of expressing dissatisfaction with the school board 
is available to parents - open-enrolling out of the school district. Both of these 
forms of dissatisfaction are decidedly higher cost than voting in a school board 
election, though their benefit is more immediate and selective.}

While some rational choice models have been adapted to the school board contest, 
there exist no large scale studies of voter turnout in school board elections 
that have empirically tested these theories 
\citep{RefWorks:243, RefWorks:340, RefWorks:339}. Instead, studies have focused 
predominantly on candidates for school board, why they run, and if their races 
are competitive \citep{RefWorks:311, RefWorks:321, RefWorks:322, RefWorks:207}. 
Yet, it might be argued, that such studies are jumping the gun. The conventional 
wisdom about school board elections is that they are minor affairs, settled on 
obscure issues, and conducted among large public apathy. Off-cycle school board 
elections are decidedly low turnout affairs. If boards have competitive elections 
that lead to consequential decisions like superintendent turnover as expected 
by Dissatisfaction Theory \citep{RefWorks:297}, what does it matter if those hotly contested electoral defeats of incumbents came at the hand of 10\% of the electorate? The overwhelming majority has indeed cast a vote of indifference. 

By leaving out the question of turnout, Dissatisfaction Theory has left out an 
important strategic actor in the act of expressing dissatisfaction with the 
direction of the schools -- the voter \citep{RefWorks:243}. The current study 
rectifies this by providing a descriptive analysis of voter turnout over an extended 
number of election cycles at hundreds of school districts within Wisconsin simultaneously. 
Naturally it is not expected to find school board races to be high turnout affairs 
year in and year out. But, if Dissatisfaction Theory is to be saved from criticism 
that it ignores voters in favor of focusing on board-superintendent relationships, 
some cases of heightened turnout must be identified. The current study is fruitful 
ground for examining voter turnout trends in school board elections as well as exploring 
possible opportunities for voters to express dissatisfaction with academic, fiscal, 
or the policy performance of the local school district. 

% 
% Low-salience and low-participation elections thus can be considered democratic, 
% if there is evidence that they are punctuated by periods of electoral activity 
% when needed. 

\section{School Boards and Voter Turnout}

The current project adds importantly to the puzzle of voter turnout in two important ways. First, it creates test conditions for competing theories of voter turnout 
in one of the most common election types in America -- non-partisan school board 
elections. Second, it provides an important update to the prior literature on school board election participation by explicitly measuring voter turnout in school board 
elections and investigating several hypothesized drivers of voter participation 
in such elections \citep{RefWorks:311,RefWorks:243,RefWorks:340}.  

\subsection{Voter Turnout in School Board Elections}

Several competing conceptions of voter turnout can be explored at the local level 
through the lens of turnout in school board elections. Table \ref{turnoutH} lists 
the evidence in school board turnout that would be consistent with the dominant 
theories of voter turnout. 


\begin{table}[h!]
\begin{center}
\begin{small}
\caption{Theories of Turnout and Expected Evidence}
\label{turnoutH}
\begin{tabular}{| p{.25\textwidth} | p{.2\textwidth} | p{.375\textwidth} |}
\hline
\textbf{Theory}  & \textbf{Citation} & \textbf{Expected Finding} \\ \hline
Habit-forming voters  & \citet{Plutzer2002} & High autocorrelation in turnout\\ \hline
Game-theoretic voters & \citet{Mueller3, aldrich1993} & Smaller electorate has higher turnout \\ \hline
Social group led voting &\citet{Fowler2005} & Union membership as share of electorate drives up turnout \\ \hline
Pivotal-voter & \citet{Downs57} & Small electorate and close election drives turnout up \\ \hline
Social group led voting &\citet{Fowler2005} & Polarized communities have higher turnout \\ \hline
\end{tabular}
\end{small}
\end{center}
\end{table}


\section{Data}
\label{sec:turnData}

This study tests competing theories of voter turnout on a dataset representing 
school board elections in the state of Wisconsin from 2002-2012. The data come 
from approximately 310 of Wisconsin's 424 school districts and are described in 
detail in Chapter \ref{chap:wisco} and Appendix \ref{app:data}.

\subsection{Dependent Variables}

I start by describing the two unique dependent variables used in this chapter. 
The first is a straightforward estimate of the voter turnout in Wisconsin spring 
school board elections. The next variable represents the distance between turnout 
for the top ticket spring race and the school board race. This variable is an 
attempt to separate out the influence of statewide races in the spring elections 
on any measurement of the effect of key variables on school board election 
participation.

\subsubsection{Spring Turnout}
As we saw in Chapter \ref{chap:wisco}, the spring elections in Wisconsin are decidedly low turnout affairs. Estimating school board election turnout is decidedly difficult because it requires 
both a reliable assessment of the votes cast in the election and a reliable 
estimate of the voting age population in the school district. Due to the fact that 
school districts have diverse electoral structure and no requirements 
on election reporting to a central authority, it is often difficult to ascertain 
the number of votes cast by voters within the school district. 
To determine the voting age population (VAP) of the school district in Wisconsin, I employ the finest resolution 
estimate of voting age population available -- VAP estimates by minor civil division (MCD) 
conducted by the Wisconsin Department of Administration described in Chapter \ref{chap:wisco} Section \ref{subsec:turnout}.\footnote{Available online: \url{http://gab.wi.gov/elections-voting/results}. Statistics for Wisconsin Minor Civil Divisions are maintained by the Department of Administration Demographic Services Center: \url{http://www.doa.state.wi.us/section\_detail.asp?linkcatid=11\&linkid=64\&locid=9}} With the method described in that section, I am able to estimate the voter turnout for 
each school district in Wisconsin on school board elections as well as on presidential, 
gubernatorial, and non-partisan spring elections. 

\subsubsection{Voter Rolloff}

Another dependent variable to look at is school board vote independent of turnout 
higher up the ticket known as the undervote or rolloff \citep{wattenberg00}. As 
voters move down the ballot, many of them simply stop voting and turn in an incomplete 
ballot, a decision based on the increasing discomfort of voters with making decisions 
on races for which they have little to no interest and/or information. As I showed 
in Section
\ref{subsec:undervote}, rolloff varies year to year in districts providing hope that some of this variation can be explained by theories of voter turnout. This variable 
has another advantage. As I showed in Section \ref{subsec:turnout}, turnout rose in 2011 due to the heightened interest in the state supreme court election between David Prosser and Joanne Kloppenburg. This makes it difficult to attribute heightened school board voter turnout year to year to school boards when 
the turnout for the top ticket race changes year to year and can do dramatically. 
The estimated difference in school board turnout to top ticket turnout can be one 
way to measure the political interest of voters in school boards in particular. 
A disadvantage of this measure is that school board is not the only down-ticket race and undervote does not measure voter interest as many voters do not abstain. 

For the 2007-2012 period, I estimate the top ticket 
turnout in each school district. Importantly, in this period, several different 
office types were the top ticket due to the pattern of statewide office terms 
in Wisconsin. These consist of primarily state supreme court races, but as there 
seven justices elected to ten-year terms, the state supreme court does not have 
an election every spring: 

\begin{myitemize}
  \item 2007 - State Supreme Court Race
  \item 2008 - State Supreme Court Race and presidential primary
  \item 2009 - State Superintendent of Public Instruction
  \item 2010 - None. Wisconsin Appeals Courts (3 of 4)
  \item 2011 - State Supreme Court Race
  \item 2012 - Presidential Preference Primary
\end{myitemize}

If top ticket races drive voter turnout, then examining the degree to which school 
board turnout leads or lags top ticket races may provide some insight into the 
political activity in school board races independent of such races. Voter rolloff 
after the top ticket arises for a number of reasons including ballot design, 
lack of information, and the complexity of choices facing the voter in a given 
election \citep{wattenberg00}. In the non-partisan context of judicial elections, 
there is evidence that rolloff is lessened in competitive races where information 
is increased \citep{streb09}.\footnote{For further details on how undervote was 
calculated and the imputation methods used for estimating rolloff in districts 
without a top ticket race, see Section \ref{subsec:undervote} in Chapter \ref{chap:wisco}}

% Citations on rolloff 

\subsection{Key Independent Variables}

<<modelsetup>>=
races <- as.data.frame(races)
races.tmp <- merge(races, VAP_dist, by = c("distid", "year"))

presTurn$presTwoPartyVote <- presTurn$presDemVotes + presTurn$presRepVotes
presTurn$presTwoPartyShareDem <- presTurn$presDemVotes / presTurn$presTwoPartyVote

govTurn$govTwoPartyVote <- govTurn$govDemVotes + govTurn$govRepVotes
govTurn$govTwoPartyShareDem <- govTurn$govDemVotes / govTurn$govTwoPartyVote


# turnout over the prior presidential election
races.tmp <- merge(races.tmp, presTurn, by = c("distid", "year"), all.x=TRUE)
races.tmp <- merge(races.tmp, govTurn, by = c("distid", "year"), all.x=TRUE)

races.tmp <- subset(races.tmp, select = c("distid", "year", "raceid2", "ncand", 
                                          "nrealcand", "nwins", "ninc", "raceid",
                                          "nminor", "votes", "districtwide", 
                                          "electiontype", "VAP", "VAP_adj", 
                                          "topPresVotesPrior", "presTwoPartyShareDem", 
                                          "topGovVotesPrior", "govTwoPartyShareDem"))

races.tmp <- subset(races.tmp, raceid!=0)
# look at general
races.tmp <- subset(races.tmp, electiontype == 1)

# Look at districtwide only
races.tmp <- subset(races.tmp, districtwide == 1)
races.tmp <- subset(races.tmp, nrealcand > 0)
races.tmp <- subset(races.tmp, nwins > 0)

races.tmp <- races.tmp[!is.na(races.tmp$distid),]
races.tmp$voters <- races.tmp$votes / races.tmp$nwins
races.tmp$turnout <- races.tmp$voters/races.tmp$VAP_adj
## Convert to district average somehow

dist_turn <- ddply(races.tmp, .(distid, year), summarise, 
              ncand = sum(ncand), nrealcand = sum(nrealcand), 
              nwins = sum(nwins), ninc = sum(ninc), 
              nminor = sum(nminor), votes = sum(votes), 
              VAP_adj = statamode(VAP_adj), 
              nraces = length(distid))

dist_turn$districtwide <- 1
############
# Non district-wide
############
races <- as.data.frame(races)
races.tmp <- merge(races, VAP_dist, by = c("distid", "year"))

races.tmp <- subset(races.tmp, select = c("distid", "year", "raceid2", "ncand", 
                                          "nrealcand", "nwins", "ninc", "raceid",
                                          "nminor", "votes", "districtwide", 
                                          "electiontype", "VAP_adj"))

races.tmp <- subset(races.tmp, raceid!=0)
# look at general
races.tmp <- subset(races.tmp, electiontype == 1)
# Look at non-districtwide only
races.tmp <- subset(races.tmp, districtwide == 0)
races.tmp <- subset(races.tmp, nrealcand > 0)
races.tmp <- races.tmp[!is.na(races.tmp$distid),]

# collapse to the district level

dist.tmp <- ddply(races.tmp, .(distid, year), summarise, 
              ncand = sum(ncand), nrealcand = sum(nrealcand), 
              nwins = sum(nwins), ninc = sum(ninc), 
              nminor = sum(nminor), votes = sum(votes), 
              VAP_adj = statamode(VAP_adj), 
              nraces = length(distid))

dist.tmp$districtwide <- 0

dist_turn <- rbind(dist_turn, dist.tmp)

row_counts <- ddply(dist_turn, .(distid, year), nrow)
dist_turn <- merge(dist_turn, row_counts, all.x=TRUE)
dist_turn$recs <- dist_turn$V1; dist_turn$V1 <- NULL
dist_turn1 <- dist_turn[dist_turn$recs >= 1 & dist_turn$districtwide > 0,]
dist_turn2 <- dist_turn[dist_turn$recs == 1 & dist_turn$districtwide == 0,]

dist_turn <- rbind(dist_turn1, dist_turn2)
dist_turn$recs <- NULL

## Clean up metrics
# turnout over the prior presidential election
dist_turn <- merge(dist_turn, presTurn, by = c("distid", "year"), all.x=TRUE)
dist_turn <- merge(dist_turn, govTurn, by = c("distid", "year"), all.x=TRUE)
dist_turn$VAP_adj <- as.numeric(dist_turn$VAP_adj)
dist_turn$voters <- dist_turn$votes / dist_turn$nwins
dist_turn$turnout <- dist_turn$voters / dist_turn$VAP_adj
# Fall turnout 
dist_turn$fallTurnout <- (dist_turn$topGovTurnoutPrior + dist_turn$topPresTurnoutPrior) / 2
dist_turn$fallTwoPartyShareDem <- (dist_turn$govTwoPartyShareDem + dist_turn$presTwoPartyShareDem) /2

rm(dist_turn1, dist_turn2, races.tmp, row_counts)
@

<<turnoutComparison, echo=FALSE, fig.cap="Comparison of Fall and Spring Turnout in Wisconsin Elections">>=

qplot(fallTurnout, turnout, data = na.omit(dist_turn[dist_turn$turnout < 0.95,])) + facet_wrap(~year) + 
  geom_smooth(se = TRUE, method = "lm") + theme_dpi() + 
  scale_x_continuous(label = percent) + 
  scale_y_continuous(label = percent) + 
  labs(x = "Average Fall Turnout Pres and Gov", y = "School Board Turnout", 
       title = "Comparing Fall and Spring Turnout in Wisconsin Elections")
@


<<partyDivision, echo=FALSE, fig.cap="Comparison of School Board Turnout to Electorate Polarization">>=

qplot(fallTwoPartyShareDem, turnout, data = na.omit(dist_turn[dist_turn$turnout < 0.95,])) + facet_wrap(~year) + 
  geom_smooth(se = TRUE) + theme_dpi() + 
  scale_x_continuous(label = percent) + 
  scale_y_continuous(label = percent) + 
  labs(x = "Democrat Share of Two Party Gubernatorial and Presidential Vote", y = "School Board Turnout", 
       title = "Turnout and Voter Partisanship")
@

<<turnoutCompetitive, echo=FALSE, fig.cap="Turnout in School Board Elections based on Contestation">>=
dist_turn$contestINC[dist_turn$nrealcand <= dist_turn$nwins & dist_turn$ninc == 0] <- "Open Uncontested"
dist_turn$contestINC[dist_turn$nrealcand <= dist_turn$nwins & dist_turn$ninc > 0] <- "Incumbent Uncontested"
dist_turn$contestINC[dist_turn$nrealcand > dist_turn$nwins & dist_turn$ninc > 0] <- "Incumbent Contested"
dist_turn$contestINC[dist_turn$nrealcand > dist_turn$nwins & dist_turn$ninc ==0] <- "Open Contested"

dist_turn$incumbent <- "Open"
dist_turn$incumbent[dist_turn$ninc > 0] <- "Incumbent"
dist_turn$contest <- "Open"
dist_turn$contest[dist_turn$nrealcand > dist_turn$nwins] <- "Contested"


tempdf <- dist_turn[!is.na(dist_turn$turnout) & dist_turn$turnout < 0.95,]
qplot(turnout, data = tempdf, fill = contest, 
      color = I("gray90")) +  
  theme_dpi() + 
  facet_wrap(~contestINC, ncol = 1) +
  scale_x_continuous(label = percent) + 
  labs(x = "Turnout in School Board Elections", fill = "Type of Contestation", 
       y = "Count of Races",
       title = "Turnout and Race Typology in School Board Elections") + 
  theme(legend.position = c(0.8, 0.85))
rm(tempdf)

@

<<turnoutSize, echo=FALSE, fig.cap="Turnout in School Board Elections based on Electorate Size">>=

qplot(VAP_adj, turnout, data = na.omit(dist_turn[dist_turn$turnout < 0.95,])) + facet_wrap(~year) + 
  geom_smooth(se = TRUE, method = "rlm") + theme_dpi() + 
  scale_y_continuous(label = percent) + 
  scale_x_log10(label = comma)+
  labs(x = "Voting Age Population (log-scale)", y = "School Board Turnout", 
       title = "Comparing Turnout and Size of Electorate")
@


<<turnoutAutocorrelation, echo=FALSE, fig.cap="Turnout in School Board Elections based on Prior Turnout">>=
lg  <- function(x) c(NA, x[1:length(x)-1])
lg2 <- function(x) c(NA, NA, x[2:length(x) -2])

dist_turn$year <- as.numeric(dist_turn$year)
dist_turn.tmp <- dist_turn[, c("distid", "year", "voters", "turnout")]

dist_turn.tmp <- dist_turn.tmp[order(dist_turn.tmp$distid, dist_turn.tmp$year),]

dist_turn.tmp <- as.data.table(dist_turn.tmp)[, votersLag1:= lg(voters), by = "distid"]
dist_turn.tmp <- as.data.table(dist_turn.tmp)[, votersLag2:= lg2(voters), by = "distid"]
dist_turn.tmp <- as.data.table(dist_turn.tmp)[, turnoutLag1:= lg(turnout), by = "distid"]
dist_turn.tmp <- as.data.table(dist_turn.tmp)[, turnoutLag2:= lg2(turnout), by = "distid"]
dist_turn.tmp$voters <- NULL
dist_turn.tmp$turnout <- NULL
dist_turn.tmp <- as.data.frame(dist_turn.tmp)
dist_turn <- merge(dist_turn, dist_turn.tmp)
rm(dist_turn.tmp)

qplot(turnoutLag2, turnout, 
      data = na.omit(dist_turn[dist_turn$turnout < 0.9 & dist_turn$year > 2003 & 
                                 dist_turn$turnoutLag2 < 0.9,])) +
  facet_wrap(~year) + theme_dpi() + geom_smooth(method = 'rlm') + 
  scale_x_continuous(label = percent) + 
  scale_y_continuous(label = percent) + 
  labs(x = "Lagged School Board Turnout (2 year lag)", y = "School Board Turnout", 
       title = "Comparing Lagged Turnout")
@
% Turnout and group membership

<<unionInf, echo=FALSE, fig.cap="Turnout in School Board Elections based on School Staff Share">>=
dist_turn <- merge(dist_turn, distAttr, by = c("distid", "year"))

dist_turn$mergeKey <- FORMATdistid(dist_turn$distid)
dist_turn <- merge(dist_turn, ADMIN, by.x = c("mergeKey", "year"), 
                   by.y =c("DISTID", "YEAR"))
dist_turn$mergeKey <- NULL
dist_turn$DISTID <- NULL

dist_turn$teachShareofVoters <- round(dist_turn$FTE_TEACH,0) / dist_turn$VAP_adj
dist_turn$teachShareofVoters[!is.finite(dist_turn$teachShareofVoters)] <- 0
dist_turn <- as.data.table(dist_turn)[, teachShareofVotersLag1:= lg(teachShareofVoters), 
                                      by = "distid"]
dist_turn <- as.data.table(dist_turn)[, teachShareofVotersLag2:= lg2(teachShareofVoters), 
                                      by = "distid"]

dist_turn <- as.data.frame(dist_turn)

plotdf <- dist_turn[dist_turn$year > 2004, c("year", "teachShareofVoters", "turnout")]
plotdf <- na.omit(plotdf)

qplot(teachShareofVoters, turnout, 
      data = plotdf) + 
  geom_smooth(method="rlm") + theme_dpi() +
  facet_wrap(~year)+ 
  scale_x_continuous(label = percent) + 
  scale_y_continuous(label = percent) + 
  labs(x = "Teacher FTE as Share of VAP", y = "School Board Turnout", 
       title = "Turnout to Staff Share of School Board Electorate")

@

% Competitiveness

<<competition, fig.cap="Competitiveness and Turnout">>=
cand.tmp <- dat[dat$candidateid!=99 & dat$electiontype==1, ]
votes.tmp <- merge(cand.tmp, 
                   as.data.frame(races)[races$nwins >0, 
                  c("raceid2", "votes", "districtwide", "ninc",
                    "nminor","nwins", "ncand", "nrealcand")], 
                   by = c("raceid2"), suffixes = c(".cand", ".race"))

votes.tmp$vote_share <- votes.tmp$votes.cand / votes.tmp$votes.race
votes.tmp$vote_share[is.na(votes.tmp$vote_share)] <- 0
votes.tmp$hareQuota <- votes.tmp$votes.race / (votes.tmp$nwins + 1)

plotdf2 <- as.data.table(votes.tmp)[, list(cand = length(winner), 
                  distid = distid[1],
                  year = year[1],
                  winners = sum(winner),
                  votescast = sum(votes.cand, na.rm=TRUE),
                  minWinVotes = min(votes.cand[winner == 1], na.rm=TRUE),
                  maxLoseVotes = max(votes.cand[winner == 0], na.rm=TRUE),
                  winnerVotes = sum(votes.cand[winner == 1], na.rm=TRUE),
                  winshare = sum(vote_share[winner ==1], na.rm=TRUE),
                  totalvoteshare = sum(vote_share, na.rm=TRUE), 
                  hareQuotaDeltaWinners = mean(votes.cand[winner ==1] - hareQuota[winner==1])),
           by = c("raceid2")]

plotdf2$minWinVotes[!is.finite(plotdf2$minWinVotes)] <- 0
plotdf2$maxLoseVotes[!is.finite(plotdf2$maxLoseVotes)] <- 0
plotdf2$voteMargin <- plotdf2$minWinVotes - plotdf2$maxLoseVotes
plotdf2$blaisLago <- 100 * (plotdf2$voteMargin / plotdf2$votescast / plotdf2$winners)
plotdf2$hareQuota <- plotdf2$votescast / (plotdf2$winners + 1)
plotdf2$hareQuotaDelta2 <- plotdf2$winnerVotes - (plotdf2$hareQuota * plotdf2$winners)

plotdf2$closeRace <- 0
plotdf2$closeRace[plotdf2$blaisLago < 
                    quantile(plotdf2$blaisLago[plotdf2$blaisLago >0], 
                             breaks = c(0.25), na.rm=TRUE)] <- 1

errors <- subset(plotdf2, blaisLago < 0)

plot.tmp <- ddply(plotdf2, .(distid, year), summarise, 
                  races = length(distid), 
                  minBlaisLago = min(blaisLago, na.rm=TRUE), 
                  avgBlaisLago = mean(blaisLago, na.rm=TRUE),
                  minHareQuotaDelta = min(hareQuotaDelta2, na.rm=TRUE),
                  avgHareQuotaDelta = mean(hareQuotaDelta2, na.rm=TRUE),
                  closeRaces = sum(closeRace))

plot.tmp$minBlaisLago[!is.finite(plot.tmp$minBlaisLago)] <- 100
plot.tmp$avgBlaisLago[!is.finite(plot.tmp$avgBlaisLago)] <- 100
plot.tmp$minHareQuotaDelta[!is.finite(plot.tmp$minHareQuotaDelta)] <- NA
plot.tmp$avgHareQuotaDelta[!is.finite(plot.tmp$avgHareQuotaDelta)] <- NA
dist_turn <- merge(dist_turn, plot.tmp, all.x=TRUE)
rm(plot.tmp, plotdf2, votes.tmp, cand.tmp)

dist_turn$CLOSE <- factor(ifelse(dist_turn$closeRaces >0, "Competitive", "Not Competitive"))

qplot(minBlaisLago, turnout, data = dist_turn[dist_turn$turnout < 0.95 & !is.na(dist_turn$turnout) & dist_turn$minBlaisLago < 100 & 
  dist_turn$minBlaisLago > 0,]) +  
  theme_dpi() + geom_smooth(method = 'lm') +
  scale_y_continuous(label = percent, breaks = seq(0, 1, by = .10)) + 
  scale_x_sqrt(breaks = c(0, 2.5, 5, 7.5, 10, 25, 50, 75, 100)) + 
  labs(y = "Turnout in School Board Elections", 
       x = "Blais-Lago Quotient",
       title = "Turnout and Competitiveness in School Board Elections") 

@

I begin with the explanations in Table \ref{turnoutH} and explore them using the Wisconsin data. I start with the models based on electorate size and explore if at the  small electorate sizes common in school board elections there is evidence 
that voters are more likely to turnout than in larger school board races. Figure 
\ref{fig:turnoutSize} shows that there is a consistent negative relationship 
between electorate size and school board election turnout across the years of data 
available in Wisconsin. As population increases, Wisconsin school board 
elections have lower turnout with a correlation of 
\Sexpr{iNum2(cor(dist_turn$turnout, dist_turn$VAP_adj, use = "pairwise.complete.obs"))}. 
This conforms with the predictions of game-theoretic approaches which state that 
in a small electorate a voter can expect their vote to matter more in the outcome and 
thus increase the potential benefits associated with voting
\citep{Mueller3, aldrich1993, Downs57}. However, this does not represent a full test 
of this theory, as voters are also voting up ticket in statewide non-partisan races 
such as Supreme Court and State Superintendent, and school board turnout may be 
driven by these races.\footnote{They may not though because upticket races have 
a statewide electorate and little chance for influence by individual voters.} 

Having competitive races is critical in driving voter turnout, as voters have 
very little reason to vote if they are not presented with a meaningful choice \citep{Downs57}. 
Figure \ref{fig:turnoutCompetitive} shows voter turnout across the competitiveness typologies 
described in Chapter \ref{chap:wisco} with a clear pattern of higher turnout in races 
featuring an incumbent and a serious challenger. Open seats also appear to feature higher 
turnout than uncontested races. The turnout in uncontested races in the bottom panel 
is very likely being driven by the presence of other contested races on the ticket. 
Using a statistical model I explore this in greater detail below. 

A related measure of contestation is that higher turnout is expected when races 
are more competitive. Measuring competitiveness in conjunction 
with turnout is a difficult methodological task, but often some measure of the final 
election margin is used as a proxy for the pre-election competitiveness of the race 
anticipated by voters. Following the argument of \citet{cox88}, I avoid using the 
percentage margin of victory due to the fact that it shares a denominator with 
the dependent variable, voter turnout. Instead, I use the Blais-Lago quotient used in 
Chapters \ref{chap:wisco} and \ref{chap:candidacy} which uses the total votes cast 
as the denominator. Figure \ref{fig:competition} shows all the races for which 
records are available with the competitiveness measures on the x-axis and the 
turnout in the corresponding school board race on the y-axis. There is a very 
slight negative effect of less competitive (higher value on the X-axis) races on 
voter turnout.\footnote{This figure excludes races with turnout greater than 95\% 
which are likely due to extremely low numbers of voters or recording error.}
How informed voters are about the 
competitiveness of their school board races prior to the election is unclear. 
There are many reasons to believe voters have little to no pre-election information 
about the closeness of their board races -- due to a lack of polling information and the 
low-level campaigning common in school board races \citep{RefWorks:321, RefWorks:217, RefWorks:322}. 
However, the electorate in Wisconsin school board elections is very different than 
the fall partisan electorate, and evidence from other jurisdictions suggests such 
off-cycle local voters are much more engaged, informed, and politically active 
than general election voters \citep{oliver12}. 

Figure \ref{fig:turnoutAutocorrelation} explores how habit forming turnout may be 
in spring elections in school districts \citep{Plutzer2002}. Using a two-year lag 
of turnout, Figure \ref{fig:turnoutAutocorrelation} shows a consistently high 
positive correlation between lagged and current turnout, averaging 
\Sexpr{iNum2(cor(dist_turn$turnout, dist_turn$turnoutLag2, use = "pairwise.complete.obs"))}.\footnote{For a single year lag, the corresponding correlation is 
\Sexpr{iNum2(cor(dist_turn$turnout, dist_turn$turnoutLag1, use = "pairwise.complete.obs"))} and the 
year to year pattern is largely similar.} A robust linear model is used to show 
the smoothed relationship between lagged and current turnout. Of note is the pattern 
shift in both 2005 and 2011 where the correlation is more pronounced and turnout 
appears to be inflated. Figure \ref{fig:turnoutComparison} looks at this further 
yet by showing the relationship between the average of the turnout in the prior two 
fall elections for Governor and President compared to the current school board turnout. 
These correlate positively as well at a level of 
\Sexpr{iNum2(cor(dist_turn$turnout, dist_turn$fallTurnout, use = "pairwise.complete.obs"))}. 

With a reduced electorate, school board elections are an interesting case to study 
the role substantial interest groups can play in an election. \citet{Fowler2005} 
provides the premise that cohesive social groups can increase turnout by activating 
their members to vote. \citet{RefWorks:207} suggests that unionized teachers are 
just one such group and provides evidence of school board elections being influenced 
substantially by such groups. To evaluate this, Figure \ref{fig:unionInf} shows 
the turnout in the school board election compared to the percentage of the voting 
age population in the school district that are teacher currently licensed and 
employed in that school district.\footnote{This data comes from the DPI PI-1202 
Fall Staffing Report. Another measure, the share of electorate in the lagged or 
twice lagged school board turnout that is made of teachers will also be explored.
This comparison illustrates how large of a voting block a cohesive teacher union 
might estimate they possess based on the number of votes cast in previous elections.}
The relationship shown in Figure \ref{fig:unionInf} is not what theory would expect. 
Here a higher teacher share of the prior school board turnout is associated with depressed turnout rates, 
instead of elevated turnout. The average correlation across years is 
\Sexpr{iNum2(cor(dist_turn$teachShareofVoters, dist_turn$turnout, use = "pairwise.complete.obs"))}. 
I will pursue this finding further with statistical models, 
but it is worth noting that there may be limits on the impact social groups can have 
on driving up turnout before they capture the electorate and thus reduce competitiveness 
and turnout. In fact, for \citet{RefWorks:207} this would represent the ideal condition 
for a union, freeing their members from the need to be politically active and influencing 
the school board through the candidate recruitment and nomination process instead. 

% Here rewrite
% TODO: Fix paragraph about competitiveness
% Competitiveness has a very modest positive effect on turnout across 
% all observations

Figure \ref{fig:partyDivision} takes a different approach to this problem by looking 
at the information voters may have about their community -- the level of partisan 
polarization. Using the average Democratic share of the two-party vote from the prior 
Gubernatorial and Presidential election combined, I explore the variation in school board election 
turnout. Theory would suggest that the more divided a community is on partisan issues, the 
greater the impetus to vote \citep{Fowler2005}. Thus in Figure \ref{fig:partyDivision} we 
should expect to see an inverted U shape representing higher turnout around 50\% share of 
the two party vote. In fact, this pattern does not occur in any year, and in some years 
there is evidence of just the opposite relationship -- a correlation between higher 
partisan unity and turnout. Figure \ref{fig:partisan2} shows the linear relationship 
between higher partisan unity and turnout. In most years there is almost no relationship, 
but in 2011 and 2012 there appears to be an uptick in school board turnout associated 
with more strongly partisan school districts. The correlation is 
\Sexpr{iNum2(cor(dist_turn$turnout, abs(dist_turn$fallTwoPartyShareDem - .5), use = 'pairwise.complete.obs'))} across all years. 

<<partisan2, fig.cap="Another Look at Relationship Between Turnout and Partisanship">>=

qplot(abs(fallTwoPartyShareDem-.5), turnout, 
      data = dist_turn[dist_turn$turnout < 0.95 & !is.na(dist_turn$turnout) & dist_turn$year > 2003,]) + facet_wrap(~year) + 
  geom_smooth(se = TRUE, method = 'rlm') + theme_dpi() + 
  scale_x_continuous(label=percent) + 
  scale_y_continuous(label = percent) + 
  labs(x = "Partisan Unity", y = "School Board Turnout", 
       title = "Turnout and Voter Partisanship")

@

Taken alone, these figures do not suggest that any of the theories in Table \ref{turnoutH} are confirmed or denied, but it does help illustrate the diversity of school board 
elections in Wisconsin and the need for statistical models to help separate out 
competing explanations that may themselves be highly correlated or confound 
one another. 

\clearpage

\subsection{Control Variables}

In addition to the variables of interest shown above, it is necessary to include 
some common demographic control variables. Political scientists have long established 
the strong relationship between certain demographic characteristics and voter 
turnout in partisan elections. % CITENEEDED
In order to understand the effect of other variables on turnout, it is desirable to 
remove as many other explanations as possible given the availability of data. 
Fortunately, using US census data, an abundance of data is available on the 
population of Wisconsin school districts. 


<<demog1, fig.cap="Pairs Plot of Demographic Variables and Turnout in 2012", fig.height = 8, fig.width=8>>=
library(GGally)
dist_turn$median_incomeLOG <- log(dist_turn$median_income)
pairLabels <- c("Turnout", "Fall Turnout", "% 65 Older", "% Bach. +", "OOH %", 
                "Median Income", "Log VAP")
tmpdf <- dist_turn[dist_turn$turnout < 0.95 & 
                            dist_turn$year == 2012 & 
                            !is.na(dist_turn$turnout), ]
tmpdf <- tmpdf[, c("turnout", "fallTurnout", "per65o", "PerBachelorOrAbove", 
                   "OOH_share", "median_incomeLOG", "VAP_adj")]

tmpdf$VAP_adj <- log(tmpdf$VAP_adj)
ggpairs(tmpdf, 
        columnLabels = pairLabels,
        lower = list(continuous = "smooth"), 
        upper = list(continuous = 'cor'), 
        title = "Pairs Plot of Key Control Variables")
rm(tmpdf)
@

Figure \ref{fig:demog1} uses a ``pairs plot" to examine the relationships between 
these dependent variables and the outcome for the year 2012. This shows a series 
of scatterplots relating the two variables, as well as the distribution of each 
variable, and the pairwise correlation of the variables in the upper diagonal. 
Turnout is indeed positively correlated with all of these demographic controls, except 
district size, to differing degrees. There are also strong relationships between these individual demographic categories, with particularly strong relationships between education, age, and income, as well as a strong negative between age and owner occupied housing and age and education level.\footnote{This pairs plot is produced using the \texttt{GGally} package in R \citep{ggally}.} 

The strongest correlations are among income, percentage of population over 65, and 
percentage of owner occupied housing -- these variables are negatively correlated. 
Turnout only has a weak correlation with these measures. It is important to 
note that all of these variables are much more highly correlated with fall 
turnout than with spring turnout. This provides some evidence that the school 
board electorate is different than the general election electorate -- a finding 
previously shown by \citet{oliver12}. 

\clearpage
\section{Methods}

This paper has two main methodological approaches to evaluating theories of voter 
turnout in school board elections. The first follows on several empirical studies 
of theories of voter turnout to compare the power of various theories of voter 
turnout to one another \citep{Larcinese, Lapp99, KanYang2001,Coate2008582}. The 
second approach investigates more narrowly the gap between voters voting at the 
top of the spring election ticket, and votes for school board. While overall 
spring election turnout may be driven by the presence of a partisan primary 
or a non-partisan statewide election, the gap between votes cast in that election 
and the school board election narrowing should be attributed to increased interest 
by voters in school board elections. 

\subsection{Estimation Equations}

In my first set of models I look for evidence that the explanations described in Table 
\ref{turnoutH} for voter turnout in elections are supported in the data 
available on Wisconsin school boards. In the second case, I change my dependent variable to be the distance between the turnout for 
the school board races in a school district, and the top non-partisan statewide 
race in the district. In each case, I start with a specification that pools 
observations across years and districts and estimates the impact of the key independent 
variable and a few key demographic control variables described in Section 
\ref{sec:turnData}. These equations look like: 

\[(1) \hspace{0.4 in} VP_{t} = \alpha + \beta X_{t} + \psi Z_{t}+\epsilon_{t} \] \\

Here $VP_{t}$ is voter turnout in the spring election $t$. $\alpha$ is the intercept and $X_{t}$ 
represents a vector of covariates including the control variables described 
above for school district $i$. All models control for competition, demographic 
covariates, district size, and whether or not turnout was measured by a district 
wide race.\footnote{The districtwide variable is a dummy variable to control for the 
measurement error associated with school districts where there was no district wide 
race to estimate voter turnout in board elections from.} I include the term $Z_{t}$ to represent the variable 
of interest in each model. 

The size of the electorate is important in many theories of voter turnout. 
\citet{dahl1973size} first hypothesized that the motivation to participate would be higher in small electorates, and there has been some evidence to support this \citep{Frandsen2002}. Thus, in all models size is included in the $X_{t}$ vector and in 
some models it is included as an interaction to test for differential impacts 
of key variables across the size of the electorate. 

The $Z_{t}$ vector includes different variables across the different models including 
lagged turnout, district size, race competitiveness, and social group membership in the school district. For example, a high predictive value of lagged turnout would suggest the electorate is habit forming -- especially if the effect is magnified in smaller districts\citep{habit02}.

The pivotal-voter model I test next uses a similar method as \citet{Coate2008582}. 
The pivotal-voter model predicts that turnout should be higher in elections that 
are closer and that this effect should be greater in smaller electorates.
Thus I include in the $Z_{t}$ vector a measure of the margin of victory. I also 
include an interaction effect to explore whether or not voters are more likely 
to turn out for close races in small electorates, where their $P$, probability of 
deciding the election, is greatest. In a game-theoretic perspective, the smaller electorate would drive turnout because the costs of non-voting can be more easily estimated by voters in small electorates, and the expected benefit of such 
non-voting is smaller. This interaction model is represented in equation 2. 

\[(2) \hspace{0.4 in} VP_{t} = \alpha + \beta X_{t} + \psi Z_{t} x \lambda S_{t} +
\epsilon_{t} \] \\

Finally, following \citet{Fowler2005}, I investigate the impact that social group 
membership may have on voting by this time including a measure of the size of the 
social group in the community in the $Z_{t}$ vector. I explore a separate model 
for each type of social group -- the partisanship of the school district in partisan statewide elections, or the share of the total electorate that is teachers. There 
has been little work explicitly testing the influence of political parties in 
non-partisan school board races, but some evidence that the 
share of teachers in the electorate is an important driver of turnout and 
policy change in school board elections \citep{RefWorks:207, 
RefWorks:218,RefWorks:320}. 

\subsection{Model Specifications}
\label{subsec:spec}
The equations represented above are stylized representations of simple OLS models 
that treat each district-year as an independently distributed observation. In 
reality, the data is more complex and requires some additional model features 
to appropriately estimate the impact of key variables on turnout. I outline 
two separate methods. 

The first method is a simple extension of the pooled linear regression 
model that includes fixed effects for years and for school districts. This 
eliminates time-invariant unobservable district characteristics as well as 
election specific unobservable characteristics between districts. However, 
the standard errors from these models are overly optimistic because each 
school district is observed between two and ten times and the assumption of independent 
and identically distributed random variables is violated. To correct for this, 
I adjust the standard errors by using the Huber-White estimator of the covariance 
matrix through the \texttt{robcov} function implemented in \citet{rms}'s \texttt{rms} 
package. This will correct for the clustering of school districts
between the observations and avoid overly optimistic standard errors for 
the $\beta$ coefficients \citep{hwhite,hwhite2,pjhuber}.

Results from these models are placed in Appendix \ref{sec:appendixT}. 
However, there are many reasons to doubt the validity of the fixed effect 
specification. First, the district fixed effects are overly conservative as 
many of the key underlining predictors are not highly variable year to year 
within districts and number of observations per district varies. The district 
estimates themselves are problematic, the model is likely underpowered to fit 
them properly and they are likely too sensitive to outliers and therefore overfit. 
There are two approaches to adjusting for this -- penalized estimation or partial 
pooling approach using a mixed effect model. With over 300 grouping parameters 
to estimate, it is better to turn to a partial pooling approach that allows 
estimates of the district effect to be shrunk toward the pooled grand estimate 
in order to avoid overfit. A partial pooling approach is also known as a mixed 
effect or hierarchical linear model (HLM). Partial pooling models can be fit in R 
using the \texttt{lme4} package \citep{lme4, gelhill}. I employ the same 
specification as the fixed effect model before, but now model the district effects 
as random effects in order to avoid overfit. 

This multilevel approach is not common in longitudinal applications in political science, but has been used by \citet{oliver} to understand the relationship between 
individual survey respondents and their communities in a study of local elections. 
The choice between these two approaches is as much theoretical as it is econometric, 
and as a result I run my analyses with both approaches.\footnote{The Hausman test 
can be used to formally test the specification of random or fixed effects and the 
results of this test for all models is included in the Methodological Appendix 
\ref{sec:appendixT} \citep{haustest}.} The formal econometric results suggest 
that the random effects of the multilevel model are appropriate. 
It is also useful because this approach is flexible for cases with unbalanced 
repeated measures and allows the analyst to disentangle the effects of time 
specific variables from the overall variability among individual units, e.g. school 
districts \cite{mlmod,raudbryk}. Furthermore, my data does not 
include all Wisconsin school districts, but instead a large sample of districts. 
This makes the ability to model the variation between districts of interest to 
understand the range of plausible district variation across the broader population 
of school districts. 

The equation below depicts the multilevel framework:

\begin{align*} 
VP_{i} &= \alpha + \gamma_{j} + \beta X_{ij} + \lambda Z_{ij} + \epsilon_{ij}  \\ 
\gamma_{j} &=  \alpha_{j} + \epsilon_{j}
\end{align*}

The only difference between this approach the linear models with equations above 
is the presence of a unique intercept for each school district \emph{j}. 
Here the $\gamma_{j}$ terms represent independent intercepts for each school 
district as predicted by $\alpha_{j}$, a unique intercept for each school district. 
$X_{ij}$ is a vector of time variant school district 
characteristics such as prior turnout. In the mixed-effect 
framework the $\gamma_{j}$ are assumed to be drawn from a normal distribution that 
is explained by the linear combination of $\alpha$ and $\zeta$. The equation above 
is flexible to the inclusion of the other predictors identified. 

This method does not account for the time structure of the data, as no 
explicit parameterization of time is included. As I have no reason to believe that 
time linearly related to voter turnout, this is 
appropriate. However, I do want to control for secular effects of election year 
variability that reaches across districts. One approach would be to include 
fixed effects for years in the $X$ vector. However, the multilevel approach is 
flexible enough to allow for a third group -- years, to be included in the model. 
The model below includes a third grouping level for years. 

\begin{align*} 
VP_{t} &= \alpha + \gamma_{j} + \psi{t} + \beta X_{ijt} + \lambda Z_{ijt} + \epsilon_{ijt}  \\ 
\gamma_{jt} &=  \alpha_{j} + \epsilon_{j} \\
\psi{t} &= \alpha_{t} + \epsilon_{t}
\end{align*}

This approach allows year parameters to be estimated independently without assuming 
a functional form for the relationship between voter turnout and time allowing for 
the model to reflect secular effects of specific elections in the data. 

The proper model of the random effects is important. Using the \texttt{RLRsim} 
package in R, I test the specification of the random effects using an exact 
likelihood ratio test and an exact restricted likelihood ratio test \cite{RLRsim}. 
The first test is used to examine whether the random effects are the appropriate 
specification. The restricted likelihood ratio test is used to compare 
two nested models with different random effect specifications to determine the 
appropriate specification. In this case, a model with random effects for district 
and year was compared against a model with random effects only for district. The 
results of these tests for all of the models is included in the Appendix \ref{sec:appendixT}. 

\subsection{Computation}

%Demonstrate outliers
% Talk about penalized maximum likelhood
% Bayesian and tobit regression options

<<simpleModel, fig.cap="Regression Diagnostics for A Simple Multiple Regression", fig.height=9>>=
dist_turn$VAP_adjLOG <- log(dist_turn$VAP_adj)
# 
# policyIdx <- c("NEW_SUP", "MATH_PROFADV_PER", "READ_PROFADV_PER", "debtFail", 
#                "overrideFail", "overrideQues", "debtQues", "NonPublicPupilPer", 
#                "ADMIN_SHARE", "ADMIN_SHARE_COMP", "debtPass", "overridePass",
#                "DEBT_ATTEMPT_CUMUL93", "OVERRIDE_ATTEMPT_CUMUL93", 
#                "SUP_TURNOVER_PRIOR_YEAR")
# 
# demogIdx <- c("per_white_all", "median_incomeLOG", "per65o", "VAP_adjLOG", 
#               "OOH_share", "PerBachelorOrAbove", "publicPupilCountLOG", 
#               "econ_disadv_per", "NonWhitePublicPupilPer")
# 
# fiscalIdx <- c("PROPERTYTAX_REV_SHARE", "balance_member_lag", "TCEC_MEMBER", 
#                "TEC_MEMBER", 
#                "NonSDMill", "millrate", "schoolMillShare", "millrate_delta", 
#                "total_cat_aids_member", "teachSalDiff", "eqv_taxfiler")
# 
# politicIdx <- c("recentTwoPartyShareDem", "incumRun", "nraces", 
#                 "partyDivisionRecent", "nwins", "teachShareofVoters", 
#                 "overrideYesPer", "fallTurnout")

moddat <- dist_turn[, c("turnout", "turnoutLag2", "turnoutLag1","year", "contest",
                        "fallTurnout", "VAP_adjLOG", "distid", "districtwide",
                        "per_white_all", "per65o", "PerBachelorOrAbove", "OOH_share", 
                        "median_incomeLOG", "minBlaisLago", "contest")]
#moddat <- na.omit(moddat)
moddat <- subset(moddat, turnout < 0.95,)
moddat <- moddat[order(moddat$distid, moddat$year),]
moddat$distid <- factor(moddat$distid)
moddat$year <- factor(moddat$year)
moddat$contest <- factor(moddat$contest)
moddat$turnout <- moddat$turnout * 100
moddat$districtwide <- factor(moddat$districtwide)
moddat$VAP_adjLOG_sq <- moddat$VAP_adjLOG^2

nums <- sapply(moddat, is.numeric)
ScaleMeans <- apply(moddat[, nums], 2, mean, na.rm=TRUE)
ScaleSD <- apply(moddat[, nums], 2, sd, na.rm=TRUE)
moddatScaleLag <- cbind(ScaleMeans, ScaleSD); rm(ScaleMeans, ScaleSD)
#Rescale
library(arm)
nums <- sapply(moddat, is.numeric)
moddat[, nums] <- apply(moddat[, nums], 2, rescale)


naive1 <- lm(turnout ~ turnoutLag2 + fallTurnout + VAP_adjLOG + VAP_adjLOG_sq + 
               per_white_all + per65o + PerBachelorOrAbove + OOH_share + 
               median_incomeLOG + districtwide + minBlaisLago,
             data = moddat)

autoplot(naive1)

@

Diagnostics from the simple pooled linear regression without fixed effects or 
clustered standard errors are shown in Figure \ref{fig:simpleModel}. The key result 
here is that there are a number of high leverage 
observations that appear to be extreme outliers. Additionally, the upper left 
quadrant of Figure \ref{fig:simpleModel} suggests the presence of some level of 
heteroskedacticity in the results, a likely result of the clustering and repeated 
observation features of the dataset. The upper right quadrant shows the QQ plot 
for this regression model which demonstrates that the model deviates from normality 
quite substantially. I investigate this further by looking for extreme outliers 
in the turnout variable. 

<<outlierdetect, results='hide'>>=
centr <- mean(moddat$turnout)
stddev <- sd(moddat$turnout)
moddat$outflag <- (moddat$turnout - centr) / stddev
@

There are \Sexpr{table(moddat$outflag>5)[[2]]} cases where 
the value of the dependent variable is more than five standard deviations above 
the group average. This is less than half of 1\% of the observations and is unlikely 
to be influential, however, it is also likely that such deviations are due to 
measurement error either in the VAP denominator or in the aggregation of district 
board election vote counts themselves. Due to the suspicion of measurement issues 
in the key estimate of turnout, I use the approach taken by \citet{berry2} on 
administrative data and exclude all observations that fall outside of five standard 
deviations of the normal values for the dependent variable. Additionally, I 
grand-center and rescale all of my continuous variables in order to speed model 
convergence and avoid computational problems associated with widely varying scales 
in the underlying data. The coefficients reported in the tables below then can be 
interpreted as the effect on the dependent variable in standard deviation terms 
of moving the predictor variable two standard deviations. This standardized 
regression approach is recommended in multilevel modeling, particularly in cases 
with underlying predictors with scales that vary by orders of magnitude like in 
the present case \citep{gelhill}. 

\clearpage
\section{Results}

I now review the results for models for all of the theories discussed above -- 
habit forming voters, rational voters, pivotal voters, and social group motivated 
voters. I fit both a fixed-effect OLS regression and a mixed-effect linear 
model for each of these theories including control variables and the key predictors. 
I fist look at evidence for these theories in each of these models for an effect 
on turnout in the spring school board races. Then I apply these same models to 
the rolloff of voters in the spring election. Finally, I conclude by interpreting 
the substantive effect of these variables to weigh how large the effects of 
these characteristics might be on school board election turnout. 

\subsection{Habit Forming Voters}

<<lagmodRLM, results ='hide'>>=
# detach("package:plyr", unload=TRUE)
library(sandwich)
library(rms)
library(devtools)
install_github("jknowles/apsrtable", subdir = "pkg", ref = "dev")
library(apsrtable)
moddat <- moddat[moddat$outflag <= 5 & moddat$outflag >= -5,]
moddat <- moddat[moddat$year != "2002",]
moddat$year <- factor(as.character(moddat$year))
dd <<- datadist(moddat)
options(datadist="dd")

dumbRLM1 <- ols(turnout ~ turnoutLag2 + fallTurnout + VAP_adjLOG + VAP_adjLOG_sq + 
                  per_white_all + 
                       per65o + PerBachelorOrAbove + OOH_share + median_incomeLOG + 
               districtwide +  minBlaisLago, data = moddat, x = TRUE, y = TRUE)

dumbRLM1$se <- sqrt(diag(vcov(robcov(dumbRLM1, cluster = moddat$distid))))

dumbRLMbest <- ols(turnout ~ turnoutLag2 + fallTurnout + VAP_adjLOG +
                     VAP_adjLOG_sq + per_white_all + per65o + PerBachelorOrAbove +
                     OOH_share + median_incomeLOG + districtwide +  
               minBlaisLago + factor(year) + factor(distid), data = moddat, x= TRUE, y = TRUE)

dumbRLMbest$se <- sqrt(diag(vcov(robcov(dumbRLMbest, cluster = moddat$distid))))
dumbRLM2 <- ols(turnout ~ turnoutLag2 + VAP_adjLOG + VAP_adjLOG_sq + 
                  per_white_all + per65o + PerBachelorOrAbove +  OOH_share+
                  median_incomeLOG + districtwide + minBlaisLago + factor(year) + 
                  factor(distid), data = moddat, x = TRUE, y = TRUE)
dumbRLM2$se <- sqrt(diag(vcov(robcov(dumbRLM2, cluster = moddat$distid))))

stars.note <- apsrtable:::stars.note
se.note <- apsrtable:::se.note

coefnamesLag <- c("Intercept","Lagged Turnout (2)", "Fall Turnout", "ln(VAP)", 
                  "$ln(VAP)^{2}$", "\\% White", 
                  "\\% Over 65", "\\% Bach. +", "\\% OOH", 
                  "ln(MedianIncome)", "District-wide", "Blais-Lago")

lagmodTab <- apsrtable(dumbRLM1, dumbRLMbest, dumbRLM2, se="robust", 
          label="tab:lagmods", 
          model.names=c("Simple RLM",  "Interaction", 
                        "RLM + District FE"), 
          order = "longest",
          caption = "Models of Lagged Turnout in School Board Elections",
          notes = list("Standard errors clustered at the school district.", 
                       stars.note, 
                       "Year and district fixed effects omitted in models 2 and 3."),
          omitcoef=list("distid", 
                        expression(grep("distid", coefnames, value=TRUE)), 
                        "year", 
                        expression(grep("year", coefnames, value = TRUE))), 
          Sweave=FALSE, coef.names = coefnamesLag,
          float = "sidewaystable")

@

Table \ref{tab:meTurnout} confirms the theoretical expectations from above to a 
large extent. The higher the prior school board election turnout, the higher 
the turnout in the current school board election. The effect is largely the same 
even when controlling for fall turnout and the competitiveness of the races. 
Additionally, as expected, larger districts have lower turnout. Other variables 
are also as expected with more affluent, older, and more educated communities 
showing higher voter turnout in school board elections. These effects are reduced 
once controlling for fall turnout due to the strong relationship between them 
and fall turnout previously noted.\footnote{These relationships are slightly 
different in the fixed effect models in the appendix.}

An additional benefit of the random effect specification is that it allows me to 
measure the variation between years and between districts. As Table 
\ref{tab:meTurnout} shows, there is substantial between district and across year 
variation in turnout for spring non-partisan school board elections. 

% Footnote about fixed effect models
% in non district fixed effects, relationship is same with lag1 and lag2
% District FE sign reverses and lagged turnout is related to negative turnout
%% Reversion to the mean, small within district differences, small within district samples
%% Lose a lot of statistical significance because the models seem to fall apart

<<model1robustness>>=
dumbRLM1b <- ols(turnout ~ turnoutLag2 + fallTurnout + VAP_adjLOG + VAP_adjLOG_sq + 
                  per_white_all + 
                       per65o + PerBachelorOrAbove + OOH_share + median_incomeLOG + 
               districtwide +  minBlaisLago, data = moddat, x = TRUE, y = TRUE)

dumbRLM1b$se <- sqrt(diag(vcov(robcov(dumbRLM1, cluster = moddat$distid))))

dumbRLMbestb <- ols(turnout ~ turnoutLag2 + fallTurnout + VAP_adjLOG +
                     VAP_adjLOG_sq + per_white_all + per65o + PerBachelorOrAbove +
                     OOH_share + median_incomeLOG + districtwide +  
               minBlaisLago + factor(year) + factor(distid), data = moddat, x= TRUE, y = TRUE)

dumbRLMbestb$se <- sqrt(diag(vcov(robcov(dumbRLMbest, cluster = moddat$distid))))
dumbRLM2b <- ols(turnout ~ turnoutLag2 + VAP_adjLOG + VAP_adjLOG_sq + 
                  per_white_all + per65o + PerBachelorOrAbove +  OOH_share+
                  median_incomeLOG + districtwide + minBlaisLago + factor(year) + 
                  factor(distid), data = moddat, x = TRUE, y = TRUE)
dumbRLM2b$se <- sqrt(diag(vcov(robcov(dumbRLM2, cluster = moddat$distid))))
stars.note <- apsrtable:::stars.note
se.note <- apsrtable:::se.note
coefnamesLag2 <- c("Intercept","Lagged Turnout (1)", "Fall Turnout", "ln(VAP)", 
                  "$ln(VAP)^{2}$", "\\% White", 
                  "\\% Over 65", "\\% Bach. +", "\\% OOH", 
                  "ln(MedianIncome)", "District-wide", "Blais-Lago")
appA1 <- apsrtable(dumbRLM1b, dumbRLMbestb, dumbRLM2b, se="robust", 
          label="tab:lagmods2", 
          model.names=c("Simple",  "Dist/Year FE", 
                        "Dist/Year FE"), 
          order = "longest",
          caption = "Models of Lagged Turnout in School Board Elections",
          notes = list("Standard errors clustered at the school district.", 
                       stars.note, 
                       "Year and district fixed effects omitted in models 2 and 3."),
          omitcoef=list("distid", 
                        expression(grep("distid", coefnames, value=TRUE)), 
                        "year", 
                        expression(grep("year", coefnames, value = TRUE))), 
          Sweave=FALSE, coef.names = coefnamesLag2,
          float = "sidewaystable")
@

\begin{tiny}
<<lagModMM, results ='asis'>>=
library(lme4)

mixedModlags <- lmer(turnout ~ turnoutLag2 +  VAP_adjLOG + 
                    per_white_all + 
                       per65o + PerBachelorOrAbove + OOH_share + median_incomeLOG + 
               districtwide + 
               minBlaisLago + (1|year) + (1|distid), 
              data = moddat, REML = FALSE)

mixedMod1lagsb <- lmer(turnout ~ turnoutLag2 + fallTurnout + VAP_adjLOG + VAP_adjLOG_sq +
                    per_white_all + 
                       per65o + PerBachelorOrAbove + OOH_share + median_incomeLOG + 
               districtwide + 
               minBlaisLago + (1|year) + (1|distid), 
              data = moddat, REML = FALSE)

coefnamesLag3 <- c("Intercept","Lagged Turnout (2)", "ln(VAP)", 
                 "\\% White", 
                  "\\% Over 65", "\\% Bach. +", "\\% OOH", 
                  "ln(MedianIncome)", "District-wide", "Blais-Lago", 
                  "Fall Turnout",  "$ln(VAP)^{2}$")
tabnote <- "Model includes both year and district random effects modeled as intercepts."

apsrtable(mixedModlags, mixedMod1lagsb, caption = "Partial Pooling Model of Lagged Turnout",
          model.names = c("No Fall Turnout", "Fall Turnout"), 
            label = "tab:meTurnout",  
           notes = list("All variables grand-mean scaled and centered.", 
                       stars.note), 
          Sweave = FALSE, digits = 3, coef.names = coefnamesLag3)
@
\end{tiny}


<<laggedTurnSens, results='hide', eval=TRUE>>=
library(RLRsim)
# m0 <- lm(turnout ~ turnoutLag2 + fallTurnout + VAP_adjLOG + 
#                     per_white_all + turnoutLag2 * VAP_adjLOG + 
#                        per65o + PerBachelorOrAbove + OOH_share + median_incomeLOG + 
#                districtwide + 
#                minBlaisLago, 
#          data = moddat) # fit the null model
# 
# exactLRT(m = mixedMod1, m0 = m0)

# Test for year specific slopes
m.slope <- update(mixedMod1lagsb, . ~ . - (1|year))
m0 <- update(mixedMod1lagsb, . ~ . - (1|distid))
lagLRT <- exactRLRT(m.slope, mixedMod1lagsb, m0)
lagLRT$callFull <- mixedMod1lagsb@call
lagLRT$callSmall <- m.slope@call
@

\subsection{Rational Voters}

My second empirical question was to examine the relationship between electorate size 
and turnout, and electorate size, margin of victory and turnout. I use an adjusted estimate 
of the voting age population - the denominator in the turnout variable - to serve as 
an estimate of the electorate size.\footnote{Address possible endogeneity here with 
the dependent variable.} This is a conservative estimate of the actual electorate 
size in school board elections, which as can be as low as 15\% of the voting 
age population. If is is assumed that voters adjust the electorate size equally across jurisdictions 
when making their assessment of the perceived uiltity of voting, then this is not a factor. 
If there is evidence that voters in different jurisdicstions have more information about the 
likely electorate size in a school board election, and this varies across jurisdictions, 
then this becomes more problematic. 

<<closeModRLM, results ='asis'>>=
moddat <- dist_turn[, c("turnout", "turnoutLag2", "year", "fallTurnout", 
                        "VAP_adjLOG", "distid", "incumbent",
                        "per_white_all", "per65o", "PerBachelorOrAbove", 
                        "OOH_share", "median_incomeLOG", "districtwide", 
                        "contest", "minBlaisLago")]
moddat <- na.omit(moddat)
moddat <- moddat[order(moddat$distid, moddat$year),]
moddat <- moddat[order(moddat$distid, moddat$year),]
moddat$distid <- factor(moddat$distid)
moddat$year <- factor(moddat$year)
moddat$turnout <- moddat$turnout * 100
moddat$districtwide <- factor(moddat$districtwide)
moddat$contest <- factor(moddat$contest)
moddat$VAP_adjLOG_sq <- moddat$VAP_adjLOG^2
centr <- mean(moddat$turnout)
stddev <- sd(moddat$turnout)
moddat$outflag <- (moddat$turnout - centr) / stddev
moddat <- moddat[moddat$outflag <= 5 & moddat$outflag >= -5,]

nums <- sapply(moddat, is.numeric)
ScaleMeans <- apply(moddat[, nums], 2, mean, na.rm=TRUE)
ScaleSD <- apply(moddat[, nums], 2, sd, na.rm=TRUE)
moddatScaleClose <- cbind(ScaleMeans, ScaleSD); rm(ScaleMeans, ScaleSD)
nums <- sapply(moddat, is.numeric)
moddat[, nums] <- apply(moddat[, nums], 2, rescale)

dd <<- datadist(moddat)
options(datadist="dd")

closeRLM <- ols(turnout ~ VAP_adjLOG + per_white_all + 
                  per65o + PerBachelorOrAbove + OOH_share + median_incomeLOG +
                  districtwide + minBlaisLago, 
              data = moddat, x = TRUE, y = TRUE)

closeRLM$se <- sqrt(diag(vcov(robcov(closeRLM, cluster = moddat$distid))))
closeRLM2 <- ols(turnout ~ VAP_adjLOG + VAP_adjLOG_sq + per_white_all + 
                  per65o + PerBachelorOrAbove + OOH_share + median_incomeLOG +
                   districtwide + minBlaisLago + factor(year),
              data = moddat, x= TRUE, y = TRUE)
closeRLM2$se <- sqrt(diag(vcov(robcov(closeRLM2, cluster = moddat$distid))))
closeRLM3 <- ols(turnout ~ VAP_adjLOG + VAP_adjLOG_sq+ per_white_all + 
                  per65o + PerBachelorOrAbove + OOH_share + median_incomeLOG +
                   districtwide + incumbent + contest * VAP_adjLOG + factor(year) + factor(distid), 
              data = moddat, x = TRUE, y = TRUE)
closeRLM3$se <- sqrt(diag(vcov(robcov(closeRLM3, cluster = moddat$distid))))
closeRLM4 <- ols(turnout ~ VAP_adjLOG + VAP_adjLOG_sq+ minBlaisLago*VAP_adjLOG + per_white_all + 
                  per65o + PerBachelorOrAbove + OOH_share + median_incomeLOG +
                   districtwide + incumbent + minBlaisLago + factor(year) + factor(distid), 
              data = moddat, x = TRUE, y = TRUE)
closeRLM4$se <- sqrt(diag(vcov(robcov(closeRLM4, cluster = moddat$distid))))


closeCoefs1 <- c("Intercept", "ln(VAP)", 
                  "$ln(VAP)^{2}$", "\\% White", 
                  "\\% Over 65", "\\% Bach. +", "\\% OOH", 
                "ln(MedianIncome)", "District-wide", "No Incumbent",
                "Uncontested Seat", "VAP x Uncontested", 
                 "Blais-Lago", "VAP x Blais-Lago")

closeModTab <- apsrtable(closeRLM3, closeRLM4, se="robust", 
          label="tab:closemods", 
          model.names=c("RLM + District FE", "Interact + Year FE"), 
          caption = "Models of Competitiveness and Turnout in School Board Elections",
          notes = list(se.note, stars.note, "Year and district fixed effects omitted."),
          omitcoef=list("distid", 
                        expression(grep("distid", coefnames, value=TRUE)), 
                        "year", 
                        expression(grep("year", coefnames, value = TRUE))),
          coef.names = closeCoefs1,
          Sweave=FALSE)
@


<<cleanupa, echo=FALSE,results='hide'>>=
rm(ADMIN, VAP_dist, dist.tmp, dvp, errors, plotdf, presTurn, canInterp,
   canInterpIDX, centr, dumbRLM1, dumbRLM1b, dumbRLM2, dumbRLM2b, dumbRLMbest, 
   dumbRLMbestb, i, j)
@


Table \ref{tab:meClose} shows the partial-pooling results for two different 
models of competitiveness in school board elections. In the first model, races 
are coded as competitive following the schema in Chapter \ref{chap:candidacy} -- 
that is there are more serious candidates than seats available. In the second, I 
use the continuous measure of the Blais-Lago quotient to represent how competitive 
the races are, with a higher values corresponding to less competitive races. The 
control variables are the same from those in Table \ref{tab:meTurnout}. As 
expected, uncontested races have much lower turnout than contested races. Somewhat 
surprisingly, there is no detectable effect of incumbency on turnout. 

In the continuous model the Blais-Lago quotient is statistically significant and 
in the expected direction -- less competitive elections result in less turnout. 
However, the expectation that the relationship between competitiveness and district 
size would have an effect on turnout is not confirmed here - the interaction term 
is not statistically significant for either the uncontested dummy variable or the 
Blais-Lago quotient although it is in the right direction.\footnote{The fixed 
effect models are largely the same?}

\begin{tiny}
<<closeModMM, results='asis'>>=
mixedModclose <- lmer(turnout ~  VAP_adjLOG + VAP_adjLOG_sq +
                     per_white_all + 
                    per65o + PerBachelorOrAbove + OOH_share + 
                    median_incomeLOG + districtwide + incumbent +
                  contest *VAP_adjLOG  + (1|year) + (1|distid), 
              data = moddat, REML = TRUE)

mixedModcloseB <- lmer(turnout ~  VAP_adjLOG +  VAP_adjLOG_sq + 
                     per_white_all + 
                     per65o + PerBachelorOrAbove + OOH_share + 
                     median_incomeLOG + districtwide + incumbent + 
                       contest * VAP_adjLOG + 
                   (1|year) + (1|distid), 
              data = moddat, REML = TRUE)

mixedModcloseC <- lmer(turnout ~  VAP_adjLOG +  VAP_adjLOG_sq + 
                     per_white_all + 
                     per65o + PerBachelorOrAbove + OOH_share + 
                     median_incomeLOG + districtwide + incumbent + 
                       minBlaisLago * VAP_adjLOG + 
                   (1|year) + (1|distid), 
              data = moddat, REML = TRUE)

closeCoefs2 <- c("Intercept", "ln(VAP)", 
                  "$ln(VAP)^{2}$", "\\% White", 
                  "\\% Over 65", "\\% Bach. +", "\\% OOH", 
                  "ln(MedianIncome)", "District-wide", "No Incumbent", 
                 "Uncontested Seat", "VAP x Uncontested", 
                 "Blais-Lago", "VAP x Blais-Lago")


# summary(mixedMod2)
apsrtable(mixedModcloseB, mixedModcloseC, caption = "Partial Pooling Models of Competitiveness",
          model.names = c("Qualitative", "Blais-Lago"),
            label = "tab:meClose", notes = list(tabnote, stars.note), 
          coef.names = closeCoefs2, 
          Sweave = FALSE)

# Results with fallTurnout are largely similar but demographic variables are not 
# significant and less impactful due to collinearity with fall turnout
@
\end{tiny}


<<closeModSens,results='hide', eval=TRUE>>=
# m0 <- lm(turnout ~  minBlaisLago + VAP_adjLOG + minBlaisLago*VAP_adjLOG + 
#            per_white_all + per65o + PerBachelorOrAbove + OOH_share + 
#            median_incomeLOG + districtwide + 
#                   contest, data = moddat) # fit the null model

# exactLRT(m = refitML(mixedModclose), m0 = m0)

# Test for year specific slopes
m.slope <- update(mixedModcloseC, . ~ . - (1|year))
m0 <- update(mixedModcloseC, . ~ . - (1|distid))
closeLRT <- exactRLRT(m.slope, mixedModcloseC, m0)
closeLRT$callFull <- mixedModcloseC@call
closeLRT$callSmall <- m.slope@call
@

\clearpage

\subsection{Social Groups}

To test the argument that voter turnout may be influenced by the share of the 
electorate that is made up of unionized teachers, I combine features from the 
previous models in an attempt to find evidence of such an effect.  

% Partisanship and unionization

\subsubsection{Teachers' Unions}
<<teachInflRLM, results ='hide'>>=
moddat <- dist_turn[, c("turnout", "turnoutLag2", "year", "fallTurnout", 
                        "VAP_adjLOG", "distid", "per_white_all", "per65o", 
                        "PerBachelorOrAbove", "OOH_share", "median_incomeLOG", 
                        "teachShareofVoters", "districtwide", "incumbent",
                        "contest", "minBlaisLago")]
moddat <- na.omit(moddat)
moddat <- moddat[order(moddat$distid, moddat$year),]
moddat$distid <- factor(moddat$distid)
moddat$year <- factor(moddat$year)
moddat <- moddat[order(moddat$distid, moddat$year),]
moddat$distid <- factor(moddat$distid)
moddat$contest <- factor(moddat$contest)
moddat$districtwide <- factor(moddat$districtwide)
moddat$VAP_adjLOG_sq <- moddat$VAP_adjLOG^2
moddat$year <- factor(moddat$year)
moddat$turnout <- moddat$turnout * 100
centr <- mean(moddat$turnout)
stddev <- sd(moddat$turnout)
moddat$outflag <- (moddat$turnout - centr) / stddev
moddat <- moddat[moddat$outflag <=5 & moddat$outflag >= -5,]

nums <- sapply(moddat, is.numeric)
ScaleMeans <- apply(moddat[, nums], 2, mean, na.rm=TRUE)
ScaleSD <- apply(moddat[, nums], 2, sd, na.rm=TRUE)
moddatScaleTeach <- cbind(ScaleMeans, ScaleSD); rm(ScaleMeans, ScaleSD)
nums <- sapply(moddat, is.numeric)
moddat[, nums] <- apply(moddat[, nums], 2, rescale)
dd <<- datadist(moddat)
options(datadist="dd")

teachRLM <- ols(turnout ~ teachShareofVoters + fallTurnout + minBlaisLago + 
                    VAP_adjLOG + per_white_all + per65o + 
                  PerBachelorOrAbove + OOH_share + median_incomeLOG + 
                  districtwide + contest, data = moddat, x = TRUE, y = TRUE)

teachRLM$se <- sqrt(diag(vcov(robcov(teachRLM, cluster = moddat$distid))))

teachRLM2 <- ols(turnout ~ teachShareofVoters + fallTurnout + minBlaisLago + 
                    VAP_adjLOG + per_white_all + per65o + 
                   PerBachelorOrAbove + OOH_share + median_incomeLOG + 
                   districtwide + contest + year,
              data = moddat, x= TRUE, y = TRUE)

teachRLM2$se <- sqrt(diag(vcov(robcov(teachRLM2, cluster = moddat$distid))))


teachRLM3 <- ols(turnout ~ teachShareofVoters + turnoutLag2 + 
                   minBlaisLago + VAP_adjLOG +
                   VAP_adjLOG_sq + per_white_all + per65o + PerBachelorOrAbove +
                   OOH_share + median_incomeLOG + districtwide + incumbent + 
                   distid + factor(year), 
              data = moddat, x = TRUE, y = TRUE)

teachRLM3$se <- sqrt(diag(vcov(robcov(teachRLM3, cluster = moddat$distid))))

# Interaction model
teachRLM4 <- ols(turnout ~ teachShareofVoters +  
                   turnoutLag2 + minBlaisLago + 
                   VAP_adjLOG +  VAP_adjLOG_sq +
                    per_white_all + per65o + PerBachelorOrAbove +
                   OOH_share + median_incomeLOG + districtwide + incumbent + 
                   teachShareofVoters * VAP_adjLOG + factor(year) +
                   distid, 
              data = moddat, x = TRUE, y = TRUE)

teachRLM4$se <- sqrt(diag(vcov(robcov(teachRLM4, cluster = moddat$distid))))


teachCoefnames <- c("Intercept", "Teacher \\% VAP", "Lag Turnout", 
                 "Blais-Lago", "ln(VAP)", "$ln(VAP)^{2}$", "\\% White", 
                  "\\% Over 65", "\\% Bach. +", "\\% OOH", 
                  "ln(MedianIncome)", "District-wide", "No Incumbent", 
                  "Teacher \\% X VAP")

teachTab1 <- apsrtable(teachRLM3, teachRLM4, se="robust", label="tab:teachmods", 
          model.names=c("RLM + District FE", "+ Interaction"), 
          caption = "Models of Unionization and Turnout in School Board Elections",
          notes = list(se.note, stars.note, "Year and district fixed effects omitted."),
          omitcoef=list("distid", 
                        expression(grep("distid", coefnames, value=TRUE)), 
                        "year", 
                        expression(grep("year", coefnames, value = TRUE))),
          coef.names = teachCoefnames,
          Sweave=FALSE)
@

Table \ref{tab:meInf} provides some evidence to support that teacher's unions 
may have an effect on the turnout. The key variables here are the teacher share of voters 
and its interaction with the voting age population. The main effects of the share 
of voters who are teachers is not significant and is quite small. However, 
the interaction suggests that as the voting age population increases and the 
teacher share of voting age population increases, turnout decreases. Including the 
square of the VAP reduces the interaction effect to being non-significant. Judging 
statistical significance of interaction predictors, however, is notoriously 
difficult -- particularly in mixed-effect models. I return to demonstrating the 
effect of these variables later using simulation methods to show their substantive 
impact on voter turnout as predicted by the model. Other variables follow their 
expected signs, although some like competitiveness have a smaller effect than 
in prior models. 

This result is counter to the theoretical expectations described above where more 
union membership would drive turnout up as a greater share of the population would 
have a stronger interest in school board outcomes. Despite this, the effect is 
understandable. If voters believe the school board election to be captured by a 
large interest group, they have  less of an incentive to vote. The threat of 
controlling the spring electorate for an interest group is enough to deter 
unorganized voters from participating. This type of behavior is the type of behavior 
that worries critics of special purpose governments like school districts 
\citep{fosterK,burnsN,berry2}. 


\begin{tiny}
<<teachInfMM, results='asis'>>=
teachCoefnames2 <- c("Intercept", "Teacher \\% VAP",  
                 "Blais-Lago", "Lag Turnout 2", "ln(VAP)", "\\% White", 
                  "\\% Over 65", "\\% Bach. +", "\\% OOH", 
                  "ln(MedianIncome)", "District-wide", "No Incumbent",
                 "Teacher \\% x VAP", "$ln(VAP)^{2}$")
# what happens if I cut out lags

mixedModteach <- lmer(turnout ~ teachShareofVoters +  minBlaisLago +  turnoutLag2 + 
                    VAP_adjLOG + per_white_all + per65o + PerBachelorOrAbove +
                   OOH_share + median_incomeLOG + districtwide +  incumbent +
                   teachShareofVoters * VAP_adjLOG + (1|year) +  (1|distid), 
              data = moddat, REML = TRUE)

mixedModteachB <- lmer(turnout ~ teachShareofVoters +  
                   turnoutLag2 + minBlaisLago + 
                   VAP_adjLOG +  VAP_adjLOG_sq +
                    per_white_all + per65o + PerBachelorOrAbove +
                   OOH_share + median_incomeLOG + districtwide + incumbent + 
                   teachShareofVoters * VAP_adjLOG + 
                         (1|year) + (1|distid), 
              data = moddat, REML = TRUE)

apsrtable(mixedModteach, mixedModteachB, caption = "Partial Pooling Model of Staff Influence",
          model.names = c("Model 1","Model 2"),
            label = "tab:meInf", notes = list(stars.note), 
          coef.names = teachCoefnames2, 
          Sweave = FALSE)

# Same results when including fall turnout
@
\end{tiny}


<<mixedInfmodSen, results='hide', eval=TRUE>>=
# Test for year specific slopes
m.slope <- update(mixedModteachB, . ~ . - (1|year))
m0 <- update(mixedModteachB, . ~ . - (1|distid))
teachLRT <- exactRLRT(m.slope, mixedModteachB, m0)
teachLRT$callFull <- mixedModteachB@call
teachLRT$callSmall <- m.slope@call
@

\subsubsection{Partisanship}

Table \ref{tab:mePartisan} provides no evidence for a partisan dimension in school 
board turnout. While other variables hold their relationship from the tables 
above, the new variables for partisanship and party divide in the electorate are 
not statistically significant and their interaction with the size of the community 
is also not significant. If parties played an important role in the vote 
in spring elections than either the interaction between the party division or the 
proportion Democrats and the population of the district should be statistically 
significant and positive. The lack of a relationship provides evidence that parties 
do not influence school board turnout as a social group in a meaningful way. This 
seems clear, boards are not proving grounds for candidates for higher office and as 
they are non-partisan the party leadership has little incentive to prioritize them. 

<<partyMods, results ='hide'>>=
dist_turn$fallPartyDivision <- abs(dist_turn$fallTwoPartyShareDem - 0.5)

moddat <- dist_turn[, c("turnout", "year", "fallTurnout", "incumbent",
                        "VAP_adjLOG", "distid", "per_white_all", "per65o", 
                        "PerBachelorOrAbove", "OOH_share", "median_incomeLOG", 
                        "fallTwoPartyShareDem", "fallPartyDivision", 
                        "districtwide", "contest", "minBlaisLago")]
moddat <- na.omit(moddat)
moddat <- moddat[order(moddat$distid, moddat$year),]
moddat$distid <- factor(moddat$distid)
moddat$year <- factor(moddat$year)
moddat <- moddat[order(moddat$distid, moddat$year),]
moddat$distid <- factor(moddat$distid)
moddat$contest <- factor(moddat$contest)
moddat$districtwide <- factor(moddat$districtwide)
moddat$VAP_adjLOG_sq <- moddat$VAP_adjLOG^2
moddat$year <- factor(moddat$year)
moddat$turnout <- moddat$turnout * 100
centr <- mean(moddat$turnout)
stddev <- sd(moddat$turnout)
moddat$outflag <- (moddat$turnout - centr) / stddev
moddat <- moddat[moddat$outflag <=5 & moddat$outflag >= -5,]
nums <- sapply(moddat, is.numeric)
# nums <- nums[!names(nums) %in% c("fallPartyDivision")]
ScaleMeans <- apply(moddat[, nums], 2, mean, na.rm=TRUE)
ScaleSD <- apply(moddat[, nums], 2, sd, na.rm=TRUE)
moddatScaleParty <- cbind(ScaleMeans, ScaleSD); rm(ScaleMeans, ScaleSD)
moddat[, nums] <- apply(moddat[, nums], 2, rescale)
dd <<- datadist(moddat)
options(datadist="dd")

partyRLM1 <- ols(turnout ~ fallTurnout + minBlaisLago + 
                    VAP_adjLOG + VAP_adjLOG_sq  + per_white_all + per65o + 
                   PerBachelorOrAbove + OOH_share + median_incomeLOG + 
                   districtwide + incumbent + fallPartyDivision + year + distid,
              data = moddat, x= TRUE, y = TRUE)

partyRLM1$se <- sqrt(diag(vcov(robcov(partyRLM1, cluster = moddat$distid))))


partyRLM2 <- ols(turnout ~ fallTwoPartyShareDem + fallTurnout + minBlaisLago + 
                    VAP_adjLOG + VAP_adjLOG_sq + per_white_all + per65o + PerBachelorOrAbove +
                   OOH_share + median_incomeLOG + districtwide + incumbent + 
                   distid + factor(year), 
              data = moddat, x = TRUE, y = TRUE)

partyRLM2$se <- sqrt(diag(vcov(robcov(partyRLM2, cluster = moddat$distid))))

partyRLM3 <- ols(turnout ~ fallPartyDivision*VAP_adjLOG + fallTurnout + minBlaisLago + 
                    VAP_adjLOG + VAP_adjLOG_sq+ per_white_all + per65o + 
                   PerBachelorOrAbove + OOH_share + median_incomeLOG + 
                   districtwide + incumbent + year + distid,
              data = moddat, x= TRUE, y = TRUE)

partyRLM3$se <- sqrt(diag(vcov(robcov(partyRLM3, cluster = moddat$distid))))


partyRLM4 <- ols(turnout ~ fallTwoPartyShareDem*VAP_adjLOG + fallTurnout + minBlaisLago + 
                    VAP_adjLOG + VAP_adjLOG_sq+ per_white_all + per65o + PerBachelorOrAbove +
                   OOH_share + median_incomeLOG + districtwide + incumbent + 
                   distid + factor(year), 
              data = moddat, x = TRUE, y = TRUE)

partyRLM4$se <- sqrt(diag(vcov(robcov(partyRLM4, cluster = moddat$distid))))

partyCoefNames <- c("Intercept", "Fall Turnout", 
                 "Blais-Lago", "ln(VAP)", "$ln(VAP)^{2}$", "\\% White", 
                  "\\% Over 65", "\\% Bach. +", "\\% OOH", 
                  "ln(MedianIncome)", "District-wide", "No Incumbent", 
                  "Fall Party Divide", "Fall 2 Party Dem.", 
                 "Party Division x VAP", 
                 "2 Party Dem x VAP")

partyModtab <- apsrtable(partyRLM1, partyRLM2, partyRLM3, partyRLM4, se="robust", label="tab:partymods", 
          model.names=c("Party Unity", "Dem Share", "Party Unity Inter.", "Dem Share Inter."), 
          caption = "Models of Partisanship and Turnout in School Board Elections",
          notes = list(se.note, stars.note, "Year and district fixed effects omitted."),
          omitcoef=list("distid", 
                        expression(grep("distid", coefnames, value=TRUE)), 
                        "year", 
                        expression(grep("year", coefnames, value = TRUE))), 
          coef.names = partyCoefNames,
          Sweave=FALSE, float = "sidewaystable")
@


\begin{tiny}
<<partyMixedMods, results='asis'>>=
partyCoefNames2 <- c("Intercept", "Fall Party Divide", "Fall Turnout", 
                 "Blais-Lago", "ln(VAP)", "$ln(VAP)^{2}$","\\% White", 
                  "\\% Over 65", "\\% Bach. +", "\\% OOH", 
                  "ln(MedianIncome)", "District-wide", "No Incumbent", 
                 "Party Division x VAP", 
                 "Fall 2 Party Dem.", "$2 Party Dem^{2}$","2 Party Dem x VAP")

mixedModP <- lmer(turnout ~ fallPartyDivision + fallTurnout + minBlaisLago + 
                    VAP_adjLOG + VAP_adjLOG_sq +per_white_all + per65o + 
                   PerBachelorOrAbove + OOH_share + median_incomeLOG + 
                   districtwide + incumbent + fallPartyDivision * VAP_adjLOG + 
                    (1|distid) + (1|year), 
              data = moddat, REML = TRUE)

mixedModPb <- lmer(turnout ~ VAP_adjLOG + VAP_adjLOG_sq + fallTwoPartyShareDem +
                     I(fallTwoPartyShareDem^2)+ 
                     fallTurnout + 
                     minBlaisLago + 
                    VAP_adjLOG + per_white_all + per65o + PerBachelorOrAbove +
                   OOH_share + median_incomeLOG + districtwide + incumbent +
                     fallTwoPartyShareDem * VAP_adjLOG +
                     (1|year) + (1|distid), 
              data = moddat, REML = TRUE)

apsrtable(mixedModP, mixedModPb, caption = "Partial Pooling Model of Partisanship",
          model.names = c("Party Divide", "Share Democrat"),
            label = "tab:mePartisan", notes = list(tabnote, stars.note), 
          Sweave = TRUE, coef.names = partyCoefNames2)
@
\end{tiny}

<<mixedPartymodSen, results='hide', eval=TRUE>>=
# Test for year specific slopes
m.slope <- update(mixedModPb, . ~ . - (1|year))
m0 <- update(mixedModPb, . ~ . - (1|distid))
partyLRT <- exactRLRT(m.slope, mixedModPb, m0)
partyLRT$callFull <- mixedModPb@call
partyLRT$callSmall <- m.slope@call
@



<<cleanupb, echo=FALSE,results='hide'>>=
rm(partyRLM1, partyRLM2, partyRLM3, partyRLM4, teachRLM, teachRLM2, 
   teachRLM3, teachRLM4, closeRLM, closeRLM2, closeRLM3, closeRLM4)
@

\clearpage

\subsection{School Board Vote Roll Off}

Next, I examine the same models above applied to voter rolloff in the spring 
elections. I explore whether any of the models above explain the difference between 
top ticket turnout and school board turnout. As much as undervote coincides with 
political relevance of the school board race to the electorate, the relationships 
observed above shouldalso be observed in the measure of undervote. 


<<cleanundervotedata, results='hide'>>=
load("../../data/cache/springElectionVotes.rda")
# load("data/cache/springElectionVotes.rda")
springVotes$votesTopTicketSpring <- springVotes$VotesCast
springVotes$VotesCast <- NULL
dist_turn <- merge(dist_turn, springVotes, 
                   by = c("distid", "year"), all.x = TRUE)

dist_turn$topTicketTurnoutSpring <- dist_turn$votesTopTicketSpring / dist_turn$VAP_adj
dist_turn$turnoutDiff <- dist_turn$topTicketTurnoutSpring - dist_turn$turnout

vars2 <- c("turnout", "turnoutLag2", "year", "fallTurnout", "incumbent",
                        "VAP_adjLOG", "distid", "per_white_all", "per65o", 
                        "PerBachelorOrAbove", "OOH_share", "median_incomeLOG", 
                        "teachShareofVoters", "districtwide", 
                        "contest", "minBlaisLago")

vars1 <- c("turnout", "turnoutLag2", "year", "fallTurnout", "topTicketTurnoutSpring",
           "turnoutDiff", "ImputedFlag",
                        "VAP_adjLOG", "distid", "per_white_all", "per65o", 
                        "PerBachelorOrAbove", "OOH_share", "median_incomeLOG", 
                        "fallTwoPartyShareDem", "fallPartyDivision", 
                        "districtwide", "contest", "minBlaisLago")

moddat <- dist_turn[, unique(c(vars1, vars2))]
moddat$ImputedFlag[is.na(moddat$ImputedFlag)] <- "Observed"
moddat$ImputedFlag <- defac(moddat$ImputedFlag)
moddat$ImputedFlag[moddat$ImputedFlag == "Imputed2010"] <- "Imputed"
moddat$ImputedFlag[moddat$ImputedFlag == "Observed2010"] <- "Observed"
moddat$ImputedFlag <- factor(moddat$ImputedFlag, levels = c("Imputed", "Observed"))
moddat$ImputedFlag <- relevel(moddat$ImputedFlag, ref = "Imputed")
moddat$VAP_adjLOG_sq <- moddat$VAP_adjLOG^2
moddat <- na.omit(moddat)
moddat <- moddat[order(moddat$distid, moddat$year),]
moddat$distid <- factor(moddat$distid)
moddat$year <- factor(moddat$year)
moddat$districtwide <- factor(moddat$districtwide)
moddat$turnout <- moddat$turnout * 100
moddat$turnoutDiff <- moddat$turnoutDiff * 100
# moddat$turnoutLag2 <- moddat$turnoutLag2 * 100
# moddat$turnoutLag1 <- moddat$turnoutLag1 * 100
# moddat$per_white_all <- moddat$per_white_all * 100
# moddat$per65o <- moddat$per65o * 100
# moddat$PerBachelorOrAbove <- moddat$PerBachelorOrAbove * 100
# moddat$OOH_share <- moddat$OOH_share * 100
# moddat$fallTurnout <- moddat$fallTurnout * 100
# moddat$VAP_adj <- log(moddat$VAP_adj)
# moddat$median_income <- log(moddat$median_income)
centr <- mean(moddat$turnoutDiff)
stddev <- sd(moddat$turnoutDiff)
moddat$outflag <- (moddat$turnoutDiff - centr) / stddev
moddat <- moddat[moddat$outflag <= 5 & moddat$outflag >= -5,]
nums <- sapply(moddat, is.numeric)
ScaleMeans <- apply(moddat[, nums], 2, mean, na.rm=TRUE)
ScaleSD <- apply(moddat[, nums], 2, sd, na.rm=TRUE)
moddatScaleUndervote <- cbind(ScaleMeans, ScaleSD); rm(ScaleMeans, ScaleSD)
nums <- sapply(moddat, is.numeric)
moddat[, nums] <- apply(moddat[, nums], 2, rescale)
dd <<- datadist(moddat)
options(datadist="dd")
@

For undervote data, I use the spring elections in from 2007-2012. To calculate 
rolloff, I take the difference in the turnout for the top ticket in the spring 
election and the turnout for the highest turnout school board election in the 
school district. The greater this number, the greater the share of voters who 
failed to complete their ballots. The median district has \Sexpr{iPer(mean(dist_turn$turnoutDiff, na.rm=TRUE)*100)} percentage point difference in their turnout, meaning that if the turnout in the school board election was 1,810, then the turnout for the 
top ticket race would be \Sexpr{iNum2(1810 + 1810*mean(dist_turn$turnoutDiff, na.rm=TRUE))}. Thus ballot fatigue is not that uncommon and matches findings in other 
elections elsewhere \citep{streb09,wattenberg00}.


\begin{tiny}
<<undervoteMMfits1, results='asis'>>=
undervoteMMlag <- lmer(turnoutDiff ~ turnoutLag2 + fallTurnout + 
                         VAP_adjLOG + VAP_adjLOG_sq + per_white_all + 
                         per65o + PerBachelorOrAbove + OOH_share + 
                         median_incomeLOG + districtwide + incumbent +
                         ImputedFlag + minBlaisLago + 
                         (1|year) + (1|distid), 
              data = moddat, REML = FALSE)
undervoteMMclose <- lmer(turnoutDiff ~  minBlaisLago + VAP_adjLOG + fallTurnout +
                           VAP_adjLOG_sq + per_white_all + 
                    per65o + PerBachelorOrAbove + OOH_share + 
                      ImputedFlag + minBlaisLago * VAP_adjLOG +
                    median_incomeLOG + districtwide + incumbent +
                    (1|year) + (1|distid), 
              data = moddat, REML = TRUE)
undervoteMMcloseB <- lmer(turnoutDiff ~ VAP_adjLOG +  VAP_adjLOG_sq + 
                     fallTurnout +
                     VAP_adjLOG + per_white_all + 
                     per65o + PerBachelorOrAbove + OOH_share + 
                       ImputedFlag +
                     median_incomeLOG + districtwide + contest + incumbent + 
                       contest * VAP_adjLOG + 
                   (1|year) + (1|distid), 
              data = moddat, REML = TRUE)
undervoteMMteach <- lmer(turnoutDiff ~ teachShareofVoters + fallTurnout + 
                           minBlaisLago + VAP_adjLOG + VAP_adjLOG_sq +
                           per_white_all + per65o + PerBachelorOrAbove +
                  OOH_share + median_incomeLOG + districtwide + incumbent +
                    ImputedFlag+  
                   teachShareofVoters * VAP_adjLOG + (1|year) + (1|distid), 
              data = moddat, REML = TRUE)
undervoteMMparty <- lmer(turnoutDiff ~ fallTwoPartyShareDem*VAP_adjLOG + VAP_adjLOG_sq +
                           fallTurnout + minBlaisLago +
                  VAP_adjLOG + per_white_all + per65o + PerBachelorOrAbove +
                   OOH_share + median_incomeLOG + districtwide + incumbent +
                    ImputedFlag + 
                      (1|year) + (1|distid), 
              data = moddat, REML = TRUE)
undervoteMMpartyB <- lmer(turnoutDiff ~ fallPartyDivision*VAP_adjLOG +  VAP_adjLOG_sq+ 
                           fallTurnout + minBlaisLago +
                  VAP_adjLOG + per_white_all + per65o + PerBachelorOrAbove +
                   OOH_share + median_incomeLOG + districtwide +incumbent +
                    ImputedFlag +
                      (1|year) + (1|distid), 
              data = moddat, REML = TRUE)

coefNamesUnd1 <- c("Intercept", "Turnout Lag (2)","Fall Turnout", 
                 "ln(VAP)", "$ln(VAP)^{2}$","\\% White", 
                  "\\% Over 65", "\\% Bach. +", "\\% OOH", 
                  "ln(MedianIncome)", "District-wide", "No Incumbent","Imputed",
                 "Blais-Lago", "Blais-Lago x VAP", 
                 "Uncontested Seat", "Uncon. Seat. x VAP")


apsrtable(undervoteMMlag, undervoteMMclose,  undervoteMMcloseB,
          caption = "Partial Pooling Model of School Board Undervote",
           model.names = c("Lag", "Close Race", "Close Race 2"),
            label = "tab:meUndv1", notes = list(stars.note), 
          Sweave = TRUE, 
          coef.names = coefNamesUnd1)
@
\end{tiny}

Table \ref{tab:meUndv1} shows the results of the first three types of models investigated 
above for turnout. Note that here the sign is flipped -- the smaller the dependent 
variable, the more turnout for school board in relation to the top ticket turnout 
in the spring election. Prior turnout continues to matter in the lagged model, 
the higher the prior turnout the less the gap between top ticket and school board 
races in the present spring election. In the measures of the closeness of seats 
the less competitive a race is the greater the gap between the top ticket and the 
board race -- but this effect is only in interaction with larger district sizes. 
In small communities this relationship does not matter. This could be for a couple 
of reasons -- information costs to voters are less in small communities meaning 
voters reaching the polls in the spring election are more likely to feel informed 
enough to complete the ballot. Another reason could be that in large communities 
school boards are even further down the ballot due to more county and municipality 
elections and voters get tired out more quickly unless the race is likely competitive 
and then they persevere. 

\begin{tiny}
<<undervoteMMfits2, results='asis'>>=
coefNamesUnd2 <- c("Intercept", "Teacher Share VAP", "Fall Turnout", 
                   "Blais-Lago", "ln(VAP)", "$ln(VAP)^{2}$","\\% White", 
                  "\\% Over 65", "\\% Bach. +", "\\% OOH", 
                  "ln(MedianIncome)", "District-wide", "No Incumbent","Imputed", 
                 "Teacher Share x VAP", "Fall Dem.", "Fall Dem. X VAP", 
                 "Fall Partisan", "Fall Partisan x VAP")
apsrtable(undervoteMMteach, undervoteMMparty, undervoteMMpartyB,
          caption = "Partial Pooling Model of School Board Undervote",
           model.names = c("Teacher Influence", "Party Influence", "Party Divide"),
            label = "tab:meUndv2", notes = list(stars.note), 
          Sweave = FALSE, coef.names = coefNamesUnd2)
@
\end{tiny}


Table \ref{tab:meUndv2} looks at interest group influence and how it affects 
voter roll-off. The results for the control variables are largely the same as 
in Table \ref{tab:meUndv1}, but here the undervote results are different than 
the results for total turnout. In all three cases I find evidence of group influence 
in the completion of spring ballots. In the case of partisan division, this effect 
is only present in larger communities -- as communities and division get larger, 
the turnout gap for school board races widens. 

In the case of teachers, as teachers make up a greater share of the electorate 
fewer voters cast a vote for school board -- paralleling the finding from above 
for overall turnout. Democratic party strength is also related with fewer voters 
completing the school board vote. An interaction effect just misses statistical 
significance here -- suggesting that as communities get larger and more Democratic, 
voter rolloff lessens. 




% Lagged turnout being higher, results in lower turnout differential
% higher fall turnout results in higher turnout differential
% bigger size = higher turnout differential
% whiter = higher turnout differential
% older - no difference
% more educated = higher turnout differential (more rolloff)
% higher income = lower turnout differential
% higher OOH share = higher voter rolloff
% imputation model dummy adjusts rolloff downward
% uncontested seat = higher rolloff
% less competitive seat = more rolloff, but only in smaller jurisdictions

\clearpage


\begin{table}[h!]
\begin{center}
\begin{small}
\caption{Summary of Evidence for All Models on Both Outcomes}
\label{turnoutRESULTS}
\begin{tabular}{| p{.25\textwidth} | p{.25\textwidth} | p{.1\textwidth} | p{.1\textwidth} | p{.1\textwidth} |} 
\hline
\textbf{Theory}  & \textbf{Evidence} & \textbf{Turnout?} & \textbf{Rolloff?} & \textbf{Magnitude}\\ \hline
Habit-forming voters  & Predictive lagged turnout & Yes & Yes & Moderate \\ \hline
Rational Voters & District size decreases turnout & Yes & Yes & Moderate \\ \hline
Strategic Voters & Small electorate and close election drives turnout up  & No & Yes  & Small \\ \hline
Teacher Influence &  Union membership as share of electorate drives up turnout & Some & Some & Small \\ \hline
Partisan Influence & Partisan division increases turnout & No & Some & Small \\ \hline
\end{tabular}
\end{small}
\end{center}
\end{table}

\subsection{Model Fit}

Assessing model fit in a mixed model framework is not as straightforward as with 
a standard OLS regression. I use a boostrapped estimate of the Root Mean Squared 
Error (RMSE) to assess how close the predicted values are to the fitted values across 
models. All of the models fit relatively well. Figure \ref{fig:modFitplot1} 
demonstrates how the multilevel model improves on the pooled fixed effect model 
fit by showing the original data, predicted values, and predicted values under 
the fixed effect model for the model of competitiveness predicting turnout.

<<modFitplot1, eval = TRUE, fig.cap="Comparing Model Fit for Competitiveness Model. Black represents observed value, purple represents fixed effect estimate, and the red dots are the estimate from the full model.">>=
library(broom)
plotdf <- augment(mixedModcloseC)
plotdf$yUnscale <- (plotdf$turnout * 2 * moddatScaleClose["turnout", 2]) + 
   moddatScaleClose["turnout", 1]
plotdf$yhatUnscale <- (plotdf$.fitted * 2 * moddatScaleClose["turnout", 2]) + 
   moddatScaleClose["turnout", 1]
plotdf$x1Unscale <- (plotdf$minBlaisLago * 2 * moddatScaleClose["minBlaisLago", 2]) + 
   moddatScaleClose["minBlaisLago", 1]
plotdf$yhatFixed <- (plotdf$.fixed * 2 * moddatScaleClose["turnout", 2]) + 
   moddatScaleClose["turnout", 1]

plotSlope <- coefficients(lm(yUnscale ~ x1Unscale, data = plotdf))[2]
plotInt <- coefficients(lm(yUnscale ~ x1Unscale, data = plotdf))[1]

cases <- sample(unique(plotdf$distid), 12)
plotdf <- plotdf[plotdf$distid %in% cases, ]

ggplot(plotdf, aes(x = year, y = yUnscale/100)) +
         geom_point() + 
  geom_point(aes(x = year, y = yhatFixed/100), color = I("purple")) +
  geom_point(aes(x = year, y = yhatUnscale/100), color = I("red")) + 
  facet_wrap(~distid) + 
  scale_y_continuous(label = percent) +
  theme_bw() + labs(x= "Year", y = "Turnout", title = "Comparing Model Fit")
@


<<modFitplot2, eval = FALSE>>=
plotdf <- augment(mixedMod1lagsb)
plotdf$yUnscale <- (plotdf$turnout * 2 * moddatScaleLag["turnout", 2]) + 
   moddatScaleLag["turnout", 1]
plotdf$yhatUnscale <- (plotdf$.fitted * 2 * moddatScaleLag["turnout", 2]) + 
   moddatScaleLag["turnout", 1]
plotdf$x1Unscale <- (plotdf$turnoutLag2 * 2 * moddatScaleLag["turnoutLag2", 2]) + 
   moddatScaleLag["turnoutLag2", 1]
plotdf$yhatFixed <- (plotdf$.fixed * 2 * moddatScaleLag["turnout", 2]) + 
   moddatScaleLag["turnout", 1]

plotdf$x1Unscale <- plotdf$x1Unscale * 100
plotdf <- plotdf[plotdf$x1Unscale < 99, ]

plotSlope <- coefficients(lm(yUnscale ~ x1Unscale, data = plotdf))[2]
plotInt <- coefficients(lm(yUnscale ~ x1Unscale, data = plotdf))[1]

cases <- sample(unique(plotdf$distid), 12)
plotdf <- plotdf[plotdf$distid %in% cases, ]


ggplot(plotdf, aes(x = x1Unscale, y = yUnscale)) +
         geom_point() + 
  geom_point(aes(x = x1Unscale, y = yhatUnscale), color = I("red")) + 
  geom_point(aes(x = x1Unscale, y = yhatFixed), color = I("purple")) +
  geom_smooth(aes(x = x1Unscale, y = yUnscale), method = "lm", 
              se = FALSE, color = I("black")) + 
  geom_smooth(aes(x = x1Unscale, y = yhatUnscale), method = "lm", 
              se = FALSE, color = I("red")) + 
  geom_smooth(aes(x = x1Unscale, y = yhatFixed), method = "lm", 
              se = FALSE, color = I("purple")) +
  facet_wrap(~distid) + 
  geom_abline(intercept = plotInt, slope = plotSlope, linetype=2) +
  xlim(c(0, max(plotdf$x1Unscale))) + 
  theme_bw()

# Bootstrap the beta coefficients here using bootMer
# http://glmm.wikidot.com/faq
@


<<bootRMSE, results='hide'>>=
library(boot)
RMSE.merMod <- function(mod){
  sqrt(mean(residuals(mod)^2))
}

bootRMSE <- function(data, indx, model){
  moddat <- data[indx, ]
  modb <- eval(model@call)
  RMSE.merMod(modb)
}

sigmaBoot <- boot(mixedModP@frame, bootRMSE, R = 100, model = mixedModP)
out <- cbind(summary(sigmaBoot), mod  = "mixedmodP")
sigmaBoot <- boot(mixedModlags@frame, bootRMSE, R = 100, model = mixedModlags)
out <- rbind(out, cbind(summary(sigmaBoot), mod  = "mixedModlags"))
sigmaBoot <- boot(mixedMod1lagsb@frame, bootRMSE, R = 100, model = mixedMod1lagsb)
out <- rbind(out, cbind(summary(sigmaBoot), mod  = "mixedMod1lagsb"))
sigmaBoot <- boot(mixedModcloseC@frame, bootRMSE, R = 100, model = mixedModcloseC)
out <- rbind(out, cbind(summary(sigmaBoot), mod  = "mixedModcloseC"))
sigmaBoot <- boot(mixedModclose@frame, bootRMSE, R = 100, model = mixedModclose)
out <- rbind(out, cbind(summary(sigmaBoot), mod  = "mixedModclose"))
sigmaBoot <- boot(mixedModcloseB@frame, bootRMSE, R = 100, model = mixedModcloseB)
out <- rbind(out, cbind(summary(sigmaBoot), mod  = "mixedModcloseB"))
sigmaBoot <- boot(mixedModteach@frame, bootRMSE, R = 100, model = mixedModteach)
out <- rbind(out, cbind(summary(sigmaBoot), mod  = "mixedModteach"))
sigmaBoot <- boot(mixedModteachB@frame, bootRMSE, R = 100, model = mixedModteachB)
out <- rbind(out, cbind(summary(sigmaBoot), mod  = "mixedModteachB"))
sigmaBoot <- boot(mixedModPb@frame, bootRMSE, R = 100, model = mixedModPb)
out <- rbind(out, cbind(summary(sigmaBoot), mod  = "mixedModPb"))

rmsePlot1 <- ggplot(out, aes(x = mod, y = bootMed, ymax = bootMed + (bootSE *2), 
                ymin = bootMed - (bootSE *2))) + 
  geom_pointrange() + geom_point(aes(x = mod, y = original), color = I("red")) + 
  labs(x = "Model Name", y = "Model RMSE", title = "Turnout Models") + 
  coord_flip() + theme_dpi()
@

<<bootRMSE2, results='hide'>>=
sigmaBoot <- boot(undervoteMMclose@frame, bootRMSE, R = 100, model = undervoteMMclose)
out <- cbind(summary(sigmaBoot), mod  = "undervoteMMclose")
sigmaBoot <- boot(undervoteMMcloseB@frame, bootRMSE, R = 100, model = undervoteMMcloseB)
out <- rbind(out, cbind(summary(sigmaBoot), mod  = "undervoteMMcloseB"))
sigmaBoot <- boot(undervoteMMlag@frame, bootRMSE, R = 100, model = undervoteMMlag)
out <- rbind(out, cbind(summary(sigmaBoot), mod  = "undervoteMMlag"))
sigmaBoot <- boot(undervoteMMparty@frame, bootRMSE, R = 100, model = undervoteMMparty)
out <- rbind(out, cbind(summary(sigmaBoot), mod  = "undervoteMMparty"))
sigmaBoot <- boot(undervoteMMpartyB@frame, bootRMSE, R = 100, model = undervoteMMpartyB)
out <- rbind(out, cbind(summary(sigmaBoot), mod  = "undervoteMMpartyB"))
sigmaBoot <- boot(undervoteMMteach@frame, bootRMSE, R = 100, model = undervoteMMteach)
out <- rbind(out, cbind(summary(sigmaBoot), mod  = "undervoteMMteach"))

rmsePlot2 <- ggplot(out, aes(x = mod, y = bootMed, ymax = bootMed + (bootSE *2), 
                ymin = bootMed - (bootSE *2))) + 
  geom_pointrange() + geom_point(aes(x = mod, y = original), color = I("red")) + 
  labs(x = "Model Name", y = "Model RMSE", title = "Rolloff Models") + 
  coord_flip() + theme_dpi()
@


\subsection{Substantive Effects}

After finding evidence in favor of voters behaving as theory might expect, I now 
turn my attention to exploring the magnitude of these effects. In order to estimate 
the substantive impact, I conduct simulations to show the change in the dependent 
variable holding all else constant and manipulating an independent variable of 
interest. While this type of simulation does not represent the interrelated 
nature of the independent variables in the models above, it does allow me to 
demonstrate the maximum possible effect predicted by the models described above -- 
assuming the independent variable is changing while all other variables remain 
constant.\footnote{Simulations are conducted using a modification of the \texttt{sim} 
function in the \texttt{arm} package for R.}


\subsubsection{Turnout}


<<fixefplot1, eval=FALSE, fig.cap="Coefficient Plot for Full Model Fixed Effects",fig.height=8.5, fig.width=8, results='hide'>>=
sim1 <- FEsim(mixedMod1lagsb, nsims = 1000); sim1$dv <- "Lags"
sim2 <- FEsim(mixedModcloseC, nsims = 1000); sim2$dv <- "Close"
sim3 <- FEsim(fullmodMMd, nsims = 1000); sim3$dv <- "Defeat"
sim4 <- FEsim(fullmodMMblq, nsims = 1000); sim4$dv <- "Competitiveness"

simPlot <- do.call(rbind, list(sim1, sim2, sim3, sim4))
simPlot$dv <- factor(simPlot$dv, levels = c("No Incumb.", "Contest", 
                                            "Defeat", "Competitiveness"))
alpha <- 1.96
simPlot$upr <- simPlot$meanEff + (alpha*simPlot$sdEff)
simPlot$lwr <- simPlot$meanEff - (alpha*simPlot$sdEff)

simPlot$color <- "Not Sig."
simPlot$color <- ifelse(simPlot$lwr >0 | simPlot$upr < 0, "Sig", "Not Sig.")

ggplot(simPlot, aes(x = variable, y = meanEff, ymax = upr, 
                    ymin = lwr, color = color)) + 
  scale_color_brewer(palette = "Dark2") + 
  geom_point() + geom_errorbar(h=1.5) +
  geom_hline(yintercept = 0, size = I(1.1), color = I("black"), linetype = 2, 
             alpha = I(0.6)) +
  coord_flip() + 
  facet_wrap(~dv) + 
  theme_dpi(base_size=12) +theme(legend.position = "bottom") + 
  labs(x = "Variable", y = "Effect", color = "Stat. Sig.")

# confint(fullmodMMni, method = "Wald", level = 0.9)
@

Figure \ref{fig:fixefSub1} shows the effect of four of the key variables of interest 
from the models above. These plots show four randomly sampled observations (represented 
by a different colored line) with the independent variable on the x-axis and the 
predicted school board turnout on the y-axis. Along the x-axis is a rug-plot showing 
the relative density of observations at each range of the x-variable to help demonstrate 
where the model may be extrapolating with less data. The two dashed lines shown 
represent the inter-quartile range or the predicted values from the model being 
simulated. This is presented to provide a reference for how powerful the effect 
of the independent variable -- as shown by the slope of the line -- is relative 
to the overall variability in turnout. 

In Figure \ref{fig:fixefSub1} two patterns stand out. First, the interaction 
effect for the teacher share of voters depicted in the top right panel, stands 
out immediately -- the differing slopes are the result of the variation in VAP 
across these randomly sampled observations. This effect is strong and is further 
explored in Figure \ref{fig:interactPlot1}. However, from this panel it is clear 
the effect of the teacher share of voters can move school board turnout a substantial 
degree of the range of the turnout variable -- as evidenced by the steep slope of 
some of these lines. 

The second pattern is in the bottom-left panel. As competitiveness decreases from 
left to right, turnout decreases substantially. Across the range of competitiveness 
the effect is almost equivalent to two quartiles of school board turnout. More 
practically, it results in turnout decreasing between three and five percentage 
points. Given that median turnout is around 20\%, this effect is quite large. 

On the other diagonal there is an expected relationship between prior turnout 
and current turnout as positive and fairly strong. Partisan division has a very 
small positive effect of turnout with more polarized communities having a slight 
increase in expected voter turnout -- but much less substantial than the effect 
of teacher voter share or competitiveness. 


<<fixefSub1, eval=TRUE, fig.cap="Substantive Effect on School Board Turnout Across Cases">>=
library(gridExtra)

seplotdf <- 1
while(class(seplotdf) != "data.frame"){
  seplotdf <- try(substEffSimFE(mixedModP, "fallPartyDivision", ncases = 4L, 
                          unscale = moddatScaleParty, re = FALSE), 
                  silent = TRUE)
}

lowerBar <- ((quantile(fitted(mixedModP), prob = 0.25) * 2 * moddatScaleParty["turnout", 2]) + 
      moddatScaleParty["turnout", 1]) / 100
upperBar <- ((quantile(fitted(mixedModP), prob = 0.75) * 2 * moddatScaleParty["turnout", 2]) + 
      moddatScaleParty["turnout", 1]) / 100

seplotdf$yhatUnscale <- seplotdf$yhatUnscale / 100
seplotdf$lwrUnscale <- seplotdf$lwrUnscale / 100
seplotdf$uprUnscale <- seplotdf$uprUnscale / 100

p1 <- ggplot(seplotdf, aes(x = newvarUnscale, y = yhatUnscale)) +
  geom_line(aes(group = caseID, color = factor(caseID)), size = I(1.05)) + 
  scale_color_discrete(guide = FALSE) +
    geom_ribbon(aes(ymin=lwrUnscale, ymax=uprUnscale, group = caseID),
                     alpha=0.1) + 
#   facet_wrap(~caseID) + 
  geom_hline(yintercept = lowerBar, linetype = 2) + 
  geom_hline(yintercept = upperBar, linetype = 2) + 
  geom_rug(data = dist_turn, aes(x = fallPartyDivision, y = NULL)) + 
  theme_dpi(base_size=12) + 
  labs(x = "Partisan Division", y = "School Board Turnout")+ 
  scale_y_continuous(label = percent, limits = c(0, .50))

seplotdf <- 1
while(class(seplotdf) != "data.frame"){
  seplotdf <- try(substEffSimFE(mixedModteach, "teachShareofVoters", ncases = 4L, 
                          unscale = moddatScaleTeach, re = TRUE), 
                  silent = TRUE)
}
lowerBar <- ((quantile(fitted(mixedModteach), prob = 0.25) * 2 * moddatScaleTeach["turnout", 2]) + 
      moddatScaleTeach["turnout", 1]) /100
upperBar <- ((quantile(fitted(mixedModteach), prob = 0.75) * 2 * moddatScaleTeach["turnout", 2]) + 
      moddatScaleTeach["turnout", 1]) / 100

seplotdf$yhatUnscale <- seplotdf$yhatUnscale / 100
seplotdf$lwrUnscale <- seplotdf$lwrUnscale / 100
seplotdf$uprUnscale <- seplotdf$uprUnscale / 100

p2 <- ggplot(seplotdf, aes(x = newvarUnscale, y = yhatUnscale)) +
  geom_line(aes(group = caseID, color = factor(caseID)), size = I(1.05)) + 
  scale_color_discrete(guide = FALSE) +
    geom_ribbon(aes(ymin=lwrUnscale, ymax=uprUnscale, group = caseID),
                     alpha=0.1) + 
#   facet_wrap(~caseID) + 
  geom_hline(yintercept = lowerBar, linetype = 2) + 
  geom_hline(yintercept = upperBar, linetype = 2) + 
  geom_rug(data = dist_turn, aes(x = teachShareofVoters, y = NULL)) + 
  theme_dpi(base_size=12) + 
  labs(x = "Teacher Share of Voters", y = "School Board Turnout") + 
  scale_y_continuous(label = percent, limits = c(0, .50)) + 
  scale_x_continuous(label = percent)
seplotdf <- 1
while(class(seplotdf) != "data.frame"){
  seplotdf <- try(substEffSimFE(mixedModcloseC, "minBlaisLago", ncases = 4L, 
                          unscale = moddatScaleClose, re = TRUE), 
                  silent = TRUE)
}

lowerBar <- ((quantile(fitted(mixedModcloseC), prob = 0.25) * 2 * moddatScaleClose["turnout", 2]) + 
      moddatScaleClose["turnout", 1]) /100
upperBar <- ((quantile(fitted(mixedModcloseC), prob = 0.75) * 2 * moddatScaleClose["turnout", 2]) + 
      moddatScaleClose["turnout", 1]) / 100

seplotdf$yhatUnscale <- seplotdf$yhatUnscale / 100
seplotdf$lwrUnscale <- seplotdf$lwrUnscale / 100
seplotdf$uprUnscale <- seplotdf$uprUnscale / 100

p3 <- ggplot(seplotdf, aes(x = newvarUnscale, y = yhatUnscale)) +
  geom_line(aes(group = caseID, color = factor(caseID)), size = I(1.05)) + 
  scale_color_discrete(guide = FALSE) +
    geom_ribbon(aes(ymin=lwrUnscale, ymax=uprUnscale, group = caseID),
                     alpha=0.1) + 
#   facet_wrap(~caseID) + 
  geom_hline(yintercept = lowerBar, linetype = 2) + 
  geom_hline(yintercept = upperBar, linetype = 2) + 
  geom_rug(data = dist_turn, aes(x = minBlaisLago, y = NULL)) + 
  theme_dpi(base_size=12) + 
  labs(x = "Blais-Lago Competitiveness", y = "School Board Turnout") + 
  scale_y_continuous(label = percent, limits = c(0, .50))
seplotdf <- 1
while(class(seplotdf) != "data.frame"){
  seplotdf <- try(substEffSimFE(mixedMod1lagsb, "turnoutLag2", ncases = 4L, 
                          unscale = moddatScaleLag, re = TRUE), 
                  silent = TRUE)
}
lowerBar <- ((quantile(fitted(mixedMod1lagsb), prob = 0.25) * 2 * moddatScaleLag["turnout", 2]) + 
      moddatScaleLag["turnout", 1]) /100
upperBar <- ((quantile(fitted(mixedMod1lagsb), prob = 0.75) * 2 * moddatScaleLag["turnout", 2]) + 
      moddatScaleLag["turnout", 1]) / 100

seplotdf$yhatUnscale <- seplotdf$yhatUnscale / 100
seplotdf$lwrUnscale <- seplotdf$lwrUnscale / 100
seplotdf$uprUnscale <- seplotdf$uprUnscale / 100

p4 <- ggplot(seplotdf, aes(x = newvarUnscale, y = yhatUnscale)) +
  geom_line(aes(group = caseID, color = factor(caseID)), size = I(1.05)) + 
  scale_color_discrete(guide = FALSE) +
    geom_ribbon(aes(ymin=lwrUnscale, ymax=uprUnscale, group = caseID),
                     alpha=0.1) + 
#   facet_wrap(~caseID) + 
  geom_hline(yintercept = lowerBar, linetype = 2) + 
  geom_hline(yintercept = upperBar, linetype = 2) + 
  geom_rug(data = dist_turn, aes(x = turnoutLag2, y = NULL)) + 
  theme_dpi(base_size=12) + 
  labs(x = "Lagged SB Turnout (2)", y = "School Board Turnout") + 
  scale_y_continuous(label = percent, limits = c(0, .50)) +
  scale_x_continuous(label = percent, limits = c(0, 0.35))

grid.arrange(p1, p2, p3, p4, main = "Simulated Effects on School Board Turnout")
@

<<fixefSub2, eval=TRUE, results='hide'>>=
seplotdf <- 1
while(class(seplotdf) != "data.frame"){
  seplotdf <- try( substEffSimFE(mixedModteachB, "teachShareofVoters", ncases = 64L, 
                          unscale = moddatScaleTeach, re = TRUE), 
                  silent = TRUE)
}
lowerBar <- ((quantile(fitted(mixedModteachB), prob = 0.25) * 2 * moddatScaleTeach["turnout", 2]) + 
      moddatScaleTeach["turnout", 1]) /100
upperBar <- ((quantile(fitted(mixedModteachB), prob = 0.75) * 2 * moddatScaleTeach["turnout", 2]) + 
      moddatScaleTeach["turnout", 1]) / 100

seplotdf$yhatUnscale <- seplotdf$yhatUnscale / 100
seplotdf$lwrUnscale <- seplotdf$lwrUnscale / 100
seplotdf$uprUnscale <- seplotdf$uprUnscale / 100

seplotdf$sizeCut <- cut(seplotdf$VAP_adjLOG, 
                        breaks = quantile(mixedModteachB@frame$VAP_adjLOG, 
                                          prob = c(0, 0.25, .5, .75, 1)), 
                        labels = c("VAP Quart. 1", "VAP Quart. 2", "VAP Quart. 3", "VAP Quart. 4"))

TeachInteractPlot <- ggplot(seplotdf, aes(x = newvarUnscale, y = yhatUnscale)) +
  geom_line(aes(group = caseID), alpha = 0.4, size = I(1.05)) +
  facet_wrap(~sizeCut) +
  geom_hline(yintercept = lowerBar, linetype = 2) + 
  geom_hline(yintercept = upperBar, linetype = 2) + 
  geom_rug(data = dist_turn, aes(x = teachShareofVoters, y = NULL)) + 
  theme_dpi(base_size=12) + 
  labs(x = "Teacher Share of Voters", y = "School Board Turnout") + 
  scale_y_continuous(label = percent, limits = c(0, .50)) + 
  scale_x_continuous(label = percent)

@


<<fixefSub3, results='hide'>>=
# mixedModPb
seplotdf <- 1
while(class(seplotdf) != "data.frame"){
  seplotdf <- try(substEffSimFE(mixedModPb, "fallTwoPartyShareDem", ncases = 64L, 
                          unscale = moddatScaleParty, re = TRUE), 
                  silent = TRUE)
}
lowerBar <- ((quantile(fitted(mixedModPb), prob = 0.25) * 2 * moddatScaleParty["turnout", 2]) + 
      moddatScaleParty["turnout", 1]) /100
upperBar <- ((quantile(fitted(mixedModPb), prob = 0.75) * 2 * moddatScaleParty["turnout", 2]) + 
      moddatScaleParty["turnout", 1]) / 100

seplotdf$yhatUnscale <- seplotdf$yhatUnscale / 100
seplotdf$lwrUnscale <- seplotdf$lwrUnscale / 100
seplotdf$uprUnscale <- seplotdf$uprUnscale / 100

seplotdf$sizeCut <- cut(seplotdf$VAP_adjLOG, 
                        breaks = quantile(mixedModPb@frame$VAP_adjLOG, 
                                          prob = c(0, 0.25, .5, .75, 1)), 
                        labels = c("VAP Quart. 1", "VAP Quart. 2", "VAP Quart. 3", "VAP Quart. 4"))

PartyInteractPlot <- ggplot(seplotdf, aes(x = newvarUnscale, y = yhatUnscale)) +
  geom_line(aes(group = caseID), alpha = 0.4, size = I(1.05)) +
  facet_wrap(~sizeCut) +
  geom_hline(yintercept = lowerBar, linetype = 2) + 
  geom_hline(yintercept = upperBar, linetype = 2) + 
  geom_rug(data = dist_turn, aes(x = fallTwoPartyShareDem, y = NULL)) + 
  theme_dpi(base_size=12) + 
  labs(x = "Democratic Two-Party Share", y = "School Board Turnout") + 
  scale_y_continuous(label = percent, limits = c(0, .50)) + 
  scale_x_continuous(label = percent)
@

All of the models specified included random intercepts for both school districts 
and years as a way to control for unobservable characteristics of each district 
and secular change in turnout from spring election to spring election. Figure 
\ref{fig:randomEffectplot1} demonstrates the variability in the district intercepts 
for each of the four models. These plots can be interpreted as the deviation of 
the intercept of a school district from the average district. This figure arranges 
the estimate of the individual intercept for each school, and its corresponding 
95\% confidence interval, from lowest to highest to depict the variability in 
district intercepts. This is known as a caterpillar plot and is useful in demonstrating 
the variability among units in a mixed-effect model. 

The results in \ref{fig:randomEffectplot1} show large and consistent variance 
between the four models with a number of individual districts deviating from the 
average district even with their confidence intervals. The height of the points 
can be interpreted as the number of standard deviations in election turnout the 
school district deviates from the average for all districts in the model. 

%TODO: check this and review wording


<<randomEffectplot1, eval=TRUE, fig.cap="Comparing District Intercepts on Standardized Coefficient Scale">>=
replotdf <- 1
while(class(replotdf) != "data.frame"){
  replotdf <- try(substEffSimRE(mixedModP, "distid", ncases = 3, alpha = 0.1), 
                  silent = TRUE)
}

replotdf$distid <- as.character(replotdf$distid)
replotdf$yhatUnscale <- (replotdf[, "yhat"] * 2 * moddatScaleParty[1, 2]) + moddatScaleParty[1, 1]
replotdf$yhatUnscale <- replotdf$yhatUnscale / 100
replotdf$lwrUnscale <- (replotdf[, "lwr"] * 2 * moddatScaleParty[1, 2]) + moddatScaleParty[1, 1]
replotdf$lwrUnscale <- replotdf$lwrUnscale / 100
replotdf$uprUnscale <- (replotdf[, "upr"] * 2 * moddatScaleParty[1, 2]) + moddatScaleParty[1, 1]
replotdf$uprUnscale <- replotdf$uprUnscale / 100

lowerBar <- ((quantile(fitted(mixedModP), prob = 0.25) * 2 * moddatScaleParty["turnout", 2]) + 
      moddatScaleParty["turnout", 1]) /100
upperBar <- ((quantile(fitted(mixedModP), prob = 0.75) * 2 * moddatScaleParty["turnout", 2]) + 
      moddatScaleParty["turnout", 1]) / 100

p0 <- ggplot(data = replotdf, aes(x = reorder(distid, -yhatUnscale), y = yhatUnscale, 
                            ymin = lwrUnscale, ymax = uprUnscale)) + 
  geom_line(aes(group = caseID)) + 
    geom_ribbon(aes(group = caseID), alpha=0.4) + 
  theme_dpi(base_size=12) + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), 
                      strip.text = element_blank(), 
                      strip.background = element_blank(), 
                      panel.grid.minor = element_blank(), 
                      panel.grid.major = element_blank()) + 
  geom_hline(yintercept = lowerBar, linetype = 2) + 
  geom_hline(yintercept = upperBar, linetype = 2) + 
  facet_wrap(~caseID, ncol = 1) + 
  labs(x = "District", y = "Predicted SB Turnout", title = "Party Model") + 
  scale_y_continuous(label = percent)

plotdf <- REsim(mixedModP, nsims = 1000)
plotdf <- plotdf[plotdf$level == "Level 1",]
p1 <- plotMCMCre(plotdf, scale = 1.96, var = "mean", 
               sd = "sd", sigmaScale = sigma(mixedModP)) + 
  labs(title = "Partisan Model", x= "District", y = "Intercept")+ 
  ylim(c(-2, 3.5))
plotdf <- REsim(mixedModclose, nsims = 1000)
plotdf <- plotdf[plotdf$level == "Level 1",]
p2 <- plotMCMCre(plotdf, scale = 1.96, var = "mean", 
                 sd = "sd", sigmaScale = sigma(mixedModclose)) + 
  labs(title = "Competitiveness Model", x= "District", y = "Intercept")+ 
  ylim(c(-2, 3.5))
plotdf <- REsim(mixedModteach, nsims = 1000)
plotdf <- plotdf[plotdf$level == "Level 1",]
p3 <- plotMCMCre(plotdf, scale = 1.96, var = "mean", 
                 sd = "sd", sigmaScale = sigma(mixedModteach))+ 
  labs(title = "Teach Share Model", x= "District", y = "Intercept")+ 
  ylim(c(-2, 3.5))
plotdf <- REsim(mixedModlags, nsims = 1000)
plotdf <- plotdf[plotdf$level == "Level 1",]
p4 <- plotMCMCre(plotdf, scale = 1.96, var = "mean", 
                 sd = "sd", sigmaScale = sigma(mixedModlags))+ 
  labs(title = "Lagged Model", x= "District", y = "Intercept") + 
  ylim(c(-2, 3.5))

grid.arrange(p1, p2, p3, p4)
@

Even more interestingly is the pattern for the year effects demonstrated in 
Figure \ref{fig:randomEffectplot2}. In all four models we see one below average year, 
2010, and three above average years -- 2003, 2011, and 2012. These above average 
years are not always statistically different than zero -- 2003 tends to have many 
fewer observations than the other years -- but statewide spring election specific 
effects do appear to exert an influence on school board turnout. Most interestingly 
is that two years of elevated turnout across the state (net of district-election and 
district-average effects) were in 2011 and 2012 after the election of Governor Scott Walker 
and the introduction of Act 10. 

<<randomEffectplot2, eval=TRUE, fig.cap="Comparing Year Intercepts of Year Effects">>=
# replotdf <- 1
# while(class(replotdf) != "data.frame"){
#   replotdf <- try(substEffSimRE(mixedModP, "year", ncases = 1, alpha = 0.1), 
#                   silent = TRUE)
# }
# 
# replotdf$year <- as.character(replotdf$year)
# 
# replotdf$yhatUnscale <- (replotdf[, "yhat"] * 2 * moddatScaleParty[1, 2]) + moddatScaleParty[1, 1]
# replotdf$yhatUnscale <- replotdf$yhatUnscale / 100
# replotdf$lwrUnscale <- (replotdf[, "lwr"] * 2 * moddatScaleParty[1, 2]) + moddatScaleParty[1, 1]
# replotdf$lwrUnscale <- replotdf$lwrUnscale / 100
# replotdf$uprUnscale <- (replotdf[, "upr"] * 2 * moddatScaleParty[1, 2]) + moddatScaleParty[1, 1]
# replotdf$uprUnscale <- replotdf$uprUnscale / 100
# 
# lowerBar <- ((quantile(fitted(mixedModP), prob = 0.2) * 2 * moddatScaleParty["turnout", 2]) + 
#       moddatScaleParty["turnout", 1]) /100
# upperBar <- ((quantile(fitted(mixedModP), prob = 0.8) * 2 * moddatScaleParty["turnout", 2]) + 
#       moddatScaleParty["turnout", 1]) / 100
# 
# ggplot(data = replotdf, aes(x = year, y = yhatUnscale, 
#                             ymin = lwrUnscale, ymax = uprUnscale)) + 
#   geom_errorbar(width = .4) + geom_point()+
#   theme_dpi(base_size=12) + 
#   theme(
#                       strip.text = element_blank(), 
#                       strip.background = element_blank(), 
#                       panel.grid.minor = element_blank()) + 
#   geom_hline(yintercept = lowerBar, linetype = 2) + 
#   geom_hline(yintercept = upperBar, linetype = 2) + 
#   facet_wrap(~caseID, ncol = 1) + 
#   labs(x = "Year", y = "Predicted SB Turnout") + 
#   scale_y_continuous(label = percent)


plotdf <- REsim(mixedModP, nsims = 1000)
plotdf <- plotdf[plotdf$level == "Level 2",]
p1 <- plotMCMCre(plotdf, scale = 1.96, var = "mean", 
               sd = "sd", sigmaScale = sigma(mixedModP)) + 
  labs(title = "Partisan Model", x= "District", y = "Intercept")+ 
  ylim(c(-2, 3.5))
plotdf <- REsim(mixedModclose, nsims = 1000)
plotdf <- plotdf[plotdf$level == "Level 2",]
p2 <- plotMCMCre(plotdf, scale = 1.96, var = "mean", 
                 sd = "sd", sigmaScale = sigma(mixedModclose)) + 
  labs(title = "Competitiveness Model", x= "District", y = "Intercept")+ 
  ylim(c(-2, 3.5))
plotdf <- REsim(mixedModteach, nsims = 1000)
plotdf <- plotdf[plotdf$level == "Level 2",]
p3 <- plotMCMCre(plotdf, scale = 1.96, var = "mean", 
                 sd = "sd", sigmaScale = sigma(mixedModteach))+ 
  labs(title = "Teach Share Model", x= "District", y = "Intercept")+ 
  ylim(c(-2, 3.5))
plotdf <- REsim(mixedModlags, nsims = 1000)
plotdf <- plotdf[plotdf$level == "Level 2",]
p4 <- plotMCMCre(plotdf, scale = 1.96, var = "mean", 
                 sd = "sd", sigmaScale = sigma(mixedModlags))+ 
  labs(title = "Lagged Model", x= "District", y = "Intercept") + 
  ylim(c(-2, 3.5))

grid.arrange(p1, p2, p3, p4, main = "Variance in Year Intercepts Across Models")

@

\clearpage

\subsubsection{Rolloff}

<<fixefSubUndv, results='hide'>>=
library(gridExtra)
seplotdf <- 1
while(class(seplotdf) != "data.frame"){
  seplotdf <- try(substEffSimFE(undervoteMMlag, "turnoutLag2", ncases = 4L, 
                          unscale = moddatScaleUndervote, re = FALSE), 
                  silent = TRUE)
}
lowerBar <- ((quantile(fitted(undervoteMMlag), prob = 0.2) * 2 * moddatScaleUndervote["turnoutDiff", 2]) + 
      moddatScaleUndervote["turnoutDiff", 1]) / 100
upperBar <- ((quantile(fitted(undervoteMMlag), prob = 0.8) * 2 * moddatScaleUndervote["turnoutDiff", 2]) + 
      moddatScaleUndervote["turnoutDiff", 1]) / 100

seplotdf$yhatUnscale <- seplotdf$yhatUnscale / 100
seplotdf$lwrUnscale <- seplotdf$lwrUnscale / 100
seplotdf$uprUnscale <- seplotdf$uprUnscale / 100

p1 <- ggplot(seplotdf, aes(x = newvarUnscale, y = yhatUnscale)) +
  geom_line(aes(group = caseID, color = factor(caseID)), size = I(1.05)) + 
  scale_color_discrete(guide = FALSE) +
    geom_ribbon(aes(ymin=lwrUnscale, ymax=uprUnscale, group = caseID),
                     alpha=0.1) + 
#   facet_wrap(~caseID) + 
  geom_hline(yintercept = lowerBar) + 
  geom_hline(yintercept = upperBar) + 
  geom_rug(data = dist_turn, aes(x = turnoutLag2, y = turnoutDiff)) + 
  theme_dpi(base_size=12) + 
  labs(x = "Lagged Turnout Prior", y = "Voter Rolloff") + 
  scale_x_continuous(label = percent) + 
  scale_y_continuous(limits = c(-.2, .2))

# -----------------------------------------------------------------
seplotdf <- 1
while(class(seplotdf) != "data.frame"){
  seplotdf <- try(substEffSimFE(undervoteMMpartyB, "fallPartyDivision", ncases = 64L, 
                          unscale = moddatScaleUndervote, re = TRUE), 
                  silent = TRUE)
}

lowerBar <- ((quantile(fitted(undervoteMMpartyB), prob = 0.2) * 2 *
                moddatScaleUndervote["turnoutDiff", 2]) + 
      moddatScaleUndervote["turnoutDiff", 1]) /100

upperBar <- ((quantile(fitted(undervoteMMpartyB), prob = 0.8) * 2 * 
                moddatScaleUndervote["turnoutDiff", 2]) + 
      moddatScaleUndervote["turnoutDiff", 1]) / 100

seplotdf$yhatUnscale <- seplotdf$yhatUnscale / 100
seplotdf$lwrUnscale <- seplotdf$lwrUnscale / 100
seplotdf$uprUnscale <- seplotdf$uprUnscale / 100

seplotdf$sizeCut <- cut(seplotdf$VAP_adjLOG, 
                        breaks = quantile(undervoteMMpartyB@frame$VAP_adjLOG, 
                                          prob = c(0, 0.25, .5, .75, 1)), 
                        labels = c("VAP Quart. 1", "VAP Quart. 2", "VAP Quart. 3", "VAP Quart. 4"))

p2 <- ggplot(seplotdf, aes(x = newvarUnscale, y = yhatUnscale)) +
  geom_line(aes(group = caseID), alpha = 0.4, size = I(1.05)) +
  facet_wrap(~sizeCut) +
  geom_hline(yintercept = lowerBar, linetype = 2) + 
  geom_hline(yintercept = upperBar, linetype = 2) + 
  geom_rug(data = dist_turn, aes(x = fallPartyDivision, y = turnoutDiff)) + 
  theme_dpi(base_size=12) + 
  labs(x = "Fall Party Division", y = "Voter Rolloff") 

# -------------------------------------------------------------------------------
seplotdf <- 1
while(class(seplotdf) != "data.frame"){
  seplotdf <- try(substEffSimFE(undervoteMMteach, "teachShareofVoters", ncases = 64L, 
                          unscale = moddatScaleUndervote, re = TRUE), 
                  silent = TRUE)
}
lowerBar <- ((quantile(fitted(undervoteMMteach), prob = 0.2) * 2 * 
                moddatScaleUndervote["turnoutDiff", 2]) + 
      moddatScaleUndervote["turnoutDiff", 1]) /100

upperBar <- ((quantile(fitted(undervoteMMteach), prob = 0.8) * 2 * 
                moddatScaleUndervote["turnoutDiff", 2]) + 
      moddatScaleUndervote["turnoutDiff", 1]) / 100

seplotdf$yhatUnscale <- seplotdf$yhatUnscale / 100
seplotdf$lwrUnscale <- seplotdf$lwrUnscale / 100
seplotdf$uprUnscale <- seplotdf$uprUnscale / 100

seplotdf$sizeCut <- cut(seplotdf$VAP_adjLOG, 
                        breaks = quantile(undervoteMMteach@frame$VAP_adjLOG, 
                                          prob = c(0, 0.25, .5, .75, 1)), 
                        labels = c("VAP Quart. 1", "VAP Quart. 2", "VAP Quart. 3", "VAP Quart. 4"))

p3 <- ggplot(seplotdf, aes(x = newvarUnscale, y = yhatUnscale)) +
  geom_line(aes(group = caseID), alpha = 0.4, size = I(1.05)) +
  facet_wrap(~sizeCut) +
  geom_hline(yintercept = lowerBar, linetype = 2) + 
  geom_hline(yintercept = upperBar, linetype = 2) + 
  geom_rug(data = dist_turn, aes(x = teachShareofVoters, y = turnoutDiff)) + 
  theme_dpi(base_size=12) + 
  labs(x = "Teacher Share of VAP", y = "Voter Rolloff") 

# -------------------------------------------------------------------------------
seplotdf <- 1
while(class(seplotdf) != "data.frame"){
  seplotdf <- try(substEffSimFE(undervoteMMclose, "minBlaisLago", ncases = 64L, 
                          unscale = moddatScaleUndervote, re = TRUE), 
                  silent = TRUE)
}

lowerBar <- ((quantile(fitted(undervoteMMclose), prob = 0.2) * 2 * 
                moddatScaleUndervote["turnoutDiff", 2]) + 
      moddatScaleUndervote["turnoutDiff", 1]) /100

upperBar <- ((quantile(fitted(undervoteMMclose), prob = 0.8) * 2 * 
                moddatScaleUndervote["turnoutDiff", 2]) + 
      moddatScaleUndervote["turnoutDiff", 1]) / 100

seplotdf$yhatUnscale <- seplotdf$yhatUnscale / 100
seplotdf$lwrUnscale <- seplotdf$lwrUnscale / 100
seplotdf$uprUnscale <- seplotdf$uprUnscale / 100

seplotdf$sizeCut <- cut(seplotdf$VAP_adjLOG, 
                        breaks = quantile(undervoteMMclose@frame$VAP_adjLOG, 
                                          prob = c(0, 0.25, .5, .75, 1)), 
                        labels = c("VAP Quart. 1", "VAP Quart. 2", "VAP Quart. 3", "VAP Quart. 4"))

p4 <- ggplot(seplotdf, aes(x = newvarUnscale, y = yhatUnscale)) +
  geom_line(aes(group = caseID), alpha = 0.4, size = I(1.05)) +
  facet_wrap(~sizeCut) +
  geom_hline(yintercept = lowerBar, linetype = 2) + 
  geom_hline(yintercept = upperBar, linetype = 2) + 
  geom_rug(data = dist_turn, aes(x = minBlaisLago, y = turnoutDiff)) + 
  theme_dpi(base_size=12) + 
  labs(x = "Blais-Lago", y = "Voter Rolloff") 

@

I now review the substantive impact of key independent variables on voter rolloff. 
Figure \ref{fig:teachUndEff} shows the variation in the impact of the teacher share 
of voters on voter rolloff across four quartiles of district VAP. For the smallest 
districts, the teacher share of voters does not affect voter rolloff -- voters 
complete their ballots at the same rate whether teachers comprise 1\% or 5\% of the 
electorate. 

As districts get larger, the impact of teachers grows stronger and in the second 
and third quartile, the impact of moving from 2\% to 3\% teachers in the VAP can 
increase voter rolloff in school board elections by nearly as much as the interquartile 
range for the variable. The simulation in the final panel, for the largest districts,
is unlikely as it is very unlikely that very large VAP district would ever have 5\% 
teachers. 

Figure \ref{fig:compUndEff} provides the same look at an interactive effect with 
district size, but for school board seat competitiveness. Competitiveness plays no 
role in voter turnout for smaller school districts, but as districts get larger, 
less competitive elections see much greater voter rolloff. 

<<teachUndEff, fig.cap="Interaction Effect of Teacher Share on Undervote">>=
p3
@

<<compUndEff, fig.cap="Interaction Effect of Competition on Undervote">>=
p4
@


%TODO: add random effect plots for undervote to the appendix as well
\clearpage
\section{Discussion}

I find strong evidence that, like voters in other elections, school board voters 
are highly habit-forming, appear to evaluate their voting decision somewhat rationally, 
and appear to be shaped by social group voting. It bears repeating that school board 
voters are a subset of the total electorate and the fall electorate in Wisconsin 
school districts, but it appears that they too appear to behave in accordance 
with voter theories. 

% Evidence for habit forming voters
% Evidence for rational voters
% Evidence for social group voters
% Evidence for discontent among voters

Table \ref{tab:meTurnout} provides strong evidence that 
in Wisconsin spring elections voters are habit forming. The electorate in these 
elections is smaller and highly autocorrelated. As the electorate size increases, 
the less prior turnout matters. This is exactly in line with the theoretical 
expectation that smaller electorates are more habit forming than larger electorates. 
Though school boards are experiencing much less voter turnout, they appear to be 
behaving within the expectations of other electorates.

Table \ref{tab:meClose} demonstrates that competitive races matter for turnout in
school board elections as well. Uncontested races have lower voter turnout than races 
with contestation. Little difference exists between races for open seats and races 
featuring an incumbent. Competitiveness matters as well, with races that are contested 
but include a non-competitive candidate having depressed turnout as well. This 
suggests that, despite a lack of campaigning by candidates or major media coverage, 
voters in school board elections are able to assess whether or not to vote based 
on an assessment of how contested a race will be. 

A school board specific effects were explored in Table \ref{tab:meInf} and Table 
\ref{tab:mePartisan}. In this, the larger the teacher share of voters in the district, 
the lower the voter turnout. This is in line with the theory of regulatory capture -- 
the nomination process being strongly controlled by the teacher union. 

This study is not without its limits. A first limitation is the question of how 
much spring election voter turnout can be considered to be driven by local 
down-ticket elections. This is particularly true during the period of study in 
this chapter, which included the highest turnout spring election in Wisconsin 
history -- a result that cannot be attributed to a slate of particularly 
contentious school board elections, but instead to the aftershocks of historical
partisan politics surrounding Governor Scott Walker and the state fiscal crisis. 
In an effort to address these concerns I confirmed the theory expectations on a 
narrower dependent variable -- the difference in turnout between the top spring 
ticket and the school board race. While this addresses the concern about falsely 
attributing larger spring election forces to school boards, more evidence directly 
about school boards would be preferred. 

Second, this study is an attempt to infer voter behavior from the observed patterns 
of turnout and rolloff observed over the last several years in a sample of 
Wisconsin school districts. Thus, while theories of habit-forming voters are in
accordance with the pattern observed here, this study is limited by its inability
to peer into the rationales of individual voters. In order to disentangle the many
confounding theories, future research must survey eligible voters and ask them about
their decision to vote or not vote in local school board elections like the work
of \citet{oliver12}. Thus, readers should be cautious in overinterpreting the
results here. 

Unlike the results in Chapter \ref{chap:candidacy}, the results in this chapter 
broadly reflect the theoretical expectations for elections. This suggests that 
although the school board electorate is different than the general election electorate, 
that electorate behaves in expected ways -- that is, habit forming, selective about 
their vote mattering, and influenced by social group mechanisms. 

\clearpage

\section{Appendix}
\label{sec:appendixT}

Sensitivity checks and further table analysis. 

\subsection{Model Fit Comparisons}

<<rmsePlot1, fig.cap="Bootstrapped RMSE for Various Models of School Board Turnout">>=
rmsePlot1
@

<<rmsePlot2, fig.cap="Bootstrapped RMSE for Various Models of School Board Rolloff">>=
rmsePlot2
@

\clearpage

\subsection{Additional Effect Plots}

<<interactPlot1, fig.cap="Illustrating Interaction Effects with District Size and Partisanship">>=
PartyInteractPlot
@

<<interactPlot2, fig.cap="Illustrating Interaction Effects with District Size">>=
TeachInteractPlot
@

<<interactPlot3, fig.cap="Prior Turnout Effect on Voter Rolloff">>=
p1
@

<<interactPlot4, fig.cap="Partisan Division Effect on Voter Rolloff in Spring">>=
p2
@

\clearpage
\subsection{Random Effect Specification Tests}

<<LRTresults, echo=FALSE, results='markup'>>=
# Lag Model LRT
print(lagLRT)
# Competitive Model LRT
print(closeLRT)
# Party Model LRT
print(partyLRT)
# Teacher Model LRT
print(teachLRT)
@


\subsection{District and Year Fixed Effect Results}

District fixed effect model results. 

\begin{tiny}
<<lagmodTab, results='asis'>>=
lagmodTab
@
\end{tiny}


\begin{tiny}
<<appA1, results='asis'>>=
appA1
@
\end{tiny}


\begin{tiny}
<<closeModTab, results='asis'>>=
closeModTab
@
\end{tiny}

\begin{tiny}
<<teachTab1, results='asis'>>=
teachTab1
@
\end{tiny}


\begin{tiny}
<<partyModtab, results='asis'>>=
partyModtab
@
\end{tiny}

