\chapter{Why Vote for School Board?}
\label{chap:turnout}
\chapterstyle{deposit}

<<rsetup, results='hide', echo=FALSE, message=FALSE, warning=FALSE>>=
opts_chunk$set(fig.width=8, fig.height=6, message=FALSE, error=FALSE, 
               fig.path="../../phd_figs/chap4-",
               warning=FALSE, echo=FALSE, dev=c('pdf', 'png'))

setwd("../../")
#source("data/dataMerge.R")
source("R/thesis_functions.R")
library(scales)
library(xtable)
library(eeptools)
options(xtable.include.rownames = FALSE, xtable.table.placement = "ht")
source("data/cleanandprep_TURNOUT.R")
set.seed(51315)
@


\section{Introduction}

In most American communities, each year voters are asked who they would like to 
lead the direction of their local schools. Elected school board members, despite 
managing only public schools, have many responsibilities including 
the setting of property tax rates, selection of curriculum, and 
negotiating compensation with employees. In making their decision, voters have 
precious little information to go on given the low level of campaign activity and 
the lack of involvement by parties. Even worse, voters may have little way to 
retrospectively rate the performance of the school board. Even if they have children
in school, the information costs of evaluating school board performance remain 
high. Given these difficulties, it is no surprise that turnout is low. 

Indeed, ever since \citet{Downs57} political scientists have been asking the question: 
why vote in any election? Despite the fact that in general school boards are 
in charge of levying a substantial share of many citizens' tax bill through property taxes, 
when school board elections are held off-cycle turnout and voter interest in them 
appears to be remarkably low \citep{RefWorks:333, RefWorks:321}. 
This despite the fact that the community stake in quality education is large, not 
just for parents of the students, but for the social, economic, and political 
impacts that school quality can have on a community. 

Voter turnout even in national on-cycle elections in the US remains 
lower than many other democracies \citep{BlaisTurnout2006}. There is an extensive 
literature seeking to explain patterns in turnout between years and within years 
between social groups \citep{ParticAnnReview2004, econvoting2007, Galston2001, EconandOutcomes2000}.
The specific puzzle of voter turnout in school board elections has even spawned 
its own set of theories with empirical tests \citep{RefWorks:311,RefWorks:243,RefWorks:340}. Despite this rich ground, much work remains to be done to adequately test the 
mechanisms at play in predicting turnout in off-cycle, local, non-partisan elections 
like school board elections. Furthermore, theories of participation in on-cycle and 
higher profile elections benefit from examining the limits of their generalizability. 

School boards provide an excellent ground on which to test theories of democratic 
participation. Unlike national elections or even state elections, school boards 
in Wisconsin exhibit a much greater range of electorate sizes and community 
characteristics. This allows the testing of Downsian hypotheses across the bottom 
range of democracy sizes and paints a fuller picture of how turnout operates on 
the small scale. Another advantage is that school board boundaries are not endogenous 
to the political power struggle. School board boundaries are not, in the Wisconsin 
case, politically drawn, but instead are historical artificats of locally determined 
boundary setting. School boards come with some peculiarities which make them less 
interesting to political scientists. Most importantly, school board elections are 
non-partisan. Non-partisanship makes judging candidate differences, voter preferences, 
and ideology difficult on a large scale. Finally, the general lack of interest 
in school boards makes them unlike larger scale elections. However, it does make 
school boards an important window into understanding local non-partisan off-cycle 
elections more broadly. 

In this chapter I seek to explore voter turnout in school board elections through 
the lenses of the major theories of voter turnout. I begin by reviewing these 
theories. Then, I move into a discussion 
of school boards and the contribution a study of school boards can bring to 
the understanding of these theories. Next, I discuss the panel data set of 
school board results that I have collected, which is unique in its length and 
breadth, and the methods with which I will test 
these competing theories on the data. Finally, I conclude with an assessment of 
the performance of each of the theories and the foundations for future work. 

%% Significance of school boards
%% - as a share of elections they are dominant
%% - they have tremendous consequences to parents and tax payers 
%% - they are very different structurally, more variation, richer ground for theory


\section{Why Vote?}

Setting aside important though largely settled issues of access to the polls, 
enfranchisement laws, administrative and cognitive barriers to casting a ballot, and 
freedom from intimidation -- all thankfully of minimal concern in American school 
board elections -- there remains a wealth of intricate and interrelated factors 
which shape a voter's decision to cast a ballot. I broadly group this literature 
into three major strands and include the theories that have sprung up uniquely 
around school boards as a fourth category: 

\begin{myitemize}
	\item Rational Choice
	\item Group Mobilization
	\item Habits and Socialization
	\item Dissatisfaction Theory
\end{myitemize}

The turnout literature asks two fundamental questions -- why does anyone vote 
in the first place, and why do some people vote sometimes, and others do not? 
My aim is not to fully summarize this rich theoretical ground, but to reframe 
these debates in light of the particular challenge of school board elections.
\footnote{Other researchers studying subnational municipal or provincial 
elections have found support for these theories of turnout 
\citep{Hajnal01052003, PPIC2002}.} This chapter will attempt to answer these 
questions with off-cycle school board elections in Wisconsin.

\subsection{Rational Choice}

\citet{Downs57}'s elegant statement of the problem of voting as a question of 
why anyone would vote when their vote has such a small probability of influencing 
the outcome presented political scientists with a challenge of understanding why 
people do vote. In the formal statement of the problem as given by Downs:

\[ R = PB - C > 0 \]

$R$ is the net expected utility of voting, $P$ is the probability of influencing the 
election, $B$ is the difference in the expected utility of the policies of the 
two candidates, and $C$ refers to the cost of voting. Voters should not vote 
unless their expected benefit from having their preferred candidate elected multiplied 
by the chance of their vote being the decisive vote exceeds the costs of voting. A first 
attempt to answer the empirical observation that many more voters vote than 
should be expected under this model came from \citet{VoteCalculus68}'s 
further refinement of the problem:

\[ R = PB - C + D > 0 \]

The addition of the $D$ term is intended to capture the benefit of self-expression associated with 
voting -- either self-expression of candidate preference, or self-expression of the utility of voting. 
However, this $D$ term merely shifted the debate - the probability of benefit 
from an individual vote still remained zero, so voters would only vote when $D > C$; 
that is, when the benefit of self-expression was greater than the cost of voting 
\citep{nonvoting74, feddersenreview}.\footnote{\citet{Dowding2005} places an 
interesting 
wrinkle on this by questioning why voters care about being the decisive vote when 
politicians so often seek large victories to ensure a safe seat or to earn a mandate. 
This seems less germane to the present case - school board members and the community 
are unlikely to interpret a substantial victory as a mandate.} 
While the $D$ term did not solve the puzzle posed by \citet{Downs57}, it 
did touch off a decades long research project to uncover why the $D$ term varies 
among voters, and the functional form of this benefit of self-expression 
\citep[see:][]{KanYang2001,Dowding2005,feddersenreview,Schuessler1}.


In the rational choice case the argument is that if everyone pursues the optimal 
strategy of not voting, then the value of $PB$ increase. This sets off a strategic 
game among voters where the value of $P$ is determined by the strategies selected by 
all other voters in the electorate \citep{Palfrey83, Palfrey85,Ledyard84}. While 
I will not attempt to summarize this theoretically rich debate here 
\citep[see instead:][]{feddersenreview,geysreview}, I do want to highlight that 
most empirical tests of these voter turnout theories have focused on large-scale
electorates such as state or national elections. There exists a class of voter 
turnout theories that predict very different behaviors for differently sized 
electorates. As shown in Chapter \ref{chap:wisco} school board 
elections are typically comprised of small electorates where 
P is much higher than other elections.\footnote{$P$ can be estimated using the 
Blais-Lago calculation for the competitiveness of elections under various configurations of open seats and number of winners \citep{blaislago}.} It remains to be seen if 
$B$ is indeed 
higher in such cases, as we shall see the policy preferences of candidates for 
board are not always easily discovered by voters. Yet, rational choice and social 
mobilization theories of turnout expect that in smaller electorates the collective 
behavior of the electorate or social group could spur turnout to be higher. 

In order for positive turnout to emerge from 
such a game, voters are expected to have certainty about the costs of voting and 
the preferences of other voters -- an unrealistic assumption in large electorates that 
hurts the case for such an approach \citep{Mueller3, aldrich1993}. This is a special 
case of the rational choice model, often called the pivotal-voter model, and it has 
been explicitly tested in small-scale elections and found that while it predicts overall 
turnout sufficiently, it does not give an accurate reflection of the margins of 
victory \citep{Coate2008582}. Other scholars find size to be an important factor 
in local elections, but do not tie this to a particular theory of voter turnout \citep{Frandsen2002}.
Interestingly, some studies of local elections have found that voters in these 
elections -- though fewer -- are much more informed and engaged than non-voters 
\citep{oliver12}.\footnote{The size question is a curious one, because at its 
extreme it would predict that lower-level elections should thus exhibit higher 
turnout than national elections - a phenomenon described by 
\citet{Horiuchi2001} as the``turnout-twist.'' Evidence of this in Wisconsin 
will be explored later.} 

The causal relationship between electorate size and voter knowledge is not clear, but 
there is some suggestion that the electorate in these non-partisan local races 
has a stronger estimate of the expected benefit of their candidate winning than 
non-voters. More importantly, \citet{oliver} finds in local municipal elections 
that more important than knowledge or perception of preferences is personal contact 
with candidates themselves. School boards are a fascinating lens through which 
we can explore the Downsian hypothesis and its extensions. The low level of 
information about school board candidates, their positions on 
issues, their likely vote share in an election, and the voters' own feelings on 
issues facing the school board make this environment dramatically different than 
the presidential election. What's more, the likelihood that the vote of any 
single voter matters in a school district is orders of magnitude larger than for 
state wide or nationwide office. 

\subsection{Group Mobilization}

Social networks and group organization might also help explain voter turnout. The 
coordinating role they play may be more critical in small electorates. \citet[p. 23]{geysreview} 
states the key of the group-based models:

\begin{quote}
First, groups are likely to have larger benefits than individuals from political
participation. The reason is that politicians may provide groups with extra 
benefits – in terms of policies that come closer to the group’s optimum – to win 
the support of the group \citep{Lapp99}. Second, as the political influence of 
a social group can be assumed to be proportional to its size 
\citep{SchrWinden1991}, the group as a whole is more likely to have a 
non-negligible impact on the election outcome. 
\end{quote}

\noindent The group approach appears to more accurately reflect the modern political environment 
and campaign strategy of mobilization and targeted messaging to voters \citep{Lapp99}. 
The theory is more nuanced because it allows for the case where the optimal strategy 
for a group is to abstain from voting \citep{geysreview, Fowler2005}. 
Crucially, such group-based mobilization relies on the group being able to enforce 
the voting norm within the group. This enforcement has been shown to depend on 
factors that seem especially of interest in small-scale local elections. 
\citet[p.25]{GrossmanHelpman} identify three such factors: the 
frequency of interactions within the group, the risk of social isolation resulting 
from deviating from the group's behavior, and the ability of group members to 
monitor one another. These factors are essential to preventing free riding \citep[see][]{Olson65}.  
\citet{SchrWinden1991} identify opinion leaders within these groups as a key 
transmitter of this social pressure. These leaders have incentives to increase turnout such 
as increasing their influence with elected officials, and voters wanting to build 
credibility with these leaders find that turning out to vote is important. In the case 
of school board elections such local effects might be amplified in communities with 
strong local organizations where monitoring costs are low.\footnote{\citet{Morton91} finds that there is an equilibrium 
with positive turnout if at least one leader has a strict preference for a single candidate.}

The social group hypothesis has some support from studies of school board elections.
\citet{anzia11} finds that off-cycle elections confer greater benefits to organized 
interest groups than larger on-cycle elections. Teacher unions have a greater 
advantage in low turnout low information off-cycle elections and therefore can 
use this advantage to influence school board members to provide higher salaries 
than among boards elected with a broader on-cycle electorate. This 
falls in line with the work of \citet{RefWorks:207,RefWorks:218} that organized 
interest groups like teacher unions play an outsized role in off-cycle low turnout 
school board elections. This hypothesis will be explored below.

\subsection{Voter Socialization}

Other scholars have found that the D term can be endogenous within individuals from 
election to election \citep{Plutzer2002}.\footnote{Though the type of motivation 
based on personal contact with the candidates would not necessarily be endogenous.} 
Experimental evidence has found that ``voting and abstention, in other words, 
are habit forming'' \citep[p.540]{Gerber2003} This is related to the group 
mobilization arguments above because social groups may well be the mechanism by 
which the habit is 
formed \citep{Kanazawa2000}. Particularly in groups that interact frequently or 
small communities with low monitoring costs, social rewards may be found for 
voting and sanctions may be made for those who abstain \citep{Fowler2005}. Then, 
citizens who are rewarded for their vote (via the election of their preferred 
candidate) or punished for their abstention (through the election of a 
less-preferred candidate) acquire an increased preference for voting. Conversely, 
if their voting is punished or their abstention is
rewarded, they lose some of their preference for voting. This has been considered 
in other cases by political scientists as well \citep{ParticAnnReview2004}.\footnote{
Other scholars have found that not just the depth and frequency of interactions with 
voters matters, but also the nature of those interactions, the ideological 
composition of those groups, and socio-economic status
\citep{Mutz2002, classpart04, classbias92}.}


In school boards there is evidence that such socialization has occurred in the case of 
conservative Christians \citep{RefWorks:240}, unionized teachers \citep[chapter 5]{RefWorks:249, RefWorks:207}, 
and suggestions about the role institutions may play in deepening or weakening 
such socialization among ethnic minorities \citep{RefWorks:195}. Evidence of socialization 
is occurring might be found by observing ``stickiness'' in voter turnout 
in school board elections year to year, independent of other factors and stronger 
in smaller communities. \citet{RefWorks:248} 
called this the social conditioning model of school board turnout and found it held 
explanatory power in California school board election voter registration rates, 
but not rates of voter turnout. If members of the community vote at a higher 
average level after a high turnout election, this may provide evidence that the 
influx of turnout in the prior election has influenced the current election. 

\subsection{Dissatisfaction Theory}

In Chapter \ref{chap:intro}, I introduced dissatisfaction theory as the 
dominant theoretical paradigm for understanding school board elections.
This theory traces its roots back to \citet{RefWorks:348}'s concept of critical 
elections and \citet{RefWorks:319}'s conception of pluralism. It describes an electoral system with relative stability and little 
involuntary incumbent turnover punctuated by periods of citizen 
dissatisfaction, contentious elections, and incumbent defeats \citep{RefWorks:297,RefWorks:271}. 
Missing from empirical tests of dissatisfaction theory to date are indicators of voter participation. 
Implied throughout the dissatisfaction theory literature is that incumbent defeat 
is accompanied by an upwelling in citizen dissatisfaction and presumably voter 
participation in the election. Incumbents are defeated because new voters enter 
the game. Yet, until now, voter turnout in school board elections has not been 
used to test dissatisfaction theory explicitly, though it has received limited 
attention in understanding other phenomena of local education politics \citep{RefWorks:248, 
RefWorks:249, RefWorks:207, RefWorks:218}.\footnote{Taxpayers also have another 
option for expressing their dissatisfaction, which is to move jurisdictions \citep{MinkoffLyons}. 
In Wisconsin, yet another option of expressing dissatisfaction with the school board 
is available to parents - open-enrolling out of the school district. Both of these 
forms of dissatisfaction are decidedly higher cost than voting in a school board 
election, though their benefit is more immediate and selective.}

While some rational choice models have been adapted to the school board contest, 
there exist no large scale studies of voter turnout in school board elections 
that have empirically tested these theories 
\citep{RefWorks:243, RefWorks:340, RefWorks:339}. Instead, studies have focused 
predominantly on candidates for school board, why they run, and if their races 
are competitive \citep{RefWorks:311, RefWorks:321, RefWorks:322, RefWorks:207}. 
Yet, it might be argued, that such studies are jumping the gun. The conventional 
wisdom about school board elections is that they are minor affairs, settled on 
obscure issues, and conducted among large public apathy. If boards have 
competitive elections that lead to consequential decisions like superintendent 
turnover as expected by dissatisfaction theory \citep{RefWorks:297}, what does 
it matter if those hotly contested electoral defeats of incumbents came at the 
hand of 10\% of the electorate?  Democratic potential is high, with voters needing 
a small coalition to defeat any given candidate, but the actualization remains low 
because of the low stakes. In other words, the overwhelming majority has indeed 
cast a vote, one of indifference.

By leaving out the question of turnout, dissatisfaction theory has left out an 
important strategic actor in the act of expressing dissatisfaction with the 
direction of the schools -- the voter \citep{RefWorks:243}. The current study 
rectifies this by providing a descriptive analysis of voter turnout over an extended 
number of election cycles at hundreds of school districts within Wisconsin simultaneously. 
Naturally it is not expected to find school board races to be high turnout affairs 
year in and year out. But, if dissatisfaction theory is to be saved from criticism 
that it ignores voters in favor of focusing on board-superintendent relationships, 
some cases of heightened turnout must be identified. The current study is fruitful 
ground for examining voter turnout trends in school board elections as well as exploring 
possible opportunities for voters to express dissatisfaction with academic, fiscal, 
or the policy performance of the local school district. 

\subsection{Conclusion}

Notably missing from this summary is the influence that candidates and campaigns 
have on voter turnout. While there is some evidence that education messages used 
by candidates and campaign expenditures in local elections can play in mobilizing voters \citep{SidesKarch2008, Holbrook15072013}, 
the impact of these in school board elections is likely marginal. In the most recent survey of school board members, over 
two-thirds of board members report their last election as being ``easy'' or ``somewhat 
easy'', and in small districts this percentage is even higher \citep{RefWorks:322}.\footnote{Moreover, it is hard to know how much mobilization or advertising 
candidates can do when nearly 75\% of survey respondents report spending less than 
\$1,000 on their last campaign, and in small districts over 95\% of candidates 
reported spending less than \$1,000 on their campaign.\citep{RefWorks:322}}


\section{School Boards and Voter Turnout}

The current project adds importantly to the puzzle of voter turnout in two important ways. First, it creates test conditions for competing theories of voter turnout 
in one of the most common election types in America -- non-partisan school board 
elections. Second, it provides an important update to the prior literature on school board election participation by explicitly measuring voter turnout in school board 
elections and investigating several hypothesized drivers of voter participation 
in such elections \citep{RefWorks:311,RefWorks:243,RefWorks:340}.  

\subsection{Voter Turnout in School Board Elections}

Several competing conceptions of voter turnout can be explored at the local level 
through the lens of turnout in school board elections. Table \ref{tab:turnoutH} lists 
the evidence in school board turnout that would be consistent with the dominant 
theories of voter turnout discussed above. 


\begin{table}[h!]
\begin{center}
\begin{small}
\caption{Theories of Turnout and Expected Evidence}
\label{tab:turnoutH}
\begin{tabular}{| p{.25\textwidth} | p{.2\textwidth} | p{.375\textwidth} |}
\hline
\textbf{Theory}  & \textbf{Citation} & \textbf{Expected Finding} \\ \hline
Habit-forming voters  & \citet{Plutzer2002} & High autocorrelation in turnout\\ \hline
Rational voters & \citet{Mueller3, aldrich1993} & Smaller electorate has higher turnout \\ \hline
Social group led voting &\citet{Fowler2005} & Union membership as share of electorate drives up turnout \\ \hline
Pivotal-voter & \citet{Downs57} & Small electorate and close election drives turnout up \\ \hline
Social group led voting &\citet{Fowler2005} & Polarized communities have higher turnout \\ \hline
\end{tabular}
\end{small}
\end{center}
\end{table}

I now turn to the data that I bring to bear in investigating these theories. 

\section{Data}
\label{sec:turnData}

This study tests competing theories of voter turnout on a dataset representing 
school board elections in the state of Wisconsin from 2002-2012. The data come 
from 310 of Wisconsin's 424 school districts and are described in 
detail in Chapter \ref{chap:wisco} and Appendix \ref{app:data}.

\subsection{Dependent Variables}

I start by describing the two unique dependent variables used in this chapter. 
The first is a straightforward estimate of the voter turnout in Wisconsin spring 
school board elections. The next variable represents the distance between turnout 
for the top ticket spring race and the school board race. This variable is an 
attempt to separate out the influence of statewide races in the spring elections 
on any measurement of the effect of key variables on school board election 
participation.

\subsubsection{Spring Turnout}
As I demonstrated in Chapter \ref{chap:wisco}, the spring elections in Wisconsin are low turnout. 
One reason prior studies may not have chosen to focus on school board turnout is the 
lack of availability of data or election records to construct an accurate measure of 
turnout.\footnote{Indeed, this is a problem for election officials even within Wisconsin. When 
a school board recall was initiated it was unclear how to determine the number of signatures 
necessary to hold an election due to confusion about how to determine the threshold of 25\% of the 
prior presidential vote within the boundaries of the school district.}
Estimating school board election turnout is not straightforward because it requires 
both a reliable assessment of the votes cast in the election and a reliable 
estimate of the voting age population in the school district. Due to the fact that 
school districts have diverse electoral structure and no requirements 
on election reporting to a central authority, it is often difficult to ascertain 
the number of voters within the school district. In order to combat this I use 
the number of votes cast divided by the number of winners for each race within a 
school district. I then aggregate the races when there is no district wide race, and 
when a district wide race is present, I use the maximum turnout in that race. 

For the denominator I use the voting age population (VAP) as a measure of the 
number of eligible voters in the district boundaries -- this measure is the 
only measure reliably calculated on a regular basis at the level of detail 
necessary to produce school district specific estimates. To determine the 
voting age population (VAP) of the school district in Wisconsin, I
employ the finest resolution estimate of voting age population available -- VAP
estimates by minor civil division (MCD) conducted by the Wisconsin Department of
Administration described in Chapter \ref{chap:wisco} Section 
\ref{subsec:turnout}.\footnote{Available online: \url{http://gab.wi.gov/elections-voting/results}. Statistics for Wisconsin Minor Civil Divisions are maintained by the Department of Administration Demographic Services Center: \url{http://www.doa.state.wi.us/section\_detail.asp?linkcatid=11\&linkid=64\&locid=9}} 
With this method, I am able to estimate the voter turnout 
for each school district in Wisconsin school board elections as well as on 
presidential, gubernatorial, and non-partisan spring elections. 

\subsubsection{Voter Rolloff}

Another dependent variable to look at is school board vote independent of turnout 
higher up the ticket known as the undervote or rolloff \citep{wattenberg00}. As 
voters move down the ballot, many of them simply stop voting and turn in an incomplete 
ballot, a decision based on the increasing discomfort of voters with making decisions 
on races for which they have little to no interest and/or information. As I showed 
in Section \ref{subsec:undervote}, rolloff varies year to year in districts 
providing hope that some of this variation can be explained by theories of voter
turnout. This variable provides an alternative measure of voter engagement with 
school board elections by measuring what share of the total spring electorate is 
disengaged with school board elections. A disadvantage of this study period in Wisconsin 
is that turnout rose in 2011 due to the heightened interest in the state supreme court 
election between David Prosser and Joanne Kloppenburg. This makes it difficult 
to attribute heightened school board voter turnout year to year to school boards 
when the turnout for the top ticket race changes year to year and can do 
dramatically. 

To construct this measure for the 2007-2012 period, I estimate the top ticket 
turnout in each school district. Importantly, in this period, several different 
office types were the top ticket due to the pattern of statewide office terms 
in Wisconsin. These consist of primarily state supreme court races, but as there 
seven justices elected to ten-year terms, the state supreme court does not have 
an election every spring: 

\begin{myitemize}
  \item 2007 - State Supreme Court Race
  \item 2008 - State Supreme Court Race and presidential primary
  \item 2009 - State Superintendent of Public Instruction
  \item 2010 - None. Wisconsin Appeals Courts (3 of 4)
  \item 2011 - State Supreme Court Race
  \item 2012 - Presidential Preference Primary
\end{myitemize}

If top ticket races drive voter turnout, then examining the degree to which school 
board turnout leads or lags top ticket races may provide some insight into the 
political activity in school board races independent of such races. Voter rolloff 
after the top ticket arises for a number of reasons including ballot design, 
lack of information, and the complexity of choices facing the voter in a given 
election \citep{wattenberg00}. In the non-partisan context of judicial elections, 
there is evidence that rolloff is lessened in competitive races where information 
is increased \citep{streb09}.\footnote{For further details on how rolloff was 
calculated and the imputation methods used for estimating rolloff in districts 
without a top ticket race, see Section \ref{subsec:undervote} in Chapter \ref{chap:wisco}}

The estimated difference in school board turnout to top ticket 
turnout can be one way to measure the political interest of voters in school 
boards in particular. A disadvantage of this measure is that school board is 
not the only down-ticket race and rolloff does not measure voter interest as 
many voters do not abstain despite not interest or knowledge of the school board 
race. 

\subsection{Key Independent Variables}

I describe the key variables for the theories in Table \ref{tab:turnoutH} 
and how I operationalize them with Wisconsin data. I start with the models based on 
electorate size and explore if at the  small electorate sizes common in school 
board elections there is evidence that voters are more likely to turnout than 
in larger school board races. I use VAP as an estimate of the actual electorate size 
in school board elections. This is a conservative measure given that the actual spring 
electorate can be as small as 15\% of the voting age population.\footnote{If is is assumed that voters 
adjust the electorate size equally across jurisdictions when making their 
assessment of the perceived utility of voting, then this is not a factor. If there 
is evidence that voters in different jurisdictions have more information about 
the likely electorate size in a school board election, and this varies across 
jurisdictions, then this becomes more problematic.}

Figure \ref{fig:turnoutSize} shows that there is 
a consistent negative relationship between electorate size and school board 
election turnout across the years of data available in Wisconsin. As population 
increases, Wisconsin school board elections have lower turnout with a correlation of 
\Sexpr{iNum2(cor(dist_turn$turnout, dist_turn$VAP_adj, use = "pairwise.complete.obs"))}. 
This correlation is consistent across years with the exceptions of 2004 and 
2012. This fits with the predictions of rational choice approaches which 
state that in a small electorate a voter can expect their vote to matter more 
in the outcome and thus increase the potential benefits associated with voting
\citep{Mueller3, aldrich1993, Downs57}. However, this does not represent a full test 
of this theory, as voters are also voting up ticket in statewide non-partisan races 
such as Supreme Court and State Superintendent, and school board turnout is also
driven by these races.\footnote{ They may not though because up ticket races have 
a statewide electorate and little chance for influence by individual voters.} 


<<turnoutSize, echo=FALSE, fig.scap="Turnout in School Board Elections based on Electorate Size", fig.height=3.15, fig.cap="Correlation coefficient between school district voting age population and school board election turnout. Each line represents the 95 percent confidence interval.">>=
plotdf <- dist_turn[dist_turn$turnout < 0.95, c("year", "VAP_adj", "turnout")]
plotdf <- na.omit(plotdf)

detach("package:plyr")
library(plyr)
plotdf2 <- ddply(plotdf, .(year), summarize, 
                 corLow = cor.test(VAP_adj, turnout)$conf.int[1], 
      cor = cor.test(VAP_adj, turnout)$estimate, 
      corHi = cor.test(VAP_adj, turnout)$conf.int[2])

ggplot(plotdf2, aes(x = factor(year), 
                    ymin = corLow, ymax = corHi, y = cor)) + 
  geom_pointrange() + 
  geom_hline(yintercept = 0,  color = I("red"), linetype = 4) + 
  theme_dpi() + labs(x = "Year", y = "Correlation Coefficient")

@

<<turnoutHide, fig.show='hide', echo=FALSE>>=
qplot(VAP_adj, turnout, data = na.omit(plotdf)) + facet_wrap(~year) + 
  geom_smooth(se = TRUE, method = "rlm") + theme_dpi() + 
  scale_y_continuous(label = percent) + 
  scale_x_log10(label = comma)+
  labs(x = "Voting Age Population (log-scale)", y = "School Board Turnout", 
       title = "Comparing Turnout and Size of Electorate")
@

<<turnoutCompetitive, eval=FALSE, results='hide', echo=FALSE, fig.scap="Turnout in School Board Elections based on Contestation",fig.cap="Histogram showing the distribution of turnout for each type of contestation. The vertical red line represents the median of the distribution.">>=
dist_turn$contestINC[dist_turn$nrealcand <= dist_turn$nwins & dist_turn$ninc == 0] <- "Open Uncontested"
dist_turn$contestINC[dist_turn$nrealcand <= dist_turn$nwins & dist_turn$ninc > 0] <- "Incumbent Uncontested"
dist_turn$contestINC[dist_turn$nrealcand > dist_turn$nwins & dist_turn$ninc > 0] <- "Incumbent Contested"
dist_turn$contestINC[dist_turn$nrealcand > dist_turn$nwins & dist_turn$ninc ==0] <- "Open Contested"

dist_turn$incumbent <- "Open"
dist_turn$incumbent[dist_turn$ninc > 0] <- "Incumbent"
dist_turn$contest <- "Open"
dist_turn$contest[dist_turn$nrealcand > dist_turn$nwins] <- "Contested"


tempdf <- dist_turn[!is.na(dist_turn$turnout) & dist_turn$turnout < 0.95,
                    c("turnout", "contestINC", "contest")]
tempdfG <- aggregate(tempdf[1], tempdf[2], median, na.rm=TRUE)


qplot(turnout, data = tempdf,
      color = I("gray90")) +  
  theme_dpi() + 
  facet_wrap(~contestINC, ncol = 1) +
  scale_x_continuous(label = percent) + 
  labs(x = "Turnout in School Board Elections", fill = "Type of Contestation", 
       y = "Count of Races",
       title = "Turnout and Race Typology in School Board Elections") + 
  geom_vline(data = tempdfG, mapping = aes(xintercept = turnout), 
             color = "red", size = I(1.1))
rm(tempdf)
@

Having competitive races is critical in driving voter turnout, as voters have 
very little reason to vote if they are not presented with a meaningful choice. 
Measuring competitiveness in conjunction 
with turnout is a difficult methodological task, but often some measure of the final 
election margin is used as a proxy for the pre-election competitiveness of the race 
anticipated by voters. Following the argument of \citet{cox88}, I avoid using the 
percentage margin of victory due to the fact that it shares a denominator with 
the dependent variable, voter turnout. Instead, I use the Blais-Lago quotient used in 
Chapters \ref{chap:wisco} and \ref{chap:candidacy}.\footnote{For simplicity I have 
rescaled this measure so that 100 represents a race decided by a single vote, 
and 0 represents races that are uncontested.}

Figure \ref{fig:competition} shows all the races for which records are available 
with the competitiveness measures on the x-axis and the turnout in the 
corresponding school board turnout on the y-axis. There is a very slight positive 
effect of more competitive (higher value on the X-axis) races on 
voter turnout.\footnote{This figure excludes races with turnout greater than 95\% 
which are likely due to extremely low numbers of voters or recording error. Clumping 
occurs at 75\% and 88\% due to the most common configurations of the number of 
candidates and number of winners in school board races.}
How informed voters are about the competitiveness of their school board races 
prior to the election is unclear. There are many reasons to believe voters 
have little to no pre-election information about the closeness of their board 
races -- due to a lack of polling information and the low-level campaigning 
common in school board races \citep{RefWorks:321, RefWorks:217, RefWorks:322}. 
However, the electorate in Wisconsin school board elections is very different than 
the fall partisan electorate, and evidence from other jurisdictions suggests such 
off-cycle local voters are much more engaged, informed, and politically active 
than general election voters \citep{oliver}. This remains an empirical question.


<<competition, fig.scap="Blais-Lago and Turnout", fig.cap="Blais-Lago quotient and turnout are slightly positively correlated. Each dot represents a district-year observation, with more competitive elections indicated by higher Blais-Lago quotients.",fig.height=4.5>>=
plotdf <- dist_turn[dist_turn$year > 2004, c("year", "minBlaisLago", "turnout")]
plotdf <- plotdf[plotdf$turnout < 0.95 & plotdf$minBlaisLago <= 100 & 
                   plotdf$minBlaisLago > 50,]
plotdf <- na.omit(plotdf)

qplot(minBlaisLago, turnout, data = plotdf) +  
  theme_dpi() + geom_smooth(method = 'lm') +
  scale_y_continuous(label = percent, breaks = seq(0, 1, by = .10)) + 
  scale_x_continuous(breaks = c(0, 25, 50, 75, 85, 90, 95, 100)) + 
  labs(y = "Turnout in School Board Elections", 
       x = "Blais-Lago Quotient",
       title = "Turnout and Competitiveness in School Board Elections") 
 
# plotdf2 <- ddply(plotdf, .(year), summarize, 
#                  corLow = cor.test(minBlaisLago, turnout)$conf.int[1], 
#       cor = cor.test(minBlaisLago, turnout)$estimate, 
#       corHi = cor.test(minBlaisLago, turnout, )$conf.int[2])
# 
# ggplot(plotdf2, aes(x = factor(year), 
#                     ymin = corLow, ymax = corHi, y = cor)) + 
#   geom_pointrange() + 
#   geom_hline(yintercept = 0,  color = I("red"), linetype = 4) + 
#   theme_dpi() + labs(x = "Year", y = "Correlation Coefficient")


@

Figure \ref{fig:turnoutAutocorrelation} explores how habit forming turnout may be 
in spring elections in school districts \citep{Plutzer2002}. Using a two-year lag 
of turnout, Figure \ref{fig:turnoutAutocorrelation} shows a consistently high 
positive correlation between lagged and current turnout, averaging 
\Sexpr{iNum2(cor(dist_turn$turnout, dist_turn$turnoutLag2, use = "pairwise.complete.obs"))}.\footnote{For a single year lag, the corresponding correlation is 
\Sexpr{iNum2(cor(dist_turn$turnout, dist_turn$turnoutLag1, use = "pairwise.complete.obs"))} and the 
year to year pattern is largely similar.} Turnout is also correlated with turnout 
in fall elections as well. I construct a measure of fall turnout using the average 
turnout in the two most recent fall general elections (Gubernatorial and Presidential), which correlates positively with school board turnout at 
\Sexpr{iNum2(cor(dist_turn$turnout, dist_turn$fallTurnout, use = "pairwise.complete.obs"))}.


<<turnoutAutocorrelation, echo=FALSE, fig.scap="Turnout in School Board Elections Correlated with Prior Turnout", fig.cap="Correlation coefficient between twice lagged turnout and turnout across years. Correlation is depicted with 95 percent confidence interval.", fig.height=3.2>>=
plotdf <- dist_turn[dist_turn$turnout < 0.95 & dist_turn$year > 2004,
                    c("year", "turnoutLag2", "turnout")]
plotdf <- na.omit(plotdf)
library(plyr)
plotdf2 <- ddply(plotdf, .(year), summarize, 
                 corLow = cor.test(turnoutLag2, turnout)$conf.int[1], 
      cor = cor.test(turnoutLag2, turnout)$estimate, 
      corHi = cor.test(turnoutLag2, turnout)$conf.int[2])

ggplot(plotdf2, aes(x = factor(year), 
                    ymin = corLow, ymax = corHi, y = cor)) + 
  geom_pointrange() + 
  geom_hline(yintercept = 0,  color = I("red"), linetype = 4) + 
  theme_dpi() + labs(x = "Year", y = "Correlation Coefficient")


@
% Turnout and group membership

<<lagplotHide, fig.show='hide', fig.cap="Lagged and current turnout across time.">>=
qplot(turnoutLag2, turnout, data = plotdf) +
  facet_wrap(~year) + theme_dpi() + geom_smooth(method = 'rlm') + 
  scale_x_continuous(label = percent) + 
  scale_y_continuous(label = percent) + 
  labs(x = "Lagged School Board Turnout (2 year lag)", y = "School Board Turnout", 
       title = "Comparing Lagged Turnout")
@

<<unionInf, echo=FALSE, fig.scap="Turnout in School Board Elections Correlated with School Staff Share",fig.height=3.5, fig.cap="Correlation between school board turnout and teacher share of voters in prior school board election. Correlation coefficient with 95 percent confidence interval.">>=

plotdf <- dist_turn[dist_turn$year > 2004, c("year", "teachShareofVoters2", "turnout")]
plotdf <- na.omit(plotdf)

plotdf2 <- ddply(plotdf, .(year), summarize, 
                 corLow = cor.test(teachShareofVoters2, turnout)$conf.int[1], 
      cor = cor.test(teachShareofVoters2, turnout)$estimate, 
      corHi = cor.test(teachShareofVoters2, turnout)$conf.int[2])

ggplot(plotdf2, aes(x = factor(year), 
                    ymin = corLow, ymax = corHi, y = cor)) + 
  geom_pointrange() + 
  geom_hline(yintercept = 0,  color = I("red"), linetype = 4) + 
  theme_dpi() + labs(x = "Year", y = "Correlation Coefficient")
@

<<unionInfhide, fig.show='hide'>>=
qplot(teachShareofVoters2, turnout, 
      data = plotdf) + 
  geom_smooth(method="rlm") + theme_dpi() +
  facet_wrap(~year)+ 
  scale_x_continuous(label = percent) + 
  scale_y_continuous(label = percent) + 
  labs(x = "Teacher FTE as Share of VAP", y = "School Board Turnout", 
       title = "Turnout to Staff Share of School Board Electorate")
@

With a reduced electorate, school board elections are an interesting case to study 
the role substantial interest groups can play in an election. \citet{Fowler2005} 
provides the premise that cohesive social groups can increase turnout by activating 
their members to vote. \citet{RefWorks:207} suggests that unionized teachers are 
just one such group and provides evidence of school board elections being influenced 
substantially by such groups. To evaluate this, I construct a measure of the potential 
strength of the teachers' union by using the number of teachers employed by the district 
divided by either the voting age population or the turnout in the prior school board 
election.\footnote{To avoid issues with cyclical school board elections and endogeneity I 
use twice lagged turnout.} Figure \ref{fig:unionInf} shows the turnout in the school board election 
compared to the percentage of teachers in the prior school board election. This comparison 
illustrates how large of a voting block a cohesive teacher union might estimate they possess based 
on the number of votes cast in previous elections.\footnote{This data comes from 
the DPI PI-1202 Fall Staffing Report. Another measure, the share of VAP that is 
made of licensed teachers is also used below, but has largely the same pattern.}
The relationship shown in Figure \ref{fig:unionInf} is not what theory would expect. 
Here a higher teacher share of the prior school board turnout is associated with depressed 
turnout rates, instead of elevated turnout. The average correlation across years is 
\Sexpr{iNum2(cor(dist_turn$teachShareofVoters2, dist_turn$turnout, use = "pairwise.complete.obs"))}. 
I will pursue this finding further with statistical models, 
but it is worth noting that there may be limits on the impact social groups can have 
on driving up turnout before they capture the electorate and thus reduce 
competitiveness and turnout. In fact, \citet{RefWorks:207} would argue 
this represents the ideal condition for a union, freeing their members from the need 
to be politically active and influencing the school board through the 
candidate recruitment and nomination process instead. 

Figure \ref{fig:partisan2} takes a different approach to this problem by looking 
at the information voters may have about their community -- the level of partisan 
polarization. Using the average Democratic share of the two-party vote from the prior 
Gubernatorial and Presidential election combined, I explore the variation in school
board election turnout explained by far away the two party vote share is from an 
even 50/50 split. Theory would suggest that the more divided a community is on 
partisan issues, the greater the impetus to vote \citep{Fowler2005}. Figure 
\ref{fig:partisan2} shows the annual correlation between higher partisan unity and 
turnout. In most years there is almost no relationship, but in 2011 and 2012 there 
appears to be an uptick in school board turnout associated with more strongly 
partisan school districts. The correlation is \Sexpr{iNum2(cor(dist_turn$turnout, 
dist_turn$partyDivisionRecent, use = 'pairwise.complete.obs'))} across all years 
but significantly stronger in 2011 and 2012.

<<partisan2, fig.scap="Correlation Between Turnout and Partisanship", fig.height=3.5, fig.cap="Correlation coefficient between fall general election partisanship and ">>=
plotdf <- dist_turn[dist_turn$year > 2004, c("year", "partyDivisionRecent", "turnout")]
plotdf <- plotdf[plotdf$turnout < 0.95 & !is.na(plotdf$turnout), ]
plotdf <- na.omit(plotdf)


plotdf2 <- ddply(plotdf, .(year), summarize, 
                 corLow = cor.test(partyDivisionRecent, turnout)$conf.int[1], 
      cor = cor.test(partyDivisionRecent, turnout)$estimate, 
      corHi = cor.test(partyDivisionRecent, turnout)$conf.int[2])

ggplot(plotdf2, aes(x = factor(year), 
                    ymin = corLow, ymax = corHi, y = cor)) + 
  geom_pointrange() + 
  geom_hline(yintercept = 0,  color = I("red"), linetype = 4) + 
  theme_dpi() + labs(x = "Year", y = "Correlation Coefficient")

@

Taken alone, these figures do not suggest that any of the theories in Table \ref{tab:turnoutH} are confirmed or denied, but it does help illustrate the diversity 
of school board elections in Wisconsin and the need for statistical models 
to help separate out competing explanations that may themselves be highly 
correlated or confound one another. 

<<partisan2hide, fig.show='hide'>>=

qplot(partyDivisionRecent, turnout, 
      data = plotdf) + facet_wrap(~year) + 
  geom_smooth(se = TRUE, method = 'rlm') + theme_dpi() + 
  scale_x_continuous(label=percent) + 
  scale_y_continuous(label = percent) + 
  labs(x = "Partisan Unity", y = "School Board Turnout", 
       title = "Turnout and Voter Partisanship")
@

\subsection{Control Variables}

In addition to the variables of interest shown above, it is necessary to include 
some common demographic control variables. Political scientists have long established 
the strong relationship between certain demographic characteristics and voter 
turnout in partisan elections. In order to understand the effect of other variables 
on turnout, it is desirable to remove as many other explanations as possible 
given the availability of data. Fortunately, using US census data, an abundance 
of data is available on the population of Wisconsin school districts. 


<<demog1, fig.scap="Correlation Plot of Demographic Variables and Turnout across Sample", fig.height = 8, fig.width=8, fig.cap="Cells are shaded in proportion to the magnitude and direction of the bivariate correlation across all observations in the sample.">>=
library(reshape)
nopanel <- theme(panel.background=element_blank(),
                 panel.grid.minor=element_blank(),
                 panel.grid.major=element_blank(),
                 axis.text.x = element_text(angle = -90, hjust = 0), 
                               axis.text = element_text(colour = "black"))

pairLabels <- c("Turnout", "Fall Turnout", "% 65 Older", "% Bach. +", "OOH %", 
                "Median Income", "Log VAP")
corVars <-  c("turnout", "fallTurnout", "per65o", "PerBachelorOrAbove", 
                   "OOH_share", "median_incomeLOG", "VAP_adj")

tempdf <- dist_turn[!is.na(dist_turn$turnout), which(names(dist_turn) %in% corVars)]
tempdf <- tempdf[, corVars]
names(tempdf) <- pairLabels

cormat <- melt(round(cor(tempdf, use = "pairwise"), 3)) 

cormat$value2 <- cut(cormat$value, 
                     breaks=c(-1,-0.75,-0.5,-0.25,0,0.25,0.5,0.75,1), 
                     include.lowest=TRUE, 
            label=c("(-0.75,-1)","(-0.5,-0.75)","(-0.25,-0.5)","(0,-0.25)",
                    "(0,0.25)","(0.25,0.5)","(0.5,0.75)","(0.75,1)")) 

qplot(x=X1, y=X2, data=cormat, fill=value2, geom="tile", color = I("gray40")) + 
  scale_fill_brewer(palette = "RdYlGn",name="Correlation", 
                    breaks = levels(cormat$value2), drop =FALSE)+
  geom_text(aes(label = value), size = 4) + nopanel + 
  labs(x = "", y = "") + theme(legend.position = "none")

@

Figure \ref{fig:demog1} uses a correlation matrix to examine the relationships between 
these dependent variables and the outcome for all complete observations in the 
data. The pairwise correlation of the variables is printed in each cell which 
represents the bivariate correlation. Additionally, the cells are shaded to 
distinguish the direction and strength of the correlation. 

From this figure it is clear that turnout is only weakly positively correlated 
with these demographic controls, except district size and share of the population 
over 65 years of age which have the strongest correlations. There are also strong
relationships between these individual demographic categories, with particularly 
strong relationships between education, age, and income, as well as a strong 
negative between age and owner occupied housing and age and education level.

It is important to note that all of these variables are much more highly 
correlated with fall turnout than with spring turnout. This provides some evidence 
that the school board electorate is different than the general election 
electorate -- as shown by \citet{oliver}. 

\section{Methods}

This paper has two main methodological approaches to evaluating theories of voter 
turnout in school board elections. The first follows on several empirical studies 
of theories of voter turnout to compare the power of various theories of voter 
turnout to one another \citep{Larcinese, Lapp99, KanYang2001,Coate2008582}. The 
second approach investigates more narrowly the gap between voters voting at the 
top of the spring election ticket, and votes for school board. While overall 
spring election turnout may be driven by the presence of a partisan primary 
or a non-partisan statewide election, the gap between votes cast in that election 
and the school board election narrowing should be attributed to increased interest 
by voters in school board elections. 

\subsection{Estimation Equations}
Each model is fit twice, once with turnout as the dependent variable and once for 
rolloff. For each variable I use multiple specifications to test the robustness of the 
relationship to varying assumptions. I start with a specification that pools 
observations across years and districts and estimates the impact of the key independent 
variable and a few key demographic control variables described in Section 
\ref{sec:turnData}. These equations look like: 

\[(1) \hspace{0.4 in} VP_{it} = \alpha + \beta X_{t} + \psi Z_{it}+\epsilon_{t} \] \\

Here $VP_{it}$ is voter turnout in a school district $i$ for the spring election $t$. 
$\alpha$ is the intercept and $X_{it}$ represents a vector of covariates including the 
control variables described above for school district $i$ in year $t$. All models control for 
competition, demographic covariates, district size, and whether or not turnout was measured by a district 
wide race.\footnote{The district wide variable is a dummy variable to control for the 
measurement error associated with school districts where there was no district wide 
race to estimate voter turnout in board elections from.} I include the term $Z_{it}$ to represent the variable 
of interest in each model. The $Z_{it}$ vector includes different variables across 
the different models including lagged turnout, district size, race competitiveness, and 
social group membership in the school district. 

The size of the electorate is important in many theories of voter turnout. 
\citet{dahl1973size} hypothesized that the motivation to participate would be higher 
in small electorates, and there has been some evidence to support this \citep{Frandsen2002}. 
Thus, in all models size is included in the $X_{it}$ vector and in 
some models it is included as an interaction to test for differential impacts 
of key variables across the size of the electorate. 

The pivotal-voter model is a subset of the rational voter model. I use a 
similar method as \citet{Coate2008582} to test whether turnout is higher in elections 
that are closer and if this effect is greater in smaller electorates.
Thus I include in the $Z_{it}$ vector a measure of the margin of victory. I also 
include an interaction effect to explore whether or not voters are more likely 
to turn out for close races in small electorates, where their probability of 
deciding the election, is greatest. This interaction model is represented in equation 2. 

\[(2) \hspace{0.4 in} VP_{t} = \alpha + \beta X_{t} + \psi Z_{t} x \lambda S_{t} +
\epsilon_{t} \] \\

Finally, following \citet{Fowler2005}, I investigate the impact that social group 
membership may have on voting by this time including a measure of the size of the 
social group in the community in the $Z_{t}$ vector. I explore a separate model 
for each type of social group -- the partisanship of the school district in partisan statewide elections, or the share of the total electorate that is teachers. There 
has been little work explicitly testing the influence of political parties in 
non-partisan school board races, but some evidence that the 
share of teachers in the electorate is an important driver of turnout and 
policy change in school board elections \citep{RefWorks:207, 
RefWorks:218,RefWorks:320}.


\subsection{Model Specifications}
\label{subsec:spec}
The equations represented above are stylized representations of simple OLS models 
that treat each district-year as an independently distributed observation. In 
reality, the data is more complex and requires some additional model features 
to appropriately estimate the impact of key variables on turnout. I outline 
two separate methods. 

The first method is a simple extension of the pooled linear regression 
model that includes fixed effects for years and for school districts. This 
eliminates time-invariant unobservable district characteristics as well as 
election specific unobservable characteristics between districts. However, 
the standard errors from these models are overly optimistic because each 
school district is observed between two and ten times and the assumption of independent 
and identically distributed random variables is violated. To correct for this, 
I adjust the standard errors by using the Huber-White estimator of the covariance 
matrix.\footnote{I do this with the \texttt{robcov} function implemented in 
\citet{rms}'s \texttt{rms} R package.} This will correct for the clustering of 
school districts between the observations and avoid overly optimistic standard errors for 
the $\beta$ coefficients \citep{hwhite,hwhite2,pjhuber}.

Results from these models are placed in Appendix \ref{sec:appendixT}. 
However, there are many reasons to doubt the validity of the fixed effect 
specification. First, the district fixed effects are overly conservative as 
many of the key underlining predictors are not highly variable year to year 
within districts and number of observations per district varies. The district 
estimates themselves are problematic, the model is likely underpowered to fit 
them properly and they are likely too sensitive to outliers and therefore overfit. 
There are two approaches to adjusting for this -- penalized estimation or partial 
pooling approach using a mixed effect model. The partial pooling approach is also known as a mixed 
effect or hierarchical linear model (HLM).\footnote{Partial pooling models can be fit in R 
using the \texttt{lme4} package \citep{lme4, gelhill}.} I employ the same 
specification as the fixed effect model before, but now model the district effects 
as random effects in order to avoid overfit. 

The formal econometric results suggest that the random effects of the multilevel 
model are appropriate.\footnote{The Hausman test 
can be used to formally test the specification of random or fixed effects and the 
results of this test for all models is included in the Methodological Appendix 
\ref{sec:appendixT} \citep{haustest}.} The choice between these two approaches is as 
much theoretical as it is econometric, and as a result I run my analyses with both 
approaches. It is also useful because this approach is flexible for cases with unbalanced 
repeated measures and allows the analyst to disentangle the effects of time 
specific variables from the overall variability among individual units, e.g. school 
districts \citep{mlmod,raudbryk}. Furthermore, my data does not 
include all Wisconsin school districts, but instead a large sample of districts. 
This makes the ability to model the variation between districts of interest to 
understand the range of plausible district variation across the broader population 
of school districts -- an attractive feature of the mixed model approach.

The equation below depicts the multilevel framework:

\begin{align*} 
VP_{ij} &= \alpha + \gamma_{j} + \beta X_{ij} + \lambda Z_{ij} + \epsilon_{ij}  \\ 
\gamma_{j} &=  \alpha_{j} + \epsilon_{j}
\end{align*}

The only difference between this approach the linear models with equations above 
is the presence of a unique intercept for each school district \emph{j}. 
Here the $\gamma_{j}$ terms represent independent intercepts for each school 
district as predicted by $\alpha_{j}$, a unique intercept for each school district. 
$X_{ij}$ is a vector of time variant school district 
characteristics such as prior turnout. In the mixed-effect 
framework the $\gamma_{j}$ are assumed to be drawn from a normal distribution. 
The equation above is flexible to the inclusion of the other predictors identified. 

This method does not account for the time structure of the data, as no 
explicit parameterization of time is included. As I have no reason to believe that 
time linearly related to voter turnout, this is 
appropriate. However, I do want to control for secular effects of election year 
variability that reaches across districts. One approach would be to include 
fixed effects for years in the $X$ vector. However, the multilevel approach is 
flexible enough to allow for a third group -- years, to be included in the model. 
The model below includes a third grouping level for years. 

\begin{align*} 
VP_{t} &= \alpha + \gamma_{j} + \psi{t} + \beta X_{ijt} + \lambda Z_{ijt} + \epsilon_{ijt}  \\ 
\gamma_{jt} &=  \alpha_{j} + \epsilon_{j} \\
\psi{t} &= \alpha_{t} + \epsilon_{t}
\end{align*}

This approach allows year parameters to be estimated independently without assuming 
a functional form for the relationship between voter turnout and time allowing for 
the model to reflect secular effects of specific elections in the data. 

The proper model of the random effects is important. Using the \texttt{RLRsim} 
package in R, I test the specification of the random effects using an exact 
likelihood ratio test and an exact restricted likelihood ratio test \cite{RLRsim}. 
The first test is used to examine whether the random effects are the appropriate 
specification. The restricted likelihood ratio test is used to compare 
two nested models with different random effect specifications to determine the 
appropriate specification. In this case, a model with random effects for district 
and year was compared against a model with random effects only for district. The 
results of these tests for all of the models is included in the Appendix \ref{sec:appendixT}. 

\subsection{Computation}

<<simpleModel, results='hide'>>=
moddat <- dist_turn[, c("turnout", "turnoutLag2", "turnoutLag1","year", "contest",
                        "fallTurnout", "VAP_adjLOG", "distid", "districtwide",
                        "per_white_all", "per65o", "PerBachelorOrAbove", 
                        "OOH_share", 
                        "median_incomeLOG", "minBlaisLago")]
#moddat <- na.omit(moddat)
moddat <- subset(moddat, turnout < 0.95,)
moddat <- moddat[order(moddat$distid, moddat$year),]
moddat$distid <- factor(moddat$distid)
moddat$year <- factor(moddat$year)
moddat$contest <- factor(moddat$contest)
moddat$turnout <- moddat$turnout * 100
moddat$districtwide <- factor(moddat$districtwide)

nums <- sapply(moddat, is.numeric)
ScaleMeans <- apply(moddat[, nums], 2, mean, na.rm=TRUE)
ScaleSD <- apply(moddat[, nums], 2, sd, na.rm=TRUE)
moddatScaleLag <- cbind(ScaleMeans, ScaleSD); rm(ScaleMeans, ScaleSD)
#Rescale
library(arm)
nums <- sapply(moddat, is.numeric)
moddat[, nums] <- apply(moddat[, nums], 2, rescale)
moddat$VAP_adjLOG_sq <- moddat$VAP_adjLOG^2

naive1 <- lm(turnout ~ turnoutLag2 + fallTurnout + VAP_adjLOG + VAP_adjLOG_sq + 
               per_white_all + per65o + PerBachelorOrAbove + OOH_share + 
               median_incomeLOG + districtwide + minBlaisLago,
             data = moddat)
centr <- mean(moddat$turnout)
stddev <- sd(moddat$turnout)
moddat$outflag <- (moddat$turnout - centr) / stddev
@


Due to the suspicion of measurement issues in the key estimate of turnout, I use 
the approach taken by \citet{berry2} on administrative data and exclude all 
observations that fall outside of five standard deviations of the normal values 
for the dependent variable. There are \Sexpr{table(moddat$outflag>5)[[2]]} cases where 
the value of the dependent variable is more than five standard deviations above 
the group average. This is less than half of 1\% of the observations and is unlikely 
to be influential. Such deviations are likely due to 
measurement error either in the VAP denominator or in the aggregation of district 
board election vote counts themselves. I also use two control variables to adjust 
for measurement error -- the first is a dummy variable indicating whether turnout 
for the top ticket spring race has been imputed and the second is an indicator 
of whether or not there are overlapping district wide and apportioned school board 
seats which may confound the estimate of the number of voters.

Additionally, I grand-center and rescale 
all of my continuous variables in order to speed model convergence and avoid 
computational problems associated with widely varying scales in the underlying 
data. The coefficients reported in the tables below then can be interpreted as 
the effect on the dependent variable in standard deviation terms of moving the 
predictor variable two standard deviations. This standardized regression approach 
is recommended in multilevel modeling, particularly in cases with underlying 
predictors with scales that vary by orders of magnitude like in the present 
case \citep{gelhill}. 

\section{Results}

I now review the results for models for each theory -- 
habit forming voters, rational voters, pivotal voters, and social group motivated 
voters. I first look at evidence for these theories in each of these models for 
an effect on turnout in the spring school board races. Then I apply these same 
models to the rolloff of voters in the spring election. Finally, I conclude by 
interpreting the substantive effect of these characteristics on school board 
election turnout. 

\subsection{Habit Forming Voters}

<<lagmodRLM, results ='hide'>>=
# detach("package:plyr", unload=TRUE)
library(sandwich)
library(rms)
# library(devtools)
# install_github("jknowles/apsrtable", subdir = "pkg", ref = "dev")
library(apsrtable)
moddat <- moddat[moddat$outflag <= 5 & moddat$outflag >= -5,]
moddat <- moddat[moddat$year != "2002",]
moddat$year <- factor(as.character(moddat$year))
dd <<- datadist(moddat)
options(datadist="dd")

dumbRLM1 <- ols(turnout ~ turnoutLag2 + fallTurnout + VAP_adjLOG + VAP_adjLOG_sq + 
                  per_white_all + 
                       per65o + PerBachelorOrAbove + OOH_share + median_incomeLOG + 
               districtwide +  minBlaisLago, data = moddat, x = TRUE, y = TRUE)

dumbRLM1$se <- sqrt(diag(vcov(robcov(dumbRLM1, cluster = moddat$distid))))

dumbRLMbest <- ols(turnout ~ turnoutLag2 + fallTurnout + VAP_adjLOG +
                     VAP_adjLOG_sq + per_white_all + per65o + PerBachelorOrAbove +
                     OOH_share + median_incomeLOG + districtwide +  
               minBlaisLago + factor(year) + factor(distid), data = moddat, x= TRUE, y = TRUE)

dumbRLMbest$se <- sqrt(diag(vcov(robcov(dumbRLMbest, cluster = moddat$distid))))
dumbRLM2 <- ols(turnout ~ turnoutLag2 + VAP_adjLOG + VAP_adjLOG_sq + 
                  per_white_all + per65o + PerBachelorOrAbove +  OOH_share+
                  median_incomeLOG + districtwide + minBlaisLago + factor(year) + 
                  factor(distid), data = moddat, x = TRUE, y = TRUE)
dumbRLM2$se <- sqrt(diag(vcov(robcov(dumbRLM2, cluster = moddat$distid))))

stars.note <- apsrtable:::stars.note
se.note <- apsrtable:::se.note

coefnamesLag <- c("Intercept","Lagged Turnout (2)", "Fall Turnout", "Electorate Size", 
                  "Electorate Size\\textsuperscript{2}", "\\% White", 
                  "\\% Over 65", "\\% Bach. +", "\\% Owner Occupied", 
                  "Median Income", "District-wide", "Competitiveness")

lagmodTab <- apsrtable(dumbRLM1, dumbRLMbest, dumbRLM2, se="robust", 
          label="tab:lagmods", 
          model.names=c("Simple", "Fall Turnout", 
                        "Dist/Year FE"), 
          order = "longest",
          caption = "Models of Lagged Turnout in School Board Elections",
          notes = list("Standard errors clustered at the school district.", 
                       stars.note, 
                       "Year and district fixed effects omitted in models 2 and 3."),
          omitcoef=list("distid", 
                        expression(grep("distid", coefnames, value=TRUE)), 
                        "year", 
                        expression(grep("year", coefnames, value = TRUE))), 
          Sweave=FALSE, coef.names = coefnamesLag, digits = 3,
          stars = "default", size = "scriptsize")

@

The results in Table \ref{tab:meTurnout} show, as expected, voter turnout is 
heavily autocorrelated in school board elections. The higher the prior school board 
election turnout, the higher 
the turnout in the current school board election. The effect is largely the same 
even when controlling for fall turnout and the competitiveness of the races. 
Additionally, as expected, larger districts have lower turnout. Other variables 
are also as expected with more affluent, older, and more educated communities 
showing higher voter turnout in school board elections. These effects are reduced 
once controlling for fall turnout due to the strong relationship between them 
and fall turnout previously noted.\footnote{These relationships are different in
fixed effect models. The inclusion of district fixed effects results in the lagged 
parameter being close to zero because the this estimates only the within-district 
effect of lagged turnout on turnout, which has much less variance than the 
between district variance on turnout and lagged turnout. It remains statistically 
significant.}

An additional benefit of the random effect specification is that it allows me to 
measure the variation between years and between districts. As Table 
\ref{tab:meTurnout} shows, there is substantial between district and between year 
variation in turnout for spring non-partisan school board elections. This 
suggests that time-invariant unobservable characteristics about school districts 
and cross-state election year specific characteristics explain much of the 
turnout in local school board elections.

<<model1robustness>>=
dumbRLM1b <- ols(turnout ~ turnoutLag2 + fallTurnout + VAP_adjLOG + VAP_adjLOG_sq + 
                  per_white_all + 
                       per65o + PerBachelorOrAbove + OOH_share + median_incomeLOG + 
               districtwide +  minBlaisLago, data = moddat, x = TRUE, y = TRUE)

dumbRLM1b$se <- sqrt(diag(vcov(robcov(dumbRLM1, cluster = moddat$distid))))

dumbRLMbestb <- ols(turnout ~ turnoutLag2 + fallTurnout + VAP_adjLOG +
                     VAP_adjLOG_sq + per_white_all + per65o + PerBachelorOrAbove +
                     OOH_share + median_incomeLOG + districtwide +  
               minBlaisLago + factor(year) + factor(distid), data = moddat, x= TRUE, y = TRUE)

dumbRLMbestb$se <- sqrt(diag(vcov(robcov(dumbRLMbest, cluster = moddat$distid))))
dumbRLM2b <- ols(turnout ~ turnoutLag2 + VAP_adjLOG + VAP_adjLOG_sq + 
                  per_white_all + per65o + PerBachelorOrAbove +  OOH_share+
                  median_incomeLOG + districtwide + minBlaisLago + factor(year) + 
                  factor(distid), data = moddat, x = TRUE, y = TRUE)
dumbRLM2b$se <- sqrt(diag(vcov(robcov(dumbRLM2, cluster = moddat$distid))))
stars.note <- apsrtable:::stars.note
se.note <- apsrtable:::se.note
coefnamesLag2 <- c("Intercept","Lagged Turnout (1)", "Fall Turnout", "Electorate Size", 
                  "Electorate Size\\textsuperscript{2}", "\\% White", 
                  "\\% Over 65", "\\% Bach. +", "\\% Owner Occupied", 
                  "Median Income", "District-wide", "Competitiveness")
appA1 <- apsrtable(dumbRLM1b, dumbRLMbestb, dumbRLM2b, se="robust", 
          label="tab:lagmods2", 
          model.names=c("Simple", "Fall Turnout", 
                        "Dist/Year FE"), 
          order = "longest",
          caption = "Models of Lagged Turnout in School Board Elections",
          notes = list("Standard errors clustered at the school district.", 
                       stars.note, 
                       "Year and district fixed effects omitted in models 2 and 3."),
          omitcoef=list("distid", 
                        expression(grep("distid", coefnames, value=TRUE)), 
                        "year", 
                        expression(grep("year", coefnames, value = TRUE))), 
          Sweave=FALSE, coef.names = coefnamesLag2, digits = 3,
          stars = "default", size = "scriptsize")
@


<<lagModMM, results ='asis'>>=
library(lme4)

mixedModlags <- lmer(turnout ~ turnoutLag2 +  VAP_adjLOG + 
                    per_white_all + 
                       per65o + PerBachelorOrAbove + OOH_share + median_incomeLOG + 
               districtwide + 
               minBlaisLago + (1|year) + (1|distid), 
              data = moddat, REML = FALSE)

mixedMod1lagsb <- lmer(turnout ~ turnoutLag2 + fallTurnout + VAP_adjLOG + 
                         VAP_adjLOG_sq + per_white_all + per65o + 
                         PerBachelorOrAbove + OOH_share + median_incomeLOG + 
                         districtwide + minBlaisLago + (1|year) + (1|distid), 
                       data = moddat, REML = FALSE)

coefnamesLag3 <- c("Intercept","Lagged Turnout (2)", "Electorate Size", 
                 "\\% White", 
                  "\\% Over 65", "\\% Bach. +", "\\% Owner Occupied", 
                  "Median Income", "District-wide", "Competitiveness", 
                  "Fall Turnout",  "Electorate Size\\textsuperscript{2}")
tabnote <- "Model includes both year and district random effects modeled as intercepts."

apsrtable(mixedModlags, mixedMod1lagsb, caption = "Partial Pooling Model of Lagged Turnout",
          model.names = c("No Fall Turnout", "Fall Turnout"), 
            label = "tab:meTurnout",  
           notes = list("All variables grand-mean scaled and centered.", 
                       stars.note), 
          Sweave = FALSE, digits = 3, 
          coef.names = coefnamesLag3, stars = "default", size = "footnotesize")
@



<<laggedTurnSens, results='hide', eval=TRUE>>=
library(RLRsim)
# m0 <- lm(turnout ~ turnoutLag2 + fallTurnout + VAP_adjLOG + 
#                     per_white_all + turnoutLag2 * VAP_adjLOG + 
#                        per65o + PerBachelorOrAbove + OOH_share + median_incomeLOG + 
#                districtwide + 
#                minBlaisLago, 
#          data = moddat) # fit the null model
# 
# exactLRT(m = mixedMod1, m0 = m0)

# Test for year specific slopes
m.slope <- update(mixedMod1lagsb, . ~ . - (1|year))
m0 <- update(mixedMod1lagsb, . ~ . - (1|distid))
lagLRT <- exactRLRT(m.slope, mixedMod1lagsb, m0)
lagLRT$callFull <- mixedMod1lagsb@call
lagLRT$callSmall <- m.slope@call
@

\subsection{Rational Voters}

My second empirical question is to examine the relationship between electorate size 
and turnout, and electorate size, margin of victory and turnout.

<<closeModRLM, results ='asis'>>=
moddat <- dist_turn[, c("turnout", "turnoutLag2", "year", "fallTurnout", 
                        "VAP_adjLOG", "distid", "incumShare",
                        "per_white_all", "per65o", "PerBachelorOrAbove", 
                        "OOH_share", "median_incomeLOG", "districtwide", 
                        "contest", "minBlaisLago")]
moddat <- na.omit(moddat)
moddat <- moddat[order(moddat$distid, moddat$year),]
moddat <- moddat[order(moddat$distid, moddat$year),]
moddat$distid <- factor(moddat$distid)
moddat$year <- factor(moddat$year)
moddat$turnout <- moddat$turnout * 100
moddat$districtwide <- factor(moddat$districtwide)
moddat$contest <- factor(moddat$contest)
centr <- mean(moddat$turnout)
stddev <- sd(moddat$turnout)
moddat$outflag <- (moddat$turnout - centr) / stddev
moddat <- moddat[moddat$outflag <= 5 & moddat$outflag >= -5,]

nums <- sapply(moddat, is.numeric)
ScaleMeans <- apply(moddat[, nums], 2, mean, na.rm=TRUE)
ScaleSD <- apply(moddat[, nums], 2, sd, na.rm=TRUE)
moddatScaleClose <- cbind(ScaleMeans, ScaleSD); rm(ScaleMeans, ScaleSD)
nums <- sapply(moddat, is.numeric)
moddat[, nums] <- apply(moddat[, nums], 2, rescale)
moddat$VAP_adjLOG_sq <- moddat$VAP_adjLOG^2
dd <<- datadist(moddat)
options(datadist="dd")

closeRLM <- ols(turnout ~ VAP_adjLOG + per_white_all + 
                  per65o + PerBachelorOrAbove + OOH_share + median_incomeLOG +
                  districtwide + minBlaisLago, 
              data = moddat, x = TRUE, y = TRUE)

closeRLM$se <- sqrt(diag(vcov(robcov(closeRLM, cluster = moddat$distid))))
closeRLM2 <- ols(turnout ~ VAP_adjLOG + VAP_adjLOG_sq + per_white_all + 
                  per65o + PerBachelorOrAbove + OOH_share + median_incomeLOG +
                   districtwide + incumShare + minBlaisLago + factor(year),
              data = moddat, x= TRUE, y = TRUE)
closeRLM2$se <- sqrt(diag(vcov(robcov(closeRLM2, cluster = moddat$distid))))
closeRLM3 <- ols(turnout ~ VAP_adjLOG + VAP_adjLOG_sq+ per_white_all + 
                  per65o + PerBachelorOrAbove + OOH_share + median_incomeLOG +
                   districtwide + incumShare + contest * VAP_adjLOG + factor(year) + factor(distid), 
              data = moddat, x = TRUE, y = TRUE)
closeRLM3$se <- sqrt(diag(vcov(robcov(closeRLM3, cluster = moddat$distid))))
closeRLM4 <- ols(turnout ~ VAP_adjLOG + VAP_adjLOG_sq+ minBlaisLago*VAP_adjLOG + per_white_all + 
                  per65o + PerBachelorOrAbove + OOH_share + median_incomeLOG +
                   districtwide + incumShare + minBlaisLago + factor(year) + factor(distid), 
              data = moddat, x = TRUE, y = TRUE)
closeRLM4$se <- sqrt(diag(vcov(robcov(closeRLM4, cluster = moddat$distid))))


closeCoefs1 <- c("Intercept", "Electorate Size", 
                  "Electorate Size\\textsuperscript{2}", "\\% White", 
                  "\\% Over 65", "\\% Bach. +", "\\% Owner Occupied", 
                "Median Income", "District-wide", "Incumbent Share",
                 "Competitiveness", "Elec. Size x Competitiveness")

closeModTab <- apsrtable(closeRLM2, closeRLM4, se="robust", 
          label="tab:closemods", 
          model.names=c("No Interact", "Interact + Year FE"), 
          caption = "Models of Competitiveness and Turnout in School Board Elections",
          notes = list(se.note, stars.note, "Year and district fixed effects omitted."),
          omitcoef=list("distid", 
                        expression(grep("distid", coefnames, value=TRUE)), 
                        "year", 
                        expression(grep("year", coefnames, value = TRUE))),
          coef.names = closeCoefs1, digits = 3,
          Sweave=FALSE, stars = "default", size = "scriptsize")
@


<<cleanupa, echo=FALSE,results='hide'>>=
rm(ADMIN, VAP_dist, dist.tmp, dvp, errors, plotdf, presTurn, canInterp,
   canInterpIDX, centr, dumbRLM1, dumbRLM1b, dumbRLM2, dumbRLM2b, dumbRLMbest, 
   dumbRLMbestb, i, j)
@

The key coefficient in Table \ref{tab:meClose} is the measure of competitiveness 
and its interaction with electorate size. I use the continuous measure 
of the Blais-Lago quotient to represent how competitive 
the races are, with a higher values corresponding to more competitive races. The 
control variables are the same from those in Table \ref{tab:meTurnout}. As 
expected, uncontested races have lower turnout than contested races. Also, as the 
share of all candidates in the race who are incumbents increases, not unsurprisingly, 
turnout decreases. However, the expectation that the relationship between 
competitiveness and district size would have an effect on turnout is not confirmed 
here - the interaction term is not statistically significant although it is in the 
right direction.\footnote{The fixed effect models are largely the same.}


<<closeModMM, results='asis'>>=
mixedModclose <- lmer(turnout ~  VAP_adjLOG + VAP_adjLOG_sq +
                     per_white_all + 
                    per65o + PerBachelorOrAbove + OOH_share + 
                    median_incomeLOG + districtwide + incumShare +
                  minBlaisLago  + (1|year) + (1|distid), 
              data = moddat, REML = TRUE)

mixedModcloseB <- lmer(turnout ~  VAP_adjLOG +  VAP_adjLOG_sq + 
                     per_white_all + 
                     per65o + PerBachelorOrAbove + OOH_share + 
                     median_incomeLOG + districtwide + incumShare + 
                       contest * VAP_adjLOG + 
                   (1|year) + (1|distid), 
              data = moddat, REML = TRUE)

mixedModcloseC <- lmer(turnout ~  VAP_adjLOG +  VAP_adjLOG_sq + 
                     per_white_all + 
                     per65o + PerBachelorOrAbove + OOH_share + 
                     median_incomeLOG + districtwide + incumShare + 
                       minBlaisLago * VAP_adjLOG + 
                   (1|year) + (1|distid), 
              data = moddat, REML = TRUE)

closeCoefs2 <- c("Intercept", "Electorate Size", 
                  "Electorate Size\\textsuperscript{2}", "\\% White", 
                  "\\% Over 65", "\\% Bach. +", "\\% OOH", 
                  "ln(MedianIncome)", "District-wide", "Incumbent Share", 
                   "Blais-Lago", "VAP x Blais-Lago")


# summary(mixedMod2)
apsrtable(mixedModclose, mixedModcloseC, 
          caption = "Partial Pooling Models of Competitiveness",
          model.names = c("No Interaction", "Interaction"),
            label = "tab:meClose", notes = list(tabnote, stars.note), 
          coef.names = closeCoefs2, digits = 3,
          Sweave = FALSE, stars = "default", size = "footnotesize")

# Results with fallTurnout are largely similar but demographic variables are not 
# significant and less impactful due to collinearity with fall turnout
@

<<closeModSens,results='hide', eval=TRUE>>=
# m0 <- lm(turnout ~  minBlaisLago + VAP_adjLOG + minBlaisLago*VAP_adjLOG + 
#            per_white_all + per65o + PerBachelorOrAbove + OOH_share + 
#            median_incomeLOG + districtwide + 
#                   contest, data = moddat) # fit the null model

# exactLRT(m = refitML(mixedModclose), m0 = m0)

# Test for year specific slopes
m.slope <- update(mixedModcloseC, . ~ . - (1|year))
m0 <- update(mixedModcloseC, . ~ . - (1|distid))
closeLRT <- exactRLRT(m.slope, mixedModcloseC, m0)
closeLRT$callFull <- mixedModcloseC@call
closeLRT$callSmall <- m.slope@call
@

\clearpage

\subsection{Social Groups}

To test the argument that voter turnout may be influenced by interest group 
strength, I combine features from the previous models in an attempt to find 
evidence of such an effect.  


\subsubsection{Teachers' Unions}
<<teachInflRLM, results ='hide'>>=
moddat <- dist_turn[, c("turnout", "turnoutLag2", "year", "fallTurnout", 
                        "VAP_adjLOG", "distid", "per_white_all", "per65o", 
                        "PerBachelorOrAbove", "OOH_share", "median_incomeLOG", 
                        "teachShareofVoters", "districtwide", "incumShare",
                        "minBlaisLago", "teachShareofVoters2")]
moddat <- na.omit(moddat)
moddat <- moddat[order(moddat$distid, moddat$year),]
moddat$distid <- factor(moddat$distid)
moddat$year <- factor(moddat$year)
moddat <- moddat[order(moddat$distid, moddat$year),]
moddat$distid <- factor(moddat$distid)
moddat$districtwide <- factor(moddat$districtwide)
moddat$year <- factor(moddat$year)
moddat$turnout <- moddat$turnout * 100
centr <- mean(moddat$turnout)
stddev <- sd(moddat$turnout)
moddat$outflag <- (moddat$turnout - centr) / stddev
moddat <- moddat[moddat$outflag <=5 & moddat$outflag >= -5,]

nums <- sapply(moddat, is.numeric)
ScaleMeans <- apply(moddat[, nums], 2, mean, na.rm=TRUE)
ScaleSD <- apply(moddat[, nums], 2, sd, na.rm=TRUE)
moddatScaleTeach <- cbind(ScaleMeans, ScaleSD); rm(ScaleMeans, ScaleSD)
nums <- sapply(moddat, is.numeric)
moddat[, nums] <- apply(moddat[, nums], 2, rescale)
moddat$VAP_adjLOG_sq <- moddat$VAP_adjLOG^2
dd <<- datadist(moddat)
options(datadist="dd")

teachRLM <- ols(turnout ~ teachShareofVoters + fallTurnout + minBlaisLago + 
                    VAP_adjLOG + per_white_all + per65o + 
                  PerBachelorOrAbove + OOH_share + median_incomeLOG + 
                  districtwide, data = moddat, x = TRUE, y = TRUE)

teachRLM$se <- sqrt(diag(vcov(robcov(teachRLM, cluster = moddat$distid))))

teachRLM2 <- ols(turnout ~ teachShareofVoters + fallTurnout + minBlaisLago + 
                    VAP_adjLOG + per_white_all + per65o + 
                   PerBachelorOrAbove + OOH_share + median_incomeLOG + 
                   districtwide + year,
              data = moddat, x= TRUE, y = TRUE)

teachRLM2$se <- sqrt(diag(vcov(robcov(teachRLM2, cluster = moddat$distid))))

teachRLM3 <- ols(turnout ~ teachShareofVoters + turnoutLag2 + 
                   minBlaisLago + VAP_adjLOG +
                   VAP_adjLOG_sq + per_white_all + per65o + PerBachelorOrAbove +
                   OOH_share + median_incomeLOG + districtwide + incumShare + 
                   distid + factor(year), 
              data = moddat, x = TRUE, y = TRUE)

teachRLM3$se <- sqrt(diag(vcov(robcov(teachRLM3, cluster = moddat$distid))))

# Interaction model
teachRLM4 <- ols(turnout ~ teachShareofVoters +  
                   turnoutLag2 + minBlaisLago + 
                   VAP_adjLOG +  VAP_adjLOG_sq +
                    per_white_all + per65o + PerBachelorOrAbove +
                   OOH_share + median_incomeLOG + districtwide + incumShare + 
                   teachShareofVoters * VAP_adjLOG + factor(year) +
                   distid, 
              data = moddat, x = TRUE, y = TRUE)

teachRLM4$se <- sqrt(diag(vcov(robcov(teachRLM4, cluster = moddat$distid))))

teachRLM5 <- ols(turnout ~ teachShareofVoters2 + turnoutLag2 + 
                   minBlaisLago + VAP_adjLOG +
                   VAP_adjLOG_sq + per_white_all + per65o + PerBachelorOrAbove +
                   OOH_share + median_incomeLOG + districtwide + incumShare + 
                   distid + factor(year), 
              data = moddat, x = TRUE, y = TRUE)

teachRLM5$se <- sqrt(diag(vcov(robcov(teachRLM5, cluster = moddat$distid))))

# Interaction model
teachRLM6 <- ols(turnout ~ teachShareofVoters2 +  
                   turnoutLag2 + minBlaisLago + 
                   VAP_adjLOG +  VAP_adjLOG_sq +
                    per_white_all + per65o + PerBachelorOrAbove +
                   OOH_share + median_incomeLOG + districtwide + incumShare + 
                   teachShareofVoters2 * VAP_adjLOG + factor(year) +
                   distid, 
              data = moddat, x = TRUE, y = TRUE)

teachRLM6$se <- sqrt(diag(vcov(robcov(teachRLM6, cluster = moddat$distid))))



teachCoefnames <- c("Intercept", "Teacher \\% Electorate", "Lag Turnout", 
                 "Competitiveness", "Electorate Size", "Electorate Size\\textsuperscript{2}", "\\% White", 
                  "\\% Over 65", "\\% Bach. +", "\\% OOH", 
                  "Median Income", "District-wide", "Incumbent Share", 
                  "Teacher \\% X Elec. Size", "Teacher \\% of SB Vote", 
                 "Teacher \\% of SB X Elec. Size")

teachTab1 <- apsrtable(teachRLM3, teachRLM4, teachRLM5, teachRLM6, 
                       se="robust", label="tab:teachmods", 
          model.names=c("RLM + District FE", "+ Interaction", "Measure 2", 
                        "Measure 2 + Interaction"), 
          caption = "Models of Unionization and Turnout in School Board Elections",
          notes = list(se.note, stars.note, "Year and district fixed effects omitted."),
          omitcoef=list("distid", 
                        expression(grep("distid", coefnames, value=TRUE)), 
                        "year", 
                        expression(grep("year", coefnames, value = TRUE))),
          coef.names = teachCoefnames, digits = 3,
          Sweave=FALSE, stars = "default", size = "scriptsize")
@


Table \ref{tab:meInf} provides some evidence to support that teacher's unions 
may have an effect on turnout. The key variables here are the teacher share 
of voters and its interaction with the share of incumbents in the race. I 
expect teachers' unions to be more active and exert more influence on turnout 
when there are more non-incumbents in the race. The main effects of the share 
of voters who are teachers is negative and significant but small. 
The interaction term is negative, which suggests that as fewer incumbents are in 
the race and unions are stronger, turnout is suppressed. However, this effect is 
not statistically significant. 

Judging statistical significance of interaction predictors, however, is notoriously 
difficult -- particularly in mixed-effect models. I return to demonstrating the 
effect of these variables later using simulation methods to show their substantive 
impact on voter turnout as predicted by the model. Other variables follow their 
expected signs, although some like competitiveness have a smaller effect than 
in prior models.\footnote{The models reported here use teacher share of the 
number of voters in the school board election two years prior. This is used to 
avoid endogeneity and to better reflect the strategic interaction between school 
board vote turnout and district size. Using the teacher share of VAP results in 
the same sign, but statistically insignificant effects.} 

This result is counter to the theoretical expectations described above where more 
union membership would drive turnout up as a greater share of the population would 
have a stronger interest in school board outcomes. However, this is in line with 
the observed bivariate correlation between teacher share and turnout. In fact, 
the effect is understandable. If voters believe the school board election to 
be captured by a large interest group, they have  less of an incentive to vote.
The threat of controlling the spring electorate for an interest group is enough 
to deter unorganized voters from participating. This type of behavior is the 
type of behavior that worries critics of special purpose governments like 
school districts \citep{fosterK,burnsN,berry2}.

<<teachInfMM, results='asis'>>=
teachCoefnames2 <- c("Intercept", "Teacher \\% SB Vote",  
                 "Competitiveness",  "Electorate Size",  "Electorate Size\\textsuperscript{2}", 
                  "\\% White", "\\% Over 65", "\\% Bach. +", "\\% Owner Occupied", 
                  "Median Income", "District-wide", "Incumbent Share",
                  "Teacher \\% of SB X Inc Share")
# what happens if I cut out lags

mixedModteach <- lmer(turnout ~ teachShareofVoters +  minBlaisLago +   
                    VAP_adjLOG + VAP_adjLOG_sq + per_white_all + per65o + 
                      PerBachelorOrAbove +
                   OOH_share + median_incomeLOG + districtwide +  incumShare +
                   teachShareofVoters + (1|year) +  (1|distid), 
              data = moddat, REML = TRUE)

mixedModteachB <- lmer(turnout ~ teachShareofVoters +  
                    minBlaisLago + 
                   VAP_adjLOG +  VAP_adjLOG_sq +
                    per_white_all + per65o + PerBachelorOrAbove +
                   OOH_share + median_incomeLOG + districtwide + incumShare + 
                   teachShareofVoters * VAP_adjLOG + 
                         (1|year) + (1|distid), 
              data = moddat, REML = TRUE)

mixedModteachC <- lmer(turnout ~ teachShareofVoters2 +  minBlaisLago +  
                    VAP_adjLOG + VAP_adjLOG_sq + 
                      per_white_all + per65o + PerBachelorOrAbove +
                   OOH_share + median_incomeLOG + districtwide +  incumShare +
                   teachShareofVoters2  + (1|year) +  (1|distid), 
              data = moddat, REML = TRUE)

mixedModteachD <- lmer(turnout ~ teachShareofVoters2 +  
                    minBlaisLago + 
                   VAP_adjLOG +  VAP_adjLOG_sq +
                    per_white_all + per65o + PerBachelorOrAbove +
                   OOH_share + median_incomeLOG + districtwide + incumShare + 
                   teachShareofVoters2 * VAP_adjLOG + 
                         (1|year) + (1|distid), 
              data = moddat, REML = TRUE)

mixedModteachE <- lmer(turnout ~ teachShareofVoters2 +  
                    minBlaisLago + 
                   VAP_adjLOG +  
                    per_white_all + per65o + PerBachelorOrAbove +
                   OOH_share + median_incomeLOG + districtwide + incumShare + 
                   teachShareofVoters2 * VAP_adjLOG + 
                         (1|year) + (1|distid), 
              data = moddat, REML = TRUE)

apsrtable(mixedModteachC, mixedModteachD, 
          caption = "Partial Pooling Model of Staff Influence",
          model.names = c("Main Effect", "Interaction"),
            label = "tab:meInf", notes = list(stars.note), 
          coef.names = teachCoefnames2, digits = 3,
          Sweave = FALSE, stars = "default", size = "footnotesize")
@


<<mixedInfmodSen, results='hide', eval=TRUE>>=
# Test for year specific slopes
m.slope <- update(mixedModteachB, . ~ . - (1|year))
m0 <- update(mixedModteachB, . ~ . - (1|distid))
teachLRT <- exactRLRT(m.slope, mixedModteachB, m0)
teachLRT$callFull <- mixedModteachB@call
teachLRT$callSmall <- m.slope@call
@

\subsubsection{Partisanship}

Table \ref{tab:mePartisan} provides no evidence to support a partisan dimension in school 
board turnout. While other variables hold their relationship from the tables 
above, the new variables for partisanship and party divide in the electorate are 
not statistically significant and their interaction with the size of the community 
is also not significant. If parties played an important role in the vote 
in spring elections than either the interaction between the party division or the 
proportion Democrats and the population of the district should be statistically 
significant and positive. The lack of a relationship provides evidence that parties 
do not influence school board turnout as a social group in a meaningful way. This 
seems clear, boards are not proving grounds for candidates for higher office and as 
they are non-partisan the party leadership has little incentive to prioritize them.
\footnote{There is no evidence in the fixed effect models either.}

<<partyMods, results ='hide'>>=
moddat <- dist_turn[, c("turnout", "year", "fallTurnout", "incumShare",
                        "VAP_adjLOG", "distid", "per_white_all", "per65o", 
                        "PerBachelorOrAbove", "OOH_share", "median_incomeLOG", 
                        "fallTwoPartyShareDem", "partyDivisionFall", 
                        "districtwide", "contest", "minBlaisLago")]
moddat <- na.omit(moddat)
moddat <- moddat[order(moddat$distid, moddat$year),]
moddat$distid <- factor(moddat$distid)
moddat$year <- factor(moddat$year)
moddat <- moddat[order(moddat$distid, moddat$year),]
moddat$distid <- factor(moddat$distid)
moddat$contest <- factor(moddat$contest)
moddat$districtwide <- factor(moddat$districtwide)
moddat$year <- factor(moddat$year)
moddat$turnout <- moddat$turnout * 100
centr <- mean(moddat$turnout)
stddev <- sd(moddat$turnout)
moddat$outflag <- (moddat$turnout - centr) / stddev
moddat <- moddat[moddat$outflag <=5 & moddat$outflag >= -5,]
nums <- sapply(moddat, is.numeric)
# nums <- nums[!names(nums) %in% c("fallPartyDivision")]
ScaleMeans <- apply(moddat[, nums], 2, mean, na.rm=TRUE)
ScaleSD <- apply(moddat[, nums], 2, sd, na.rm=TRUE)
moddatScaleParty <- cbind(ScaleMeans, ScaleSD); rm(ScaleMeans, ScaleSD)
moddat[, nums] <- apply(moddat[, nums], 2, rescale)
moddat$VAP_adjLOG_sq <- moddat$VAP_adjLOG^2
dd <<- datadist(moddat)
options(datadist="dd")

partyRLM1 <- ols(turnout ~ fallTurnout + minBlaisLago + 
                    VAP_adjLOG + VAP_adjLOG_sq  + per_white_all + per65o + 
                   PerBachelorOrAbove + OOH_share + median_incomeLOG + 
                   districtwide + incumShare + partyDivisionFall + year + distid,
              data = moddat, x= TRUE, y = TRUE)

partyRLM1$se <- sqrt(diag(vcov(robcov(partyRLM1, cluster = moddat$distid))))


partyRLM2 <- ols(turnout ~ fallTwoPartyShareDem + fallTurnout + minBlaisLago + 
                    VAP_adjLOG + VAP_adjLOG_sq + per_white_all + per65o + 
                   PerBachelorOrAbove +
                   OOH_share + median_incomeLOG + districtwide + incumShare + 
                   distid + factor(year), 
              data = moddat, x = TRUE, y = TRUE)

partyRLM2$se <- sqrt(diag(vcov(robcov(partyRLM2, cluster = moddat$distid))))

partyRLM3 <- ols(turnout ~ partyDivisionFall*VAP_adjLOG + fallTurnout + minBlaisLago + 
                    VAP_adjLOG + VAP_adjLOG_sq+ per_white_all + per65o + 
                   PerBachelorOrAbove + OOH_share + median_incomeLOG + 
                   districtwide + incumShare + year + distid,
              data = moddat, x= TRUE, y = TRUE)

partyRLM3$se <- sqrt(diag(vcov(robcov(partyRLM3, cluster = moddat$distid))))


partyRLM4 <- ols(turnout ~ fallTwoPartyShareDem*VAP_adjLOG + fallTurnout + minBlaisLago + 
                    VAP_adjLOG + VAP_adjLOG_sq+ per_white_all + per65o + PerBachelorOrAbove +
                   OOH_share + median_incomeLOG + districtwide + incumShare + 
                   distid + factor(year), 
              data = moddat, x = TRUE, y = TRUE)

partyRLM4$se <- sqrt(diag(vcov(robcov(partyRLM4, cluster = moddat$distid))))

partyCoefNames <- c("Intercept", "Fall Turnout", 
                 "Competitiveness", "Electorate Size", "Electorate Size\\textsuperscript{2}", "\\% White", 
                  "\\% Over 65", "\\% Bach. +", "\\% Owner Occupied", 
                  "Median Income", "District-wide", "Incumbent Share", 
                  "Fall Party Divide", "Fall 2 Party Dem.", 
                 "Party Division x Elec. Size", 
                 "2 Party Dem x Elec. Size")

partyModtab <- apsrtable(partyRLM1, partyRLM2, partyRLM3, partyRLM4, 
                         se="robust", label="tab:partymods", 
          model.names=c("Party Unity", "Dem Share", 
                        "Party Unity Inter.", "Dem Share Inter."), 
          caption = "Models of Partisanship and Turnout in School Board Elections",
          notes = list(se.note, stars.note, "Year and district fixed effects omitted."),
          omitcoef=list("distid", 
                        expression(grep("distid", coefnames, value=TRUE)), 
                        "year", 
                        expression(grep("year", coefnames, value = TRUE))), 
          coef.names = partyCoefNames,
          Sweave=FALSE, stars = "default", 
          size = "scriptsize")
@



<<partyMixedMods, results='asis'>>=
partyCoefNames2 <- c("Intercept", "Fall Party Divide", "Fall Turnout", 
                 "Competitiveness", "Electorate Size", "Electorate Size\\textsuperscript{2}","\\% White", 
                  "\\% Over 65", "\\% Bach. +", "\\% Owner Occupied", 
                  "Median Income", "District-wide", "Incumbent Share", 
                 "Party Division x Elec. Size", 
                 "Fall 2 Party Dem.", "2 Party Dem\\textsuperscript{2}","2 Party Dem x Elec. Size")

mixedModP <- lmer(turnout ~ partyDivisionFall + fallTurnout + minBlaisLago + 
                    VAP_adjLOG + VAP_adjLOG_sq +per_white_all + per65o + 
                   PerBachelorOrAbove + OOH_share + median_incomeLOG + 
                   districtwide + incumShare + partyDivisionFall * VAP_adjLOG + 
                    (1|distid) + (1|year), 
              data = moddat, REML = TRUE)

mixedModPb <- lmer(turnout ~ VAP_adjLOG + VAP_adjLOG_sq + fallTwoPartyShareDem +
                     I(fallTwoPartyShareDem^2)+ 
                     fallTurnout + 
                     minBlaisLago + 
                    VAP_adjLOG + per_white_all + per65o + PerBachelorOrAbove +
                   OOH_share + median_incomeLOG + districtwide + incumShare +
                     fallTwoPartyShareDem * VAP_adjLOG +
                     (1|year) + (1|distid), 
              data = moddat, REML = TRUE)

apsrtable(mixedModP, mixedModPb, caption = "Partial Pooling Model of Partisanship",
          model.names = c("Division", "Democrat"),
            label = "tab:mePartisan", notes = list(tabnote, stars.note), 
          Sweave = FALSE, 
          coef.names = partyCoefNames2, digits = 3, stars = "default", 
          size = "footnotesize")
@


<<mixedPartymodSen, results='hide', eval=TRUE>>=
# Test for year specific slopes
m.slope <- update(mixedModPb, . ~ . - (1|year))
m0 <- update(mixedModPb, . ~ . - (1|distid))
partyLRT <- exactRLRT(m.slope, mixedModPb, m0)
partyLRT$callFull <- mixedModPb@call
partyLRT$callSmall <- m.slope@call
@



<<cleanupb, echo=FALSE,results='hide'>>=
rm(partyRLM1, partyRLM2, partyRLM3, partyRLM4, teachRLM, teachRLM2, 
   teachRLM3, teachRLM4, closeRLM, closeRLM2, closeRLM3, closeRLM4)
@

\clearpage

\subsection{School Board Vote Rolloff}

In this section I explore whether any of the models 
above explain the difference between top ticket turnout and school board turnout. 
As much as rolloff coincides with political relevance of the school board race 
to the electorate, the relationships observed above should also be observed in 
the measure of rolloff -- with decreased rolloff taking the place of increased 
turnout. 


<<cleanundervotedata, results='hide'>>=
load("../../data/cache/springElectionVotes.rda")
# load("data/cache/springElectionVotes.rda")
springVotes$votesTopTicketSpring <- springVotes$VotesCast
springVotes$VotesCast <- NULL
dist_turn <- merge(dist_turn, springVotes, 
                   by = c("distid", "year"), all.x = TRUE)

dist_turn$topTicketTurnoutSpring <- dist_turn$votesTopTicketSpring / dist_turn$VAP_adj
dist_turn$turnoutDiff <- dist_turn$topTicketTurnoutSpring - dist_turn$turnout

vars2 <- c("turnout", "turnoutLag2", "year", "fallTurnout", "incumShare",
                        "VAP_adjLOG", "distid", "per_white_all", "per65o", 
                        "PerBachelorOrAbove", "OOH_share", "median_incomeLOG", 
                        "teachShareofVoters", "districtwide", 
                        "contest", "minBlaisLago", "teachShareofVoters2")

vars1 <- c("turnout", "turnoutLag2", "year", "fallTurnout", "topTicketTurnoutSpring",
           "turnoutDiff", "ImputedFlag",
                        "VAP_adjLOG", "distid", "per_white_all", "per65o", 
                        "PerBachelorOrAbove", "OOH_share", "median_incomeLOG", 
                        "fallTwoPartyShareDem", "partyDivisionFall", 
                        "districtwide", "contest", "minBlaisLago")

moddat <- dist_turn[, unique(c(vars1, vars2))]
moddat$ImputedFlag[is.na(moddat$ImputedFlag)] <- "Observed"
moddat$ImputedFlag <- defac(moddat$ImputedFlag)
moddat$ImputedFlag[moddat$ImputedFlag == "Imputed2010"] <- "Imputed"
moddat$ImputedFlag[moddat$ImputedFlag == "Observed2010"] <- "Observed"
moddat$ImputedFlag <- factor(moddat$ImputedFlag, levels = c("Imputed", "Observed"))
moddat$ImputedFlag <- relevel(moddat$ImputedFlag, ref = "Imputed")
moddat <- na.omit(moddat)
moddat <- moddat[order(moddat$distid, moddat$year),]
moddat$distid <- factor(moddat$distid)
moddat$year <- factor(moddat$year)
moddat$districtwide <- factor(moddat$districtwide)
moddat$turnout <- moddat$turnout * 100
moddat$turnoutDiff <- moddat$turnoutDiff * 100
# moddat$turnoutLag2 <- moddat$turnoutLag2 * 100
# moddat$turnoutLag1 <- moddat$turnoutLag1 * 100
# moddat$per_white_all <- moddat$per_white_all * 100
# moddat$per65o <- moddat$per65o * 100
# moddat$PerBachelorOrAbove <- moddat$PerBachelorOrAbove * 100
# moddat$OOH_share <- moddat$OOH_share * 100
# moddat$fallTurnout <- moddat$fallTurnout * 100
# moddat$VAP_adj <- log(moddat$VAP_adj)
# moddat$median_income <- log(moddat$median_income)
centr <- mean(moddat$turnoutDiff)
stddev <- sd(moddat$turnoutDiff)
moddat$outflag <- (moddat$turnoutDiff - centr) / stddev
moddat <- moddat[moddat$outflag <= 5 & moddat$outflag >= -5,]
centr <- mean(moddat$turnout)
stddev <- sd(moddat$turnout)
moddat$outflag <- (moddat$turnout - centr) / stddev
moddat <- moddat[moddat$outflag <= 5 & moddat$outflag >= -5,]
nums <- sapply(moddat, is.numeric)
ScaleMeans <- apply(moddat[, nums], 2, mean, na.rm=TRUE)
ScaleSD <- apply(moddat[, nums], 2, sd, na.rm=TRUE)
moddatScaleUndervote <- cbind(ScaleMeans, ScaleSD); rm(ScaleMeans, ScaleSD)
nums <- sapply(moddat, is.numeric)
moddat[, nums] <- apply(moddat[, nums], 2, rescale)
moddat$VAP_adjLOG_sq <- moddat$VAP_adjLOG^2
dd <<- datadist(moddat)
options(datadist="dd")
@

For rolloff data my data are restricted to the spring elections from 2007-2012. 
To calculate rolloff, I take the difference in the turnout for the top ticket 
in the spring election and the turnout for the highest turnout school board 
election in the school district. The greater this number, the greater the 
share of voters who failed to complete their ballots. The median district 
has \Sexpr{iPer(mean(dist_turn$turnoutDiff, na.rm=TRUE)*100)} percentage point 
difference in their turnout, meaning that if the turnout in the school board 
election was 1,810, then the turnout for the top ticket race would be 
\Sexpr{iNum2(1810 + 1810*mean(dist_turn$turnoutDiff, na.rm=TRUE))}. Thus 
ballot fatigue is not that uncommon and matches findings in other elections 
\citep{streb09,wattenberg00}.

<<undervoteMMfits1, results='asis'>>=
undervoteMMlag <- lmer(turnoutDiff ~ turnoutLag2 + fallTurnout + 
                         VAP_adjLOG + VAP_adjLOG_sq + per_white_all + 
                         per65o + PerBachelorOrAbove + OOH_share + 
                         median_incomeLOG + districtwide + incumShare +
                         ImputedFlag + minBlaisLago + 
                         (1|year) + (1|distid), 
              data = moddat, REML = FALSE)
undervoteMMclose <- lmer(turnoutDiff ~  minBlaisLago + VAP_adjLOG + fallTurnout +
                           VAP_adjLOG_sq + per_white_all + 
                    per65o + PerBachelorOrAbove + OOH_share + 
                      ImputedFlag + minBlaisLago * VAP_adjLOG +
                    median_incomeLOG + districtwide + incumShare +
                    (1|year) + (1|distid), 
              data = moddat, REML = TRUE)

undervoteMMteach <- lmer(turnoutDiff ~ teachShareofVoters + fallTurnout + 
                           minBlaisLago + VAP_adjLOG + VAP_adjLOG_sq +
                           per_white_all + per65o + PerBachelorOrAbove +
                  OOH_share + median_incomeLOG + districtwide + incumShare +
                    ImputedFlag+  
                   teachShareofVoters * VAP_adjLOG + (1|year) + (1|distid), 
              data = moddat, REML = TRUE)
undervoteMMteachB <- lmer(turnoutDiff ~ teachShareofVoters2 + fallTurnout + 
                           minBlaisLago + VAP_adjLOG + VAP_adjLOG_sq +
                           per_white_all + per65o + PerBachelorOrAbove +
                  OOH_share + median_incomeLOG + districtwide + incumShare +
                    ImputedFlag+  
                   teachShareofVoters2 * VAP_adjLOG + (1|year) + (1|distid), 
              data = moddat, REML = TRUE)

undervoteMMparty <- lmer(turnoutDiff ~ fallTwoPartyShareDem*VAP_adjLOG + VAP_adjLOG_sq +
                           fallTurnout + minBlaisLago +
                  VAP_adjLOG + per_white_all + per65o + PerBachelorOrAbove +
                   OOH_share + median_incomeLOG + districtwide + incumShare +
                    ImputedFlag + 
                      (1|year) + (1|distid), 
              data = moddat, REML = TRUE)
undervoteMMpartyB <- lmer(turnoutDiff ~ partyDivisionFall*VAP_adjLOG +  VAP_adjLOG_sq+ 
                           fallTurnout + minBlaisLago +
                  VAP_adjLOG + per_white_all + per65o + PerBachelorOrAbove +
                   OOH_share + median_incomeLOG + districtwide +incumShare +
                    ImputedFlag +
                      (1|year) + (1|distid), 
              data = moddat, REML = TRUE)

coefNamesUnd1 <- c("Intercept", "Turnout Lag (2)","Fall Turnout", 
                 "Electorate Size", "Electorate Size\\textsuperscript{2}","\\% White", 
                  "\\% Over 65", "\\% Bach. +", "\\% Owner Occupied", 
                  "ln(MedianIncome)", "District-wide", "Incumbent Share","Imputed",
                 "Competitiveness", "Competitiveness X Elec. Size")


apsrtable(undervoteMMlag, undervoteMMclose,  
          caption = "Partial Pooling Model of School Board Rolloff",
           model.names = c("Lag", "Close Race"),
            label = "tab:meUndv1", notes = list(stars.note), 
          Sweave = FALSE, digits = 3, 
          coef.names = coefNamesUnd1, stars = "default", size = "footnotesize")
@


Table \ref{tab:meUndv1} shows the results of the first three types of models 
investigated 
above for turnout. Note that here the sign is flipped -- the smaller the dependent 
variable, the more turnout for school board in relation to the top ticket turnout 
in the spring election. Prior turnout continues to matter in the lagged model, 
the higher the prior turnout the less the gap between top ticket and school board 
races in the present spring election. In the measures of the closeness of seats 
the less competitive a race is the greater the gap between the top ticket and the 
board race -- but this effect is only significant in interaction with district size. 
In small communities this relationship does not matter. 

<<undervoteMMfits2, results='asis'>>=
coefNamesUnd2 <- c("Intercept", "Teacher Share Elec.", "Fall Turnout", 
                   "Competitiveness", "Electorate Size", "Electorate Size\\textsuperscript{2}","\\% White", 
                  "\\% Over 65", "\\% Bach. +", "\\% Owner Occupied", 
                  "Median Income", "District-wide", "Incumbent Share","Imputed", 
                 "Teacher Share x Elec. Size", "Teach. Share of SB", "Teach. Share SB x Elec. Size",
                 "Fall Dem.", "Fall Dem. X Elec. Size", 
                 "Fall Partisan", "Fall Partisan x Elec. Size")
apsrtable(undervoteMMteach, undervoteMMteachB, undervoteMMparty, undervoteMMpartyB,
          caption = "Partial Pooling Model of School Board Rolloff",
           model.names = c("Teach. Infl.", "Teach. Infl. 2", 
                           "Party Infl.", "Party Divide"),
            label = "tab:meUndv2", notes = list(stars.note), 
          Sweave = FALSE, coef.names = coefNamesUnd2, stars = "default", 
          size = "footnotesize")
@


Table \ref{tab:meUndv2} shows the models for interest group influence on 
school board rolloff and provides the most interesting results. The results for the 
control variables are largely the same as in Table \ref{tab:meUndv1}, but here the 
rolloff results are different than the results for total turnout. In all three 
cases I find evidence of group influence in the completion of spring ballots. In 
the case of partisan division, this effect is only present in larger communities -- 
as communities and division get larger, the turnout gap for school board races widens. 

In the case of teachers, as teachers make up a greater share of the electorate 
fewer spring election voters who go to the polls bother to cast a vote for school 
board -- paralleling the finding from above for overall turnout. Community size 
exacerbates this effect -- in larger communities this effect is stronger. 

There is also evidence in Table \ref{tab:meUndv2} that Democratic party strength is 
related with fewer voters completing the school board vote. 
Partisan division increases rolloff, but is strongly interacted with district 
size -- as communities get larger and party division is stronger, rolloff grows. 

Also of interest is the near insignificance of all demographic controls on spring 
election rolloff. In both Table \ref{tab:meUndv1} and Table \ref{tab:meUndv2} 
the only consistent demographic indicators are indicators of wealth. This aligns 
with prior work by \citet{oliver} indicating that local election voters are 
more likely to be long-time residents who own property in the community. 

\clearpage
\subsection{Model Fit}

After reviewing the generally favorable results above, it is important to evaluate 
how well the models actually fit the data at hand. Assessing model fit in a mixed 
model framework is not as straightforward as with a standard OLS regression. 
Instead of a more sample-dependent model fit statistics like the Akaike's An 
Information Criterion, I prefer an estimate of the predictive power of the 
model for the observations in the sample. To assess this, I use a bootstrapped 
estimate of the Root Mean Squared Error (RMSE) to demonstrate how close the 
predicted values are to the fitted values across models across many resamples.
\footnote{To do this, I predict turnout on 150 bootstrap resamples of the data 
and estimate the RMSE for predictions from the original model across each of these 
resamples.}


<<modFitplot1, eval = TRUE, fig.scap="Comparing Model Fit for Competitiveness Model", fig.cap="Comparing Model Fit for Competitiveness Model. Black represents observed value, purple represents fixed effect estimate, and the red dots are the estimate from the full model.", fig.show='hide'>>=
library(broom)
plotdf <- augment(mixedModcloseC)
plotdf$yUnscale <- (plotdf$turnout * 2 * moddatScaleClose["turnout", 2]) + 
   moddatScaleClose["turnout", 1]
plotdf$yhatUnscale <- (plotdf$.fitted * 2 * moddatScaleClose["turnout", 2]) + 
   moddatScaleClose["turnout", 1]
plotdf$x1Unscale <- (plotdf$minBlaisLago * 2 * moddatScaleClose["minBlaisLago", 2]) + 
   moddatScaleClose["minBlaisLago", 1]
plotdf$yhatFixed <- (plotdf$.fixed * 2 * moddatScaleClose["turnout", 2]) + 
   moddatScaleClose["turnout", 1]

plotSlope <- coefficients(lm(yUnscale ~ x1Unscale, data = plotdf))[2]
plotInt <- coefficients(lm(yUnscale ~ x1Unscale, data = plotdf))[1]

cases <- sample(unique(plotdf$distid), 12)
plotdf <- plotdf[plotdf$distid %in% cases, ]

modelFitexamplePlot <- ggplot(plotdf, aes(x = year, y = yUnscale/100)) +
         geom_line(aes(group = distid), linetype = 2) + 
  geom_point(aes(x = year, y = yhatFixed/100), color = I("purple")) +
  geom_point(aes(x = year, y = yhatUnscale/100), color = I("red")) + 
  facet_wrap(~distid) + 
  scale_y_continuous(label = percent) +
  theme_bw() + labs(x= "Year", y = "Turnout", 
                    title = "Model Fit for Blais-Lago Model") + 
  theme(strip.text = element_blank())

modelFitexamplePlot
@


<<modFitplot2Hide, fig.show='hide'>>=
plotdf <- augment(mixedMod1lagsb)
plotdf$yUnscale <- (plotdf$turnout * 2 * moddatScaleLag["turnout", 2]) + 
   moddatScaleLag["turnout", 1]
plotdf$yhatUnscale <- (plotdf$.fitted * 2 * moddatScaleLag["turnout", 2]) + 
   moddatScaleLag["turnout", 1]
plotdf$x1Unscale <- (plotdf$turnoutLag2 * 2 * moddatScaleLag["turnoutLag2", 2]) + 
   moddatScaleLag["turnoutLag2", 1]
plotdf$yhatFixed <- (plotdf$.fixed * 2 * moddatScaleLag["turnout", 2]) + 
   moddatScaleLag["turnout", 1]

plotdf$x1Unscale <- plotdf$x1Unscale * 100
plotdf <- plotdf[plotdf$x1Unscale < 99, ]

plotSlope <- coefficients(lm(yUnscale ~ x1Unscale, data = plotdf))[2]
plotInt <- coefficients(lm(yUnscale ~ x1Unscale, data = plotdf))[1]

cases <- sample(unique(plotdf$distid), 12)
plotdf <- plotdf[plotdf$distid %in% cases, ]


ggplot(plotdf, aes(x = x1Unscale, y = yUnscale)) +
         geom_point() + 
  geom_point(aes(x = x1Unscale, y = yhatUnscale), color = I("red")) + 
  geom_point(aes(x = x1Unscale, y = yhatFixed), color = I("purple")) +
  geom_smooth(aes(x = x1Unscale, y = yUnscale), method = "lm", 
              se = FALSE, color = I("black")) + 
  geom_smooth(aes(x = x1Unscale, y = yhatUnscale), method = "lm", 
              se = FALSE, color = I("red")) + 
  geom_smooth(aes(x = x1Unscale, y = yhatFixed), method = "lm", 
              se = FALSE, color = I("purple")) +
  facet_wrap(~distid) + 
  geom_abline(intercept = plotInt, slope = plotSlope, linetype=2) +
  xlim(c(0, max(plotdf$x1Unscale))) + 
  theme_bw() + labs(x = "Lag Turnout", y = "Turnout", 
                    title = "Model Fit for Lagged Turnout Models")

# Bootstrap the beta coefficients here using bootMer
# http://glmm.wikidot.com/faq
@


<<bootRMSE, results='hide', cache=TRUE>>=
library(boot)

sigmaBoot <- boot(mixedModP@frame, bootRMSE, R = 150, model = mixedModP)
out <- cbind(summary(sigmaBoot), mod  = "Party Division")
# sigmaBoot <- boot(mixedModlags@frame, bootRMSE, R = 150, model = mixedModlags)
# out <- rbind(out, cbind(summary(sigmaBoot), mod  = "mixedModlags"))
sigmaBoot <- boot(mixedMod1lagsb@frame, bootRMSE, R = 150, model = mixedMod1lagsb)
out <- rbind(out, cbind(summary(sigmaBoot), mod  = "Habit"))
# sigmaBoot <- boot(mixedModcloseC@frame, bootRMSE, R = 150, model = mixedModcloseC)
# out <- rbind(out, cbind(summary(sigmaBoot), mod  = "mixedModcloseC"))
sigmaBoot <- boot(mixedModclose@frame, bootRMSE, R = 150, model = mixedModclose)
out <- rbind(out, cbind(summary(sigmaBoot), mod  = "Blais-Lago"))
# sigmaBoot <- boot(mixedModcloseB@frame, bootRMSE, R = 100, model = mixedModcloseB)
# out <- rbind(out, cbind(summary(sigmaBoot), mod  = "mixedModcloseB"))
# sigmaBoot <- boot(mixedModteach@frame, bootRMSE, R = 150, model = mixedModteach)
# out <- rbind(out, cbind(summary(sigmaBoot), mod  = "mixedModteach"))
sigmaBoot <- boot(mixedModteachD@frame, bootRMSE, R = 150, model = mixedModteachD)
out <- rbind(out, cbind(summary(sigmaBoot), mod  = "Teach. Infl."))
# sigmaBoot <- boot(mixedModPb@frame, bootRMSE, R = 150, model = mixedModPb)
# out <- rbind(out, cbind(summary(sigmaBoot), mod  = "mixedModPb"))

rmsePlot1 <- ggplot(out, aes(x = mod, y = bootMed)) + 
  geom_bar(stat='identity', width = .5) + 
  geom_errorbar(aes(ymin = bootMed - bootSE, ymax = bootMed + bootSE), 
                width = .2, color = I("red")) + theme_dpi() + 
  labs(x = "Model Name", y = "", 
       title = "Turnout Models") 
# 
# ggplot(out, aes(x = mod, y = bootMed, ymax = bootMed + (bootSE *2), 
#                 ymin = bootMed - (bootSE *2))) + 
#   geom_pointrange() + geom_point(aes(x = mod, y = original), color = I("red")) + 
#   labs(x = "Model Name", y = "Mean Model Error in Standard Deviations", 
#        title = "Turnout Models") + 
#   scale_y_continuous(label = percent) + 
#   coord_flip() + theme_dpi()
@

<<bootRMSE2, results='hide', cache=TRUE>>=
sigmaBoot <- boot(undervoteMMclose@frame, bootRMSE, R = 150, model = undervoteMMclose)
out <- cbind(summary(sigmaBoot), mod  = "Blais-Lago")
sigmaBoot <- boot(undervoteMMlag@frame, bootRMSE, R = 150, model = undervoteMMlag)
out <- rbind(out, cbind(summary(sigmaBoot), mod  = "Habit"))
sigmaBoot <- boot(undervoteMMparty@frame, bootRMSE, R = 150, model = undervoteMMparty)
out <- rbind(out, cbind(summary(sigmaBoot), mod  = "% Democrat"))
sigmaBoot <- boot(undervoteMMpartyB@frame, bootRMSE, R = 150, model = undervoteMMpartyB)
out <- rbind(out, cbind(summary(sigmaBoot), mod  = "Party Division"))
sigmaBoot <- boot(undervoteMMteach@frame, bootRMSE, R = 150, model = undervoteMMteach)
out <- rbind(out, cbind(summary(sigmaBoot), mod  = "Teach. Infl."))
# sigmaBoot <- boot(undervoteMMteachB@frame, bootRMSE, R = 150, model = undervoteMMteachB)
# out <- rbind(out, cbind(summary(sigmaBoot), mod  = "undervoteMMteachB"))

rmsePlot2 <- ggplot(out, aes(x = mod, y = bootMed)) + 
  geom_bar(stat='identity', width = .5) + 
  geom_errorbar(aes(ymin = bootMed - bootSE, ymax = bootMed + bootSE), 
                width = .2, color = I("red")) + theme_dpi() + 
  # geom_point(aes(y = original, x = mod), color = I("red")) + 
  labs(x = "Model Name", y = "", 
       title = "Rolloff Models") 
@

Figure \ref{fig:printRMSEplot} shows the results for turnout models in the top 
panel and rolloff models in the bottom panel. The height of the bar represents 
the RMSE standardized to represent the percentage of a standard deviation the 
average observation is mispredicted. A lower figure is better. The red error 
bar represents the bootstrapped RMSE plus or minus two standard deviations of 
all of the resampled RMSE values. Overall the rolloff models perform better than the 
turnout models, but none of the models are significantly better fitting than any 
of the others within each dependent variable. 

This suggests two things. First, the demographic variables and the year and 
district effects are doing most of the work in explaining the dependent variables. 
Any additional variance explained by the theoretically interesting variables has 
marginal impact on accurately predicting the dependent variable. Second, there 
is significant unexplained variance in turnout that is not covered by any of the 
measures in any of the models or in the district or election specific intercepts. 
There is room for future work to improve these models through identifying measures 
to improve the prediction. 

<<printRMSEplot, fig.scap="Comparing Model Fit Across Variables", fig.cap="Figures show the bootstrapped root mean square error (RMSE) of competing models across 150 bootstrapped replications along with a confidence interval. A lower RMSE corresponds to a more accurate prediction and better explanation of the dependent variable.", fig.height=4,fig.width=8>>==
library(gridExtra)
grid.arrange(rmsePlot1, rmsePlot2, left = "Mean Model Error in Std. Dev.")
@

\subsection{Substantive Effects}

After finding evidence in favor of voters behaving as theory might expect, I now 
turn my attention to exploring the magnitude of these effects. Table 
\ref{tab:turnoutRESULTS} summarizes the substantive findings for all variables 
across both turnout and rolloff. Each row in the table shows the net impact on 
turnout and rolloff changing a key predictor associated with one of the theories 
of voter turnout. 

In general, the impacts are modest. District size and prior district turnout have 
the largest substantive impacts on both rolloff and turnout. Competitiveness has 
a notably smaller impact, requiring a large shift in competitiveness to provide 
a measurable increase in turnout. In a median sized district, the increase in 
voter turnout attributable to this increase in competitiveness would result in 
an additional 25 voters -- enough to sway the outcome of a race in fewer than 
10\% of the observed spring election cycles. Net of these effects, the effects 
of interest groups and political parties are quite low. School board turnout is suppressed by a larger share of the number of voters being represented by 
teachers in the school district. This effect is smaller in smaller communities. 
There appears to be an influence of teachers on rolloff as well -- but only 
when measured as a share of the voting age population. These effects are quite 
modest with turnout averaging around 18\% a 0.25\% point increase in turnout in 
the median size district equates to just 13 additional voters. 

There is no evidence of a role of political parties in school board spring election 
turnout, but there is evidence off an effect on rolloff. A one standard deviation 
increase in partisan division represents a 25\% increase in rolloff for a typical 
district. However, in the median district this represents 50 fewer school board 
election voters -- well below the median victory margin in the closest race in each 
district, approximately 290 votes. 


% Describe model results

<<substEffSim, eval=FALSE, results='hide'>>=

# beta <- fixef(mixedMod1lagsb)["turnoutLag2"]
# margEff <- 0.6 * beta
# 
# margEff * 2 * moddatScaleLag["turnout", 2] + moddatScaleLag["turnout", 1] - 
#    moddatScaleLag["turnout", 1]
# 
# 0.6 * 2 * moddatScaleLag["turnoutLag2", 2] + moddatScaleLag["turnoutLag2", 1] - 
#    moddatScaleLag["turnoutLag2", 1]
# 
# # ------------------
# 
# beta <- fixef(undervoteMMlag)["turnoutLag2"]
# margEff <- 0.6 * beta
# 
# margEff * 2 * moddatScaleUndervote["turnoutDiff", 2] + 
#   moddatScaleUndervote["turnoutDiff", 1] - 
#    moddatScaleUndervote["turnoutDiff", 1]
# 
# 0.6 * 2 * moddatScaleUndervote["turnoutLag2", 2] + 
#   moddatScaleUndervote["turnoutLag2", 1] - 
#    moddatScaleUndervote["turnoutLag2", 1]

# ------------------------
effSizeScale <- function(model, scales, betaChg, dv, iv, iv2=NULL){
  beta <- fixef(model)[iv]
  polyString <- paste0(iv, "_sq")
  polyTerm <- intersect(polyString, names(fixef(model)))
  if(!is.null(iv2)){
    alpha <- fixef(model)[iv2]
    interactStrings <- c(paste(iv, iv2, sep=":"), paste(iv2, iv, sep=":"))
    interactTerm <- intersect(interactStrings, names(fixef(model)))
  } else{
    interactTerm <- NULL
  }
  
  if(length(polyTerm) > 0){
    beta2 <- fixef(model)[polyTerm]
    margEff <- (betaChg * beta) + (betaChg^2 * beta2)
  } else {
    margEff <- betaChg * beta
  }

  if(length(interactTerm > 0)){
    polyString <- paste0(iv2, "_sq")
    polyTerm <- intersect(polyString, names(fixef(model)))
    if(length(polyTerm) > 0){
    alpha2 <- fixef(model)[polyTerm]
    alphaLo <- quantile(model@frame[[iv2]], probs = 0.125) 
    alphaEffl <- (alphaLo * alpha) + (alpha2 * alphaLo^2)
    alphaM <- quantile(model@frame[[iv2]], probs = 0.5) 
    alphaEffm <- (alphaM * alpha) + (alpha2 * alphaM^2)
    alphaHi <- quantile(model@frame[[iv2]], probs = 0.875)
    alphaEffh <- (alphaHi * alpha) + (alpha2 * alphaHi^2)
      
    } else{
    alphaLo <- quantile(model@frame[[iv2]], probs = 0.125) 
    alphaEffl <- alphaLo * alpha
    alphaM <- quantile(model@frame[[iv2]], probs = 0.5) 
    alphaEffm <- alphaM * alpha
    alphaHi <- quantile(model@frame[[iv2]], probs = 0.875)
    alphaEffh <- alphaHi * alpha
    }
    
    psi <- fixef(model)[interactTerm]
    
    margEffLo <- margEff + alphaEffl + (betaChg * alphaLo *  psi)
    margEffHi <- margEff + alphaEffh + (betaChg * alphaHi *  psi)
    margEffM <-  margEff + alphaEffm + (betaChg * alphaM *  psi)
    margEff <- c(margEffLo, margEffM, margEffHi)
}

  DVdelta <- margEff * 2 * scales[dv, 2] + scales[dv, 1] - scales[dv, 1]

  varChg <- betaChg * 2 * scales[iv, 2] 
  varChg <- round(varChg, digits = 4)
  DVdelta <- round(DVdelta, digits = 4)
  
  ivMax <- max(model@frame[[iv]])
  ivMin <- min(model@frame[[iv]])
  
  varMax <- round(ivMax * 2 * scales[iv, 2] + scales[iv, 1], digits = 4)
  varMin <- round(ivMin * 2 * scales[iv, 2] + scales[iv, 1], digits = 4)
  varSD <- round(0.5 * 2 * scales[iv, 2], digits = 4)
  
  dvMax <- max(model@frame[[dv]])
  dvMin <- min(model@frame[[dv]])
  
  dvarMax <- round(dvMax * 2 * scales[dv, 2] + scales[dv, 1], digits = 4)
  dvarMin <- round(dvMin * 2 * scales[dv, 2] + scales[dv, 1], digits = 4)
  dvarSD <-  round(0.5 * 2 * scales[dv, 2], digits = 4)
  
  if(!is.null(iv2)){
    stub <- c(" for the Bottom Quartile ", " for the Median ", 
              " for the Top Quartile")
    print(paste0("Dependent variable changes ",  paste(DVdelta, stub, collapse=""), 
          " of the interacted variable ", iv2))
  } else{
    print(paste0("Dependent variable changes ", DVdelta))
  }
  print(paste0("on a range from ", dvarMin, " to ", dvarMax, 
               " on the dependent variable with standard deviation of ", dvarSD))
  print(paste0("for a change in independent variable of ", varChg))
  print(paste0("on a range from ", varMin, " to ", varMax, 
               " on the independent variable with standard deviation of ", varSD))
}

# turnoutlag2
effSizeScale(mixedMod1lagsb, scales = moddatScaleLag, betaChg = 0.6, 
             dv = "turnout", iv = "turnoutLag2")

# decreases are good
effSizeScale(mixedModcloseC, scales = moddatScaleClose, betaChg = -0.5, 
              dv = "turnout", iv = "VAP_adjLOG")

# Closeness
effSizeScale(mixedModcloseC, scales = moddatScaleClose, betaChg = 0.5, 
              dv = "turnout", iv = "minBlaisLago")
effSizeScale(mixedModcloseC, scales = moddatScaleClose, betaChg = 0.5, 
              dv = "turnout", iv = "minBlaisLago", iv2="VAP_adjLOG")
effSizeScale(mixedModcloseC, scales = moddatScaleClose, betaChg = 0, 
              dv = "turnout", iv = "minBlaisLago", iv2="VAP_adjLOG")

# teachershare
effSizeScale(mixedModteachD, scales = moddatScaleTeach, betaChg = 0.25, 
             dv = "turnout", iv = "teachShareofVoters2", iv2="VAP_adjLOG")
effSizeScale(mixedModteachD, scales = moddatScaleTeach, betaChg = 0, 
             dv = "turnout", iv = "teachShareofVoters2", iv2="VAP_adjLOG")

# Partisan divide
effSizeScale(mixedModP, scales = moddatScaleParty, betaChg = 0.25, 
             dv = "turnout", iv = "partyDivisionFall", iv2="VAP_adjLOG")
effSizeScale(mixedModPb, scales = moddatScaleParty, betaChg = 0.25, 
             dv = "turnout", iv = "fallTwoPartyShareDem", iv2="VAP_adjLOG")
#------------
# Rolloff
# turnoutlag2
effSizeScale(undervoteMMlag, scales = moddatScaleUndervote, betaChg = 0.8, 
             dv = "turnoutDiff", iv = "turnoutLag2")

# decreases are good
effSizeScale(undervoteMMclose, scales = moddatScaleUndervote, betaChg = -0.5, 
              dv = "turnoutDiff", iv = "VAP_adjLOG")

# Closeness
effSizeScale(undervoteMMclose, scales = moddatScaleUndervote, betaChg = 0.25, 
              dv = "turnoutDiff", iv = "minBlaisLago")
effSizeScale(undervoteMMclose, scales = moddatScaleUndervote, betaChg = 0.25, 
              dv = "turnoutDiff", iv = "minBlaisLago", iv2="VAP_adjLOG")
effSizeScale(undervoteMMclose, scales = moddatScaleUndervote, betaChg = 0, 
              dv = "turnoutDiff", iv = "minBlaisLago", iv2="VAP_adjLOG")

# teachershare
effSizeScale(undervoteMMteachB, scales = moddatScaleUndervote, betaChg = 0.5, 
             dv = "turnoutDiff", iv = "teachShareofVoters2", iv2="VAP_adjLOG")
effSizeScale(undervoteMMteachB, scales = moddatScaleUndervote, betaChg = 0, 
             dv = "turnoutDiff", iv = "teachShareofVoters2", iv2="VAP_adjLOG")

# Partisan divide
effSizeScale(undervoteMMparty, scales = moddatScaleUndervote, betaChg = 0.25, 
             dv = "turnoutDiff", iv = "fallTwoPartyShareDem", iv2="VAP_adjLOG")
effSizeScale(undervoteMMparty, scales = moddatScaleUndervote, betaChg = 0, 
             dv = "turnoutDiff", iv = "fallTwoPartyShareDem", iv2="VAP_adjLOG")
effSizeScale(undervoteMMpartyB, scales = moddatScaleUndervote, betaChg = 0.25, 
             dv = "turnoutDiff", iv = "partyDivisionFall", iv2="VAP_adjLOG")
effSizeScale(undervoteMMpartyB, scales = moddatScaleUndervote, betaChg = 0, 
             dv = "turnoutDiff", iv = "partyDivisionFall", iv2="VAP_adjLOG")
@


\renewcommand\arraystretch{1.4}
\begin{table}[h!]
\begin{center}
\begin{scriptsize}
\caption[Summary of Evidence for All Models on Turnout and Rolloff]{Summary of substantive model results. Large districts are in the middle of top VAP quartile; small districts at midpoint of bottom quartile.}
\label{tab:turnoutRESULTS}
\begin{tabular}{| p{.175\textwidth} | >{\centering\arraybackslash\hspace{0pt}}p{.125\textwidth} | >{\centering\arraybackslash\hspace{0pt}}p{.34\textwidth} | >{\centering\arraybackslash\hspace{0pt}}p{.34\textwidth} |} 
\hline
\textbf{Theory}  & \textbf{Variable} & \textbf{Turnout Effect} & \textbf{Rolloff Effect} \\[2ex] \hline
Habit-forming voters  & Lagged turnout & 10 point lagged turnout $\uparrow = 0.8$ point turnout $\uparrow $& 5\% $\uparrow$ lagged turnout = $\downarrow$ 0.25 point rolloff 
\\ \hline
Rational Voters & VAP & 4.5 point turnout $\uparrow$ for VAP $\downarrow$ from 
6,000 to 2,100 & 2.9 point rolloff $\downarrow$ for VAP $\downarrow$ from 
6,000 to 2,100  \\ \hline
Rational Voters & Blais-Lago & 1 SD $\uparrow$ in BL = $\uparrow$ turnout 0.5 points
& None. \\ \hline
Pivotal Voter & VAP x Blais-Lago &\vspace{-4mm} \begin{itemize}[leftmargin=*] \setlength\itemsep{-2pt}
\item Large district: 0.35 point turnout $\uparrow$ when $\uparrow$ 
0.5 SD of Blais-Lago
\item Small district:  0.18 point turnout $\uparrow$ when $\uparrow$ 0.5 SD 
of Blais-Lago
\end{itemize} \vspace{-8mm} & \vspace{-4mm} \begin{itemize}[leftmargin=*] \setlength\itemsep{-2pt}
\item Large district: 0.41 point rolloff $\downarrow$ when BL $\uparrow$ 0.5 SD
\item Small district:  0.26 point rolloff $\uparrow$ when BL $\uparrow$ 0.5 SD
\end{itemize} \vspace{-8mm} \\ \hline
Social Group & Teacher \% of SB & \vspace{-4mm} \begin{itemize}[leftmargin=*] \setlength\itemsep{-2pt}
\item Large district: 0.25 point turnout $\downarrow$ when $\uparrow$ 
0.5 SD of teacher share
\item Small district:  0.18\% point turnout $\downarrow$ when $\uparrow$ 0.5 SD 
of teacher share
\end{itemize} \vspace{-8mm} & None. \\ \hline
Social Group & Teacher \% of VAP & None. & \vspace{-4mm} \begin{itemize}[leftmargin=*] \setlength\itemsep{-2pt}
\item Large district: 0.88 point rolloff $\uparrow$ when $\uparrow$ 
0.5 SD of teacher share
\item Small district:  0.2 point rolloff $\uparrow$ when $\uparrow$ 0.5 SD 
of teacher share
\end{itemize} \vspace{-8mm} \\ \hline
Social Group & Party Divide & None. &\vspace{-4mm} \begin{itemize}[leftmargin=*] \setlength\itemsep{-2pt}
\item Large district: 1 point $\uparrow$ rolloff as party division $\uparrow$ 6.6\% points
\item Small district:  0.15 point $\downarrow$ for rolloff as party division $\uparrow$ 6.6\% points
\end{itemize} \vspace{-8mm} \\ \hline
Social Group & Dem. Share & None. &\vspace{-4mm} \begin{itemize}[leftmargin=*] \setlength\itemsep{-2pt}
\item Large district: 0.29 point $\uparrow$ rolloff as Dem. share $\uparrow$ 5\% point
\item Small district:  0.6 point $\uparrow$ rolloff as Dem. share $\uparrow$ 5\% point
\end{itemize} \vspace{-8mm} \\ \hline
\end{tabular}
\end{scriptsize}
\end{center}
\end{table}

In the rest of this section, I conduct simulations to show the change in the 
dependent variable holding all else constant and manipulating an independent 
variable of interest. I then plot the result to give a visual representation of 
the findings of the models above. While this type of simulation does not represent 
the interrelated nature of the independent variables in the models above, it does 
allow me to demonstrate the maximum possible effect predicted by the models 
described above -- assuming the independent variable is changing while all other
variables remain constant.\footnote{Simulations are conducted using a modification 
of the \texttt{sim} function in the \texttt{arm} package for R.}

In addition to demonstrating the effect of the key variables of interest, I use 
simulations to illustrate the election and school district specific effects to 
provide a sense of the scale of year to year and district to district variation 
captured in the models. This simulation technique presents caterpillar plots of 
the estimated values of the impact the unobservable characteristics of these 
grouping variables have on turnout and rolloff. 

\clearpage

\subsubsection{Turnout Models}


<<fixefplot1, eval=FALSE, fig.cap="Coefficient Plot for Full Model Fixed Effects",fig.height=8.5, fig.width=8, fig.show='hide'>>=
set.seed(51315)
sim1 <- FEsim(mixedMod1lagsb, nsims = 1000); sim1$dv <- "Lags"
sim2 <- FEsim(mixedModcloseC, nsims = 1000); sim2$dv <- "Close"
sim3 <- FEsim(fullmodMMd, nsims = 1000); sim3$dv <- "Defeat"
sim4 <- FEsim(fullmodMMblq, nsims = 1000); sim4$dv <- "Competitiveness"

simPlot <- do.call(rbind, list(sim1, sim2, sim3, sim4))
simPlot$dv <- factor(simPlot$dv, levels = c("No Incumb.", "Contest", 
                                            "Defeat", "Competitiveness"))
alpha <- 1.96
simPlot$upr <- simPlot$meanEff + (alpha*simPlot$sdEff)
simPlot$lwr <- simPlot$meanEff - (alpha*simPlot$sdEff)

simPlot$color <- "Not Sig."
simPlot$color <- ifelse(simPlot$lwr >0 | simPlot$upr < 0, "Sig", "Not Sig.")

ggplot(simPlot, aes(x = variable, y = meanEff, ymax = upr, 
                    ymin = lwr, color = color)) + 
  scale_color_brewer(palette = "Dark2") + 
  geom_point() + geom_errorbar(h=1.5) +
  geom_hline(yintercept = 0, size = I(1.1), color = I("black"), linetype = 2, 
             alpha = I(0.6)) +
  coord_flip() + 
  facet_wrap(~dv) + 
  theme_dpi(base_size=12) +theme(legend.position = "bottom") + 
  labs(x = "Variable", y = "Effect", color = "Stat. Sig.")

# confint(fullmodMMni, method = "Wald", level = 0.9)
@

Figure \ref{fig:fixefSub1} shows the simulated effect of four variables on turnout. 
These plots show four randomly sampled 
observations (represented by a different colored line) with the independent 
variable on the x-axis and the predicted school board turnout on the y-axis. Along 
the x-axis is a rug-plot showing the relative density of observations at each 
range of the x-variable to demonstrate where the model is extrapolating 
with less data. The two dashed horizontal lines shown represent the inter-quartile range 
of the predicted values. This is presented to provide 
a reference for how powerful the effect of the independent variable -- as shown 
by the slope of the line -- is relative to the overall variability in turnout. 

In Figure \ref{fig:fixefSub1} the modest effects in Table \ref{tab:turnoutRESULTS} 
are illustrated. The negative effect for the teacher share of voters 
on turnout in the top right panel show the modest impact interest groups may play 
in school board votes. The positive effect of competitiveness on turnout is 
depicted in the bottom left. On the other 
diagonal there is an expected relationship between prior turnout and current 
turnout as positive and fairly strong. Partisan division has no measurable effect 
on turnout. 

Taken together with the results in Table \ref{tab:turnoutRESULTS} it seems clear 
that net of election cycle and district long-term trends, as well as demographic 
characteristics of the communities, school board election turnout is relatively 
unmoved by these factors. 


<<fixefSub1, eval=TRUE, fig.scap="Substantive Effect on School Board Turnout Across Cases",fig.cap="Effect of four variables on school board turnout. Each panel represents the results from a different model for a different explanatory variable. Each line in each panel represents a randomly selected school district. The line represents the change in the expected turnout for that case as the value of the explanatory value is increased across the distribution.">>=
set.seed(51315)
seplotdf <- 1
while(class(seplotdf) != "data.frame"){
  seplotdf <- try(substEffSimFE(mixedModP, "partyDivisionFall", ncases = 4L, 
                          unscale = moddatScaleParty, re = FALSE), 
                  silent = TRUE)
}

lowerBar <- ((quantile(fitted(mixedModP), prob = 0.25) * 2 * moddatScaleParty["turnout", 2]) + 
      moddatScaleParty["turnout", 1]) / 100
upperBar <- ((quantile(fitted(mixedModP), prob = 0.75) * 2 * moddatScaleParty["turnout", 2]) + 
      moddatScaleParty["turnout", 1]) / 100

seplotdf$yhatUnscale <- seplotdf$yhatUnscale / 100
seplotdf$lwrUnscale <- seplotdf$lwrUnscale / 100
seplotdf$uprUnscale <- seplotdf$uprUnscale / 100

p1 <- ggplot(seplotdf, aes(x = newvarUnscale, y = yhatUnscale)) +
  geom_line(aes(group = caseID, color = factor(caseID)), size = I(1.05)) + 
  scale_color_discrete(guide = FALSE) +
    geom_ribbon(aes(ymin=lwrUnscale, ymax=uprUnscale, group = caseID),
                     alpha=0.1) + 
#   facet_wrap(~caseID) + 
  geom_hline(yintercept = lowerBar, linetype = 2) + 
  geom_hline(yintercept = upperBar, linetype = 2) + 
  geom_rug(data = dist_turn, aes(x = partyDivisionFall, y = NULL)) + 
  theme_dpi(base_size=12) + 
  labs(x = "Partisan Division", y = "School Board Turnout")+ 
  scale_y_continuous(label = percent, limits = c(0, .50))

seplotdf <- 1
while(class(seplotdf) != "data.frame"){
  seplotdf <- try(substEffSimFE(mixedModteachD, "teachShareofVoters2", ncases = 4L, 
                          unscale = moddatScaleTeach, re = TRUE), 
                  silent = TRUE)
}
lowerBar <- ((quantile(fitted(mixedModteachD), prob = 0.25) * 2 * moddatScaleTeach["turnout", 2]) + 
      moddatScaleTeach["turnout", 1]) /100
upperBar <- ((quantile(fitted(mixedModteachD), prob = 0.75) * 2 * moddatScaleTeach["turnout", 2]) + 
      moddatScaleTeach["turnout", 1]) / 100

seplotdf$yhatUnscale <- seplotdf$yhatUnscale / 100
seplotdf$lwrUnscale <- seplotdf$lwrUnscale / 100
seplotdf$uprUnscale <- seplotdf$uprUnscale / 100

p2 <- ggplot(seplotdf, aes(x = newvarUnscale, y = yhatUnscale)) +
  geom_line(aes(group = caseID, color = factor(caseID)), size = I(1.05)) + 
  scale_color_discrete(guide = FALSE) +
    geom_ribbon(aes(ymin=lwrUnscale, ymax=uprUnscale, group = caseID),
                     alpha=0.1) + 
#   facet_wrap(~caseID) + 
  geom_hline(yintercept = lowerBar, linetype = 2) + 
  geom_hline(yintercept = upperBar, linetype = 2) + 
  geom_rug(data = dist_turn, aes(x = teachShareofVoters2, y = NULL)) + 
  theme_dpi(base_size=12) + 
  labs(x = "Teacher Share of Voters", y = "School Board Turnout") + 
  scale_y_continuous(label = percent, limits = c(0, .50)) + 
  scale_x_continuous(label = percent, limits = c(0, 0.5))
seplotdf <- 1
while(class(seplotdf) != "data.frame"){
  seplotdf <- try(substEffSimFE(mixedModcloseC, "minBlaisLago", ncases = 4L, 
                          unscale = moddatScaleClose, re = TRUE), 
                  silent = TRUE)
}

lowerBar <- ((quantile(fitted(mixedModcloseC), prob = 0.25) * 2 * moddatScaleClose["turnout", 2]) + 
      moddatScaleClose["turnout", 1]) /100
upperBar <- ((quantile(fitted(mixedModcloseC), prob = 0.75) * 2 * moddatScaleClose["turnout", 2]) + 
      moddatScaleClose["turnout", 1]) / 100

seplotdf$yhatUnscale <- seplotdf$yhatUnscale / 100
seplotdf$lwrUnscale <- seplotdf$lwrUnscale / 100
seplotdf$uprUnscale <- seplotdf$uprUnscale / 100

p3 <- ggplot(seplotdf, aes(x = newvarUnscale, y = yhatUnscale)) +
  geom_line(aes(group = caseID, color = factor(caseID)), size = I(1.05)) + 
  scale_color_discrete(guide = FALSE) +
    geom_ribbon(aes(ymin=lwrUnscale, ymax=uprUnscale, group = caseID),
                     alpha=0.1) + 
#   facet_wrap(~caseID) + 
  geom_hline(yintercept = lowerBar, linetype = 2) + 
  geom_hline(yintercept = upperBar, linetype = 2) + 
  geom_rug(data = dist_turn, aes(x = minBlaisLago, y = NULL)) + 
  theme_dpi(base_size=12) + 
  labs(x = "Blais-Lago Competitiveness", y = "School Board Turnout") + 
  scale_y_continuous(label = percent, limits = c(0, .50))
seplotdf <- 1
while(class(seplotdf) != "data.frame"){
  seplotdf <- try(substEffSimFE(mixedMod1lagsb, "turnoutLag2", ncases = 4L, 
                          unscale = moddatScaleLag, re = TRUE), 
                  silent = TRUE)
}
lowerBar <- ((quantile(fitted(mixedMod1lagsb), prob = 0.25) * 2 * moddatScaleLag["turnout", 2]) + 
      moddatScaleLag["turnout", 1]) /100
upperBar <- ((quantile(fitted(mixedMod1lagsb), prob = 0.75) * 2 * moddatScaleLag["turnout", 2]) + 
      moddatScaleLag["turnout", 1]) / 100

seplotdf$yhatUnscale <- seplotdf$yhatUnscale / 100
seplotdf$lwrUnscale <- seplotdf$lwrUnscale / 100
seplotdf$uprUnscale <- seplotdf$uprUnscale / 100

p4 <- ggplot(seplotdf, aes(x = newvarUnscale, y = yhatUnscale)) +
  geom_line(aes(group = caseID, color = factor(caseID)), size = I(1.05)) + 
  scale_color_discrete(guide = FALSE) +
    geom_ribbon(aes(ymin=lwrUnscale, ymax=uprUnscale, group = caseID),
                     alpha=0.1) + 
#   facet_wrap(~caseID) + 
  geom_hline(yintercept = lowerBar, linetype = 2) + 
  geom_hline(yintercept = upperBar, linetype = 2) + 
  geom_rug(data = dist_turn, aes(x = turnoutLag2, y = NULL)) + 
  theme_dpi(base_size=12) + 
  labs(x = "Lagged SB Turnout (2)", y = "School Board Turnout") + 
  scale_y_continuous(label = percent, limits = c(0, .50)) +
  scale_x_continuous(label = percent, limits = c(0, 0.35))

grid.arrange(p1, p2, p3, p4, main = "Simulated Effects on School Board Turnout")
@

<<fixefSub2, eval=TRUE, results='hide'>>=
seplotdf <- 1
while(class(seplotdf) != "data.frame"){
  seplotdf <- try( substEffSimFE(mixedModteachD, "teachShareofVoters2", ncases = 64L, 
                          unscale = moddatScaleTeach, re = TRUE), 
                  silent = TRUE)
}
lowerBar <- ((quantile(fitted(mixedModteachD), prob = 0.25) * 2 * moddatScaleTeach["turnout", 2]) + 
      moddatScaleTeach["turnout", 1]) /100
upperBar <- ((quantile(fitted(mixedModteachD), prob = 0.75) * 2 * moddatScaleTeach["turnout", 2]) + 
      moddatScaleTeach["turnout", 1]) / 100

seplotdf$yhatUnscale <- seplotdf$yhatUnscale / 100
seplotdf$lwrUnscale <- seplotdf$lwrUnscale / 100
seplotdf$uprUnscale <- seplotdf$uprUnscale / 100

seplotdf$sizeCut <- cut(seplotdf$VAP_adjLOG, 
                        breaks = quantile(mixedModteachD@frame$VAP_adjLOG, 
                                          prob = c(0, 0.25, .5, .75, 1)), 
                        labels = c("VAP Quart. 1", "VAP Quart. 2", "VAP Quart. 3", "VAP Quart. 4"))

TeachInteractPlot <- ggplot(seplotdf, aes(x = newvarUnscale, y = yhatUnscale)) +
  geom_line(aes(group = caseID), alpha = 0.4, size = I(1.05)) +
  facet_wrap(~sizeCut) +
  geom_hline(yintercept = lowerBar, linetype = 2) + 
  geom_hline(yintercept = upperBar, linetype = 2) + 
  geom_rug(data = dist_turn, aes(x = teachShareofVoters2, y = NULL)) + 
  theme_dpi(base_size=12) + 
  labs(x = "Teacher Share of Voters", y = "School Board Turnout") + 
  scale_y_continuous(label = percent, limits = c(0, .50)) + 
  scale_x_continuous(label = percent)

@


<<fixefSub3, results='hide'>>=
# mixedModPb
seplotdf <- 1
while(class(seplotdf) != "data.frame"){
  seplotdf <- try(substEffSimFE(mixedModPb, "fallTwoPartyShareDem", ncases = 64L, 
                          unscale = moddatScaleParty, re = TRUE), 
                  silent = TRUE)
}
lowerBar <- ((quantile(fitted(mixedModPb), prob = 0.25) * 2 * moddatScaleParty["turnout", 2]) + 
      moddatScaleParty["turnout", 1]) /100
upperBar <- ((quantile(fitted(mixedModPb), prob = 0.75) * 2 * moddatScaleParty["turnout", 2]) + 
      moddatScaleParty["turnout", 1]) / 100

seplotdf$yhatUnscale <- seplotdf$yhatUnscale / 100
seplotdf$lwrUnscale <- seplotdf$lwrUnscale / 100
seplotdf$uprUnscale <- seplotdf$uprUnscale / 100

seplotdf$sizeCut <- cut(seplotdf$VAP_adjLOG, 
                        breaks = quantile(mixedModPb@frame$VAP_adjLOG, 
                                          prob = c(0, 0.25, .5, .75, 1)), 
                        labels = c("VAP Quart. 1", "VAP Quart. 2", "VAP Quart. 3", "VAP Quart. 4"))

PartyInteractPlot <- ggplot(seplotdf, aes(x = newvarUnscale, y = yhatUnscale)) +
  geom_line(aes(group = caseID), alpha = 0.4, size = I(1.05)) +
  facet_wrap(~sizeCut) +
  geom_hline(yintercept = lowerBar, linetype = 2) + 
  geom_hline(yintercept = upperBar, linetype = 2) + 
  geom_rug(data = dist_turn, aes(x = fallTwoPartyShareDem, y = NULL)) + 
  theme_dpi(base_size=12) + 
  labs(x = "Democratic Two-Party Share", y = "School Board Turnout") + 
  scale_y_continuous(label = percent, limits = c(0, .50)) + 
  scale_x_continuous(label = percent)
@

One possible reason these simulated results show such modest effects is that a 
large degree of variance in turnout is explained by individual school district 
unobservable characteristics captured as random intercepts in the mixed model 
framework. All of the models specified included random intercepts for both 
school districts and election cycles as a way to control for unobservable 
characteristics of each district and secular change in turnout from spring election 
to spring election. Figure \ref{fig:randomEffectplot1} demonstrates the variability 
in the district intercepts from one of the models.\footnote{This figure is derived 
from the partisanship model in particular, but the school district intercepts are 
remarkably stable across all of the model specifications and this figure can be 
interpreted as representative of all of these models.} This figure represents the 
change in turnout for a randomly selected school district 
election as it is moved from the lowest through the highest school district 
intercept. Thus, it represents how much turnout would change in a school district 
election if it were modified by the effect of each other school district in the 
state. This figure arranges the estimate of the individual intercept 
for in each district, and its corresponding 90\% confidence interval, from lowest to 
highest to depict the variability in district intercepts. The horizontal dashed 
lines represent the middle two quartiles of fitted school board election turnout 
from the model. The vertical lines mark the top most and bottom most decile of 
school district effects. \footnote{Extracting the parameter estimates from 
random effect models is not straightforward and there are many ways to estimate 
the resulting confidence intervals. Here I use the simulation method proposed 
by \citet{gelhill} and implemented in the excellent \texttt{arm} package 
\citep{armpkg}.} 

The results in \ref{fig:randomEffectplot1} show that moving from 
the bottom decile to the top decile in district effect results in an increase of 
nearly 10\% points in school board turnout. This effect is quite large in comparison 
with the effects shown in Figure \ref{fig:fixefSub1}, suggesting that community 
factors unmeasured in this study explain a large part of the variance in turnout 
between school districts. This effect exists even with the inclusion of strong 
demographic and historical controls like school district size and historical 
school board turnout. 

<<randomEffectplot1, eval=TRUE, fig.scap="Exploring the Variance in District Effects on School Board Turnout", fig.cap="Simulated effect of district effects on turnout. As a case moves from the lowest turnout effect to the highest turnout effect, the effect of the district on turnout is represented by the line with a 90 percent confidence interval represented by the gray ribbon. This figure shows the results for the partisan divide model, but all models reported in the text show a similar distribution. The horizontal bars represent the interquartile range of the dependent variable, and the vertical bars represent the 20th and 80th percentile of school district effects.", fig.height=3.5>>=
replotdf <- 1
while(class(replotdf) != "data.frame"){
  replotdf <- try(substEffSimRE(mixedModP, "distid", ncases = 1, alpha = 0.1), 
                  silent = TRUE)
}

replotdf$distid <- as.character(replotdf$distid)
replotdf$yhatUnscale <- (replotdf[, "yhat"] * 2 * moddatScaleParty[1, 2]) + 
  moddatScaleParty[1, 1]
replotdf$yhatUnscale <- replotdf$yhatUnscale / 100
replotdf$lwrUnscale <- (replotdf[, "lwr"] * 2 * moddatScaleParty[1, 2]) + 
  moddatScaleParty[1, 1]
replotdf$lwrUnscale <- replotdf$lwrUnscale / 100
replotdf$uprUnscale <- (replotdf[, "upr"] * 2 * moddatScaleParty[1, 2]) + 
  moddatScaleParty[1, 1]
replotdf$uprUnscale <- replotdf$uprUnscale / 100

lowerBar <- ((quantile(fitted(mixedModP), probs = 0.25) * 2 * 
                moddatScaleParty["turnout", 2]) + moddatScaleParty["turnout", 1]) /100
upperBar <- ((quantile(fitted(mixedModP), probs = 0.75) * 2 * 
                moddatScaleParty["turnout", 2]) + moddatScaleParty["turnout", 1]) / 100

ggplot(data = replotdf, aes(x = reorder(distid, yhatUnscale), y = yhatUnscale, 
                            ymin = lwrUnscale, ymax = uprUnscale)) + 
  geom_line(aes(group = caseID)) + 
    geom_ribbon(aes(group = caseID), alpha=0.4) + 
  theme_dpi(base_size=12) + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), 
                      strip.text = element_blank(), 
                      strip.background = element_blank(), 
                      panel.grid.minor = element_blank(), 
                      panel.grid.major = element_blank()) + 
  geom_hline(yintercept = lowerBar, linetype = 2) + 
  geom_hline(yintercept = upperBar, linetype = 2) + 
  geom_vline(xintercept = 31) + 
  geom_vline(xintercept = 280) + 
  facet_wrap(~caseID, ncol = 1) + 
  labs(x = "District", y = "Predicted SB Turnout") + 
  scale_y_continuous(label = percent, limits = c(0, .5))
@

<<rePlotHide, fig.show='hide'>>=
plotdf <- REsim(mixedModP, nsims = 1000)
plotdf <- plotdf[plotdf$level == "Level 1",]
p1 <- plotMCMCre(plotdf, scale = 1.96, var = "mean", 
               sd = "sd", sigmaScale = sigma(mixedModP)) + 
  labs(title = "Partisan Model", x= "District", y = "Intercept")+ 
  ylim(c(-2, 3.5))
plotdf <- REsim(mixedModclose, nsims = 1000)
plotdf <- plotdf[plotdf$level == "Level 1",]
p2 <- plotMCMCre(plotdf, scale = 1.96, var = "mean", 
                 sd = "sd", sigmaScale = sigma(mixedModclose)) + 
  labs(title = "Competitiveness Model", x= "District", y = "Intercept")+ 
  ylim(c(-2, 3.5))
plotdf <- REsim(mixedModteach, nsims = 1000)
plotdf <- plotdf[plotdf$level == "Level 1",]
p3 <- plotMCMCre(plotdf, scale = 1.96, var = "mean", 
                 sd = "sd", sigmaScale = sigma(mixedModteach))+ 
  labs(title = "Teach Share Model", x= "District", y = "Intercept")+ 
  ylim(c(-2, 3.5))
plotdf <- REsim(mixedModlags, nsims = 1000)
plotdf <- plotdf[plotdf$level == "Level 1",]
p4 <- plotMCMCre(plotdf, scale = 1.96, var = "mean", 
                 sd = "sd", sigmaScale = sigma(mixedModlags))+ 
  labs(title = "Lagged Model", x= "District", y = "Intercept") + 
  ylim(c(-2, 3.5))

grid.arrange(p1, p2, p3, p4)
@


\clearpage

\subsubsection{Rolloff}

<<fixefSubUndv, results='hide'>>=
library(gridExtra)
seplotdf <- 1
while(class(seplotdf) != "data.frame"){
  seplotdf <- try(substEffSimFE(undervoteMMlag, "turnoutLag2", ncases = 4L, 
                          unscale = moddatScaleUndervote, re = FALSE), 
                  silent = TRUE)
}
lowerBar <- ((quantile(fitted(undervoteMMlag), prob = 0.2) * 2 * moddatScaleUndervote["turnoutDiff", 2]) + 
      moddatScaleUndervote["turnoutDiff", 1]) / 100
upperBar <- ((quantile(fitted(undervoteMMlag), prob = 0.8) * 2 * moddatScaleUndervote["turnoutDiff", 2]) + 
      moddatScaleUndervote["turnoutDiff", 1]) / 100

seplotdf$yhatUnscale <- seplotdf$yhatUnscale / 100
seplotdf$lwrUnscale <- seplotdf$lwrUnscale / 100
seplotdf$uprUnscale <- seplotdf$uprUnscale / 100

p1 <- ggplot(seplotdf, aes(x = newvarUnscale, y = yhatUnscale)) +
  geom_line(aes(group = caseID, color = factor(caseID)), size = I(1.05)) + 
  scale_color_discrete(guide = FALSE) +
    geom_ribbon(aes(ymin=lwrUnscale, ymax=uprUnscale, group = caseID),
                     alpha=0.1) + 
#   facet_wrap(~caseID) + 
  geom_hline(yintercept = lowerBar) + 
  geom_hline(yintercept = upperBar) + 
  geom_rug(data = dist_turn, aes(x = turnoutLag2, y = turnoutDiff)) + 
  theme_dpi(base_size=12) + 
  labs(x = "Lagged Turnout Prior", y = "Voter Rolloff in % Points") + 
  scale_x_continuous(label = percent) + 
  scale_y_continuous(limits = c(-.2, .2))

# -----------------------------------------------------------------
seplotdf <- 1
while(class(seplotdf) != "data.frame"){
  seplotdf <- try(substEffSimFE(undervoteMMpartyB, "partyDivisionFall", ncases = 64L, 
                          unscale = moddatScaleUndervote, re = TRUE), 
                  silent = TRUE)
}

lowerBar <- ((quantile(fitted(undervoteMMpartyB), prob = 0.2) * 2 *
                moddatScaleUndervote["turnoutDiff", 2]) + 
      moddatScaleUndervote["turnoutDiff", 1]) /100

upperBar <- ((quantile(fitted(undervoteMMpartyB), prob = 0.8) * 2 * 
                moddatScaleUndervote["turnoutDiff", 2]) + 
      moddatScaleUndervote["turnoutDiff", 1]) / 100

seplotdf$yhatUnscale <- seplotdf$yhatUnscale / 100
seplotdf$lwrUnscale <- seplotdf$lwrUnscale / 100
seplotdf$uprUnscale <- seplotdf$uprUnscale / 100

seplotdf$sizeCut <- cut(seplotdf$VAP_adjLOG, 
                        breaks = quantile(undervoteMMpartyB@frame$VAP_adjLOG, 
                                          prob = c(0, 0.25, .5, .75, 1)), 
                        labels = c("VAP Quart. 1", "VAP Quart. 2", "VAP Quart. 3", "VAP Quart. 4"))

p2 <- ggplot(seplotdf, aes(x = newvarUnscale, y = yhatUnscale)) +
  geom_line(aes(group = caseID), alpha = 0.4, size = I(1.05)) +
  facet_wrap(~sizeCut) +
  geom_hline(yintercept = lowerBar, linetype = 2) + 
  geom_hline(yintercept = upperBar, linetype = 2) + 
  geom_rug(data = dist_turn, aes(x = partyDivisionFall, y = turnoutDiff)) + 
  theme_dpi(base_size=12) + 
  labs(x = "Fall Party Division", y = "Voter Rolloff in % Points") 

# -------------------------------------------------------------------------------
seplotdf <- 1
while(class(seplotdf) != "data.frame"){
  seplotdf <- try(substEffSimFE(undervoteMMteach, "teachShareofVoters", ncases = 64L, 
                          unscale = moddatScaleUndervote, re = TRUE), 
                  silent = TRUE)
}
lowerBar <- ((quantile(fitted(undervoteMMteach), prob = 0.2) * 2 * 
                moddatScaleUndervote["turnoutDiff", 2]) + 
      moddatScaleUndervote["turnoutDiff", 1]) /100

upperBar <- ((quantile(fitted(undervoteMMteach), prob = 0.8) * 2 * 
                moddatScaleUndervote["turnoutDiff", 2]) + 
      moddatScaleUndervote["turnoutDiff", 1]) / 100

seplotdf$yhatUnscale <- seplotdf$yhatUnscale / 100
seplotdf$lwrUnscale <- seplotdf$lwrUnscale / 100
seplotdf$uprUnscale <- seplotdf$uprUnscale / 100

seplotdf$sizeCut <- cut(seplotdf$VAP_adjLOG, 
                        breaks = quantile(undervoteMMteach@frame$VAP_adjLOG, 
                                          prob = c(0, 0.25, .5, .75, 1)), 
                        labels = c("VAP Quart. 1", "VAP Quart. 2", "VAP Quart. 3", "VAP Quart. 4"))
seplotdf <- na.omit(seplotdf)
p3 <- ggplot(seplotdf, aes(x = newvarUnscale, y = yhatUnscale)) +
  geom_line(aes(group = caseID), alpha = 0.4, size = I(1.05)) +
  facet_wrap(~sizeCut, nrow=1) +
  geom_hline(yintercept = lowerBar, linetype = 2) + 
  geom_hline(yintercept = upperBar, linetype = 2) + 
  geom_rug(data = dist_turn, aes(x = teachShareofVoters, y = turnoutDiff)) + 
  theme_dpi(base_size=12) + 
  scale_x_continuous(limits = c(0, .06), label = percent) + 
  scale_y_continuous(limits = c(-.15, .2)) +
  labs(x = "Teacher Share of VAP", y = "Voter Rolloff in % Points") 

# -------------------------------------------------------------------------------
seplotdf <- 1
while(class(seplotdf) != "data.frame"){
  seplotdf <- try(substEffSimFE(undervoteMMclose, "minBlaisLago", ncases = 32L, 
                          unscale = moddatScaleUndervote, re = TRUE), 
                  silent = TRUE)
}

lowerBar <- ((quantile(fitted(undervoteMMclose), prob = 0.2) * 2 * 
                moddatScaleUndervote["turnoutDiff", 2]) + 
      moddatScaleUndervote["turnoutDiff", 1]) /100

upperBar <- ((quantile(fitted(undervoteMMclose), prob = 0.8) * 2 * 
                moddatScaleUndervote["turnoutDiff", 2]) + 
      moddatScaleUndervote["turnoutDiff", 1]) / 100

seplotdf$yhatUnscale <- seplotdf$yhatUnscale / 100
seplotdf$lwrUnscale <- seplotdf$lwrUnscale / 100
seplotdf$uprUnscale <- seplotdf$uprUnscale / 100

seplotdf$sizeCut <- cut(seplotdf$VAP_adjLOG, 
                        breaks = quantile(undervoteMMclose@frame$VAP_adjLOG, 
                                          prob = c(0, 0.25, .5, .75, 1)), 
                        labels = c("VAP Quart. 1", "VAP Quart. 2", 
                                   "VAP Quart. 3", "VAP Quart. 4"))
seplotdf <- na.omit(seplotdf)
p4 <- ggplot(seplotdf, aes(x = newvarUnscale, y = yhatUnscale)) +
  geom_line(aes(group = caseID), alpha = 0.4, size = I(1.05)) +
  facet_wrap(~sizeCut, nrow=1) +
  geom_hline(yintercept = lowerBar, linetype = 2) + 
  geom_hline(yintercept = upperBar, linetype = 2) + 
  geom_rug(data = dist_turn, aes(x = minBlaisLago, y = turnoutDiff)) + 
  theme_dpi(base_size=12) + 
  scale_y_continuous(limits = c(-.15, .2)) + 
  labs(x = "Blais-Lago", y = "Voter Rolloff in % Points") 

@

Here I depict the evidence 
that influences on voter rolloff appear more pronounced than influences on turnout 
and are strongly interacted with community size. 

Figure \ref{fig:teachUndEff} depicts the simulated impact of increasing teacher 
share of the voting age population on voter rolloff. Each panel represents a 
quartile of the VAP distribution and each line in each panel represents a single 
district being simulated. The line represents the change in voter rolloff for 
that district as the teacher share of the VAP is increased from its minimum of 
0.8\% to its maximum of 5\%. As before, the dashed horizontal lines represent the 
median two quartiles of the distribution of the rolloff variable. 

Two patterns emerge immediately from this figure. First, teacher share of the 
population has a consistent positive impact on rolloff across districts of all 
sizes. Second, the interaction effect is quite strong. As districts get 
larger, the impact of teachers grows stronger and in the second and third quartile, 
the impact of moving from 2\% to 3\% teachers in the VAP can increase voter rolloff 
in school board elections enough to move between quartiles. Though this effect 
is quite striking it is important to remember that these are simulations and have 
their limitations -- the simulation in the final panel, for the largest 
districts, depicts the very unlikely scenario in which the most populated 
Wisconsin school districts have a population consisting of 5\% teachers 
employed in public schools. However, despite this fact, it is clear that there 
is a sizable impact on rolloff explained by the share of the VAP that are teachers. 

Figure \ref{fig:compUndEff} provides same look at an interactive effect with 
district size, but for school board seat competitiveness. Each panel represents 
one quartile of the voting age population variable. Competitiveness has an 
almost imperceptible role in small districts, but as districts get larger toward 
the right, more competitive races result in reduced voter rolloff. In larger 
communities, competitive races may be more necessary to drive turnout because 
personal contact is more difficult and media coverage of local elections is 
scarce \citep{oliver}.

<<teachUndEff, fig.scap="Interaction Effect of Teacher Share on Rolloff", fig.height=4, fig.cap="Interaction between teacher share of the VAP and district VAP on school board voter rolloff. Each panel displays a random sample of districts within a quartile of the VAP distribution. Each line represents the predicted rolloff for a single district as the teacher share of VAP is increased. The horizontal dotted lines represent the interquartile range of the rolloff variable.">>=
p3
@

<<compUndEff, fig.scap="Interaction Effect of Competition on Rolloff", fig.height=4, fig.cap="Interaction between the Blais-Lago quotient and district VAP on school board voter rolloff. Each panel displays a random sample of districts within a quartile of the VAP distribution. Each line represents the predicted rolloff for a single district as the competitiveness of races is increased. The horizontal dotted lines represent the interquartile range of the rolloff variable.">>=
p4
@

<<effPlotHide, fig.show='hide'>>=
p1

p2
@

\clearpage

\section{Discussion}

Overall, unlike the results in Chapter \ref{chap:candidacy}, the results in this chapter 
reflect theoretical expectations for election behavior. This suggests that although 
the school board electorate is different than the general election electorate, 
it behaves in expected ways -- that is, spring voters are habit forming, selective 
about their vote mattering, and influenced by social group mechanisms. 

\subsection{Results}

This chapter has explored the explanatory power of four different theories of voter 
turnout in small democracies using the example of Wisconsin school board elections 
from 2002-2012. In this exploration of democracy at the small scale, there was 
consistent evidence to support each of the theories - habit forming voters, 
rational voters, and social group led voters. To test this theory 
I used two separate measures of voter turnout. First, the estimated number of 
voters in school board elections as a share of the voting age population residing 
in the school district. The second, rolloff, is a measure of the proportion of 
voters who cast a ballot for the top ticket race (a non-partisan statewide office) 
but did not cast a ballot for school board. This second measure provides a measure 
of school board turnout net of the macro political forces that may be shaping 
spring turnout. 

The strongest evidence is in support of habit-forming electorates. Even after controlling 
for demographic factors, turnout in the fall election cycle, and unobservable 
community characteristics lagged turnout remained a substantively important 
predictor of turnout in school board elections. This means that communities with 
higher historical spring election participation will have smaller rolloff on 
school board ballots and overall higher turnout in the spring election. Though 
non-partisan spring school board elections have much lower levels of turnout, 
they appear to be behaving similarly to other electorates. And, by modeling 
unobservable school district characteristics which are also likely to include 
the civic character of the electorate, the estimated impact of twice-lagged 
school board turnout reported in this chapter is likely an underestimate of the
stickiness of school board turnout year to year.  

There is also support for rational voters. School district 
size explains more of the variance in voter turnout and rolloff than any other 
variable of theoretical interest. These data provide a great test of this theory 
because of the large variance in electorate size from a few hundred to tens of 
thousands of voters. Smaller communities exhibit much higher voter turnout than 
larger communities -- all else equal. Additionally, voters in smaller communities 
are more likely to cast a ballot for school board after casting a ballot in the 
top ticket election. In fact, in small communities, it can happen that more voters 
abstain from the top of the ticket race than from the school board. This ``turnout 
twist'', as it is called by \citet{Horiuchi2001}, may have a number of contributing mechanisms including personal familiarity with the candidate, a higher sense of 
influence, and a stronger sense of social obligation 
\citep{oliver,Plutzer2002,Mueller3, aldrich1993}. 

The other variables of theoretical interest had measurable impact on turnout and 
rolloff as well, but not with the substantive magnitude of the above impacts. 
Competitiveness led to an increase in turnout but did not affect rolloff. 
That is, competitiveness explained the number of voters going to the poll and 
voting for school board, but not the share of all voters who did not complete a 
school board ballot. Interestingly, there is evidence that the impact of 
competitiveness is partially attenuated by the size of the district. Larger districts 
have an increase in turnout when races are competitive that is larger than the 
increase in smaller districts. Additionally, rolloff is decreased in larger 
districts when races are competitive, but in smaller districts, rolloff will 
increase (suggesting turnout is saturated and additional turnout is not 
interested in school board). 

Taken together, this suggests that, despite a lack of campaigning by candidates 
or major media coverage, voters in school board elections may be able to assess 
whether or not to vote based on an assessment of how contested a race will be and 
they are more able to do so in smaller communities where informal information 
networks may be more far reaching. On the other hand, it may be that voters are much 
more likely to hear about a school board election if it is competitive, and so 
they are more likely to be reminded to vote. Without further study into the motives 
and knowledge of individual voters in spring elections it is hard to know 
what in particular is shaping voter behavior. However, at the community level 
there is evidence that having more competitive elections drives turnout up. 

The evidence of direct influence of social groups is less consistent and strong. 
I was only to test for the influence of a couple of interest groups -- 
political parties and teacher unions. Teacher unions appear to suppress turnout, 
albeit to a modest degree. They also increase rolloff, again to a higher degree 
in larger communities than in smaller communities. This may be due to a deterrent 
effect -- if the nomination process is controlled by interest groups, voters 
may feel less clear that they have a true choice between candidates 
\citep{RefWorks:207}. 

Partisan divides increases rolloff, but with differential effects between small 
and large communities. In fact, in small communities, partisan divide leads to 
a decrease in rolloff on the part of voters. However, in larger communities rolloff 
increases greatly with deeper partisan divides. This seems likely due to increased 
turnout for top ticket spring non-partisan races in communities with deep party 
divisions where party activists may be working to turn voters out for non-partisan 
races. The spring 2011 Supreme Court race in Wisconsin is a prime example of a 
non-partisan statewide race that turned into a deep battle between parties. 
Parties may be doing organizing for the top ticket spring race -- such as 
State Superintendent or Supreme Court -- and 
increasing voter turnout for these races by providing information to voters on 
policy preferences of the candidates. If parties are successful in organizing voters 
for top ticket races, then more voters with less interest in down-ticket races like 
school board may find themselves at the polls and thus not interested in casting 
a vote in school board races.\footnote{As further evidence, the partisanship 
variables and their interaction with VAP are statistically significant predictors 
in models using spring election top ticket turnout as the dependent variable.}

\subsection{Limitations and Future Work}

This study is not without its limits. A first limitation is the question of how 
much spring election voter turnout can be considered to be driven by local 
down-ticket elections. This is particularly true during the period of study in 
this chapter, which included the highest turnout spring election in Wisconsin 
history -- a result that cannot be attributed to a slate of particularly 
contentious school board elections. In an effort to address these concerns I 
examined a narrower dependent variable -- the difference in turnout between the top spring 
ticket and the school board race. While this addresses the concern about falsely 
attributing larger spring election forces to school boards, more evidence directly 
about school boards would be preferred -- particularly the information available 
to individual voters at the time of their decision.

This study is an attempt to infer voter behavior from the observed patterns 
of turnout and rolloff observed over the last several years in a sample of 
Wisconsin school districts. It is not appropriate to draw conclusions about the 
behavior of individuals from the group level results presented here. Thus, while 
theories of habit-forming voters are in
accordance with the pattern observed here, this study is limited by its inability
to peer into the rationales of individual voters. In order to disentangle the many
confounding theories, future research must survey eligible voters and ask them about
their decision to vote or not vote in local school board elections like the work
of \citet{oliver12}. In fact, such local election studies suggest that much voter 
turnout in local elections is issue based. The large remaining unexplained variance 
uncovered here could be in part due to the lack of district-election specific 
issue measures. Chapter \ref{chap:walker} will attempt to address this concern, 
in part, by measuring community preferences on a statewide education issue. 

Third, there is a limited ability to draw causal inferences from this study. 
While all of the results presented are net of a set of strong 
control variables and after conditioning out unobservable election and school 
district specific effects, there may be a large set of potential omitted variables 
responsible for the patterns shown here. Chapter \ref{chap:walker} will 
leverage an exogenous statewide shock to school board elections to investigate 
the causal impact of some of these variables on turnout and lend more support to 
these findings.

\subsection{Theory}

Actualized democracy in the form of voter turnout is rare in school board elections. 
However, unlike the case of contestation, the democratic potential is also low given 
the structural and informational barriers to voting. This chapter has shown that 
many of the forces that shape voter turnout in state and national 
elections also shape turnout in spring non-partisan elections. However, this 
turnout still remains very small and these forces are very likely shaping an 
unrepresentative subset of the residents in a school district. There is evidence 
that school board election turnout is shaped by interest groups. However, this 
low turnout is only consequential if this subset of the electorate is representing 
interests out of alignment with the wider voting age population of the school 
district. This is the question that I turn to in the next chapter. 

\clearpage

\section{Appendix}
\label{sec:appendixT}

Sensitivity checks and further table analysis. 


<<ModFitExamp, fig.cap="Example Model Fit Plot",fig.show='hide'>>=
modelFitexamplePlot
@


<<interactPlot1, fig.cap="Illustrating Interaction Effects with District Size and Partisanship", fig.show='hide'>>=
PartyInteractPlot
@

<<interactPlot2, fig.cap="Illustrating Interaction Effects with District Size",fig.show='hide'>>=
TeachInteractPlot
@

<<interactPlot3, fig.cap="Prior Turnout Effect on Voter Rolloff",fig.show='hide'>>=
p1
@

<<interactPlot4, fig.cap="Partisan Division Effect on Voter Rolloff in Spring", fig.show='hide'>>=
p2
@

\subsection{Random Effect Specification Tests}

Likelihood Ratio Test results for models with and without a third level of 
year effects. In all cases the year effects should be retained. I used the 
simulated finite sample distribution of the Restricted Likelihood Ratio Test 
\citep{rlrt1, rlrt2, rlrt3}. Computation implemented using the \texttt{RLRsim} 
package for R \citep{rlrt2}. 


<<LRTresults, echo=FALSE, results='hide'>>=
# Lag Model LRT
print(lagLRT)
# Competitive Model LRT
print(closeLRT)
# Party Model LRT
print(partyLRT)
# Teacher Model LRT
print(teachLRT)

lagLRT$p.value <- ifelse(lagLRT$p.value < 0.01, 0.01, lagLRT$p.value)
closeLRT$p.value <- ifelse(closeLRT$p.value < 0.01, 0.01, closeLRT$p.value)
partyLRT$p.value <- ifelse(partyLRT$p.value < 0.01, 0.01, partyLRT$p.value)
teachLRT$p.value <- ifelse(teachLRT$p.value < 0.01, 0.01, teachLRT$p.value)
@


\begin{myitemize}
\item Lag Model: p-value < \Sexpr{lagLRT$p.value}
\item Competitiveness Model: p-value < \Sexpr{closeLRT$p.value}
\item Partisanship Model: p-value < \Sexpr{partyLRT$p.value}
\item Teacher Influence Model: p-value < \Sexpr{teachLRT$p.value}
\end{myitemize}

\subsection{Additional Substantive Effect Plots}

Figure \ref{fig:randomEffectplot2} shows the standardized intercepts for each 
election cycle -- here the year effects are measured in standard deviations from 
the grand average of 0 marked by the red line. From 2004 to 2009 elections were 
relatively consistent with one another in terms of turnout. From 2010 to 2012, 
turnout was first depressed, and then heightened across the state. Most interestingly 
is that two years of elevated turnout across the state (net of district-election and 
district-average effects) were in 2011 and 2012 after the election of Governor Scott Walker and the introduction of Act 10. 

<<rePlotHide2, fig.show='hide'>>=
replotdf <- 1
while(class(replotdf) != "data.frame"){
  replotdf <- try(substEffSimRE(mixedModclose, "year", ncases = 1, alpha = 0.1), 
                  silent = TRUE)
}

replotdf$year <- as.character(replotdf$year)

replotdf$yhatUnscale <- (replotdf[, "yhat"] * 2 * moddatScaleParty[1, 2]) + moddatScaleParty[1, 1]
replotdf$yhatUnscale <- replotdf$yhatUnscale / 100
replotdf$lwrUnscale <- (replotdf[, "lwr"] * 2 * moddatScaleParty[1, 2]) + moddatScaleParty[1, 1]
replotdf$lwrUnscale <- replotdf$lwrUnscale / 100
replotdf$uprUnscale <- (replotdf[, "upr"] * 2 * moddatScaleParty[1, 2]) + moddatScaleParty[1, 1]
replotdf$uprUnscale <- replotdf$uprUnscale / 100

lowerBar <- ((quantile(fitted(mixedModP), prob = 0.2) * 2 * moddatScaleParty["turnout", 2]) + 
      moddatScaleParty["turnout", 1]) /100
upperBar <- ((quantile(fitted(mixedModP), prob = 0.8) * 2 * moddatScaleParty["turnout", 2]) + 
      moddatScaleParty["turnout", 1]) / 100

ggplot(data = replotdf, aes(x = year, y = yhatUnscale, 
                            ymin = lwrUnscale, ymax = uprUnscale)) + 
  geom_errorbar(width = .4) + geom_point()+
  theme_dpi(base_size=12) + 
  theme(
                      strip.text = element_blank(), 
                      strip.background = element_blank(), 
                      panel.grid.minor = element_blank()) + 
  geom_hline(yintercept = lowerBar, linetype = 2) + 
  geom_hline(yintercept = upperBar, linetype = 2) + 
  facet_wrap(~caseID, ncol = 1) + 
  labs(x = "Year", y = "Predicted SB Turnout") + 
  scale_y_continuous(label = percent)


plotdf <- REsim(mixedModP, nsims = 1000)
plotdf <- plotdf[plotdf$level == "Level 2",]
p1 <- plotMCMCre(plotdf, scale = 1.96, var = "mean", 
               sd = "sd", sigmaScale = sigma(mixedModP)) + 
  labs(title = "Partisan Model", x= "District", y = "Intercept")+ 
  ylim(c(-2, 3.5))
plotdf <- REsim(mixedModclose, nsims = 1000)
plotdf <- plotdf[plotdf$level == "Level 2",]
p2 <- plotMCMCre(plotdf, scale = 1.96, var = "mean", 
                 sd = "sd", sigmaScale = sigma(mixedModclose)) + 
  labs(title = "Competitiveness Model", x= "District", y = "Intercept")+ 
  ylim(c(-2, 3.5))
plotdf <- REsim(mixedModteach, nsims = 1000)
plotdf <- plotdf[plotdf$level == "Level 2",]
p3 <- plotMCMCre(plotdf, scale = 1.96, var = "mean", 
                 sd = "sd", sigmaScale = sigma(mixedModteach))+ 
  labs(title = "Teach Share Model", x= "District", y = "Intercept")+ 
  ylim(c(-2, 3.5))
plotdf <- REsim(mixedMod1lagsb, nsims = 1000)
plotdf <- plotdf[plotdf$level == "Level 2",]

grid.arrange(p1, p2, p3, main = "Variance in Year Intercepts Across Models")
@

<<randomEffectplot2, eval=TRUE, fig.scap="Comparing Year Effects for Turnout",fig.height=4, fig.cap="Estimated year effects in model effect size terms. Each point represents the estimated standard deviation increase or decrease in turnout for a given election year across all school districts. Confidence intervals are the 90 percent confidence interval across 1000 simulations of the model random effects.">>=

plotdf$median <- plotdf$median / sigma(mixedMod1lagsb)
plotdf$sd <- plotdf$sd / sigma(mixedMod1lagsb)

ggplot(plotdf, aes(x = as.numeric(X1), y = median, ymin = median - 1.6 * sd, 
       ymax = median + 1.6*sd)) + geom_pointrange() + 
  labs(x= "Year", y = "Intercept", "Year Effect Sizes") + 
  scale_x_continuous(breaks = c(2003:2012), labels = c(2003:2012)) + 
  scale_y_continuous(breaks = seq(-1.5, 1.5, by = .25)) + 
  geom_hline(yintercept = 0, size =I(1.05), color = I("red")) +
  theme(axis.text.x=element_text(), panel.grid = element_line(), 
         panel.grid.major = element_line(linetype="dotted", colour ="black"),
        panel.grid.major.x = element_blank(), 
         panel.grid.minor = element_blank(), 
         panel.background = element_rect(fill = "white", colour = NA), 
            panel.border = element_rect(fill = NA, colour = "grey50"), 
        axis.title = element_text(size = rel(0.8), face = "bold"), 
            axis.title.y = element_text(vjust = 0.35, angle = 90), 
            axis.text = element_text(size = rel(0.8), colour = "black"), 
        axis.ticks = element_line(colour = "black", 
                size = rel(1.5)), legend.key = element_rect(colour = "grey80"), 
            legend.title = element_text(), legend.text = element_text())
@


\subsection{District and Year Fixed Effect Results for Turnout}

District fixed effect model results. 

<<lagmodTab, results='asis', include=FALSE>>=
lagmodTab
@

<<appA1, results='asis', include=FALSE>>=
appA1
@

<<closeModTab, results='asis', include=FALSE>>=
closeModTab
@

<<teachTab1, results='asis', include=FALSE>>=
teachTab1
@

<<partyModtab, results='asis', include=FALSE>>=
partyModtab
@
