\chapter{Why Run for School Board?}
\label{chap:candidacy}
\chapterstyle{deposit}


<<rsetup, results='hide', echo=FALSE, message=FALSE, warning=FALSE>>=
opts_chunk$set(fig.width=8, fig.height=6, message=FALSE, error=FALSE, 
               fig.path="../../phd_figs/chap3-", 
               cache.path = "../../phd_cache/chap3-",
               warning=FALSE, echo=FALSE, dev = c('pdf','png'))

setwd("../../")
library(eeptools)
source("R/thesis_functions.R")
source("data/dataAssemble.R")
source("data/cleanandprep_CANDIDACY.R")

library(xtable)
options(xtable.include.rownames = FALSE, xtable.table.placement = "ht")
library(gridExtra)
library(scales)
library(reshape2)
# library(devtools)
# install_github("jknowles/apsrtable", subdir = "pkg", ref = "dev")
library(apsrtable)
@


\section{Introduction}

By all accounts being a school board member is a thankless job. 
School board meetings frequently occur in the evening to allow parents and 
community members to participate, and very few school board members are 
compensated for their work \citep{RefWorks:333, RefWorks:321}. Contrary to 
popular conceptions, the role of the school board as a stepping stone to future 
elected office is overstated \citep{RefWorks:321, RefWorks:322}. In fact, the dissatisfaction
incumbents have with the position has been a confounding factor in the literature; 
in comparison to state or national offices, non-political turnover due to 
retirement from the seat is the most common form of exit \citep{RefWorks:311}. 

% Need a vignette here about a school baord member

More so than other political offices, the elected school 
board begs the question: why run? Political scientists have grappled with this 
question across contexts for decades, and a number of explanations have been put 
forth. This chapter will review these theories and evaluate their explanatory power 
for school boards. With a unique data set that includes the political 
histories of over 300 Wisconsin school districts from 2002-2012 I will investigate 
empirical support for these theories. In particular, the panel nature of the 
data set allows me to test competing claims about the role that salient policy 
and political factors play in the emergence of candidates for school boards. 
Finally, this chapter will consider the importance of candidate emergence in a 
full model of school district political activity outlined in Figure \ref{model}. 

\section{Theories of Candidate Emergence}

I organize the political science literature around candidate emergence into three broad schools of thought.

\begin{myitemize}
\item Strategic Candidates
\item Political Individuals
\item Policy Preferences
\end{myitemize}

In addition to these broad theoretical treatments of candidacy, I review the sparse 
literature that has focused explicitly on local elections such as municipal, county, 
and school board elections. Before beginning, it is important to consider the features 
of local elections and offices that might set them apart from state and national 
legislative office. 


\subsection{Strategic Timing of Candidate Entry}

Simply put, the strategic view of candidate entry argues that candidates emerge for 
office when they perceive victory to be most likely \citep{schlesinger1}. This 
includes avoiding running against incumbents or choosing to run against incumbents 
when they are weak or when redistricting has altered the political conditions in 
the district \citep{Black1972}. However, candidates are not merely strategic 
within their individual race, but are also sensitive to macro-level partisan trends.
\citet{JacobsonBook}'s strategic timing theory argues that high-quality challengers 
emerge when favorable electoral conditions emerge for their party. For U.S. House election, 
strategic timing has been found to increase the likelihood of a win 
and increases the vote-share of such candidates \citep{JacobsonStrategy}. This 
foundational finding matches well with the evidence that 
national legislative contests do appear to become more heated with higher quality 
challengers emerging when incumbents appear weak, districts are redrawn, or 
national trends appear in the favor of the challenger's party. 

The strategic timing theory has tended to ignore that political 
amateurs also behave in this manner \citep{CanonArt, CanonBook}. 
By only defining a high-quality challenger as a prior office holder, the strategic 
timing and rational entry models have misrepresented the decision calculus made 
by candidates when deciding to run for office. \citet{Lazarus2008} 
enters into this debate by explicitly testing the differences between amateurs 
and high quality candidates, while also focusing on the differences between the 
decision to challenge in a primary and in a general election. This study finds 
that the correlates of candidate entry are different for experienced challengers 
and political amateurs. Unfortunately, the problem of how to operationalize 
experience for challengers looms large in this literature, and even larger when 
seeking to generalize the strategic candidate model to lower levels of 
government, where candidates are likely to be beginning their political career. 
Certainly, defining candidate quality as holding prior office creates a very 
different and much smaller group of candidates than in higher level state and 
federal offices.\footnote{Candidate quality may look entirely different at the 
local level where long community ties, a local business, or a family history 
may play more important roles at the more personal level of politics practiced 
here \citep{oliver12}.}

Though strategic timing has empirical support from U.S. Congressional elections, 
important questions remain about how to operationalize some of the key concepts of 
the model when applying it outside of these offices. How do we think of candidate 
quality for local offices such as mayor (think Michael Bloomberg) or school board? 
Does strategic timing operate in an implicitly non-partisan environment (urban 
areas with a single party in control) or explicitly non-partisan offices such as 
most American school boards? Local political jurisdictions thus present an 
important extension of the empirical testing of this model. 

\subsection{Political Individuals}

For some political scientists, strategic timing stops short of explaining the
 behavior of candidates and leaves out the important question of why a candidate 
will seeks office in the first place. The factors that lead someone to run, whether 
due to personal experience, social status, exposure to political communities, or 
status in a historically politically marginalized group profoundly shape the supply 
of candidates for office \citep{AJPS:AJPS147}. Furthermore, limiting the definition 
of high quality challengers to those with prior experience running for or holding office 
excludes high quality amateurs such as celebrities and the wealthy 
\citep{CanonArt, CanonBook, fowler96}. By explaining the initial choice to run 
for office, or political ambition, we paint a richer picture of the pool from 
which candidates for office will be drawn. For local elections, it is important 
to consider the traits associated with being a political candidate, as it can 
help operationalize the size of the pool of potential candidates in a community -- 
a key aspect of its democratic potential. 

This personal motivation tradition was founded by \citet{Lasswell}'s theory of a 
``political person'' who sought political power. The first studies to operationalize 
what features make up such a ``political person'' focused on personality and individual 
attributes \citep{barber1, fishel1}, a line of research that laid dormant for some time 
after the emergence of the rational model. A more quantitative return to 
the study of such political ambition emerged with \citet{AJPS:AJPS147}'s study of 
political psychology directed at explaining the ``nascent'' aspects of political ambition
through predictive features of candidates themselves. 

This work builds on the seemingly unremarkable foundation that political 
candidates are likely to possess more time, money, and civic skills to 
devote to running for office \citep{Verba1}. But, in fact, only a small subset 
of individuals with time, money, and resources run for political office - for 
example, university professors are surprisingly absent from the ballot. This requires further 
investigation as to what differentiates those with resources who choose to run for 
office from those who do not. Family and childhood socialization can account for 
the desire to acquire these resources and devote them to office - sometimes very 
early on in life \citep{prewitt1, beckjennings}. 
\citet{AJPS:AJPS147} attempt to test this and a number of additional explanations 
such as measures of individual self-efficacy, stage in life, ambition, demographics, 
and opportunity both perceived and partisan. The authors find that these factors 
substantially ``winnow'' the pool of potential candidates with time, money, and resources to 
pursue office into a much smaller group of actual candidates - whose entry into 
an election the rational model attempts to explain. 

The present study does not have the ability to delve into the 
ambition and psychology of candidates for school board elections, though quality 
descriptive work has been done exploring the political and personal backgrounds of 
school board members as reviewed in Chapter \ref{chap:intro} 
\citep{RefWorks:321, RefWorks:322, RefWorks:333}. The important contribution of 
this work is that helps to define attributes that correlate with the supply of 
candidates. In large jurisdictions the supply can be safely assumed to be 
saturated, but in a community of a few thousand adults eligible for office, it 
can not. Understanding the traits of the ``political person'' can help 
operationalize measures that control for the size of the potential candidate pool 
in comparing across jurisdictions. Furthermore, work on lower levels of government 
may uncover other important linkages and help inform how such local institutions 
can be shaped in such a way as to foster the development of quality candidates. 
The pool of candidates in small restricted jurisdictions is an important constraint 
on the democratic potential of those communities and forms a key trade off with the more 
personal campaigning possible in such situations. 


\subsection{Policy Change}

Though high-profile candidates sometimes run with explicit policy goals 
in mind, it has yet to be assessed if candidates for local office are motivated 
by explicit policy goals with any level of regularity. While the desire to set 
policy may seem like an intuitive and perhaps obvious explanation for candidates 
running for office, its explanatory power relative to other measures of opportunity, 
socialization, and candidate self-assessment is quite small \citep{AJPS:AJPS147}. 
\citet{deckman1} suggests that with school board candidates there may be a strong policy 
orientation, and that in some cases this policy orientation may be explicitly developed by 
well-organized interest groups \citep{RefWorks:240}. Deckman's study of the 
organization of the Christian right to locate, train, and fund candidates for 
school board provides evidence that strong policy motivation and organized 
interest groups can spur candidates to run. Evaluating competing explanations 
about the motivations of school board candidates in a more rigorous way may help 
shed light on the motivations of the larger pool of candidates. 

\subsection{Local and Special Purpose Governments}

Another reason to explore candidate emergence in different jurisdictions is that 
different types of elected office are likely to attract different types of 
candidates. A priori there are many reasons to believe that local elections in general, and 
school board elections in particular, are qualitatively different than state or 
federal office in America. The most critical of these with relation to the above 
theories is that in most cases school board is a non-partisan office \citep{oliver}. 
Partisanship is a foundational aspect of the strategic candidate framework and 
to a lesser degree necessarily motivates the goals of policy-oriented office 
seekers. Without party lines and with a less divisive set of issues to 
distinguish and motivate candidates, it may be hard for individuals to exercise 
a strategic or a policy oriented candidacy. 

\citet{RefWorks:218} has found 
evidence that school board elections can be characterized by issues defined by 
teacher unions - which can serve the role of a large external organizers of 
voters, donors, and nominator of candidates \citep{RefWorks:207}.\footnote{Though 
see \citet{boardfundraising2008} for important counter evidence about the role 
of large organized interests in the financing of school board campaigns.} However, 
there are studies in the literature where the applicability of the 
strategic emergence and personal and psychological factors have been tested 
empirically, most notably in city council elections \citep{boardfundraising2008, prewitt1, 
bledsoe1}. \citet{Krebs01111999} finds evidence of strategic candidate emergence 
in ward level elections. However, school board members differ yet from these local 
candidates due to their role as political actors within the limited policy sphere 
of public education and the power of property tax levies.\footnote{Though in practice 
the power to set property tax levels is often constrained by both state law and 
practical concerns \citep{berry2}.} 

Political science has a rich history of studying the applicability of theories 
of candidate participation to local governmental organizations more broadly. Local 
governments can be thought of as being either general (municipal or county wide general 
service agencies) or special (school, fire, or water districts, etc.) purpose 
\citep{fosterK}. \citet{oliver} identifies a framework for understanding the 
variability in electoral participation across local governmental units around the 
concepts of size, scope, and bias. In this framework, the amount and type of 
political contestation for local offices is shaped by the relative size of the 
governmental unit, the scope of that unit's policy making, and the specificity or 
universality of the benefits and services provided by that unit to the population. 
Thus, in order to understand the likelihood of new candidates to run for office, 
we must account for the size of the population from which candidates may be drawn, 
the variation in the level of services the governmental unit provides, and the 
degree to which those services are distributed evenly within the community. 
Chapter \ref{chap:wisco} demonstrates that Wisconsin school districts have variation 
in Oliver's categories of size and bias, but almost all school districts are equal 
in the scope of their policy making as they are proscribed in state law. 

% \citet{krebs} provides a model for a study of the effect of incumbency and the 
% participation of candidates in local elections. That study restricts candidates 
% to those receiving 5\% of the vote and includes a measure for the level of competition. 

An important overarching distinction is that most of the previous literature on 
local elections and school boards treats the individual race between candidates 
as the atomic unit. This study does not do so for a number of reasons. First, 
school board races are less frequently head to head contests for a single seat 
than other common forms of local government such as city council, mayoral, or 
county board seats. Second, theory suggests that voters have very little information 
about individual school board members and are much more likely to make any voting 
decisions about the board as a whole by evaluating district wide conditions instead 
of features of individual board members \citep{oliver}. 

\section{Data}
\label{sec:data}

I now turn my attention to my investigation of the factors that influence 
the emergence of candidates in school board elections. In this study, two 
approaches will be taken to allow for a more explicit test of the theories outlined 
above. 

\subsection{Wisconsin Data}

This paper utilizes a unique data set of school board election results in the state 
of Wisconsin from 2002-2012.\footnote{For more details on the collection method, 
see the Appendix \ref{app:data}.} While previous studies of school board elections have focused 
on nationally representative samples (and been plagued by non-response for smaller 
districts which constitute the majority of school board members), or statewide 
samples for a snapshot in time, this data follows in the 
tradition of \citet{RefWorks:311} by constructing a panel of school board elections 
within a single state. In addition to collecting the results of all school board 
general elections for which records could be obtained throughout this time period, 
this study also includes the results from any primary elections that were held 
as well. The longitudinal look is used in order to allow for possibility of 
observing the periodic eruption of voter and candidate activity expected by 
dissatisfaction theory \citep{RefWorks:297,RefWorks:271}. 

This database on the electoral outcomes of each school board is accompanied by 
a broad range of attributes about the school districts they oversee. In addition 
to the unique data set on school board election results described in 
Chapter \ref{chap:wisco}, there exists 
a large array of publicly available data about the performance, finances, 
and demographics of the public school districts in the state. These data are useful 
in understanding the impact of local factors on school board election conditions. 
Importantly, we can use these data to identify if the sample of school 
districts responding to the records request is representative of the school 
districts in the state. From Table \ref{tab:samplecomp} we saw 
that the school districts providing records did not differ significantly in any 
key variable from those who did not provide records on observable characteristics. 

\subsection{Data Structure and Grouping}

School districts as jurisdictions can have multiple election races per election 
cycle with multiple winners per race. Unlike in studies of legislative elections, 
then, the electoral district is not unique to a single race each year. Instead, 
a school district may feature two or three distinct races for school board each year, 
with each race electing multiple winners.\footnote{See Appendix \ref{app:data} for 
details about the coding of races.}

<<datastructure, results='asis'>>=
tablestruc <- ddply(races, .(year), summarize, 
                    districts = length(unique(distid)), 
                    races = length(raceid2))
names(tablestruc) <- c("Year", "Districts", "Races")
tmp.cap   <- "Frequency of multiple races within a district by year."
tmp.label <- "tab:mrfreq"
print(xtable(t(tablestruc[tablestruc$Year > 2001 & tablestruc$Year < 2013, ]), 
             caption = tmp.cap, 
             label = tmp.label), include.colnames = FALSE, 
      include.rownames=TRUE)

@

Table \ref{tab:mrfreq} shows that there are a bout 100 more races than districts 
in each year. Due to the relatively few unique variables I have at the level of the school 
district race, I aggregate multiple races per district into a single district-year 
observation. This aggregation is done by summing the number of candidates, winners, 
votes, and incumbents across races and including a binary indicator if any of the 
races was a district wide race. I also include the maximum value of the coding for 
the presence of a contested race. This approach is similar to the approach of 
\citet{berry2} as a solution to handle the case where jurisdictional overlap is 
difficult to determine. 

\clearpage
\subsection{Dependent Variables}

Previous research has focused on incumbent challenges or candidate self-reports of 
contestation in their most recent elections \citep{RefWorks:311, RefWorks:321}. 
By collecting election results I observe the level of contestation 
in school board elections directly for the first time. This allows me to construct 
multiple measures of contestation, the presence of multiple choices for voters on 
the ballot. Choice among candidates is a key component of the democratic potential 
of a jurisdiction, and one criticism leveled against school boards and other local 
offices is that they are undemocratic due to a lack of choice for voters. 

I conceptualize the degree of candidate emergence for school boards as qualitatively 
three distinct levels. The first, and lowest level, is whether any candidates other 
than incumbents appear on the ballot. In lieu of partisanship, local elections are 
often conceived of as races between incumbents and challengers \citep{oliver07,oliver12}. 
I refer to this variable as ``incumbent lockout'', when incumbents are the only 
candidates, and I focus on predictors for when it does not occur. However, merely 
having non-incumbents on the ballot does not mean voters have a full choice, 
as non-incumbents often run unopposed so the second level of competitiveness is the 
presence of more candidates than seats on the ballot. Finally, the ultimate measure of 
competitiveness is whether or not any incumbents are defeated or at risk of defeat. 
I investigate the ability of political theory to explain each of these three levels 
of competitiveness to understand if school district election competitiveness at any 
level is predicted by theory. 

<<nonincumbent2, results='asis'>>=
races$contestMinor <- 0
races$contestMinor[races$nrealcand > races$nwins] <- 1
races$contestSer <- 0
races$contestSer[(races$nrealcand - races$nminor) > races$nwins] <- 1
races$incumbOnly <- ifelse(races$nrealcand == races$ninc, 1, 0)

# table(dist_turn$contestSer, dist_turn$incDefeats)
dist_turn$contestSer <- 0
dist_turn$contestSer[(dist_turn$nrealcand - dist_turn$nminor) > dist_turn$nwins] <- 1
dist_turn$contestMinor <- 0
dist_turn$contestMinor[dist_turn$nrealcand > dist_turn$nwins] <- 1
dist_turn$incumbOnly <- ifelse(dist_turn$nrealcand == dist_turn$ninc, 1, 0)
tab1 <- table(dist_turn$incumbOnly, dist_turn$contestSer)
tab2 <- table(races$incumbOnly, races$contestSer)

rownames(tab1) <- c("Non-Incumbents Run", "Only Incumbents")
colnames(tab1) <- c("No Serious Challengers", "Serious Challengers")

tmp.cap   <- "Frequency of Incumbency and Contestation Across School Board Races."
tmp.label <- "tab:icbychal"

print(xtable(tab1, caption = tmp.cap, 
             label = tmp.label, digits = 0), include.rownames=TRUE, 
      format.args = list(big.mark= ","))

@

Table \ref{tab:icbychal} shows the relationship between incumbency and challengers 
across all school district elections in the sample. The modal elections consists of either 
contested open seats or uncontested races with only incumbents. Measuring candidate 
emergence and contestation in multi-member seats is not as straightforward as in single 
member districts. \footnote{In school board races in Wisconsin there is rarely a seriously 
contested race with all incumbents. This is due to the relative infrequency with 
which school board seats are changed or redrawn. In addition, even if the race is 
between two incumbents, the research literature around school boards suggests 
that the strongest signal most voters have about candidate policy goals is incumbency status. 
Thus, voters are unlikely able to parse the policy differences between two incumbents. 
For voters, choosing between two incumbents is not likely to present much of a true choice.} Taking 
Table \ref{tab:icbychal} into account, I frame contestation in school 
boards as a three step process. First, voters have to have a choice of a candidate
that is not an incumbent. If all the candidates are incumbents, then voters cannot 
reasonably be said to have a choice and it can be assumed that the school board 
seat is not sufficiently attractive to potential candidates. Next, voters have to
have a choice between more candidates than there are open seats. Finally, the 
ultimate measure of contestation is that an incumbent is successfully defeated. 
Table \ref{tab:icbydef} shows that in races in which 
at least one of the candidates is not an incumbent incumbent defeat is rare. 

<<nonincumbent3, results='asis'>>=
dist_turn$incDefeats <- ifelse(dist_turn$incsDefeated > 0, 1, 0)
dist_turn$incDefeatFac <- ifelse(dist_turn$incDefeats > 0, 1, 0)

tabdf <- dist_turn[dist_turn$ninc > 0, c("incumbOnly", "contestSer", "incDefeatFac")]

tab1 <- table(tabdf$contestSer[tabdf$incumbOnly ==0], 
              tabdf$incDefeatFac[tabdf$incumbOnly ==0])

colnames(tab1) <- c("Incumbents All Win", "Incumbent Defeated")
rownames(tab1) <- c("No Serious Challengers", "Serious Challengers")

tmp.cap   <- "Frequency of Incumbency Defeat and Contestation in School Districts."
tmp.label <- "tab:icbydef"

print(xtable(tab1, caption = tmp.cap, 
             label = tmp.label, digits = 0), include.rownames=TRUE, 
      format.args = list(big.mark= ","))

@

This three step approach means that I model three separate dependent variables 
and explore the way the explanatory variables discussed above explain or do not 
explain the variation in these three degrees of contestation. 

\subsubsection{Non-incumbents}

<<nonincumbent, results='asis'>>=
tablestruc <- ddply(races[races$nwins > 0,], .(year), summarize, 
                    districts = length(unique(distid)), 
                    races = length(raceid2), 
                    nonIncumbents = sum(ifelse(nrealcand > ninc, 1, 0)), 
                    incumbOnly = sum(ifelse(nrealcand == ninc, 1, 0)))

tmp.cap   <- "Frequency of races with and without non-incumbents."
tmp.label <- "tab:nifreq"

tablestruc[, "nonIncumbents"] <- iPer2((tablestruc$nonIncumbents / tablestruc$races) * 100)
tablestruc[, "incumbOnly"] <- iPer2((tablestruc$incumbOnly / tablestruc$races) * 100)
tablestruc <- tablestruc[tablestruc$year > 2001 & tablestruc$year < 2013, ]

colnames(tablestruc) <- c("Year", "Districts", "SB Races", 
                          "Non-Incumb.", "Incumb. Only")

print(xtable(tablestruc, 
             caption = tmp.cap, 
             label = tmp.label, digits = 0), include.colnames = TRUE, 
      include.rownames=FALSE)

tablestruc <- ddply(races[races$nwins > 0,], .(year), summarize, 
                    districts = length(unique(distid)), 
                    races = length(raceid2), 
                    nonIncumbents = sum(ifelse(nrealcand > ninc, 1, 0)), 
                    incumbOnly = sum(ifelse(nrealcand == ninc, 1, 0)))
@

A first condition of contestation is that someone other than incumbents run for 
office. The least competitive of all elections is that in which voters not only 
have no choice, but they have no choice and all candidates are incumbents -- the 
status quo is maintained by default. Nearly 
\Sexpr{iPer(sum(tablestruc[,"incumbOnly"])/sum(tablestruc[,"races"])*100)}, or between 
100 and 150 races, of races each year feature all incumbents. 

\subsubsection{Who Counts as a Candidate?}

The definition of a candidate is inherently subjective. Previous work in the 
literature has excluded candidates who receive fewer than 5\% of the overall vote, 
while other studies have focused exclusively on contested incumbent held seats in 
open jurisdictions \citep{krebs,oliver}. Due to the diversity of school board 
electoral organization, school district size, and the relatively low number of votes 
necessary to secure a victory, I define minor candidates as those candidates who 
receive fewer than 20 votes on the ballot and I exclude all such candidates from 
measures of contestation. This is a liberal enough interpretation 
of candidate seriousness to include write-in challenges and has the potential to 
bias results by inflating the number of contested races. However, with the 
median winning candidate needing only \Sexpr{iNum(median(dat$votes[dat$winner ==1], na.rm=TRUE))} 
votes to secure victory, 20 votes seems sizable enough to exert influence on the race overall. 


<<candidatedescriptives4, echo=FALSE, fig.cap="Annual share of contested school board elections under two different measures of candidate contestation.">>=
library(scales)
# 
races$contested <- 0
races$contested[races$nrealcand > races$nwins & 
                          races$nwins > 0 & races$electiontype == 1] <- 1
races$contestedSer <- 0
races$contestedSer[(races$nrealcand - races$nminor) > races$nwins & 
                          races$nwins > 0 & races$electiontype == 1] <- 1
#  incumbents challenged
races$contestedInc <- 0
races$contestedInc[races$nrealcand > races$ninc & 
                          races$ninc > 0 & races$electiontype == 1] <- 1
races$contestedSerInc <- 0
races$contestedSerInc[(races$nrealcand - races$nminor) > races$ninc & 
                          races$ninc > 0 & races$electiontype == 1] <- 1
# 
a <- table(races$contestedSer, races$year)
a.tmp <- prop.table(a, margin = 2) 
a <- t(a)
a.tmp <- t(a.tmp)
a <- as.data.frame(a)
a.tmp <- as.data.frame(a.tmp)
a$Var1 <- as.numeric(as.character(a$Var1))
a.tmp$Var1 <- as.numeric(as.character(a.tmp$Var1))
a$Var2 <- ifelse(a$Var2 == 0, "No", "Yes")
a$Var2 <- factor(a$Var2, levels = c("Yes", "No"))
a.tmp$Var2 <- ifelse(a.tmp$Var2 == 0, "No", "Yes")
# a.tmp$Var2 <- factor(a.tmp$Var2, levels = c("Yes", "No"))

p1 <- qplot(factor(Var1), Freq, data=a[a$Var1 > 2002 & a$Var1 < 2013,], geom='bar', stat='identity', fill=Var2, position='stack', color = I("black")) + 
  labs(x= "Year", y = "Districts", title = "Excluding Minor Candidates", 
       fill = "Contested?") + theme_bw() +
  scale_fill_brewer(type = "qual", palette = 6) 

p1 <- qplot(factor(Var1), Freq, data=a.tmp[a.tmp$Var1 > 2002 & a.tmp$Var1 < 2013,], 
            geom='bar', stat='identity', fill=Var2, position='stack', color = I("black")) + 
  labs(x= "Year", y = "Percent of Races", title = "Excluding Minor Candidates", 
       fill = "Contested?") + theme_bw() + scale_y_continuous(label = percent) +
  scale_fill_brewer(type = "qual", palette = 6) +
  guides(colour = FALSE, fill = guide_legend(reverse = TRUE, 
                                             override.aes = list(colour = NULL)))


a <- table(races$contested, races$year)
a.tmp <- prop.table(a, margin = 2) 
a <- t(a)
a.tmp <- t(a.tmp)
a <- as.data.frame(a)
a.tmp <- as.data.frame(a.tmp)
a$Var1 <- as.numeric(as.character(a$Var1))
a.tmp$Var1 <- as.numeric(as.character(a.tmp$Var1))
a$Var2 <- ifelse(a$Var2 == 0, "No", "Yes")
a$Var2 <- factor(a$Var2, levels = c("Yes", "No"))
a.tmp$Var2 <- ifelse(a.tmp$Var2 == 0, "No", "Yes")
# a.tmp$Var2 <- factor(a.tmp$Var2, levels = c("Yes", "No"))

p2 <- qplot(factor(Var1), Freq, data=a[a$Var1 > 2002 & a$Var1 < 2013,], geom='bar', stat='identity', fill=Var2, position='stack', color = I("black")) + 
  labs(x= "Year", y = "Races", title = "Including Minor Candidates", 
       fill = "Contested?")+ theme_bw() + 
  scale_fill_brewer(type = "qual", palette = 6) 

p2 <- qplot(factor(Var1), Freq, data=a.tmp[a.tmp$Var1 > 2002 & a.tmp$Var1 < 2013,], 
            geom='bar', stat='identity', fill=Var2, position='stack', color = I("black")) + 
  labs(x= "Year", y = "Percent of Races", title = "Including Minor Candidates", 
       fill = "Contested?") + theme_bw() + scale_y_continuous(label = percent) +
  scale_fill_brewer(type = "qual", palette = 6) +
  guides(colour = FALSE, fill = guide_legend(reverse = TRUE, 
                                             override.aes = list(colour = NULL)))


grid.arrange(p1, p2, main = "Comparing School Board Contestation Measures")
@

Figure \ref{fig:candidatedescriptives4} depicts the pattern of school board candidate 
emergence over time including and excluding these candidates. Contested elections are in
blue and uncontested races are in salmon. A slight trend toward fewer contested races is 
evident in both panels. The top panel, excluding minor candidates, changes the share of 
elections that are contested each year slightly, but does not change the overall pattern 
across years. 


<<perseatcontests,  echo=FALSE, fig.cap="Serious candidates per available seat by school year in Wisconsin school districts over time.">>=

races$candPerSeat <- races$nrealcand / races$nwins

qplot(factor(year), candPerSeat, 
      data=races[races$year > 2001 & races$year < 2013,], geom='boxplot') + 
  theme_bw() + 
  labs(x="Year", y="Candidates per Open Seat", 
       title = "Candidates Per Open Seat on Wisconsin School Boards") + 
  geom_hline(yintercept = 2, linetype = I(2), color = I("blue")) +
  geom_hline(yintercept = 1, linetype = I(5), color = I("red"), size = I(1.025))


@

Another way we might measure the level of candidate emergence in school board races 
would be to look at the number of candidates per seat. This measure would 
differentiate between districts with wide spread contestation and those with 
simply a single contested seat. As Figure \ref{fig:perseatcontests} demonstrates, 
the level of contestation per available seat does not change much across the years with 
the median race having 1 candidate per seat, and the majority of races having between 
1 and 2 candidates per seat. This means, for example, that a typical pattern 
of competition in a Wisconsin school board election features four candidates vying 
for three available seats, or one and a third candidates per seat. This measure 
does not appear to capture much information beyond a binary indicator for the 
presence of more than one candidate per race.

\subsubsection{District Competitiveness}

Incumbent defeat is a good measure of strong candidates emerging, but it is overly 
conservative because a challenger losing by a single vote is counted the same as 
a race where a challenger gains only a few dozen votes. Political scientists have 
developed a standardized way to assess the competitiveness of an electoral competition 
when races are for varying number of seats with varying numbers of candidates. 
This method was introduced in Chapter \ref{chap:wisco}.\footnote{See Table \ref{tab:votemargincalc} 
for a review of other possible measures.}

The preferred method from the literature is the Blais-Lago metric described 
in Table \ref{tab:votemargincalc}. This metric has the advantage of better adjusting 
the vote margin calculation for both the size of the electorate and the size of the 
election slate, thus making meaningful comparisons across diverse districts possible. 
While this method still focuses on the most competitive seat in the district, it 
better enables comparisons across districts. It represents a standardized metric for 
the number of votes needed to change the outcome of a multi-member or single member 
seat's election. I further standardize this measure so that a higher number, 100, 
represents the most competitive election, and zero represents the least competitive 
election.\footnote{This transformation is done by subtracting 100 and taking the 
absolute value. For each school district, I report the most competitive seat in the 
district.}

Figure \ref{fig:computeblaisLago1} shows the distribution of Blais-Lago Quotient 
for school districts for each year of the sample. The top panel shows this including 
races where no challenge is observed. The bottom panel adjust this and depicts only the 
\Sexpr{iPer((nrow(dist_turn[dist_turn$nrealcand > dist_turn$nwins,]) / nrow(dist_turn)) *100)} 
of seats where voters have a choice. As I noted in Section \ref{subsec:closeraces}, 
school board races that are contested are generally much closer than the contested 
multi-member districts for national legislatures that the Blais-Lago Quotient was 
first developed to evaluate \citep{blaislago}. Although incumbent defeat may be 
uncommon, races that can be decided by a handful of voters are not as uncommon. 

<<computeblaisLago1, echo=FALSE, fig.cap="Annual competitiveness of most competitive seat in each school district as measured by the Blais-Lago quotient.",fig.width=7,fig.height=8>>=

p1 <- qplot(factor(year), minBlaisLago, data = dist_turn[dist_turn$minBlaisLago > 0,], 
      geom='boxplot') + theme_dpi() + labs(x = "Year", y = "Blais-Lago Quotient", 
                                           title = "All Seats")

p2 <- qplot(factor(year), minBlaisLago, data = dist_turn[dist_turn$minBlaisLago > 0 & 
                                dist_turn$nrealcand > dist_turn$nwins,], 
      geom='boxplot') + theme_dpi() + labs(x = "Year", y = "Blais-Lago Quotient", 
                                           title = "Contested Seats")

grid.arrange(p1, p2, main = "Comparing Measures of Competitiveness Over Time")
@


\subsubsection{Incumbent Defeat}

Traditionally, the school board literature has focused on  the frequency of 
incumbent defeat. Incumbent defeat is a good measure of the democratic functioning 
of the school district as a government because it reflects the ability of voters 
to exercise a preference for change and to ``throw the bums out''. 
Incumbent defeat is at the heart of the dissatisfaction theory of school board 
participation \citep{RefWorks:297}. Previous research has found that apolitical 
forms of board member turnover often swamp political forms of turnover and skew 
results \citep{RefWorks:311}. These studies used surveys of former board members 
and asked whether their reason for no longer serving was political or apolitical -- 
allowing the observation of candidates who chose not to run due to political pressure 
or a perception of a strong emerging challenger. This is a limitation of the current 
study is identifying seat vacancies due to retirement or plausible threat where a candidate does not mount a 
campaign. This is less troubling in the school board case because the cost of 
campaigning is so low that presumably a challenged incumbent would still stand 
for election. Moreso, direct observation allows me to directly observe electoral 
for the first time, something which previously has only been analyzed through 
candidate self-report. This alternative form of measurement is a way to triangulate 
the findings of previous work. 

<<incdefeat, echo=FALSE, fig.cap="Annual share of Wisconsin school board elections featuring an incumbent with a defeated incumbent 2002-2012.">>=
races$nincDefInd <- ifelse(races$nincDef >0, 1, 0)

a <- table(races$nincDefInd[races$ninc > 0], races$year[races$ninc > 0])
a.tmp <- prop.table(a, margin = 2) 
a <- t(a)
a.tmp <- t(a.tmp)
a <- as.data.frame(a)
a.tmp <- as.data.frame(a.tmp)
a$Var1 <- as.numeric(as.character(a$Var1))
a.tmp$Var1 <- as.numeric(as.character(a.tmp$Var1))
a.tmp$Var2 <- ifelse(a.tmp$Var2 == 0, "No", "Yes")
# a.tmp$Var2 <- factor(a.tmp$Var2, levels = c("Yes", "No"))
qplot(factor(Var1), Freq, data=a.tmp[a.tmp$Var1 > 2002 & a.tmp$Var1 < 2013,], 
            geom='bar', stat='identity', fill=Var2, position='stack', 
      color = I("black")) + 
  labs(x= "Year", y = "Percent of Races", 
       title = "Percentage of Races with Incumbents Defeated", 
       fill = "Inc. Defeat") + theme_bw() + scale_y_continuous(label = percent) +
  scale_fill_brewer(type = "qual", palette = 6) +
  guides(colour = FALSE, fill = guide_legend(reverse = TRUE, 
                                             override.aes = list(colour = NULL)))
@

Figure \ref{fig:incdefeat} shows the rate of incumbent defeat in Wisconsin. The 
year with the greatest share of races featuring an incumbent that had incumbent defeat featured 
a defeat rate of \Sexpr{iPer(max(a.tmp$Freq[a.tmp$Freq < 0.5])*100)}. As we saw in 
Chapter \ref{chap:wisco} this rate of incumbent defeat is lower than other 
forms of office, but it is not as low as might be expected. \citet{oliver}'s study 
of the suburban voter found 10 out of 11 mayoral incumbents securing re-election 
and 47 out of 56 city council incumbents winning re-election. This result is encouraging 
and it suggests the potential to explore theories for why voters may prefer 
challengers over incumbents. Next I turn my attention to the selection of variables 
to explain the variability in these dependent variables. 

\clearpage

\subsection{Independent Variables}

\subsubsection{Demographics}
Both \citet{oliver} and \citet{RefWorks:297} find community demographics, and 
importantly their change, critical in understanding electoral variation both 
between school boards and within them across time. The first of these variables 
I consider is the voting age population (VAP) of 
the school district. VAP represents the pool of voters and also of potential 
candidates for school board in a community. I expect this variable to be 
positively related to contestation of school board elections both because of the 
larger pool of available candidates, but also the larger scope of influence in 
larger school districts -- which is more attractive to potential candidates 
\citep{oliver}. In addition to size, the homogeneity of the community is an 
important indicator of the level of electoral participation. I consider two types 
of homogeneity -- racial and generational. First, I include a measure of the 
percentage of the adult population in the school district that is white. While 
Wisconsin is an overwhelmingly white state, I expect racial homogeneity to be 
negatively associated with more school board contestation -- there will be less 
competition for resources neighborhood to neighborhood in the community. Additionally, 
prior research has shown that voter (and property tax payer) age is associated with 
support for local schools. The greater the percentage of elderly in the school 
district, the more participation I expect to see \citep{RefWorks:332}. 
Additionally, given the results of surveys that indicate school board members 
are more likely to be white and elderly, I expect that the increase in these 
variables is an increase in supply of potential candidates, and thus should be 
positively related to board contestation. Previous research has shown that school 
board candidates are disproportionately drawn from white, upper middle class, retired 
populations \citep{RefWorks:321, RefWorks:322, RefWorks:333}. 

The last two demographic variables are measures of wealth and income. A key feature 
of school boards is 
their ability to independently set property taxes. Following \citet{berry2} and 
others, I include a measure of the percentage of housing occupied by owners as a 
measure of both the permanency of the community (following \citet{oliver}) and the 
salience of property tax rates -- an important issue for single jurisdiction 
governments like school boards \citep{berry2}. Homeowners are more directly aware 
of property tax rates, longer term residents of the community, and thus expected 
to be more sensitive to changes in the property tax rate that is under control 
of school boards. As an additional control, I include a measure of median household 
income, but as other studies of Wisconsin school districts have noted, this does 
not exhibit much variation within Wisconsin as it does in other jurisdictions 
\citep{akrTax}.

\subsubsection{Fiscal}

Next, I consider variables measuring the scope of the school district relative 
to other local governments. \citet{berry2} finds stacking of local governments 
with overlapping taxing jurisdictions divides the attention of voters; I consider 
whether overlapping fiscal authority might divide the attention of potential 
candidates and make school boards less attractive. The first variable I consider 
is what share of its total revenue a school district raises from property taxes. 
While the intricacies of the Wisconsin school funding formula are beyond the 
scope of this study, the result of this formula is that there is much variation 
in the share of district revenues that are raised by local property owners. 
I expect the greater the share of revenue from property taxes, the more likely 
candidates are to participate because there is greater fiscal power with higher 
tax rates. However, the share of revenue derived from 
property tax may not be particularly salient to the voting population, especially 
not those without school aged children. 

Due to this, I test an alternate measure which is the share of total property tax 
revenue that is levied by school districts. This variable should also be positively 
related to candidacy -- as property tax revenue directed to schools increases as 
a share of all property tax revenue, individuals should be more motivated to 
pursue a seat on the school board \citep{berry2, oliver}.
Another indicator of the fiscal health of a school district is the available 
savings, or fund balance, of the school district. I normalize this variable to 
be a per pupil measure of dollars available in savings to the school district. 
I expect this variable to be negatively related to candidacy with districts 
that have more savings having less contestation as a result of lower overall 
fiscal pressure. A final measure of fiscal health is the level of per pupil 
spending in the school district. I expect higher spending districts to have 
higher levels of candidate contestation because of increased accountability 
pressure from the public.

It would be fair to argue that these measures seem unlikely to be salient to the 
voting public. However, voters in these off-cycle non-partisan races are very 
different than voters in the general election with evidence suggesting they are 
much more highly informed on local matters, longer term residents of the community, 
and very engaged in local affairs year round \citep{oliver}. This suggests that 
key information about the fiscal health of the community is likely to be 
familiar to the spring electorate. 

\subsubsection{Political}
Next, I look to explore the influence of political factors in the emergence of 
challenges to incumbents. First, I include a variable to control for the 
different structure of school board elections each year by controlling for the number of 
races in each school district. This variable should be positively related with 
more incumbency challenge as it represents more opportunities for a challenge 
to emerge when multiple races exist. I also test for advantage of incumbency 
by including a measure of the share of candidates who are incumbents. I expect 
this variable to be negatively related to challenge as incumbents should deter 
challengers. 

Next, I explore the impact of both turnout and partisanship in general elections 
on local elections. I am interested in the role partisan divisions among voters 
in the school district may play in the off-cycle non-partisan school board 
election cycle. I include two potential measures of partisanship. First I 
measure the average two party vote share for Democrats across the immediately 
previous Gubernatorial and Presidential fall elections. I expect this variable 
to be unrelated to challengers emerging for school board -- Republican and Democrat 
leaning communities should exhibit similar levels of local contestation. Next, I test the 
partisan polarization of the community by measuring the distance from an even 
vote share between Republican and Democratic communities by taking the absolute 
value of the difference between the Democratic vote share and the expected vote 
share in a perfectly polarized community of 0.5. The greater this difference, the 
less likely I believe candidate emergence will be due to the homogeneous nature 
of voter preferences in the community. 

A criticism of of special district elections, like school boards, is their susceptibility 
to capture by organized interests -- which in the case of school boards is most 
likely teachers' unions. Thus, as a final measure, I follow the work of 
\citet{RefWorks:207,anzia11} and explore the influence of teachers' unions in 
elections. Teachers' unions represent the strongest interest group in school board 
politics. The greater the share of the teaching staff in the voting population, 
the less likely I expect candidates to emerge. A strong interest group presence 
in the community should ensure the the board reflects interest group preferences 
and depress the need for electoral competition. 

\subsubsection{Policy}
A final set of total variables is policy related concerns. These variables 
explore the idea that candidates may emerge in response to underlying 
policy changes in the district. Policy concerns allow me to test whether or not 
voters in school board races are retrospective. A challenge with retrospective 
voting is the irregular timing of school board seat opening relative to other 
offices. Whereas the state and federal legislatures are elected on a regular cycle, 
school board seats are more like senate seats -- they come up for election at 
different times in different jurisdictions, and thus they may be influenced by 
distinct policy evaluations from voters depending on the year they are up for election. 

First, I assess the impact that a change in superintendent has on school board 
challengers. Because theory suggests that board turnover often precedes 
superintendent turnover, I posit that a new superintendent should signal a 
decrease in candidate challenges to board members as the citizen dissatisfaction 
that sparked the turnover has been relieved \cite{RefWorks:336, RefWorks:340}. 
I test for a new superintendent either in the prior year or two years prior. 

Next, I include measures of school district funding referenda. Wisconsin has 
two common types of school referenda measures -- bond and override referenda. 
Bond referenda are familiar across the United States as authority for a school 
district to raise taxes to cover the payments on a loan for the costs of infrastructure 
construction such as a new or renovated school building. Override referenda are specific 
to school funding formulas like Wisconsin and Massachusetts, where schools must 
operate under a revenue limit unless given explicit authority via an 
election to exceed that limit with additional property tax revenue.\footnote{Wisconsin 
school funding is governed by a state funding formula with a revenue limit for 
school districts. Wisconsin's revenue limit sets a cap on district spending in 
certain categories, more information can be found here: \url{http://sfs.dpi.wi.gov/sfs_revlim} Wisconsin also has a state equalization aid formula, more information 
can be found here: \url{http://sfs.dpi.wi.gov/sfs_equalaid}} Attempting 
a bond or override referenda is one of the more high profile actions a school 
board can take -- asking the public to vote for an increase of property tax rates 
in return for improved quality of educational services. As such, I expect 
failed referenda to precede challenges to school board, and I expect merely 
offering a referenda to also be related to increased challenges. 

Three other policy indicators are relevant to board challenge. The first is the 
percentage of school age children in non-public schools. I expect as this 
percentage increases, competition for school boards will decrease due to a 
reduced interest among more affluent or more religiously conservative 
families attending private schools in shaping the policy of the local 
school board. I also look at measures of student performance to test whether 
districts with higher or lower performance 
are more likely to have candidates emerge. School districts with lower performing 
students should, all else equal, have more candidates emerge as citizen dissatisfaction 
with board and district performance should be higher. Finally, I include a measure 
of the share of district salaries spent on administrators. All else equal, I expect 
more administrative school districts to have fewer board challenges. This 
expectation comes from the education administration literature which suggests 
that school board conflict comes from administration and boards not having a 
shared vision \citep{RefWorks:233}. 

Finally, I seek to control for autocorrelation in board contestation. If board 
elections are competitive consecutively because of sustained community dissatisfaction 
or the goal of seeking a majority of seats, then I expect lagged measures of 
contestation to be positively related to contestation in the current period. 
There is little evidence in the literature to suggest whether it is likely that 
sustained competition will emerge in school board elections, so I expect this 
variable to be unrelated in the models that follow. 

These expectations are summarized in Table \ref{tab:candIV}. 


\begin{table}[h!]
\begin{center}
\begin{tiny}
\caption{Available Variables and Expected Signs}
\label{tab:candIV}
\begin{tabular}{| p{.45\textwidth} | p{.12\textwidth} | p{.35\textwidth} |} 
\hline
\textbf{Variable}  & \textbf{Expected Sign} & \textbf{Short name} \\ \hline
Demographics  &  & \\ \hline 
Voting Age Population (VAP) & + & VAP \\
\% white VAP & + & per\_white \\
\% Over 65 & + & per65O \\
Median Household Income & + & median\_income \\
\% Bachelor Degree Over age 25 & + & PerBachelorOrAbove \\
Public School Pupils & + & PublicPupils \\
\% Owner Occupied Housing & + & OOH\_share \\ \hline
Fiscal & & \\ \hline
Property Tax Share of District Revenue & + & PROPERTYTAX\_REV\_SHARE \\
District Fund Balance Per Pupil & - & balance\_member \\
Per Pupil Expenditure & + & TCEC\_MEMBER; TDC\_MEMBER, TEC\_MEMBER \\
School District Share of Property Tax & + & millrateShare \\ 
Equalized Property Value Per Pupil & + & eqv\_member \\ \hline
Political & & \\ \hline
Number of Board Races & + & nraces \\
Share of Candidates Who are Incumbents & - & incumShare \\
Turnout in Fall Elections & + & fallTurnout \\
Partisanship in Fall Election & None & fallTwoPartyShareDem \\
Partisan Division in Previous Fall & + & partyDivision \\
Teacher Share of Voters & - & teachShareofVoters \\ \hline
Policy & & \\ \hline
New Superintendent & - & NEW\_SUP \\
Math and Reading Performance & - & MATH\_PROFADV\_PER READ\_PROFADV\_PER \\
Debt Referenda Attempt and Failure & + & debtFail; debtQues \\
Override Referenda Attempt and Failure & + & overrideQues; overrideFail \\
Cumulative Bond Attempts & + & cumulAttp \\
Administrator Share of Salary & - & ADMIN\_SHARE \\
Percentage of Pupils in Non-public schools & - & NonPublicPupilPer \\ 
Serious Contestation in Prior election & None & contestSerLag \\ \hline
\end{tabular}
\end{tiny}
\end{center}
\end{table}
\clearpage


\subsection{Variable Selection}

It is not feasible to test all of the variables in Table \ref{tab:candIV} 
simultaneously due to the presence of high correlation among some of these 
key indicators. In this section, I investigate the correlation among these 
variables and describe the process of reducing the list of factors in Table \ref{tab:candIV} 
to a manageable subset for inclusion in statistical models that can evaluate their 
impact. 

<<cleanupIV, echo=FALSE, results='hide'>>=
# library(GGally)
dist_turn$contest <- "Uncontested"
dist_turn$contest[dist_turn$nrealcand == dist_turn$nwins 
                  & dist_turn$ninc > 0] <- "Open Uncontested"
dist_turn$contest[dist_turn$nrealcand == dist_turn$nwins & 
                    dist_turn$ninc == 0] <- "Incumbent Uncontested"
dist_turn$contest[dist_turn$nrealcand > dist_turn$nwins 
                  & dist_turn$ninc > 0] <- "Incumbent Contested"
dist_turn$contest[dist_turn$nrealcand > dist_turn$nwins 
                  & dist_turn$ninc ==0] <- "Open Contested"

dist_turn$publicPupilCountLOG <- dist_turn$TOT_COUNT - dist_turn$TOTAL_COUNT_PVT
dist_turn$publicPupilCountLOG <- log(dist_turn$publicPupilCountLOG)
dist_turn$schoolMillShare <- dist_turn$millrate / (dist_turn$millrate +dist_turn$NonSDMill)
dist_turn$eqv_taxfiler <- dist_turn$eqv_adj_tifout / dist_turn$totalincome_count
dist_turn$OVERRIDE_ATTEMPT_CUMUL93[is.na(dist_turn$OVERRIDE_ATTEMPT_CUMUL93)] <- 0
# create a most recent partisanship variable

policyIdx <- c("NEW_SUP", "MATH_PROFADV_PER", "READ_PROFADV_PER", "debtFail", 
               "overrideFail", "overrideQues", "debtQues", "NonPublicPupilPer", 
               "ADMIN_SHARE", "ADMIN_SHARE_COMP", "debtPass", "overridePass",
               "DEBT_ATTEMPT_CUMUL93", "OVERRIDE_ATTEMPT_CUMUL93", 
               "SUP_TURNOVER_PRIOR_YEAR")

demogIdx <- c("per_white_all", "median_incomeLOG", "per65o", "VAP_adjLOG", 
              "OOH_share", "PerBachelorOrAbove", "publicPupilCountLOG", 
              "econ_disadv_per", "NonWhitePublicPupilPer")

fiscalIdx <- c("PROPERTYTAX_REV_SHARE", "balance_member_lag", "TCEC_MEMBER", 
               "TEC_MEMBER", 
               "NonSDMill", "millrate", "schoolMillShare", "millrate_delta", 
               "total_cat_aids_member", "teachSalDiff", "eqv_taxfiler")

politicIdx <- c("recentTwoPartyShareDem", "incumRun", "nraces", 
                "partyDivisionRecent", "nwins", "teachShareofVoters", 
                "overrideYesPer", "fallTurnout")

# ggpairs(dist_turn[dist_turn$year == 2011 & !is.na(dist_turn$turnout),], 
#         columns = which(names(dist_turn) %in% fiscalIdx), 
#         lower = list(continuous = "smooth"), 
#         upper = list(continuous = 'cor'), 
#         title = "Pairs Plot of Key Control Variables")

nopanel <- theme(panel.background=element_blank(),
                 panel.grid.minor=element_blank(),
                 panel.grid.major=element_blank(),
                 axis.text.x = element_text(angle = -90, hjust = 0), 
                               axis.text = element_text(colour = "black"))
@

<<prettyNameR, results='hide', echo=FALSE>>=

varNamer <- function(x){
  x <- as.character(x)
  x[x=="per65o"] <- "% 65 +"
  x[x=="PerBachelorOrAbove"] <- "% Bach. +"
  x[x=="OOH_share"] <- "% Owner Occupied"
  x[x=="econ_disadv_per"] <- "% Economic Disadv."
  x[x=="per_white_all"] <- "% White"
  x[x=="NonWhitePublicPupilPer"] <- "% Non-white Pupils"
  x[x=="VAP_adjLOG"] <- "Electorate Size"
  x[x=="median_incomeLOG"] <- "Median Income"
  x[x=="publicPupilCountLOG"] <- "Pupil Count"
  x[x=="PROPERTYTAX_REV_SHARE"] <- "% of Revenue by Prop. Tax"
  x[x=="balance_member_lag"] <- "Cash Reserves"
  x[x=="TCEC_MEMBER"] <- "Total Cost to Educate"
  x[x=="TEC_MEMBER"] <- "Total Educational Cost"
  x[x=="NonSDMill"] <- "Non School Property Tax Rate"
  x[x=="millrate"] <- "School District Millrate"
  x[x=="schoolMillShare"] <- "% Property Tax for Schools"
  x[x=="millrate_delta"] <- "Change in School Millrate"
  x[x=="total_cat_aids_member"] <- "Total Categorical Aids"
  x[x=="teachSalDiff"] <- "Teacher Salary - Median Income"
  x[x=="eqv_taxfiler"] <- "Property Wealth per Taxfiler"
  x[x=="recentTwoPartyShareDem"] <- "% Democratic"
  x[x=="incumRun"] <- "Incumbents in Race"
  x[x=="nraces"] <- "Number of Races"
  x[x=="partyDivisionRecent"] <- "Party Polarization"
  x[x=="nwins"] <- "Seats Up"
  x[x=="teachShareofVoters"] <- "% of Electorate FTE"
  x[x=="overrideYesPer"] <- "% for Revenue Limit Override"
  x[x=="fallTurnout"] <- "Turnout in Last Fall election"
  x[x=="NEW_SUP"] <- "New Superintendent"
  x[x=="MATH_PROFADV_PER"] <- "% Proficient or Adv. Math"
  x[x=="READ_PROFADV_PER"] <- "% Proficient or Adv. Read"
  x[x=="debtFail"] <- "Bond Referenda Failure"
  x[x=="overrideFail"] <- "Override Referenda Failure"
  x[x=="overrideQues"] <- "Override Referenda Offered"
  x[x=="debtQues"] <- "Debt Referenda Offered"
  x[x=="NonPublicPupilPer"] <- "% Private School"
  x[x=="ADMIN_SHARE"] <- "% of Staff Administrative"
  x[x=="ADMIN_SHARE_COMP"] <- "% of Salary for Administrators"
  x[x=="debtPass"] <- "Debt Referenda Pass"
  x[x=="overridePass"] <- "Override Referenda Pass"
  x[x=="DEBT_ATTEMPT_CUMUL93"] <- "Cumulative Debt Attempts since '93"
  x[x=="OVERRIDE_ATTEMPT_CUMUL93"] <- "Cumulative Override Attempts since '93"
  x[x=="SUP_TURNOVER_PRIOR_YEAR"] <- "Superintendent Turnover Last Year"
  return(x)
}

@

<<demogCorr1, fig.cap="Correlations of Demographic Variables", fig.height=5.5, fig.width=7.5>>=
cormat <- melt(round(cor(dist_turn[!is.na(dist_turn$turnout), 
              which(names(dist_turn) %in% demogIdx)], use = "pairwise"), 3)) 
cormat$Var1 <- varNamer(cormat$Var1)
cormat$Var2 <- varNamer(cormat$Var2)

cormat$value2 <- cut(cormat$value, 
                     breaks=c(-1,-0.75,-0.5,-0.25,0,0.25,0.5,0.75,1), 
                     include.lowest=TRUE, 
            label=c("(-0.75,-1)","(-0.5,-0.75)","(-0.25,-0.5)","(0,-0.25)",
                    "(0,0.25)","(0.25,0.5)","(0.5,0.75)","(0.75,1)")) 

qplot(x=Var1, y=Var2, data=cormat, fill=value2, geom="tile", color = I("gray40")) + 
  scale_fill_brewer(palette = "RdYlGn",name="Correlation", 
                    breaks = levels(cormat$value2), drop =FALSE)+
  geom_text(aes(label = value), size = 3) + nopanel + 
  labs(x = "", y = "") +  
  guides(colour = FALSE, fill = guide_legend(reverse = TRUE, 
                                             override.aes = list(colour = NULL)))  +
  scale_x_discrete(labels = function(x) str_wrap(x, width = 12)) +
  scale_y_discrete(labels = function(x) str_wrap(x, width = 12))

@

In Figure \ref{fig:demogCorr1} I depict the correlations between key 
demographic variables with dark red and green representing the highest negative 
and positive correlations respectively.\footnote{These figures represent the correlation 
matrix for the complete pooled data set across years and school districts. Correlations 
for individual years follow similar patterns, but are not shown. The Pearson correlation 
coefficient is reported.} The most problematic correlations are 
between the median household income and percentage of pupils in the school district 
eligible for free and reduced price lunch. The other large correlation is 
between the number of pupils in the district and the VAP. Household median 
income is also strongly correlated with the proportion of the population with a 
BA or above and with the proportion of owner-occupied housing. As a result, 
I drop median income in favor of these two variables in the models below. 

<<fiscal1, fig.cap="Correlations of Fiscal Variables", fig.height=5.5, fig.width=7.5>>=
cormat <- melt(round(cor(dist_turn[!is.na(dist_turn$turnout), 
              which(names(dist_turn) %in% fiscalIdx)], 
              use = "pairwise"), 3)) 
cormat$Var1 <- varNamer(cormat$Var1)
cormat$Var2 <- varNamer(cormat$Var2)
cormat$value2 <- cut(cormat$value, 
                     breaks=c(-1,-0.75,-0.5,-0.25,0,0.25,0.5,0.75,1), 
                     include.lowest=TRUE, 
            label=c("(-0.75,-1)","(-0.5,-0.75)","(-0.25,-0.5)","(0,-0.25)",
                    "(0,0.25)","(0.25,0.5)","(0.5,0.75)","(0.75,1)")) 

qplot(x=Var1, y=Var2, data=cormat, fill=value2, geom="tile", color = I("gray70")) + 
  scale_fill_brewer(palette = "RdYlGn",name="Correlation", 
                    breaks = levels(cormat$value2), drop =FALSE)+
  geom_text(aes(label = value), size = 3)  + nopanel + 
  labs(x = "", y = "") +  
  guides(colour = FALSE, fill = guide_legend(reverse = TRUE, 
                                             override.aes = list(colour = NULL)))+
  scale_x_discrete(labels = function(x) str_wrap(x, width = 12)) +
  scale_y_discrete(labels = function(x) str_wrap(x, width = 12))

@

Figure \ref{fig:fiscal1} shows the correlations among the fiscal measures for school 
districts. Here there are fewer extremely high correlations. The largest correlations 
belong to two pairs of four variables. Understandably, our two measures of equalized 
district costs, total district cost (TDC) per member and total complete educational cost 
(TCEC) per member, are very highly correlated with the only differences being relative spending 
on transportation and food services. In the models below, I use TCEC. The 
next set of high correlations have to do with property tax rates and population. 
The share of the millrate within the school district attributable to school district 
taxation is highly correlated with the tax rate set by the school district. 
Additionally, the amount of property value per tax filer in the community is 
highly correlated with the millrate in a negative direction. In most cases, 
I include only the millrate. 

<<politic1, fig.cap="Correlations of Political Variables", fig.height=5.5, fig.width=7.5>>=
cormat <- melt(round(cor(dist_turn[!is.na(dist_turn$turnout), 
              which(names(dist_turn) %in% politicIdx)], 
              use = "pairwise"), 3)) 
cormat$Var1 <- varNamer(cormat$Var1)
cormat$Var2 <- varNamer(cormat$Var2)
cormat$value2 <- cut(cormat$value, 
                     breaks=c(-1,-0.75,-0.5,-0.25,0,0.25,0.5,0.75,1), 
                     include.lowest=TRUE, 
            label=c("(-0.75,-1)","(-0.5,-0.75)","(-0.25,-0.5)","(0,-0.25)",
                    "(0,0.25)","(0.25,0.5)","(0.5,0.75)","(0.75,1)")) 

qplot(x=Var1, y=Var2, data=cormat, fill=value2, geom="tile", color = I("gray70")) + 
  scale_fill_brewer(palette = "RdYlGn",name="Correlation", 
                    breaks = levels(cormat$value2), drop =FALSE)+
  geom_text(aes(label = value), size = 3)  + nopanel + 
  labs(x = "", y = "") +  
  guides(colour = FALSE, fill = guide_legend(reverse = TRUE, 
                                             override.aes = list(colour = NULL)))+
  scale_x_discrete(labels = function(x) str_wrap(x, width = 12)) +
  scale_y_discrete(labels = function(x) str_wrap(x, width = 12))
@

The political variables in Figure \ref{fig:politic1} are largely free of high 
correlations. The strongest relationships are between partisan division 
and the share of the two party vote -- an expected correlation. Higher fall turnout 
is also correlated with partisan division. 


<<policy1, fig.cap="Correlations of Policy Variables", fig.height=5.5, fig.width=7.5>>=

policyIdx2 <- policyIdx[c(1:3, 8:9, 13:15)]

cormat <- melt(round(cor(dist_turn[!is.na(dist_turn$turnout), 
              which(names(dist_turn) %in% policyIdx2)],  
              use = "pairwise"), 3)) 
cormat$Var1 <- varNamer(cormat$Var1)
cormat$Var2 <- varNamer(cormat$Var2)
cormat$value2 <- cut(cormat$value, 
                     breaks=c(-1,-0.75,-0.5,-0.25,0,0.25,0.5,0.75,1), 
                     include.lowest=TRUE, 
            label=c("(-0.75,-1)","(-0.5,-0.75)","(-0.25,-0.5)","(0,-0.25)",
                    "(0,0.25)","(0.25,0.5)","(0.5,0.75)","(0.75,1)")) 

qplot(x=Var1, y=Var2, data=cormat, fill=value2, geom="tile", color = I("gray70")) + 
  scale_fill_brewer(palette = "RdYlGn",name="Correlation", 
                    breaks = levels(cormat$value2), drop =FALSE)+
  geom_text(aes(label = value), size = 3)  + nopanel + 
  labs(x = "", y = "") +  
  guides(colour = FALSE, fill = guide_legend(reverse = TRUE, 
                                             override.aes = list(colour = NULL)))+
  scale_x_discrete(labels = function(x) str_wrap(x, width = 12)) +
  scale_y_discrete(labels = function(x) str_wrap(x, width = 12))
@

The story is the same for policy measures in Figure \ref{fig:policy1}. The only 
large correlations are between reading and math state standardized assessment 
proficiency rates, a measure of academic performance of the district. Superintendent 
turnover in year t-1 and year t is also highly correlated. Otherwise, there 
are no concerns about these measures. 

<<skiptables, eval=FALSE, echo=FALSE>>=
xtable(round(cor(dist_turn[dist_turn$year == 2011 & !is.na(dist_turn$turnout), 
              which(names(dist_turn) %in% politicIdx)]), 3))
@

\section{Methods}

For each of my measures of contestation, I fit four separate models 
looking at the impact of demographic, fiscal, political, and policy characteristics 
of school districts on the probability of a contested school board race. All models 
contain the demographic variables. I then fit a full model which includes variables 
from all of the models. This approach allows me to evaluate the relative power of 
these differing factors in explaining the competitiveness of board elections. 
To assess the probability of a contested election in a school district in a given 
election cycle, I start with a model of candidate emergence:

\[ (1) \hspace{0.25 in}  \Pr_{CE_{t}} = \alpha + \beta X + \epsilon \] \\

$\Pr_{CE_{t}}$ represents the probability that a school board seat is contested 
in an election in year \emph{t} as measured by one of the three flavors of contestation 
discussed above: non-incumbents running, contested seats, and finally incumbent defeat. 
The $X$ represent a vector of measures of conditions 
in the school district leading up to the time candidates choose to run for office, 
the period between the previous election and the current election. Estimating 
$\beta$ provides a way to test for the importance of each of the conditions in 
the school districts.\footnote{I use the logistic transformation for binomial 
outcomes, though for simplicity I do not represent the model this way here.}

The first way to estimate $\Pr_{CE_{t}}$ is by estimating a logistic regression. 
Logistic regression allows for the estimation of a binomial outcome using linear 
predictors. In this case, the linear predictors will be composed of the variables 
discussed above in Table \ref{tab:candIV}. I estimate the logistic regression using 
the maximum likelihood estimator available in the generalized linear model,  
\texttt{glm}, functions in R \citep{cran}. 

However, this logistic regression is not correctly specified as it ignores the 
dependence between observations inherent in the Wisconsin data. Each school district 
is observed between two and ten times, meaning that the assumption of independent 
and identically distributed random variables is violated. To correct for this, 
I employ sandwich estimators of the variance-covariance matrix to extract robust 
standard errors for these models, which will correct for the clustering of school districts
between the observations and avoid overly optimistic standard errors for 
the $\beta$ coefficients. I estimate the robust standard errors using 
the \texttt{lmtest} and \texttt{sandwich} packages for R 
\citep{sandwich, sandwich2, lmtest}. 

This approach still makes assumptions about the structure of the data that 
are unrealistic. Most importantly, this approach compares each school district year 
to all other school district years in the data set and ignores any explicit 
interdependence on prior years within the same district. This fails to take advantage 
of the repeated measures available for each school district due to the panel nature 
of the data set and reduces the importance of large changes in $X$ values within a 
district that are still relatively small when compared across all districts. 

There are a number of approaches available to estimating longitudinal and panel 
data. One way to adjust for this is to estimate fixed effects for school districts. 
While this approach is common in other studies of local government in political science, 
I prefer the alternative approach of multi-level modeling. The choice between these two 
approaches is as much theoretical as it is econometric, and as a result I run my analyses 
with both approaches.\footnote{The Hausman test can be used to formally 
test the specification of random or fixed effects and the results of this test for all 
models is included in the Methodological Appendix \ref{sec:appendix} \citep{haustest}.} 
However, I prefer the multi-level approach because the panel here is not balanced, 
the observations within districts are not evenly spaced due to the fact that districts 
may not have open seats on their board each year. Furthermore, my data does not 
include all Wisconsin school districts, but instead a large sample of districts. 
This makes the ability to model the variation between districts of interest to 
understand the range of plausible district variation across the broader population 
of school districts. 

The multilevel modeling approach, also known as hierarchical linear modeling (HLM), 
is flexible for cases with unbalanced repeated measures and allows the analyst to 
disentangle the effects of time specific variables from the overall variability 
among individual units, e.g. school districts \citep{mlmod,raudbryk}. One way to depict 
this approach is in the equation:

\begin{align*} 
\Pr_{CE_{ij}} &= \alpha_{i} + \beta X_{ij} + \gamma_{j} + \epsilon_{ij}   \\ 
\gamma_{j} &=  \alpha_{j} + \epsilon_{j}
\end{align*}

In this model I use \texttt{i} for the specific elections nested within the school 
districts, \texttt{j}. The $\gamma_{j}$ terms represent independent intercepts for each school 
districts, modeled as being drawn from a normal distribution. $X_{ij}$ is a vector of time 
variant school district characteristics, some of which may be lagged. 

This method does not account for the time structure of the data, as no 
explicit parameterization of time is included. As I have no reason to believe that 
time linearly relates to the probability of an election being contested, this is 
appropriate. However, I do want to control for secular effects of election year 
variability that reaches across districts. One approach would be to include 
fixed effects for years in the $X$ vector. However, the multilevel approach is 
flexible enough to allow for a third group -- years, to be included in the model. 
The model below includes a third grouping level for years. 

\begin{align*} 
\Pr_{CE_{ijt}} &= \alpha_{i} + \beta X_{ijt} + \gamma_{j} + \lambda_{t} + \epsilon_{ijt}   \\ 
\gamma_{j} &= \alpha_{j} + \epsilon_{j} \\ 
\lambda_{t} &= \alpha_{t} + \epsilon_{t} \\
\end{align*}

This approach allows year parameters to be estimated independently without assuming 
a functional form for the relationship between the probability of candidate emergence 
and time. This is beneficial as there does not appear to be a linear time trend 
in Figure \ref{fig:incdefeat} or Figure \ref{fig:candidatedescriptives4}. 
It also results in estimates the $\beta$ coefficients that are conditional 
on the group specific variances captured in the $\gamma$ and $\lambda$ vectors. 
This allows me to take advantage of the repeated measure structure of the data and 
avoid overconfidence in estimates resulting from comparisons within and across groups. 
The models are fit after grand-centering and rescaling all variables by their 
standard deviations in order to avoid convergence issues following the guidance of \citet{gelhill}.
\footnote{I modify the optimizer settings when necessary to ensure all models converge, estimating 
the models using the \texttt{lme4} package in R \citep{lme4, cran}.} For the mixed model 
approach, I also fit the four models -- demographic, fiscal, political, and policy. 

\subsection{Model Comparison}

Next, I need a way to compare the models to evaluate the variables that best explain 
the emergence of candidates. Model comparison is difficult, especially in the case 
of binomial regression where more traditional measures like $R^{2}$ are not available. 
Furthermore, model-based measures like psuedo-$R^{2}$, AIC, and BIC are sample dependent 
and not valid across varying dependent variables. Additionally, there is no intuitive way 
to empirically judge whether or not models are ``good enough'' in explaining the 
dependent variable. To address this, I adopt predictive measures of accuracy -- 
the ability of models to correctly predict observations as either a contested or 
uncontested election. 

Since my observations are unbalanced, with many more uncontested than contested 
elections, I need a measure of correct classification that is robust to class 
imbalance. This allows me to avoid spurious confidence in my models due to the fact 
that simply predicting most races as uncontested would yield a high percentage of 
correct classifications. For this, I use the receiver operator characteristic, or ROC,  
which provides a measure of the trade off between detection (true positive identification) 
and false alarm rates (false positive identification) across different values of 
the cutoff of the probability estimate from a model \citep{hanley, zwieg}. Of 
particular value is the area-under-the-curve which summarizes the accuracy of 
the model across all values of the probability cutoff. 

A disadvantage of this approach is that the area under the curve metric is relatively 
unfamiliar in the political science literature making it difficult to draw comparisons 
to similar studies in the field. However, a strong advantage of this approach is that 
it allows for valid comparisons within the current study that are easily understood 
on the sample at hand. I will demonstrate the rate at which each of the models 
accurately predicts the emergence of candidates for school board seats, which 
allows the reader to easily assess the relative value of the different models 
for this data. 

% Table \ref{tab:emergenceD} shows the theories and expected evidence in support of 
% them that can be explored using a descriptive analysis of the Wisconsin data. Here 
% we are evaluating what evidence there is that is suggestive of a relationship in 
% macro-level motivations among school board candidates common across the state of 
% Wisconsin. A lack of evidence tells us that we have the wrong measures. Finding 
% supportive measures suggests that further work with better measures should be 
% undertaken. 
%
% \begin{table}[h!]
% \begin{center}
% \begin{small}
% \caption{Theories of Candidate Emergence and Expected Evidence}
% \label{tab:emergenceD}
% \begin{tabular}{| p{.2\textwidth} | p{.25\textwidth} | p{.45\textwidth} |}
% \hline
% \textbf{Theory}  & \textbf{Citation} & \textbf{Expected Finding} \\ \hline
% Strategic Candidates  & \citet{Plutzer2002} & Change in partisanship precedes increase in candidates \\ \hline
% Policy Oriented Candidates & \citet{deckman1, CanonBook} & Changes in policy drive change \\ \hline
% %Fiscal Revolt & \citet{RefWorks:297,RefWorks:271} & Union membership as share of electorate drives up turnout \\ \hline
% Ambition & \citet{AJPS:AJPS147, Lasswell} & No data available to test \\ \hline
% Dissatisfaction & \citet{RefWorks:297,RefWorks:271} & Failed referenda leads to more candidates running \\ \hline
% \end{tabular}
% \end{small}
% \end{center}
% \end{table}

\section{Results}

I present results across four dependent variables for each of the four models. I begin by 
discussing the results for each dependent variable separately. In the text, I 
report the results for of the mixed-effect models and I leave the results of the 
fixed effect models for the appendix \ref{sec:appendix}. I prefer the mixed-effect 
models for reasons stated above, and because they represent a closer estimation 
of the impact of the variables of interest by eliminating the variance attributable 
to unobservable time-invariant characteristics of school districts. 

Next, I explore some substantive interpretations of the findings in the models. I do this by producing simulated observations and showing the prediction across the range 
of the variable of interest. This allows me to explore the marginal effect of 
changes in a predictor in the probability space of the predicted values of the 
model. This is more intuitive than discussing the coefficient values or 
interpreting effect sizes. 

Finally, I close by comparing the four groups of models to one another in an effort 
to understand which variables jointly explain the dependent variables best. In this 
section, I also compare the models to null models consisting merely of year and 
group factors. Thus, I explore how much additional classification power the school 
district annual attributes provide in explaining the likelihood candidates emerge 
or incumbents are defeated in a school board race. 

<<distTransform, results='hide'>>=
dist_turn$nonincumbRun <- ifelse(dist_turn$onlyIncum == 1, 0, 1)
dist_turn$partyDivisionRecent <- log(dist_turn$partyDivisionRecent)
@

<<cleanModData, results='hide'>>=
demogIdx <- c(demogIdx, "locale2")
dvs <- c("contestSer", "contestMinor", "contestMinorLag", 
         "contestSerLag", "incDefeats", "onlyIncum", "incumShare", "nonincumbRun", 
         "minBlaisLago", "turnout", "turnoutLag1", "turnoutLag2", "dissatFactor_fw", 
         "dissatFactor")
ids <- c("distid", "year", "districtwide")
moddat <- dist_turn[, c(dvs, ids, demogIdx, fiscalIdx, policyIdx, politicIdx)]

moddat$year <- factor(moddat$year)
moddat <- moddat[order(moddat$distid, moddat$year),]
moddat$distid <- factor(moddat$distid)
moddat$districtwide <- factor(moddat$districtwide)
moddat$contestSer <- factor(moddat$contestSer)
moddat$contestMinor <- factor(moddat$contestMinor)
moddat$contestMinorLag <- factor(moddat$contestMinorLag)
moddat$contestSerLag <- factor(moddat$contestSerLag)
moddat$onlyIncum <- factor(moddat$onlyIncum)
moddat$nonincumbRun <- factor(moddat$nonincumbRun)
moddat$locale2 <- factor(moddat$locale2)
moddat$incDefeats <- factor(moddat$incDefeats)
moddat$NEW_SUP <- factor(moddat$NEW_SUP)
moddat$SUP_TURNOVER_PRIOR_YEAR <- factor(moddat$SUP_TURNOVER_PRIOR_YEAR)
moddat$debtPass <- factor(moddat$debtPass)
moddat$overridePass <- factor(moddat$overridePass)
moddat$debtQues <- factor(moddat$debtQues)
moddat$overrideQues <- factor(moddat$overrideQues)
moddat$PerBachelorOrAbove <- moddat$PerBachelorOrAbove * 100
moddat$per_white_all <- moddat$per_white_all * 100
moddat$OOH_share <- moddat$OOH_share * 100
moddat$per65o <- moddat$per65o * 100
moddat$teachShareofVoters <- moddat$teachShareofVoters * 100

# Save scale parameters 
nums <- sapply(moddat, is.numeric)
ScaleMeans <- apply(moddat[, nums], 2, mean, na.rm=TRUE)
ScaleSD <- apply(moddat[, nums], 2, sd, na.rm=TRUE)
moddatScale <- cbind(ScaleMeans, ScaleSD); rm(ScaleMeans, ScaleSD)
#Rescale
library(arm)
nums <- sapply(moddat, is.numeric)
moddat[, nums] <- apply(moddat[, nums], 2, rescale)
@

\subsection{Dissatisfaction}

<<glmmodsDF, results='hide'>>=
moddat2 <- moddat[!is.na(moddat$dissatFactor_fw) & 
                    !is.na(moddat$dissatFactor), ]

demogsDF <- lm(dissatFactor_fw ~ VAP_adjLOG + per65o + PerBachelorOrAbove + per_white_all +
              OOH_share + locale2 + dissatFactor + year, 
              data = moddat2) #bach and 65o switch?

demogSE <- get_CL_vcov(demogsDF, moddat2$distid)
demogsDF$se <- sqrt(diag(demogSE))

politicDF <- update(demogsDF, . ~ . + overrideQues + overridePass + 
                      debtQues + debtPass +  partyDivisionRecent +
                    teachShareofVoters + fallTurnout + nraces) 

politicSE <- get_CL_vcov(politicDF, moddat2$distid)
politicDF$se <- sqrt(diag(politicSE))

fiscalDF <- update(demogsDF, . ~ . + schoolMillShare + PROPERTYTAX_REV_SHARE + 
                   TCEC_MEMBER + balance_member_lag + millrate_delta)

fiscalSE <- get_CL_vcov(fiscalDF, moddat2$distid)
fiscalDF$se <- sqrt(diag(fiscalSE))

policyDF <- update(demogsDF, . ~ . + ADMIN_SHARE_COMP + NEW_SUP + NonPublicPupilPer + 
                   DEBT_ATTEMPT_CUMUL93 + OVERRIDE_ATTEMPT_CUMUL93)

policySE <- get_CL_vcov(policyDF, moddat2$distid)
policyDF$se <- sqrt(diag(policySE))

fullmodDF <- update(politicDF, . ~ . +  schoolMillShare + PROPERTYTAX_REV_SHARE + 
                   TCEC_MEMBER + balance_member_lag + millrate_delta + 
                    ADMIN_SHARE_COMP + NEW_SUP + NonPublicPupilPer + 
                   DEBT_ATTEMPT_CUMUL93 + OVERRIDE_ATTEMPT_CUMUL93)
fullmodSE <- get_CL_vcov(fullmodDF, moddat2$distid)
fullmodDF$se <- sqrt(diag(fullmodSE))
rescalenote <- "All continuous variables mean centered and 
divided by 2 standard deviations"
stars.note <- apsrtable:::stars.note
coef.note <- "Year fixed effect coefficients excluded"

coefnames1 <- c("Intercept", "Electorate Size", "\\% Over 65", "\\% Bachelor +", 
               "\\% White", "\\% Owner Occupied",  "Exurb", "Rural", "Dissat. Lag", 
               "Rev. Lim. Attpt.", "Rev. Lim. Pass", "Bond Attpt.", "Bond Pass", 
               "\\% Polarized", "\\% Teach. Voters", "Fall Turnout", "Number Seats", 
               "\\% Tax for Schl.", "\\% Rev. Prop. Tax", "Cost per Pupil", 
               "Bal. per Pupil", "Millrate $\\Delta$", "\\% Salary Admin.", 
               "New Sup.", "\\% Private School", "Cumul. Bond Att.", 
               "Cumul. Ref Att.")

glmDFtab <- apsrtable(demogsDF, politicDF, fiscalDF, policyDF, fullmodDF, 
                     se = "robust", 
          float = "longtable",
          label="tab:glmModsDF", 
          omitcoef=list("year", 
                        expression(grep("year", coefnames, value = TRUE))), 
          model.names=c("Demog.", "Politic", 
                        "Fiscal",
                        "Policy", "Full"), 
          caption = "Models of Dissatisfaction Factor in School Board Elections",
          notes = list(stars.note, rescalenote, coef.note),
          Sweave=FALSE, digits = 3, coef.names = coefnames1, size="scriptsize", 
          stars = "default")
@

<<lmermodsDF, results='hide'>>=
demogsMMdf <- lmer(dissatFactor_fw ~ VAP_adjLOG + per65o + PerBachelorOrAbove + per_white_all +
              OOH_share + locale2 + dissatFactor + year + (1|distid), 
              data = moddat) 

politicMMdf <- update(demogsMMdf, . ~ . + overrideQues + overridePass + 
                      debtQues + debtPass +   partyDivisionRecent +
                    teachShareofVoters + fallTurnout + nwins) 

fiscalMMdf <- update(demogsMMdf, . ~ . + schoolMillShare + PROPERTYTAX_REV_SHARE + 
                   TCEC_MEMBER + balance_member_lag + millrate_delta)

policyMMdf <- update(demogsMMdf, . ~ . + ADMIN_SHARE_COMP + NEW_SUP + NonPublicPupilPer + 
                   DEBT_ATTEMPT_CUMUL93 + OVERRIDE_ATTEMPT_CUMUL93)

fullmodMMdf <- update(politicMMdf, . ~ . +  schoolMillShare + PROPERTYTAX_REV_SHARE + 
                   TCEC_MEMBER + balance_member_lag + millrate_delta + 
                    ADMIN_SHARE_COMP + NEW_SUP + NonPublicPupilPer + 
                   DEBT_ATTEMPT_CUMUL93 + OVERRIDE_ATTEMPT_CUMUL93)


lmerDFtab <- apsrtable(demogsMMdf, politicMMdf, fiscalMMdf, policyMMdf, fullmodMMdf,
          float = "longtable",
          label="tab:glmerModsDF", 
          omitcoef=list("year", 
                        expression(grep("year", coefnames, value = TRUE))), 
          model.names=c("Demog.", "Politic", 
                        "Fiscal",
                        "Policy", "Full"), 
          caption = "Mixed Models of Dissatisfaction Factor in School Board Elections",
          notes = list(stars.note, rescalenote),
          Sweave=FALSE, digits = 3, coef.names = coefnames1, size="scriptsize", 
          stars = "default")

@
\subsection{Presence of Non-incumbents}

<<glmmodsNI, results='hide'>>=
# moddat <- moddat[moddat$year != "2002" & moddat$year != "2003", ]
moddat2 <- moddat[!is.na(moddat$contestSerLag), ]

demogsNI <- glm(nonincumbRun ~ VAP_adjLOG + per65o + PerBachelorOrAbove + per_white_all +
              OOH_share + locale2 + contestSerLag + year, 
              data = moddat2, family = "binomial") #bach and 65o switch?

demogSE <- get_CL_vcov(demogsNI, moddat2$distid)
demogsNI$se <- sqrt(diag(demogSE))

politicNI <- update(demogsNI, . ~ . + overrideQues + overridePass + 
                      debtQues + debtPass +  partyDivisionRecent +
                    teachShareofVoters + fallTurnout + nraces) 
  # partyDivision and fallTwoPartyShareDem lose 2 years

politicSE <- get_CL_vcov(politicNI, moddat2$distid)
politicNI$se <- sqrt(diag(politicSE))

fiscalNI <- update(demogsNI, . ~ . + schoolMillShare + PROPERTYTAX_REV_SHARE + 
                   TCEC_MEMBER + balance_member_lag + millrate_delta)

fiscalSE <- get_CL_vcov(fiscalNI, moddat2$distid)
fiscalNI$se <- sqrt(diag(fiscalSE))

policyNI <- update(demogsNI, . ~ . + ADMIN_SHARE_COMP + NEW_SUP + NonPublicPupilPer + 
                   DEBT_ATTEMPT_CUMUL93 + OVERRIDE_ATTEMPT_CUMUL93)

policySE <- get_CL_vcov(policyNI, moddat2$distid)
policyNI$se <- sqrt(diag(policySE))

fullmodNI <- update(politicNI, . ~ . +  schoolMillShare + PROPERTYTAX_REV_SHARE + 
                   TCEC_MEMBER + balance_member_lag + millrate_delta + 
                    ADMIN_SHARE_COMP + NEW_SUP + NonPublicPupilPer + 
                   DEBT_ATTEMPT_CUMUL93 + OVERRIDE_ATTEMPT_CUMUL93)


fullmodSE <- get_CL_vcov(fullmodNI, moddat2$distid)
fullmodNI$se <- sqrt(diag(fullmodSE))
rescalenote <- "All continuous variables mean centered and 
divided by 2 standard deviations"
stars.note <- apsrtable:::stars.note
coef.note <- "Year fixed effect coefficients excluded"

coefnames1 <- c("Intercept", "Electorate Size", "\\% Over 65", "\\% Bachelor +", 
               "\\% White", "\\% Owner Occupied",  "Exurb", "Rural", "Contest. Lag", 
               "Rev. Lim. Attpt.", "Rev. Lim. Pass", "Bond Attpt.", "Bond Pass", 
               "\\% Polarized", "\\% Teach. Voters", "Fall Turnout", "Number Seats", 
               "\\% Tax for Schl.", "\\% Rev. Prop. Tax", "Cost per Pupil", 
               "Bal. per Pupil", "Millrate $\\Delta$", "\\% Salary Admin.", 
               "New Sup.", "\\% Priv. School", "Cumul. Bond Att.", 
               "Cumul. Ref Att.")

glmNItab <-apsrtable(demogsNI, politicNI, fiscalNI, policyNI, fullmodNI, se = "robust", 
          float = "longtable",
          label="tab:glmModsNI", 
          omitcoef=list("year", 
                        expression(grep("year", coefnames, value = TRUE))), 
          model.names=c("Demog.", "Politic", 
                        "Fiscal",
                        "Policy", "Full"), 
          caption = "Models of Incumbent Lockout in School Board Elections",
          notes = list(stars.note, rescalenote, coef.note),
          Sweave=FALSE, digits = 3, coef.names = coefnames1, size="scriptsize", 
          stars = "default")

@

<<glmermodsNI, results='asis'>>=
library(optimx)
ctrl2 <- glmerControl(optimizer = "optimx", calc.derivs = FALSE, 
                     optCtrl = list(method = "nlminb", starttests = FALSE, 
                                    kkt = FALSE, maxit = 4000))
ctrl <- glmerControl(optimizer = "Nelder_Mead", calc.derivs = FALSE)

demogsMMni <- glmer(nonincumbRun ~ VAP_adjLOG + per65o + PerBachelorOrAbove + per_white_all +
              OOH_share + locale2 + contestSerLag + year + (1|distid), 
              data = moddat, family = "binomial", control = ctrl) 

politicMMni <- update(demogsMMni, . ~ . + overrideQues + overridePass + 
                      debtQues + debtPass +   partyDivisionRecent +
                    teachShareofVoters + fallTurnout + nwins, control = ctrl2) 

fiscalMMni <- update(demogsMMni, . ~ . + schoolMillShare + PROPERTYTAX_REV_SHARE + 
                   TCEC_MEMBER + balance_member_lag + millrate_delta, control = ctrl)

policyMMni <- update(demogsMMni, . ~ . + ADMIN_SHARE_COMP + NEW_SUP + NonPublicPupilPer + 
                   DEBT_ATTEMPT_CUMUL93 + OVERRIDE_ATTEMPT_CUMUL93, control = ctrl)

fullmodMMni <- update(politicMMni, . ~ . +  schoolMillShare + PROPERTYTAX_REV_SHARE + 
                   TCEC_MEMBER + balance_member_lag + millrate_delta + 
                    ADMIN_SHARE_COMP + NEW_SUP + NonPublicPupilPer + 
                   DEBT_ATTEMPT_CUMUL93 + OVERRIDE_ATTEMPT_CUMUL93, 
                   control = ctrl2)

apsrtable(demogsMMni, politicMMni, fiscalMMni, policyMMni, fullmodMMni,
          float = "longtable",
          label="tab:glmerModsNI", 
          omitcoef=list("year", 
                        expression(grep("year", coefnames, value = TRUE))), 
          model.names=c("Demog.", "Politic", 
                        "Fiscal",
                        "Policy", "Full"), 
          caption = "Mixed Models of Incumbent Lockout in School Board Elections",
          notes = list(stars.note, rescalenote),
          Sweave=FALSE, digits = 3, coef.names = coefnames1, size="scriptsize", 
          stars = "default")
@

The models in Table \ref{tab:glmerModsNI} are disappointing overall. Not only are 
most variables not statistically significant, many of them are not of the correct 
sign.\footnote{The demographic variables fair poorly, although they are generally in the 
correct direction.} The most consistent result is that the measure of the size 
of the community, voting age population, is positively related to a greater probability 
of non-incumbents participating in a race. The other variables that seek to control 
for the pool of candidates, however, are not statistically significant and some run 
counter to evidence from surveys showing board members are more highly educated, 
older, and less likely to be minorities. Thus, we would expect a greater share 
of these groups in the community to be positively related to more non-incumbents. 

More disappointingly, the substantive variables provide relatively few detectable 
effects. The only variables that are statistically significant are the presence 
of a referenda attempt to exceed the revenue limit, a control for the number of 
seats open in the race, and the dollars per pupil in the district's savings account. 
These variables are all in the correct sign with a referenda attempt increasing 
the likelihood that non-incumbents will participate in the race, more seats open 
leading to more non-incumbents, and a larger fund balance being associated with 
decreased challenger participation in the election.\footnote{Observations are 
dropped from these models if they have no lagged observation of the dependent 
variable.}

In all the models, quite a bit of variation is explained by variability between 
districts as captured by the district effects. The district intercepts vary about 
as much as moving one standard deviation in the voting age population, suggesting 
that much of the variation in determining if any non-incumbents are running is up 
to district factors that are not measured here. 

\subsection{Non-Incumbents and More Candidates than Seats}

Table \ref{tab:glmerModsCon} shows the results for estimates of whether voters 
face a ballot with more challengers than seats and at least one non-incumbent 
on the ballot. This presents a better measure of what voters might think of as 
contestation because it is measuring the presence of an actual choice on the ballot 
for voters. These models are better supported by the variables I selected to 
test than the models predicting non-incumbents running - a positive sign. 
\footnote{These models do not consider races where a candidate with few votes is 
included in the ballot. However, the results here are robust to coding all districts 
with even a nominal challenge as contested races.}

First, larger districts correctly are associated with more contestation, 
confirming the predictions about the importance of size posited by \citet{oliver12}. 
Another demographic variable shows that the greater the population over 65 in a community,  
the more likely voters will have a choice for school board election. This matches 
with the expectation that this represents a greater pool of potential candidates. 
The percentage of adults with a bachelor degree is inconsistently negative, suggesting 
that communities with greater levels of education in their population are less 
likely to experience school board choice. This is counter to our expectation but 
may reflect that these communities have greater consensus about the value and nature 
of locally provided education. 

Unsurprisingly, the measure for the number of incumbents is strongly 
negatively related to the the likelihood the race will be contested, suggesting 
that like incumbents in other elections, incumbents in school board races may 
also deter challengers. However, some policy decisions of school boards do 
appear to significantly affect the presence of new candidates for board - notably 
the decision to offer and the passage of an override referendum, the millrate 
for the district, and the community's history of recent bond referenda attempts. 
Attempting an override referendum in the prior year increases the likelihood of a 
challenge, but if an override referendum is successful, then this effect is negated. 
This suggests that the decision to offer an override referendum is politically perilous 
for school board members -- if they misjudge the community and the referendum fails, 
they increase their chance for a contested election. 

Even more support for fiscally minded voters emerges with a positive relationship 
between districts with higher tax rates. Board races are more contentious when taxation 
rates rise. 


<<glmmodsContest, results='hide'>>=
# moddat <- moddat[moddat$year != "2002" & moddat$year != "2003", ]

moddat2 <- moddat[moddat$incumShare != max(moddat$incumShare) & 
                    !is.na(moddat$contestSerLag), ]

demogsCon <- glm(contestSer ~ VAP_adjLOG + per65o + PerBachelorOrAbove + 
                   per_white_all +
              OOH_share + locale2 + contestSerLag +  year, 
              data = moddat2, 
              family = "binomial") #bach and 65o switch?

demogSE <- get_CL_vcov(demogsCon, moddat2$distid)
demogsCon$se <- sqrt(diag(demogSE))

politicCon <- update(demogsCon, . ~ . + incumShare + overrideQues + overridePass + 
                      debtQues + debtPass + partyDivisionRecent +
                    teachShareofVoters + fallTurnout + nwins) 
  # partyDivision and fallTwoPartyShareDem lose 2 years

politicSE <- get_CL_vcov(politicCon, moddat2$distid)
politicCon$se <- sqrt(diag(politicSE))

fiscalCon <- update(demogsCon, . ~ . + schoolMillShare + PROPERTYTAX_REV_SHARE + 
                   TCEC_MEMBER + balance_member_lag + millrate_delta)

fiscalSE <- get_CL_vcov(fiscalCon, moddat2$distid)
fiscalCon$se <- sqrt(diag(fiscalSE))

policyCon <- update(demogsCon, . ~ . + ADMIN_SHARE_COMP + NEW_SUP + NonPublicPupilPer + 
                   DEBT_ATTEMPT_CUMUL93 + OVERRIDE_ATTEMPT_CUMUL93)

policySE <- get_CL_vcov(policyCon, moddat2$distid)
policyCon$se <- sqrt(diag(policySE))

fullmodCon <- update(politicCon, . ~ . +  schoolMillShare + PROPERTYTAX_REV_SHARE + 
                   TCEC_MEMBER + balance_member_lag + millrate_delta + 
                    ADMIN_SHARE_COMP + NEW_SUP + NonPublicPupilPer + 
                   DEBT_ATTEMPT_CUMUL93 + OVERRIDE_ATTEMPT_CUMUL93)


fullmodSE <- get_CL_vcov(fullmodCon, moddat2$distid)
fullmodCon$se <- sqrt(diag(fullmodSE))
rescalenote <- "All continuous variables rescaled to center 0 
                and divided by 2 standard deviations."
stars.note <- apsrtable:::stars.note


coefnames2 <- c("Intercept", "Electorate Size", "\\% Over 65", "\\% Bachelor +", 
               "\\% White", "\\% Owner Occupied", "Exurb", "Rural", "Lag. Contest.", 
               "\\% Incumbents", 
               "Override Attpt.", "Override Pass", "Debt Ques.", "Debt Pass", 
               "\\% Polarized", "\\% Teach. Voters", "Fall Turnout", "Number Seats", 
               "\\% Tax for Schl.", "\\% Revenue Prop. Tax", "Cost per Pupil", 
               "Balance per Pupil", "Millrate $\\Delta$", "\\% Salary - Admin.", 
               "New Sup.", "\\% Priv. School", "Cumul. Bond Att.", 
               "Cumul. Override Att.")

glmContab <- apsrtable(demogsCon, politicCon, fiscalCon, policyCon, fullmodCon, se = "robust", 
          float = "longtable",
          label="tab:glmModsCon", 
          omitcoef=list("year", 
                        expression(grep("year", coefnames, value = TRUE))), 
          model.names=c("Demog.", "Politic", 
                        "Fiscal",
                        "Policy", "Full"), 
          caption = "Models of Contestation in School Board Elections",
          notes = list(stars.note, rescalenote),
          Sweave=FALSE, digits = 3, coef.names = coefnames2, 
          size="scriptsize", stars = "default")

@



<<glmermods, results='asis'>>=
library(optimx)
ctrl2 <- glmerControl(optimizer = "optimx", calc.derivs = FALSE, 
                     optCtrl = list(method = "nlminb", starttests = FALSE, 
                                    kkt = FALSE, maxit = 4000))
ctrl <- glmerControl(optimizer = "Nelder_Mead", calc.derivs = FALSE)

demogsMMCon <- glmer(contestSer ~ VAP_adjLOG + per65o + PerBachelorOrAbove + 
                       per_white_all +
              OOH_share + locale2 + contestSerLag + year + (1|distid), 
              data = moddat2, family = "binomial", control = ctrl) #bach and 65o switch?

politicMMCon <- update(demogsMMCon, . ~ . + incumShare + overrideQues + overridePass + 
                      debtQues + debtPass + partyDivisionRecent +
                    teachShareofVoters + fallTurnout + nraces, control = ctrl2) 

fiscalMMCon <- update(demogsMMCon, . ~ . + schoolMillShare + PROPERTYTAX_REV_SHARE + 
                   TCEC_MEMBER + balance_member_lag + millrate_delta, control = ctrl2)

policyMMCon <- update(demogsMMCon, . ~ . + ADMIN_SHARE_COMP + NEW_SUP + NonPublicPupilPer + 
                   DEBT_ATTEMPT_CUMUL93 + OVERRIDE_ATTEMPT_CUMUL93, control = ctrl2)

fullmodMMCon <- update(politicMMCon, . ~ . +  schoolMillShare + PROPERTYTAX_REV_SHARE + 
                   TCEC_MEMBER + balance_member_lag + millrate_delta + 
                    ADMIN_SHARE_COMP + NEW_SUP + NonPublicPupilPer + 
                   DEBT_ATTEMPT_CUMUL93 + OVERRIDE_ATTEMPT_CUMUL93, 
                   control = ctrl2)

apsrtable(demogsMMCon, politicMMCon, fiscalMMCon, policyMMCon, fullmodMMCon,
          float = "longtable",
          label="tab:glmerModsCon", 
           omitcoef=list("year", 
                        expression(grep("year", coefnames, value = TRUE))), 
          model.names=c("Demog.", "Politic", 
                        "Fiscal",
                        "Policy", "Full"), 
          caption = "Mixed Models of Contestation in School Board Elections",
          notes = list(stars.note, rescalenote),
          Sweave=FALSE, digits = 3, coef.names = coefnames2, 
          size="scriptsize", stars = "default")
@

\subsection{Competitiveness}

A continuous measure of competitiveness is preferable to a binary cutoff because 
it allows us to measure the feature of interest -- the intensity of the divide 
among candidates. Here, I find more evidence of fiscally motivated voters as 
before. While the demographic results are largely the same, so too are the 
results surrounding fiscal variables. It is encouraging to see that the structural 
variables are in the correct direction as well -- more incumbents result in less competitive 
elections and more seats result in less competitive elections as well. 
School districts with relatively more scope, that is, districts which capture a 
larger share of the property tax millrate in their community have more competitive 
elections. Within districts this suggests that as the millrate increases, the 
competitiveness increases -- though the change in millrate variable itself is not 
statistically significant.

The more often the district has attempted to override revenue limits is, 
counter intuitively, less associated with competitive elections. This perhaps 
represents a community that has reached consensus about supporting public schools 
and as such, has less electoral competition. Districts with 
higher per pupil expenditures are also marked by less competitive elections. Without 
measures of board member preferences there are at least two equally plausible 
explanations for this result. First, these communities may have higher costs because 
of a policy consensus around more public support for education and thus higher 
per pupil expenditures. That is, elections are not competitive because there is 
already a community consensus that is reflected in current board policy. Thus, 
candidates do not run or challenges are not spirited because all candidates 
broadly support the same policy. Alternatively, it may be that these communities 
are less competitive because no challengers ever emerge in the first place. 


<<blqGLMs, eval=TRUE, results='hide'>>=
# Select only elections with more candidates than seats
# moddat4 <- moddat[moddat$contestMinor == 1, ]

moddat4 <- moddat[!is.na(moddat$contestSerLag),]
demogsBLQ <- lm(minBlaisLago ~ VAP_adjLOG + per65o + PerBachelorOrAbove + per_white_all +
              OOH_share + locale2 + contestSerLag + year,
              data = moddat4)

demogSE <- get_CL_vcov(demogsBLQ, moddat4$distid)
demogsBLQ$se <- sqrt(diag(demogSE))

politicBLQ <- update(demogsBLQ, . ~ . + incumShare + overrideYesPer +  partyDivisionRecent +
                    teachShareofVoters + fallTurnout + nraces) 

politicSE <- get_CL_vcov(politicBLQ, moddat4$distid)
politicBLQ$se <- sqrt(diag(politicSE))


fiscalBLQ <- update(demogsBLQ, . ~ . + schoolMillShare + PROPERTYTAX_REV_SHARE + 
                   TCEC_MEMBER + balance_member_lag + millrate_delta)

fiscalSE <- get_CL_vcov(fiscalBLQ, moddat4$distid)
fiscalBLQ$se <- sqrt(diag(fiscalSE))

policyBLQ <- update(demogsBLQ, . ~ . + ADMIN_SHARE_COMP + NEW_SUP + NonPublicPupilPer + 
                   DEBT_ATTEMPT_CUMUL93 + OVERRIDE_ATTEMPT_CUMUL93)

policySE <- get_CL_vcov(policyBLQ, moddat4$distid)
policyBLQ$se <- sqrt(diag(policySE))

fullmodBLQ <- update(politicBLQ, . ~ . +  schoolMillShare + PROPERTYTAX_REV_SHARE + 
                   TCEC_MEMBER + balance_member_lag + millrate_delta + 
                    ADMIN_SHARE_COMP + NEW_SUP + NonPublicPupilPer + 
                   DEBT_ATTEMPT_CUMUL93 + OVERRIDE_ATTEMPT_CUMUL93)
fullmodSE <- get_CL_vcov(fullmodBLQ, moddat4$distid)
fullmodBLQ$se <- sqrt(diag(fullmodSE))

rescalenote <- "All continuous variables rescaled to center 0 
                and divided by 2 standard deviations."
stars.note <- apsrtable:::stars.note


coefnames4 <- c("Intercept", "Electorate Size", "\\% Over 65", "\\% Bachelor +", 
               "\\% White", "\\% Owner Occupied", "Exurb", "Rural",
               "Contest. Lag", "\\% Incumbents", "\\% Yes Rev. Limit", 
               "\\% Polarized", "\\% Teach. Voters", "Fall Turnout", "Number Seats", 
               "\\% Tax for Schl.", "\\% Revenue Prop. Tax", "Cost per Pupil", 
               "Balance per Pupil", "Millrate $\\Delta$", "\\% Salary - Admin.", 
               "New Sup.", "\\% Priv. School", "Cumul. Bond Att.", 
               "Cumul. Override Att.")

glmBLQtab <- apsrtable(demogsBLQ, politicBLQ, fiscalBLQ, policyBLQ, fullmodBLQ, se = "robust", 
          float = "longtable",
          label="tab:glmModsBLQ", 
          omitcoef=list("year", 
                        expression(grep("year", coefnames, value = TRUE))), 
          model.names=c("Demog.", "Politic", 
                        "Fiscal",
                        "Policy", "Full"), 
          caption = "Linear Models of Blais-Lago Quotient of Competitiveness in School Board Elections",
          notes = list(stars.note, rescalenote),
          Sweave=FALSE, digits = 3, coef.names = coefnames4, 
          size="scriptsize", stars = "default")

@


<<blqMMmods, eval=TRUE, results='asis'>>=
demogsMMblq <- lmer(minBlaisLago ~ VAP_adjLOG + per65o + PerBachelorOrAbove + 
                      per_white_all + OOH_share + locale2 + contestSerLag + 
                      year + (1|distid), data = moddat4) 

politicMMblq <- update(demogsMMblq, . ~ . + incumShare +  overrideYesPer +  
                       partyDivisionRecent +
                    teachShareofVoters + fallTurnout + nraces) 
  
fiscalMMblq <- update(demogsMMblq, . ~ . + schoolMillShare + PROPERTYTAX_REV_SHARE + 
                   TCEC_MEMBER + balance_member_lag + millrate_delta)

policyMMblq <- update(demogsMMblq, . ~ . + ADMIN_SHARE_COMP + NEW_SUP + NonPublicPupilPer + 
                   DEBT_ATTEMPT_CUMUL93 + OVERRIDE_ATTEMPT_CUMUL93)

fullmodMMblq <- update(politicMMblq, . ~ . +  schoolMillShare + PROPERTYTAX_REV_SHARE + 
                   TCEC_MEMBER + balance_member_lag + millrate_delta + 
                    ADMIN_SHARE_COMP + NEW_SUP + NonPublicPupilPer + 
                   DEBT_ATTEMPT_CUMUL93 + OVERRIDE_ATTEMPT_CUMUL93)

apsrtable(demogsMMblq, politicMMblq, fiscalMMblq, policyMMblq, fullmodMMblq,
          float = "longtable",
          label="tab:glmerModsBLQ", 
           omitcoef=list("year", 
                        expression(grep("year", coefnames, value = TRUE))), 
          model.names=c("Demog.", "Politic", 
                        "Fiscal",
                        "Policy", "Full"), 
          caption = "Linear Mixed Models of Blais-Lago Quotient of Competitiveness in School Board Elections",
          notes = list(stars.note, rescalenote),
          Sweave=FALSE, digits = 3, coef.names = coefnames4, 
          size="scriptsize", stars = "default")

@
% TODO: Robustness of above models with a reduced sample

\subsection{Incumbent Defeat}

Table \ref{tab:glmerModsID} shows the results for incumbent defeat. These results 
are less promising than those in Table \ref{tab:glmerModsCon} for candidates emerging. 
Again, population size is strongly positively related with more incumbent defeats. 
However, other demographic variables do not seem to be predictive of incumbents 
being defeated. In fact, incumbent defeat proves very difficult to predict. Outside of the 
percentage of incumbents on the ballot -- a control to account for the varying 
opportunity for incumbent defeat election to election. 

% VAP = correct, larger = more defeats, but peters out in fuller models
% No other demographics matter
% %incumbents increases likelihood incumbent is defeated
% Revenue limit passed increasing chance of defeat
% Nothing else matters, damn this is hard to predict

%TODO: Check signs are correct

<<incdefeatGLM, eval=TRUE, results='hide'>>=
moddat3 <- moddat[moddat$incumShare != max(moddat$incumShare) &
                              moddat$incumShare != min(moddat$incumShare) & 
                    !is.na(moddat$contestSerLag),]

demogsD <- glm(incDefeats ~ VAP_adjLOG + per65o + PerBachelorOrAbove + 
                 per_white_all +
              OOH_share + locale2 + contestSerLag + year, 
              data = moddat3, 
              family = "binomial") #bach and 65o switch?


demogSE <- get_CL_vcov(demogsD, moddat3$distid)
demogsD$se <- sqrt(diag(demogSE))

politicD <- update(demogsD, . ~ . + incumShare + overrideYesPer +  partyDivisionRecent +
                    teachShareofVoters + fallTurnout + nraces) 

politicSE <- get_CL_vcov(politicD, moddat3$distid)
politicD$se <- sqrt(diag(politicSE))


fiscalD <- update(demogsD, . ~ . + schoolMillShare + PROPERTYTAX_REV_SHARE + 
                   TCEC_MEMBER + balance_member_lag + millrate_delta)

fiscalSE <- get_CL_vcov(fiscalD, moddat3$distid)
fiscalD$se <- sqrt(diag(fiscalSE))


policyD <- update(demogsD, . ~ . + ADMIN_SHARE_COMP + NEW_SUP + NonPublicPupilPer + 
                   DEBT_ATTEMPT_CUMUL93 + OVERRIDE_ATTEMPT_CUMUL93)


policySE <- get_CL_vcov(policyD, moddat3$distid)
policyD$se <- sqrt(diag(policySE))

fullmodD <- update(politicD, . ~ . +  schoolMillShare + PROPERTYTAX_REV_SHARE + 
                   TCEC_MEMBER + balance_member_lag + millrate_delta + 
                    ADMIN_SHARE_COMP + NEW_SUP + NonPublicPupilPer + 
                   DEBT_ATTEMPT_CUMUL93 + OVERRIDE_ATTEMPT_CUMUL93)

fullmodSE <- get_CL_vcov(fullmodD, moddat3$distid)
fullmodD$se <- sqrt(diag(fullmodSE))

rescalenote <- "All continuous variables rescaled to center 0 
                and divided by 2 standard deviations."
stars.note <- apsrtable:::stars.note


coefnames3 <- c("Intercept", "Electorate Size", "\\% Over 65", "\\% Bachelor +", 
               "\\% White", "\\% Owner Occupied", "Exurb", "Rural", "Contest. Lag", 
               "\\% Incumbents", "\\% Yes Rev. Limit", 
               "\\% Polarized", "\\% Teach. Voters", "Fall Turnout", "Number Seats", 
               "\\% Tax for Schl.", "\\% Revenue Prop. Tax", "Cost per Pupil", 
               "Balance per Pupil", "Millrate $\\Delta$", "\\% Salary - Admin.", 
               "New Sup.", "\\% Private School", "Cumul. Bond Att.", 
               "Cumul. Override Att.")

glmDtab <- apsrtable(demogsD, politicD, fiscalD, policyD, fullmodD, se = "robust", 
          float = "longtable",
          label="tab:glmModsD", 
          omitcoef=list("year", 
                        expression(grep("year", coefnames, value = TRUE))), 
          model.names=c("Demog.", "Politic", 
                        "Fiscal",
                        "Policy", "Full"), 
          caption = "Logit Models of Incumbent Defeat in School Board Elections",
          notes = list(stars.note, rescalenote),
          Sweave=FALSE, digits = 3, coef.names = coefnames3, 
          size="scriptsize", stars = "default")

@

<<incdefeatMods, eval=TRUE, results='asis'>>=
moddat3 <- moddat[moddat$incumShare != max(moddat$incumShare) &
                              moddat$incumShare != min(moddat$incumShare),]

demogsMMd <- glmer(incDefeats ~ VAP_adjLOG + per65o + PerBachelorOrAbove + per_white_all +
              OOH_share + locale2 + year + (1|distid), 
              data = moddat3, 
              family = "binomial", control = ctrl) #bach and 65o switch?

politicMMd <- update(demogsMMd, . ~ . + incumShare + overrideYesPer +  
                       partyDivisionRecent +
                    teachShareofVoters + fallTurnout + nraces, control = ctrl) 
  # partyDivision and fallTwoPartyShareDem lose 2 years

fiscalMMd <- update(demogsMMd, . ~ . + schoolMillShare + PROPERTYTAX_REV_SHARE + 
                   TCEC_MEMBER + balance_member_lag + millrate_delta, control = ctrl)

policyMMd <- update(demogsMMd, . ~ . + ADMIN_SHARE_COMP + NEW_SUP + NonPublicPupilPer + 
                   DEBT_ATTEMPT_CUMUL93 + OVERRIDE_ATTEMPT_CUMUL93, control = ctrl)

fullmodMMd <- update(politicMMd, . ~ . +  schoolMillShare + PROPERTYTAX_REV_SHARE + 
                   TCEC_MEMBER + balance_member_lag + millrate_delta + 
                    ADMIN_SHARE_COMP + NEW_SUP + NonPublicPupilPer + 
                   DEBT_ATTEMPT_CUMUL93 + OVERRIDE_ATTEMPT_CUMUL93, 
                   control = ctrl2)

coefnames3 <- c("Intercept", "Electorate Size", "\\% Over 65", "\\% Bachelor +", 
               "\\% White", "\\% Owner Occupied", "Exurb", "Rural", 
               "\\% Incumbents", "\\% Yes Rev. Limit", 
               "\\% Polarized", "\\% Teach. Voters", "Fall Turnout", "Number Seats", 
               "\\% Tax for Schl.", "\\% Revenue Prop. Tax", "Cost per Pupil", 
               "Balance per Pupil", "Millrate $\\Delta$", "\\% Salary - Admin.", 
               "New Sup.", "\\% Private School", "Cumul. Bond Att.", 
               "Cumul. Override Att.")

apsrtable(demogsMMd, politicMMd, fiscalMMd, policyMMd, fullmodMMd,
          float = "longtable",
          label="tab:glmerModsID", 
           omitcoef=list("year", 
                        expression(grep("year", coefnames, value = TRUE))), 
          model.names=c("Demog.", "Politic", 
                        "Fiscal",
                        "Policy", "Full"), 
          caption = "Mixed Models of Incumbent Defeat in School Board Elections",
          notes = list(stars.note, rescalenote),
          Sweave=FALSE, digits = 3, coef.names = coefnames3, 
          size="scriptsize", stars="default")

@

\clearpage

\subsection{Substantive Effects}

The results of the above models are disappointing. The data do not provide much 
evidence of many of the theoretical expectations despite an ample sample size. 
Figure \ref{fig:fixefplot1} depicts a summary of the coefficients across all 
models from the tables above along with the confidence intervals. Very few 
effects are statistically significant across the models, and the magnitudes of 
these effects all appear quite small.\footnote{The confidence intervals are not 
those reported by the estimate, but are constructed from simulations of the posterior 
for the mixed level models and represents the median estimate plus or minus 
two standard deviations of the simulated values of the parameter across 1,000 
simulations. These are standardized coefficients.}

This section seeks to explore the effects that do matter from Figure 
\ref{fig:fixefplot1} to 
illustrate the magnitude of the effects that have been identified and explore 
the findings of the models. Given the high number of observations available in 
this data set, there is likely sufficient power to detect effects that are 
substantively quite small yet remain statistically significant. In order to 
better understand this, I use simulations to illustrate the substantive impact of 
several of the key variables identified in the models above on school board 
contestation and illustrate them here.  

\subsubsection{Main Effects}

The tables above provide the coefficients and standard errors for the models, but 
logistic regression coefficients can be difficult to interpret -- especially on 
data that has been rescaled. In order to better demonstrate the impact of key 
variables, I provide simulations from the models above that show the impact on the 
probability of contestation conditional on changes in those variables. 

<<fixefplot1, eval=TRUE, fig.cap="Coefficient Plot of Coefficients for Full Models",fig.height=9.5, fig.width=8, results='hide'>>=
set.seed(51315)
sim1 <- FEsim(fullmodMMCon, nsims = 1000); sim1$dv <- "Contest"
sim2 <- FEsim(fullmodMMni, nsims = 1000); sim2$dv <- "No Incumb."
sim3 <- FEsim(fullmodMMd, nsims = 1000); sim3$dv <- "Defeat"
sim4 <- FEsim(fullmodMMblq, nsims = 1000); sim4$dv <- "Competitiveness"

simPlot <- do.call(rbind, list(sim1, sim2, sim3, sim4))
simPlot$dv <- factor(simPlot$dv, levels = c("No Incumb.", "Contest", 
                                            "Defeat", "Competitiveness"))
alpha <- 1.96
simPlot$upr <- simPlot$meanEff + (alpha*simPlot$sdEff)
simPlot$lwr <- simPlot$meanEff - (alpha*simPlot$sdEff)

simPlot$color <- "Not Sig."
simPlot$color <- ifelse(simPlot$lwr >0 | simPlot$upr < 0, "Sig", "Not Sig.")
simPlot <- simPlot[!simPlot$variable %in% grep("year", simPlot$variable, value=TRUE),]

ggplot(simPlot, aes(x = variable, y = meanEff, ymax = upr, 
                    ymin = lwr, color = color)) + 
  scale_color_brewer(type = "qual", palette = 6) + 
  geom_point() + geom_errorbar(h=1.5) +
  geom_hline(yintercept = 0, size = I(1.1), color = I("black"), linetype = 2, 
             alpha = I(0.6)) +
  coord_flip() + 
  facet_wrap(~dv) + 
  theme_dpi(base_size=10) +theme(legend.position = "bottom") + 
  labs(x = "Variable", y = "Effect", color = "Stat. Sig.")
@

In Figure \ref{fig:fixefSub1} I provide a series of simulation results for three 
variables. Each numbered panel represents a simulated case. Each column of panels 
represents a combination of a predictor and a dependent variable, in this case from left 
to right, the probability of a contested seat by millrate share, the probability of a 
contested seat by electorate size, and the Blais-Lago quotient by cost. Each plot 
contains two dotted lines which represent the $25^{th}$ 
and $75^{th}$ percentiles of the value of the dependent variable as fit by the 
model. These lines are reference frames for examining the third solid line which 
represents the simulated value of the dependent variable for each observation as the 
independent variable changes across its full range. The movement of this line 
in relation to the dotted lines helps depict how much variability can be explained 
by increasing or decreasing the variable on the x-axis. Finally, uncertainty about 
the predicted value at each value of the x-axis is represented by the gray shadow 
around the solid line. The x-axis also contains a ``rug-plot'' for reference, which 
shows the density of observed values of the x-variable. 

Taken together, each panel shows the behavior of variables in the models on 
specific observations and allows us to answer the question -- how would contestation 
change if the x-variable increased or decreased? 

<<fixefSub1, fig.cap="Simulated Effect of Key Variables on Contestation Levels Across Models">>=
seplotdf <- substEffSimFE(fullmodMMCon, "schoolMillShare", ncases = 4L, 
                          unscale = moddatScale, re = TRUE)

p1 <- ggplot(seplotdf, aes(x = newvarUnscale, y = yhat)) +
  geom_line(aes(group = caseID)) + 
    geom_ribbon(aes(ymin=lwr, ymax=upr, group = caseID),
                     alpha=0.4) + 
  facet_wrap(~caseID) + 
  geom_hline(yintercept = quantile(fitted(fullmodMMCon), prob = 0.25), linetype = 2) + 
  geom_hline(yintercept = quantile(fitted(fullmodMMCon), prob = 0.75), linetype = 2) + 
  geom_rug(data = dist_turn, aes(x = schoolMillShare, y = NULL)) + 
  theme_dpi(base_size=12) + 
  labs(x = "School Millrate Share", y = "Pr(Contested)", title = "Cont. Model")

seplotdf <- substEffSimFE(fullmodMMCon, "VAP_adjLOG", ncases = 4L, 
                          unscale = moddatScale, re = TRUE)

p2 <- ggplot(seplotdf, aes(x = newvarUnscale, y = yhat)) +
  geom_line(aes(group = caseID)) + 
    geom_ribbon(aes(ymin=lwr, ymax=upr, group = caseID),
                     alpha=0.4) + 
  facet_wrap(~caseID) + 
  geom_hline(yintercept = quantile(fitted(fullmodMMCon), prob = 0.25), linetype = 2) + 
  geom_hline(yintercept = quantile(fitted(fullmodMMCon), prob = 0.75), linetype = 2) + 
  geom_rug(data = dist_turn, aes(x = VAP_adjLOG, y = NULL)) + 
  theme_dpi(base_size=12) + 
  labs(x = "log(VAP)", y = "Pr(Contested)", title = "Cont. Model")

seplotdf <- substEffSimFE(fullmodMMblq, "TCEC_MEMBER", ncases = 4L, 
                          unscale = moddatScale, re = TRUE)

seplotdf$yhatUnscale <- (seplotdf[, "yhat"] * 2 * moddatScale["minBlaisLago", 2]) + 
  moddatScale["minBlaisLago", 1] # assumes first slot in mod frame is DV
seplotdf$lwrUnscale <- (seplotdf[, "lwr"] * 2 * moddatScale["minBlaisLago", 2]) + 
  moddatScale["minBlaisLago", 1] # assumes first slot in mod frame is DV
seplotdf$uprUnscale <- (seplotdf[, "upr"] * 2 * moddatScale["minBlaisLago", 2]) + 
  moddatScale["minBlaisLago", 1] # assumes first slot in mod frame is DV
seplotdf <- seplotdf[seplotdf$uprUnscale < 100,]
lowerBar <- (quantile(fitted(fullmodMMblq), prob = 0.25) * 2 * moddatScale["minBlaisLago", 2]) + 
      moddatScale["minBlaisLago", 1]
upperBar <- (quantile(fitted(fullmodMMblq), prob = 0.75) * 2 * moddatScale["minBlaisLago", 2]) + 
      moddatScale["minBlaisLago", 1]

p3 <- ggplot(seplotdf, aes(x = newvarUnscale, y = yhatUnscale)) +
  geom_line(aes(group = caseID)) + 
    geom_ribbon(aes(ymin=lwrUnscale, ymax=ifelse(uprUnscale > 100, 
                                                      100, uprUnscale), 
                    group = caseID), alpha=0.4) + 
  facet_wrap(~caseID) + 
  geom_rug(data = dist_turn, aes(x = TCEC_MEMBER, y = NULL)) + 
  geom_hline(yintercept = lowerBar, linetype = 2) + 
  geom_hline(yintercept = upperBar, linetype = 2) + 
  theme_dpi(base_size=12) + 
  labs(x = "TCEC_MEMBER", y = "Blais-Lago", title = "BLQ Model") 
  # scale_y_log10(limits=c(1, 100), breaks = c(1, 25, 50, 75, 100))

grid.arrange(p1, p2, p3, nrow = 1)
@

\clearpage

\subsubsection{District Variation}

By far the most variation is explained by effects across districts. These effects 
represent the sum of unobserved characteristics that do not vary within districts 
over time. In this section, I employ a similar graphical technique as in the 
previous section to depict the magnitude of the impact that year and district 
effects have in the models for the outcome variables.

Figure \ref{fig:randomEffectplot31} simulates the variance in the predicted 
probabilities of each outcome across school districts. As in Figure 
\ref{fig:fixefSub1}, each panel represents a single case. Within that panel, the 
predicted probability for that case is estimated if that case had been observed 
in each district, ordered by the impact each district has on the outcome. Thus, 
the line in each panel be interpreted as, all else constant, how much would the 
outcome change if the same observation was modified by each district intercept 
estimate. The horizontal dashed lines in each panel represent the 
interquartile-range (IQR) of the fitted values from the models to give a sense 
of the variability in the predicted probabilities across cases. In other words, 
each panel shows the magnitude of moving from the district that has the least 
impact on the outcome to the district that has the most. While this is not a 
realistic counter factual in the sense that it is not possible to hold all else 
constant while moving across districts, it does help graphically depict the 
amount of variability that exists across districts that is captured by the 
district-level intercepts estimated in each of the models.

The first set of plots on the left represent the variability in incumbent defeat 
probabilities that are explained by school districts. Given how little each case 
changes across districts (the slope of the line formed by these probabilities), 
it appears that there is very little substantive variation between districts. The 
next two panels, contestation and incumbent lockout, have much steeper slopes, suggesting 
that the variability between the highest and lowest district effect is equivalent 
to more than the the distance between the first and third quartiles in predicted 
probabilities. The final panel shows the impact on the Blais-Lago quotient which 
appears to be in some cases equivalent to a substantial portion of the interquartile 
range of the predicted probabilities. 

In general, it seems that between-district variation is much larger than the 
substantive impact of independent variables. While some of the variables in 
Figure \ref{fig:fixefSub1} had substantial variation, the estimates were noisier 
in these cases.  A similar graphic is included in the Appendix depicting the 
estimates of the year effects. 

<<randomEffectplot31, eval=TRUE, fig.cap="Substantive Impact of District Intercepts">>=
set.seed(51315)

replotdf <- substEffSimRE(fullmodMMni, "distid", ncases=6, alpha = 0.1)
replotdf$distid <- as.character(replotdf$distid)
NIre <- ggplot(data = replotdf, aes(x = reorder(distid, -yhat), y = yhat, 
                            ymin = lwr, ymax = upr)) + 
  geom_line(aes(group = caseID)) + 
    geom_ribbon(aes(group = caseID), alpha=0.4) + 
  theme_dpi(base_size=12) + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), 
                      strip.text = element_blank(), 
                      strip.background = element_blank(), 
                      panel.grid.minor = element_blank(), 
                      panel.grid.major = element_blank()) + 
  geom_hline(yintercept = quantile(fitted(fullmodMMni), prob = 0.25), linetype = 2) + 
  geom_hline(yintercept = quantile(fitted(fullmodMMni), prob = 0.75), linetype = 2) + 
  facet_wrap(~caseID) + 
  labs(x = "District", y = "Pr(No Incumbent)", title = "Inc. Lockout")

replotdf <- substEffSimRE(fullmodMMCon, "distid", ncases=6, alpha = 0.1)
replotdf$distid <- as.character(replotdf$distid)
NIcon <- ggplot(data = replotdf, aes(x = reorder(distid, -yhat), y = yhat, 
                            ymin = lwr, ymax = upr)) + 
  geom_line(aes(group = caseID)) + 
    geom_ribbon(aes(group = caseID), alpha=0.4) + 
  theme_dpi(base_size=12) + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), 
                      strip.text = element_blank(), 
                      strip.background = element_blank(), 
                      panel.grid.minor = element_blank(), 
                      panel.grid.major = element_blank()) + 
  geom_hline(yintercept = quantile(fitted(fullmodMMCon), prob = 0.25), linetype = 2) + 
  geom_hline(yintercept = quantile(fitted(fullmodMMCon), prob = 0.75), linetype = 2) + 
  facet_wrap(~caseID) + 
  labs(x = "District", y = "Pr(Contested)", title = "Contest")


replotdf <- substEffSimRE(fullmodMMd, "distid", ncases=6, alpha = 0.1)
replotdf$distid <- as.character(replotdf$distid)
NIdef <- ggplot(data = replotdf, aes(x = reorder(distid, -yhat), y = yhat, 
                            ymin = lwr, ymax = upr)) + 
  geom_line(aes(group = caseID)) + 
    geom_ribbon(aes(group = caseID), alpha=0.4) + 
  theme_dpi(base_size=12) + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), 
                      strip.text = element_blank(), 
                      strip.background = element_blank(), 
                      panel.grid.minor = element_blank(), 
                      panel.grid.major = element_blank()) + 
  geom_hline(yintercept = quantile(fitted(fullmodMMd), prob = 0.25), linetype = 2) + 
  geom_hline(yintercept = quantile(fitted(fullmodMMd), prob = 0.75), linetype = 2) + 
  facet_wrap(~caseID) + 
  labs(x = "District", y = "Pr(Incumb. Def.)", title = "Defeat")

replotdf <- substEffSimRE(fullmodMMblq, "distid", ncases=6, alpha = 0.1)
replotdf$yhatUnscale <- replotdf[, "yhat"] * 2 * moddatScale["minBlaisLago", 2] + 
  moddatScale["minBlaisLago", 1] # assumes first slot in mod frame is DV
replotdf$lwrUnscale <- replotdf[, "lwr"] * 2 * moddatScale["minBlaisLago", 2] + 
  moddatScale["minBlaisLago", 1] # assumes first slot in mod frame is DV
replotdf$uprUnscale <- replotdf[, "upr"] * 2 * moddatScale["minBlaisLago", 2] + 
  moddatScale["minBlaisLago", 1] # assumes first slot in mod frame is DV
replotdf <- replotdf[replotdf$uprUnscale < 100,]
lowerBar <- quantile(fitted(fullmodMMblq), prob = 0.25) * 2 * moddatScale["minBlaisLago", 2] + 
      moddatScale["minBlaisLago", 1]
upperBar <- quantile(fitted(fullmodMMblq), prob = 0.75) * 2 * moddatScale["minBlaisLago", 2]+ 
      moddatScale["minBlaisLago", 1]

replotdf$newvar <- as.character(replotdf$newvar)

NIblq <- ggplot(replotdf, aes(x = reorder(newvar, -yhatUnscale), y = yhatUnscale)) +
  geom_line(aes(group = caseID)) + 
    geom_ribbon(aes(ymin=lwrUnscale, ymax=uprUnscale, group = caseID),
                     alpha=0.4) + 
  geom_hline(yintercept = lowerBar, linetype = 2) + 
  geom_hline(yintercept = upperBar, linetype = 2) + 
  facet_wrap(~caseID) +
  theme_dpi(base_size=12) + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), 
                      strip.text = element_blank(), 
                      strip.background = element_blank(), 
                      panel.grid.minor = element_blank(), 
                      panel.grid.major = element_blank()) +
  labs(x = "District", y = "Blais-Lago", title = "BLQ")


grid.arrange(NIdef, NIcon, NIre, NIblq, nrow = 1)
@

\clearpage

\subsection{Comparisons}

After exploring these effects, the question stands -- which set of variables best 
explain the pattern of contested elections and candidate emergence in Wisconsin. 
Testing for the impact of individual variables is difficult because of the likelihood 
of colinearity leading to overly pessimistic estimates of the impact of variables 
on the outcome. Measures of goodness of fit provide a sense of the variation in 
the data explained by the whole model, but are poor choices for cross-model comparison 
and are on a scale that is hard to interpret. In the case of the main variables 
of interest here -- binomial measures of contestation -- it is easier to report 
the rate of correct classification for predictions from the model compared to 
observed data. I graphically depict the results of these classification based 
model fit metrics now.


<<generateROC, eval=TRUE>>=
set.seed(51315)
library(ROCR)

rocNInull <- makeROCdf(update(demogsMMni, . ~ + 1 + (1|distid) + year), "null")
rocNI1 <- makeROCdf(demogsMMni, "Demog.")
rocNI2 <- makeROCdf(fiscalMMni, "Fiscal")
rocNI3 <- makeROCdf(policyMMni, "Policy")
rocNI4 <- makeROCdf(politicMMni, "Political")
rocNI5 <- makeROCdf(fullmodMMni, "Full")

rocNI <- do.call(rbind, list(rocNInull, rocNI1, rocNI2, rocNI3, rocNI4, rocNI5))
rm(rocNInull, rocNI1, rocNI2, rocNI3, rocNI4, rocNI5)
rocNI$dv <- "No Incumbents"

rocConnull <- makeROCdf(update(demogsMMCon, . ~ + 1 + (1|distid) + year), "null")
rocCon1 <- makeROCdf(demogsMMCon, "Demog.")
rocCon2 <- makeROCdf(fiscalMMCon, "Fiscal")
rocCon3 <- makeROCdf(policyMMCon, "Policy")
rocCon4 <- makeROCdf(politicMMCon, "Political")
rocCon5 <- makeROCdf(fullmodMMCon, "Full")

rocCon <- do.call(rbind, list(rocConnull, rocCon1, rocCon2, rocCon3, rocCon4, rocCon5))
rm(rocConnull, rocCon1, rocCon2, rocCon3, rocCon4, rocCon5)
rocCon$dv <- "Contested Race"

rocDnull <- makeROCdf(update(demogsMMd, . ~ + 1 + (1|distid) + year), "null")
rocD1 <- makeROCdf(demogsMMd, "Demog.")
rocD2 <- makeROCdf(fiscalMMd, "Fiscal")
rocD3 <- makeROCdf(policyMMd, "Policy")
rocD4 <- makeROCdf(politicMMd, "Political")
rocD5 <- makeROCdf(fullmodMMd, "Full")

rocD <- do.call(rbind, list(rocDnull, rocD1, rocD2, rocD3, rocD4, rocD5))
rm(rocDnull, rocD1, rocD2, rocD3, rocD4, rocD5)
rocD$dv <- "Incumbent Defeat"
@

<<rocplot1, echo=FALSE, fig.cap="ROC Curves for Models of Election Contestation in Wisconsin School Boards by Model Type. The diagonal line represents a model equal to random chance, the top left corner represents the best prediction performance.", fig.keep='last', fig.width=6.75, fig.height=5, fig.scap="ROC Curves for Models of Election Contestation in Wisconsin School Boards by Model Type.">>=

roc <- do.call(rbind, list(rocNI, rocCon, rocD))
rm(rocNI, rocCon, rocD)
roc$modType <- paste(roc$mod, roc$dv, sep ="-")

# ggplot(roc, aes(x = fpr, y = tpr, group = modType,color = mod)) + 
#   geom_smooth(size= I(1.1), se = FALSE) +
#    geom_abline(intercept = 0, slope = 1, colour = "gray") + 
#    ylab("Sensitivity") + 
#    xlab("1 - Specificity") + 
#   coord_cartesian(xlim=c(0, 1), ylim=c(0,1)) + theme_bw() + 
#   labs(title = "Comparing Models of Candidate Contestation \n 
#        in School Board Elections", 
#        color = "Model") + theme(legend.position = c(0.8, 0.15)) + 
#   facet_wrap(~dv, nrow=3)


ggplot(roc[roc$mod != "null",], aes(x = fpr, y = tpr, group = modType, color = dv)) + 
  geom_line(size= I(1.1), se = FALSE, stat = "smooth") +
   geom_abline(intercept = 0, slope = 1, colour = "gray") + 
  scale_color_brewer(type = "qual", palette = 6) +
   ylab("Sensitivity") + 
   xlab("1 - Specificity") + 
  coord_cartesian(xlim=c(0, 1), ylim=c(0,1)) + theme_bw() + 
  labs(title = "Comparing Models of Candidate Contestation \n 
       in School Board Elections across Dependent Variables", 
       color = "Model") + theme(legend.position = c(0.8, 0.15)) + 
    facet_wrap(~mod, nrow=2) +
  geom_line(data = roc[roc$mod == "null", c(1, 2, 6)], 
              aes(x = fpr, y = tpr, group = modType, color = NULL), 
               alpha = I(0.6), size = I(1.1), color = I('gray20'), 
            se = FALSE, linetype = 2, stat = "smooth") 

@

<<rocplot2, echo=FALSE, fig.scap="ROC Curves for Models of Election Contestation in Wisconsin School Boards by DV", fig.keep='last', fig.width=6.75, fig.height=5,fig.cap="ROC Curves for Models of Election Contestation in Wisconsin School Boards by DV. The diagonal line represents a model equal to random chance, the top left corner represents the best prediction performance.">>=

ggplot(roc[roc$mod != "null",], aes(x = fpr, y = tpr, group = modType, color = mod)) + 
  geom_line(size= I(1.1), se = FALSE, stat = "smooth") +
   geom_abline(intercept = 0, slope = 1, colour = "gray") + 
  scale_color_brewer(type = "qual", palette = 6) +
   ylab("Sensitivity") + 
   xlab("1 - Specificity") + 
  coord_cartesian(xlim=c(0, 1), ylim=c(0,1)) + theme_bw() + 
  labs(title = "Comparing Models of Candidate Contestation \n 
       in School Board Elections within Dependent Variables", 
       color = "Model") + theme(legend.position = c(0.7, 0.25)) + 
    facet_wrap(~dv, nrow=2) +
  geom_line(data = roc[roc$mod == "null", c(1, 2, 5, 6)], 
              aes(x = fpr, y = tpr, group = modType, color = NULL), 
               alpha = I(0.6), size = I(1.1), color = I('gray20'), 
            se = FALSE, linetype = 2, stat = "smooth") 
@


In Figure \ref{fig:rocplot1} each model is represented in an individual panel. 
The x-axis represents the false-alarm rate, or uncontested elections that would be 
classified as contested elections. The y-axis represents the true contested elections
that would be correctly classified. The closer the line is to the top left, the closer 
the model is to achieving perfect prediction. The dashed diagonal line represents random 
chance and is included for reference in each panel. The ROC curves along these dimensions for the 
predictions produced by each model are represented by individual 
curves for each dependent variable. A null model consisting of year fixed 
effects and random intercepts for each school district is represented in each panel 
by the dashed gray curves. A clear pattern emerges. 
First, incumbent defeat is much more difficult to predict than either the presence 
of all incumbents, or a serious challenger -- these two curves are substantially 
higher than the green curve representing incumbent defeat in all panels. Second, 
each of the models appears to do equally well at classifying districts for each 
of the dependent variables -- the pattern is the same panel to panel. This is likely 
due to a final observation, which is that the null model is nearly identical to 
the models which include predictors. 

This is further explored in Figure \ref{fig:rocplot2} where the same ROC curves 
are reorganized into each of the three dependent variables, with each model being 
represented by a colored line and the null model again in gray. This makes it 
clear that a simple random intercept model with fixed year effects has the same 
explanatory power as the other models that include election level predictors. This 
suggests that the bulk of the variation in school board contestation 
is the result of individual district patterns and year to year fluctuations in 
political participation. These results also serve as a caution about overinterpreting the 
coefficients above -- while some of them may be statistically significant, they 
provide very little additional predictive power beyond the unobservable district 
and year effects modeled by the hierarchical parameters in the model. 

\clearpage
\section{Discussion}

The study shows that the decision to contest school board 
elections, and thus for new candidates to emerge, is not well explained by 
observable attributes of the school districts themselves. Across an array of attributes 
such as the demographic makeup of the district, the fiscal health of the district, 
the local politics of school district finances, and the policy decisions of the 
school boards themselves -- very little of the variation in school board 
contestation was explained. The biggest factor in school board election contestation 
from the data in Wisconsin was the unobserved variance between districts themselves 
as demonstrated by the simulations plotted in Figure \ref{fig:randomEffectplot31}. 

This finding is important for three reasons. First, by eliminating a number of 
possible between-district explanations, these findings provide evidence that the 
determinants of running for school board are localized and idiosyncratic as opposed 
to based on responses to policy, fiscal, or political pressures. The fact that 
unobservable school district effects explain the biggest share of the variance in 
candidate emergence and competitiveness, and that other factors explain very little 
provides strong evidence for this. This fits with 
other studies of local non-partisan elections -- particularly those held off-cycle -- 
where an engaged subset of the general election electorate votes based on 
primarily local issues \citep{oliver12}. This suggests that future study of school 
board elections needs to take a deeper look at the issues at play in individual 
districts by studying the preferences of likely voters and the positions of 
potential candidates, a la the suburban voter studies of \citet{oliver12}. 

Second, the Wisconsin evidence suggests that the competitiveness of board elections 
across this period in the state has not changed. There is no detectable uptick or 
decrease in competition across any of the measures of competition. This is a theme 
I will return to in Chapter \ref{chap:walker}, but it is clear from the evidence 
here that whatever the implications are for the level of competitiveness shown 
in school board elections in Wisconsin, it is stable. 

Third, board elections appear to operate on a non-partisan issue domain. Predictors 
of the partisanship of the community or the partisan division of the community 
in recent elections had no detectable effect on the contestation of school board 
elections. Education is an issue that confounds ideology for both parties, but 
the lack of evidence of partisanship mattering for board contestation has important 
consequences for future studies. 

Taken together, when returning to the question that guides this chapter -- why 
run for school board -- the answer appears to be idiosyncratic to the conditions 
within the school district as a community. While it is certainly true that the 
size of the population is importantly related to higher levels of contestation 
across almost all measures, there are few other relevant factors that seem 
predictive of the frequency of challenges for school board seats. School board 
candidates do not seem to emerge in response at all to the measures of policy pressure 
collected for this study such as shifts in compensation, changes in the district 
superintendent, or the academic performance of the school district. However, 
candidates do seem to be responsive to fiscal factors. Consistently, some 
measure of fiscal policy is predictive across the models, whether it is the share 
of the millrate devoted to the school district, the passage of an override or debt 
referenda, or the cumulative effect of school district referenda since the imposition 
of revenue limits. Despite these variables being statistically significant, they 
explained relatively little of the variation in candidate contestation and proved 
to be poor predictors of contestation. 

So, why run for school board? In the majority of school boards across Wisconsin 
the answer appears to be in response to some local issue or because of the nature 
of the community itself. Potential board members may be activated by fiscal conditions, 
if at all, but predominantly appear to respond to unobservable conditions in the 
community in which they serve. Chapter \ref{chap:walker} will seek to more formally 
test the causality of candidate activation. 

Normatively, arguments can be constructed for or against these findings being healthy 
for democracy. Critics of special jurisdictions such as school boards are 
quick to point out their ease of capture by special interests due to the very low 
levels of interest exhibited by voters and candidates in serving these organizations 
\citep{RefWorks:207,berry2}. It is undoubtedly true that low-levels of participation are 
observed here, but my, admittedly weaker, tests of teacher-union capture found 
no observable effects on board policy. More work remains to be done to understand 
the motivations of candidates and school board voters, but this study suggests that 
such work needs to go beyond administrative collections of school district attributes 
and delve into specific features of the individual candidates and voters in the 
districts they serve. 

In defense of the findings here, school board elections -- when contested -- appear to 
be more competitive than legislative counterparts \citep{blaislago}. Attempting to 
explain this competition led to few observable results, which suggests further study 
is needed to understand what issues or policy concerns lead to competitive elections. 
Without a deeper understanding than can be given by the statewide measures used 
in this study, it is clear that any community divisions that may drive board competition 
will continue to go undetected. 

For adherents of dissatisfaction theory, this study 
has eliminated some easily observable antecedents of voter dissatisfaction, but has 
certainly not eliminated the likely possibility that voter dissatisfaction with 
boards is more closely related to specific policy decisions. In fact, consistent 
evidence was found that the highest profile board decisions, offering a 
referenda for school funding, was related to competition for board seats. This 
suggests that other high profile decisions not captured here, such as a change in the 
curriculum or the modification of graduation requirements, may also be more than 
sufficient to activate voters and be part of the large variation between districts 
observed in the models above. Without political party gatekeepers or consistently 
polarized issues, a potential candidate may find the barriers to seeking office 
remarkably low in Wisconsin -- representing great democratic potential. From the 
community side though, it is clear that the smaller size of school board electorates 
greatly reduces the pool of likely candidates with time, resources, and interests. 
This suggests a need to consider how to expand the demographic pools from which 
school board members are drawn to convert democratic potential into actualized 
democracy. 

The next chapters will explore the motivations of voters to help further understand 
this puzzle. Then I will turn my attention to using exogenous variation to test 
the causal impact of changes to the balance of power between school boards and 
employees in collective bargaining on voter and candidate activity 
in board elections. Finally, I will turn my attention toward investigating if 
board turnover leads to any detectable changes in school district policies in an 
effort to answer the question -- if an incumbent loses in a school board election 
that is marked by low turnout, does anything happen?

\section{Technical Appendix}
\label{sec:appendix}

All analyses were done using R \citep{cran}. Source code and data available online. 

\subsection{Pooled GLM Model Results}

Not printed.

<<printGLMni, results='asis'>>=
glmNItab
@

<<printGLMcon, results='asis'>>=
glmContab
@

<<printGLMblq, results='asis',eval=TRUE>>=
glmBLQtab
@

<<printGLMd, results='asis',eval=TRUE>>=
glmDtab
@

\subsection{Dissatisfaction Factor Model}

<<printGLMdf, results='asis',eval=TRUE>>=
glmDFtab
@

<<printlmerDFtab, results='asis', eval=TRUE>>=
lmerDFtab
@

\subsection{Year Effects Across Models}

Across year effects. There is no consistent pattern between years and the year 
to year variation is a fraction of the IQR of the fitted values for all models - 
represented by the horizontal lines in each panel.

<<fixefSubYear, fig.cap="Substantive Effect on Contestation for Years">>=
seplotdf <- substEffSimFE(fullmodMMni, "year", ncases = 4L, re = TRUE, alpha = 0.1)

p1 <- ggplot(seplotdf, aes(x = year, y = yhat)) +
  geom_line(aes(group = caseID)) + 
    geom_ribbon(aes(ymin=lwr, ymax=upr, group = caseID),
                     alpha=0.4) + 
  geom_hline(yintercept = quantile(fitted(fullmodMMni), prob = 0.25)) + 
  geom_hline(yintercept = quantile(fitted(fullmodMMni), prob = 0.75)) + 
  facet_wrap(~caseID, nrow=1) +
  theme_dpi(base_size=12) + 
  theme(strip.text = element_blank(), strip.background = element_blank()) +  
  labs(x = "Year", y = "Pr(Non-Incumbent)", title= "Year Effect Across Observations")


seplotdf <- substEffSimFE(fullmodMMCon, "year", ncases = 4L, re = TRUE, alpha = 0.1)

p2 <- ggplot(seplotdf, aes(x = year, y = yhat)) +
  geom_line(aes(group = caseID)) + 
    geom_ribbon(aes(ymin=lwr, ymax=upr, group = caseID),
                     alpha=0.4) + 
  geom_hline(yintercept = quantile(fitted(fullmodMMCon), prob = 0.25)) + 
  geom_hline(yintercept = quantile(fitted(fullmodMMCon), prob = 0.75)) + 
  facet_wrap(~caseID, nrow=1) +
  theme_dpi(base_size=12) + 
  theme(strip.text = element_blank(), strip.background = element_blank()) +  
  labs(x = "Year", y = "Pr(Contested)", title= "Year Effect Across Observations")


seplotdf <- substEffSimFE(fullmodMMd, "year", ncases = 4L, re = TRUE, alpha = 0.1)

p3 <- ggplot(seplotdf, aes(x = year, y = yhat)) +
  geom_line(aes(group = caseID)) + 
    geom_ribbon(aes(ymin=lwr, ymax=upr, group = caseID),
                     alpha=0.4) + 
  geom_hline(yintercept = quantile(fitted(fullmodMMd), prob = 0.25)) + 
  geom_hline(yintercept = quantile(fitted(fullmodMMd), prob = 0.75)) + 
  facet_wrap(~caseID, nrow=1) +
  theme_dpi(base_size=12) + 
  theme(strip.text = element_blank(), strip.background = element_blank()) +  
  labs(x = "Year", y = "Pr(Inc. Defeat)", title= "Year Effect Across Observations")

seplotdf <- substEffSimFE(fullmodMMblq, "year", ncases = 4L, re = TRUE, alpha = 0.1)
seplotdf$yhatUnscale <- (seplotdf[, "yhat"] * 2 * moddatScale["minBlaisLago", 2]) + 
  moddatScale["minBlaisLago", 1] # assumes first slot in mod frame is DV
seplotdf$lwrUnscale <- (seplotdf[, "lwr"] * 2 * moddatScale["minBlaisLago", 2]) + 
  moddatScale["minBlaisLago", 1] # assumes first slot in mod frame is DV
seplotdf$uprUnscale <- (seplotdf[, "upr"] * 2 * moddatScale["minBlaisLago", 2]) + 
  moddatScale["minBlaisLago", 1] # assumes first slot in mod frame is DV

lowerBar <- exp((quantile(fitted(fullmodMMblq), prob = 0.25) * 2 * moddatScale["minBlaisLago", 2]) + 
      moddatScale["minBlaisLago", 1])
upperBar <- exp((quantile(fitted(fullmodMMblq), prob = 0.75) * 2 * moddatScale["minBlaisLago", 2]) + 
      moddatScale["minBlaisLago", 1])

p4 <- ggplot(seplotdf, aes(x = year, y = exp(yhatUnscale))) +
  geom_line(aes(group = caseID)) + 
    geom_ribbon(aes(ymin=exp(lwrUnscale), ymax=exp(uprUnscale), group = caseID),
                     alpha=0.4) + 
  geom_hline(yintercept = lowerBar) + 
  geom_hline(yintercept = upperBar) + 
  facet_wrap(~caseID, nrow=1) +
  theme_dpi(base_size=12) + 
  theme(strip.text = element_blank(), strip.background = element_blank()) +  
  labs(x = "Year", y = "Blais-Lago", title= "Year Effect Across Observations")

grid.arrange(p1, p2, p3, p4, ncol = 1)
@


\subsection{Model Specification Tests}

<<hausmantest, eval=TRUE, results='asis', cache=TRUE>>=
phDemog1 <- phtest_glmer(demogsMMd, update(demogsD, . ~. + distid))
phDemog2 <- phtest_glmer(demogsMMni, update(demogsNI, . ~. + distid))
phDemog3 <- phtest_glmer(demogsMMCon, update(demogsCon, . ~. + distid))

phPolicy1 <- phtest_glmer(policyMMd, update(policyD, . ~. + distid))
phPolicy2 <- phtest_glmer(policyMMni, update(policyNI, . ~. + distid))
phPolicy3 <- phtest_glmer(policyMMCon, update(policyCon, . ~. + distid))

phPolitic1 <- phtest_glmer(politicMMd, update(politicD, . ~. + distid))
phPolitic2 <- phtest_glmer(politicMMni, update(politicNI, . ~. + distid))
phPolitic3 <- phtest_glmer(politicMMCon, update(politicCon, . ~. + distid))


phFiscal1 <- phtest_glmer(fiscalMMd, update(fiscalD, . ~. + distid))
phFiscal2 <- phtest_glmer(fiscalMMni, update(fiscalNI, . ~. + distid))
phFiscal3 <- phtest_glmer(fiscalMMCon, update(fiscalCon, . ~. + distid))

phFull1 <- phtest_glmer(fullmodMMd, update(fullmodD, . ~. + distid ))
phFull2 <- phtest_glmer(fullmodMMni, update(fullmodNI, . ~. + distid ))
phFull3 <- phtest_glmer(fullmodMMCon, update(fullmodCon, . ~. + distid))

results_grid <- expand.grid(spec = c("Demog", "Fiscal", "Policy", "Politic", "Full"), 
                            var = c("Non-Incumbent", "Contestation", "Defeat"))

pval.ph <- function(x) x$p.value
ts.ph <- function(x) x$statistic
df.ph <- function(x) x$parameter

mods <- list(phDemog2, phFiscal2, phPolicy2, phPolitic2, phFull2, 
             phDemog3, phFiscal3, phPolicy3, phPolitic3, phFull3, 
             phDemog1, phFiscal1, phPolicy1, phPolitic1, phFull1)

results_grid$pval <- lapply(mods, pval.ph)
results_grid$test.stat <- lapply(mods, ts.ph)
results_grid$degfree <- lapply(mods, df.ph)
names(results_grid) <- c("Model", "Dependent Variable", "Hausman P Value", 
                         "Chi-Square", "Degrees of Freedom")

print(xtable(results_grid, digits = c(0,0, 0, 3, 3, 1),
      caption = "Hausman Specification Test Results for All Models"))

@

<<modTestRuns, results='hide', eval=FALSE, cache=TRUE>>=
library(pbkrtest)
library(doParallel)
cl <- makePSOCKcluster(detectCores())

modTestDemog1 <- PBmodcomp(demogsMM, demogsMM2, nsim = 200, 
          cl = cl)

modTestDemog2 <- PBmodcomp(demogsMM, demogsMM3, nsim = 200, 
          cl = cl)

stopCluster(cl)

cl <- makePSOCKcluster(detectCores())

fiscalMM2 <- update(fiscalMM, .~. - (1|distid) - (1|year) + (1|year/distid))
fiscalMM3 <- update(fiscalMM, . ~ . - (1|year))

modTestFiscal1 <- PBmodcomp(fiscalMM, fiscalMM2, nsim = 200, 
          cl = cl)

modTestFiscal2 <- PBmodcomp(fiscalMM, fiscalMM3, nsim = 200, 
          cl = cl)


stopCluster(cl)

cl <- makePSOCKcluster(detectCores())


politicMM2 <- update(politicMM, .~. - (1|distid) - (1|year) + (1|year/distid))
politicMM3 <- update(politicMM, . ~ . - (1|year))

modTestPolitic1 <- PBmodcomp(politicMM, politicMM2, nsim = 200, 
          cl = cl)

modTestPolitic2 <- PBmodcomp(politicMM, politicMM3, nsim = 200, 
          cl = cl)


stopCluster(cl)

cl <- makePSOCKcluster(detectCores())


policyMM2 <- update(policyMM, .~. - (1|distid) - (1|year) + (1|year/distid))
policyMM3 <- update(policyMM, . ~ . - (1|year))

modTestPolicy1 <- PBmodcomp(policyMM, policyMM2, nsim = 200, 
          cl = cl)

modTestPolicy2 <- PBmodcomp(policyMM, policyMM3, nsim = 200, 
          cl = cl)


stopCluster(cl)

# cl <- makePSOCKcluster(2)
# 
# 
# politicMM2 <- update(politicMM, .~. - (1|distid) - (1|year) + (1|year/distid))
# politicMM3 <- update(politicMM, . ~ . - (1|year))
# 
# modTestPolitic1 <- PBmodcomp(politicMM, politicMM2, nsim = 200, 
#           cl = cl)
# 
# modTestPolitic2 <- PBmodcomp(politicMM2, politicMM3, nsim = 200, 
#           cl = cl)
# 
# 
# stopCluster(cl)
@

<<pbtestresults, results='asis', eval=FALSE, cache=TRUE>>=
#print parametric bootstrap

nams1 <- c("district and year effects", "districts nested in years")
nams2 <-  c("district and year effects", "district effects alone")

printPB(modTestDemog1, names = nams1, label = "demographic models")
printPB(modTestDemog2, names = nams2, label = "demographic models")

printPB(modTestFiscal1, names = nams1, label = "fiscal models")
printPB(modTestFiscal2, names = nams2, label = "fiscal models")

printPB(modTestPolitic1, names = nams1, label = "political models")
printPB(modTestPolitic2, names = nams2, label = "political models")

printPB(modTestPolicy1, names = nams1, label = "policy models")
printPB(modTestPolicy2, names = nams2, label = "policy models")

@

<<pbresults, results='markup', eval=FALSE, cache=TRUE>>=
modTestDemog1
modTestDemog2
modTestFiscal1
modTestFiscal2
modTestPolitic1
modTestPolitic2
modTestPolicy1
modTestPolicy2
@


