\chapter{Why Run for School Board?}
\label{chap:candidacy}
\chapterstyle{deposit}


<<rsetup, results='hide', echo=FALSE, message=FALSE, warning=FALSE>>=

opts_chunk$set(fig.width=8, fig.height=6, message=FALSE, error=FALSE, 
               fig.path="../../phd_figs/chap3-",
               warning=FALSE, echo=FALSE, dev='pdf')

setwd("../../")
source("data/dataAssemble.R")
source("data/cleanandprep_CANDIDACY.R")

SAMPSIZE <- length(unique(SBELEC$distid))
# load data
# print descriptives

library(xtable)
options(xtable.include.rownames = FALSE, xtable.table.placement = "ht")
@



\section{Introduction}

By all accounts being a school board member is a difficult and thankless job. 
School board meetings frequently occur in the evening to allow parents and 
community members to participate, and very few school board members are 
compensated for their work \citep{RefWorks:333, RefWorks:321}. Contrary to popular conceptions, 
the role of the school board as a stepping stone to further office is by all 
accounts overstated \citep{RefWorks:321, RefWorks:322}. In fact, the dissatisfaction
incumbents have with the position has been a confounding factor in the literature; in 
comparison to state wide or nationwide offices, non-political turnover due to retirement 
from the seat is much more common among school board members \citep{RefWorks:311}. 

% Need a vignette here about a school baord member

More so than many other forms of office then the office of the elected school 
board begs the question: why run? Political scientists have grappled with this 
question with respect to political office for decades, and a number of explanations 
have been put forth. This chapter will review these theories and evaluate their 
explanatory power for local elections, of which school boards are a specific case. 
Next, leveraging a unique dataset that includes the political 
histories of over 300 Wisconsin school districts from 2002-2012 I will investigate 
empirical support for these theories. In particular, the panel nature of the 
dataset allows me to test causal claims about the role that salient policy and 
political factors may or may not play in the emergence of candidates for school 
boards. 

\section{Theories of Candidate Emergence}

I organize the political science literature into three broad schools of thought 
regarding candidate emergence. They are:

\begin{itemize}
\item Rational Choice / Strategic Candidates
\item Ambition Forming / Psychological
\item Policy Making
\end{itemize}

In addition to these broad theoretical treatments of candidacy, I review the sparse 
literature that has focused explicitly on local elections such as municipal, county, 
and school board elections. Before beginning, it is important to consider the features 
of local elections and offices that might set them apart from state and national 
legislative office. 

\subsection{Municipal Differences}

A priori there are many reasons to believe that local elections in general, and 
school board elections in particular, are qualitatively different than state or 
federal office in America. The most critical of these with relation to the above 
theories is that in most cases school board is a non-partisan office. Partisanship 
is a foundational aspect of the Rational Candidate framework and to a lesser degree 
necessarily motivates the goals of policy-oriented office seekers. Without party 
lines and with a less distinctive set of issues to distinguish and motivate 
candidates, it may be hard for individuals to exercise a rational or a policy 
oriented candidacy. \citet{RefWorks:218} has found evidence that school board 
elections can be characterized by issues defined by teacher unions - which can 
serve the role of a large external organizers of voters, donors, and nominator 
of candidates \citep{RefWorks:207}. \footnote{Though see \citet{boardfundraising2008} 
for important counter evidence about the role of large organized interests in 
the financing of school board campaigns.} 

However, there are studies in the literature where the applicability of the 
strategic emergence and personal and psychological factors have been tested empirically, 
most notably in city council elections \citep{boardfundraising2008, prewitt1, 
bledsoe1}. \citet{Krebs01111999} finds evidence of strategic candidate emergence in ward level 
elections. 


% Candidates for school board, as discussed in the introduction, are 
% representing a narrow interest to an inherently very local constituency. This 
% stands in contrast to state or federal legislators who oversee a wide ranging 
% policy brief, represent tens or hundreds of thousands of voters, and run 
% election campaigns that cost hundreds of thousands to millions of dollars. Second

% Small 
% Local
% Constrained
% Not prestigious
% Lacking of funds

% borrow from introduction and link back to that section

\subsection{Rational Model of Candidate Entry}

The strategic view of candidate emergence argues that candidates emerge for 
office when they perceive victory to be most likely \citep{schlesinger1}. This includes avoiding 
running against incumbents or choosing to run against incumbents when they are 
weak or when redistricting has altered the political conditions in the district 
\citep{Black72, Black1972}. 
\citet{JacobsonBook} represents targues that high-quality challengers emerge when 
favorable electoral conditions emerge for their party. For U.S. House election, 
strategic timing indeed has been found to increase the likelihood of a win 
and increases the vote-share of such candidates \citep{JacobsonStrategy}. This 
strategic view of candidate emergence has many appeals. Most importantly, political 
contests do appear to become more heated with higher quality challengers emerging 
when incumbents appear weak, districts are redrawn, or national trends appear 
in the favor of the party. 

Strategic candidate emergence studies have tended to be tested weakly - largely 
finding unsurprisingly that strong challengers emerge when conditions are favorable, 
but ignoring that amateurs also behave in this manner \citep{CanonArt, CanonBook}. 
This contrasts with previous tests which focused on only the emergence of high 
quality candidates, narrowly defined as having held prior office. \citet{Lazarus2008} 
enters into this debate by explicitly testing the differences between amateurs 
and high quality candidates, while also focusing on the differences between the 
decision to challenge in a primary and in a general election. The problem of 
how to operationalize a high-quality candidate looms large in this literature, but 
even larger when seeking to generalize the Rational Model of Candidate Entry to 
lower levels of government, where candidates are likely to be beginning their 
political career. Certainly, defining candidate quality as holding prior office 
creates a very different and much smaller group of candidates than in higher 
level state and federal offices. 


Though the Rational Model has empirical support from U.S. Congressional elections, 
important questions remain about how to operationalize some of the key concepts of 
the model when applying it outside of these offices. How do we think of candidate 
quality for local offices such as mayor (think Michael Bloomberg) or school board? 
How does the Rational Model operate in an implicitly non-partisan environment (urban 
areas with a single party in control) or explicitly non-partisan offices such as 
most American school boards? Alternative political environments thus present an 
important extension of the empirical testing of this model. 

\subsection{Nascent and Personal Political Ambition}

For some political scientists, the Rational Model does not explain enough of the 
behavior of candidates and leaves out important factors in the decision to run 
for office. For one, the Rational Model leaves little to say about why a candidate 
will first seek elected office - which may be based on personal experience, 
social status, exposure to political communities, and status in a historically 
politically marginalized group \citep{AJPS:AJPS147}. By explaining the initial 
choice to run for office these authors argue we can paint a richer picture of the 
supply of candidates and the pool from which candidates for high office will be drawn. 

The cornerstone of this argument was laid by \citet{Lasswell} theory of a 
``political person'' who sought political power. The first studies to operationalize 
what features make up such a ``political person'' focused on personality and individual 
attributes \citep{barber1, fishel1}, a line of research that was put on the back 
burner with the focus on the Rational Model. 

Understanding 
and explaining the "nascent" aspects of political ambition -- predictive features of 
candidates themselves -- \citet{AJPS:AJPS147} attempt to explain what the Rational Model 
cannot -- entry into first office. 

This work builds on the unremarkable fact that political candidates are likely 
to possess more time, money, and civic skills to 
devote to running for office \citep{Verba1}. But, the fact that only a small subset 
of individuals with time, money, and resources run for political office - university 
professors are surprisingly absent from the ballot - requires further investigation. 
Family and childhood socialization can account for the desire to acquire these 
resources and devote them to office - sometimes very early on in life \citep{prewitt1, beckjennings}. 
\citet{AJPS:AJPS147} attempt to test this and a number of additional explanations 
such as measures of individual self-efficacy, stage in life, ambition, demographics, 
and opportunity both perceived and partisan. The authors find that these factors 
substantially "winnow" the pool of potential candidates with time, money, and resources to 
pursue office into a much smaller group of actual candidates - from which the Rational Model builds its 
theory draws its conclusions. 

It is clear that the study of nascent political ambition provides a vital frame for understanding 
the emergence of candidates in local and municipal elections. What is less obvious, 
but perhaps more important, is that the study of local and municipal elections is 
vital to understanding the candidate pool for higher offices. By moving down to 
the level of state politicians, \citet{MaestasEtAl} 
find substantial variation among state legislators based on the level of professionalization 
of their legislature. This work demonstrates that the Rational Choice Model alone 
is not sufficient to explain why some highly qualified candidates do not emerge 
and others do - professional norms and individual ambition were missing. Work on 
lower levels of government may uncover other important linkages and help inform how 
such local institutions can be shaped in such a way as to foster the development 
of quality candidates necessary for democratic legitimacy. 


\subsection{Policy Change}

Though self-assessments of success and personal ambition are important to understanding 
why individuals would devote time, money, and personal reputation to pursuit of 
office, this work is not sufficient to explain the motivations of candidates. The 
behavior of celebrity amateur candidates provides an important window into the 
deficiency of these explanations. \citet{CanonBook} demonstrates that successful 
and famous people with little to gain personally from running for office run for a
diverse set of reasons, including particularly to forward a specific policy agenda. While the
desire to set policy may seem like an intuitive and perhaps obvious explanation for 
candidates running for office, its explanatory power relative to other measures of 
opportunity, socialization, and candidate self-assessment is quite small \citep{AJPS:AJPS147}. 

Though high-profile candidates sometimes run with explicit policy goals 
in mind, it has yet to be assessed if candidates for local office seek office for explicit 
policy goals with any level of regularity. \citet{deckman1} suggests that with school 
board candidates there may be a strong policy orientation, and that in some cases this 
policy orientation may be explicitly developed by well-organized interest groups \citep{RefWorks:240}. 
Evaluating competing explanations about the motivations of school board candidates 
in a more rigorous way may help shed light on the motivations of the larger pool of 
candidates. 



\section{Data and Methods}



With these three frames I now turn my attention to investigating the motivations 
behind the emergence of candidates in school board elections. In this study, two 
approaches will be taken to allow for a more explicit test of the theories outlined 
above. First, theories of candidate emergence will be explored in the context of 
school board elections using the longitudinal database of school board election 
results from Wisconsin. Next, we will turn our attention to assessing the causal 
impact of policy preferences on candidate emergence by leveraging the unique 
political conditions in Wisconsin in the period studied - namely the availablility 
of fine-grained policy preference indicators for school districts through the 
2012 recall election. 

\subsection{Wisconsin Data}

This paper utilizes a unique dataset of school board election results in the state 
of Wisconsin from 2002-2012.\footnote{For more details on the collection method, 
see the Appendix.} While previous studies of school board elections have focused 
on nationally representative samples (and been plagued by non-response for smaller 
more common districts), or statewide samples for a snapshot in time, this data follows in the 
tradition of \citet{RefWorks:311} by constructing a panel of school board elections 
within a single state. In addition to collecting the results of all school board 
general elections for which records could be obtained throughout this time period, 
this study also includes the results from any primary elections that were held 
as well. The longitudinal look also allows for constructing a measure of candidate 
quality not previously available in the literature on school board elections -- 
prior attempt for school board office. 

This database on the electoral outcomes of each school board is accompanied by 
a broad range of attributes about the school districts they oversee. These include 
fiscal, academic, demographic, and political measures of the district and the population 
it serves. A final feature of this dataset is that the years of the panel span 
an important and dramatic policy change for education in Wisconsin - the passage of 
Wisconsin Act 10 by Wisconsin Governor Scott Walker. While the political fallout 
over this legislation was nightly news across the nation, the implications of Act 10
were and continue to be particularly salient for school districts, school boards, 
and local policy regarding the governance of education in the state. Combined with 
unprecedented cuts in per-pupil-spending, Act 10 was framed as a set of "tools" 
to give local officials - elected school boards - the flexibility to reduce their 
fixed costs by renegotiating employee compensation and benefits with employees now 
with much weakened labor representation and substantial limits on their bargaining 
authority. \footnote{Perhaps the most salient 
issue is the requirement under the law that any wage increase greater than a cost 
of living adjustment pegged to CPI be approved by a district wide referenda - 
effectively placing a firm ceiling on any salary negotiations2011 Wisconsin Act 10: 
https://docs.legis.wisconsin.gov/2011/related/acts/10}

% Section on sample and coverage
One reason that school board elections have not been comprehensively studied in a 
single state is the highly decentralized state of record keeping for school board 
elections in many states. In Wisconsin school district election records are not 
kept in any central record keeping, but are the sole responsibility of the school 
district clerk (CITE STATUTE).\footnote{While a few enterprising county clerks have 
collected school board election results and made them available, these can be incomplete 
by only including the precincts that are within the county. They also are not official. 
\citep{clerk1}.} In order to conduct this study then, a records 
request was made to all public school districts in the state of Wisconsin (COUNT). 
This request was e-mailed to the school district administrator in each of Wisconsin's 
424 school districts in January of 2013. Three follow up waves were conducted, and 
at the end of the collection period, \Sexpr{print(SAMPSIZE)} districts responded 
with records. 

School board election records came in many forms. The official and preferred 
records included the Statement of the Board of Canvass and the Certificate of the 
Board of Canvass. These two documents are legally mandated for each school board 
election and certify the winner for each school board seat, as well as the votes 
cast for each candidate. In most cases the records were provided electronically, 
though some were also received as hard copy in the mail. Full details on the data 
collection process can be found in the appendix. % INCLUDE ACTUAL REFERENCE 
These records were then transcribed from the various records provided by school 
districts into spreadsheets that combined together form the key database for this 
analysis. 

Using the names, vote totals, and winners from each school board election allow 
for the construction of measures of the number of candidates in each election 
cycle, the number of contested seats, the level of voter participation, and other 
metrics of electoral activity at the school board level. Importantly, because the 
data was collected for several years in each district, time-variant trends can be 
evaluated and explored. 

In addition to this unique dataset on school board election results, there exist 
a large array of publicly available data about the performance, financial health, 
and demographics of the public school districts in the state. These data are useful 
in understanding the impact of local factors on school board election conditions. 
Importantly, we can use these data elements to identify if the sample of school 
districts responding to the records request is representative of the school 
districts in the state. 


<<samplecoverage, results='asis'>>=
# Table showing sample and non-sample on key covariates
# Need to finish
mysub <- FULLDAT[FULLDAT$year == 2012, ]

selectVars <- c("TOTPOP.x", "toprepshare.x", "member", "econ_disadv_per", 
                "millrate", "PerBachelorOrAbove", "avg_salary", "average_fringe", 
                "median_income", "OOH_share", "balance_lag")

rnames <- c("Total Population", "Republican Share", "Students", 
            "% FRL", "Millrate", "Share Bachelor +", "Average Salary", 
            "Average Fringe", "Median Income", "Owner Occupied Share", 
            "Lagged Acct. Balance")

a <- round(t(aggregate(mysub[, selectVars], 
                  by = list(sample = mysub$sample), mean, na.rm=TRUE)), digits=2)
b <- round(t(aggregate(mysub[, selectVars], 
                  by = list(sample = mysub$sample), sd, na.rm=TRUE)), digits=2)

a <- as.data.frame(a); names(a) <- c("Out of Sample (Mean)", "Sample (Mean)")
b <- as.data.frame(b); names(b) <- c("Out of Sample (SD)", "Sample (SD)")

ab <- as.data.frame(cbind(a[,2], b[,2], a[,1], b[,1]))
ab[10, ] <- ab[10, ] * 10000
ab[12, ] <- ab[12, ] / 1000
names(ab) <- c("Sample (mean)", "Sample (SD)", "Out of Sample (mean)", "Out of Sample (SD)")
row.names(ab) <- c("Var", rnames)

print(xtable(ab[-1,]), format.args = list(big.mark=","), include.rownames=TRUE)

rm(a, b, ab, selectVars)
@

% Describe above table

As shown in table X, there is little difference between schools in and out of the sample. 

\subsubsection{Dependent Variable}

To understand candidacy it is important to consider measures of candidate emergence 
that make the most sense. % Find studies of candidate emergence in low-level elections
By collecting election results directly, in contrast to surveying former school 
board members, we can for the first time seriously explore the level of contestation 
in school board elections directly. Previous literature has found that apolitical 
forms of board member turnover often swamp political forms of turnover and skew 
results \citep{RefWorks:311}. Using election results we measure contestation by 
two factors -- if the number of candidates is greater than the number of victors, 
and if the number of non-minor candidates is greater than the number of victors. 


<<candidatedescriptives, results='asis'>>=
aggregate(SBELEC$candidates, by=list(SBELEC$year), function(x) sum(x) / length(x))

SBELEC$contested <- ifelse(SBELEC$candidates > SBELEC$winners, 1, 0)
a <- table(SBELEC$contested, SBELEC$year)
rownames(a) <- c("Uncontested", "Contested")
print(xtable(a[, 3:13]), include.rownames=TRUE)

# Now toss out minor candidates
SBELEC$contested2 <- ifelse((SBELEC$candidates - SBELEC$minorcand) > SBELEC$winners, 1, 0)
a <- table(SBELEC$contested2, SBELEC$year)
rownames(a) <- c("Uncontested", "Contested")
print(xtable(a[, 3:13]), include.rownames=TRUE)

@


In general, the years surrounding Act 10 do not appear more contested than the 
years prior to Act 10 -- whether minor candidates are included or excluded. However, 
we have to control for local factors as well as macro factors in order to evaluate 
the independent effect Act 10 may have had on the likelihood of running for office. 


Figure \ref{model} provides an illustration of way that school board elections can 
be an important window into candidate emergence. 

\subsection{Methods: Descriptive}

Using data gleaned from administrative records and election returns leaves little 
room to conduct an in-depth analysis at the motivations of individual candidates 
to run. However, evidence of two motivators of candidate entry can be compared 
in Wisconsin school districts. First, evidence of policy goal entry can be 
assessed. Second, evidence of strategic entry can be examined by looking at 
exogenous variations in voter turnout. In both cases we can estimate the probability 
of an election being contested through the following equation:

\[ (1) \hspace{0.5 in}  \Pr_{CE_{t}} = \alpha + \beta X_{t-1} + \gamma Z_{t} + \epsilon \] \\

Here, $\Pr_{CE_{t}}$ represents the probability that a school board seat is contested 
in an election. $\gamma$ will either represent the variable measuring the variation 
in voter turnout or the policy condition prompting candidate entry, such as a 
change in property tax rates or a change in student achievement. 

In the literature there is only very sparse indication about what local factors 
may cause candidates to enter a school board race. This is likely due to the limits 
of previous data collections to test a wide variety of hypotheses. The present 
collection combines sample election results from a large proportion of Wisconsin 
school districts with extensive administrative records capturing diverse school 
district attributes over time including change in enrollment, fiscal health, 
student and adult demographics, and school district referenda. 

\subsection{Methods: Causal}


Combining this information with returns from the late spring recall election of 
the Governor--certain to be a statewide referendum on the Governor's education policies--it is 
possible using data from all 424 school districts in the state to directly to test 
whether divided communities see greater participation by challenger candidates than 
unified communities. This would represent the first comprehensive test of the public 
choice theory of school board elections and represent the first test of Dissatisfaction 
Theory across an entire state using actual election results instead of self-reports 
of school board members and superintendents \citep{RefWorks:243,RefWorks:297}. The 
empirical model of candidate emergence (CE) would look something like: \\

\[ (2) \hspace{0.5 in}  CE_{t} = \alpha + \beta X_{t-1} + \gamma Z_{t} + \epsilon \] \\

Where $CE_{t}$ represents a measure of the number of candidates greater than one per seat, 
$\alpha$ is an intercept, $X_{t-1}$ is a vector of lagged covariates such as prior 
levels of contestation and district size, and $Z_{t}$ is the absolute value of the 
deviation from 50\% of the vote share for the Governor in a recall election aggregated 
to the school district from ward level returns.\footnote{Depending on the data and 
the prevalence of incumbent retirements candidate emergence may need to be measured a 
number of additional ways. \citet{RefWorks:337} discuss a number of possibilities for 
turnover that could be adapted to candidate emergence including: Seats available 
divided by incumbents + challengers minus retired candidates; seats available divided 
by all candidates; or seats available divided by challengers.} Thus, when $Z_{t} = 0$ 
the community is completely divided on the Governor. When $Z_{t}=.5$ the community is 
either united for or against the Governor. Thus, all things equal, we would expect 
$\gamma$ to have a negative value--as $Z_{t}$ increases, the number of challengers, 
$Y_{t}$ should decrease because the community is fairly homogeneous and the school 
board should reflect existing preferences for or against the Governor's reforms. 



\section{Results}

\subsection{Descriptive}

<<candidatedescriptives>>=

SBELEC$primary2 <- ifelse(SBELEC$primary == "None", "None", "Primary")

tax_model <- glm(contested2 ~ primary2 + millrate + cum_attptsD + overlevy_ind_lag +
                   passedD + toprepshare.x + OOH_share + perwhite + levy_chg +
                   balance_member_lag + median_income + locale3, 
                 data=SBELEC, family="binomial")



library(lme4)

mermod1 <- glmer(contested2 ~ primary2 + millrate + cum_attptsD + overlevy_ind_lag +
                    perwhite + levy_chg +
                   balance_member_lag + median_income + 
                   (1|fyear) + (1|distid), 
                 data=SBELEC, family="binomial")

rr1 <- ranef(mermod1, condVar=TRUE)

confint(mermod1, method="Wald")
@

\subsection{Causal}

<<candidatedescriptives>>=

SBELEC$secturnout <- SBELEC$sectot.x / SBELEC$VAP_adj.x
SBELEC$recallpartisan <- abs(.5 - SBELEC$secrepshare.x)
library(arm)
simple_model <- bayesglm(contested2 ~  millrate_delta + 
                      recallpartisan + secturnout +
                   balance_member_lag2 + member_delta2 + locale3, 
                 data=SBELEC[SBELEC$year == 2011, ], family="binomial")

@

\section{Conclusions}


