\chapter{Why Run for School Board?}
\label{chap:candidacy}
\chapterstyle{deposit}


<<rsetup, results='hide', echo=FALSE, message=FALSE, warning=FALSE>>=

opts_chunk$set(fig.width=8, fig.height=6, message=FALSE, error=FALSE, 
               fig.path="../../phd_figs/chap3-",
               warning=FALSE, echo=FALSE, dev='pdf')

setwd("../../")
library(eeptools)
source("data/dataAssemble.R")
source("data/cleanandprep_CANDIDACY.R")

# load data
# print descriptives

library(xtable)
options(xtable.include.rownames = FALSE, xtable.table.placement = "ht")
library(gridExtra)
library(scales)
@


\section{Introduction}

By all accounts being a school board member is a difficult and thankless job. 
School board meetings frequently occur in the evening to allow parents and 
community members to participate, and very few school board members are 
compensated for their work \citep{RefWorks:333, RefWorks:321}. Contrary to popular conceptions, 
the role of the school board as a stepping stone to further office is by all 
accounts overstated \citep{RefWorks:321, RefWorks:322}. In fact, the dissatisfaction
incumbents have with the position has been a confounding factor in the literature; in 
comparison to state wide or nationwide offices, non-political turnover due to retirement 
from the seat is the most common form of exit \citep{RefWorks:311}. 

% Need a vignette here about a school baord member

More so than many other forms of political office, the elected school 
board begs the question: why run? Political scientists have grappled with this 
question across contexts for decades, and a number of explanations 
have been put forth. This chapter will review these theories and evaluate their 
explanatory power for school boards. Next, leveraging a unique data set that includes the political 
histories of over 300 Wisconsin school districts from 2002-2012 I will investigate 
empirical support for these theories. In particular, the panel nature of the 
data set allows me to test competing claims about the role that salient policy and 
political factors play in the emergence of candidates for school 
boards. Additionally, as mentioned in Chapter \ref{chap:intro}, Wisconsin provides a 
strong test of the policy linkages between levels of government. Leveraging what is 
arguably an exogenous shock in the form of Act 10 in 2011, we can evaluate changes 
in the level of contestation in school board elections. Finally, this chapter will
consider the importance of candidate emergence 
in a full model of school district political activity outlined in Figure \ref{model}. 

\section{Theories of Candidate Emergence}

I organize the political science literature into three broad schools of thought 
regarding candidate emergence. They are:

\begin{myitemize}
\item Strategic Candidates
\item Political Psychology
\item Policy Preferences
\end{myitemize}

In addition to these broad theoretical treatments of candidacy, I review the sparse 
literature that has focused explicitly on local elections such as municipal, county, 
and school board elections. Before beginning, it is important to consider the features 
of local elections and offices that might set them apart from state and national 
legislative office. 

\subsection{Municipal Differences}

A priori there are many reasons to believe that local elections in general, and 
school board elections in particular, are qualitatively different than state or 
federal office in America. The most critical of these with relation to the above 
theories is that in most cases school board is a non-partisan office. Partisanship 
is a foundational aspect of the strategic candidate framework and to a lesser degree 
necessarily motivates the goals of policy-oriented office seekers. Without party 
lines and with a less distinctive set of issues to distinguish and motivate 
candidates, it may be hard for individuals to exercise a strategic or a policy 
oriented candidacy. \citet{RefWorks:218} has found evidence that school board 
elections can be characterized by issues defined by teacher unions - which can 
serve the role of a large external organizers of voters, donors, and nominator 
of candidates \citep{RefWorks:207}.\footnote{Though see \citet{boardfundraising2008} 
for important counter evidence about the role of large organized interests in 
the financing of school board campaigns.} 

However, there are studies in the literature where the applicability of the 
strategic emergence and personal and psychological factors have been tested empirically, 
most notably in city council elections \citep{boardfundraising2008, prewitt1, 
bledsoe1}. \citet{Krebs01111999} finds evidence of strategic candidate emergence in 
ward level elections. However, school board members differ yet from these local 
candidates due to their role as political actors within the limited policy sphere 
of public education and the power of property tax levies.\footnote{Though in practice 
the power to set property tax levels is often constrained by both state law and 
practical concerns (CITATION).} 

% Small 
% Local
% Constrained
% Not prestigious
% Lacking of funds

% borrow from introduction and link back to that section

\subsection{Strategic Timing of Candidate Entry}

Simply put, strategic view of candidate entry argues that candidates emerge for 
office when they perceive victory to be most likely \citep{schlesinger1}. This includes avoiding 
running against incumbents or choosing to run against incumbents when they are 
weak or when redistricting has altered the political conditions in the district 
\citep{Black72, Black1972}. However, candidates are not merely strategic within 
their individual race, but are also sensitive to macro-level partisan trends.
\citet{JacobsonBook}'s strategic timing theory argues that high-quality challengers 
emerge when favorable electoral conditions emerge for their party. For U.S. House election, 
strategic timing indeed has been found to increase the likelihood of a win 
and increases the vote-share of such candidates \citep{JacobsonStrategy}. This 
foundational finding matches well with the evidence that 
national legislative contests do appear to become more heated with higher quality 
challengers emerging when incumbents appear weak, districts are redrawn, or 
national trends appear in the favor of the party. 

Unfortunately, the strategic timing thesis has tended to ignore that political 
amateurs also behave in this manner \citep{CanonArt, CanonBook}. 
By only defining a high-quality challenger as a prior office holder, the strategic 
timing and rational entry models have misrepresented the decision calculus made 
by candidates when deciding to run for office. \citet{Lazarus2008} 
enters into this debate by explicitly testing the differences between amateurs 
and high quality candidates, while also focusing on the differences between the 
decision to challenge in a primary and in a general election. % What does lazarus find
The problem of how to operationalize a high-quality candidate looms large in this literature, but 
even larger when seeking to generalize the rational model to 
lower levels of government, where candidates are likely to be beginning their 
political career. Certainly, defining candidate quality as holding prior office 
creates a very different and much smaller group of candidates than in higher 
level state and federal offices. 

Though strategic timing has empirical support from U.S. Congressional elections, 
important questions remain about how to operationalize some of the key concepts of 
the model when applying it outside of these offices. How do we think of candidate 
quality for local offices such as mayor (think Michael Bloomberg) or school board? 
Does strategic timing operate in an implicitly non-partisan environment (urban 
areas with a single party in control) or explicitly non-partisan offices such as 
most American school boards? Alternative political environments thus present an 
important extension of the empirical testing of this model. 

\subsection{Nascent and Personal Political Ambition}

For some political scientists, strategic timing stops short of explaining the
 behavior of candidates and leaves out the important question of why a candidate 
will seeks office in the first place. The factors that lead someone to run, whether 
due to personal experience, social status, exposure to political communities, or 
status in a historically politically marginalized group profoundly shape the supply 
of candidates for office \citep{AJPS:AJPS147}. Furthermore, limiting the definition 
of high quality challengers to those with prior experience running for or holding office 
excludes high quality amateurs \citep{CanonArt, CanonBook}. 
By explaining the initial choice to run for office, or political ambition, we 
paint a richer picture of the pool from which candidates for office will be drawn. 

This personal motivation tradition was founded by \citet{Lasswell}'s theory of a 
``political person'' who sought political power. The first studies to operationalize 
what features make up such a ``political person'' focused on personality and individual 
attributes \citep{barber1, fishel1}, a line of research that laid dormant for some time 
after the emergence of the rational model. A more quantitative return to 
the study of such political ambition emerged with \citet{AJPS:AJPS147}'s study of 
political psychology directed at explaining the ``nascent'' aspects of political ambition
through predictive features of candidates themselves. 

This work builds on the seemingly unremarkable foundation that political 
candidates are likely to possess more time, money, and civic skills to 
devote to running for office \citep{Verba1}. But, in fact, only a small subset 
of individuals with time, money, and resources run for political office - for 
example, university professors are surprisingly absent from the ballot. This requires further 
investigation as to what differentiates those with resources who choose to run for 
office from those who do not. Family and childhood socialization can account for 
the desire to acquire these resources and devote them to office - sometimes very 
early on in life \citep{prewitt1, beckjennings}. 
\citet{AJPS:AJPS147} attempt to test this and a number of additional explanations 
such as measures of individual self-efficacy, stage in life, ambition, demographics, 
and opportunity both perceived and partisan. The authors find that these factors 
substantially ``winnow'' the pool of potential candidates with time, money, and resources to 
pursue office into a much smaller group of actual candidates - whose entry into 
an election the rational model attempts to explain. 

It is clear that the study of nascent political ambition provides a vital frame for understanding 
the emergence of candidates in local and municipal elections. What is less obvious, 
but perhaps more important, is that the study of local and municipal elections is 
vital to understanding the candidate pool for higher offices. By moving down to 
the level of state politicians, \citet{MaestasEtAl} find substantial variation 
among state legislators based on the level of professionalization 
of their legislature. In as much as candidates flow from local to state and 
national politics, the impact that those local and state institutions have on 
shaping the quality of candidates for higher office is an important avenue for 
further research into how the pool of candidates develops and can be shaped by 
institutions. The political psychology framework provides an important extension 
of strategic timing by explaining how the pool of potential candidates is 
developed in the first place. Work on lower levels of government may uncover other
important linkages and help inform how such local institutions can be shaped in
such a way as to foster the development of quality candidates. 


\subsection{Policy Change}

Though self-assessments of success and personal ambition are important to understanding 
why individuals would devote time, money, and personal reputation to pursuit of 
office, this work is not sufficient to explain the motivations of candidates. The 
behavior of celebrity amateur candidates provides an important window into the 
deficiency of these explanations. \citet{CanonBook} demonstrates that successful 
and famous people with little to gain personally from running for office run for a
diverse set of reasons, including particularly to forward a specific policy agenda. While the
desire to set policy may seem like an intuitive and perhaps obvious explanation for 
candidates running for office, its explanatory power relative to other measures of 
opportunity, socialization, and candidate self-assessment is quite small \citep{AJPS:AJPS147}. 

Though high-profile candidates sometimes run with explicit policy goals 
in mind, it has yet to be assessed if candidates for local office are motivated by explicit 
policy goals with any level of regularity. \citet{deckman1} suggests that with school 
board candidates there may be a strong policy orientation, and that in some cases this 
policy orientation may be explicitly developed by well-organized interest groups \citep{RefWorks:240}. 
Deckman's study of the organization of the Christian right to locate, train, and fund 
candidates for school board provides evidence that strong policy motivation and 
organized interest groups can spur candidates to run. Evaluating competing 
explanations about the motivations of school board candidates 
in a more rigorous way may help shed light on the motivations of the larger pool of 
candidates. 

\subsection{Summary}

All three of these traditions leave something to be desired in the context of 
school board elections. The present study does not have the ability to delve into the 
ambition and psychology of candidates for school board elections, though quality 
descriptive work has been done exploring the political and personal backgrounds of 
school board members as reviewed in Chapter \ref{chap:theoryreview} 
\citep{RefWorks:321, RefWorks:322, RefWorks:333}. However, 
this chapter will explore the evidence of strategic timing and policy change as 
motivations of school board candidate emergence. As discussed in Chapter \ref{chap:theoryreview}, the four theories 
of school board election contestation all seek to explain the general pattern of 
quiet uncontested elections punctuated by incumbent defeat and sharp increases 
in turnout. This chapter will first explore the extent to which this stylized 
representation of school board elections rings true in the Wisconsin case, and second 
seek to evaluate the explanatory power of these theories in reaching down to the 
local level and explaining the entry of candidates into school board races.

\section{Data and Methods}



With these three frames I now turn my attention to investigating the motivations 
behind the emergence of candidates in school board elections. In this study, two 
approaches will be taken to allow for a more explicit test of the theories outlined 
above. First, theories of candidate emergence will be explored in the context of 
school board elections using the longitudinal database of school board election 
results from Wisconsin. 

\subsection{Wisconsin Data}

This paper utilizes a unique data set of school board election results in the state 
of Wisconsin from 2002-2012.\footnote{For more details on the collection method, 
see the Appendix \ref{app:data}}. While previous studies of school board elections have focused 
on nationally representative samples (and been plagued by non-response for smaller 
districts which constitute the majority of school board members), or statewide 
samples for a snapshot in time, this data follows in the 
tradition of \citet{RefWorks:311} by constructing a panel of school board elections 
within a single state. In addition to collecting the results of all school board 
general elections for which records could be obtained throughout this time period, 
this study also includes the results from any primary elections that were held 
as well. The longitudinal look also allows for constructing a measure of candidate 
quality not previously available in the literature on school board elections -- 
prior attempt for school board office. 

This database on the electoral outcomes of each school board is accompanied by 
a broad range of attributes about the school districts they oversee. These include 
fiscal, academic, demographic, and political measures of the district and the population 
it serves. A final feature of this data set is that the years of the panel span 
an important and dramatic policy change for education in Wisconsin - the passage of 
Wisconsin Act 10 by Wisconsin Governor Scott Walker. While the political fallout 
over this legislation was nightly news across the nation, the implications of Act 10
were and continue to be particularly salient for school districts, school boards, 
and local policy regarding the governance of education in the state. Combined with 
unprecedented cuts in per-pupil-spending, Act 10 was framed as a set of "tools" 
to give local officials - elected school boards - the flexibility to reduce their 
fixed costs by renegotiating employee compensation and benefits with employees now 
with much weakened labor representation and substantial limits on their bargaining 
authority. \footnote{Perhaps the most salient 
issue is the requirement under the law that any wage increase greater than a cost 
of living adjustment pegged to CPI be approved by a district wide referenda - 
effectively placing a firm ceiling on any salary negotiations2011 Wisconsin Act 10: 
https://docs.legis.wisconsin.gov/2011/related/acts/10}


In addition to the unique data set on school board election results described in 
Chapter \ref{chap:wisco}, there exist 
a large array of publicly available data about the performance, finances, 
and demographics of the public school districts in the state. These data are useful 
in understanding the impact of local factors on school board election conditions. 
Importantly, we can use these data elements to identify if the sample of school 
districts responding to the records request is representative of the school 
districts in the state. 

As shown in table \ref{tab:samplecomp}, there is little difference between schools 
in and out of the sample. From Chapter \ref{chap:wisco} we saw that the school 
districts providing records 

\subsubsection{Dependent Variable}

To understand candidacy it is important to consider measures of candidate emergence 
that make the most sense. % Find studies of candidate emergence in low-level elections
By collecting election results directly, in contrast to surveying former school 
board members, we can for the first time seriously explore the level of contestation 
in school board elections directly. Previous literature has found that apolitical 
forms of board member turnover often swamp political forms of turnover and skew 
results \citep{RefWorks:311}. A limitation of the current study is identifying seat 
vacancies due to retirement or plausible threat where a candidate does not mount a 
campaign. This is less troubling in the school board case because the cost of 
campaigning is so low that presumably a challenged incumbent would still stand 
for election. Using election results we measure contestation by 
two factors -- if the number of candidates is greater than the number of victors, 
and if the number of non-minor candidates is greater than the number of victors. 


<<candidatedescriptives4, echo=FALSE, fig.cap="Districts with contested school board elections under two different measures of candidate contestation.">>=
library(scales)
dist_turn$contest <- "Uncontested"
dist_turn$contest[dist_turn$nrealcand > dist_turn$nwins & dist_turn$ninc > 0] <- "Incumbent Contested"
dist_turn$contest[dist_turn$nrealcand > dist_turn$nwins & dist_turn$ninc ==0] <- "Open Contested"

# 
races$contested <- 0
races$contested[races$nrealcand > races$nwins & 
                          races$nwins > 0 & races$electiontype == 1] <- 1
races$contestedSer <- 0
races$contestedSer[(races$nrealcand - races$nminor) > races$nwins & 
                          races$nwins > 0 & races$electiontype == 1] <- 1
#  incumbents challenged
races$contestedInc <- 0
races$contestedInc[races$nrealcand > races$ninc & 
                          races$ninc > 0 & races$electiontype == 1] <- 1
races$contestedSerInc <- 0
races$contestedSerInc[(races$nrealcand - races$nminor) > races$ninc & 
                          races$ninc > 0 & races$electiontype == 1] <- 1
# 


a <- table(races$contestedSer, races$year)
a.tmp <- prop.table(a, margin = 2) 
a <- t(a)
a.tmp <- t(a.tmp)
a <- as.data.frame(a)
a.tmp <- as.data.frame(a.tmp)
a$Var1 <- as.numeric(as.character(a$Var1))
a.tmp$Var1 <- as.numeric(as.character(a.tmp$Var1))

p1 <- qplot(factor(Var1), Freq, data=a[a$Var1 > 2002 & a$Var1 < 2013,], geom='bar', stat='identity', fill=Var2, position='stack', color = I("black")) + 
  labs(x= "Year", y = "Districts", title = "Excluding Minor Candidates", 
       fill = "Contested") + theme_bw()

p1 <- qplot(factor(Var1), Freq, data=a.tmp[a.tmp$Var1 > 2002 & a.tmp$Var1 < 2013,], 
            geom='bar', stat='identity', fill=Var2, position='stack', color = I("black")) + 
  labs(x= "Year", y = "Percent of Races", title = "Excluding Minor Candidates", 
       fill = "Contested") + theme_bw() + scale_y_continuous(label = percent)


a <- table(races$contested, races$year)
a.tmp <- prop.table(a, margin = 2) 
a <- t(a)
a.tmp <- t(a.tmp)
a <- as.data.frame(a)
a.tmp <- as.data.frame(a.tmp)
a$Var1 <- as.numeric(as.character(a$Var1))
a.tmp$Var1 <- as.numeric(as.character(a.tmp$Var1))


p2 <- qplot(factor(Var1), Freq, data=a[a$Var1 > 2002 & a$Var1 < 2013,], geom='bar', stat='identity', fill=Var2, position='stack', color = I("black")) + 
  labs(x= "Year", y = "Races", title = "Including Minor Candidates", 
       fill = "Contested")+ theme_bw()

p2 <- qplot(factor(Var1), Freq, data=a.tmp[a.tmp$Var1 > 2002 & a.tmp$Var1 < 2013,], 
            geom='bar', stat='identity', fill=Var2, position='stack', color = I("black")) + 
  labs(x= "Year", y = "Percent of Races", title = "Including Minor Candidates", 
       fill = "Contested") + theme_bw() + scale_y_continuous(label = percent)


grid.arrange(p1, p2, main = "Comparing School Board Contestation Measures")
@


% Compare other measures of contestation, number of candidates per seat, etc. 

Figure \ref{fig:candidatedescriptives4} depicts the pattern of school board candidate 
emergence over time. Excluding minor candidates vastly changes the share of elections 
that are contested at any given juncture. Minor candidates are defined as those 
candidates who receive fewer than 30 votes on the ballot. With appearance on a 
school board ballot being much less of selection filter than many other higher 
offices, it is important to evaluate the seriousness and strength of an opponent 
in an alternative way. Here we filter out elections featuring an opposition candidate 
that receives fewer than 30 votes as non-contested elections. 

Another way we might measure the level of candidate emergence in school board races 
would be to look at the number of candidates per open seat. This measure would 
differentiate between districts with wide spread contestation and those with 
simply a single contested seat -- perhaps adding some additional information. 

<<perseatcontests,  echo=FALSE, fig.cap="Serious candidates per open seat by school year in Wisconsin school districts over time.">>=

races$candPerSeat <- races$nrealcand / races$nwins

qplot(factor(year), candPerSeat, 
      data=races[races$year > 2001 & races$year < 2013,], geom='boxplot') + 
  theme_bw() + 
  labs(x="Year", y="Candidates per Open Seat", 
       title = "Candidates Per Open Seat on Wisconsin School Boards") + 
  geom_hline(yintercept = 2, linetype = I(2), color = I("blue"))


@

As Figure \ref{fig:perseatcontests} demonstrates, the level of contestation per open 
seat does not change much across the years with the vast majority of seats having 
between 1 and 2 candidates per seat. In general, the years surrounding Act 10 do not appear more contested than the 
years prior to Act 10 -- whether minor candidates are included or excluded. However, 
we have to control for local factors as well as macro factors in order to evaluate 
the independent effect Act 10 may have had on the likelihood of running for office. 

\clearpage
\subsection{Methods: Descriptive}

Using administrative records and election returns leaves little 
room to conduct an in-depth analysis at the motivations of individual candidates 
to run. In the literature there is only very sparse indication about what local factors 
may cause candidates to enter a school board race. This is likely due to the limits 
of previous data collections to test a wide variety of hypotheses. The present 
collection combines sample election results from a large proportion of Wisconsin 
school districts with extensive administrative records capturing diverse school 
district attributes over time including change in enrollment, fiscal health, 
student and adult demographics, and school district referenda. Thus, an empirical 
model of candidate emergence (CE) is represented below in equation 1:

\[ (1) \hspace{0.25 in}  \Pr_{CE_{t}} = \alpha + \beta X_{t-1} + \epsilon \] \\

Here, $\Pr_{CE_{t}}$ represents the probability that a school board seat is contested 
in an election. The $X_{t-1}$ represent lagged variables measuring school districts 
in three domains -- taxation decisions, political conditions, and policy choices. 

Table \ref{tab:emergenceD} shows the theories and expected evidence in support of 
them that can be explored using a descriptive analysis of the Wisconsin data. Here 
we are evaluating what evidence there is that is suggestive of a relationship in 
macro-level motivations among school board candidates common across the state of 
Wisconsin. A lack of evidence tells us that we have the wrong measures. Finding 
supportive measures suggests that further work with better measures should be 
undertaken. 

\begin{table}[h!]
\begin{center}
\begin{small}
\caption{Theories of Candidate Emergence and Expected Evidence}
\label{tab:emergenceD}
\begin{tabular}{| p{.2\textwidth} | p{.25\textwidth} | p{.45\textwidth} |}
\hline
\textbf{Theory}  & \textbf{Citation} & \textbf{Expected Finding} \\ \hline
Strategic Candidates  & \citet{Plutzer2002} & Change in partisanship precedes increase in candidates \\ \hline
Policy Oriented Candidates & \citet{deckman1, CanonBook} & Changes in policy drive change \\ \hline
%Fiscal Revolt & \citet{RefWorks:297,RefWorks:271} & Union membership as share of electorate drives up turnout \\ \hline
Ambition & \citet{AJPS:AJPS147, Lasswell} & No data available to test \\ \hline
Dissatisfaction & \citet{RefWorks:297,RefWorks:271} & Failed referenda leads to more candidates running \\ \hline
\end{tabular}
\end{small}
\end{center}
\end{table}

To do this we will fit three models plus an overall model: 


\begin{table}[h!]
\begin{center}
\begin{small}
\caption{Descriptive Models of Candidate Emergence}
\label{tab:emergenceDmodels}
\begin{tabular}{| p{.1\textwidth} | p{.4\textwidth} | p{.35\textwidth} |}
\hline
\textbf{Model}  & \textbf{Predictors} & \textbf{Interpretation} \\ \hline
Fiscal   & revenue limit, tax rate, median income, referenda & If the model is explanatory, fiscal forces may motivate candidates\\ \hline
Politics & Lagged contestation, lagged primary, cumulative debt referenda, political division, lagged referendum & Political activity \\ \hline
%Fiscal Revolt & \citet{RefWorks:297,RefWorks:271} & Union membership as share of electorate drives up turnout \\ \hline
Policy & teacher compensation, referenda attempts & Unsure \\ \hline \hline
Controls & District population, white \%,  median income & To control for differences in contexts \\ \hline
\end{tabular}
\end{small}
\end{center}
\end{table}

There are some unexplored measures to be added including the turnover of the 
district administrator (to test dissatisfaction theory), union support in the 
district measured by re-certification strength, and more precise measures of 
referenda outcomes, share of students in public education,  and school and 
district staff, teacher, and administrative salaries. This section will be much 
improved!


\subsection{Methods: Causal}

Combining this information with returns from the late spring recall election of 
the Governor--certain to be a statewide referendum on the Governor's education policies--it is 
possible using data from all 424 school districts in the state to directly to test 
whether divided communities see greater participation by challenger candidates than 
unified communities. This would represent the first comprehensive test of the public 
choice theory of school board elections and represent the first test of Dissatisfaction 
Theory across an entire state using actual election results instead of self-reports 
of school board members and superintendents \citep{RefWorks:243,RefWorks:297}. The 
empirical model of candidate emergence (CE) would look something like: \\

\[ (2) \hspace{0.25 in}  CE_{t} = \alpha + \beta X_{t-1} + \gamma Z_{t} + \epsilon \] \\

Where $CE_{t}$ represents a measure of the number of candidates greater than one per seat, 
$\alpha$ is an intercept, $X_{t-1}$ is a vector of lagged covariates such as prior 
levels of contestation and district size, and $Z_{t}$ is the absolute value of the 
deviation from 50\% of the vote share for the Governor in a recall election aggregated 
to the school district from ward level returns.\footnote{Depending on the data and 
the prevalence of incumbent retirements candidate emergence may need to be measured a 
number of additional ways. \citet{RefWorks:337} discuss a number of possibilities for 
turnover that could be adapted to candidate emergence including: Seats available 
divided by incumbents + challengers minus retired candidates; seats available divided 
by all candidates; or seats available divided by challengers.} Thus, when $Z_{t} = 0$ 
the community is completely divided on the Governor. When $Z_{t}=.5$ the community is 
either united for or against the Governor. Thus, all things equal, we would expect 
$\gamma$ to have a negative value--as $Z_{t}$ increases, the number of challengers, 
$Y_{t}$ should decrease because the community is fairly homogeneous and the school 
board should reflect existing preferences for or against the Governor's reforms. 

\section{Results}

\subsection{Descriptive}

The challenge in the descriptive analysis is to identify systematic contextual 
factors that have influence over school board candidate emergence. In essence, we 
can imagine three types of contextual factors that may influence the local political 
conditions in a school board -- taxation decisions, political conditions, and 
policy decisions. Of particular interest is understanding which of these factors, 
for the sample observed and over the time period of observation, are the most 
predictive of the emergence of contested school board seats. 

\subsubsection{Demographics}

Let's look at the demographics of districts and how they affect the likelihood 
of a challenge. 

% 3 modeling strategies
%% model binomial by district, contested or not
%% model beta by district, # of contested out of # of races
%% model nested, races in districts

<<buildingDV>>=
dist_turn$contest1 <- "Uncontested"
dist_turn$contest1[dist_turn$nrealcand > dist_turn$nwins] <- "Contested"
dist_turn$contest2 <- "Uncontested"
dist_turn$contest2[(dist_turn$nrealcand - dist_turn$nminor) > dist_turn$nwins] <- "Contested"
dist_turn$contest2 <- factor(dist_turn$contest2)
dist_turn$contest1 <- factor(dist_turn$contest1)
confusion.glm <- function(data, model) {
  prediction <- ifelse(predict(model, data, type='response') > 0.5, TRUE, FALSE)
  confusion  <- table(prediction, as.logical(model$y))
  confusion  <- cbind(confusion, c(1 - confusion[1,1]/(confusion[1,1]+confusion[2,1]), 1 - confusion[2,2]/(confusion[2,2]+confusion[1,2])))
  confusion  <- as.data.frame(confusion)
  names(confusion) <- c('FALSE', 'TRUE', 'class.error')
  confusion
}


dist_turn$VAP_adjLOG <- log(dist_turn$VAP_adj)
dist_turn$median_incomeLOG <- log(dist_turn$median_income) 
dist_turn$ADJ_MEDIAN_FRINGE_TEACH[dist_turn$ADJ_MEDIAN_FRINGE_TEACH == 0] <- 1
dist_turn$ADJ_MEDIAN_FRINGE_TEACHlog <- log(dist_turn$ADJ_MEDIAN_FRINGE_TEACH)
dist_turn$ADJ_MEDIAN_SALARY_TEACHlog <- log(dist_turn$ADJ_MEDIAN_SALARY_TEACH)
dist_turn$partyDivision <- abs(0.5 - dist_turn$fallTwoPartyShareDem)
dist_turn$overrideYesPer <- dist_turn$yesVotes / dist_turn$VAP_adj

@

<<demogModel, results='asis'>>=
moddat <- dist_turn[, c("contest2", "contest1", "distid","year", 
                        "balance_member_lag", 
                        "PerBachelorOrAbove", "VAP_adjLOG", "per_white_all", 
                        "districtwide",
                        "OOH_share", "median_incomeLOG", "per65o", 
                        "NonWhitePublicPupilPer", "NonPublicPupilPer", 
                        "teachShareofVoters", "locale2", 
                        "member_delta_per")]

moddat <- moddat[order(moddat$distid, moddat$year),]
moddat$distid <- factor(moddat$distid)
moddat$year <- factor(moddat$year)
moddat$PerBachelorOrAbove <- moddat$PerBachelorOrAbove * 100
moddat$per_white_all <- moddat$per_white_all * 100
moddat$OOH_share <- moddat$OOH_share * 100
moddat$per65o <- moddat$per65o * 100
moddat$teachShareofVoters <- moddat$teachShareofVoters * 100
moddat$member_delta_per <- moddat$member_delta_per * 100
moddat$districtwide <- factor(moddat$districtwide)
library(sandwich)
library(rms)
library(apsrtable)
moddat <- na.omit(moddat)
dd <<- datadist(moddat)
options(datadist="dd")

demogModel <- glm(contest2 ~ VAP_adjLOG + PerBachelorOrAbove + per_white_all + 
                    OOH_share + median_incomeLOG + per65o + 
                    NonWhitePublicPupilPer + NonPublicPupilPer + 
                    teachShareofVoters + locale2 + member_delta_per, 
                  data = moddat, family = "binomial")

confusion.glm(demogModel$model, demogModel)

demogModel2 <- glm(contest2 ~ VAP_adjLOG + PerBachelorOrAbove + per_white_all + 
                    OOH_share + median_incomeLOG + per65o + 
                    NonWhitePublicPupilPer + NonPublicPupilPer + 
                    teachShareofVoters + locale2 + member_delta_per + 
                     factor(year) + factor(districtwide), 
                  data = moddat, family = "binomial")

demogModel3 <- glm(contest2 ~ VAP_adjLOG + PerBachelorOrAbove + per_white_all + 
                    OOH_share + median_incomeLOG + per65o + 
                    NonWhitePublicPupilPer + NonPublicPupilPer + 
                    teachShareofVoters + locale2 + member_delta_per + 
                     distid, 
                  data = moddat, family = "binomial")


# dumbRLMbest <- lrm(contest2 ~ VAP_adjLOG + PerBachelorOrAbove + per_white_all + 
#                     OOH_share + median_incomeLOG + per65o + 
#                     NonWhitePublicPupilPer + NonPublicPupilPer + 
#                     teachShareofVoters + locale2 + member_delta_per + 
#                     factor(year) + factor(districtwide), 
#                    data = moddat, x= TRUE, y = TRUE)
# 
# dumbRLMbest$se <- sqrt(diag(vcov(robcov(dumbRLMbest, cluster = moddat$distid))))

dumbRLM2$se <- sqrt(diag(vcov(robcov(dumbRLM2, cluster = moddat$distid))))

apsrtableSummary.rms <<- function(x) {
  s <- summary.lm(x)
  newCoef <- coef(s)
  ## which columns have z scores? (two of them in robust case)
  zcols <- grep("value",colnames(newCoef))
  newCoef[,zcols] <- pt(abs(newCoef[,zcols]),df=s$df[2], lower.tail=FALSE)
  colnames(newCoef)[zcols] <- "Pr(z)"
  s$coefficients <- newCoef
  ## put the robust se in $se so that notefunction works automatically
  ## the se checker will overwrite [,4] with pt, but this doesn't matter
  ## because the last column Pr(z) is used by apsrstars() anyway
  ## and the se are pulled from $se.
  if("orig.var"%in% objects(x)==TRUE) {
    s$se <- sqrt(diag(x$var))
  }
  return(s)
}

apsrtable(demogModel, demogModel2, demogModel3,
          label="tab:demogmods", 
          model.names=c("Simple Demog.", "Demog + Year FE", 
                        "Demog + District FE"), 
          caption = "Models of Contestation in School Board Elections",
          omitcoef=list("distid", 
                        expression(grep("distid", coefnames, value=TRUE)), 
                        "year", 
                        expression(grep("year", coefnames, value = TRUE))), 
          Sweave=FALSE, float = "sidewaystable")


@


Some text. Do I put lagged contestation in?

We need to consider a partially pooled model. 

<<partialPooldemog>>=
library(lme4)
library(blme)

demogModelPP <- bglmer(contest2 ~ VAP_adjLOG + PerBachelorOrAbove + per_white_all + 
                    OOH_share + median_incomeLOG + per65o + 
                    NonWhitePublicPupilPer + NonPublicPupilPer + 
                    teachShareofVoters + locale2 + member_delta_per + 
                     (1|year), 
                  data = moddat, family = binomial, 
                  cov.prior = wishart)


demogModelPP2 <- bglmer(contest2 ~ VAP_adjLOG + PerBachelorOrAbove + 
                          per_white_all + 
                    OOH_share + median_incomeLOG + per65o + 
                    NonWhitePublicPupilPer + NonPublicPupilPer + 
                    teachShareofVoters + locale2 + member_delta_per + 
                     (1|distid), 
                  data = moddat, family = binomial, 
                  cov.prior = wishart)


@

\subsubsection{Fiscal}

One of the highest profile activities of a school district is fiscal management. 
Does fiscal health of a district predict the run for office? 


<<fiscalMod>>=
dist_turn$teachSalDiff <- dist_turn$ADJ_MEDIAN_SALARY_TEACHlog - 
  dist_turn$median_incomeLOG

moddat <- dist_turn[, c("contest2", "contest1", "distid","year", 
                        "balance_member_lag", 
                        "millrate", "VAP_adjLOG", "NonSDMill", 
                        "districtwide",
                        "overridePass", "median_incomeLOG", "debtPass", 
                        "millrate_delta", "refInPlace", 
                        "DEBT_ATTEMPT_CUMUL93", "eqv_member", 
                        "OVERRIDE_ATTEMPT_CUMUL93", "ADJ_MEDIAN_SALARY_TEACHlog",
                        "member_delta_per", "teachSalDiff")]

moddat <- moddat[order(moddat$distid, moddat$year),]
moddat$distid <- factor(moddat$distid)
moddat$year <- factor(moddat$year)
moddat$PerBachelorOrAbove <- moddat$PerBachelorOrAbove * 100
moddat$per_white_all <- moddat$per_white_all * 100
moddat$OOH_share <- moddat$OOH_share * 100
moddat$per65o <- moddat$per65o * 100
moddat$per65o <- moddat$per65o * 100
moddat$teachShareofVoters <- moddat$teachShareofVoters * 100
moddat$member_delta_per <- moddat$member_delta_per * 100
moddat$districtwide <- factor(moddat$districtwide)
moddat <- na.omit(moddat)
dd <<- datadist(moddat)
options(datadist="dd")


fiscalModel <- glm(contest2 ~ balance_member_lag + millrate * NonSDMill + 
                     overridePass + debtPass + refInPlace + median_incomeLOG + 
                     millrate_delta + VAP_adjLOG + 
                     DEBT_ATTEMPT_CUMUL93 + eqv_member + teachSalDiff +
                     OVERRIDE_ATTEMPT_CUMUL93, 
                   data = moddat, family = 'binomial')


@

Some text

<<fiscalModPP>>=
fiscalModelPP <- bglmer(contest2 ~ balance_member_lag + millrate * NonSDMill + 
                     overridePass + debtPass + refInPlace + median_incomeLOG + 
                     millrate_delta + VAP_adjLOG + 
                     DEBT_ATTEMPT_CUMUL93 + eqv_member + teachSalDiff +
                     OVERRIDE_ATTEMPT_CUMUL93 + (1|year), 
                   data = moddat, family = 'binomial', 
                   cov.prior = wishart)

fiscalModelPP2 <- bglmer(contest2 ~ balance_member_lag + millrate * NonSDMill + 
                     overridePass + debtPass + refInPlace + median_incomeLOG + 
                     millrate_delta + VAP_adjLOG + 
                     DEBT_ATTEMPT_CUMUL93 + eqv_member + teachSalDiff +
                     OVERRIDE_ATTEMPT_CUMUL93 + (1|distid), 
                   data = moddat, family = 'binomial', 
                   cov.prior = wishart)

fiscalModelPP3 <- bglmer(contest2 ~ balance_member_lag + millrate * NonSDMill + 
                     overridePass + debtPass + refInPlace + median_incomeLOG + 
                     millrate_delta + VAP_adjLOG + 
                     DEBT_ATTEMPT_CUMUL93 + eqv_member + teachSalDiff +
                     OVERRIDE_ATTEMPT_CUMUL93 + (1|distid) + (1|year), 
                   data = moddat, family = 'binomial', 
                   cov.prior = wishart)


@

<<modelcomparisonD, eval=FALSE>>=
politicModel <- glm(contest2 ~ NEW_SUP + turnoutLag1 + partyDivision + 
                      overrideQues +  debtPass + debtQues + 
                      SUP_TURNOVER_PRIOR_YEAR +
                      median_incomeLOG + fallTurnout + overrideYesPer, 
                    data = dist_turn, family = "binomial")

mod1 <- glm(contest2 ~ VAP_adjLOG + NEW_SUP + turnoutLag1 +partyDivision +
              PerBachelorOrAbove + per_white_all+
              OOH_share + median_incomeLOG + ADMIN_SHARE + 
              per65o + ADJ_MEDIAN_SALARY_TEACHlog + refInPlace+
              NonWhitePublicPupilPer *per_white_all+ overrideQues +
              millrate*NonSDMill + 
              overridePass + debtPass, 
            data = dist_turn, family = "binomial")
summary(mod1)


confusion.glm(dist_turn, glm(factor(contest2) ~ log(VAP_adj) + NEW_SUP + turnoutLag1 +fallTwoPartyShareDem +
              PerBachelorOrAbove + OOH_share + log(median_income) + ADMIN_SHARE + 
              NonWhitePublicPupilPer + overrideQues + millrate*NonSDMill, 
            data = dist_turn, family = "binomial"))
#moddat <- na.omit(moddat)
# Filter out extreme values

## Tax model -- voters are driven by tax concdrns
## Politics model -- voters are driven by political ideology
## Policy model -- teacher salary and benefits? 

tax_model <- glm(contested2 ~  millrate + cum_attptsD + overlevy_ind_lag +
                    per_white_all + levy_chg + log(Population18O) + 
                   ref_share +
                   balance_member_lag +  median_income + fyear, 
                 data=SBELEC[!is.na(SBELEC$contested2Lag1), ], 
                 family=binomial("logit"))

#summary(tax_model)
#sigma1 <- sum(residuals(tax_model, type = "pearson")^2) / df.residual(tax_model)

poli_model <- glm(contested2 ~ contested2Lag1 + primary2Lag1 +
                    cum_attptsD + per_white_all + per65o + log_politicaldivide +
                     fallTwoPartyShareDem +fallTurnout+
                    PerBachelorOrAbove +
                    median_income + log(Population18O) + fyear, 
                 data=SBELEC[!is.na(SBELEC$contested2Lag1), ], 
                 family=binomial("logit"))

#summary(poli_model)
SBELEC$average_fringe[SBELEC$average_fringe==0] <- 0.1
poly_model <- glm(contested2 ~ log(avg_salary) + log(average_fringe) + 
                    avg_total_exp + log(Population18O) + 
                    median_income +member_delta + total_attempts + fyear, 
                   data=SBELEC[!is.na(SBELEC$avg_salary), ], 
                  family = binomial("logit"))

#summary(poly_model)

uber_model <- glm(contested2 ~ log(dv_r) + avg_salary + average_fringe + 
                    avg_total_exp + log(Population18O) + contested2.lag1 +
                    median_income +member_delta + total_attempts + 
                    primary2.lag1 + cum_attptsD + perwhite + Per65over + 
                   attemptsD.lag1 + log_politicaldivide + PerBachelorOrAbove +
                    millrate + overlevy_ind_lag + toprepshare +
                    winshare.lag1 +
                    levy_chg + balance_member_lag + fyear, 
                   data=SBELEC[!is.na(SBELEC$contested2.lag1), ], 
                  family = binomial("logit"))
                   

makeROCdf <- function(model, name){
  predicted <- predict(model)
  prob <- prediction(predicted, model$model$contested2)
  tprfpr <- performance(prob, "tpr", "fpr")
  tpr <- unlist(slot(tprfpr, "y.values"))
  fpr <- unlist(slot(tprfpr, "x.values"))
  roc <- data.frame(tpr, fpr)
  roc$mod <- name
  return(roc)
}

roc <- makeROCdf(tax_model, "tax")
roc2 <- makeROCdf(poli_model, "politics")
roc3 <- makeROCdf(poly_model, "policy")
roc4 <- makeROCdf(uber_model, "uber")

roc <- rbind(roc, roc2); rm(roc2)
roc <- rbind(roc, roc3); rm(roc3)
roc <- rbind(roc, roc4); rm(roc4)
@

<<rocplot1, echo=FALSE, fig.cap="ROC Curves for 4 Models of Election Contestation in Wisconsin School Boards", fig.keep='last'>>=
ggplot(roc) + geom_smooth(aes(x = fpr, y = tpr, color=mod), 
                          se=FALSE,size= I(1.1)) + 
   geom_abline(intercept = 0, slope = 1, colour = "gray") + 
   ylab("Sensitivity") + 
   xlab("1 - Specificity") + 
  coord_cartesian(xlim=c(0, 1), ylim=c(0,1)) + theme_bw() + 
  labs(title = "Comparing Models of Candidate Contestation in School Board Elections", 
       color = "Model")

@

When understanding model fit for binomial outcomes, the receiver operating characteristic, or ROC, provides a standard metric for performance \citep{hanley, vivo, zwieg}. 
Of particular value is the area-under-the-curve. This metric tells us how well a 
model performances across the range of thresholds. As we are modeling a discrete 
event -- whether or not a challenger emerges in a school district board election -- 
it makes most sense to judge model fit using a measure of how well the model 
accurately classifies elections into types -- contested and uncontested. 

In Figure \ref{fig:rocplot1} it is clear that policy and tax variables have less 
explanatory power than politics and the full model. The x-axis represents the 
false-alarm rate, or uncontested elections that would be classified as contested 
elections. The y-axis represents the true contested elections that would be 
correctly classified. Our politics model and our uber model both exhibit superior 
performance for a lower rate of false-alarms than the policy or tax measures. 

This is not evidence that taxation and compensation policy do not matter to school 
districts or in determining board elections. The goal here is to simply compare 
the explanatory power of different classes of descriptive predictors available 
statewide over time for all school districts in order to understand which, if any, 
macro-level measures that are publicly reported provide strong evidence of a 
school district having a contested election. 

A table of likelihood ratio tests shows the same result:

<<anovatable1, results='asis'>>=
print(xtable(anova(tax_model, poly_model, poli_model, uber_model, test="LRT")), 
      include.rownames=TRUE)
@

This provides some evidence that school district elections are driven by political 
factors -- both local and cross-district -- more so than the measures of financial 
and policy concern that we have available at a statewide level. As the task is to 
explain school district elections using consistent and statewide available data, 
it appears that measures of political climate in the school district are particularly 
well suited to the task. 

Model tables

<<modelsplot, fig.cap="Comparing Coefficients for the 4 Models of School Board Election Contestation", fig.height=9>>=

plotcoefs = c("total_attempts", "avg_total_exp", "log(politicaldivide)", 
          "Per65over", "average_fringe", "avg_salary", "log(dv_r)", 
          "PerBachelorOrAbove", "toprepshare", "attemptsD", "Per65over", 
          "contested2.lag1", "primary2Primary", "median_income",
          "balance_member_lag", "log(Population180)", "levy_chg", 
          "perwhite", "overlevy_ind_lag", "cum_attptsD", "millrate")


multiplot(poli_model, tax_model, poly_model, uber_model, intercept=FALSE, 
          coefficients = plotcoefs, sort = c("magnitude"), 
          title = "Change in Probability of A Contested Election") + 
  coord_trans(x = "asinh") + 
  theme_dpi() + theme(legend.position = "bottom")


@

Figure \ref{fig:modelsplot} shows the coefficients and their standard errors 
plotted for the four models.\footnote{Graph made using the excellent \texttt{coefplot} package for R along with \texttt{theme\_dpi} theme for \texttt{ggplot2} provided 
in the \texttt{eeptools} package \citep{eeptools, coefplot, gg}.} The scale is 
exaggerated around 0 to allow for presentation of smaller coefficient sizes and 
to be able to distinguish them from 0. 

From this we can see that the comprehensive model provides point estimates very 
close to the estimates in the corresponding topic models. We can also see that 
most of the effects are very low - the coefficients reported here are logistic 
coefficients - with a few pointed exceptions. 

Let's look at within district variability. We can do this by fitting partial pooling 
models using a random-intercept framework of \citet{gelhill} using the \texttt{lme4} 
package in R \citep{lme4, cran}. This method will allow us to estimate changes in 
trends within districts and separate between and within district variance. 

The model estimated follows the form:

\begin{align*} 
\Pr_{CE_{tj}} &= \alpha_{tj} + \beta X_{tj} + \gamma_{j} + \epsilon   \\ 
\gamma_{j} &=  \alpha_{j} + \zeta Z_{j}
\end{align*}

Here the $\gamma_{j}$ terms represent independent intercepts for each school 
district as predicted by $Z_{j}$, a vector of school district characteristics 
that are time invariant. $X_{tj}$ is a vector of time variant school district - 
election cycle characteristics, some of which may be lagged. In the mixed-effect 
framework the $\gamma_{j}$ are assumed to be drawn from a normal distribution that 
is explained by the linear combination of $\alpha$ and $\zeta$. 

<<descrmixedeff, eval=FALSE>>=

# Alternative is to model number of cnadidates as poisson
# 
# SBELEC$candidatesDV <- SBELEC$candidates - SBELEC$minorcand - SBELEC$winners
# SBELEC$candidatesDV <- ifelse(SBELEC$candidatesDV > -1, SBELEC$candidatesDV, 0)
# # Investigate why negative numbers come up here

library(lme4)

SBELEC$distidF <- factor(SBELEC$distid)
mermod1 <- glmer(contested2 ~  log(dv_r) +   
    avg_total_exp + log(Population18O) +  median_income + 
      cum_attptsD + attemptsD +
    perwhite +  log_politicaldivide + 
    millrate + overlevy_ind_lag +  
     fyear + (1 + log_politicaldivide|distidF), 
                 data=SBELEC[SBELEC$year > 2004, ], family="binomial")

nullmermod <- glmer(contested2 ~  log(dv_r) +   
    avg_total_exp + log(Population18O) +  median_income + 
      cum_attptsD + attemptsD +
    perwhite +  log_politicaldivide + 
    millrate + overlevy_ind_lag +  
     fyear + (1|distidF), 
                 data=SBELEC[SBELEC$year > 2004, ], family="binomial")


# summary(mermod1)
# rr1 <- ranef(mermod1, condVar=TRUE)
# 
# confint(mermod1, method="Wald")
#dotplot(ranef(mermod1, condVar=TRUE))
@

Here is some text about the within district variation. 

Not sure which specification to use yet. 






\clearpage
\subsection{Causal}

To test the effect of the passage of Act 10 on participation in school board elections, 
we fit a simple longitudinal model of school districts. In this model, school district 
elections are treated as repeated measures, nested within the school districts 
themselves. Using this repeated measures framework allows us to estimate cross 
district and within district effects. Act 10 represented a statewide intervention 
in the relative power of school boards in Wisconsin by giving school boards much 
more authority and control over the compensation of teachers and staff, and by 
dramatically restricting the ability of the districts' employees to bargain over 
wages, working conditions, and benefits. This shift in power, in essence, raised 
the stakes for school board elections substantially and should have increased the 
overall contestation of school board elections. 

To evaluate this, a series of models of school board election contestation over 
time are fit to attempt to detect changes in contestation levels relative to the 
levels of contestation observed in school districts prior to the passage of 
Act 10. If levels of contestation increase after the introduction of Act 10, even 
after controlling for the factors that influenced this above, it would be strong 
evidence that the statewide policy lever pulled by Act 10 did spur a response 
from candidates in terms of increasing the attractiveness of school board seats. 


<<candidatedescriptives3, eval=FALSE, echo=FALSE>>=

# Base model with simple treatment dummy
# Time model with linear time for Act 10
# Longitudinal within district using lmer
# add dummies for years

SBELEC$pres_primary <- 0
SBELEC$pres_primary <- ifelse(SBELEC$year == 2008, 1, 0)
SBELEC$pres_primary <- ifelse(SBELEC$year == 2012, 1, SBELEC$pres_primary)


trtmnt_model <- bayesglm(contested2 ~  millrate_delta + contested2Lag2 +
                      RecallPolarization*treatment + GovTurnout_recall +  
                       log(Population18O) + treatment, 
                 data=SBELEC[SBELEC$year >= 2010 & SBELEC$year < 2013, ], 
                 family="binomial")

simple_model <- bayesglm(contested2 ~  millrate + contested2.lag1 +
                      walkerdivide + recallturnout +  pres_primary +
                       log(Population18O) + time + I(time^2), 
                 data=SBELEC[SBELEC$year >= 2009 & SBELEC$year < 2013, ], 
                 family="binomial")

summary(simple_model)

library(lme4)
simple_lmer <- glmer(contested2 ~ treatment + pres_primary + 
                       millrate + log(Population18O) +
                       contested2.lag1 + 
                       (1 + sqrt(walkerdivide) + recallturnout | distid), 
                     data=SBELEC[SBELEC$year >=2008 & SBELEC$year <2013, ], 
                     family = "binomial")

summary(simple_lmer)


dotplot(ranef(simple_lmer, condVar=TRUE))
##### 
# LME4

# 
# blahmod <- glmer(contested2 ~ log(dv_r) + avg_salary + average_fringe + 
#                     log(Population18O) + walkerdivide +
#                     median_income + primary2 + perwhite + Per65over + 
#                    attemptsD +
#                     millrate + overlevy_ind_lag + fyear+ (1|distid), 
#                  data = SBELEC, family = binomial("logit"))
# 
# 
# 
# blahmod2 <- glmer(contested2 ~ log(dv_r) + avg_salary + average_fringe + 
#                     log(Population18O) + 
#                     median_income + primary2 + perwhite + Per65over + 
#                    attemptsD +
#                     millrate + overlevy_ind_lag + fyear + 
#                     (1 + walkerdivide|distid), 
#                  data = SBELEC, family = binomial)
# 
# dotplot(ranef(blahmod2, condVar=TRUE))
# 
# anova(blahmod, blahmod2)

@

\section{Conclusions}

School board elections are not marked by much contestation. 


\section{Tables}

<<modeltables, results='asis'>>=
stargazer(tax_model, poli_model, poly_model, uber_model, 
          omit = "fyear", font.size="scriptsize", label = "tab:descrmodels", 
          title = "Comparing 4 Models of Contestation in School Board Elections", 
          column.labels = c("Taxation Model", "Politics Model", "Policy Model", 
                            "Overall Model"))
@

