\chapter{Describing Wisconsin School Board Elections}
\label{chap:wisco}
\chapterstyle{deposit}


<<rsetup, results='hide', echo=FALSE, message=FALSE, warning=FALSE>>=
opts_chunk$set(fig.width=8, fig.height=6, message=FALSE, error=FALSE, 
               fig.path="../../phd_figs/chap2-",
               warning=FALSE, echo=FALSE, dev=c('pdf', 'png'))

setwd("../../")
source("data/dataAssemble.R")
# source("data/dataMerge.R")
source("R/thesis_functions.R")
load("data/cache/DataMergeVAP.rda")
library(plyr)
library(eeptools)
library(scales)
library(xtable)
library(data.table)
options(xtable.include.rownames = FALSE, xtable.table.placement = "ht")
@

\section{The Wisconsin Case}

This chapter describes school board elections in Wisconsin from 2002-2012. 
Wisconsin has many attributes that make it representative of the Midwest, if not 
the country. Its is located in the Midwest and ranks 23rd among U.S. states in 
terms of total area, 20th in terms of population size with 5.7 million residents, 
and has 424 school districts.\footnote{All facts from US Census.} Wisconsin has 
become a crucial swing state exhibiting a close split between Republican and 
Democratic voters in presidential politics. 

One differentiating factor for Wisconsin is that like many other states in the 
Midwest it grants much of the authority in school district decision making to 
local school boards -- a so-called ``local control'' state. This is also why 
Wisconsin, in contrast to Southern states, has such a large number of 
school districts serving relatively small populations over relatively small areas. 
Prior studies of school boards like those of \citet{RefWorks:311,RefWorks:214} have 
taken place in states with larger school districts and more centralized state 
control. Thus, Wisconsin serves as a good exemplar for other ``local control'' 
jurisdictions where school boards have more authority relative to the state 
government. 

Another advantage of selecting Wisconsin is the comparative advantage
I have had in gathering the necessary data to study a substantial proportion of the 
school board races within the state.\footnote{For details on this, see the 
Appendix \ref{app:data}.} With close relationships to policymakers in my role 
as a research analyst at the SEA I have been able to collect a diverse set of 
data on Wisconsin school districts. A final advantage is the ability 
to test theories of the linkage between school board and state level politics thanks 
to the dramatic shock to education policy that accompanied the election of Wisconsin 
Governor Scott Walker in 2010. Taken together, these advantages mean that the in-depth 
study of school board elections across the entire K-12 educational system in Wisconsin 
can provide a new perspective on theories of candidate emergence in local elections, 
voter turnout in non-partisan off-cycle local races, and federalist linkages between 
state and local governments. Such an in-depth study of a single system can, then, 
build a foundation on which to advance the study of local governance more broadly 
\citep{RefWorks:192}. 

In this chapter I address the unique case of Wisconsin by providing a descriptive 
overview of the legal, demographic, and historical landscape for school board races within 
the state. I start by describing the ways in which the laws governing 
school board races vary from more familiar legislative races. Next, I describe the data 
I have collected on school board election results in detail and provide descriptive 
statistics of the frequency of incumbency challenges and open races, voter turnout, 
and the socio-demographic diversity of the constituencies served by Wisconsin school 
boards. This overview serves as the groundwork for the three subsequent chapters 
which examine how well theories of political engagement explain candidate emergence and voter 
turnout in school board elections, as well as any subsequent policy shifts. 

\section{Background and Legal Basis of Wisconsin School District Elections}
\label{sec:wiscolaw}
This project is a comprehensive study of the patterns in school board elections 
across an entire state over multiple years. Before examining the patterns that 
emerge both within and between school districts, it is important to first describe 
the data available on school board elections and the legal procedure under which 
elections are conducted. This helps lay the groundwork for the democratic potential 
of school boards by explaining what the legal barriers are for candidates and voters 
to participate in school board election. Wisconsin, like many other Midwest states, is a 
local control state. This means that Wisconsin school districts have revenue 
authority independent of municipalities and counties, and are governed by 
a non-partisan elected board independent of other local government 
bodies. The independence of Wisconsin school districts is established in the 
state constitution and through state law (WI Const. art. X, \S 3 and Wis. Stat 120.10). 

This independence gives Wisconsin school districts comparatively considerable power and authority. 
Importantly, school boards administer their own elections and retain their own 
election records. This represents a serious barrier to studies of school board 
elections due to the burden associated with collecting and organizing school board 
election results from over 420 independent administrative entities. This is why previous studies of 
school boards have tended to focus on candidates, random samples of school boards, 
or on states with county-wide school boards such as North Carolina and Georgia 
\citep{RefWorks:311,RefWorks:210,RefWorks:214}. 

A benefit of the independence of Wisconsin school boards is the opportunity for study 
their organizational diversity presents compared to other states. While Wisconsin school 
board elections are held consistently on the same dates across 
the state, during the spring non-partisan election cycle, the size and distribution 
of board seats is largely locally determined. The spring primary election is the 
third Tuesday in February, and the spring general election is the first Tuesday 
in April (Wis. Stat \S 120.06). Wisconsin school boards must have between 3 and 9 
members with some exceptions made for boards of 11 members (Wis. Stat \S 120.01). 
Board member terms are not consistent across school boards, though 3 year terms are 
the most common with limited exceptions for terms of 1 or 2 years (Wis. Stat \S 120.06 (3)). 
Board members are elected by a plurality and must be residents of the district to 
be eligible for office (Wis. Stat \S 120.06 (2) (a)). All candidate verification, 
ballot preparation, and election announcement is the responsibility of the school district 
clerk, in practice a job often managed by district administrators 
(Wis. Stat \S 120.06 (8)). Primary elections occur if there are more than 
twice as many candidates as there are members to be elected (Wis. Stat \S 120.06 (7) (b)). 

School boards also have flexibility to apportion their seats in different ways 
ranging from a board of 3-9 members each representing the entire district, to a board 
of 3-11 members each representing either a specific region of the school district or 
the entire district. Figure \ref{fig:boardsize} shows the sizes of school boards 
in Wisconsin over the time period being studied. This is calculated using a database 
of school board members provided by the Wisconsin Association of School Boards (WASB).
\footnote{There was one anomaly with this data where school board seats were under reported 
in the 2007 data due to a reporting error. As a result, I have added one to number of 
seats for all school districts in the 2007 data.} The only restriction on the way 
seats are allocated is that the plan is proposed with a petition by a threshold 
of voters and passed by the board at an annual meeting or through an election 
(Wis. Stat \S 120.02 (2)).

%TODO: Calculate number of voters per board seat

\begin{table}[h!]
\begin{center}
\caption{Wisconsin Election Dates}
\label{tab:elecdates}
\begin{tabular}{| p{.3\textwidth} | p{.6\textwidth} |}
\hline
\textbf{Election}  & \textbf{Date}  \\ \hline
Spring Primary  & Third Tuesday in February  \\ \hline
Spring General &  First Tuesday in April  \\ \hline
Fall Primary & Second Tuesday in August \\ \hline
Fall General & First Tuesday in November\\ \hline
\end{tabular}
\end{center}
\end{table}

My study distinguishes itself from previous studies with 
its use of official election results provided directly by school boards to determine 
the results of the elections. In Wisconsin, school districts are the official holder of all school district election results. This means that official school board election records are maintained solely by 
school districts themselves and gathering school board election results in Wisconsin 
requires requesting records from individual school districts.\footnote{See Appendix 
\ref{app:data} and the Appendix \ref{app:log} for details on the request process.} 
This challenge is a key barrier to the study of school board elections; though 
school boards are required by law to retain these records, the record keeping is 
often incomplete, unclear, or confusing (Wis. Stat \S 120.06 (8) (g)).
\footnote{A few enterprising county clerks have collected school board election 
results and made them available online, however, these can be incomplete 
by only including the precincts that are within the county. They also are not official. 
\citep[personal communication with][]{clerk1}.} In order to gather these records, a 
request was e-mailed to the school district administrator in each of Wisconsin's 
424 school districts in January of 2013. Three follow up waves were conducted throughout 
2013, and at the end of the collection period, \Sexpr{iNum(length(unique(dat$distid)))} 
districts responded with records. The official and preferred 
records of the election requested included the Statement of the Board of Canvass 
and the Certificate of the Board of Canvass. These two documents are legally mandated 
for each school board election and certify the winner for each school board seat, 
as well as the votes cast for each candidate. When these were unavailable, a less 
official record such as a tally sheet from the election or a vote count spreadsheet 
was requested. Full details on the data collection process can be found in Appendix \ref{app:data}. 
These records were then transcribed a database for analysis.

The median district provided 
\Sexpr{iNum(median(ddply(races, .(distid), summarise, out = length(unique(year)))[, 2]))} 
years of records.\footnote{While each district was requested to provide the maximum amount of records legally required to be retained, ten years, many districts were unable to locate complete 
records going this far back.} Figure \ref{fig:yeargraph} shows the number of districts providing 
records in each year. Overall, records were provided on \Sexpr{iNum(nrow(races))} school 
board races involving \Sexpr{iNum(nrow(cand))} unique candidates in the state. 
For each election the votes received by each candidate was recorded, as well as 
whether the candidate won, was an incumbent, was a repeat candidate in the school 
district, or was a minor candidate -- receiving fewer than 20 total votes. For each 
race, whether the candidate was running for district wide or regional seat was 
also recorded. 

Using the names, vote totals, and winners from each school board election allows 
for the construction of measures of the number of candidates in each election 
cycle, the number of contested seats, the level of voter participation, and other 
metrics of electoral activity at the school board level. Importantly, because the 
data were collected for several years in each district, time-variant trends can be 
explored. 


<<boardsize, echo=FALSE, fig.cap="Number of Seats Per District in 2012", fig.height=4.5>>=
setwd("../../")
boardsize <- read.csv("data/cache/SchoolBoardRosterVerification.csv", colClasses = "character")

plotdf <- ddply(boardsize, .(year, agency_short_name), summarize, 
                out = length(unique(full_name)))

# # Off by 1 error in data from DPI for year 2007
# plotdf$out[plotdf$year == 2007] <- plotdf$out[plotdf$year == 2007] + 1
# 
# qplot(year, out, data = plotdf, geom = 'boxplot') + theme_classic() + 
#   labs( x= "Year", y = "Board Seats Per District", 
#         title = "Distribution of Number of Seats Per District") + 
#   scale_y_continuous(breaks = c(3:11))

ggplot(data = plotdf[plotdf$year == 2012,], aes(x=factor(out))) +
  stat_bin(bindwidth = 1, geom='histogram') +
    stat_bin(binwidth=1, geom="text", aes(label=..count..), 
           hjust = 1, vjust = -1, size = 4) +
  scale_y_continuous(limits = c(0, 250)) +
  theme_classic() + 
  labs(x = "Number of Board Seats", y = "Count of Districts") 

@

<<yeargraph, echo=FALSE, fig.cap="Number of Districts Providing Records by Year", fig.height=4.5>>=
plotdf <- ddply(races, .(year), summarize, out = length(unique(distid)))

qplot(year, out, data = plotdf, geom = 'bar', stat = 'identity') + theme_dpi() + 
  geom_text(vjust = -.2, aes(label = out)) + 
  labs(x = "Election Year", y = "Number of Districts", 
       title = "District Providing Usable Records by Year") + 
  scale_y_continuous(limits = c(0, 320))
@



<<racesgraph, echo=FALSE, fig.cap="Number of Races Provided by Districts. Red line indicates the median.">>=
plotdf <- ddply(races, .(distid), summarize, years = length(unique(year)), 
                races = length(year))

qplot(races, data = plotdf, fill = I("gray80"), color = I("black")) + theme_dpi() + 
  geom_vline(xintercept = median(plotdf$races), color = I('red'), size=I(1.1), 
             linetype = 2) + 
  labs(x = "Number of School Board Races", y = "Count of Districts", 
       title = "Number of Race Records Provided by Each District") + 
  coord_cartesian(ylim = c(0,150), xlim= c(0,40))
@



<<continuityinrecords, echo=FALSE, results='hide'>>=
continuity <- as.matrix(table(races$distid, races$year))
continuity <- continuity[, -14]

# Let's look at continuity from 2007 to 2012

continuity <- continuity[, 8:13]

@

The good news is that the most crucial period of the sample, from 2007 to 2012, is 
the period with the most complete set of records. The mean district provided records on 
\Sexpr{prettyNum(mean(plotdf$races), big.mark=",", digits = 3)} school 
board races. Figure \ref{fig:racesgraph} shows the number of races 
provided by each school district, with the median highlighted by a red vertical line. 
\Sexpr{iNum(table(rowSums(continuity) >5)[[2]])} districts had 
a race in each year between 2007 and 2012, while \Sexpr{iNum(table(rowSums(continuity) >5)[[1]])} 
did not. \footnote{In some cases a district like Milwaukee may only hold board elections 
on an every other year cycle.} I distinguish these cases from others by verifying 
the absence of a ballot for school board, as opposed to the absence of records. 
 
\clearpage
\section{The Diversity of Wisconsin School Districts}

The authority given to school districts in Wisconsin to determine their own
electoral 
rules and structure make Wisconsin a useful case in exploring the variation in 
school board electoral participation across contexts. In addition to the legal 
variation in electoral rules across school districts, Wisconsin school districts 
also vary widely in size, wealth, tax rates, and demographics. In order to 
explore this diversity and to demonstrate the representativeness of the school 
districts that responded to the request for records, I now explore several aspects 
of Wisconsin school districts. 

\subsection{Comparing the Sample to the Population}

<<samplecomparisonsPREP, results='hide'>>=
rm(list=ls())
setwd("../../")
source("data/dataAssemble.R")
# load("data/cache/DataMergeVAP.rda")
source("data/cleanandprep_ABOUTWISCO.R")

SAMPSIZE <- length(unique(SBELEC$distid))
mysub <- FULLDAT[FULLDAT$year == 2011, ]
mysub <- mysub[mysub$distid != 3619, ]
selectVars <- c("TOTPOP", "member_aidyear", "econ_disadv_per", 
                "millrate", "toprepshare", "PerBachelorOrAbove", 
                "per_white_all","ADJ_MEDIAN_SALARY_teachers", 
                "AVERAGE_FRINGE_teachers", 
                "median_income", "OOH_share", "balance_member_lag", 
                "teacherpupil_ratio", 
                "eqv_member")

rnames <- c("Total Population", "Membership", 
            "% FRL", "Millrate", "% Republican", "% Bachelor+", "% White Pop.","Avg Teach. Sal. ($)", 
            "Avg Teach. Fringe ($)", "Median Income ($)", "% Owner Occupied", 
            "Acct. Balance per Member", "Teacher-Pupil Ratio", "Property Wealth per Member ($100k)")

a <- round(t(aggregate(mysub[, selectVars], 
                  by = list(sample = mysub$sample), mean, na.rm=TRUE)), digits=2)
b <- round(t(aggregate(mysub[, selectVars], 
                  by = list(sample = mysub$sample), sd, na.rm=TRUE)), digits=2)

a <- as.data.frame(a); names(a) <- c("Non-Sample (Mean)", "Sample (Mean)")
b <- as.data.frame(b); names(b) <- c("Non-Sample (SD)", "Sample (SD)")

ab <- as.data.frame(cbind(a[,2], b[,2], a[,1], b[,1]))
ab[2, ] <- round(ab[2,])
ab[3, ] <- round(ab[3,])
ab[6, ] <- round(ab[6, ] *100)
ab[7, ] <- round(ab[7, ] *100)
ab[8, ] <- round(ab[8, ] *100)
ab[12, ] <- ab[12, ] *100
ab[15, ] <- ab[15, ] *.00001
names(ab) <- c("Sample (mean)", "Sample (SD)", "Out of Sample (mean)", "Out of Sample (SD)")
row.names(ab) <- c("Var", rnames)
@

<<samplecomparisons, results='asis'>>=
tabDigits <- c(0,0,2,2,1,1,1,0,0,0,0,0,2,2)
tabDigitsMat <- cbind(rep(0, 14), tabDigits, tabDigits, tabDigits, tabDigits)
tabDigitsMat <- as.matrix(tabDigitsMat, ncol = 5)
sampleStats <- xtable(ab[-1,], label="tab:samplecomp", caption = "Comparing school districts that provided board election results to those that did not and are not included in the study. Data from the 2010-2011 school year. Table excludes 
                      Milwaukee Public Schools.", digits = tabDigitsMat)

align(sampleStats) <- c('p{1.5in}','p{.8in}','p{.8in}','p{.8in}','p{.8in}')

print(sampleStats, 
      format.args = list(big.mark=",", decimal.mark = "."), 
      include.rownames=TRUE, size="scriptsize")

rm(a, b, ab)
@

% Describe above table

As shown in Table \ref{tab:samplecomp}, there is little difference between districts 
in and out of the sample for the year 2011 on a range of measures of school district 
characteristics. The groups have similar levels of student 
economic disadvantage as measured by eligibility for free and reduced price lunch and 
similar proportions of minority students in their schools. 
Their communities have similar levels of income, owner occupied housing, and levels 
of education. Teacher salary and fringe benefit rates are also nearly identical, as 
is the teacher-pupil ratio.\footnote{2011 was selected as an exemplar year, but 
the pattern holds for all available years from 2007-2012, which comprise the focus 
of this study.} The districts also look similar on their partisanship in presidential 
and gubernatorial elections.

The biggest discrepancy is that sample districts tend to be larger on average than 
out-of-sample districts in terms of student membership. This is no surprise as the largest 
Wisconsin school districts publish their election results online, making them among 
the easiest to obtain. This makes my coverage of the largest Wisconsin school 
districts perfect, while my coverage of the smallest Wisconsin school districts 
is lower. The sample districts tend to have slightly smaller account balances or 
district savings accounts on a per pupil basis which is likely related to their larger size. 
Finally, sample districts tend to have less property value per member, or taxable 
assets to raise revenue from, owing to the slightly higher populations of sample 
districts and the inclusion of all urban areas.\footnote{Property value is measured 
by equalized property value, known as EQV, which is used in the state school funding 
formula to determine state equalization aid for school districts.} All of these differences, however, 
are within one standard deviation of the mean from one another and do not represent 
a significant deviation either statistically or substantively. 

\subsection{Exploring the Biggest and Smallest Jurisdictions}

Wisconsin, like other states with independent school districts, has a great diversity 
in school district size and demographics. To illustrate the wide 
array of communities that school boards in Wisconsin represent, I present Tables 
\ref{tab:small5} and \ref{tab:big5} describing the five smallest and five largest 
school districts in Wisconsin and how 
they compare on the variables from Table \ref{tab:samplecomp}. Table \ref{tab:small5} 
shows that the smallest 
school districts in Wisconsin have fewer than 100 students and fewer than 1,000 
residents. Smaller districts also tend to be much higher percentage Republican, 
less low-income, whiter, and have less disparity between the average teacher 
salary and the median income in the community. Contrast this with Table \ref{tab:big5} 
where the student population is 200 to 300 times larger than the smallest districts, 
the electorate is much more Democratic, student poverty is higher, and teacher 
salaries and median incomes are more divergent. 

<<small5, results='asis'>>=

tabDigits <- c(0,0,2,2,1,1,1,0,0,0,0,0,2,2)
tabDigitsMat <- cbind(rep(0, 14), tabDigits, tabDigits, tabDigits, tabDigits,tabDigits)
tabDigitsMat <- as.matrix(tabDigitsMat, ncol = 6)
tmp.mat <- head(mysub[order(mysub$member_aidyear), c("legal_name", selectVars)], 5)
row.names(tmp.mat) <- tmp.mat[,1]
tmp.mat <- tmp.mat[,-1]
small5 <- as.data.frame(t(tmp.mat))
row.names(small5) <- rnames
small5[5, ] <- small5[5, ] * 100
small5[6, ] <- small5[6, ] * 100
small5[7, ] <- small5[7, ] * 100
small5[11, ] <- small5[11, ] *100
small5[14, ] <- small5[14, ] * .00001

small5x <-xtable(small5, label="tab:small5", caption = "Some attributes of Wisconsin's 5 smallest school districts. Data 
             from the 2010-2011 school year.", digits = tabDigitsMat)

align(small5x) <- c('p{1.25in}','p{.8in}','p{.8in}','p{.8in}','p{.8in}', 'p{.8in}')

print(small5x, 
      format.args = list(big.mark=","), include.rownames=TRUE, size="scriptsize")
rm(small5)
@

<<big5, results='asis'>>=
tmp.mat <- head(mysub[order(-mysub$member_aidyear), c("legal_name", selectVars)], 5)
row.names(tmp.mat) <- tmp.mat[,1]
tmp.mat <- tmp.mat[,-1]
big5 <- as.data.frame(t(tmp.mat))
row.names(big5) <- rnames
big5[5, ] <- big5[5, ] * 100
big5[6, ] <- big5[6, ] * 100
big5[7, ] <- big5[7, ] * 100
big5[11, ] <- big5[11, ] *100
big5[14, ] <- big5[14, ] * .00001

big5x <- xtable(big5, label="tab:big5", caption = "Some attributes of Wisconsin's 5 largest school districts. Data 
             from the 2010-2011 school year.", digits = tabDigitsMat)

align(big5x) <-  c('p{1.25in}','p{.8in}','p{.8in}','p{.8in}','p{.8in}', 'p{.8in}')

print(big5x, 
      format.args = list(big.mark=","), include.rownames=TRUE, size="scriptsize")

@

The larger districts shown in Table \ref{tab:big5} are representative of the 
kind of local governments that political scientists have typically studied -- 
large urban centers. This study will include such districts, but also include over 
290 smaller jurisdictions which are more representative of the vast majority of 
school board offices and school board elections across the country 
\citep{RefWorks:321}. 

<<reloadworkspace, results='hide'>>=
rm(list=ls())
setwd("../../")
source("data/dataAssemble.R")
source("data/cleanandprep_ABOUTWISCO.R")
source("R/thesis_functions.R")
options(xtable.include.rownames = FALSE, xtable.table.placement = "ht")

plotdf <- ddply(races, .(distid), summarize, years = length(unique(year)), 
                races = length(year))
@


\clearpage

\subsection{General Elections, Primaries, and Special Elections}

General elections for school board members follow the schedule described in Section 
\ref{sec:wiscolaw}. However, for this project, I requested records for \emph{all} elections 
for school board office including school board member primaries and special elections. 
School board primaries occur when the number of candidates exceeds twice 
the number of seats open in a race.\footnote{In Wisconsin first class cities, 
only Milwaukee is a first class city during the period of study, a primary must be held whenever there are more than two candidates for 
a race. Wis. Stat \S 8.11 (2m)} Special 
elections occur either if a vacancy occurs in a specific window in a first class 
city, or if a candidate is recalled under Wis. Stat \S 9.10 (1) (a) 
which states that a petition for recall must be signed by electors equal 
in number to at least 25\% of the votes cast for the office of President of the United 
States at the last election within the same jurisdiction.\footnote{
A special election is also required to fill a vacancy for board of school directors 
in the Milwaukee Public School system (MPS) [Wis. Stat \S 8.50 (intro.)]. A 
special election is not required to fill a vacancy for any other school district - 
instead vacancies are filled by appointment of the remaining members Wis. Stat \S 17.26 (1). It is unclear if this would hold for school districts because the determination 
to hold the election is made by school district election official, who may 
determine that a reliable count of votes cast is not available and thus may defer 
to a formula specified in statute to determine the number of petitioners required 
to initiate a recall. Wis. Stat \S 9.10 (1) (c) to (d). Cited in a Staff Brief by 
the Joint Legislative Council Special Committee on Election Law Review, October 
2004 \url{http://libcd.law.wisc.edu/~wilc/sb/sb\_2004\_07.pdf}}


<<electype, results='asis'>>=
tabledf <- subset(races, year > 2001 & year < 2013)
tabledf$electype2 <- ifelse(tabledf$electiontype == 1, "General", 
                            ifelse(tabledf$electiontype == 2, "Primary", "Special"))
print(xtable(table(tabledf$year, tabledf$electype2), label="tab:electype", 
             caption = "Number of general, primary, and special school board elections 2002-2012."), 
      include.rownames=TRUE)
@

In general, school board elections have fewer primary and special elections than 
their legislative counterparts. This leads to the biggest question in the school 
board literature from Chapter \ref{chap:intro}. For the entire data set from 2002-2012 there are \Sexpr{iNum(length(races$distid[races$electiontype == 1]))} 
general election races, \Sexpr{iNum(length(races$distid[races$electiontype == 2]))} 
primary election races, and \Sexpr{iNum(length(races$distid[races$electiontype == 3]))}
special elections. Table \ref{tab:electype} shows the number of races of each type 
for the period between 2002 and 2012. In all, \Sexpr{iNum(length(unique(races$distid[races$electiontype == 2])))} districts 
reported a primary election. Only 
\Sexpr{iNum(length(unique(tabledf$distid[tabledf$electiontype == 3])))}, 
districts reported a special election during this period, and \Sexpr{iNum(length(unique(tabledf$distid[tabledf$electiontype == 1])))} 
reported a general election race. 

Since Wisconsin school boards are non-partisan offices, a primary is not a symbol of 
an ideological challenge to an incumbent or a battle to win the votes of 
strict partisans. Instead, a primary is a signal of a substantial level of candidate 
activity for a school board race. 

Only a single recall election occurred during the 2007 to 2012 period. This was a
recall election held on December 29$^{th}$, 2009 in the Crivitz school district which 
was triggered after a petition against school board member David Kwiatkowski. Mr. Kwiatkowski 
resigned his seat that November in the face of the recall petition, but the recall 
election was still held. This special election raised several important issues that 
are indicative of the challenge surrounding the study of local elections. First, 
it was unclear how Wisconsin's recall statutes apply in the case of school boards. 
The recall statute allows for a recall based on the number of petitioners equal to 
at least 25\% of the vote cast for the office of Governor at the last gubernatorial 
election held within the same jurisdiction.\footnote{\url{http://gab.wi.gov/sites/default/files/publication/64/recall_of_local_elected_officials_manual_2009_06_p_13139.pdf}} As discussed above, Wisconsin does not 
have official records on the number of votes cast for each office by school district 
jurisdiction and in this case the threshold was calculated by the district administrator 
to be 668 - which is roughly the average number of voters who voted for school board. 
An additional difficulty was the overlap between many officials involved in the 
recall process in this small jurisdiction had overlapping responsibilities and allegations 
of conflicts of interest arose as a result -- leading to appeals to the Wisconsin 
Governmental Accountability Board.\footnote{For a full account of this 
particular case, see the Peshtigo Times article online \url{http://www.peshtigotimes.net/?id=12617}} 

\subsection{Contestation: Frequency and Context}

The biggest question in the school board literature seems to be -- are school 
board elections contested, and if so, when? While Chapter \ref{chap:candidacy} 
will explore when candidates emerge for school board elections, this section will 
provide a descriptive look at how often elections are contested, and how this varies compared to 
other elected bodies. 

Unlike studies of congressional or state legislative races, where the barriers to 
appearing on the ballot are generally understood. Using the framework of democratic 
potential, I describe the low legal and political barriers to school board service. 
To appear on the ballot in the spring election a candidate may not begin 
circulating nomination papers prior to December 1 in the previous year. The 
nomination papers must be 
filed no later than 5 p.m. on the first Tuesday in January preceding the election. 
(Wis. Stat \S 8.10 and 8.15). The number of signatures by electors varies in statute, 
depending on the proximity of the school district to cities. In Milwaukee Public Schools 
candidates must obtain between 400 to 800 signatures within the jurisdiction they 
are running to represent (either across the school district, or a specific region 
of the district). 
If the school district contains any territory that lies within a second class city, a 
candidate must obtain between 100 and 200 signatures. School districts that have no 
territory that lies within a first or second class city are free to determine 
whether or not require nomination papers (Wis. Stat \S 120.06 (a)).\footnote{Milwaukee 
is the only first class city that meets all requirements in Wis. Stat \S 62.05 (I). 
There are currently sixteen second class cities in Wisconsin, and two more which 
qualify but have not switched status yet. The second class cities are Madison, 
Green Bay, Kenosha, Racine, Appleton, Waukesha, Oshkosh, Eau Claire, Janesville, 
West Allis, La Crosse, Sheboygan, Wauwatosa, Fond du Lac, Brookfield, and Superior.} 
The statutes specify that these remaining districts can choose to require 
nomination papers from candidates, but may only require 
between 20 and 100 signatures of electors [Wis. Stat \S 8.10 (3) and 8.15 (6)]. In 
jurisdictions that do not require elector signatures, candidates must file a declaration 
of candidacy to register for the election with the election clerk in the school district.
After meeting these requirements the candidate will appear on the spring ballot as 
a candidate for school board. Outside of first and second class cities, running for school board presents very few barriers to entry for potential candidates. Even 
within first and second class cities, candidates face lower formal barriers than 
candidates for legislative or executive office. Coupled with the low cost of school board campaigns, most often less than \$1,000, the campaign presents 
very little impediment toward serving on a school board \citep{RefWorks:322}. If we 
observe low levels of candidate participation in school board races, then, we must 
look to explanations other than difficulty in nomination or campaign costs. 

To explore candidate participation, I consider the pool of school board races between 
2002 and 2012 for which records were successfully obtained. Of the \Sexpr{iNum(nrow(races))}, I focus on the \Sexpr{iNum(nrow(races[races$electiontype == 1,]))} 
general elections. Of these general election races, 
\Sexpr{iNum(nrow(races[races$electiontype == 1 & races$nrealcand > 1,]))} feature 
two or more candidates who both were on the ballot and garnered more than 20 votes.\footnote{
It is not uncommon in school board races for a write-in candidate to garner well over 20 votes. Thus, candidates not appearing on the ballot but receiving over 20 votes are included in the 
dataset where their names were reported by the jurisdictions. Candidates under 20 
votes are collapsed into a category of scatter votes.} 
However, it is important to note that in many school districts voters select more than 
one candidate for each seat and elect the top N vote recipients to the board. A 
better measure of contestation is to see how many races featured more candidates than 
winners - \Sexpr{iNum(nrow(races[races$electiontype == 1 & races$nrealcand > races$nwins,]))} 
races featured this, or \Sexpr{iPer((nrow(races[races$electiontype == 1 & races$nrealcand > races$nwins,])/ 
nrow(races[races$electiontype == 1,]))*100)} of all races. 

Next, I look at how often incumbents stand for election and how often they are 
defeated. In order to code incumbency, two data sources were used. First, if a 
candidate appeared in consecutive races and was coded as a winner in the prior 
race, they are coded as an incumbent. However, for races from the beginning 
of the dataset, incumbency was coded using a master roster of known school board 
members provided by the Wisconsin Department of Public Instruction to the author.\footnote{
This collection is not required or official, but is maintained by the DPI in partnership with 
the Wisconsin Association of School Boards.} This collection indicates name, school district, 
and year of service for school board members in Wisconsin. Candidates appearing on the ballot 
in the early years of a school district's election records were cross referenced against this 
list to infer their incumbency status.\footnote{Details about this procedure can 
be found in the Appendix \ref{app:log}} 

<<challeng1, echo=FALSE, results='hide'>>=
nrow(races[races$ninc > 0 & races$electiontype == 1,])
nrow(races[races$ninc > 1 & races$electiontype == 1,])
contested <- nrow(races[races$nrealcand > races$nwins & 
                          races$nwins > 0 & races$electiontype == 1, ])
contestedSer <- nrow(races[(races$nrealcand - races$nminor) > races$nwins & 
                          races$nwins > 0 & races$electiontype == 1 , ])
base <- nrow(races[races$electiontype == 1,])
@

Actualized democracy requires voters to have candidates to choose among. 
In order to assess this I first identify the number of races where 
there are more candidates on the ballot than winners. This is a nominal measure 
of the level of choice that voters are presented with. \Sexpr{iPer(contested/base*100)} 
of races feature at least one more candidate than the number of winners. However, 
while this represents the number of candidates appearing on the ballot, it does 
not provide an indication of the seriousness of the challenge. Merely having  
multiple candidates is not the same as having a contested election. Political scientists 
focus on serious candidates and quality challengers. Measuring challenger quality 
in elections is difficult, but particularly difficult in non-partisan 
off-cycle elections like school boards where measures of features of individual 
candidates are difficult to gather or compare across jurisdictions \citep{oliver12}. 
In lieu of a better measure, I restrict the sample only to candidates that garner at least 20 votes -- which represents \Sexpr{iPer(20/median(races$votes[races$electiontype==1], na.rm=TRUE)*100)} of the total votes cast in the median school board race -- other studies have used cutoffs of 3\% or even 5\%. This represents arguably a conservative cutoff, because in some cases a write-in candidate may garner 20 votes and in larger jurisdictions 20 votes are easier to come by than in smaller jurisdictions. Once I filter out all cases where a candidate received fewer than 20 votes, the level of contestation is \Sexpr{iPer(contestedSer/base*100)} of general election races.\footnote{In Wisconsin 
school board races candidates may appear on the ballot but not garner even 20 votes. Other times, local election records did not distinguish between candidates who declared officially and any candidate who received votes.}

% Challenger and incumbent
<<incumb1, echo=FALSE, results='hide'>>=
nrow(races[races$ninc > 0 & races$electiontype == 1,])
nrow(races[races$ninc > 1 & races$electiontype == 1,])
contested <- nrow(races[races$nrealcand > races$ninc & 
                          races$ninc > 0 & races$electiontype == 1, ])
contestedSer <- nrow(races[(races$nrealcand - races$nminor) > races$ninc & 
                          races$ninc > 0 & races$electiontype == 1 , ])
base <- nrow(races[races$electiontype == 1,])
@

Another important type of contestation is how often incumbents are challenged. 
Incumbent defeat is important to normative conceptions of the functioning of 
democracy. In general elections, \Sexpr{iPer((nrow(races[races$ninc > 0 & races$electiontype == 1,])/base)*100)} of all races featured at least one incumbent. However, a 
more important figure is identifying how many races featured at least one challenger 
against an incumbent. \Sexpr{iPer(contestedSer/base*100)} of races featured 
incumbents facing challengers that received more than 20 votes.\footnote{Some evidence to support the selection of 20 votes is that very few 
candidates that appeared on the ballot received fewer than 20 votes -- even in the 
smallest jurisdictions.} %TODO: Find evidence and count of this. 

Table \ref{tab:incumbentContest} shows the patterns of contestation in Wisconsin 
elections for the period from 2002-2012 for the approximately 400 races in each 
year. Two trends that appear are the decrease in uncontested incumbents running 
and contested open seats. Instead, there has been an increase in races featuring 
an open and uncontested seat. Chapter \ref{chap:candidacy} will investigate this.

<<incumbtable, echo=FALSE, results='asis'>>=

# Make a table showing races featuring incumbent challenger by year
races.tmp <- subset(races, electiontype ==1 & year > 2001 & year <2013)
races.tmp$contest <- "Uncontested"
races.tmp$contest[races.tmp$nrealcand == races.tmp$nwins & races.tmp$ninc > 0] <- "Open Uncontested"
races.tmp$contest[races.tmp$nrealcand == races.tmp$nwins & races.tmp$ninc == 0] <- "Incumbent Uncontested"
races.tmp$contest[races.tmp$nrealcand > races.tmp$nwins & races.tmp$ninc > 0] <- "Incumbent Contested"
races.tmp$contest[races.tmp$nrealcand > races.tmp$nwins & races.tmp$ninc ==0] <- "Open Contested"


table.tmp <- table(races.tmp$year, races.tmp$contest)
table.tmp <- prop.table(table.tmp, margin = 1) * 100
table.tmp <- apply(table.tmp, MARGIN = 2, FUN=iPer2)
row.names(table.tmp) <- 2002:2012
table.tmp <- xtable(table.tmp, label = "tab:incumbentContest", 
                    caption = "Races featuring a challenge to an incumbent 2002-2012.", 
                    align = c("l", "c", "c", "c", "c"))

print(table.tmp, include.rownames=TRUE, size = "small")

@

% Comparisons

In comparison to these school board races, legislative races at both the state and federal 
level have much higher rates of contestation. In 2012, 10 out of 435 (2.3\%) U.S. House 
races were uncontested, and none of the 33 U.S. Senate races were uncontested. 
While these races are considerably more attractive to candidates due to the career and financial 
opportunities they represent, they are also more difficult to qualify for and 
labor intensive to compete in. State legislative races also exhibit high levels 
of contestation. Taking Wisconsin as an example, in 2012 only 26 of 99 seats 
(26.3\%) in the 
Wisconsin Assembly were uncontested, and only 8 out of 33 seats (24.2\%) in the Wisconsin 
Senate were uncontested in 2012 and 2010 combined.\footnote{All results provided 
by Ballotpedia.} Another comparison would be to compare contestation of partisan 
primaries in legislative districts. Partisan primaries are more apt because partisan 
general elections tend to include a partisan challenger. Primary races are more 
comparable to school board races where ideological differences are not the main 
concern. In the 2014 
U.S. House midterm primaries, only 314 of the 795 possible major party primaries (39.5\%)
were contested.\footnote{Ballotpedia. \url{http://ballotpedia.org/National_contested\_primary\_average\_during\_the\_2014\_U.S.\_congressional_elections}} This figure is on par with the level of 
contestation seen in school board elections in Table \ref{tab:incumbentContest}. 

The similar levels of contestation between partisan primaries and school board 
races serves as an interesting background to explore why boards are contested 
so rarely. The barrier to entry in a school board race is quite low when compared to a 
partisan primary for a major party. However, relative to legislative office, candidates 
have seemingly many fewer reasons to run for school board -- a narrow issue portfolio, 
low media exposure, and little to no money or fame \citep{RefWorks:321,RefWorks:322}. 
Despite this, both a primary race and a school board race are characterized by 
smaller electorates, lower information available to voters, and an off-cycle election 
seat. Actualized democracy appears to fall short of the democratic potential, but 
perhaps not as far short as detractors of school boards may believe. 

\subsubsection{Close Races}
\label{subsec:closeraces}

In Table \ref{tab:incumbentContest} I show that school board elections are 
contested more often than the literature from Chapter \ref{chap:intro} would lead 
one to believe. However, Table \ref{tab:incumbentContest} represents an overestimate 
of contestation by using a generous definition of a contest -- the presence of a 
nominal challenge. As with other studies of electoral competitiveness, it is 
important to consider not just the presence of alternative candidates, but of 
serious challenges. Ideally, 
this would mean developing a priori judgments of the fitness of individual candidates 
for office and polling information on the preferences of voters ahead of the 
campaign. Such measures as unavailable in the current study. Instead, I turn to 
measures of the margin of victory as a proxy for pre-election voter preferences. 


<<votemargin1>>=
cand.tmp <- dat[dat$candidateid!=99 & dat$electiontype==1, ]
votes.tmp <- merge(cand.tmp, as.data.frame(races)[races$nwins >0, c("raceid2", "votes", 
                                                                    "districtwide", "ninc",
                                                                    "nminor","nwins", "ncand",
                                                                    "nrealcand")], 
                   by = c("raceid2"), suffixes = c(".cand", ".race"))

votes.tmp$vote_share <- votes.tmp$votes.cand / votes.tmp$votes.race
votes.tmp$vote_share[is.na(votes.tmp$vote_share)] <- 0
votes.tmp$hareQuota <- votes.tmp$votes.race / (votes.tmp$nwins + 1)

plotdf <- as.data.table(votes.tmp)[, list(cand = length(winner), 
                                          winners = sum(winner),
                                          votescast = sum(votes.cand, na.rm=TRUE),
                                          minWinVotes = min(votes.cand[winner == 1], na.rm=TRUE),
                                          maxLoseVotes = max(votes.cand[winner == 0], na.rm=TRUE),
                                          winnerVotes = sum(votes.cand[winner == 1], na.rm=TRUE),
                                          winshare = sum(vote_share[winner ==1], na.rm=TRUE),
                                          totalvoteshare = sum(vote_share, na.rm=TRUE), 
                          hareQuotaDeltaWinners = mean(votes.cand[winner ==1] - hareQuota[winner==1])),
                                   by = c("raceid2")]

plotdf$minWinVotes[!is.finite(plotdf$minWinVotes)] <- 0
plotdf$maxLoseVotes[!is.finite(plotdf$maxLoseVotes)] <- 0
plotdf$voteMargin <- plotdf$minWinVotes - plotdf$maxLoseVotes
plotdf$blaisLago <- 100 * (plotdf$voteMargin / plotdf$votescast / plotdf$winners)
plotdf$hareQuota <- plotdf$votescast / (plotdf$winners + 1)
plotdf$hareQuotaDelta2 <- plotdf$winnerVotes - (plotdf$hareQuota * plotdf$winners)

# To correct
# plotdf2[plotdf2$voteMargin < 0,] 19 cases with more votes for a loser than a winner
errors <- subset(plotdf, voteMargin < 0)
plotdf <- as.data.frame(plotdf)
#plotdf <- reshape(plotdf, direction = "wide", timevar = "winner", idvar = c("distid", "year", "raceid"))

# hist(plotdf$winmargin3[plotdf$winners < plotdf$cand & !is.na(plotdf$votescast) & plotdf$votescast > 100])
iNum <- function(x){prettyNum(x, big.mark = ",", small.mark = ".", 
                                           digits = 0)}
@


Chapter \ref{chap:candidacy} will explore this measurement in further depth, but here 
I pause to review some possible measures of electoral margin in cases of non-partisan 
multi-member districts. For an analysis of the intensity of competitiveness in 
school board races, I turn my attention to races where voters have a choice. I 
restrict the sample to the \Sexpr{iPer(nrow(plotdf[plotdf$cand > plotdf$winners,])/nrow(plotdf) * 100)} of contested general election races that feature multiple candidates 
on the ballot who garner more than 20 votes. Figure 
\ref{fig:winsandcandidatestable} shows the distribution of school board 
races by the number of winners and the number of candidates. From this figure 
it is clear that a plurality of races feature 1 or 2 winners and only 1 or 
2 candidates, however, the method for calculating vote margin has to be robust to a wide 
array of combinations of candidates receiving votes and number of winners for the 
seat. Table \ref{tab:votemargincalc} describes the ways of dealing with this in 
calculating the margin of victory in school board races.

\begin{table}[h!]
\begin{center}
\begin{footnotesize}
\caption{Methods of Calculating Vote Margin}
\label{tab:votemargincalc}
{\renewcommand{\arraystretch}{2}%
\begin{tabular}{| p{.15\textwidth} | p{.3\textwidth} | >{\centering}p{.275\textwidth}| p{.175\textwidth}|}
\hline
\textbf{Name}  & \textbf{Description} & \textbf{Formula} & \textbf{Citation} \\ \hline
Vote Margin  & Minimum votes needed for a losing candidate to win & $min(votes_{winner}) - max(votes_{loser})$ & \citet{VoteCalculus68,RefWorks:351,cox88} \\ \hline
Hare Quota Difference & Average distance of winners from minimum winning vote count & $\sum \frac{votes_{iw}}{votes_{total}} - \frac{1}{n_{candidates}}n_{winners}$  & \citet{Jesse1999323}   \\ \hline
Psuedo Two Candidate Races & Combine candidates and challengers into plurality races & No formula & \citet{jackmanwinsky} \\ \hline
Blais-Lago Quotient & Adjustment of vote margin to normalize across district types & $100 \times \frac{\frac{VoteMargin}{TotalVotes}}{Seats}$ & \citet{blaislago} \\ \hline
\end{tabular}}
\end{footnotesize}
\end{center}
\end{table}

In the comparative politics literature, competitiveness if often described as the 
vote differential between the last winner and the first loser. That is, the number 
of votes necessary to change the proportion of seats awarded to parties in the 
district \citep{blaislago}. Wisconsin school board seats are non-partisan so instead I focus on the 
number of votes between the last winner and the first loser -- the number of votes 
necessary to change who is on the board. This method also focuses on the rational 
choice perspective that voters evaluate electoral closeness by the pure number 
of votes separating candidates -- the probability of their vote changing the outcome 
\citep{VoteCalculus68,RefWorks:351}. 

The vote margin metric has two disadvantages. First, it only measures the 
competitiveness 
of the most competitive part of a multimember district. The rest of the seats in 
such a district may be very lopsided. In cases where party membership of the 
candidates is known this can still be meaningful since if the competitive division 
is between two candidates from different parties, the substantive representation of 
the district will change and voters may realize a shift in district ideology toward 
their own ideal point by casting votes. In non-partisan elections like those of 
school boards, it is difficult to know \emph{a priori} if an ideological difference 
exists between the last winner and first loser in a seat, and thus whether a narrow 
victory is meaningful. A second problem with the vote margin metric is more practical. 
Vote margin functions well when comparing districts in which the number of voters is 
relatively similar, such as U.S. House seats. However, in cases where the voting 
population can vary by two orders of magnitude or more, using the raw vote margin 
can prove distorting \citep{cox88}. 

To adjust for this there are three methods. The first is to measure the mean distance 
of all winning candidates from the minimum necessary to secure a seat, also known 
as the Hare Quota.\footnote{The Hare Quota is simply the quotient $\frac{Total Votes}{Seats}$ For simplicity I use the Hare Quota, but other measures 
that are similar include the Droop Quota and the Hagenbach-Bischoff Quota. While Wisconsin school board elections do not use the Hare Quota formally to determine representation, because 
voters may vote once for each seat, it properly represents the plurality necessary to 
win a seat on boards across the state.} This measure better captures the competitiveness 
of the entire race because multiple candidate races where some of the victors win 
in blowouts will be less competitive than if they were measured solely on the 
closest single match up within their district. This method also has the benefit 
of being more normalized across disparate electorate sizes by differencing out the 
required plurality from the measure, thereby adjusting for differential electorate 
size. 

The second option is to construct psuedo races of two candidates each from within 
the multi-member districts. This is the approach taken by \citet{jackmanwinsky} to 
evaluate the competitiveness of multimember districts in US state legislative elections. 
This is an elegant approach because it appears to best reflect 
the decision process of individual voters -- voters who split their ticket between 
parties are likely doing so based on their evaluation of an individual candidate.
This approach was possible because of the partisan nature of these seats, allowing 
logical contests to be simulated from the multimember results pitting Democrats 
against Republicans. No formal partisan or ideological categorization is 
available in school board races to make this approach possible, though it could 
be argued that local elections are best characterized as incumbents versus 
challengers. The incumbent challenger divide will not work for two reasons. First, 
not all races feature an incumbent and a challenger as we have seen above. In cases 
where seats are open or only one challenger and three incumbents are running, it is 
difficult to see how to apply the psuedo-district model. Second, challenger and 
incumbent status is not clear to voters on the ballot -- not all ballots indicate 
incumbent status and voters are likely often unaware of which candidates are up 
for re-election. In this low-information environment then, the simulated district 
approach does not appear to accurately model the decision of individual voters. 

The final method is the Blais-Lago quotient. This metric has the advantage of 
better adjusting the vote margin calculation for both the size of the electorate 
and the size of the election slate, thus making meaningful comparisons across 
diverse districts possible. While this method still focuses on the most competitive 
seat in the district, it better enables comparisons across districts. The authors 
describe the measure as: ``the minimal number of additional votes required under 
existing rules, for any party to win one additional seat'' \citep{blaislago}. 
A downside of the Blais-Lago quotient is that in non-partisan elections it must be interpreted with caution as the last 
winner and first loser may have little to no ideological divide. That is, for voters, 
switching the last winner with the first loser would not meaningfully affect policy, 
and thus the competition was not between these two candidates and must either be 
with a third candidate further down the vote tabulation, or no competition exists 
at all because all candidates broadly represent the same interests. While this 
makes the ideological consequences of changing winners unclear, it still represents 
the best way to comparatively measure the closeness of the election outcome across 
districts with differing seats. Thus, the Blais-Lago Quotient can be 
interpreted as the minimum number of votes necessary to adjust the outcome divided 
by the number of voters. 

%TODO: Find an example for the above

<<winsandcandidatestable, echo=FALSE, fig.cap="Distribution of School Board Races by Candidates and Winners.", fig.width=4.5, fig.height=4.5>>=
plotdf <- merge(plotdf, races, by = "raceid2", all.x=TRUE)
plotdf <- plotdf[plotdf$voteMargin > 0, ]

mytab <- table(plotdf$nrealcand, plotdf$winners)

mytab <- reshape2::melt(mytab)
mytab$value2 <- mytab$value / sum(mytab$value)
mytab$value2LABEL <- paste0(round(mytab$value2, 3)*100, "%")
mytab <- mytab[mytab$Var1 <= 6,]
ggplot(mytab, aes(Var1, Var2)) + geom_tile(aes(fill = value2), color = I('gray80')) + 
  scale_fill_gradient(low = "white", high = "gray50", guide = "none") + 
  geom_text(aes(label = value2LABEL)) + 
  scale_x_continuous(breaks = c(0:6)) + 
  scale_y_continuous(breaks = c(0:6)) + theme_bw() + 
  theme(panel.grid = element_blank()) + 
  labs(x = "Serious Candidates", y = "Winners", 
       title = "Distribution of Races by Winners and Candidates")

@


<<winmarginplots, echo=FALSE, fig.cap="Win margin in contested school board elections as measured by the Blais-Lago Quotient.">>=
qplot(year, blaisLago/100, 
      data = plotdf[plotdf$cand > plotdf$winners & 
                      plotdf$year > 2001 & plotdf$year < 2013,], 
      geom = 'boxplot') + theme_dpi() + 
  labs(y = "Maximum Value Method", x = "Year", title = "Distribution of Blais-Lago Quotient in Contested School Board Races") + scale_y_continuous(label = percent) + 
  geom_hline(yintercept = 0, color = I("red"), linetype = 2, size = I(1.05)) +
  geom_hline(yintercept = 0.05, color = I("blue"), linetype = 3, size = I(1.05))
@

Figures \ref{fig:winmarginplots} and \ref{fig:winmarginplots2} show the distribution 
of the Blais-Lago Quotient and the Hare Quota distance for contested school board 
races respectively. They show that school board races, when they are contested, 
tend to be fairly competitive. \citet{blaislago} find that national legislative 
districts in four countries had average quotients ranging from 16.77 in Portugal 
to 26.88 in Spain. All Wisconsin school board elections in the study have a 
quotient of \Sexpr{round(mean(plotdf$blaisLago), digits=2)}. However, the 
\Sexpr{iPer(nrow(plotdf[plotdf$cand > plotdf$winners,])/nrow(plotdf) * 100)} of 
races that were contested featured a quotient of 
\Sexpr{round(mean(plotdf$blaisLago[plotdf$cand > plotdf$winners]), digits=2)}.
This is substantially more competitive, and Figure \ref{fig:winmarginplots2} shows 
why this might be the case. The interquartile 
range of the Hare Quota distance for contested school board races is roughly 25 to 
200 in a given year. This means that the average winner in these school board race was 
between 25 and 200 voters shifting their ballots away from losing their seat. School 
board races are so competitive on these measures, in part, because of the low number of total votes cast. 


<<winmarginplots2, echo=FALSE, fig.cap="Win margin in contested school board elections as measured by the Hare Quota distance.">>=
qplot(year, hareQuotaDeltaWinners, 
      data = plotdf[plotdf$cand > plotdf$winners & 
                      plotdf$year > 2001 & plotdf$year < 2013,], 
      geom = 'boxplot') + theme_dpi() + scale_y_sqrt() +
  labs(y = "Vote Margin", x = "Year", title = "Average Hare Quota Distance") + 
  geom_hline(yintercept = 25, color = I("red"), linetype = 2, size = I(1.05)) +
  geom_hline(yintercept = 200, color = I("blue"), linetype = 3, size = I(1.05))
@

<<competitivenessTab, echo=FALSE, eval=FALSE>>==

competitionMeasures <- ddply(plotdf, .(year), summarize, 
                            allRaces = length(unique(raceid2)), 
                            closeMargin = length(voteMargin[voteMargin < 100]), 
                            closeHareQuota = length(hareQuotaDeltaWinners[hareQuotaDeltaWinners < 50]),
                            closeblaisLago = length(blaisLago[blaisLago < 2.5]))
qplot(blaisLago, data=plotdf[plotdf$blaisLago < 50,], binwidth = 1) + scale_x_continuous(breaks = seq(0,50, by = 1))
@

The Blais-Lago quotient is the best measure of competitiveness. Not only does it 
generalize across the diverse election types in Wisconsin, but it also captures 
intuitively the concept of democratic potential -- many school board races require 
candidates to convince only a handful of voters to change their minds. 

% \subsubsection{Scattered Votes}
% 
% One adjustment to deal with this concern is to subtract out votes for write-in 
% candidates where possible. This is not always possible because voting records do not 
% always indicate in which school board race the scattered votes were cast. In most 
% cases, school board election clerks record candidates getting very few votes -- 
% less than 10 -- together into a single category of votes called "scatter". Though 
% these votes are largely inconsequential in federal and state legislative races, 
% in non-partisan local races with low vote counts they can make a significant 
% impact on measures of turnout, win share, and contestation. Of the \Sexpr{iNum(nrow(dat))} 
% candidate-races of data on school board elections in Wisconsin, \Sexpr{iNum(nrow(dat[dat$candidateid == 99, ]))} 
% were scatter votes. 
% 
% Votes were labeled scatter in the Wisconsin data set for two reasons: first, all 
% candidates receiving fewer than 10 votes in a single race were compiled together 
% into a scatter category. This decision was put in place to reduce the data 
% collection burden that already involved hand coding 
% \Sexpr{iNum(nrow(dat[dat$candidateid != 99,]))} 
% candidate-race records. Including the "long-tail" of write-in votes, protest votes, 
% and spurious candidates would have added substantial burden to the data collection 
% process. 
% 
% Second, some jurisdictions reported their votes with a "scatter" category for 
% reporting in newspapers, to county election officials, 
% or for local reporting. In these cases, the threshold for a candidate being labeled 
% in the "scatter" category is unknown, however, for 
% \Sexpr{iNum(nrow(dat[dat$candidateid == 99 & dat$votes > 20,]))} 
% races it exceeds the threshold of 20 votes for label as a minor candidate, and for 
% \Sexpr{iNum(nrow(dat[dat$candidateid == 99 & dat$votes > 200,]))} 
% it exceeds 200. In these cases, it is important to consider how these votes should 
% be included in further analysis -- should they be subtracted from the total votes 
% in the district or should they be further collapsed into a category? 

%TODO: What should be done with these votes?

<<scatter1>>=
# scat1 <- dat[dat$candidateid == 99, ]
# head(scat1[order(-scat1$votes),], 20)
@

% \subsubsection{Write-in Candidates}
% 
% In only the rarest legislative elections are write-in candidates consequential with 
% only a handful of write-in candidates at the state or federal level over the past 
% 50 years making an impact at the polls. However, in school board elections in Wisconsin, 
% serious challenges and even victories by write-in candidates are frequent enough to 
% merit special consideration. Unfortunately, write-in candidates are often not 
% noted in election returns explicitly in Wisconsin school board elections. 

\clearpage

\subsection{Incumbent Defeat}

As we saw in Chapter \ref{chap:intro}, incumbent defeat is an important concept 
in the school board literature \citep{RefWorks:311,RefWorks:264}. Incumbent 
defeat has been shown to be difficult to measure in the school board election 
literature due to a lack of available records; most prior studies have relied 
instead on surveys of current and former school board members. Using self-reports 
and lists of current 
and past members of school board members does not provide a reliable way to distinguish 
between political and apolitical forms of turnover \citep{RefWorks:311}. Using 
incumbent electoral defeat is not a perfect measure, because it does not capture 
cases where an incumbent finds it not worth it to run for office or does not seek 
reelection for political reasons. However, it does 
allow me to identify political turnover consistently across jurisdictions across 
a decade of elections -- a first in the literature. 

<<incDefeat, fig.cap="Incumbent Defeat by Year by District">>=
incDefeat <- ddply(dat[dat$electiontype == 1 & dat$year > 2001 & dat$year < 2013,], 
                   .(year), 
                   summarise, 
                   incsDefeated = sum(incumbent[winner == 0]), 
                   incsTotal = sum(incumbent), 
                   winnersTotal = sum(winner))

incDefeatDist <- ddply(dat[dat$electiontype == 1 & dat$year > 2001 & dat$year < 2013,], 
                   .(year), 
                   summarise, 
                   incsDefeated = sum(incumbent[winner == 0]), 
                   totalDistricts = length(unique(distid)),
                   incDefeatDist = length(unique(distid[incumbent==1 & winner == 0])),
                   incsTotal = sum(incumbent), 
                   winnersTotal = sum(winner))

qplot(year, incDefeatDist/totalDistricts, data = incDefeatDist, geom = 'bar', 
      stat = 'identity', 
      fill = I("gray60"), color = I("black")) + theme_dpi() + 
  scale_x_continuous(breaks = 2002:2012, "Year") + 
  scale_y_continuous(label = percent, "Percent of Districts With SB Race") + 
  labs(title = "Percentage of Districts With Defeated Incumbent 2002-2012") + 
  coord_cartesian(ylim = c(0, .25)) +
  geom_text(aes(label = paste0(round(incDefeatDist/totalDistricts*100, 1), "%")), 
            vjust = 1.55) +
  theme(axis.ticks.x = element_blank())


rm(incDefeat,incDefeatDist)
@ 

Figure \ref{fig:incDefeat} shows the percentage of districts with school board 
races each year where an incumbent was defeated. This shows a consistent pattern 
of regular incumbent defeat on school boards, suggesting the incumbency advantage 
in school boards is much weaker than in other elections. \citet{oliver07} shows evidence 
from suburban mayoral elections that voters defeat incumbents based on a retrospective 
evaluation of their stewardship of the community, likability, and issue agreement. Unlike 
national election voters, however, \citet{oliver07} shows that local election voters are 
much more engaged in and informed about local issues. This, coupled with the low-cost 
of entry into a school board campaign, may explain why incumbent defeat is more 
frequent. This will be explored further in Chapter \ref{chap:candidacy}.

\subsection{Voter Turnout}
\label{subsec:turnout}

The spring elections in Wisconsin are decidedly low turnout affairs. Since 2000 
Wisconsin has had a voting age population between 4 and 4.35 million. However, 
in this time period the spring election has seen around 800,000 votes cast. 2011 saw 
a record breaking peak of 1.5 million.\footnote{Statistics from a Wisconsin Government Accountability 
Board report, available online: \url{http://gab.wi.gov/sites/default/files/page/non\_partisan\_turnout\_2000\_2013\_pdf\_15069.pdf}} \citet{teixeira92} suggests a 
rule of thumb that off-cycle partisan elections have a fifteen percentage point 
drop from the presidential election and non-partisan local elections experience a 
further fifteen point drop. This would mean Wisconsin should see 55\% turnout in 
gubernatorial races and 40\% turnout in local elections. Numbers on typical school 
board election turnout are not available in the literature, so it is difficult to 
assess the degree Wisconsin's off-cycle races differ from other races nationally. 
Perhaps this is due tot eh difficulty in assessing turnout in special jurisdiction 
elections. However, turnout has typically been around 18\% in Wisconsin spring elections. 
Unsurprisingly then, school board elections are also low turnout affairs. By comparison, 
in the November partisan general election voter turnout is around 70\% in the last 
three presidential elections, and around 48\% in the last three gubernatorial 
elections.\footnote{Statistics from a Wisconsin Government Accountability 
Board report, available online: \url{http://gab.wi.gov/sites/default/files/page/partisan\_voter_turnout\_statistics\_1948\_2012\_pdf\_20396.pdf}}

In this section I will describe the approaches to estimating turnout in Wisconsin 
school board elections and the comparison of school board turnout to other 
electoral participation. A first concern with estimating turnout is finding the 
proper denominator. For the analysis here I elect to use Voting Age Population 
(VAP) as the measure for 
the denominator of the voter turnout calculation instead of registered or eligible 
voters. VAP is the only measure available both at a unit smaller than a school district 
and at the statewide level that can allow for consistent comparisons between the two over 
the entire period of study. Unfortunately, the state of Wisconsin does not maintain 
county, municipality, or ward level registered voter or eligible voter counts 
historically.

To determine the VAP of the school district in Wisconsin, I employ the finest 
resolution estimate of voting age population available -- VAP estimates by minor 
civil division (MCD) produced by the Wisconsin Department of Administration.
\footnote{ Minor civil division is a term used by the US Census Bureau to denote 
the primary governmental and/or administrative divisions within a county. In 
Wisconsin these include cities, towns, villages and unincorporated areas. 
Statistics available online: \url{http://gab.wi.gov/elections-voting/results}. 
Statistics for Wisconsin Minor Civil Divisions are maintained by the Department 
of Administration Demographic Services Center: 
\url{http://www.doa.state.wi.us/section\_detail.asp?linkcatid=11\&linkid=64\&locid=9}}
However, MCDs are not perfectly coterminous with school districts -- school districts 
are contiguous only at the ward level where VAP estimates are not available. In 
order to estimate the proportion of each MCD's VAP that belongs to a given school
district, I use property tax records provided by the Wisconsin Department of 
Revenue (DOR). These records annually report for each school district every MCD 
that is located entirely or partially within the boundaries of the school district, 
as well as the share of property wealth (as measured by equalized values, or EQV), 
for that MCD that the school district 
is authorized to levy tax for. For each year, the share of every MCD's EQV that 
was allocated to each school district was calculated. I use this share to 
prorate the population of each MCD both for the purposes of 
calculating the voting age population, and for calculating votes cast for and 
against candidates in statewide elections. An additional adjustment 
is made to interpolate the VAP for school districts to correct for adjustments in 
the creation and destruction of MCDs year to year which can influence the VAP 
estimates for a school district.\footnote{A sensitivity check was done 
to determine if weighting by residential property values  instead of all property 
value changed the estimates, but it did not. For more details see Appendix \ref{app:data}}

I verify how accurate this estimation procedure is by comparing the official number 
of votes cast and voter turnout statewide to the statewide estimates derived by 
rebuilding voter data at the district level. 

<<turnout, echo = FALSE,  results='asis'>>=
# qplot(races.tmp$turnout, races.tmp$topPresTurnoutPrior, geom = 'point') + 
#   ylim(c(0,1)) + xlim(c(0,1)) + geom_smooth()

years <- c(2002, 2004, 2006, 2008, 2010, 2012)
turnoutEst <- merge(VAP_dist, presTurn, by = c("distid", "year"), all.x=TRUE)
turnoutEst <- merge(turnoutEst, govTurn, by = c("distid", "year"), all.x=TRUE)

turnoutOf <- c(1785710, 3016288, 2166671, 2996869, 2171331, 3071434)
vapOf <- c(4060973, 4118621, 4260038, 4330695, 4372347, 4378741)
turnoutPerOf <- c(44, 72.9, 50.9, 69.2, 49.7, 70.1)

vapEst <- c(sum(turnoutEst$VAP[turnoutEst$year == 2002], na.rm =TRUE), 
            sum(turnoutEst$VAP[turnoutEst$year == 2004], na.rm =TRUE), 
            sum(turnoutEst$VAP[turnoutEst$year == 2006], na.rm =TRUE), 
            sum(turnoutEst$VAP[turnoutEst$year == 2008], na.rm =TRUE), 
            sum(turnoutEst$VAP[turnoutEst$year == 2010], na.rm =TRUE), 
            sum(turnoutEst$VAP[turnoutEst$year == 2012], na.rm =TRUE))


vapadjEst <- c(sum(turnoutEst$VAP_adj[turnoutEst$year == 2002], na.rm =TRUE), 
            sum(turnoutEst$VAP_adj[turnoutEst$year == 2004], na.rm =TRUE), 
            sum(turnoutEst$VAP_adj[turnoutEst$year == 2006], na.rm =TRUE), 
            sum(turnoutEst$VAP_adj[turnoutEst$year == 2008], na.rm =TRUE), 
            sum(turnoutEst$VAP_adj[turnoutEst$year == 2010], na.rm =TRUE), 
            sum(turnoutEst$VAP_adj[turnoutEst$year == 2012], na.rm =TRUE))


turnoutEst <- c(sum(turnoutEst$topGovVotesPrior[turnoutEst$year == 2002], na.rm =TRUE), 
            sum(turnoutEst$topPresVotesPrior[turnoutEst$year == 2004], na.rm =TRUE), 
            sum(turnoutEst$topGovVotesPrior[turnoutEst$year == 2006], na.rm =TRUE), 
            sum(turnoutEst$topPresVotesPrior[turnoutEst$year == 2008], na.rm =TRUE), 
            sum(turnoutEst$topGovVotesPrior[turnoutEst$year == 2010], na.rm =TRUE), 
            sum(turnoutEst$topPresVotesPrior[turnoutEst$year == 2012], na.rm =TRUE))

turnoutPerEst <- (turnoutEst / vapadjEst)*100

tab1names <- c("Year", "Official Total Votes", "Offical VAP", "Offical Turnout", 
               "Estimated Total Votes", "Estimated VAP", "Estimated Turnout")
table1 <- cbind(years, turnoutOf, vapOf, turnoutPerOf, turnoutEst, vapEst, 
                turnoutPerEst)
table1 <- as.data.frame(table1)
table1$years <- as.character(table1$years)
names(table1) <- tab1names
rm(years, turnoutOf, vapOf, turnoutPerOf, turnoutEst, vapEst, turnoutPerEst, 
   tab1names, vapadjEst)
table1$"Offical Turnout" <- paste0(round(table1$"Offical Turnout", 1), "%")
table1$"Estimated Turnout" <- paste0(round(table1$"Estimated Turnout", 1), "%")

table1 <- xtable(table1, digits =0, label="tab:turnoutEst", 
             caption = "Comparing estimates of voter turnout derived from MCD estimates to official GAB turnout records." )
align(table1) <- c('p{.3in}','p{.55in}',  'p{.55in}','p{.55in}','p{.55in}','p{.55in}',
                   'p{.55in}','p{.55in}')

print(table1, 
      include.rownames = FALSE, 
      format.args = list(big.mark = ",", decimal.mark = "."), 
      size = "footnotesize")
@

As shown in Table \ref{tab:turnoutEst}, the estimation procedure accurately 
reproduces the statewide official turnout estimates. Thus the procedure used generates 
reasonable estimates of the VAP at the school district level.\footnote{Doing this 
verification at the county level would provide another robustness check.} This 
takes care of the denominator of the turnout equation. 

The numerator, the number of voters casting votes for school board, presents a 
second set of challenges. I begin by collecting election returns from as many 
school districts as possible in Wisconsin.\footnote{For details on the collection 
procedure see Appendix \ref{app:data}} However, unlike a top ticket race such as 
a presidential or gubernatorial race, the election rules vary across school district 
jurisdictions. In some districts, voters may have multiple votes to cast in the election 
and in each race -- eliminating the ability to judge voter turnout based on the 
number of votes cast. In other districts, only a subsection of the electorate may 
be eligible to vote for a school district office due to apportionment within 
the district. 

<<turnoutgraph, echo=FALSE, fig.cap="Turnout for district wide school board races.", fig.height=4.5>>=
races <- as.data.frame(races)
races.tmp <- merge(races, VAP_dist, by = c("distid", "year"))

presTurn$presTwoPartyVote <- presTurn$presDemVotes + presTurn$presRepVotes
presTurn$presTwoPartyShareDem <- presTurn$presDemVotes / presTurn$presTwoPartyVote

govTurn$govTwoPartyVote <- govTurn$govDemVotes + govTurn$govRepVotes
govTurn$govTwoPartyShareDem <- govTurn$govDemVotes / govTurn$govTwoPartyVote

# turnout over the prior presidential election
races.tmp <- merge(races.tmp, presTurn, by = c("distid", "year"), all.x=TRUE)
races.tmp <- merge(races.tmp, govTurn, by = c("distid", "year"), all.x=TRUE)

races.tmp <- subset(races.tmp, select = c("distid", "year", "raceid2", "ncand", 
                                          "nrealcand", "nwins", "ninc", "raceid",
                                          "nminor", "votes", "districtwide", 
                                          "electiontype", "VAP", "VAP_adj", 
                                          "topPresVotesPrior", "presTwoPartyShareDem", 
                                          "topGovVotesPrior", "govTwoPartyShareDem"))

races.tmp <- subset(races.tmp, raceid!=0)
# look at general
races.tmp <- subset(races.tmp, electiontype == 1)

# Look at districtwide only
races.tmp <- subset(races.tmp, districtwide == 1)
races.tmp <- subset(races.tmp, nrealcand > 0)

races.tmp <- races.tmp[!is.na(races.tmp$distid),]
races.tmp$voters <- races.tmp$votes / races.tmp$nwins
races.tmp$turnout <- races.tmp$voters/races.tmp$VAP_adj
qplot(year, turnout, data = races.tmp, geom = 'boxplot') + 
  scale_y_continuous(label = percent) + theme_dpi() + 
  labs(y = "Voter Turnout", x = "Year", title = "Voter Turnout in School Board Races")
@

There is one set of cases for which estimating voter turnout is easy - the case 
where a school board seat is chosen district wide. As shown in Table 
\ref{tab:yearsample}, this is the vast majority of Wisconsin school districts. 
To determine if a seat was apportioned or district wide, I coded the seats for 
labels such as ``Area", ``District", ``Region", or ``Village" as opposed to 
``At-Large". In these district wide races, the number of voters is simply the 
number of votes cast divided by the number of seats elected. As district 
wide is the default in state law, in the absence of evidence, I assume the race is 
district wide.  Figure \ref{fig:turnoutgraph} shows that district wide school board 
races feature an average turnout below 25\%. 

<<comparison, results='asis', echo=FALSE>>=
out1 <- ddply(races.tmp, .(year), summarize, 
              nraces = length(distid), 
              ndists = length(unique(distid)))
names(out1) <- c("year", "nDistWideRaces", "nDistrictsDistWide")

out2 <- ddply(races, .(year), summarize, 
              nraces = length(distid), 
              ndists = length(unique(distid)))
names(out2) <- c("year", "nAllRaces", "nAllDistricts")

table2 <- merge(out1, out2)
rm(out1, out2)
table2 <- table2[table2$year != 2001, ]
table2 <- table2[table2$year != 2002, ]
table2 <- table2[table2$year != 2013, ]
table2$difference <- table2[, 5] - table2[, 3]
table2$difference2 <- table2[, 4] - table2[, 2]
names(table2) <- c("Year", "Districtwide Races", "Districts with Districtwide", 
                   "All Board Races", "Total Districts", 
                   "Districts without Districtwide", "Non-districwide Races")

table2 <- t(table2)
table2 <- xtable(table2, label="tab:yearsample", 
             caption = "Comparing sample size for district wide vs. apportioned school board races." )
# align(table2) <- c('p{.2in}','p{.5in}',  'p{.8in}','p{.8in}','p{.8in}','p{.8in}',
#                    'p{.8in}','p{.8in}')

print.xtable(table2, 
      include.colnames = FALSE, include.rownames = TRUE,
      format.args = list(big.mark = ",", decimal.mark = "."), 
      size = "footnotesize")
@


<<nondistraces, fig.cap="Turnout for non-district wide school board races.", fig.height=4.5>>=
races <- as.data.frame(races)
races.tmp <- merge(races, VAP_dist, by = c("distid", "year"))

presTurn$presTwoPartyVote <- presTurn$presDemVotes + presTurn$presRepVotes
presTurn$presTwoPartyShareDem <- presTurn$presDemVotes / presTurn$presTwoPartyVote

govTurn$govTwoPartyVote <- govTurn$govDemVotes + govTurn$govRepVotes
govTurn$govTwoPartyShareDem <- govTurn$govDemVotes / govTurn$govTwoPartyVote

races.tmp <- subset(races.tmp, select = c("distid", "year", "raceid2", "ncand", 
                                          "nrealcand", "nwins", "ninc", "raceid",
                                          "nminor", "votes", "districtwide", 
                                          "electiontype", "VAP_adj"))

races.tmp <- subset(races.tmp, raceid!=0)
# look at general
races.tmp <- subset(races.tmp, electiontype == 1)
# Look at non-districtwide only
races.tmp <- subset(races.tmp, districtwide == 0)
races.tmp <- subset(races.tmp, nrealcand > 0)
races.tmp <- races.tmp[!is.na(races.tmp$distid),]

# collapse to the district level

dist.tmp <- ddply(races.tmp, .(distid, year), summarize, 
              ncand = sum(ncand), nrealcand = sum(nrealcand), 
              nwins = sum(nwins), ninc = sum(ninc), 
              nminor = sum(nminor), votes = sum(votes), 
              VAP_adj = statamode(VAP_adj), 
              nraces = length(distid))

# turnout over the prior presidential election
dist.tmp <- merge(dist.tmp, presTurn, by = c("distid", "year"), all.x=TRUE)
dist.tmp <- merge(dist.tmp, govTurn, by = c("distid", "year"), all.x=TRUE)
dist.tmp$VAP_adj <- as.numeric(dist.tmp$VAP_adj)

dist.tmp$voters <- dist.tmp$votes / dist.tmp$nwins
dist.tmp$turnout <- dist.tmp$voters / dist.tmp$VAP_adj
qplot(year, turnout, data = dist.tmp, geom = 'boxplot') + 
  scale_y_continuous(label = percent) + theme_dpi() + 
  labs(y = "Voter Turnout", x = "Year")
@


Estimating turnout in the roughly 50 districts annually, as shown in Table 
\ref{tab:yearsample}, which do not have a district wide school board race is a 
different matter. Figure \ref{fig:nondistraces} shows the pattern for non-district 
wide races appears very similar under the estimation method of collapsing all races 
in a district into one race and dividing the votes counted by the number of winners. 
This still represents an underestimate, as districts with apportioned seats 
do not always elect all seats within district in the same election cycle. However, 
the underestimate represents the best possible estimate and can be partially 
controlled for in subsequent analyses by including indicator variables for boards 
with elections that are not district wide. 

Putting these two together, we can estimate overall voter turnout in school board 
races by school district, over time. First, I take the maximum number of voters in a
district wide race, where available. If no such race is present in a given district 
in a given year, I then use the adjusted district wide turnout based on the 
apportioned seats available. If both races are present, only a district wide race 
is used. 

<<overallturnoutest, fig.cap="Turnout for school board races by school district.", fig.height=4.5>>=
races <- as.data.frame(races)
races.tmp <- merge(races, VAP_dist, by = c("distid", "year"))

# turnout over the prior presidential election
races.tmp <- merge(races.tmp, presTurn, by = c("distid", "year"), all.x=TRUE)
races.tmp <- merge(races.tmp, govTurn, by = c("distid", "year"), all.x=TRUE)

races.tmp <- subset(races.tmp, select = c("distid", "year", "raceid2", "ncand", 
                                          "nrealcand", "nwins", "ninc", "raceid",
                                          "nminor", "votes", "districtwide", 
                                          "electiontype", "VAP", "VAP_adj", 
                                          "topPresVotesPrior", "presTwoPartyShareDem", 
                                          "topGovVotesPrior", "govTwoPartyShareDem"))

races.tmp <- subset(races.tmp, raceid!=0)
# look at general
races.tmp <- subset(races.tmp, electiontype == 1)

# Look at districtwide only
races.tmp <- subset(races.tmp, districtwide == 1)
races.tmp <- subset(races.tmp, nrealcand > 0)

races.tmp <- races.tmp[!is.na(races.tmp$distid),]
races.tmp$voters <- races.tmp$votes / races.tmp$nwins
races.tmp$turnout <- races.tmp$voters/races.tmp$VAP_adj
## Convert to district average somehow

dist_turn <- ddply(races.tmp, .(distid, year), summarize, 
              ncand = sum(ncand), nrealcand = sum(nrealcand), 
              nwins = sum(nwins), ninc = sum(ninc), 
              nminor = sum(nminor), votes = sum(votes), 
              VAP_adj = statamode(VAP_adj), 
              nraces = length(distid))

dist_turn$districtwide <- 1
############
# Non district-wide
############
races <- as.data.frame(races)
races.tmp <- merge(races, VAP_dist, by = c("distid", "year"))

presTurn$presTwoPartyVote <- presTurn$presDemVotes + presTurn$presRepVotes
presTurn$presTwoPartyShareDem <- presTurn$presDemVotes / presTurn$presTwoPartyVote

govTurn$govTwoPartyVote <- govTurn$govDemVotes + govTurn$govRepVotes
govTurn$govTwoPartyShareDem <- govTurn$govDemVotes / govTurn$govTwoPartyVote

races.tmp <- subset(races.tmp, select = c("distid", "year", "raceid2", "ncand", 
                                          "nrealcand", "nwins", "ninc", "raceid",
                                          "nminor", "votes", "districtwide", 
                                          "electiontype", "VAP_adj"))

races.tmp <- subset(races.tmp, raceid!=0)
# look at general
races.tmp <- subset(races.tmp, electiontype == 1)
# Look at non-districtwide only
races.tmp <- subset(races.tmp, districtwide == 0)
races.tmp <- subset(races.tmp, nrealcand > 0)
races.tmp <- races.tmp[!is.na(races.tmp$distid),]

# collapse to the district level

dist.tmp <- ddply(races.tmp, .(distid, year), summarize, 
              ncand = sum(ncand), nrealcand = sum(nrealcand), 
              nwins = sum(nwins), ninc = sum(ninc), 
              nminor = sum(nminor), votes = sum(votes), 
              VAP_adj = statamode(VAP_adj), 
              nraces = length(distid))

dist.tmp$districtwide <- 0

dist_turn <- rbind(dist_turn, dist.tmp)
row_counts <- ddply(dist_turn, .(distid, year), nrow)
dist_turn <- merge(dist_turn, row_counts, all.x=TRUE)
dist_turn$recs <- dist_turn$V1; dist_turn$V1 <- NULL
dist_turn <- ddply(dist_turn, .(distid, year), summarize, 
                    ncand = sum(ncand), nrealcand = sum(nrealcand), 
                    nwins = sum(nwins), ninc = sum(ninc), 
                    nminor = sum(nminor), votes = sum(votes), 
                    VAP_adj = ceiling(as.numeric(VAP_adj)[1]), 
                    nraces = sum(nraces), 
                    districtwide = max(districtwide), 
                    distWidemix = max(recs))

## Clean up metrics
# turnout over the prior presidential election
dist_turn <- merge(dist_turn, presTurn, by = c("distid", "year"), all.x=TRUE)
dist_turn <- merge(dist_turn, govTurn, by = c("distid", "year"), all.x=TRUE)
dist_turn$VAP_adj <- as.numeric(dist_turn$VAP_adj)
dist_turn$voters <- dist_turn$votes / dist_turn$nwins
dist_turn$turnout <- dist_turn$voters / dist_turn$VAP_adj

qplot(year, turnout, data = dist_turn[dist_turn$turnout < 0.75 & !is.na(dist_turn$turnout),], geom = 'boxplot') + 
  scale_y_continuous(label = percent) + theme_dpi() + 
  labs(x = "Year", y = "Turnout as Share of VAP Estimate")
@

Figure \ref{fig:overallturnoutest} shows the final estimate of the distribution 
of school board voter turnout among reporting districts across the years of data 
available. Both the median and the distribution of turnout by school district 
remains consistent from 2002-2010. However, 2011 and 2012 exhibit a sharp spike 
upward in voter turnout. These elections represent the first two spring elections 
after the passage of Act 10 and the election of Governor Scott Walker. 

\clearpage

\subsection{Rolloff}
\label{subsec:undervote}

School board races are far down the ballot from other races that are occurring 
during the spring non-partisan elections cycle in Wisconsin and the spring of 
2011 was marked by a highly contested statewide race for the Supreme Court. The 
election was seen as a referendum on the recent passage of Act 10 and Governor 
Scott Walker's first year in office and was characterized by unprecedented turnout. 
The influence of the strength or weakness of the top ticket race confounds our 
understanding of voter turnout in school board elections. One way to approach this 
is to consider studying the dropoff in votes cast from the statewide top of the 
ticket race to the school board races further down the ballot -- a phenomenon 
known as voter rolloff \citep{wattenberg00}. For the 2007-2012 period, I estimate 
the top ticket turnout in each school district. Importantly, in this period, 
several different office types were the top ticket due to the pattern of 
statewide office terms in Wisconsin. These consist of primarily state supreme 
court races, but as there seven justices elected to ten-year terms, the state 
supreme court does not have an election every spring: 

\begin{myitemize}
  \item 2007 - State Supreme Court Race
  \item 2008 - State Supreme Court Race and presidential primary
  \item 2009 - State Superintendent of Public Instruction
  \item 2010 - None. Wisconsin Appeals Courts (3 of 4)
  \item 2011 - State Supreme Court Race
  \item 2012 - Presidential Preference Primary
\end{myitemize}


<<undervoting, fig.cap="Comparing School Board and Spring Top Ticket Turnout">>=
load("../../data/cache/springElectionVotes.rda")
# load("data/cache/springElectionVotes.rda")
springVotes$votesTopTicketSpring <- springVotes$VotesCast
springVotes$VotesCast <- NULL
dist_turn <- merge(dist_turn, springVotes, 
                   by = c("distid", "year"), all.x = TRUE)

dist_turn$topTicketTurnoutSpring <- dist_turn$votesTopTicketSpring / dist_turn$VAP_adj

springVotes.tmp <- springVotes[springVotes$year == 2020, ]
springVotes.tmp$year <- 2010
idx <- names(dist_turn)[!names(dist_turn) %in% 
                          c("topTicketTurnoutSpring", 
                            names(springVotes)[3:ncol(springVotes)])]
dist_turn.tmp <- merge(dist_turn[, idx], springVotes.tmp, 
                   by = c("distid", "year"))
dist_turn.tmp$topTicketTurnoutSpring <- dist_turn.tmp$votesTopTicketSpring / dist_turn.tmp$VAP_adj

dist_turn <- rbind(dist_turn, dist_turn.tmp)
dist_turn <- dist_turn[!duplicated(dist_turn), ]
rm(dist_turn.tmp, springVotes.tmp)

plotdat <- subset(dist_turn, select = c("turnout", "topTicketTurnoutSpring", 
                                        "districtwide",
                                        "ImputedFlag", "year", "distid"))
plotdat$ImputedFlag[is.na(plotdat$ImputedFlag)] <- "Observed"
plotdat <- na.omit(plotdat)
plotdat <- plotdat[is.finite(plotdat$turnout), ]
centr <- mean(plotdat$turnout)
stddev <- sd(plotdat$turnout)
plotdat$outflag <- (plotdat$turnout - centr) / stddev
plotdat <- plotdat[plotdat$outflag <= 5,]

plotdat$ImputedFlag <- defac(plotdat$ImputedFlag)
plotdat$ImputedFlag[plotdat$ImputedFlag == "Imputed2010"] <- "Imputed"
plotdat$ImputedFlag[plotdat$ImputedFlag == "Observed2010"] <- "Observed"
plotdat$ImputedFlag <- factor(plotdat$ImputedFlag, levels = c("Imputed", "Observed"))
plotdat$ImputedFlag <- relevel(plotdat$ImputedFlag, ref = "Imputed")
# levels(plotdat$ImputedFlag) <- c("Observed", "Imputed")
plotdat <- plotdat[!duplicated(plotdat[, c(5, 6)]),]

mypal <- c("Imputed" = "red", "Observed" = "black")

qplot(topTicketTurnoutSpring, turnout, data = plotdat, color = ImputedFlag) + 
  geom_abline(slope = 1, intercept = 0, linetype = 2, size = I(1.05), color =I("gray50")) + 
  theme_dpi() + 
  scale_color_manual(name = "Imputation", values = mypal) + 
  facet_wrap(~year) + scale_y_continuous("School Board Turnout", label = percent) + 
  scale_x_continuous("Top Ticket Turnout", label = percent) + 
  stat_smooth(method = 'rlm', aes(group = 1), se = FALSE, size = 1.1, color = I("blue")) + 
  theme(legend.position = c(0.08, 0.36))

@

If top ticket races drive voter turnout, then examining the degree to which school 
board turnout leads or lags top ticket races may provide some insight into the 
political activity in school board races independent of such races. Voter rolloff 
after the top ticket arises for a number of reasons including ballot design, 
lack of information, and the complexity of choices facing the voter in a given 
election \citep{wattenberg00}. In the non-partisan context of judicial elections, 
there is evidence that rolloff is lessened in competitive races where information 
is increased \citep{streb09}. 

To estimate rolloff, I apply the same method described in Section 
\ref{subsec:turnout} to 
estimate school district level voter turnout in top ticket races. This method 
poses a few different complications when applied 
to the spring election. First, spring election records provided by the Wisconsin 
GAB use inconsistent reporting units depending on the top ticket of the race. This 
means that first the reporting units must be aggregated into MCDs correctly, before 
MCDs can be assigned to school districts. Second, in the spring of 2010 there was no 
statewide top ticket -- instead 
\Sexpr{iPer((length(springVotes$ImputedFlag[springVotes$ImputedFlag=="Observed2010" & springVotes$year == 2010])/length(springVotes$year[springVotes$year==2010]))*100)} of jurisdictions 
had a top ticket race of Wisconsin Appeals Court judges. The other jurisdictions 
had only local elections on the ballot. To avoid losing these observations, I impute 
the 2010 estimated turnout as if the top ticket was a state supreme court race or 
election for state superintendent.\footnote{Imputation was done using model averaging 
of three separate k-nearest-neighbor models using votes cast in other spring 
elections as the primary predictors.} I expect the majority of Wisconsin 
districts to exhibit rolloff in school board elections relative to these 
top ticket races. 

Figure \ref{fig:undervoting} shows the relationship between top ticket turnout 
and school board turnout. Imputed cases are shown in red to make them distinct. The 
dashed line represents a 1:1 relationship between turnout for the top ticket on the 
X axis and turnout for the school board race(s) on the Y axis. The solid line represents 
the line of best fit, which has a slope and intercept less than the dashed line 
in all years except for in the 2010 year where the top ticket turnout was estimated. 
Interestingly, rolloff is fairly small in all years, except for in 2011 where 
top ticket turnout was substantially elevated. 

This relationship will be explored further in subsequent chapters. Table 
\ref{tab:undervotestats} shows the annual trends in Wisconsin from 2007 through 
2012 for districts where school board races received more or fewer votes than the 
top ticket candidate. Overvote occurs more than we might expect. However, school 
districts are very small jurisdictions and across all of them in a given year, it 
is not impossible to believe that voters may be interested in local candidates, but 
relatively uninterested in the non-partisan statewide race at the top of the ticket. 

<<undervotetab, results='asis', echo=FALSE>>=
plotdat$vote_diff <- plotdat$topTicketTurnoutSpring - plotdat$turnout
OVbase <- length(plotdat$turnout[plotdat$turnout > plotdat$topTicketTurnoutSpring])
OVdistwide <- sum(plotdat$districtwide[plotdat$turnout > plotdat$topTicketTurnoutSpring])
# 
# length(plotdat$vote_diff[plotdat$vote_diff < 0]) / nrow(plotdat)
# length(plotdat$vote_diff[plotdat$vote_diff > 0]) / nrow(plotdat)

yearStats <- ddply(plotdat, .(year, ImputedFlag), summarize, 
                   overvote = length(vote_diff[vote_diff < 0]), 
                   undervote = length(vote_diff[vote_diff > 0]), 
                   sbturnout = mean(turnout), 
                   springturn = mean(topTicketTurnoutSpring))
yearStats$undervote_per <- yearStats[, 4] / (yearStats[, 3] + yearStats[, 4])
yearStats$overvote_per <- 1 - yearStats$undervote_per


names(yearStats) <- c("Year", "Impute?", "Districts Overvoting", "Districts Undervoting", 
                   "Avg.SB Turnout", "Avg.Top Turnout", 
                   "% Districts Undervote", "% Districts Overvote")
yearStats[, 5] <- iPer2(yearStats[,5]*100)
yearStats[, 6] <- iPer2(yearStats[,6]*100)
yearStats[, 7] <- iPer2(yearStats[,7]*100)
yearStats[, 8] <- iPer2(yearStats[,8]*100)


yearStats <- xtable(yearStats, label="tab:undervotestats", 
             caption = "Overvote and Undervote in Spring Elections." )
align(yearStats) <- c('p{.15in}','p{.5in}','p{.5in}', 'p{.5in}','p{.6in}','p{.6in}','p{.6in}',
                   'p{.6in}','p{.6in}')

print(yearStats, 
      include.rownames = FALSE, 
      format.args = list(big.mark = ",", decimal.mark = "."), 
      size = "footnotesize")

@

Some caveats include that school districts where there is no district wide seat 
elected may have multiple jurisdictions counting in their turnout numbers. Of 
the \Sexpr{length(plotdat$turnout[plotdat$turnout > plotdat$topTicketTurnoutSpring])} 
elections where this occurs, only \Sexpr{iPer(((OVbase - OVdistwide) / OVbase)*100)} 
of these elections were in jurisdictions where the school board seat was not 
district wide. This over vote is also fairly consistent across the years. 

<<eval=FALSE, echo=FALSE>>=
hist(table(plotdat$distid, plotdat$turnout>plotdat$topTicketTurnoutSpring)[,2])
@

\clearpage

\section{Conclusion}

Wisconsin is a valuable case for the study of school board elections. 
The statewide nature of this data collection allows for the exploration of the level 
of contestation and turnout in school board elections across a variety of contexts and 
within the same state political system. 

School boards, despite their lower ballot entry and campaign costs, are contested 
less than half the time. School board seats are less prestigious, carry little 
financial benefit for members, and often require late evening meetings -- making 
them less attractive to potential candidates. School boards are also not shown 
to be a stepping stone to further political office, reducing their attractiveness 
to potential political candidates. Despite this, the democratic potential for 
school boards remain high -- school board may be the most obtainable elected 
office in the U.S. democracy today. 

Chapter 3 will seek to explore further the predictors of candidates 
emerging for office by exploring what local and state level factors may explain the 
emergence of a challenger to a school board election. Theory suggests that events 
like failed school bond referenda, turnover in district leadership, or fiscal pressure 
may drive local challenges. Theory also suggests that changing the powers of 
the school board, partisan identification of school board candidates, or 
political polarization may drive school board challenges to emerge statewide. 
Evidence of these state and local factors will be evaluated to test whether 
theories of candidate emergence apply to school boards. 

With voters, the democratic potential is much lower. Voters vote less in 
school board elections as well. In Wisconsin school board elections 
are held during the non-partisan spring elections, which have much lower turnout 
than partisan fall elections. In general, school board voter turnout hovers around 
20\% in school districts, but has plenty of variability. Voter turnout should be 
depressed in school board elections because of both their non-partisan nature and 
their lower probability of being contested. School board voters also face an 
information deficit with much less information about the policy positions of 
candidates, incumbents, or the school district as a whole. 

Chapter 4 will further explore the puzzle of low school board turnout. I test 
multiple theories of school board turnout in the new domain of local school 
board elections and evaluate how well they explain variability within and between 
school board elections. 

Chapter 5 will evaluate the effect of statewide policy shocks like the passage 
of Act 10 and budget cuts. This will represent the fullest test of dissatisfaction 
theory to date and the first time exogenous policy shocks are leveraged to 
explore the causal relationship between changes in policy and voter turnout. 

In Chapter 6 I take up a final question of whether or not the results of school 
board elections matter. I investigate if contestation for school board seats 
or incumbent defeat have impacts on school district policy. I look for impact 
of school board elections on student outcomes, district leadership, and district 
finances. 

