\chapter{Describing Wisconsin School Board Elections}
\label{chap:wisco}
\chapterstyle{deposit}




\section{The Wisconsin Case}

As noted in Chapter \ref{chap:intro}, this dissertation focuses on a 
single state -- Wisconsin. Wisconsin is located in the Midwest and ranks 
23rd among U.S. states in terms of total area, 20th in terms of population size 
with 5.7 million residents, and has over 420 local school districts.\footnote{All facts from US Census.} Recently, Wisconsin has become a crucial swing state exhibiting a close split 
between Republican and Democratic voters in presidential politics. Wisconsin, 
like many other states in the Midwest is a state that grants much of the power and authority 
in school district decision making to local school boards -- a so-called ``local 
control'' state. This is also why Wisconsin, in contrast to Southern states for example, 
has such a large number of school districts with relatively small sizes. 
Prior studies of school boards like those of \citet{RefWorks:311,RefWorks:214} have 
taken place in states with larger school districts and more centralized state 
control. Thus, Wisconsin serves as a good exemplar for other ``local control'' 
jurisdictions where school boards have more authority relative to the state 
government. Another advantage of selecting Wisconsin is the comparative advantage
I have had in gathering the necessary data to study a substantial proportion of the 
school board races within the state.\footnote{For details on this, see the 
Appendix \ref{app:data}.} A final advantage is the ability 
to test theories of the linkage between school board and state level politics thanks 
to the dramatic shock to education policy that accompanied the election of Wisconsin 
Governor Scott Walker in 2010. Taken together, these advantages mean that the in-depth 
study of school board elections across the entire K-12 educational system in Wisconsin 
can provide a new perspective on theories of candidate emergence in local elections, 
voter turnout in non-partisan off-cycle local races, and federalist linkages between 
state and local governments. 

In this chapter I address the unique case of Wisconsin by providing a descriptive 
overview of the legal and the electoral landscape for school board races within 
the state. I start by describing the ways in which the laws governing 
school board races vary from more familiar legislative races. Next, I describe the data 
I have collected on school board election results in detail and provide descriptive 
statistics of the frequency of incumbency challenges and open races, voter turnout, 
and the socio-demographic diversity of the constituencies served by Wisconsin school 
boards. This overview serves as the groundwork for the three subsequent chapters 
which examine how well theories of political engagement explain candidate emergence, 
voter turnout, and policy shifts in school board elections. 

\section{Background and Legal Basis of Wisconsin School District Elections}
\label{sec:wiscolaw}
This project represents the first attempt to comprehensively study the patterns 
in school board elections across an entire state over multiple years. Before 
examining the patterns that emerge both within and between school districts, 
it is important to first explore the data available on school board elections. 
Wisconsin, like many other Midwest states and unlike states in the South, is a 
local control state. This means that Wisconsin school districts have revenue 
authority independent of municipalities and counties, and are governed by 
a non-partisan elected board independent of other local government 
bodies. The independence of Wisconsin school districts is established in the 
state constitution and through state law (WI Const. art. X, \S 3 and Wis. Stat 120.10). 

This independence gives Wisconsin school districts considerable power and authority. 
Importantly, school boards administer their own elections and retain their own 
election records. This represents a serious barrier to studies of school board 
elections due to the burden associated with collecting and organizing school board 
elections from over 420 independent administrative entities. This is why previous studies of 
school boards have tended to focus on candidates, random samples of school boards, 
or on states with county-wide school boards such as North Carolina or Georgia. 

A benefit of the independence of Wisconsin school boards is the opportunity for study 
their organizational diversity presents compared to other states. While Wisconsin school 
board elections are held consistently on the same dates across 
the state, during the spring non-partisan election cycle, the size and distribution 
of board seats is largely locally determined. The spring primary election is the 
third Tuesday in February, and the spring general election is the first Tuesday 
in April (Wis. Stat \S 120.06). Wisconsin school boards must have between 3 and 9 
members with some exceptions made for boards of 11 members (Wis. Stat \S 120.01). 
Board member terms are not consistent across school boards, though 3 year terms are 
the most common with limited exceptions for terms of 1 or 2 years (Wis. Stat \S 120.06 (3)). 
Board members are elected by a plurality and must be residents of the district to 
be eligible for office (Wis. Stat \S 120.06 (2) (a)). All candidate verification, 
ballot preparation, and election announcement is the responsibility of the school district 
clerk (Wis. Stat \S 120.06 (8)) -- often a role filled by a board member. Primary 
elections occur if there are more than 
twice as many candidates as there are members to be elected (Wis. Stat \S 120.06 (7) (b)). 
School boards may choose to apportion their seats in dramatically different ways 
ranging from a board of 3-9 members each representing the entire district, to a board 
of 3-11 members each representing either a specific region of the school district or 
the entire district. The only restriction on the way seats are allocated is that the 
plan is proposed with a petition by a varying threshold of voters and passed by the board 
at an annual meeting or through an election (Wis. Stat \S 120.02 (2)). 


\begin{table}[h!]
\begin{center}
\caption{Wisconsin Election Dates}
\label{tab:elecdates}
\begin{tabular}{| p{.3\textwidth} | p{.6\textwidth} |}
\hline
\textbf{Election}  & \textbf{Date}  \\ \hline
Spring Primary  & Third Tuesday in February  \\ \hline
Spring General &  First Tuesday in April  \\ \hline
Fall Primary & Second Tuesday in August \\ \hline
Fall General & First Tuesday in November\\ \hline
\end{tabular}
\end{center}
\end{table}

My study distinguishes itself from many other studies of school board elections through 
its use of official election results provided directly by school boards to determine 
the results of the elections. In Wisconsin, school boards are the official holder of all school district election results. This means that official school board election records are maintained solely by 
school districts themselves and gathering school board election results in Wisconsin 
requires requesting records from individual school districts.\footnote{See Appendix 
\ref{app:data} and the Appendix \ref{app:log} for details on the request process.} These election records come in many forms and though school boards are required by law to retain 
these records, the record keeping is often incomplete, unclear, or confusing (Wis. 
Stat \S 120.06 (8) (g)).\footnote{While a few enterprising county clerks have 
collected school board election results and made them available online, however these can be incomplete 
by only including the precincts that are within the county. They also are not official. 
\citep[personal communication with][]{clerk1}.} In order to conduct this study then, a records 
request was made to all 424 public school districts in the state of Wisconsin. 
This request was e-mailed to the school district administrator in each of Wisconsin's 
424 school districts in January of 2013. Three follow up waves were conducted throughout 
2013, and at the end of the collection period, 313 
districts responded with records. The official and preferred 
records of the election requested included the Statement of the Board of Canvass 
and the Certificate of the Board of Canvass. These two documents are legally mandated 
for each school board election and certify the winner for each school board seat, 
as well as the votes cast for each candidate. When these were unavailable, a less 
official record such as a tally sheet from the election or a vote count spreadsheet 
was requested. Full details on the data collection process can be found in Appendix \ref{app:data}. 
These records were then transcribed from the various records provided by school 
districts into spreadsheets that combined together form the key database for this 
analysis. 

The median district provided 
11 
years of records.\footnote{While each district was requested to provide the maximum amount of records legally required to be retained, ten years, many districts were unable to locate complete 
records going this far back.} Overall, records were provided on 4,204 school 
board races involving 5,866 candidates in the state. For each election 
the votes received by each candidate was recorded, as well as whether the candidate 
won, was an incumbent, was a repeat candidate in the school district, or was a 
minor candidate. For each race, whether the candidate was running for district 
wide or regional seat was also recorded. 

Using the names, vote totals, and winners from each school board election allows 
for the construction of measures of the number of candidates in each election 
cycle, the number of contested seats, the level of voter participation, and other 
metrics of electoral activity at the school board level. Importantly, because the 
data was collected for several years in each district, time-variant trends can be 
explored. 


\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{figure}
\includegraphics[width=\maxwidth]{../../phd_figs/chap3-boardsize-1} \caption[Boxplot of the Number of Seats Per District]{Boxplot of the Number of Seats Per District\label{fig:boardsize}}
\end{figure}


\end{knitrout}

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{figure}
\includegraphics[width=\maxwidth]{../../phd_figs/chap3-yeargraph-1} \caption[Number of Districts Providing Records by Year]{Number of Districts Providing Records by Year\label{fig:yeargraph}}
\end{figure}


\end{knitrout}



\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{figure}
\includegraphics[width=\maxwidth]{../../phd_figs/chap3-racesgraph-1} \caption[Number of Races Provided by Districts]{Number of Races Provided by Districts. Red line indicates the median.\label{fig:racesgraph}}
\end{figure}


\end{knitrout}





The good news is that the most crucial period of the sample, from 2007 to 2012, is 
the period with the most complete set of records. The mean district provided records on 
13.4 school 
board races. 284 districts had 
a race in each year between 2007 and 2012, while 29 
did not. I distinguish these cases from others by verifying the absence of a ballot 
for school board, as opposed to the absence of records. 

\section{The Diversity of Wisconsin School Districts}

The authority given to school districts in Wisconsin to determine their own electoral 
rules and structure make Wisconsin a useful case in exploring the variation in 
school board electoral participation across contexts. In addition to the legal 
variation in electoral rules across school districts, Wisconsin school districts 
also vary widely in size, wealth, performance, and student and household demographics. In order to 
explore this diversity and to demonstrate the representativeness of the school 
districts that responded to the request for records, I now explore several aspects 
of Wisconsin school districts. 

\subsection{Comparing the Sample to the Population}



% latex table generated in R 3.1.2 by xtable 1.7-4 package
% Tue Dec 16 17:59:13 2014
\begin{table}[ht]
\centering
{\scriptsize
\begin{tabular}{p{1.5in}p{.8in}p{.8in}p{.8in}p{.8in}}
  \hline
 & Sample (mean) & Sample (SD) & Out of Sample (mean) & Out of Sample (SD) \\ 
  \hline
Total Population & 16,608.00 & 39,685.00 & 8,002.00 & 8,586.00 \\ 
  Membership & 2,483.00 & 5,652.00 & 1,233.00 & 1,284.00 \\ 
  \% FRL & 35.28 & 15.06 & 38.34 & 16.72 \\ 
  Millrate & 9.46 & 2.08 & 9.35 & 2.64 \\ 
  \% Republican & 58.00 & 10.00 & 57.00 & 10.00 \\ 
  \% Bachelor+ & 16.00 & 7.00 & 15.00 & 7.00 \\ 
  \% White Pop. & 94.00 & 8.00 & 95.00 & 5.00 \\ 
  Avg Teach. Sal. (\$) & 51,827.06 & 6,244.48 & 49,962.39 & 6,552.87 \\ 
  Avg Teach. Fringe (\$) & 26,564.57 & 3,424.95 & 26,325.68 & 3,159.97 \\ 
  Median Income (\$) & 33,099.11 & 8,111.48 & 32,131.95 & 8,058.61 \\ 
  \% Owner Occupied & 67.00 & 13.00 & 65.00 & 15.00 \\ 
  Acct. Balance per Member & 4,524.66 & 2,948.17 & 6,087.54 & 3,907.58 \\ 
  Teacher-Pupil Ratio & 14.26 & 1.93 & 13.47 & 2.20 \\ 
  EQV per Member (\$100k) & 10.64 & 23.64 & 13.15 & 19.93 \\ 
   \hline
\end{tabular}
}
\caption{Comparing school districts that provided board election results to those that did not and are not included in the study. Data 
             from the 2010-2011 school year.} 
\label{tab:samplecomp}
\end{table}


% Describe above table

As shown in Table \ref{tab:samplecomp}, there is little difference between districts 
in and out of the sample for the year 2011 on a range of measures of school district 
characteristics. Politically, the sample and the non-respondents reflect the rest of 
the state of Wisconsin -- evenly split. The groups have similar levels of student 
economic disadvantage as measured by eligibility for free and reduced price lunch and 
similar proportions of minority students in their schools. 
Their communities have similar levels of income, owner occupied housing, and levels 
of education. Teacher salary and fringe benefit rates are also nearly identical, as 
is the teacher-pupil ratio.\footnote{2012 was selected as an exemplar year, but 
the pattern holds for all available years from 2007-2012, which comprise the focus 
of this study.} 

The biggest discrepancy is that sample districts tend to be larger on average than 
out-of-sample districts in terms of student membership. This is no surprise as the largest 
Wisconsin school districts publish their election results online, making them among 
the easiest to obtain. This makes my coverage of the largest Wisconsin school 
districts perfect, while my coverage of the smallest Wisconsin school districts 
is lower. The sample districts tend to have slightly smaller account balances or 
district savings accounts on a per pupil basis which is likely related to their larger size. 
Finally, sample districts tend to have less property value per member, or taxable 
assets to raise revenue from, owing to the slightly higher populations of sample 
districts and the inclusion of all urban areas. All of these differences, however, 
are within one standard deviation of the mean from one another and do not represent 
a significant deviation either statistically or substantively. 
\clearpage
\subsection{The Bigs and the Smalls}

Wisconsin, like other states with independent school districts, has a great diversity 
in school district size, demographic make up, and structure. To illustrate the wide 
array of organizations that school boards in Wisconsin govern, I present Tables 
\ref{tab:small5} and \ref{tab:big5} describing the five smallest and five largest 
school districts in Wisconsin and how 
they compare on the variables above in Table \ref{tab:samplecomp}. These tables are intended 
to illustrate the range of organizational contexts that govern public K-12 education 
in Wisconsin and to illustrate the diversity of jurisdictions within which school 
board members are contesting elections. Table \ref{tab:small5} shows that the smallest 
school districts in Wisconsin have fewer than 100 students and fewer than 1,000 
residents. Smaller districts also tend to be much higher percentage Republican, 
less low-income, whiter, and have less disparity between the average teacher 
salary and the median income in the community. Contrast this with Table \ref{tab:big5} 
where the student population is 200 to 300 times larger than the smallest districts, 
the electorate is much more Democratic, student poverty is higher, and teacher 
salaries and median incomes are more divergent. 

% latex table generated in R 3.1.2 by xtable 1.7-4 package
% Tue Dec 16 17:59:13 2014
\begin{table}[ht]
\centering
{\scriptsize
\begin{tabular}{p{1.25in}p{.8in}p{.8in}p{.8in}p{.8in}p{.8in}}
  \hline
 & WASHINGTON & NORWAY J7 & HERMAN \#22 & GENEVA J4 & LINN J4 \\ 
  \hline
Total Population & 707.00 & 677.17 & 511.00 & 672.58 & 363.88 \\ 
  Membership & 71.00 & 86.00 & 88.00 & 101.00 & 107.00 \\ 
  \% FRL & 33.33 & 24.10 & 41.18 & 0.00 & 50.82 \\ 
  Millrate & 3.73 & 8.39 & 8.03 & 3.03 & 3.72 \\ 
  \% Republican & 60.21 & 74.54 & 85.25 & 67.88 & 68.13 \\ 
  \% Bachelor+ & 22.16 & 15.36 & 7.70 & 27.60 & 20.86 \\ 
  \% White Pop. & 98.37 & 97.83 & 97.23 & 92.50 & 96.54 \\ 
  Avg Teach. Sal. (\$) & 50,959.00 & 39,289.00 & 52,582.00 & 50,767.00 & 45,573.00 \\ 
  Avg Teach. Fringe (\$) & 28,925.45 & 24,550.98 & 26,201.78 & 28,825.53 & 24,192.63 \\ 
  Median Income (\$) & 28,500.00 & 44,410.00 & 34,050.00 & 31,860.00 & 32,930.00 \\ 
  \% Owner Occupied & 42.39 & 90.67 & 75.49 & 62.46 & 50.57 \\ 
  Acct. Balance per Member & 7,783.26 & 11,863.61 & 1,642.26 & 9,850.56 & 15,398.20 \\ 
  Teacher-Pupil Ratio & 7.30 & 9.80 & 13.80 & 14.90 & 9.90 \\ 
  EQV per Member (\$100k) & 44.95 & 19.78 & 16.01 & 91.31 & 78.45 \\ 
   \hline
\end{tabular}
}
\caption{Some attributes of Wisconsin's 5 smallest school districts. Data 
             from the 2010-2011 school year.} 
\label{tab:small5}
\end{table}


% latex table generated in R 3.1.2 by xtable 1.7-4 package
% Tue Dec 16 17:59:13 2014
\begin{table}[ht]
\centering
{\scriptsize
\begin{tabular}{p{1.25in}p{.8in}p{.8in}p{.8in}p{.8in}p{.8in}}
  \hline
 & MILWAUKEE & MADISON METROPOLITAN & KENOSHA & RACINE UNIFIED & RACINE \\ 
  \hline
Total Population & 595,525.00 & 233,901.44 & 123,252.37 & 139,079.00 & 139,079.00 \\ 
  Membership & 85,239.00 & 25,347.00 & 22,934.00 & 21,595.00 & 21,595.00 \\ 
  \% FRL & 77.43 & 48.74 & 47.82 & 59.43 & 59.43 \\ 
  Millrate & 10.75 & 11.06 & 10.60 & 8.41 & 8.41 \\ 
  \% Republican & 25.35 & 22.44 & 46.66 & 49.32 & 49.32 \\ 
  \% Bachelor+ & 15.34 & 27.29 & 16.63 & 15.21 & 15.21 \\ 
  \% White Pop. & 44.67 & 77.77 & 79.86 & 72.99 & 72.99 \\ 
  Avg Teach. Sal. (\$) & 62,672.00 & 52,193.00 & 58,506.00 & 53,664.00 & 53,664.00 \\ 
  Avg Teach. Fringe (\$) & 41,142.57 & 22,959.76 & 32,238.22 & 28,056.95 & 28,056.95 \\ 
  Median Income (\$) & 23,290.00 & 33,070.00 & 29,400.00 & 29,720.00 & 29,720.00 \\ 
  \% Owner Occupied & 44.49 & 46.02 & 56.95 & 63.00 & 63.00 \\ 
  Acct. Balance per Member & 1,770.42 & 2,377.47 & 1,947.45 & 1,419.72 & 1,419.72 \\ 
  Teacher-Pupil Ratio & 19.60 & 13.80 & 15.20 & 15.10 & 15.10 \\ 
  EQV per Member (\$100k) & 3.57 & 9.16 & 4.17 & 4.52 & 4.52 \\ 
   \hline
\end{tabular}
}
\caption{Some attributes of Wisconsin's 5 largest school districts. Data 
             from the 2010-2011 school year.} 
\label{tab:big5}
\end{table}


The larger districts shown in Table \ref{tab:big5} are representative of the 
kind of local governments that political scientists have typically studied -- 
large urban centers. This study will include such districts, but also include over 
290 smaller jurisdictions which are more representative of the vast majority of 
school board offices and school board elections across the country \citep{oliver12, RefWorks:321}. 




\clearpage

\subsection{General Elections, Primaries, and Special Elections}

General elections for school board members follow the schedule described in Section 
\ref{sec:wiscolaw}. However, for this project, I requested records for \emph{all} elections 
for school board office including school board member primaries and special elections. 
School board primaries occur when the number of candidates exceeds twice 
the number of seats open in a race.\footnote{In Wisconsin first class cities, 
only Milwaukee during the period of study, a primary must be held whenever there are more than two candidates for 
a race. Wis. Stat \S 8.11 (2m)} Special 
elections occur either if a vacancy occurs in a specific window or in a first class 
city, or if a candidate is recalled under Wis. Stat \S 9.10 (1) (a) 
which states that a petition for recall must be signed by electors equal 
in number to at least 25\% of the votes cast for the office of President of the United 
States at the last election within the same jurisdiction.\footnote{It is unclear if this 
would hold for school districts because the determination to hold the election is made by 
school district election official, who may determine that a reliable count of votes cast 
is not available and thus may defer to a formula specified in statute to determine the 
number of petitioners required to initiate a recall. Wis. Stat \S 9.10 (1) (c) to (d). 
Cited in a Staff Brief by the Joint Legislative Council Special Committee on Election 
Law Review, October 2004 \url{http://libcd.law.wisc.edu/~wilc/sb/sb\_2004\_07.pdf}} 
A special election is also required to fill a vacancy for board of school directors 
in the Milwaukee Public School system (MPS) [Wis. Stat \S 8.50 (intro.)]. A 
special election is not required to fill a vacancy for any other school district - 
instead vacancies are filled by appointment of the remaining members [Wis. Stat \S 17.26 (1)]. 


% latex table generated in R 3.1.2 by xtable 1.7-4 package
% Tue Dec 16 17:59:28 2014
\begin{table}[ht]
\centering
\begin{tabular}{rrrr}
  \hline
 & General & Primary & Special \\ 
  \hline
2002 & 278 &  12 &   2 \\ 
  2003 & 321 &  21 &   0 \\ 
  2004 & 336 &  17 &   0 \\ 
  2005 & 330 &  19 &   1 \\ 
  2006 & 365 &  12 &   3 \\ 
  2007 & 400 &  16 &   0 \\ 
  2008 & 379 &  13 &   0 \\ 
  2009 & 395 &  15 &   1 \\ 
  2010 & 394 &  16 &   0 \\ 
  2011 & 394 &  12 &   0 \\ 
  2012 & 396 &  22 &   0 \\ 
   \hline
\end{tabular}
\caption{Number of records for general, primary, and special school board elections 2002-2012.} 
\label{tab:electype}
\end{table}


For the entire data set from 2002-2012 there are 4,022 
general election races,175 
primary election races, and 7
special elections. Table \ref{tab:electype} shows the number of races of each type 
for the period between 2002 and 2012. In all, 101 districts 
reported a primary, with 101 
reporting a primary between 2002 and 2012. Only 5
district reported a special election during this period, and 313 
reported a general election race. 

Since Wisconsin school boards are non-partisan offices, a primary is not a symbol of 
an ideological challenge to an incumbent or a battle to win the votes of 
strict partisans. Instead, a primary is a signal of a substantial level of candidate 
activity for a school board race. 

Only a single recall election occurred during the 2007 to 2012 period. This was a
recall election held on December 29$^{th}$, 2009 in the Crivitz school district which 
was triggered after a petition against school board member David Kwiatkowski. Mr. Kwiatkowski 
resigned his seat that November in the face of the recall petition, but the recall 
election was still held. This special election raised several important issues that 
are indicative of the challenge surrounding the study of local elections. First, 
it was unclear how Wisconsin's recall statutes apply in the case of school boards. 
The recall statute allows for a recall based on the number of petitioners equal to 
at least 25\% of the vote cast for the office of Governor at the last gubernatorial 
election held within the same jurisdiction. \footnote{\url{http://gab.wi.gov/sites/default/files/publication/64/recall_of_local_elected_officials_manual_2009_06_p_13139.pdf}} As discussed above, Wisconsin does not 
have official records on the number of votes cast for each office by school district 
jurisdiction and in this case the threshold was calculated by the district administrator 
to be 668 - which is roughly the average number of voters who voted for school board. 
An additional difficulty was the overlap between many officials involved in the 
recall process in this small jurisdiction had overlapping responsibilities and allegations 
of conflicts of interest arose as a result -- leading to appeals to the Wisconsin 
Governmental Accountability Board.  
\footnote{For a full account of this 
particular case, see the Peshtigo Times article online \url{http://www.peshtigotimes.net/?id=12617}} 
In general, school board elections have fewer primary and special elections than 
their legislative counterparts. This leads to the biggest question in the school 
board literature from Chapter \ref{chap:intro}. 

\subsection{Contestation: Frequency and Context}

The biggest question in the school board literature seems to be -- are school 
board elections contested, and if so, when \citep{RefWorks:344, RefWorks:336, RefWorks:340}? 
While Chapter \ref{chap:candidacy} 
will explore when candidates emerge for school board elections, this section will 
provide a descriptive look at how often elections are contested, and how this varies compared to 
other elected bodies. 

Unlike studies of congressional or state legislative races, where the barriers to 
appearing on the ballot are generally understood, I begin by discussing the decisions 
a potential school board candidate faces when deciding to run. To appear on the 
ballot in the spring election a candidate may not begin circulating nomination 
papers prior to December 1 in the previous year. The nomination papers must be 
filed no later than 5 p.m. on the first Tuesday in January preceding the election. 
(Wis. Stat \S 8.10 and 8.15). The number of signatures by electors varies in statute, 
depending on the proximity of the school district to cities. In Milwaukee Public Schools 
candidates must obtain between 400 to 800 signatures within the jurisdiction they 
are running to represent (either across the school district, or a specific region 
of the district). 
If the school district contains any territory that lies within a second class city, a 
candidate must obtain between 100 and 200 signatures. School districts that have no 
territory that lies within a first or second class city are free to determine 
whether or not require nomination papers.\footnote{Milwaukee is the only first 
class city that meets all requirements in Wis. Stat \S 62.05 (I). There are currently 
sixteen second class cities in Wisconsin, and two more which qualify but have not switched 
status yet. The second class cities are Madison, Green Bay, Kenosha, Racine, Appleton, 
Waukesha, Oshkosh, Eau Claire, Janesville, West Allis, La Crosse, Sheboygan, Wauwatosa, 
Fond du Lac, Brookfield, and Superior.} [Wis. Stat \S 120.06 (a)] The statutes specify that these remaining districts can choose to require nomination papers from candidates, but may only require 
between 20 and 100 signatures of electors [Wis. Stat \S 8.10 (3) and 8.15 (6)]. In 
jurisdictions that do not require elector signatures, candidates must file a declaration 
of candidacy to register for the election with the election clerk in the school district.
After meeting these requirements the candidate will appear on the spring ballot as 
a candidate for school board. Outside of first and second class cities, running for school board presents very few barriers to entry for potential candidates. Even 
within first and second class cities, candidates face lower formal barriers than 
candidates for legislative or executive office. Coupled with the low cost of school board campaigns, most often fewer than \$1,000, the campaign presents 
very little friction toward serving on a school board \citep{RefWorks:322}. If we 
observe low levels of candidate participation in school board races, then, we must 
look to other explanations. 
%TODO: Explain why this is so and how the current study contributes to this

To explore candidate participation, let's consider the pool of school board races between 
2002 and 2012 for which records were successfully obtained. Of the 4,204, I focus on the 4,022 
general elections. Of these general election races, 
2,867 feature 
two or more candidates who either were on the ballot or garnered more than 10 votes.\footnote{
It is not uncommon in school board races for a write-in candidate to garner well over 10 votes. Thus, candidates not appearing on the ballot but receiving over 10 votes are included in the 
dataset. Candidates under 10 votes are collapsed into a category of scatter votes.} 
However, it is important to note that in many school districts voters select more than 
one candidate for each seat and elect the top N vote recipients to the board. A 
better measure of contestation is to see how many races featured more candidates than 
winners - 1,864 
races featured this, or 46.34510.19393.337\% of all races. 

Next, let's look at how often incumbents stand for election and how often they are 
defeated. In order to code incumbency, two data sources were used. First, if a 
candidate appeared in consecutive races and was coded as a winner in the prior 
race, they are coded as an incumbent. However, for races that were the beginning 
of the dataset, incumbency was coded using a master roster of known school board 
members provided by the Wisconsin Department of Public Instruction to the author.\footnote{
This collection is not required or official, but is maintained by the DPI in partnership with 
the Wisconsin Association of School Boards.} This collection indicates name, school district, 
and year of service for school board members in Wisconsin. Candidates appearing on the ballot 
in the early years of a school district's election records were cross referenced against this 
list to infer their incumbency status. 



% More candidates than seats

A basic requirement for voters to express a choice is to have multiple options to 
choose from. In order to assess this I first identify the number of races where 
there are more candidates on the ballot than winners. This is a nominal measure 
of the level of choice that voters are presented with. 46\% 
of races feature at least one more candidate than the number of winners. However, 
while this represents the number of candidates appearing on the ballot, it does 
not provide an indication of the seriousness of the challenge. Merely having  
multiple candidates is not the same as having a contested election. Political scientists 
focus on serious candidates and quality challengers. Measuring challenger quality 
in elections is difficult, but particularly difficult in non-partisan 
off-cycle elections like school boards \citep{oliver12}. In lieu of a better measure, I restrict the sample only to candidates that garner at least 20 votes -- which represents 1.39\% of the votes cast in the median school board race. 
This represents arguably a conservative estimate, because in some cases a write-in candidate may garner 20 votes and in larger jurisdictions 20 votes are easier to come by than in smaller jurisdictions. Once I filter out all cases where a candidate received fewer than 20 votes, the level of contestation is 31.4\% of general election races. In Wisconsin 
school board races candidates may appear on the ballot but not garner even 20 votes. Other times, local election records did not distinguish between candidates who declared officially and any 
candidate who received votes.

% Challenger and incumbent


Another important type of contestation is how often incumbents are challenged. Incumbent 
defeat is important to normative conceptions of the functioning of democracy. %TODO:citation 
In general elections, 80.6\% of all races featured at least one incumbent. However, a more important figure is 
identifying how many races featured at least one challenger against an incumbent. 
46.9\% of Wisconsin school board general elections featured 
this pattern of contestation.  %TODO: Check citation here.
Only 34.5\% of races featured challengers that received more than 20 votes. \footnote{Some evidence to support the selection of 20 votes is that very few 
candidates that appeared on the ballot received fewer than 20 votes -- even in the 
smallest jurisdictions.} %TODO: Find evidence and count of this. 

Table \ref{tab:incumbentContest} shows the patterns of contestation in Wisconsin 
elections for the period from 2002-2012 for the approximately 400 races in each 
year. Two trends that appear are the decrease in uncontested incumbents running 
and contested open seats. Instead, there has been an increase in races featuring 
an open and uncontested seat. Chapter \ref{chap:candidacy} will investigate this 
more thoroughly.

% latex table generated in R 3.1.2 by xtable 1.7-4 package
% Tue Dec 16 17:59:29 2014
\begin{table}[ht]
\centering
{\small
\begin{tabular}{rllll}
  \hline
 & Incumbent Contested & Incumbent Uncontested & Open Contested & Open Uncontested \\ 
  \hline
2002 & 41\% & 11.2\% & 8.27\% & 39.6\% \\ 
  2003 & 43.3\% & 9.66\% & 8.41\% & 38.6\% \\ 
  2004 & 44\% & 11.6\% & 6.55\% & 37.8\% \\ 
  2005 & 41.8\% & 11.5\% & 10.6\% & 36.1\% \\ 
  2006 & 38.6\% & 10.1\% & 7.95\% & 43.3\% \\ 
  2007 & 37.8\% & 12.2\% & 9\% & 41\% \\ 
  2008 & 30.9\% & 13.5\% & 8.44\% & 47.2\% \\ 
  2009 & 34.7\% & 12.2\% & 7.85\% & 45.3\% \\ 
  2010 & 40.6\% & 9.9\% & 5.33\% & 44.2\% \\ 
  2011 & 38.8\% & 12.2\% & 5.84\% & 43.1\% \\ 
  2012 & 38.1\% & 11.4\% & 7.32\% & 43.2\% \\ 
   \hline
\end{tabular}
}
\caption{Races featuring a challenge to an incumbent 2002-2012.} 
\label{tab:incumbentContest}
\end{table}


% Comparisons

In comparison to school board races, legislative races at both the state and federal 
level have much higher rates of contestation. In 2012, 10 out of 435 (2.3\%) U.S. House 
races were uncontested, and none of the 33 U.S. Senate races were uncontested. 
While these races are considerably more attractive to candidates due to the career and financial 
opportunities they represent, they are also more difficult to qualify for and 
labor intensive to compete in. State legislative races also exhibit high level 
of contestation. Taking Wisconsin as an example, in 2012 only 26 of 99 seats (26.3\%) in the 
Wisconsin Assembly were uncontested, and only 8 out of 33 seats (24.2\%) in the Wisconsin 
Senate were uncontested in 2012 and 2010 combined.\footnote{All results provided 
by Ballotpedia.} Another comparison would be to compare contestation of partisan 
primaries in legislative districts. While partisan offices often face at least 
nominal contestation and contestation of partisan seats can be explained by the 
competitiveness of the seat (based on redistricting), looking at the contestation 
levels of primaries might provide a more apt legislative comparison. In the 2014 
U.S. House midterm primaries, only 314 of the 795 possible major party primaries (39.5\%)
were contested. \footnote{Ballotpedia. \url{http://ballotpedia.org/National_contested\_primary\_average\_during\_the\_2014\_U.S.\_congressional_elections}} This figure is on par with the level of 
contestation seen in school board elections. 

%TODO: Compare primaries, how often are they contested vs. school board?

Candidates have many fewer reasons to run for school board. Despite the low barrier 
of entry, serving on a school board is much less prestigous than other offices, 
requires attending evening meetings, and in most cases offers only a modest stipend 
and no benefits \citep{RefWorks:321,RefWorks:322}. 

% Some more discussion here

\subsubsection{Close Races}

In Table \ref{tab:incumbentContest} we see that school board elections are contested more often than the literature from Chapter \ref{chap:intro} would lead us to believe. In fact, 
school board races are about as contested as partisan primaries for Congress. However, 
Table \ref{tab:incumbentContest} represents an overestimate of contestation by 
using a generous definition of a serious contest. Another way to look at this is 
to look at the differential vote share between winners and losers and count the 
number of close races that have occurred in Wisconsin.  



For an analysis of the intensity of competitiveness in school board races, we turn 
our attention to races where voters have a choice -- those with serious candidates 
on the ballot. As we saw above, this is a much smaller subset of all races than 
the corresponding restriction would be for state or federal legislative offices. 
I restrict the sample to the 
0\% of 
general election races that feature more real candidates than winners. These races 
are most commonly for one, two, or three seats simultaneously. These multi-member 
districts pose a challenge in calculating the win margin and making comparisons 
across races with differing expected pluralities. 

Figure \ref{fig:winsandcandidatestable} shows the distribution of school board 
races by the number of winners and the number of candidates. From this figure 
it is clear that while a plurality of races feature 1 or 2 winners and only 1 or 
2 candidates the method for calculating vote margin has to be robust to a wide 
array of combinations of candidates receiving votes and number of winners for the 
seat. Table \ref{tab:votemargincalc} describes the ways of dealing with this in 
calculating the margin of victory in school board races. 


\begin{table}[h!]
\begin{center}
\begin{footnotesize}
\caption{Methods of Calculating Vote Margin}
\label{tab:votemargincalc}
\begin{tabular}{| p{.2\textwidth} | p{.45\textwidth} | p{.175\textwidth}| p{.175\textwidth}|}
\hline
\textbf{Name}  & \textbf{Method} & \textbf{Pros} & \textbf{Cons} \\ \hline
Share by Each  & $\sum \frac{votes_{iw}}{votes_{total}} - \sum \frac{votes_{il}}{votes_{total}}$ & Clean & Biased by lopsided races \\ \hline
Two-Means & $\frac{\sum \frac{votes_{iw}}{votes_{total}}}{n_{winners}} - \frac{\sum \frac{votes_{il}}{votes_{total}}}{n_{losers}}$ & Intuitive & Biased by lopsided races   \\ \hline
Maximum Value & $\sum \frac{votes_{iw}}{votes_{total}} - \frac{1}{n_{candidates}}n_{winners}$ & Normalized & Not intuitive \\ \hline
\end{tabular}
\end{footnotesize}
\end{center}
\end{table}

One method to do this is to take the share of votes won by each candidate as a start 
by taking votes for one candidate over the total votes cast in the election.\footnote{All 
school board elections in Wisconsin restrict voters to one vote per candidate -- 
though in multi-member districts voters may select two or three candidates total 
for election to office.} Then, the vote share for the winners is summed and the 
vote share for the losers is summed, and the difference is taken as the margin 
of victory for the winners. Another method takes the mean of the winners' vote 
share and the mean of the losers' vote share and differences these. A final measure 
captures the share of votes all the winners in the election captured above the 
maximum they can capture -- determined by the proportion of votes available to 
each candidate (1 over the number of candidates) multiplied by the number of winners. 
For a district with three candidates running for two seats, this would mean that 
the winners collectively need to win 66\% of the vote. If they win 70\% this equates 
to a margin of victory of 4\%. For a district with five candidates running for three seats, 
the winners collectively need to win 60\% of the vote. If they win 70\% of the vote 
this equates to a 10\% margin of victory, even though each candidate has only won 
on average 23.3\% of the vote in this race as compared to 35\% of the vote in the 
prior race. 

This final method is the best because it normalizes across the number of winners 
per race, but it has some limitations. First, school board race vote share measures 
are more heavily influenced by the presence of write-in candidates than state or 
federal legislative districts. This is because the average school board race has 
only 3,468 votes cast and the median 
race has only 1,498. A large number 
of scatter votes can thus swing the vote share calculation. Note that in the current 
data set, any candidate receiving more than 20 votes is counted as a candidate, but 
districts with many candidates receiving fewer than 20 votes will still be affected 
by this concern. This makes it possible for the winning candidates 
to collectively secure only 58\% of the votes and win election, resulting in a 
negative win margin from the expected total. 


%TODO: Find an example for the above

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{figure}
\includegraphics[width=\maxwidth]{../../phd_figs/chap3-winsandcandidatestable-1} \caption[Distribution of School Board Races by Candidates and Winners]{Distribution of School Board Races by Candidates and Winners.\label{fig:winsandcandidatestable}}
\end{figure}


\end{knitrout}


\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{figure}
\includegraphics[width=\maxwidth]{../../phd_figs/chap3-winmarginplots-1} \caption[Win Margin in Competitive School Board Races]{Win Margin in Competitive School Board Races.\label{fig:winmarginplots}}
\end{figure}


\end{knitrout}

Figure \ref{fig:winmarginplots} shows that contested school board races do not tend 
to be that close. On average, fewer than 25\% of the contested races have a win 
margin of less than 5 percentage points as indicated by the blue line. The average race sees the 
winners securing about 10 percentage points more votes than the losers. Thus, while 
school board races may have some level of contestation, the intensity of that 
contestation is called into doubt. 

% \subsubsection{Scattered Votes}
% 
% One adjustment to deal with this concern is to subtract out votes for write-in 
% candidates where possible. This is not always possible because voting records do not 
% always indicate in which school board race the scattered votes were cast. In most 
% cases, school board election clerks record candidates getting very few votes -- 
% less than 10 -- together into a single category of votes called "scatter". Though 
% these votes are largely inconsequential in federal and state legislative races, 
% in non-partisan local races with low vote counts they can make a significant 
% impact on measures of turnout, win share, and contestation. Of the iNum(nrow(dat)) 
% candidate-races of data on school board elections in Wisconsin, iNum(nrow(dat[dat$candidateid == 99, ])) 
% were scatter votes. 
% 
% Votes were labeled scatter in the Wisconsin data set for two reasons: first, all 
% candidates receiving fewer than 10 votes in a single race were compiled together 
% into a scatter category. This decision was put in place to reduce the data 
% collection burden that already involved hand coding 
% iNum(nrow(dat[dat$candidateid != 99,])) 
% candidate-race records. Including the "long-tail" of write-in votes, protest votes, 
% and spurious candidates would have added substantial burden to the data collection 
% process. 
% 
% Second, some jurisdictions reported their votes with a "scatter" category for 
% reporting in newspapers, to county election officials, 
% or for local reporting. In these cases, the threshold for a candidate being labeled 
% in the "scatter" category is unknown, however, for 
% iNum(nrow(dat[dat$candidateid == 99 & dat$votes > 20,])) 
% races it exceeds the threshold of 20 votes for label as a minor candidate, and for 
% iNum(nrow(dat[dat$candidateid == 99 & dat$votes > 200,])) 
% it exceeds 200. In these cases, it is important to consider how these votes should 
% be included in further analysis -- should they be subtracted from the total votes 
% in the district or should they be further collapsed into a category? 

%TODO: What should be done with these votes?



% \subsubsection{Write-in Candidates}
% 
% In only the rarest legislative elections are write-in candidates consequential with 
% only a handful of write-in candidates at the state or federal level over the past 
% 50 years making an impact at the polls. However, in school board elections in Wisconsin, 
% serious challenges and even victories by write-in candidates are frequent enough to 
% merit special consideration. Unfortunately, write-in candidates are often not 
% noted in election returns explicitly in Wisconsin school board elections. 

\clearpage

\subsection{Incumbent Defeat}

As we saw in Chapter \ref{chap:intro}, incumbent defeat is an important concept 
in the school board literature \citep{RefWorks:311,RefWorks:264}. Incumbent defeat has been shown to be 
difficult to measure in the school board election literature due to a lack of 
available records and the fact that most prior studies have relied on surveys of 
current and former school board members. Using self-reports and lists of current 
and past members of school board members does not provide a reliable way to distinguish 
between political and apolitical forms of turnover \citep{RefWorks:311}. Using 
incumbent electoral defeat is not a perfect measure, because it does not capture 
cases where an incumbent finds it not worth it to run for office. 


\includegraphics[width=\maxwidth]{../../phd_figs/chap3-incDefeat-1} 

\includegraphics[width=\maxwidth]{../../phd_figs/chap3-incDefeat-2} 



\subsection{Voter Turnout}
\label{subsec:turnout}

The spring elections in Wisconsin are decidedly low turnout affairs. Since 2000 
Wisconsin has had between 4 and 4.35 million voting age population residents. However, 
in this time period the spring election has seen around 800,000 votes cast on 
average with a peak of 1.5 million.\footnote{Statistics from a Wisconsin Government Accountability 
Board report, available online: \url{http://gab.wi.gov/sites/default/files/page/non\_partisan\_turnout\_2000\_2013\_pdf\_15069.pdf}}
Turnout is typically around 18\% in such elections. Unsurprisingly then, school 
board elections are also low turnout affairs. By comparison, 
in the November partisan general election voter turnout is around 70\% in the last 
three presidential elections, and around 48\% in the last three gubernatorial 
elections.\footnote{Statistics from a Wisconsin Government Accountability 
Board report, available online: \url{http://gab.wi.gov/sites/default/files/page/partisan\_voter_turnout\_statistics\_1948\_2012\_pdf\_20396.pdf}} \citet{teixeira92} suggests a 
rule of thumb that off-cycle partisan elections have a fifteen percentage point 
drop from the presidential election and non-partisan local elections experience a 
further fifteen point drop. This would mean Wisconsin should see 55\% turnout in 
gubernatiroal races and 40\% turnout in local elections. Numbers on typical school 
board election turnout are not available in the literature, so it is difficult to 
assess the degree Wisconsin's off-cycle races differ from other races nationally. 
In this section I will describe the approaches to estimating turnout in Wisconsin 
school board elections and the comparison of school board turnout to other 
electoral participation. 

A first concern with estimating turnout is finding the proper denominator. 
For the analysis here I elect to use Voting Age Population (VAP) as the measure for 
the denominator of the voter turnout calculation instead of registered or eligible 
voters. VAP is the only measure available both at a unit smaller than a school district 
and at the statewide level that can allow for consistent comparisons between the two. \
Unfortunately, the state of Wisconsin does not maintain county, municipality, or ward 
level registered voter or eligible voter counts historically -- though such figures can be obtained from the GAB around election time for a current election.

Estimating school board election turnout is decidedly difficult because it requires 
both a reliable assessment of the votes cast in the election and a reliable 
estimate of the voting age population in the school district. Due to the fact that 
school districts have diverse organizational structure, independent boundaries, 
and no requirements on election reporting to a central authority, it is often difficult to ascertain 
the number of votes cast by voters within the school district. To determine the VAP 
of the school district in Wisconsin, I employ the finest resolution 
estimate of voting age population available -- VAP estimates by minor civil division (MCD) 
produced by the Wisconsin Department of Administration.\footnote{ Minor civil division is a 
term used by the US Census Bureau to denote the primary governmental and/or administrative 
divisions within a county. In Wisconsin these include cities, towns, villages and 
unincorporated areas. Statistics available online: \url{http://gab.wi.gov/elections-voting/results}. 
Statistics for Wisconsin Minor Civil Divisions are maintained by the Department of Administration 
Demographic Services Center: \url{http://www.doa.state.wi.us/section\_detail.asp?linkcatid=11\&linkid=64\&locid=9}}
However, MCDs are not perfectly contiguous with school districts -- school districts 
are contiguous only at the ward level where VAP estimates are not available. In 
order to estimate the proportion of each MCD's VAP that belongs to a given school district, 
I use property tax records provided by the Wisconsin Department of Revenue (DOR). 
These records annually report for each school district every MCD that is located entirely or partially within the boundaries of the school district, as well as the share of property wealth 
(as measured by equalized values, or EQV), for that MCD that the school district 
is authorized to levy tax for. For each year, the share of every MCD's EQV that 
was allocated to each school district was calculated. I use this share to 
prorate the population of each school district both for the purposes of 
calculating the voting age population, and for calculating votes cast for and 
against candidates in statewide elections. An additional adjustment 
is made to interpolate the VAP for school districts to correct for adjustments in 
the creation and destruction of MCDs year to year which can influence the VAP 
estimates for a school district.\footnote{A sensitivity check was done 
to determine if weighting by residential property values only changed the estimates, but 
it did not. For more details see Appendix \ref{app:data}}

We can measure how accurate this estimation procedure is by comparing the official number 
of votes cast and voter turnout statewide to the statewide estimates derived by 
rebuilding voter data at the district level. 

% latex table generated in R 3.1.2 by xtable 1.7-4 package
% Tue Dec 16 17:59:31 2014
\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{p{.55in}p{.55in}p{.55in}p{.55in}p{.55in}p{.55in}p{.55in}}
  \hline
Year & Official Total Votes & Offical VAP & Offical Turnout & Estimated Total Votes & Estimated VAP & Estimated Turnout \\ 
  \hline
2002 & 1,785,710 & 4,060,973 & 44\% & 1,770,028 & 4,060,924 & 43.6\% \\ 
  2004 & 3,016,288 & 4,118,621 & 72.9\% & 2,961,919 & 4,079,302 & 72\% \\ 
  2006 & 2,166,671 & 4,260,038 & 50.9\% & 2,159,033 & 4,241,864 & 50.3\% \\ 
  2008 & 2,996,869 & 4,330,695 & 69.2\% & 2,981,638 & 4,321,981 & 68.7\% \\ 
  2010 & 2,171,331 & 4,372,347 & 49.7\% & 2,152,344 & 4,370,268 & 49.2\% \\ 
  2012 & 3,071,434 & 4,378,741 & 70.1\% & 3,053,558 & 4,375,320 & 69.7\% \\ 
   \hline
\end{tabular}
}
\caption{Comparing estimates of voter turnout derived from MCD estimates to official GAB turnout records.} 
\label{tab:turnoutEst}
\end{table}


As shown in Table \ref{tab:turnoutEst}, the estimation procedure accurately 
reproduces the statewide official turnout estimates. Using these estimates, 
are more confident that the procedure used generates 
reasonable estimates of the VAP at the school district level. This takes care 
of the denominator of the turnout equation. 

The numerator, the number of voters casting votes for school board, presents a 
second set of challenges. 
I begin by collecting election returns from as many school districts as possible 
in Wisconsin.\footnote{For details on the collection procedure see Appendix \ref{app:data}} 
However, unlike a top ticket race such as a presidential or gubernatorial race, 
the election rules vary across school district jurisdictions. In some districts, 
voters may have multiple votes to cast in the election -- eliminating the ability 
to judge voter turnout based on the number of votes cast. In other districts, only 
a subsection of the electorate may be eligible to vote for a school district office 
due to apportionment within the district. 

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{figure}
\includegraphics[width=\maxwidth]{../../phd_figs/chap3-turnoutgraph-1} \caption[Turnout for district wide school board races]{Turnout for district wide school board races.\label{fig:turnoutgraph}}
\end{figure}


\end{knitrout}

There is one set of cases for which estimating voter turnout is easy - the case 
where a school board seat is chosen district wide. As shown in Table \ref{tab:yearsample}, 
this is the vast majority of Wisconsin school districts. To determine if a seat 
was apportioned or district wide, I coded the seats for labels such as ``Area", ``District", 
``Region", or ``Village" as opposed to ``At-Large". As district wide is the default in state law, 
in the absence of evidence, I assume the race is district wide.  Figure \ref{fig:turnoutgraph} 
shows that district wide school board races feature an average turnout below 25\%. 

% latex table generated in R 3.1.2 by xtable 1.7-4 package
% Tue Dec 16 17:59:32 2014
\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{p{.5in}p{.8in}p{.8in}p{.8in}p{.8in}p{.8in}p{.8in}}
  \hline
Year & Districtwide Races & Districts with Districtwide & All Board Races & Total Districts & Districts without Districtwide & Non-districwide Races \\ 
  \hline
2001 &   7 &   7 &  11 &   8 &   1 &   4 \\ 
  2002 & 190 & 184 & 292 & 221 &  37 & 102 \\ 
  2003 & 203 & 201 & 342 & 243 &  42 & 139 \\ 
  2004 & 222 & 216 & 353 & 258 &  42 & 131 \\ 
  2005 & 212 & 206 & 350 & 256 &  50 & 138 \\ 
  2006 & 228 & 225 & 380 & 271 &  46 & 152 \\ 
  2007 & 251 & 249 & 416 & 299 &  50 & 165 \\ 
  2008 & 250 & 245 & 392 & 300 &  55 & 142 \\ 
  2009 & 255 & 250 & 411 & 299 &  49 & 156 \\ 
  2010 & 256 & 251 & 410 & 301 &  50 & 154 \\ 
  2011 & 263 & 256 & 406 & 305 &  49 & 143 \\ 
  2012 & 266 & 258 & 418 & 305 &  47 & 152 \\ 
   \hline
\end{tabular}
}
\caption{Comparing sample size for district wide vs. apportioned school board races.} 
\label{tab:yearsample}
\end{table}


Estimating turnout in the roughly 50 districts annually, as shown in Table \ref{tab:yearsample}, which do not have a district wide school board race is a different matter. 

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{figure}
\includegraphics[width=\maxwidth]{../../phd_figs/chap3-nondistraces-1} \caption[Turnout for non-district wide school board races]{Turnout for non-district wide school board races.\label{fig:nondistraces}}
\end{figure}


\end{knitrout}

Figure \ref{fig:nondistraces} shows the pattern for non-district wide races appears 
very similar under the estimation method of collapsing all races in a district 
into one race and dividing the votes counted by the number of winners. This 
represents an underestimate, as even districts with apportioned seats 
do not elect all portions of their district in the same election cycle or even 
have consistent apportionment from one cycle to the next.

%TODO: Explain this better.

Putting these two together, we can estimate overall voter turnout in school board 
races by school district, over time. To do this, we prefer the district wide race 
turnout. If no district wide race is present in a given district in a given year, 
we then use the adjusted districtwide turnout based on the apportioned seats 
available. 

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{figure}
\includegraphics[width=\maxwidth]{../../phd_figs/chap3-overallturnoutest-1} \caption[Turnout for school board races by school district]{Turnout for school board races by school district.\label{fig:overallturnoutest}}
\end{figure}


\end{knitrout}

Figure \ref{fig:overallturnoutest} shows the final estimate of the distribution 
of school board voter turnout among reporting districts across the years of data 
available. Both the median and the distribution of turnout by school district 
remains consistent from 2002-2010. However, 2011 and 2012 exhibit a sharp spike 
upward in voter turnout. These elections represent the first two spring elections 
after the passage of Act 10 and the election of Governor Scott Walker. 

\clearpage

\subsection{Rolloff}
\label{subsec:undervote}

The spring 2011 election is an example of why it is not accurate to attribute 
voter turnout in school board elections solely to the school board race. School 
board races are downticket from other races that are occuring during the spring 
non-partisan elections cycle in Wisconsin and the spring of 2011 was marked by 
a highly contested statewide race for the Supreme Court. The election was seen 
as a referendum on the recent passage of Act 10 and Governor Scott Walker's first 
year in office and was characterized by unprecedented turnout. The influence of 
the strength of weakeness of the top ticket race confounds our understanding 
of voter turnout in school board elections. One way to approach this is to consider 
studying the dropoff in votes cast from the statewide top of the ticket race to the school 
board races further down the ballot -- a phenomenon known as voter rolloff. For the 
2007-2012 period, I estimate the top ticket 
turnout in each school district. Importantly, in this period, several different 
office types were the top ticket due to the pattern of statewide office terms 
in Wisconsin. These consist of primarily state supreme court races, but as there 
seven justices elected to ten-year terms, the state supreme court does not have 
an election every spring: 

\begin{myitemize}
  \item 2007 - State Supreme Court Race
  \item 2008 - State Supreme Court Race and presidential primary
  \item 2009 - State Superintendent of Public Instruction
  \item 2010 - None. Wisconsin Appeals Courts (3 of 4)
  \item 2011 - State Supreme Court Race
  \item 2012 - Presidential Preference Primary
\end{myitemize}


\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{figure}
\includegraphics[width=\maxwidth]{../../phd_figs/chap3-undervoting-1} \caption[Spring Turnout For Top Ticket and School Board Compared]{Spring Turnout For Top Ticket and School Board Compared\label{fig:undervoting}}
\end{figure}


\end{knitrout}

If top ticket races drive voter turnout, then examining the degree to which school 
board turnout leads or lags top ticket races may provide some insight into the 
political activity in school board races independent of such races. Voter rolloff 
after the top ticket arises for a number of reasons including ballot design, 
lack of information, and the complexity of choices facing the voter in a given 
election \citep{wattenberg00}. In the non-partisan context of judicial elections, 
there is evidence that rolloff is lessened in competitive races where information 
is increased \citep{streb09}. 

To do this, I apply the same method described in Section \ref{subsec:turnout} to 
estimate school district level voter turnout, instead using records from spring 
election MCD votes. This method poses a few different complications when applied 
to the spring election. First, spring election records provided by the Wisconsin 
GAB use inconsistent reporting units depending on the top ticket of the race. This 
means that first the reporting units must be aggregated into MCDs correctly, before 
MCDs can be assigned to school districts. Second, in the spring of 2010 there was no 
statewide top ticket -- instead 
66.5\% of jurisdictions 
had a top ticket race of Wisconsin Appeals Court judges. The other jurisdictions 
had only local elections on the ballot. To avoid losing these observations, I impute 
the 2010 estimated turnout as if the top ticket was a state supreme court race or 
election for state superintendent.\footnote{Imputation was done using model averaging 
of three k-nearest-neighbor models using votes cast in other spring elections as the 
primary predictors.} I expect the majority of Wisconsin districts to exhibit an 
undervote in school board elections relative to these top ticket races. 

Figure \ref{fig:undervoting} shows the relationship between top ticket turnout 
and school board turnout. Imputed cases are shown in red to make them distinct. The 
dashed line represents a 1:1 relationship between turnout for the top ticket on the 
X axis and turnout for the school board race(s) on the Y axis. The solid line represents 
the line of best fit, which has a slope and intercept less than the dashed line 
in all years except for in the 2010 year where the top ticket turnout was estimated. 
Interestingly, roll off is fairly small in all years, except for in 2011 where 
top ticket turnout was substantially elevated. This provides some evidence that the 
new voters attracted to the spring race in 2011 were not as motivated by school board elections 
as the electorate in previous spring elections. This relationship will be explored 
further in subsequent chapters. 
Table \ref{tab:undervotestats} shows the annual trends in Wisconsin from 2007 through 
2012 for districts where school board races received more or fewer votes than the 
top ticket candidate. 

% latex table generated in R 3.1.2 by xtable 1.7-4 package
% Tue Dec 16 17:59:40 2014
\begin{table}[ht]
\centering
{\footnotesize
\begin{tabular}{p{.5in}p{.5in}p{.5in}p{.6in}p{.6in}p{.6in}p{.6in}p{.6in}}
  \hline
Year & Impute? & Districts Overvoting & Districts Undervoting & Avg.SB Turnout & Avg.Top Turnout & \% Districts Undervote & \% Districts Overvote \\ 
  \hline
2007 & Observed &  42 & 253 & 18.7\% & 21.9\% & 85.8\% & 14.2\% \\ 
  2008 & Observed &  47 & 249 & 17.1\% & 19.7\% & 84.1\% & 15.9\% \\ 
  2009 & Observed &  45 & 251 & 17.6\% & 20.7\% & 84.8\% & 15.2\% \\ 
  2010 & Imputed &  26 &  69 & 11.5\% & 15.9\% & 72.6\% & 27.4\% \\ 
  2010 & Observed &  90 & 110 & 14.2\% & 13.5\% & 55\% & 45\% \\ 
  2011 & Observed &  28 & 269 & 27.5\% & 35.1\% & 90.6\% & 9.43\% \\ 
  2012 & Observed &  41 & 260 & 21.2\% & 25.9\% & 86.4\% & 13.6\% \\ 
   \hline
\end{tabular}
}
\caption{Overvote and Undervote in Spring Elections.} 
\label{tab:undervotestats}
\end{table}


Some caveats include that school districts where there is no district wide seat 
elected may have multiple jurisdictions counting in their turnout numbers. Of 
the 319 
elections where this occurs, only 13.5\% 
of these elections were in jurisdictions where the school board seat was not 
district wide. This over vote is also fairly consistent across the years. 



\clearpage

\section{Conclusion}

Wisconsin is a valuable case for the study of school board elections. 
The statewide nature of this data collection allows for the exploration of the level 
of contestation and turnout in school board elections across a variety of contexts and 
within the same state political system. 

School boards, despite their lower barrier to ballot entry and campaign costs, are contested less than half the time. School board elections are less prestigious, carry little financial benefit 
for members, and often require late evening meetings -- making them less attractive 
to potential candidates. School boards are also not shown to be a stepping stone 
to further political office, reducing their attractiveness to potential political 
candidates. 

Chapter 3 will seek to explore further the predictors of candidates 
emerging for office by exploring what local and state level factors may explain the 
emergence of a challenger to a school board election. Theory suggests that events 
like failed school bond referenda, turnover in district leadership, or fiscal pressure 
may drive local challenges. Theory also suggests that changing the powers of the school board, 
partisan identification of school board candidates, or political polarization may 
drive school board challenges to emerge statewide. Evidence of these state and 
local factors will be explored and evaluated to test whether theories of candidate 
emergence explain the case of school boards. 

Voters vote less in school board elections as well. In Wisconsin school board elections 
are held during the non-partisan spring elections, which have much lower turnout 
than partisan fall elections. In general, school board voter turnout hovers around 
20\% in school districts, but has plenty of variability. Voter turnout should be 
depressed in school board elections because of both their non-partisan nature and 
their lower probability of being contested. School board researchers have long evaluated 
the dissatisfaction theory, which suggests that school boards exhibit higher contestation 
and voter turnout when local policy conditions change and the electorate is unsatisfied 
with the governance of the board. 

Chapter 4 will futher explore the puzzle of low school board turnout and identify 
if voter turnout does indeed respond to policy shocks. Local policy shocks such 
as leadership turnover and school fiscal challenges will be evaluated as well as 
statewide policy shocks like the passage of Act 10 and budget cuts. This will 
represent the fullest test of dissatisfaction theory to date and the first time 
exogenous policy shocks are leveraged to explore the causal relationship between 
changes in policy and voter turnout. 
