\chapter{Describing Wisconsin School Board Elections}
\label{chap:wisco}
\chapterstyle{deposit}


<<rsetup, results='hide', echo=FALSE, message=FALSE, warning=FALSE>>=
opts_chunk$set(fig.width=8, fig.height=6, message=FALSE, error=FALSE, 
               fig.path="../../phd_figs/chap3-",
               warning=FALSE, echo=FALSE, dev='pdf')

setwd("../../")
source("data/dataAssemble.R")
source("data/dataMerge.R")
library(plyr)
library(eeptools)
library(scales)
library(xtable)
options(xtable.include.rownames = FALSE, xtable.table.placement = "ht")

iNum <- function(x){formatC(x, big.mark = ",", digits = 2)}

# gpclibPermit()
#setwd("../../../MasterText")
#elec <- read.csv("data/electionpartisanshippanel.csv")
@



\section{Consider This}

Wisconsin is located in the region of the United States known as the Midwest and ranks 
23rd in terms of total area, 20th in terms of population size with 5.7 million residents, 
and has over 420 local school districts. Recently, Wisconsin has become a crucial swing state 
exhibiting a close split between Republican and Democratic voters in presidential 
politics.\citet{RefWorks:311} 

\section{Background and Legal Basis of School District Elections}

This project represents the first attempt to comprehensively study the patterns 
in school board elections across an entire state over multiple years. Before 
examining the patterns that emerge both within and between school districts, 
it is important to first explore the data available on school board elections. 
Wisconsin, like many other Midwest states and unlike states in the South, is a 
local control state. This means that Wisconsin school districts have revenue 
authority independent of municipalities and counties, and are governed by 
a non-partisan elected board independent of counties and other local government 
bodies. The independence of Wisconsin school districts is established in the 
state constitution. 

This independence gives Wisconsin school districts considerable power and authority. 
Importantly, school boards administer their own elections and retain their own 
election records. This represents a serious barrier to studies of school board 
elections due to the burden associated with collecting and organizing school board 
elections from over 420 administrative entities. This is why previous studies of 
school boards have tended to focus on candidates, random samples of school boards, 
or on states with county-wide school boards such as North Carolina or Georgia. 

Wisconsin school board elections are held consistently on the same dates across 
the state, during the spring election cycle. The spring primary election is the 
third Tuesday in February, and the spring general election is the first Tuesday 
in April (Wis. Stat \S 120.06). Wisconsin school boards must have between 3 and 9 
members with some exceptions made for boards of 11 members (Wis. Stat \S 120.01). 
Board member terms are not consistent across school boards, though 3 year terms are 
the most common with limited exceptions for terms of 1 or 2 years (Wis. Stat \S 120.06 (3)). 
Board members are elected by a plurality and must be residents of the district to 
be eligible for office (Wis. Stat \S 120.06 (2) (a)). All candidate verification, 
ballot preparation, and election announcement is the responsibility of the school district 
clerk (Wis. Stat \S 120.06 (8)). Primary elections occur if there are more than 
twice as many candidates as there are members to be elected (Wis. Stat \S 120.06 (7) (b)). 
School boards may choose to apportion their seats in dramatically different ways 
ranging from a board of 3-9 members each representing the entire district, to a board 
of 3-11 members each representing either a specific region of the school district or 
the entire district. The only restriction on the way seats are allocated is that the 
plan is proposed with a petition by a threshold of voters and passed by the board 
at an annual meeting or through an election (Wis. Stat \S 120.02 (2)). 

School board election records came in many forms. The official and preferred 
records included the Statement of the Board of Canvass and the Certificate of the 
Board of Canvass. These two documents are legally mandated for each school board 
election and certify the winner for each school board seat, as well as the votes 
cast for each candidate. In most cases the records were provided electronically, 
though some were also received as hard copy in the mail. Full details on the data 
collection process can be found in Appendix \ref{app:data}. 
These records were then transcribed from the various records provided by school 
districts into spreadsheets that combined together form the key database for this 
analysis. 

Using the names, vote totals, and winners from each school board election allow 
for the construction of measures of the number of candidates in each election 
cycle, the number of contested seats, the level of voter participation, and other 
metrics of electoral activity at the school board level. Importantly, because the 
data was collected for several years in each district, time-variant trends can be 
evaluated and explored. 


\section{Studying Wisconsin School Board Elections}

In Wisconsin, school boards are the offical holder of all school district elections. 
This means that offical school board election records are maintained solely by 
school districts themselves and gathering school board election results in Wisconsin 
requires requesting records from individual school districts.\footnote{See Appendix 
\ref{app:data} and the Appendix \ref{app:log} for details on the request process.} 
An additional challenge is that though school boards are required by law to retain 
these records, the record keeping is often incomplete, unclear, or confusing (Wis. 
Stat \S 120.06 (8) (g)).\footnote{While a few enterprising county clerks have 
collected school board election results and made them available, these can be incomplete 
by only including the precincts that are within the county. They also are not official. 
\citep[personal communication with][]{clerk1}.}In order to conduct this study then, a records 
request was made to all 424 public school districts in the state of Wisconsin. 
This request was e-mailed to the school district administrator in each of Wisconsin's 
424 school districts in January of 2013. Three follow up waves were conducted throughout 
2013, and at the end of the collection period,\Sexpr{iNum(length(unique(dat$distid)))} 
districts responded with records. The median district provided 
\Sexpr{iNum(median(ddply(races, .(distid), summarize, out = length(unique(year)))[, 2]))} 
years of records. Overall, records were provided on \Sexpr{iNum(nrow(races))} school 
board races involving \Sexpr{iNum(nrow(cand))} candidates in the state. For each election 
the votes received by each candidate was recorded, as well as whether the candidate 
won, was an incumbent, was a repeat candidate in the school district, or was a 
minor candidate. For each race, whether the candidate was running for district 
wide or regional seat was also recorded. 

While each district was requested to provide the maximum amount of records legally 
required to be retained, ten years, many districts were unable to locate complete 
records going this far back. 

<<yeargraph, echo=FALSE, fig.cap="Number of Districts Providing Records by Year">>=
plotdf <- ddply(races, .(year), summarize, out = length(unique(distid)))

qplot(year, out, data = plotdf, geom = 'bar', stat = 'identity') + theme_dpi() + 
  geom_text(vjust = -.2, aes(label = out)) + 
  labs(x = "Election Year", y = "Number of Districts", 
       title = "District Providing Usable Records by Year")

@

The good news is that the most crucial period of the sample, from 2007 to 2012, is 
the period with the most complete set of records. 

<<racesgraph, echo=FALSE, fig.cap="Number of Races Provided by Districts. Red line indicates the mean.">>=
plotdf <- ddply(races, .(distid), summarize, years = length(unique(year)), 
                races = length(year))

qplot(races, data = plotdf) + theme_dpi() + 
  geom_vline(xintercept = mean(plotdf$races), color = I('red')) + 
  labs(x = "Number of School Board Races", y = "Count of Districts", 
       title = "Number of Race Records Provided by Each District")
@

The mean district provided records on \Sexpr{iNum(mean(plotdf$races))} school 
board races. However, it is important to consider 

\subsection{Contestation: Frequency and Context}

The biggest question in the school board literature seems to be -- are school 
board elections contested, and if so, when? While Chapter \ref{chap:candidacy} 
will explore when candidates emerge for school board elections, this section will 
first look at how often elections are contested, and how this varies compared to 
other elected bodies. 

First, let's consider the pool of school board races for which records were successfully 
obtained. Of the \Sexpr{iNum(nrow(races))}, \Sexpr{iNum(nrow(races[races$electiontype == 1,]))} 
were general elections. Another \Sexpr{iNum(nrow(races[races$electiontype == 2,]))} 
were primary elections, and the reamining \Sexpr{iNum(nrow(races[races$electiontype == 3, ]))} 
were special or recall elections. Of the general election races, 
\Sexpr{iNum(nrow(races[races$electiontype == 1 & races$nrealcand > 1,]))} feature 
two or more candidates who either were on the ballot or garnered more than 20 votes. 
However, it is important to note that in many school districts voters select more than 
one candidate for each seat and elect the top N vote recipients to the board. A 
better measure of contestation is to see how many races featured more candidates than 
winners - \Sexpr{iNum(nrow(races[races$electiontype == 1 & races$nrealcand > races$nwins,]))} 
races featured this, or \Sexpr{iNum(nrow(races[races$electiontype == 1 & races$nrealcand > races$nwins,])/ 
nrow(races[races$electiontype == 1,])*100)}\% of all races. 

\subsection{Margins and Voters}

The spring elections in Wisconsin are decidedly low turnout affairs. Since 2000 
Wisconsin has had between 4 and 4.35 million voting age population residents. However, 
in this time period the spring election has seen around 800,000 votes cast on 
average with a peak of 1.5 million.\footnote{Statistics from a Wisconsin Government Accountability 
Board report, available online: \url{http://gab.wi.gov/sites/default/files/page/non\_partisan\_turnout\_2000\_2013\_pdf\_15069.pdf}}
Turnout is typically around 18\% in such elections. Unsurprisingly then, school 
board elections are also low turnout affairs. By comparison, 
in the November partisn general election voter turnout is around 70\% in the last 
three presidential elections, and around 48\% in the last three gubernatorial 
elections.\footnote{Statistics from a Wisconsin Government Accountability 
Board report, available online: \url{http://gab.wi.gov/sites/default/files/page/partisan\_voter_turnout\_statistics\_1948\_2012\_pdf\_20396.pdf}}

Estimating school board election turnout is decidedly difficult because it requires 
both a reliable assessment of the votes cast in the election and a reliable 
estimate of the voting age population in the school district. Due to the fact that 
school districts have diverse organizational structure above, and no requirements 
on election reporting to a central authority, it is often difficult to ascertain 
the number of votes cast by voters within the school district. To determine the voting 
age population (VAP) of the school district in Wisconsin, I employ the finest resolution 
estimate of voting age population available -- VAP estimates by minor civil division (MCD) 
conducted by the Wisconsin Department of Administration.\footnote{Available online: \url{http://gab.wi.gov/elections-voting/results}. 
Statistics for Wisconsin Minor Civil Divisons are maintained by the Department of Administration 
Demographic Services Center: \url{http://www.doa.state.wi.us/section\_detail.asp?linkcatid=11\&linkid=64\&locid=9}}
However, MCDs are not perfectly contiguous with school districts -- school districts 
are contiguous only at the ward level where VAP estimates are not available. In 
order to estimate the proportion of the VAP that belongs to a given school district, 
I use property tax records provided by the Wisconsin Department of Revenue (DOR). 
These records annually report for each school district every MCD that is located entirely or partially 
within the boundaries of the school district, as well as the share of property wealth 
(as measured by equalized values, or EQV), for that MCD that the school district 
is authorized to levy tax for. For each year, the share of every MCD's EQV that 
was allocated to each school district was calculated. This share was used to 
pro-rate the population of each school district both for the purposes of 
calculating the voting age population, and for calculating votes cast for and 
against candidates in statewide elections.\footnote{A sensitivity check was done 
to determine if weighting by residential property values only changed the estimates, but 
it did not. For more details see Appendix \ref{app:data}}

We can measure how accurate this estimation procedure is by comparing the official number 
of votes cast and voter turnout statewide to the statewide estimates derived by 
rebuilding voter data at the district level. 


<<turnout, echo = FALSE,  results='asis'>>=
# qplot(races.tmp$turnout, races.tmp$topPresTurnoutPrior, geom = 'point') + 
#   ylim(c(0,1)) + xlim(c(0,1)) + geom_smooth()

years <- c(2002, 2004, 2006, 2008, 2010, 2012)
turnoutEst <- merge(VAP_dist, presTurn, by = c("distid", "year"), all.x=TRUE)
turnoutEst <- merge(turnoutEst, govTurn, by = c("distid", "year"), all.x=TRUE)

turnoutOf <- c(1785710, 3016288, 2166671, 2996869, 2171331, 3071434)
vapOf <- c(4060973, 4118621, 4260038, 4330695, 4372347, 4378741)
turnoutPerOf <- c(44, 72.9, 50.9, 69.2, 49.7, 70.1)

vapEst <- c(sum(turnoutEst$VAP[turnoutEst$year == 2002], na.rm =TRUE), 
            sum(turnoutEst$VAP[turnoutEst$year == 2004], na.rm =TRUE), 
            sum(turnoutEst$VAP[turnoutEst$year == 2006], na.rm =TRUE), 
            sum(turnoutEst$VAP[turnoutEst$year == 2008], na.rm =TRUE), 
            sum(turnoutEst$VAP[turnoutEst$year == 2010], na.rm =TRUE), 
            sum(turnoutEst$VAP[turnoutEst$year == 2012], na.rm =TRUE))


vapadjEst <- c(sum(turnoutEst$VAP_adj[turnoutEst$year == 2002], na.rm =TRUE), 
            sum(turnoutEst$VAP_adj[turnoutEst$year == 2004], na.rm =TRUE), 
            sum(turnoutEst$VAP_adj[turnoutEst$year == 2006], na.rm =TRUE), 
            sum(turnoutEst$VAP_adj[turnoutEst$year == 2008], na.rm =TRUE), 
            sum(turnoutEst$VAP_adj[turnoutEst$year == 2010], na.rm =TRUE), 
            sum(turnoutEst$VAP_adj[turnoutEst$year == 2012], na.rm =TRUE))


turnoutEst <- c(sum(turnoutEst$topGovVotesPrior[turnoutEst$year == 2002], na.rm =TRUE), 
            sum(turnoutEst$topPresVotesPrior[turnoutEst$year == 2004], na.rm =TRUE), 
            sum(turnoutEst$topGovVotesPrior[turnoutEst$year == 2006], na.rm =TRUE), 
            sum(turnoutEst$topPresVotesPrior[turnoutEst$year == 2008], na.rm =TRUE), 
            sum(turnoutEst$topGovVotesPrior[turnoutEst$year == 2010], na.rm =TRUE), 
            sum(turnoutEst$topPresVotesPrior[turnoutEst$year == 2012], na.rm =TRUE))

turnoutPerEst <- (turnoutEst / vapadjEst)*100

tab1names <- c("Year", "Official Total Votes", "Offical VAP", "Offical Turnout", 
               "Estimated Total Votes", "Estimated VAP", "Estimated Turnout")
table1 <- cbind(years, turnoutOf, vapOf, turnoutPerOf, turnoutEst, vapEst, 
                turnoutPerEst)
table1 <- as.data.frame(table1)
table1$years <- as.character(table1$years)
names(table1) <- tab1names
rm(years, turnoutOf, vapOf, turnoutPerOf, turnoutEst, vapEst, turnoutPerEst, 
   tab1names, vapadjEst)

print(xtable(table1, digits =0, label="tab:turnoutEst", 
             caption = "Comparing estimates of voter turnout derived from MCD estimates to official GAB turnout records." ), 
      include.rownames = FALSE, 
      format.args = list(big.mark = ",", decimal.mark = "."), 
      size = "footnotesize")

@

As shown in Table \ref{tab:turnoutEst}, the estimation procedure is very accurate. 
Using these estimates, we can be confident that the procedure used generates 
reasonable estimates of the VAP at the school district level. This takes care 
of the denominator of the turnout equation. TODO: Say something about vapadj

Collecting votes cast in school board elections presents a second set of challenges. 
I begin by collecting election returns from as many school districts as possible 
in Wisconsin.\footnote{For details on the collection procedure see Appendix \ref{app:data}} 
However, unlike a top ticket race such as a presidential or gubernatorial race, 
the election rules vary across school district jurisdictions. In some districts, 
voters may have multiple votes to cast in the election -- eliminating the ability 
to judge voter turnout based on the number of votes cast. In other districts, only 
a subsection of the electorate may be eligible to vote for a school district office 
due to apportionment in the district. 

<<turnoutgraph, echo=FALSE, fig.cap="Turnout for district wide school board races.">>=
races <- as.data.frame(races)
races.tmp <- merge(races, VAP_dist, by = c("distid", "year"))

presTurn$presTwoPartyVote <- presTurn$presDemVotes + presTurn$presRepVotes
presTurn$presTwoPartyShareDem <- presTurn$presDemVotes / presTurn$presTwoPartyVote

govTurn$govTwoPartyVote <- govTurn$govDemVotes + govTurn$govRepVotes
govTurn$govTwoPartyShareDem <- govTurn$govDemVotes / govTurn$govTwoPartyVote

# turnout over the prior presidential election
races.tmp <- merge(races.tmp, presTurn, by = c("distid", "year"), all.x=TRUE)
races.tmp <- merge(races.tmp, govTurn, by = c("distid", "year"), all.x=TRUE)

races.tmp <- subset(races.tmp, select = c("distid", "year", "raceid2", "ncand", 
                                          "nrealcand", "nwins", "ninc", "raceid",
                                          "nminor", "votes", "districtwide", 
                                          "electiontype", "VAP", "VAP_adj", 
                                          "topPresVotesPrior", "presTwoPartyShareDem", 
                                          "topGovVotesPrior", "govTwoPartyShareDem"))

races.tmp <- subset(races.tmp, raceid!=0)
# look at general
races.tmp <- subset(races.tmp, electiontype == 1)

# Look at districtwide only
races.tmp <- subset(races.tmp, districtwide == 1)
races.tmp <- subset(races.tmp, nrealcand > 0)

races.tmp <- races.tmp[!is.na(races.tmp$distid),]
races.tmp$voters <- races.tmp$votes / races.tmp$nwins
races.tmp$turnout <- races.tmp$voters/races.tmp$VAP_adj
qplot(year, turnout, data = races.tmp, geom = 'boxplot') + 
  scale_y_continuous(label = percent) + theme_dpi()
@

There is one set of cases for which estimating voter turnout is easy - the case 
where a school board seat is chosen district wide. Figure \ref{fig:turnoutgraph} 
shows that district wide school board races feature an average turnout below 25\%. 

<<comparison, results='asis', echo=FALSE>>=
out1 <- ddply(races.tmp, .(year), summarize, 
              nraces = length(distid), 
              ndists = length(unique(distid)))
names(out1) <- c("year", "nDistWideRaces", "nDistrictsDistWide")

out2 <- ddply(races, .(year), summarize, 
              nraces = length(distid), 
              ndists = length(unique(distid)))
names(out2) <- c("year", "nAllRaces", "nAllDistricts")

table2 <- merge(out1, out2)
rm(out1, out2)
table2$difference <- table2[, 5] - table2[, 3]
table2$difference2 <- table2[, 4] - table2[, 2]
names(table2) <- c("Year", "District Wide Races", "Districts with District Wide", 
                   "All SB Races", "All Districts with Records", 
                   "Districts without District Wide", "Non-district Wide Races")

print(xtable(table2, label="tab:yearsample", 
             caption = "Comparing sample size for district wide vs. apportioned school board races." ), 
      include.rownames = FALSE, 
      format.args = list(big.mark = ",", decimal.mark = "."), 
      size = "footnotesize")

@

Estimating turnout in the roughly 50 districts annually, as shown in Table \ref{tab:yearsample}, 
which do not have a district wide school board race is a different matter. 

<<nondistraces, fig.cap="Turnout for non-district wide school board races.">>=
races <- as.data.frame(races)
races.tmp <- merge(races, VAP_dist, by = c("distid", "year"))

presTurn$presTwoPartyVote <- presTurn$presDemVotes + presTurn$presRepVotes
presTurn$presTwoPartyShareDem <- presTurn$presDemVotes / presTurn$presTwoPartyVote

govTurn$govTwoPartyVote <- govTurn$govDemVotes + govTurn$govRepVotes
govTurn$govTwoPartyShareDem <- govTurn$govDemVotes / govTurn$govTwoPartyVote

races.tmp <- subset(races.tmp, select = c("distid", "year", "raceid2", "ncand", 
                                          "nrealcand", "nwins", "ninc", "raceid",
                                          "nminor", "votes", "districtwide", 
                                          "electiontype", "VAP_adj"))

races.tmp <- subset(races.tmp, raceid!=0)
# look at general
races.tmp <- subset(races.tmp, electiontype == 1)
# Look at non-districtwide only
races.tmp <- subset(races.tmp, districtwide == 0)
races.tmp <- subset(races.tmp, nrealcand > 0)
races.tmp <- races.tmp[!is.na(races.tmp$distid),]

# collapse to the district level

dist.tmp <- ddply(races.tmp, .(distid, year), summarize, 
              ncand = sum(ncand), nrealcand = sum(nrealcand), 
              nwins = sum(nwins), ninc = sum(ninc), 
              nminor = sum(nminor), votes = sum(votes), 
              VAP_adj = statamode(VAP_adj), 
              nraces = length(distid))

# turnout over the prior presidential election
dist.tmp <- merge(dist.tmp, presTurn, by = c("distid", "year"), all.x=TRUE)
dist.tmp <- merge(dist.tmp, govTurn, by = c("distid", "year"), all.x=TRUE)
dist.tmp$VAP_adj <- as.numeric(dist.tmp$VAP_adj)

dist.tmp$voters <- dist.tmp$votes / dist.tmp$nwins
dist.tmp$turnout <- dist.tmp$voters / dist.tmp$VAP_adj
qplot(year, turnout, data = dist.tmp, geom = 'boxplot') + 
  scale_y_continuous(label = percent) + theme_dpi()

@

Figure \ref{fig:nondistraces} shows the pattern for non-district wide races appears 
very similar under the estimation method of collapsing all races in a district 
into one race and dividing the votes counted by the number of winners. 

\section{Putting School Board Elections in Context}

The authority given to school districts in Wisconsin to determine their own electoral 
rules and structure make Wisconsin a useful case in exploring the variation in 
school board electoral participation across contexts. In addition to the contextual 
variation across school districts, Wisconsin school districts also vary widely in 
size, wealth, performance, and student and household demographics. 

There we go.