\chapter{Do Board Elections have Policy Consequences?}
\label{chap:policy}
\chapterstyle{deposit}

<<rsetup, results='hide', echo=FALSE, message=FALSE, warning=FALSE>>=
#setwd("../../../Data/Raw Files/Election Data")
#setwd("../Data/Raw Files/Election Data")
opts_chunk$set(fig.width=8, fig.height=6, message=FALSE, error=FALSE, 
               fig.path="../../phd_figs/chap6-",
               warning=FALSE, echo=FALSE, dev=c('pdf', 'png'))

setwd("../../")
library(eeptools)
source("R/thesis_functions.R")
source("data/cleanandprep_POLICY.R")
library(scales)
library(xtable)
options(xtable.include.rownames = FALSE, xtable.table.placement = "ht")
# library(devtools)
# install_github("jknowles/apsrtable", subdir = "pkg", ref = "dev")
library(apsrtable)
stars.note <- apsrtable:::stars.note
@

\section{Introduction}

Prior chapters have focused on the ability of community members to influence 
their school boards through elections. While the evidence on the responsiveness 
of school board elections to community influences was mixed, it remains to 
be seen if successfully defeating an incumbent matters. Why vote or 
run if meaningful changes in policy do not occur? Mobilizing to vote or run for 
school board can appear more expensive when compared to a small perceived 
benefit, thus shifting the democratic potential of school boards. Are voters and 
potential candidates correct if they assess school boards as unable to shift 
policy toward their preferences? Are school boards so constrained as actors that 
they are not able to effect meaningful policy change? In this chapter I explore 
this issue with two specific policy changes -- improvements in student outcomes and 
the change in district administrator. In other words, are these policies responsive 
to school board election results. 

There are many challenges in testing the responsiveness of school boards. First, 
in most 
cases school boards are non-partisan offices and many education issues do not fall 
along traditional ideological lines \citep[for counter example:][]{RefWorks:347}. 
This poses a measurement challenge for researchers seeking evidence of policy 
responsiveness. Additionally, the majority of school board election activity is 
low-impact and low-cost, eliminating traditional ways of measuring the information 
provided to voters about candidates and their policy preferences 
\citep{RefWorks:322,RefWorks:321}. Finally, the link between school board decisions 
and aggregate student outcomes in the community is weak in two distinct ways. First, 
the ability or desire of boards to make decisions that are counter to the preferences 
of the district administrator is questionable \citep{RefWorks:258}. Second, 
school board decisions, like other policy decisions, may take time to 
show results in district outcomes, particularly aggregate measures of student 
performance. 

Despite these measurement difficulties, there are strong reasons to believe that 
school boards do in fact matter. School boards have considerable power over 
local issues in their community. School boards in Wisconsin are responsible for 
setting property tax levies, managing labor relations with staff, and adopting 
and approve academic standards and curricula. They 
determine graduation requirements and discipline and attendance policies for 
their schools. The driving idea behind locally elected school boards 
was to ensure that the local community retained some control over the direction 
taken by their schools and that the school system was responsive to their 
preferences. Until now there have only been limited tests of school board 
responsiveness \citep{RefWorks:345}. 

In this chapter I explore the impact of board turnover on student outcomes both 
directly and indirectly in Wisconsin school districts. I focus on two measures 
of board turnover -- incumbent defeat and the dissatisfaction factor, or number 
of candidates per seat. 
Incumbent defeat is the clearest sign of dissatisfaction with current board policy 
and practice and serves as a cornerstone for dissatisfaction theory, the richest 
theory linking school board practice to educational outcomes \citep{RefWorks:297,RefWorks:245}. The dissatisfaction factor, though, can be considered a strong 
indication of community dissatisfaction with the school board as well, and has 
the added advantage of being more frequently occurring than the relatively rare 
defeat of incumbents. Dissatisfaction studies have used this indicator 
historically as well \citep{RefWorks:247,RefWorks:282,RefWorks:245}. 

<<incdefeat, results='hide'>>=
dist_turn$incDefeats <- NULL
incDefeat <- ddply(dat[dat$electiontype == 1,], 
                   .(distid, year), 
                   summarise, 
                   incsDefeated = sum(incumbent[winner == 0]), 
                   incsTotal = sum(incumbent), 
                   candTotal = length(candidateid[candidateid != 99]),
                   candReal = length(candidateid[candidateid != 99 & minor < 1]),
                   winnersTotal = sum(winner))
# incumbents defeated can exceed number of winners, especially when races 
# consolidate
fw  <- function(x) c(x[2:length(x)], NA)
dist_turn <- merge(dist_turn, incDefeat, by = c("distid", "year")) 
dist_turn$candReal <- ifelse(dist_turn$candReal == 0, dist_turn$candTotal, 
                             dist_turn$candReal)
dist_turn$boardTurnover <- dist_turn$incsDefeated / dist_turn$servingMembers
dist_turn$boardSeatsUp <- dist_turn$winnersTotal / dist_turn$servingMembers
dist_turn$challengRate <- 1 - (dist_turn$incsTotal / dist_turn$candTotal)
dist_turn$dissatFactor <- 1 - (dist_turn$winnersTotal / dist_turn$candTotal)
dist_turn$dissatFactor2 <- 1 - (dist_turn$winnersTotal / dist_turn$candReal)

library(data.table)
dist_turn <- dist_turn[order(dist_turn$distid, dist_turn$year),]
dist_turn <- as.data.table(dist_turn)[, NEW_SUP_FW:= fw(NEW_SUP), by = "distid"]
dist_turn <- as.data.table(dist_turn)[, 
                                      READ_PROFADV_PER_LAG:= lg(READ_PROFADV_PER),
                                      by = "distid"]
dist_turn <- as.data.table(dist_turn)[, 
                                      MATH_PROFADV_PER_LAG:= lg(MATH_PROFADV_PER),
                                      by = "distid"]
dist_turn <- as.data.table(dist_turn)[, 
                                      incsDefeatedLag:= lg(incsDefeated),
                                      by = "distid"]
dist_turn <- as.data.table(dist_turn)[, 
                                      incsTotalLag:= lg(incsTotal),
                                      by = "distid"]
dist_turn <- as.data.table(dist_turn)[, 
                                      winnersTotalLag:= lg(winnersTotal),
                                      by = "distid"]
dist_turn <- as.data.table(dist_turn)[, 
                                      nrealcandLag:= lg(nrealcand),
                                      by = "distid"]

dist_turn <- as.data.frame(dist_turn)

# head(dist_turn[, c("distid", "year", "NEW_SUP", 
#                  "NEW_SUP_FW", "READ_PROFADV_PER", "READ_PROFADV_PER_LAG")], 25)
@

\section{Literature Review and Theory}

While previous chapters examined the exercise of democratic control 
of school board elections -- under what conditions did voters and candidates 
participate, and was this participation sensitive to policy pressures -- this 
chapter seeks to understand the result of such participation. In order for 
democratic institutions to matter, the results of elections must also matter. 

I start with a simplified concept of voter dissatisfaction. Dissatisfaction in 
the community can be expressed on the ballot in two distinct ways: a) the presence 
of challengers to incumbents who see an opportunity to exploit voter dissatisfaction 
to defeat an incumbent, and b) the actual defeat of an incumbent. In the school 
board election literature these two approaches are known as the Lutz and the 
Iannaccone-Lutz models of dissatisfaction respectively 
\citep{RefWorks:337,RefWorks:297}. In the study of school boards, since 
\citet{RefWorks:297}, incumbent defeat has 
been seen as a strong sign that citizens are dissatisfied with the existing 
outputs of their school government and wish to see changes. Its roots can be 
traced back to fundamental ideas about the function elections play in allowing 
citizens to shape the policies of their government. Incumbent defeat has shown 
evidence of predicting policy change in school districts, but much of this evidence 
remains relatively weak \citep{RefWorks:312}. Additionally, as shown in 
Chapters \ref{chap:wisco} and \ref{chap:candidacy}, in Wisconsin school board 
incumbent defeat is relatively rare. 

\citet{RefWorks:337} defines the dissatisfaction 
factor, which is the number of challengers running for a school board seat. Partially 
in response to the twin measurement problems of the rarity of incumbent defeat 
and the confounding influence of politically motivated incumbent retirement, 
this measure has been used to predict both incumbent defeat and policy change 
\citep{RefWorks:337,RefWorks:247}. 
An increase in the number of challengers is expected to 
lead eventually to incumbent defeat as well as to encourage incumbents to retire 
rather than face reelection. It also sends a strong signal to board members not 
up for reelection that the community is not pleased with board decisions. This, 
then, will lead to policy change \citep{RefWorks:247}.\footnote{
Formally, the dissatisfaction factor is counted as the number of available seats 
divided by the number of challengers to that seat. The numerator includes all 
candidates for seats, though the original study does not indicate how to handle 
the case of challengers with very few votes or write-in candidates.}

Deciding which policy changes to focus on is the next challenge in this literature. 
School board policy is, by its very nature, highly localized. Finding policy 
outputs that are measurable and meaningful across school districts and across 
time on which to compare the impact of board turnover is difficult. Qualitative studies 
with interviews of key stakeholders and analyses of board and community preferences 
have found that dissatisfaction does matter and does drive change, but has done 
so with a level of depth unavailable for a wide scale study 
\citep{RefWorks:234,RefWorks:254,RefWorks:256,RefWorks:235}. Without such an 
in-depth study of the politics of each community, it is difficult to know 
what voters might wish to see change. Much of the work in this area reviewed in Chapter \ref{chap:intro} 
dealt focused on the impact of school board elections on superintendent
turnover \citep{RefWorks:297,RefWorks:271, RefWorks:351,
RefWorks:339,RefWorks:340,RefWorks:243}. The relatively recent emergence of 
public accountability for student performance in school districts has opened 
up another venue of potential investigation -- the importance of political 
turnover among school board members as a precursor to improved student 
performance \citep{RefWorks:311}. 

If voters are dissatisfied with their board and replace 
some board members with new challengers, it is likely that they demand higher student
performance, new district management, or both. While the linkage to superintendent 
turnover is straightforward, the influence of boards on student outcomes is less 
clear and merits further explanation. 

In many cases, boards are criticized as being highly constrained actors with 
little room to set policy after complying with state and federal mandates 
\citep{RefWorks:316}, although the extent of this is not clear \citep{RefWorks:223}.\footnote{Note that this argument can be reduced down ever further to the impact 
of district policies on schools or school policies on classroom \citep{RefWorks:255}}
Yet, evidence exists that boards can influence student outcomes through a range 
of decisions - some direct and some less direct.\citet{RefWorks:210} provides 
an example by examining the relationship between board decisions to consolidate 
school districts and the resulting changes in student achievement. More 
important still, boards allocate limited school resources such as quality staff, 
technology materials, and curricula materials, and evidence shows that such 
resources matter \citep{RefWorks:183}. On a more 
universal basis, \citet{RefWorks:214} explores if boards change policies in 
response to public accountability for student achievement, and find evidence in 
favor of resulting improvements in student achievement.\footnote{This argument 
assumes a certain level of effectiveness that is not captured by any measures in 
the current study and may not be evenly distributed across boards 
\citep{RefWorks:237,RefWorks:261}.}

\section{Data}

To study the impacts of incumbent defeat in Wisconsin school districts I employ 
a panel data set of school board election outcomes matched to school district 
administrative records. School board election results were obtained for a sample 
of Wisconsin school districts for the time period from 2002-2012 and coded to 
indicate winners, losers, incumbents, and repeat candidates. To code incumbent 
defeat, I matched a roster of known school board members in a given school year 
against the victors in the following school year to identify which candidates 
were incumbents. In addition to this, I code the dissatisfaction factor in two 
specific ways -- first as the number of elected seats over all candidates, and 
second as the number of elected seats over all candidates receiving greater than 
20 votes \citep{RefWorks:337}.\footnote{In the few cases in which a candidate 
with fewer than 20 votes was the winner, this latter measure is replaced by the 
former.} 

This method differs from the board and candidate self-reported measure of incumbent 
defeat that have been used previously in the literature \citep{RefWorks:345}. The 
longitudinal design is also more observations per district and includes a larger 
proportion of districts in the state than prior designs. In addition to this, 
a host of administrative data on school districts is also included, most critically 
measures of student outcomes and superintendent turnover. I discuss these below. 

\subsection{Independent Variables}

Timing is of critical importance in assessing the \emph{impact} of school board 
incumbent defeat. While school board members are elected in spring elections, 
their term begins the following fall. I use a lagged indicator of incumbent defeat 
to account for this by looking at the impact incumbent defeat has on student 
performance on the state exam and graduation rate two years after the election date. 
For an incumbent defeated in the spring election of 2004, the impact of this 
defeat is expected to come not during the 2005-06 school year, but instead the 
2006-07 year.\footnote{Future work may consider extending the lag even further 
because of the length of time it may take to see achievement results.}

<<incDefeatMeasure, fig.cap="Incumbent Defeat Year to Year in Wisconsin 2002-2012">>=
library(gridExtra)
plotdf <- ddply(dist_turn, .(year), summarise, 
                incsDefeated = sum(incsDefeated), 
                incsRunning = sum(incsTotal),
                challengers = sum(candTotal) - sum(incsTotal), 
                races = sum(winnersTotal))

p1 <- qplot(year, incsDefeated/incsRunning, data = plotdf, 
      geom = "bar", stat = "identity", fill = I("gray80"), color=I("black")) + 
  scale_x_continuous(breaks = c(2001:2012)) + theme_bw() + 
  scale_y_continuous(label = percent) + 
  labs(x = "Year", y = "% Defeated")

p2 <- qplot(year, incsDefeated, data = plotdf, 
      geom = "bar", stat = "identity",  fill = I("gray80"), color=I("black")) + 
  scale_x_continuous(breaks = c(2001:2012)) + theme_bw() + 
  scale_y_continuous() + 
  labs(x = "Year", y = "n Defeated")

grid.arrange(p1, p2, nrow = 2, main = "Incumbent Defeats in Data over Time")
@

Figure \ref{fig:incDefeatMeasure} shows the count and proportion of  
incumbent defeats in the Wisconsin data from 2002-2012. Typically 40-60 incumbents 
are defeated a year, representing approximately 10\% of all incumbents running 
each year. One shortcoming with using simple incumbent defeat as a measure is that 
Wisconsin school boards are majority rule decision making bodies meaning that if 
a single incumbent is defeated, it may be insufficient to result in substantive 
policy change depending on the policy positions of other members of the board. 
Figure \ref{fig:incTurnover} shows the number of seats on average up for election 
in districts in each year. The majority of districts elect one or two members 
and this represents a minority of the typically sized board of five to seven 
members. Unfortunately, there is not enough variation in the number of board seats 
elected and the number of incumbents defeated to use anything other than a binary 
measure of incumbent defeat. 


<<incTurnover, fig.cap="Number of Board Seats Elected Each Year">>=
# Number of winners
dist_turn$winnerFac <- ifelse(dist_turn$winnersTotal == 1, "1", 0)
dist_turn$winnerFac <- ifelse(dist_turn$winnersTotal == 2, "2", dist_turn$winnerFac)
dist_turn$winnerFac <- ifelse(dist_turn$winnersTotal > 2, "3+", dist_turn$winnerFac)

tmpdf <- as.data.frame(prop.table(table(dist_turn$winnerFac, dist_turn$year), margin = 2))
tmpdf$Var1 <- ordered(tmpdf$Var1, levels = c("1", "2", "3+"))

qplot(Var2, Freq, data = tmpdf, fill = Var1, geom='bar', stat='identity', 
      color = I("black")) + 
  scale_y_continuous(label = percent) + 
  guides(colour = FALSE, fill = guide_legend(override.aes = list(colour = NULL))) + 
  labs(fill = "Seats Elected", x= "Year", y = "Percent of Districts") + 
  scale_fill_brewer(type = "seq", palette = 8) + 
  theme_bw()

dist_turn$winnerFac <- NULL
# qplot(factor(year), boardSeatsUp, data = dist_turn, geom = 'boxplot')
# qplot(factor(year), challengRate, data = dist_turn, geom = 'boxplot')
# qplot(factor(year), boardTurnover, data = dist_turn, geom = 'boxplot')
@


For a more continuous measure, I employ the dissatisfaction factor of 
\citet{RefWorks:337} as well as a modified version which is the ratio of non-incumbents 
to incumbents. Figure \ref{fig:dfactor} shows the average dissatisfaction factor 
and average incumbent challenger rate in each year in the data. For both figures, 
a higher number indicates more dissatisfaction either due to more candidates 
overall participating or more non-incumbents. In general, competition seems to 
have dropped off in both measures since 2002.\footnote{Though years prior to 2007 
will be excluded from most further analyses due to concerns about reporting bias 
with the reduced sample and lack of student performance measures.}

<<dfactor, fig.cap="Average Candidate Challenge in Wisconsin 2002-2012">>=
plotdf <- ddply(dist_turn, .(year), summarise, 
                dfactor1 = mean(dissatFactor), 
                dfactor2 = mean(dissatFactor2),
                crate = mean(challengRate), 
                winnerAvg = mean(winnersTotal), 
                candAvg = mean(candTotal))

p1 <- qplot(year, dfactor1, data = plotdf, 
      geom = "bar", stat='identity', color = I("black"), fill = "gray80") + 
  scale_x_continuous(breaks = c(2001:2012)) + theme_bw() + 
  scale_y_continuous(label = percent) + 
  labs(x = "Year", y = "DFACTOR")

p2 <-  qplot(year, crate, data = plotdf, 
      geom = "bar", stat='identity', color = I("black"), fill = "gray80") + 
  scale_x_continuous(breaks = c(2001:2012)) + theme_bw() + 
  scale_y_continuous(label = percent) + 
  labs(x = "Year", y = "CRATE")

grid.arrange(p1, p2, nrow = 2, main = "Candidate Challenge Data over Time")
@


\subsection{Control Variables}

Following the work of \citet{RefWorks:345}, I include relatively few control 
variables. Including too many control variables results in overly restricting the 
variance available to be explained by incumbent defeat and possibly collinear. 
However I do include measures of whether the district is rural, urban, or exurban, 
and a control for the size of the voting age population. I also include measures 
of the level of education of the adult population and the percentage of adults in 
the community who are over the age of 65. I also include a measure of economic 
disadvantage for students in the school district -- a key predictor of student 
outcomes. 

\subsection{Outcomes}

First, and most directly, boards are charged with hiring and monitoring 
the performance of a district administrator who manages the academic and 
financial affairs of the district. The choice of superintendent is critical to 
the board as the superintendent is the board's primary conduit of information 
about the health of the district and the educational strategies in place for 
students \citep{RefWorks:271}. Superintendent turnover is a primary prediction 
of dissatisfaction theory, and rightfully so. If voters are unhappy with the 
state of affairs in their school district, in all likelihood they are unhappy 
with the performance of their district administrator \citep{RefWorks:246,RefWorks:245,
RefWorks:273}. 

Superintendent change is coded using the Wisconsin Department of Public Instruction 
database on school staffing - the PI-1202 report. This report includes annual 
information on the job position, license status, full-time equivalency or full-time 
part-time nature of the job, and salary. This information is collected each fall. 
A superintendent change was coded if a new superintendent was listed that differed 
from the prior year.\footnote{One limitation in the current study is the inability 
to distinguish between voluntary and involuntary superintendent turnover. Within 
year turnover is also not included, but is rare.} Figure 
\ref{fig:supChange} shows the percentage of school districts in the sample 
each year that experienced a superintendent turnover. Annually around 15\% of 
districts in the sample had a change in superintendent. 

<<supChange, fig.cap="Superintendent turnover by year in sample.",fig.height=3.75>>=
tmpdf <- as.data.frame(prop.table(table(dist_turn$NEW_SUP, dist_turn$year),
                                  margin=2))
tmpdf$Var1 <- ifelse(tmpdf$Var1 == 1, "Yes", "No")
tmpdf$Var1 <- ordered(tmpdf$Var1, levels = c("Yes", "No"))

qplot(Var2, Freq, data = tmpdf, fill = Var1, geom='bar', stat='identity') + 
  scale_y_continuous(label = percent) + 
  labs(fill = "Sup. Turnover?", x= "Year", y = "Percent of Districts") + 
  scale_fill_brewer(type = "qual", palette = 6) + 
  theme_bw()

@


More indirectly, school boards are responsible for setting policy and directing 
the superintendent to provide quality education. Thus, incumbent defeat may 
serve as a method by which the community can express its demand for higher 
quality education as measured by accountability measures such as student 
test scores and graduation rates. While prior research has found evidence of 
an effect of school board turnover and elections on student performance on 
standardized tests, this outcome seems the furthest from the control of school 
board members. 

For student test scores I use the district-wide proficiency rate on the state 
standardized reading and math examinations known as the Wisconsin Knowledge 
and Concepts Examination (WKCE). Proficiency rates are calculated by identifying 
which range of scale scores student scores lie within. Four proficiency categories 
exist -- minimal, basic, proficient, and advanced. I use the percentage of students 
in the district scoring at the level of proficient or advanced across all grades. 
During the period of study Wisconsin increased the score required to reach 
proficiency to reflect increased performance expectations on schools and districts. 
I use these adjusted proficiency rates retroactively applied throughout the time 
period.\footnote{State standardized assessment results are only available from 2005-2006 
to present, truncating the sample for this analysis.}

<<testscorePlot, eval=FALSE>>=
qplot(year, MATH_PROFADV_PER, data = dist_turn, group = distid, geom='line', 
      alpha = I(0.2)) + geom_smooth(aes(group = 1), method ='lm')

qplot(year, READ_PROFADV_PER, data = dist_turn, group = distid, geom='line', 
      alpha = I(0.2)) + geom_smooth(aes(group = 1), method ='lm')

qplot(factor(year), READ_PROFADV_PER, 
      data = dist_turn[dist_turn$READ_PROFADV_PER > 0 &                                                !is.na(dist_turn$READ_PROFADV_PER),], 
      geom='boxplot') + theme_bw() + 
  scale_y_continuous(label = percent) + 
  labs(x= "Year", y = "Public Graduation Rate")

@

School boards appear to have more ability to influence graduation rates. First, 
school boards in Wisconsin have wide leverage in setting the academic standards 
for graduation and there is large variability in the credit requirements to graduate 
in high schools across the state. Second, graduation rates are highly visible 
accountability measures throughout this period of observation, and districts may 
have been able to attempt a wide variety of policy changes to improve graduation 
outcomes relatively quickly. The graduation rate measure I use is the only measure consistently calculated 
throughout the time period and the one used for accountability purposes for 
most of the period from 2002-2012 -- the legacy graduation rate. This rate differs 
from more recent graduation rates reported by schools, districts, and states -- 
it is not a four-year graduation rate. One challenge with this measure is that 
overall Wisconsin has a high graduation rate, and many school districts in 
Wisconsin has particularly high graduation rates. Figure \ref{fig:gradRateplot} 
shows the graduation rates of school districts throughout the period of study.
\footnote{Not every school district with a school board graduates students, so 
this sample is only for school districts with a high school.}

<<gradRateplot, fig.scap="Public High School Graduation Rates", fig.cap="Public high school graduation rates in Wisconsin. In general, Wisconsin school districts have very high graduation rates with litle variance between districts.", fig.height=3.75>>=
qplot(factor(year), gradRate/100, data = dist_turn[dist_turn$gradRate > 0 & 
                                                   !is.na(dist_turn$gradRate),], 
      geom='boxplot') + theme_bw() + 
  scale_y_continuous(label = percent) + 
  labs(x= "Year", y = "Public Graduation Rate")

@

The final set of outcomes are fiscal outcomes. One of the few factors related 
to the emergence of contested elections from Chapter \ref{chap:candidacy} was 
fiscal performance. For this chapter, I focus on two salient factors in the 
community, the change in the millrate on property taxes and the median teacher 
salary. 

In Wisconsin the school funding formula puts restrictions on school millrates with 
overall revenue limits. Additionally, the amount of state funding school districts 
receive is highly variable with a few districts receiving only a nominal amount 
of money from the state -- and thus deriving almost all school funding from 
local property taxes. So, while a change in a millrate does not represent a change 
in a school district's fiscal fortunes on its own, it does represent a highly 
salient impact of the school district on residents of the district through a 
higher property tax bill. Figure \ref{fig:millratePlot} shows the general trend 
of increasing and then receding school district millrates across the study period. 
But, substantial variation between districts exists. 

<<millratePlot, fig.scap="Annual Change in District Millrate", fig.cap="Smoothed lines for annual change in the millrate for each district in the sample, measured in mills.", fig.height=3.75>>=
ggplot(dist_turn, aes(x = year, y = millrate_delta, group = distid)) + 
  geom_line(stat="smooth", se = FALSE, color = I("black"), alpha = I(0.45)) + 
  scale_x_continuous(breaks = c(2002:2013), "Year") + 
  geom_hline(yintercept = 0, size= I(1.1), color = I("red")) +
  labs(y = "Annual Change in Millrate") +
  theme_bw()
@

Figure \ref{fig:teachSalPlot} shows the trajectory of the median teacher salary 
for the school districts in the sample. In general, during this period all teacher 
salaries followed the same trajectory, but the variation between districts in 
median salary is quite large -- nearly \$8,000 between the first and third 
quartiles. This figure is important because this accounts for the majority of 
district expenses. 

<<teachSalPlot, fig.scap="Annual Change in Median Teacher Salary", fig.cap="Smoothed lines for annual change in the median teacher salary for each district in the sample.", fig.height=3.75>>=
ggplot(dist_turn, aes(x = year, y = ADJ_MEDIAN_SALARY_TEACH, group = distid)) + 
  geom_line(stat="smooth", se = FALSE, color = I("black"), alpha = I(0.45)) + 
  scale_x_continuous(breaks = c(2002:2013), "Year") + 
  scale_y_continuous(label = dollar, "Median Teacher Salary") + 
  theme_bw()
@


\clearpage

\section{Methods}

To explore the impact that school board member electoral defeat has on school 
outcomes I employ a regression strategy that leverages the panel nature of my 
data and repeated measures of school districts over time. As in previous 
chapters, I employ the bounding strategy from Chapter \ref{chap:walker} and 
suggested by \citet{mhecon}, using a 
lagged dependent variable and a fixed effect model to compare for time variant 
and time invariant unobservable factors respectively. This model provides better 
confidence that the effect estimated, in this case the effect of incumbent defeat, 
is independent of unobserved factors. I refer to the 
different measures of board dissatisfaction or incumbent defeat collectively as 
the dissatisfaction factor, or \texttt{DFACTOR}. 

The equation below represents the fixed effects approach with the
$\gamma_{j}$ 's representing the individual district intercepts in the sample. 
$\lambda$ represents the conditional estimate of the \texttt{DFACTOR}, taking into 
account the within district variation and conditional on lagged measures of the 
control variables in $X_{it-2}$. 

\begin{align*} 
y_{it} &= \alpha + \gamma_{j} + \beta X_{it-2} + \lambda T_{it-2} + \epsilon_{it} \\ \end{align*}

Alternatively, the next equation replaces the $\gamma_{j}$'s with a lagged 
dependent variable to control for time-variant unobservable characteristics. 

\begin{align*} 
y_{it} &= \alpha + \gamma Y_{it-2} + \beta X_{it-2} + \lambda T_{it-2} + \epsilon_{it} \\ \end{align*}

The disadvantage of this 
strategy is that for the outcomes in question, relatively little variance 
remains to be explained after accounting for all between school district effects, 
because the within school district variation is so small. Thus, even with a large
sample size and several observations per district, the study may be underpowered 
to detect any residual impact of school board incumbent defeat. As an alternative 
to the two model strategy above, I also include a reduced model 
which includes no district fixed effects and no lagged outcome measure, but instead 
includes just a few indicators of district demographics so that the effect of 
board member turnover is estimated between districts that are similar on exogenous 
demographic factors.\footnote{Before fitting the models I log the variables 
expressed as percentages to make their distribution more normal. For all three 
types of models I report robust district clustered standard errors.}

\begin{align*} 
y_{it} &= \alpha +  \beta X_{it-2} + \lambda T_{it-2} + \epsilon_{it}  \\ 
\end{align*}


\section{Results}

In all of the models I expect to find a positive relationship between incumbent 
defeat and the outcome. If voters are defeating incumbents as a way of seeking 
improvement in their schools, then incumbent defeat should lead to increased 
accountability pressure and improved student outcomes. 

\subsection{Student Outcomes}


<<testScoresR, results='asis'>>=
modeldata <- dist_turn[, c("distid", "year", "incsDefeated", "servingMembers",
                           "READ_PROFADV_PER", "NEW_SUP", "SUP_EXPERIENCE", 
                           "dissatFactor", 
                           "econ_disadv_per", "VAP_adj", "per65o", "challengRate",
                           "PerBachelorOrAbove", "locale2", "incsTotal")]
modeldata$READ_PROFADV_PER <- log(modeldata$READ_PROFADV_PER*100)
modeldata$incsDefeatedFac <- ifelse(modeldata$incsDefeated > 0, 1, 0)
modeldata$incsDefeatedFac <- factor(modeldata$incsDefeatedFac)
preTreat <- modeldata[modeldata$year <= 2010,]
preTreat$year <- preTreat$year + 2
names(preTreat) <- paste(names(preTreat), "lag", sep = "_")
modeldata <- modeldata[, c("READ_PROFADV_PER", "distid", "year")]
modeldata <- merge(modeldata, preTreat, by.y = c("distid_lag", "year_lag"), 
                 by.x = c("distid", "year"))
modeldata <- modeldata[modeldata$year > 2005, ]
modeldata$SUP_EXPERIENCE_lag <- ifelse(is.na(modeldata$SUP_EXPERIENCE_lag), 0, 
                                       modeldata$SUP_EXPERIENCE_lag)

simpModRead <- lm(READ_PROFADV_PER ~ incsDefeatedFac_lag + locale2_lag  +
                    servingMembers_lag + log(VAP_adj_lag), 
                  data = modeldata)
simpModRead$se <- sqrt(diag(get_CL_vcov(simpModRead, modeldata$distid)))
lagModRead <- lm(READ_PROFADV_PER ~ incsDefeatedFac_lag + econ_disadv_per_lag + 
                   READ_PROFADV_PER_lag + servingMembers_lag + 
                   log(VAP_adj_lag) + locale2_lag + PerBachelorOrAbove_lag + 
                   per65o_lag, data = modeldata)
lagModRead$se <- sqrt(diag(get_CL_vcov(lagModRead, 
                   modeldata$distid[!is.na(modeldata$READ_PROFADV_PER_lag)])))
lagModReadFE <- lm(READ_PROFADV_PER ~ incsDefeatedFac_lag + econ_disadv_per_lag + 
                   log(VAP_adj_lag) + locale2_lag + PerBachelorOrAbove_lag + 
                      servingMembers_lag + per65o_lag + distid, 
                   data = modeldata)
lagModReadFE$se <- sqrt(diag(get_CL_vcov(lagModReadFE, modeldata$distid)))

prettyNames <- c("Intercept", "Inc. Def. Lag", "Exurb", "Rural", "Board Size",
                  "Electorate Size", "Econ. Disadv. \\%", "Prof Rate Lag", "\\% Bach. +", 
                 "\\% Over 65")

fe.note <- "District fixed effects not displayed."

apsrtable(simpModRead, lagModRead, lagModReadFE, se = "robust", 
          stars = "default", digits = 3, model.names = c("Simple", "Lag", "FE"), 
          caption = "Incumbent Defeat and Reading Proficiency Rates", 
          label = "tab:readMod", notes = list(stars.note, fe.note), 
          Sweave = FALSE, 
           omitcoef=list("distid", 
                         expression(grep("distid", coefnames, value=TRUE))), 
          coef.names = prettyNames, size = "small")
@

<<testScoresRchall, results='hide'>>=
simpModReadC <- update(simpModRead, . ~ challengRate_lag + . - 
                         incsDefeatedFac_lag)
simpModReadC$se <- sqrt(diag(get_CL_vcov(simpModReadC, modeldata$distid)))
lagModReadC <- update(lagModRead, . ~ challengRate_lag + . - 
                         incsDefeatedFac_lag)
lagModReadC$se <- sqrt(diag(get_CL_vcov(lagModReadC, 
                   modeldata$distid[!is.na(modeldata$READ_PROFADV_PER_lag)])))
lagModReadFEc <- update(lagModReadFE, . ~ challengRate_lag + . - 
                         incsDefeatedFac_lag)
lagModReadFEc$se <- sqrt(diag(get_CL_vcov(lagModReadFEc, modeldata$distid)))

simpModReadD <- update(simpModReadC, . ~ dissatFactor_lag + . - 
                         challengRate_lag)
simpModReadD$se <- sqrt(diag(get_CL_vcov(simpModReadD, modeldata$distid)))

lagModReadD <- update(lagModReadC, . ~ dissatFactor_lag + . - 
                         challengRate_lag)
lagModReadD$se <- sqrt(diag(get_CL_vcov(lagModReadD, 
                   modeldata$distid[!is.na(modeldata$READ_PROFADV_PER_lag)])))
lagModReadFEd <- update(lagModReadFEc, . ~ dissatFactor_lag + . - 
                         challengRate_lag)
lagModReadFEd$se <- sqrt(diag(get_CL_vcov(lagModReadFEd, modeldata$distid)))

prettyNames <- c("Intercept", "Challenge Rate", "Exurb", "Rural", "Board Size",
                  "Electorate Size", "Econ. Disadv. \\%", "Prof Rate Lag", "\\% Bach. +", 
                 "\\% Over 65")

readChalRateTab <- apsrtable(simpModReadC, lagModReadC, lagModReadFEc, se = "robust", 
          stars = "default", digits = 3, model.names = c("Simple", "Lag", "FE"), 
          caption = "Challenger Rate and Reading Proficiency Rates", 
          label = "tab:readMod2", notes = list(stars.note, fe.note), 
          Sweave = FALSE, 
           omitcoef=list("distid", 
                         expression(grep("distid", coefnames, value=TRUE))), 
          coef.names = prettyNames, size = "small")

prettyNames <- c("Intercept", "Dissat. Factor", "Exurb", "Rural", "Board Size",
                  "ln(VAP)", "FRL \\%", "Prof Rate Lag", "\\% Bach. +", 
                 "\\% Over 65")
readDRateTab <- apsrtable(simpModReadD, lagModReadD, lagModReadFEd, se = "robust", 
          stars = "default", digits = 3, model.names = c("Simple", "Lag", "FE"), 
          caption = "Dissatisfaction Factor and Reading Proficiency Rates", 
          label = "tab:readMod3", notes = list(stars.note, fe.note), 
          Sweave = FALSE, 
           omitcoef=list("distid", 
                         expression(grep("distid", coefnames, value=TRUE))), 
          coef.names = prettyNames, size = "small")

@


Table \ref{tab:readMod} shows relatively little effect of school board incumbent 
defeat on student proficiency rates. In the simple model, there appears to be a 
slight negative effect on student scores after an incumbent is defeated. However, 
this effect disappears when including a lagged dependent variable or district 
fixed effect, and the sign switches. The model also has a very small $R^{2}$ and 
the inclusion of indicators of district economic disadvantage and fixed effects 
or the lagged dependent variable pushes the $R^{2}$ to 0.85 to 0.9. 

The substantive impact of the most generous estimate in the first model in Table 
\ref{tab:readMod} is equivalent to a reduction in 0.3\% in the percentage of 
students in a school district that are proficient or advanced. This is approximately 
0.036 of a standard deviation. 

Table \ref{tab:mathMod} shows the results for math proficiency rates. Again, 
the effect of incumbent defeat is significant and negative in the first model, 
but that effect is erased in the lagged and fixed effect models. The first model 
has a very small $R^{2}$, but the lagged and FE models have a much higher $R^{2}$ 
with economic and unobservable characteristics explaining most of the variance 
in student performance. 

The substantive impact here is again small, but larger than that found on the reading 
models in Table \ref{tab:readMod}. Here the reduction due to school 
board incumbent defeat is equivalent to a reduction of the percentage proficient 
or advanced at math in the district of 1.4\%. This is a much larger effect than 
that measured in the reading models, about 0.13 of a standard deviation. 

For both reading and math, the results for incumbent defeat are broadly similar 
for the dissatisfaction factor, which is negatively related to future test 
score performance. These results can be found in Tables \ref{tab:readMod3} and 
\ref{tab:mathMod3} and again the reduced model is statistically significant, 
but the lagged and fixed effect models have greatly reduced coefficients and 
no statistical significance.\footnote{The challenge rate is similar, but not 
statistically significant.}

<<testScoresM, results='asis'>>=
modeldata <- dist_turn[, c("distid", "year", "incsDefeated", "servingMembers",
                           "MATH_PROFADV_PER", "NEW_SUP", "SUP_EXPERIENCE",
                           "econ_disadv_per", "VAP_adj", "per65o", "challengRate",
                           "PerBachelorOrAbove", "locale2", "dissatFactor")]
modeldata$MATH_PROFADV_PER <- log(modeldata$MATH_PROFADV_PER*100)
modeldata$incsDefeatedFac <- ifelse(modeldata$incsDefeated > 0, 1, 0)
modeldata$incsDefeatedFac <- factor(modeldata$incsDefeatedFac)
preTreat <- modeldata[modeldata$year <= 2010,]
preTreat$year <- preTreat$year + 2
names(preTreat) <- paste(names(preTreat), "lag", sep = "_")
modeldata <- modeldata[, c("MATH_PROFADV_PER", "distid", "year")]
modeldata <- merge(modeldata, preTreat, by.y = c("distid_lag", "year_lag"), 
                 by.x = c("distid", "year"))
modeldata <- modeldata[modeldata$year > 2005, ]
modeldata$SUP_EXPERIENCE_lag <- ifelse(is.na(modeldata$SUP_EXPERIENCE_lag), 0, 
                                       modeldata$SUP_EXPERIENCE_lag)

simpModMath <- lm(MATH_PROFADV_PER ~ incsDefeatedFac_lag + locale2_lag + 
                    servingMembers_lag + log(VAP_adj_lag), 
                  data = modeldata)
simpModMath$se <- sqrt(diag(get_CL_vcov(simpModMath, modeldata$distid)))
lagModMath <- lm(MATH_PROFADV_PER ~ incsDefeatedFac_lag + econ_disadv_per_lag + 
                   MATH_PROFADV_PER_lag +servingMembers_lag+
                   log(VAP_adj_lag) + locale2_lag + PerBachelorOrAbove_lag + 
                   per65o_lag, data = modeldata)
lagModMath$se <- sqrt(diag(get_CL_vcov(lagModMath, 
                   modeldata$distid[!is.na(modeldata$MATH_PROFADV_PER_lag)])))
lagModMathFE <- lm(MATH_PROFADV_PER ~ incsDefeatedFac_lag + econ_disadv_per_lag + 
                   log(VAP_adj_lag) + locale2_lag + PerBachelorOrAbove_lag + 
                  servingMembers_lag+  per65o_lag + distid, data = modeldata)
lagModMathFE$se <- sqrt(diag(get_CL_vcov(lagModMathFE, modeldata$distid)))

prettyNames <- c("Intercept", "Inc. Def. Lag", "Exurb", "Rural", "Board Size",
                 "Electorate Size",
                 "Econ. Disadv. \\%", "Prof Rate Lag", "\\% Bach. +", 
                 "\\% Over 65")

fe.note <- "District fixed effects not displayed."

apsrtable(simpModMath, lagModMath, lagModMathFE, se = "robust", 
          stars = "default", digits = 3, model.names = c("Simple", "Lag", "FE"), 
          caption = "Incumbent Defeat and Math Proficiency Rates", 
          label = "tab:mathMod", notes = list(stars.note, fe.note), 
          Sweave = FALSE, 
           omitcoef=list("distid", 
                         expression(grep("distid", coefnames, value=TRUE))), 
          coef.names = prettyNames, size = "small")
@


<<testScoreschallM, results='hide'>>=
simpModMathc <- update(simpModMath, . ~ challengRate_lag + . - 
                         incsDefeatedFac_lag)
simpModMathc$se <- sqrt(diag(get_CL_vcov(simpModReadC, modeldata$distid)))
lagModMathC <- update(lagModMath, . ~ challengRate_lag + . - 
                         incsDefeatedFac_lag)
lagModMathC$se <- sqrt(diag(get_CL_vcov(lagModMathC, 
                   modeldata$distid[!is.na(modeldata$MATH_PROFADV_PER_lag)])))
lagModMathFEc <- update(lagModMathFE, . ~ challengRate_lag + . - 
                         incsDefeatedFac_lag)
lagModMathFEc$se <- sqrt(diag(get_CL_vcov(lagModMathFEc, modeldata$distid)))

simpModMathD <- update(simpModMathc, . ~ dissatFactor_lag + . - 
                         challengRate_lag)
simpModMathD$se <- sqrt(diag(get_CL_vcov(simpModMathD, modeldata$distid)))

lagModMathD <- update(lagModMathC, . ~ dissatFactor_lag + . - 
                         challengRate_lag)
lagModMathD$se <- sqrt(diag(get_CL_vcov(lagModMathD, 
                   modeldata$distid[!is.na(modeldata$MATH_PROFADV_PER_lag)])))
lagModMathFEd <- update(lagModMathFEc, . ~ dissatFactor_lag + . - 
                         challengRate_lag)
lagModMathFEd$se <- sqrt(diag(get_CL_vcov(lagModMathFEd, modeldata$distid)))

prettyNames <- c("Intercept", "Challenge Rate", "Exurb", "Rural", "Board Size",
                  "Electorate Size", "Econ. Disadv. \\%", "Prof Rate Lag", "\\% Bach. +", 
                 "\\% Over 65")

mathChalRateTab <- apsrtable(simpModMathc, lagModMathC, lagModMathFEc, se = "robust", 
          stars = "default", digits = 3, model.names = c("Simple", "Lag", "FE"), 
          caption = "Challenger Rate and Math Proficiency Rates", 
          label = "tab:mathMod2", notes = list(stars.note, fe.note), 
          Sweave = FALSE, 
           omitcoef=list("distid", 
                         expression(grep("distid", coefnames, value=TRUE))), 
          coef.names = prettyNames, size = "small")

prettyNames <- c("Intercept", "Dissat. Factor", "Exurb", "Rural", "Board Size",
                  "Electorate Size", "Econ. Disadv. \\%", "Prof Rate Lag", "\\% Bach. +", 
                 "\\% Over 65")
mathDRateTab <- apsrtable(simpModMathD, lagModMathD, lagModMathFEd, se = "robust", 
          stars = "default", digits = 3, model.names = c("Simple", "Lag", "FE"), 
          caption = "Dissatisfaction Factor and Math Proficiency Rates", 
          label = "tab:mathMod3", notes = list(stars.note, fe.note), 
          Sweave = FALSE, 
           omitcoef=list("distid", 
                         expression(grep("distid", coefnames, value=TRUE))), 
          coef.names = prettyNames, size = "small")

@

Table \ref{tab:gradMod} shows the results for graduation rates. Although I expected 
to find a stronger effect of school boards on graduation rates, there is weaker 
evidence here. The estimated effect is consistently negative -- counter to 
expectations -- but is not statistically significant. The effect is substantively 
equivalent to a decrease of 0.18\% in the graduation rate, an effect of 
0.03 standard deviations. The effects for the challenge rate and the dissatisfaction 
factor are largely the same, but only the dissatisfaction factor has a negative 
statistically significant relationship in the simple model. These results are in 
Table \ref{tab:gradMod2} and \ref{tab:gradMod3}. 

% HSC 
<<hscModel, results='asis'>>=
modeldata <- dist_turn[, c("distid", "year", "incsDefeated", "servingMembers",
                           "gradRate", "NEW_SUP", "SUP_EXPERIENCE", "challengRate",
                           "econ_disadv_per", "VAP_adj", "per65o", "dissatFactor",
                           "PerBachelorOrAbove", "locale2")]
modeldata <- modeldata[modeldata$gradRate > 0, ]
modeldata$gradRate <- log(modeldata$gradRate)
modeldata$incsDefeatedFac <- ifelse(modeldata$incsDefeated > 0, 1, 0)
modeldata$incsDefeatedFac <- factor(modeldata$incsDefeatedFac)
preTreat <- modeldata[modeldata$year <= 2010,]
preTreat$year <- preTreat$year + 2
names(preTreat) <- paste(names(preTreat), "lag", sep = "_")
modeldata <- modeldata[, c("gradRate", "distid", "year")]
modeldata <- merge(modeldata, preTreat, by.y = c("distid_lag", "year_lag"), 
                 by.x = c("distid", "year"))
modeldata <- modeldata[modeldata$year > 2005, ]
modeldata$SUP_EXPERIENCE_lag <- ifelse(is.na(modeldata$SUP_EXPERIENCE_lag), 0, 
                                       modeldata$SUP_EXPERIENCE_lag)

simpModGrad <- lm(gradRate ~ incsDefeatedFac_lag + locale2_lag + 
                    servingMembers_lag + log(VAP_adj_lag), 
                  data = modeldata)
simpModGrad$se <- sqrt(diag(get_CL_vcov(simpModGrad, 
                                        modeldata$distid[!is.na(modeldata$gradRate)])))

lagModGrad <- lm(gradRate ~ gradRate_lag + incsDefeatedFac_lag + servingMembers_lag+
                   log(VAP_adj_lag) + locale2_lag + PerBachelorOrAbove_lag + 
                   per65o_lag, data = modeldata)
lagModGrad$se <- sqrt(diag(get_CL_vcov(lagModGrad, 
                   modeldata$distid[!is.na(modeldata$gradRate_lag) & 
                                      !is.na(modeldata$gradRate)])))

lagModGradFE <- lm(gradRate ~ incsDefeatedFac_lag + econ_disadv_per_lag + 
                   log(VAP_adj_lag) + locale2_lag + PerBachelorOrAbove_lag + 
                   servingMembers_lag + per65o_lag + distid, data = modeldata)

lagModGradFE$se <- sqrt(diag(get_CL_vcov(lagModGradFE, 
                                         modeldata$distid[!is.na(modeldata$gradRate)])))

prettyNames <- c("Intercept", "Inc. Def. Lag", "Exurb", "Rural", "Board Size",
                  "Electorate Size", "Econ. Disadv. \\%", "Grad Rate Lag", "\\% Bach. +", 
                 "\\% Over 65")

fe.note <- "District fixed effects not displayed."

apsrtable(simpModGrad, lagModGrad, lagModGradFE, se = "robust", 
          stars = "default", digits = 3, model.names = c("Simple", "Lag", "FE"), 
          caption = "Incumbent Defeat and High School Graduation", 
          label = "tab:gradMod", notes = list(stars.note, fe.note), 
          Sweave = FALSE, 
           omitcoef=list("distid", 
                         expression(grep("distid", coefnames, value=TRUE))), 
          coef.names = prettyNames, size="small")
@


<<hscChalRate, results='hide'>>=

simpModGradc <- update(simpModGrad, . ~ challengRate_lag + . - incsDefeatedFac_lag)

simpModGradc$se <- sqrt(diag(get_CL_vcov(simpModGradc, 
                                  modeldata$distid[!is.na(modeldata$gradRate)])))
lagModGradc <- update(lagModGrad,  . ~ challengRate_lag + . - incsDefeatedFac_lag)
lagModGradc$se <- sqrt(diag(get_CL_vcov(lagModGradc, 
                   modeldata$distid[!is.na(modeldata$gradRate_lag) & 
                                      !is.na(modeldata$gradRate)])))

lagModGradFEc <- update(lagModGradFE,  . ~ challengRate_lag + . - incsDefeatedFac_lag)
lagModGradFEc$se <- sqrt(diag(get_CL_vcov(lagModGradFEc, 
                                         modeldata$distid[!is.na(modeldata$gradRate)])))

prettyNames <- c("Intercept", "Challenge Rate", "Exurb", "Rural", "Board Size",
                  "Electorate Size", "Econ. Disadv. \\%", "Grad Rate Lag", "\\% Bach. +", 
                 "\\% Over 65")

fe.note <- "District fixed effects not displayed."

gradChalRateTab <- apsrtable(simpModGradc, lagModGradc, lagModGradFEc, se = "robust", 
          stars = "default", digits = 3, model.names = c("Simple", "Lag", "FE"), 
          caption = "Challenge Rate and High School Graduation", 
          label = "tab:gradMod2", notes = list(stars.note, fe.note), 
          Sweave = FALSE, 
           omitcoef=list("distid", 
                         expression(grep("distid", coefnames, value=TRUE))), 
          coef.names = prettyNames, size="small")

simpModGradD <- update(simpModGradc, . ~ dissatFactor_lag + . - challengRate_lag)
simpModGradD$se <- sqrt(diag(get_CL_vcov(simpModGradD, 
                                  modeldata$distid[!is.na(modeldata$gradRate)])))
lagModGradD <- update(lagModGradc, . ~ dissatFactor_lag + . - challengRate_lag)
lagModGradD$se <- sqrt(diag(get_CL_vcov(lagModGradD, 
                   modeldata$distid[!is.na(modeldata$gradRate_lag) & 
                                      !is.na(modeldata$gradRate)])))
lagModGradFEd <- update(lagModGradFEc, . ~ dissatFactor_lag + . - challengRate_lag)
lagModGradFEd$se <- sqrt(diag(get_CL_vcov(lagModGradFEd, 
                                         modeldata$distid[!is.na(modeldata$gradRate)])))
prettyNames <- c("Intercept", "Dissat. Factor", "Exurb", "Rural", "Board Size",
                  "ln(VAP)", "FRL \\%", "Grad Rate Lag", "\\% Bach. +", 
                 "\\% Over 65")

fe.note <- "District fixed effects not displayed."

gradDRateTab <- apsrtable(simpModGradD, lagModGradD, lagModGradFEd, se = "robust", 
          stars = "default", digits = 3, model.names = c("Simple", "Lag", "FE"), 
          caption = "Dissatisfaction Factor and High School Graduation", 
          label = "tab:gradMod3", notes = list(stars.note, fe.note), 
          Sweave = FALSE, 
           omitcoef=list("distid", 
                         expression(grep("distid", coefnames, value=TRUE))), 
          coef.names = prettyNames, size="small")
@

\clearpage

\subsection{Superintendent Turnover}

Superintendent turnover models are slightly different in that they are logistic 
regression models predicting a binary outcome of whether the superintendent 
turned over or not. Table \ref{tab:supMod} shows the results of these logistic 
regressions. Here, incumbent defeat is consistently positively related with 
superintendent turnover, but this effect is only statistically significant in 
the first model. The estimated effect is quite large -- an incumbent defeat 
translates into an odds-ratio of 1.31 which can be interpreted as 1.3x increase in 
the probability of the superintendent leaving their position two years after 
an incumbent is defeated. 

<<newSup, results='asis'>>=
modeldata <- dist_turn[, c("distid", "year", "incsDefeated", "servingMembers",
                           "MATH_PROFADV_PER", "NEW_SUP", "SUP_EXPERIENCE",
                           "econ_disadv_per", "VAP_adj", "per65o", 
                           "challengRate", "dissatFactor",
                           "PerBachelorOrAbove", "locale2")]
modeldata$incsDefeatedFac <- ifelse(modeldata$incsDefeated > 0, 1, 0)
modeldata$incsDefeatedFac <- factor(modeldata$incsDefeatedFac)
preTreat <- modeldata[modeldata$year <= 2010,]
preTreat$year <- preTreat$year + 2
names(preTreat) <- paste(names(preTreat), "lag", sep = "_")
modeldata <- modeldata[, c("NEW_SUP", "distid", "year")]
modeldata <- merge(modeldata, preTreat, by.y = c("distid_lag", "year_lag"), 
                 by.x = c("distid", "year"))
modeldata <- modeldata[modeldata$year > 2005, ]
modeldata$SUP_EXPERIENCE_lag <- ifelse(is.na(modeldata$SUP_EXPERIENCE_lag), 0, 
                                       modeldata$SUP_EXPERIENCE_lag)

simpModSup <- glm(NEW_SUP ~ incsDefeatedFac_lag + locale2_lag + 
                    servingMembers_lag + log(VAP_adj_lag), 
                  data = modeldata, family = "binomial")
simpModSup$se <- sqrt(diag(get_CL_vcov(simpModSup, modeldata$distid)))
fullModSup <- glm(NEW_SUP ~ incsDefeatedFac_lag + econ_disadv_per_lag + 
                   log(VAP_adj_lag) + servingMembers_lag + NEW_SUP_lag +
                    locale2_lag + PerBachelorOrAbove_lag + 
                   per65o_lag, data = modeldata, family = "binomial")
fullModSup$se <- sqrt(diag(get_CL_vcov(fullModSup, modeldata$distid)))
library(arm)
fullModSupFE <- bayesglm(NEW_SUP ~ incsDefeatedFac_lag + 
                      econ_disadv_per_lag + log(VAP_adj_lag) + servingMembers_lag +
                      locale2_lag + PerBachelorOrAbove_lag + 
                   per65o_lag + distid, data = modeldata, family = "binomial")
fullModSupFE$se <- sqrt(diag(get_CL_vcov(fullModSupFE, modeldata$distid)))
prettyNames <- c("Intercept", "Inc. Def. Lag", "Exurb", "Rural", "Board Size",
                  "Electorate Size", "Econ. Disadv. \\%", "New Sup. Lag", "\\% Bach. +", 
                 "\\% Over 65")

fe.note <- "District fixed effects not displayed."

apsrtable(simpModSup, fullModSup, fullModSupFE, se = "robust", 
          stars = "default", digits = 3, 
          model.names = c("Simple", "Lag", "FE"), 
          caption = "Incumbent Defeat and Superintendent Turnover", 
          label = "tab:supMod", notes = list(stars.note, fe.note), 
          Sweave = FALSE, 
           omitcoef=list("distid", 
                         expression(grep("distid", coefnames, value=TRUE))), 
          coef.names = prettyNames, size = "small")

@

<<chalRateGrad, results='asis'>>=


simpModSupc <- update(simpModSup, . ~ challengRate_lag + . - incsDefeatedFac_lag)
simpModSupc$se <- sqrt(diag(get_CL_vcov(simpModSupc, modeldata$distid)))
fullModSupc <- update(fullModSup, . ~ challengRate_lag + . - incsDefeatedFac_lag)
fullModSupc$se <- sqrt(diag(get_CL_vcov(fullModSupc, modeldata$distid)))
fullModSupFEc <- update(fullModSupFE, . ~ challengRate_lag + . - incsDefeatedFac_lag)
fullModSupFEc$se <- sqrt(diag(get_CL_vcov(fullModSupFEc, modeldata$distid)))

prettyNames <- c("Intercept", "Challenge Rate", "Exurb", "Rural", "Board Size",
                  "Electorate Size", "Econ. Disadv. \\%", "New Sup. Lag", "\\% Bach. +", 
                 "\\% Over 65")

apsrtable(simpModSupc, fullModSupc, fullModSupFEc, se = "robust", 
          stars = "default", digits = 3, 
          model.names = c("Simple", "Lag", "FE"), 
          caption = "Challenge Rate and Superintendent Turnover", 
          label = "tab:supMod2", notes = list(stars.note, fe.note), 
          Sweave = FALSE, 
           omitcoef=list("distid", 
                         expression(grep("distid", coefnames, value=TRUE))), 
          coef.names = prettyNames, size = "small")
@

<<dissatFatGrad, results='asis'>>=
simpModSupd <- update(simpModSupc, . ~ dissatFactor_lag + . - challengRate_lag)
simpModSupd$se <- sqrt(diag(get_CL_vcov(simpModSupc, modeldata$distid)))
fullModSupd <- update(fullModSupc, . ~ dissatFactor_lag + . - challengRate_lag)
fullModSupd$se <- sqrt(diag(get_CL_vcov(fullModSupc, modeldata$distid)))
fullModSupFEd <- update(fullModSupFEc, . ~ dissatFactor_lag + . - challengRate_lag)
fullModSupFEd$se <- sqrt(diag(get_CL_vcov(fullModSupFEc, modeldata$distid)))

prettyNames <- c("Intercept", "Dissat. Factor", "Exurb", "Rural", "Board Size",
                  "Electorate Size", "Econ. Disadv. \\%", "New Sup. Lag", "\\% Bach. +", 
                 "\\% Over 65")

apsrtable(simpModSupd, fullModSupd, fullModSupFEd, se = "robust", 
          stars = "default", digits = 3, 
          model.names = c("Simple", "Lag", "FE"), 
          caption = "Dissatisfaction Factor and Superintendent Turnover", 
          label = "tab:supMod3", notes = list(stars.note, fe.note), 
          Sweave = FALSE, 
           omitcoef=list("distid", 
                         expression(grep("distid", coefnames, value=TRUE))), 
          coef.names = prettyNames, size = "small")

@

The results for challenge rate and the dissatisfaction factor in Tables 
\ref{tab:supMod2} and \ref{tab:supMod3} are even stronger -- with a consistent 
positive statistically significant relationship. These findings confirm findings 
like \citet{RefWorks:246} that board dissatisfaction does lead to superintendent 
turnover. 

\subsection{Fiscal Outcomes}

Table \ref{tab:millrateDelta} shows the results for the dissatisfaction factor 
on the millrate change in school districts two years later. Across specifications 
there is a consistent negative coefficient suggesting that stronger dissatisfaction 
leads to a millrate decrease in the future. However, this coefficient is only 
statistically significant in the lagged specification, and none of the models 
have a respectable $R^{2}$. 

<<taxoutcomesMD, results='asis'>>=
modeldata <- dist_turn[, c("distid", "year", "incsDefeated", "servingMembers",
                           "NEW_SUP", "SUP_EXPERIENCE", "dissatFactor", 
                           "econ_disadv_per", "VAP_adj", "per65o", "challengRate",
                           "PerBachelorOrAbove", "locale2", "incsTotal", 
                           "millrate_delta", "millrate", "ADJ_MEDIAN_SALARY_TEACH", 
                           "overrideQues", "debtQues", "debtPass", "overridePass")]

modeldata$incsDefeatedFac <- ifelse(modeldata$incsDefeated > 0, 1, 0)
modeldata$incsDefeatedFac <- factor(modeldata$incsDefeatedFac)
preTreat <- modeldata[modeldata$year <= 2010,]
preTreat$year <- preTreat$year + 2
names(preTreat) <- paste(names(preTreat), "lag", sep = "_")
modeldata <- modeldata[, c("millrate_delta", "millrate", "ADJ_MEDIAN_SALARY_TEACH", 
                           "overrideQues", "debtQues", "debtPass", 
                           "overridePass", "distid", "year")]

modeldata <- merge(modeldata, preTreat, by.y = c("distid_lag", "year_lag"), 
                 by.x = c("distid", "year"))
modeldata <- modeldata[modeldata$year > 2005, ]
modeldata$SUP_EXPERIENCE_lag <- ifelse(is.na(modeldata$SUP_EXPERIENCE_lag), 0, 
                                       modeldata$SUP_EXPERIENCE_lag)

simpModMillDelta <- lm(millrate_delta ~ dissatFactor_lag + locale2_lag  +
                    servingMembers_lag + log(VAP_adj_lag), 
                  data = modeldata)
simpModMillDelta$se <- sqrt(diag(get_CL_vcov(simpModMillDelta, modeldata$distid)))

lagModMillDelta <- lm(millrate_delta ~ dissatFactor_lag + econ_disadv_per_lag + 
                   millrate_delta_lag + servingMembers_lag + 
                   log(VAP_adj_lag) + locale2_lag + PerBachelorOrAbove_lag + 
                   per65o_lag, data = modeldata)
lagModMillDelta$se <- sqrt(diag(get_CL_vcov(lagModMillDelta, 
                   modeldata$distid[!is.na(modeldata$millrate_delta_lag)])))
millDeltaFE <- lm(millrate_delta ~ dissatFactor_lag + econ_disadv_per_lag + 
                   log(VAP_adj_lag) + locale2_lag + PerBachelorOrAbove_lag + 
                      servingMembers_lag + per65o_lag + distid, 
                   data = modeldata)
millDeltaFE$se <- sqrt(diag(get_CL_vcov(millDeltaFE, modeldata$distid)))

prettyNames <- c("Intercept", "D-Factor", "Exurb", "Rural", "Board Size",
                  "Electorate Size", "Econ. Disadv. \\%", "MillRate delta Lag", "\\% Bach. +", 
                 "\\% Over 65")

fe.note <- "District fixed effects not displayed."

apsrtable(simpModMillDelta, lagModMillDelta, millDeltaFE, se = "robust", 
          stars = "default", digits = 3, model.names = c("Simple", "Lag", "FE"), 
          caption = "Dissatisfaction and Millrate Changes", 
          label = "tab:millrateDelta", notes = list(stars.note, fe.note), 
          Sweave = FALSE, 
           omitcoef=list("distid", 
                         expression(grep("distid", coefnames, value=TRUE))), 
          coef.names = prettyNames, size = "small")
@

Table \ref{tab:salaryLag} shows the results for the teacher median salary. In 
all the specifications dissatisfaction is associated with a decrease in teacher 
salary (dependent variable is on the log-scale here), but only in the simple 
specification is this effect statistically significant. It's easy to see why, 
while the simple model explains a healthy amount of the variance in teacher 
salary, including the fixed effects or the lags reduces the variance too greatly 
for the dissatisfaction factor to retain its predictive power. 

<<taxresultsTeachSal, results='asis'>>=
modeldata$ADJ_MEDIAN_SALARY_TEACH <- log(modeldata$ADJ_MEDIAN_SALARY_TEACH)
modeldata$ADJ_MEDIAN_SALARY_TEACH_lag <- log(modeldata$ADJ_MEDIAN_SALARY_TEACH_lag)
modeldata$yearF <- factor(modeldata$year)
modeldata <- modeldata[modeldata$ADJ_MEDIAN_SALARY_TEACH > 10.2,]

simpModSal <- lm(ADJ_MEDIAN_SALARY_TEACH ~ dissatFactor_lag + locale2_lag  +
                    servingMembers_lag + log(VAP_adj_lag) + yearF, 
                  data = modeldata)
simpModSal$se <- sqrt(diag(get_CL_vcov(simpModSal, modeldata$distid)))

lagModSal <- lm(ADJ_MEDIAN_SALARY_TEACH ~ dissatFactor_lag + econ_disadv_per_lag + 
                   ADJ_MEDIAN_SALARY_TEACH_lag + servingMembers_lag + 
                   log(VAP_adj_lag) + locale2_lag + PerBachelorOrAbove_lag + 
                   per65o_lag + yearF, data = modeldata)
lagModSal$se <- sqrt(diag(get_CL_vcov(lagModSal, 
                   modeldata$distid[!is.na(modeldata$millrate_delta_lag)])))
FEmodSal <- lm(ADJ_MEDIAN_SALARY_TEACH ~ dissatFactor_lag + econ_disadv_per_lag + 
                   log(VAP_adj_lag) + locale2_lag + PerBachelorOrAbove_lag + 
                      servingMembers_lag + per65o_lag + yearF + distid, 
                   data = modeldata)
millDeltaFE$se <- sqrt(diag(get_CL_vcov(FEmodSal, modeldata$distid)))

prettyNames <- c("Intercept", "D-Factor", "Exurb", "Rural", "Board Size",
                  "Electorate Size", "Econ. Disadv. \\%", "Teach Salary Lag", "\\% Bach. +", 
                 "\\% Over 65")

fe.note <- "District and year fixed effects not displayed."

apsrtable(simpModSal, lagModSal, FEmodSal, se = "robust", 
          stars = "default", digits = 3, model.names = c("Simple", "Lag", "FE"), 
          caption = "Dissatisfaction and Teacher Salary Changes", 
          label = "tab:salaryLag", notes = list(stars.note, fe.note), 
          Sweave = FALSE, 
           omitcoef=list("distid", 
                         expression(grep("distid", coefnames, value=TRUE)), 
                         "yearF", 
                         expression(grep("yearF", coefnames, value=TRUE))), 
          coef.names = prettyNames, size = "small")
@


\clearpage

\section{Conclusion}

There is little evidence that school board turnover is related to student 
outcomes across any measure of dissatisfaction. If anything, it was found to be 
counter to the prior findings in the literature which found a small positive 
affect on student achievement after school board electoral defeats. At best, 
the findings above provide some evidence 
that suggests that communities with lower student outcomes have more board 
turnover. Models that try to identify the causal relationship by controlling 
for prior levels of achievement or within-district changes in student outcomes 
did not have any findings. This is, at least in part, due to the nature of the 
measures of student performance available which show very little year to year 
variation net of student characteristics and prior achievement or graduation rates. 

The story for superintendent turnover is different. Across the three measures 
of school board dissatisfaction, a positive statistically significant relationship 
with superintendent turnover was identified. The stability of the prediction 
across increasingly restrictive model specifications provides strong evidence 
that an increase in candidates, challengers and defeats for school board in a 
school district increases the likelihood the superintendent will turnover. 

Finally, on the fiscal measures there was some evidence that dissatisfaction is 
associated with a decrease in property taxes -- but the effect was weak. It 
appears more likely that school board challenges are unable to affect either 
salary schedules or tax rates. Of the findings in this chapter, these are 
likely the least generalizable to other states given the peculiarities of 
Wisconsin's revenue limit and equalization aid funding system -- which shapes 
both which districts have millrate flexibility and limits funds available for 
salary expenditures. 

Future work is needed to explore the mechanisms here. First, a limitation of 
this study is the inability to distinguish between types of superintendent 
turnover including retirement, buyout, and firing. Another limitation is the 
limited window -- using a twice lagged model is preferable, but both board 
and superintendent turnover may need to be analyzed from a three year rolling 
average basis to best measure this. For the fiscal measures, it remains to be 
seen if the new powers granted to school boards by Act 10 result in a change 
in this relationship and an increased responsiveness of school boards to 
community dissatisfaction using new fiscal flexibility. 

These results provide a first step, perhaps, toward answering the puzzle posed 
in the previous chapters. If democratic potential is so high in school board 
elections, why is actualized democracy so weak? One answer might be the dismal 
prospects for school boards to meaningfully change salient high-profile indicators 
of school district functioning -- student performance, leadership, and salaries 
and tax rates. The average citizen would be forgiven from opting out of learning 
about, or worse sitting on, an elected body which is unable to make measurable 
changes in schools. While the evidence presented in this chapter is just one 
set of measures of one slice of school district functioning, it's longitudinal 
nature allows a window into the true impact of school boards that previous 
cross-sectional studies could not provide. The democratic promise appears, from 
this view, to go unfulfilled in response to the weak track record of school board 
election activity resulting in meaningful change. 


\section{Appendix}

Sub-analysis of challenger rate models instead of incumbent defeat. The results 
here are largely the same.

<<printChalRates, results='asis'>>=
mathChalRateTab

readChalRateTab

gradChalRateTab

mathDRateTab

readDRateTab

gradDRateTab

@