\chapter{Policy Implications of School Board Votes}
\label{chap:policy}
\chapterstyle{deposit}

<<rsetup, results='hide', echo=FALSE, message=FALSE, warning=FALSE>>=
#setwd("../../../Data/Raw Files/Election Data")
#setwd("../Data/Raw Files/Election Data")
# source("dataclean.R")
# source("mappingfunctions.R")
# source("k8uhs.R")
opts_chunk$set(fig.width=8, fig.height=6, message=FALSE, error=FALSE, 
               fig.path="../../phd_figs/chap5-",
               warning=FALSE, echo=FALSE, dev='pdf')
@

Outline:

