\chapter{Policy Implications of School Board Votes}
\label{chap:policy}
\chapterstyle{deposit}

<<rsetup, results='hide', echo=FALSE, message=FALSE, warning=FALSE>>=
#setwd("../../../Data/Raw Files/Election Data")
#setwd("../Data/Raw Files/Election Data")
opts_chunk$set(fig.width=8, fig.height=6, message=FALSE, error=FALSE, 
               fig.path="../../phd_figs/chap6-",
               warning=FALSE, echo=FALSE, dev=c('pdf', 'png'))

setwd("../../")
library(eeptools)
source("R/thesis_functions.R")
source("data/cleanandprep_POLICY.R")
library(scales)
library(xtable)
options(xtable.include.rownames = FALSE, xtable.table.placement = "ht")
library(devtools)
install_github("jknowles/apsrtable", subdir = "pkg", ref = "dev")
library(apsrtable)
stars.note <- apsrtable:::stars.note
@

\section{Introduction}

School boards have considerable power over local issues in their community. 
We have seen that school boards are often responsible for setting property tax
levies, labor relations with teachers and support staff within the school, and
often serve as the largest single employer in their community. The driving idea
behind locally elected school boards was to ensure that the local community
retained some control over the direction taken by the schools in their community
and to ensure that the school system was responsive to the preferences of that
community. Until now there have only been limited tests of school board 
responsiveness. 

The challenge in testing school board responsiveness is great. First, in most 
cases school boards are non-partisan offices and education issues do not fall 
along traditional ideological lines \citep[for counter example:][]{RefWorks:347}. 
This poses a challenge for researchers seeking evidence of such responsiveness. 
Additionally, the majority of school board election activity is low-impact and 
low-cost, eliminating traditional ways of measuring the information provided to 
voters about candidates and their policy preferences \citep{RefWorks:322, RefWorks:321}. 

Voter policy preferences were expressed and made clear through two elections in 
Wisconsin - the 2010 Gubernatorial election, and updated with the 2011 recall 
election. 

% Does board member turnout change anything? 
% Does it change superintendents?
% Does it change test scores?
% Board turnover writ large = change
% Incumbent defeat should change things


<<incdefeat, results='hide'>>=
dist_turn$incDefeats <- NULL
incDefeat <- ddply(dat[dat$electiontype == 1,], 
                   .(distid, year), 
                   summarise, 
                   incsDefeated = sum(incumbent[winner == 0]), 
                   incsTotal = sum(incumbent), 
                   winnersTotal = sum(winner))
# TODO:
# Why is this?
# incumbents defeated can exceed number of winners, especially when races 
# consolidate
fw  <- function(x) c(x[2:length(x)], NA)

dist_turn <- merge(dist_turn, incDefeat, by = c("distid", "year")) 
dist_turn$boardTurnover <- dist_turn$incsDefeated / dist_turn$servingMembers

library(data.table)
dist_turn <- dist_turn[order(dist_turn$distid, dist_turn$year),]
dist_turn <- as.data.table(dist_turn)[, NEW_SUP_FW:= fw(NEW_SUP), by = "distid"]
dist_turn <- as.data.table(dist_turn)[, 
                                      READ_PROFADV_PER_LAG:= lg(READ_PROFADV_PER),
                                      by = "distid"]
dist_turn <- as.data.table(dist_turn)[, 
                                      MATH_PROFADV_PER_LAG:= lg(MATH_PROFADV_PER),
                                      by = "distid"]
dist_turn <- as.data.table(dist_turn)[, 
                                      incsDefeatedLag:= lg(incsDefeated),
                                      by = "distid"]
dist_turn <- as.data.table(dist_turn)[, 
                                      incsTotalLag:= lg(incsTotal),
                                      by = "distid"]
dist_turn <- as.data.table(dist_turn)[, 
                                      winnersTotalLag:= lg(winnersTotal),
                                      by = "distid"]
dist_turn <- as.data.table(dist_turn)[, 
                                      nrealcandLag:= lg(nrealcand),
                                      by = "distid"]

dist_turn <- as.data.frame(dist_turn)

# head(dist_turn[, c("distid", "year", "NEW_SUP", 
#                  "NEW_SUP_FW", "READ_PROFADV_PER", "READ_PROFADV_PER_LAG")], 25)
@

\section{School Boards and Policy Change}

The literature on school boards affecting policy change is dominated by a focus 
on three areas - 1) superintendent turnover as policy change, 2) setting tax
levies, or 3) making direct policy changes about social issues, and 4) changes
resulting in student outcomes. 

Much of the work referred to in Chapter \ref{chap:intro} dealt with the impact 
of school boards on policy change. In fact, both the dissatisfaction theory and the public choice theories of school board politics include superintendent
turnover as key evidence \citep{RefWorks:297,RefWorks:271, RefWorks:351, RefWorks:339,RefWorks:340,RefWorks:243}. Recently a key improvement in empirical tests 
of this work has focused on political vs. apolitical turnover, typically 
retirement, among school board members and superintendents \citep{RefWorks:311}. 

There is a strong public economics literature that views school boards as agents 
that set the price for the public good of education through property tax rates. % citations needed

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Find citations about public finance from Reschovsky work
%


\citet{RefWorks:347} represents the most thorough study of school boards as agents 
of change in social issues. Some view school boards as potentially captured by 
special interest groups \citep{RefWorks:320}. There is evidence that when 
boards are elected, they become more responsive to interest groups than previously 
when they were appointed \citep{RefWorks:242}. 

\citet{RefWorks:347} represents the most thorough study of school boards as 
agents of change in social issues. Some view school boards as potentially 
captured by special interest groups \citep{RefWorks:320}. There is evidence that
when boards are elected, they become more responsive to interest groups than
previously when they were appointed \citep{RefWorks:242}. 

Boards can influence student outcomes through a range of decisions - some direct 
and some less direct. \citet{RefWorks:210} provides an example by examining the 
relationship between board decisions to consolidate school districts and the 
resulting changes in student achievement. On a more universal basis, 
\citet{RefWorks:214} explores if boards change policies in response to public
accountability for student achivement, and if this results in improvements in
student achievement.\footnote{This argument assumes a certain level of 
effectiveness that is not captured by any measures in the current study and 
may not be evenly distributed across boards \citep{RefWorks:237,RefWorks:261}.} 
In many cases, boards are criticized as being highly constrained actors with 
little room to set policy after complying with state and federal mandates 
\citep{RefWorks:316}, although the extent of this is not clear 
\citep{RefWorks:223}.\footnote{Note that this argument can be reduced down ever
further to the impact of district policies on schools or school policies on
classroom \citep{RefWorks:255}}

Yet boards allocate resources, and resources matter \citep{RefWorks:183}. 

\section{Theory}

Figure \ref{fig:model} can be seen as the primary representation of the model of school board politics and policy change that the present study seeks to evaluate.
Building on the work in Chapters \ref{chap:turnout} and \ref{chap:candidacy}, 
this chapter combines the political conditions in school districts and the 
changes that result in school outcomes. 

While previous chapters examined the exercise of democratic control 
of school board elections -- under what conditions did voters and candidates 
participate, and was this participation sensitive to policy pressures -- this 
chapter seeks to understand the result of such participation. In order for 
democratic institutions to matter, the results of elections must also matter. 
Challengers must represent a policy alternative to defeated incumbents. Policy 
distinction must be seen among candidates. 

Incumbent defeat provides a strong sign that citizens are dissatisfied with the 
existing outputs of their school government and wish to see changes. Without 
polling data or an in-depth study of the politics of each community, it is 
difficult to understand what might be the source of this voter dissatisfaction 
and what voters might wish to see change. In this study I look for evidence of 
change along the two dimensions previously identified in the literature as 
critical to voters -- the district administrator and student performance. If 
voters are dissatisfied with their board and replace some board members with new 
challengers, it is likely that they demand higher student performance, new 
district management, or both. 


\section{Data}

To study the impacts of incumbent defeat in Wisconsin school districts I employ 
a panel data set of school board election outcomes matched to school district 
administrative records. To code incumbent defeat, I matched a roster of known 
school board members in a given school year against the victors in the following 
school year to identify which candidates were incumbents. Though both the roster 
and the election results require some judgment in assessing their accuracy, 
this represents a strong measure of incumbency and electoral defeat for school 
board members in 300 Wisconsin school districts from 2002-2012. 

\subsection{Independent Variables}

Previous chapters have established that school board incumbent defeat is rare 
because incumbents are rarely challenged, and even more rarely is that challenge 
serious. Incumbents often face no challenge or leave office without running for 
re-election. As we have seen, previous research on school board incumbent 
defeat has focused on correctly measuring political and apolitical turnover 
by focusing on incumbents who are defeated, not simply those who do not return 
to the board for another term. 

Timing is of critical importance in assessing the \emph{impact} of school board 
incumbent defeat. While school board members are elected in spring elections, 
their term begins the following fall. It is not reasonable to expect school 
board members to have time after taking office to affect student outcomes or 
superintendent contracts. As such, I lag incumbent defeat to allow for an 
additional year. 

% Check measurement of incumbent defeat 
% Measure share of board that turnsover, vs. any incumbent defeat, vs. count of
% incumbent defeats -- which is best

It is also insufficient to simply turn over a single board member and expect 
broad policy change if consensus existed among the other board members. 

% Triple check the timing of the board elections, spring of 2012 is merged with 
% which year of administrative records? Document this decision

\subsection{Outcomes}

I am primarily interested in the effect of board turnover on two classes of 
outcomes. First, and most directly, boards are charged with hiring and monitoring 
the performance of a district administrator who manages the academic and 
financial affairs of the district. The choice of superintendent is critical to 
the board as the superintendent is the board's primary conduit of information 
about the health of the district and the educational strategies in place for 
students. Superintendent turnover is a primary prediction of dissatisfaction 
theory, and rightfully so. If voters are unhappy with the state of affairs in 
their school district, in all likelihood they are unhappy with the performance 
of their district administrator. 

More indirectly, school boards are responsible for setting policy and directing 
the superintendent to provide quality education. Thus, incumbent defeat may 
serve as a method by which the community can express its demand for higher 
quality education as measured by accountability measures such as student 
test scores and graduation rates. 


\section{Methods}

Measuring the impact of school board turnout on superintendent turnover and 
student outcomes is difficult because of the large number of competing 
forces shaping these outcomes. Student performance is largely predicted by 
family income and parental education levels. Superintendent turnover may be 
related to salary and the prestige associated with leading certain school 
districts. In order to better understand the impact of school board turnover 
net of these factors, I employ a regression strategy to control for as many 
of these observable and unobservable factors as possible. 


I employ two distinct modeling strategies. The first is the most restrictive. 
As in previous chapters, I employ the bounding strategy suggested by \citet{mhe} 
to leverage the repeated observations in my data to compare, where possible, 
school districts within themselves. The disadvantage of this strategy is that 
for the outcomes in question, relatively little variance remains to be explained 
after accounting for all between school district effects, because the within 
school district variation is so small. 

The second strategy is more susceptible to unobserved alternative explanatory 
variables, but attempts to explain the variation in outcomes between school 
districts by comparing school districts with similar demographic 
charcteristics, but which differ on their incumbent defeat. 


\section{Results}


\subsection{Student Outcomes}

<<testScoresR, results='asis'>>=
modeldata <- dist_turn[, c("distid", "year", "incsDefeated", "servingMembers",
                           "READ_PROFADV_PER", "NEW_SUP", "SUP_EXPERIENCE",
                           "econ_disadv_per", "VAP_adj", "per65o", 
                           "PerBachelorOrAbove", "locale2")]
modeldata$incsDefeatedFac <- ifelse(modeldata$incsDefeated > 0, 1, 0)
modeldata$incsDefeatedFac <- factor(modeldata$incsDefeatedFac)
preTreat <- modeldata[modeldata$year <= 2010,]
preTreat$year <- preTreat$year + 2
names(preTreat) <- paste(names(preTreat), "lag", sep = "_")
modeldata <- modeldata[, c("READ_PROFADV_PER", "distid", "year")]
modeldata <- merge(modeldata, preTreat, by.y = c("distid_lag", "year_lag"), 
                 by.x = c("distid", "year"))
modeldata <- modeldata[modeldata$year > 2005, ]
modeldata$SUP_EXPERIENCE_lag <- ifelse(is.na(modeldata$SUP_EXPERIENCE_lag), 0, 
                                       modeldata$SUP_EXPERIENCE_lag)

simpModRead <- lm(READ_PROFADV_PER ~ incsDefeatedFac_lag + locale2_lag  +
                    servingMembers_lag, 
                  data = modeldata)
simpModRead$se <- sqrt(diag(get_CL_vcov(simpModRead, modeldata$distid)))
lagModRead <- lm(READ_PROFADV_PER ~ incsDefeatedFac_lag + econ_disadv_per_lag + 
                   READ_PROFADV_PER_lag + servingMembers_lag + 
                   log(VAP_adj_lag) + locale2_lag + PerBachelorOrAbove_lag + 
                   per65o_lag, data = modeldata)
lagModRead$se <- sqrt(diag(get_CL_vcov(lagModRead, 
                   modeldata$distid[!is.na(modeldata$READ_PROFADV_PER_lag)])))
lagModReadFE <- lm(READ_PROFADV_PER ~ incsDefeatedFac_lag + econ_disadv_per_lag + 
                   log(VAP_adj_lag) + locale2_lag + PerBachelorOrAbove_lag + 
                      servingMembers_lag + per65o_lag + distid, 
                   data = modeldata)
lagModReadFE$se <- sqrt(diag(get_CL_vcov(lagModReadFE, modeldata$distid)))

apsrtable(simpModRead, lagModRead, lagModReadFE, se = "robust", 
          stars = "default", digits = 3, model.names = c("Lag"), 
          caption = "Incumbent Defeat and Student Scores", 
          label = "tab:readMod", notes = list(stars.note), 
          Sweave = TRUE, 
           omitcoef=list("distid", 
                         expression(grep("distid", coefnames, value=TRUE))))
@



<<testScoresM, results='asis'>>=
modeldata <- dist_turn[, c("distid", "year", "incsDefeated", "servingMembers",
                           "MATH_PROFADV_PER", "NEW_SUP", "SUP_EXPERIENCE",
                           "econ_disadv_per", "VAP_adj", "per65o", 
                           "PerBachelorOrAbove", "locale2")]
modeldata$incsDefeatedFac <- ifelse(modeldata$incsDefeated > 0, 1, 0)
modeldata$incsDefeatedFac <- factor(modeldata$incsDefeatedFac)
preTreat <- modeldata[modeldata$year <= 2010,]
preTreat$year <- preTreat$year + 2
names(preTreat) <- paste(names(preTreat), "lag", sep = "_")
modeldata <- modeldata[, c("MATH_PROFADV_PER", "distid", "year")]
modeldata <- merge(modeldata, preTreat, by.y = c("distid_lag", "year_lag"), 
                 by.x = c("distid", "year"))
modeldata <- modeldata[modeldata$year > 2005, ]
modeldata$SUP_EXPERIENCE_lag <- ifelse(is.na(modeldata$SUP_EXPERIENCE_lag), 0, 
                                       modeldata$SUP_EXPERIENCE_lag)

simpModMath <- lm(MATH_PROFADV_PER ~ incsDefeatedFac_lag + locale2_lag, 
                  data = modeldata)
simpModMath$se <- sqrt(diag(get_CL_vcov(simpModMath, modeldata$distid)))
lagModMath <- lm(MATH_PROFADV_PER ~ incsDefeatedFac_lag + econ_disadv_per_lag + 
                   MATH_PROFADV_PER_lag +
                   log(VAP_adj_lag) + locale2_lag + PerBachelorOrAbove_lag + 
                   per65o_lag, data = modeldata)
lagModMath$se <- sqrt(diag(get_CL_vcov(lagModMath, 
                   modeldata$distid[!is.na(modeldata$MATH_PROFADV_PER_lag)])))
lagModMathFE <- lm(MATH_PROFADV_PER ~ incsDefeatedFac_lag + econ_disadv_per_lag + 
                   log(VAP_adj_lag) + locale2_lag + PerBachelorOrAbove_lag + 
                   per65o_lag + distid, data = modeldata)
lagModMathFE$se <- sqrt(diag(get_CL_vcov(lagModMathFE, modeldata$distid)))

apsrtable(simpModMath, lagModMath, lagModMathFE, se = "robust", 
          stars = "default", digits = 3, model.names = c("Lag"), 
          caption = "Incumbent Defeat and Student Scores", 
          label = "tab:readMod", notes = list(stars.note), 
          Sweave = TRUE, 
           omitcoef=list("distid", 
                         expression(grep("distid", coefnames, value=TRUE))))
@

% HSC 


\subsection{Student Outcomes}

\subsection{Superintendent Turnover}

<<newSup, results='asis'>>=
modeldata <- dist_turn[, c("distid", "year", "incsDefeated", 
                           "MATH_PROFADV_PER", "NEW_SUP", "SUP_EXPERIENCE",
                           "econ_disadv_per", "VAP_adj", "per65o", 
                           "PerBachelorOrAbove", "locale2")]
modeldata$incsDefeatedFac <- ifelse(modeldata$incsDefeated > 0, 1, 0)
modeldata$incsDefeatedFac <- factor(modeldata$incsDefeatedFac)
preTreat <- modeldata[modeldata$year <= 2010,]
preTreat$year <- preTreat$year + 2
names(preTreat) <- paste(names(preTreat), "lag", sep = "_")
modeldata <- modeldata[, c("NEW_SUP", "distid", "year")]
modeldata <- merge(modeldata, preTreat, by.y = c("distid_lag", "year_lag"), 
                 by.x = c("distid", "year"))
modeldata <- modeldata[modeldata$year > 2005, ]
modeldata$SUP_EXPERIENCE_lag <- ifelse(is.na(modeldata$SUP_EXPERIENCE_lag), 0, 
                                       modeldata$SUP_EXPERIENCE_lag)

simpModSup <- glm(NEW_SUP ~ incsDefeatedFac_lag + locale2_lag, 
                  data = modeldata, family = "binomial")
simpModSup$se <- sqrt(diag(get_CL_vcov(simpModSup, modeldata$distid)))
fullModSup <- glm(NEW_SUP ~ incsDefeatedFac_lag + econ_disadv_per_lag + 
                   log(VAP_adj_lag) + locale2_lag + PerBachelorOrAbove_lag + 
                   per65o_lag, data = modeldata, family = "binomial")
fullModSup$se <- sqrt(diag(get_CL_vcov(fullModSup, modeldata$distid)))
library(arm)
fullModSupFE <- bayesglm(NEW_SUP ~ incsDefeatedFac_lag + 
                      econ_disadv_per_lag + log(VAP_adj_lag) + 
                      locale2_lag + PerBachelorOrAbove_lag + 
                   per65o_lag + distid, data = modeldata, family = "binomial")
fullModSupFE$se <- sqrt(diag(get_CL_vcov(fullModSupFE, modeldata$distid)))

apsrtable(simpModSup, fullModSup, fullModSupFE, se = "robust", 
          stars = "default", digits = 3, 
          model.names = c("Simple", "Full", "Fixed Effect"), 
          caption = "Incumbent Defeat and Student Scores", 
          label = "tab:readMod", notes = list(stars.note), 
          Sweave = TRUE, 
           omitcoef=list("distid", 
                         expression(grep("distid", coefnames, value=TRUE))))
@


\clearpage

\section{Conclusion}

This chapter has looked for evidence of the impact of school board electoral 
defeat. 



