\chapter{Assessing the Causal Impact of Policy Shocks}
\label{chap:walker}
\chapterstyle{deposit}

<<rsetup, results='hide', echo=FALSE, message=FALSE, warning=FALSE>>=
opts_chunk$set(fig.width=8, fig.height=6, message=FALSE, error=FALSE, 
               fig.path="../../phd_figs/chap6-",
               warning=FALSE, echo=FALSE, dev='pdf')

setwd("../../")
library(scales)
library(xtable)
library(eeptools)
source("R/thesis_functions.R")
source("data/cleanandprep_WALKER.R")
options(xtable.include.rownames = FALSE, xtable.table.placement = "ht")
# Set up tables
library(devtools)
install_github("jknowles/apsrtable", subdir = "pkg", ref = "dev")
library(apsrtable)
stars.note <- apsrtable:::stars.note
# Quick variable transform
dist_turn$VAP_adjLOG_sq <- dist_turn$VAP_adjLOG^2
dist_turn$RecallPolarization <- 1 - abs(dist_turn$GovTwoPartyShareDem_recall - dist_turn$GovTwoPartyShareRep_recall)
dist_turn$RecallPolarization <- dist_turn$RecallPolarization * 100
dist_turn$contestMinor <- factor(dist_turn$contestMinor)
dist_turn$contestSer <- factor(dist_turn$contestSer)
dist_turn$onlyIncum <- ifelse(dist_turn$incumShare == 1, 1, 0)
dist_turn$nonincumbRun <- ifelse(dist_turn$onlyIncum == 1, 0, 1)
dist_turn$incDefeats <- ifelse(dist_turn$incDefeats > 0, 1, 0)
# consider diminishing returns to these
# dist_turn$minBlaisLago[dist_turn$minBlaisLago == 0] <- .0001
# dist_turn$minBlaisLago <- log(dist_turn$minBlaisLago)
# dist_turn$partyDivisionRecent <- log(dist_turn$partyDivisionRecent)

library(gridExtra)
@


\section{Introduction}

While the previous chapters have explored whether understanding of national and 
state level electoral activity can explain school board electoral activity, this 
chapter uses a different approach. I leverage a natural experiment created by 
the unprecedented policy shock of the passage of Act 10 in Wisconsin following the 
election of Governor Scott Walker to test whether or not local electoral activity 
can be influenced directly by state level policy. This question falls into a broader 
literature unpacking the federalist entanglements of the multi-level system of 
government in the US. The question of whether a policy shock at a higher level of 
government can influence electoral activity at lower levels of government is 
directly relevant to studies of the policy making process and the system of feedback 
and interaction between policy and electoral activity. 

There are two reasons to believe that the policy shock associated with the passage 
of Wisconsin Act 10 would lead to an increase in voter and candidate participation 
in school board elections. The first is that the political debate around Act 10, 
the historic protests, and the recall election campaign all increased the amount 
of information voters had about school boards, school board powers, and the 
positions of their local school boards. This increase in information decreased 
the costs associated with voting, and increased the ability of candidates to 
distinguish themselves (by taking a clear position on Act 10), making it more 
likely both voters and candidates would participate. 

Another mechanism comes from the new power granted to school boards. After Act 10 
boards were given the ability to unilaterally set compensation plans for their 
staff, which account for approximately 90\% of their annual operating costs. This 
new power strongly incentivized both employee unions and property owners to express 
their policy preference for school district expenditures to mobilize both candidates 
and voters. School boards now, more than ever, had the chance to actualize the 
preferences of voters either to hold down property taxes, or to protect school 
staff from budget cuts. 

What are the motivations of both candidates and voters that might be greater 
after this state level policy than before? For candidates, the door is opened 
for reformers who want to challenge status quo taxation and compensation policy. 
These candidates may seek to challenge current board members and capitalize on the 
increased public awareness about school funding and compensation plans to distinguish 
themselves from incumbents. Additionally, these candidates have more information 
about the likelihood of their success based on the implied or revealed preferences 
of the voters in their school district for Governor Walker -- both in the 2010 
Gubenatorial race and in the 2012 recall. 

For voters, the advantages are perhaps even more clear. Now voters have a high 
profile polarizing issue into which to divide candidates. This increases the 
information available for voters, decreasing the costs of voting. Additionally, 
if boards are given more power, voters have more reason to believe that their 
policy preferences can be actualized by electing a candidate more closely related 
to their preferences. 

It is important to stop and consider why this can be considered an exogenous 
shock, and thus allow for some causal inference. Figure \ref{fig:wiscotimeline2} 
shows the sequence of events in Wisconsin from 2011 to 2013. It shows that the 
2011 and 2012 spring elections were both post passage of Wisconsin Act 10. The 
2011 election was also marked by a highly contested statewide Supreme Court 
election and the ultimate effect of Act 10 was in doubt due to multiple legal 
challenges. By the 2012 election, Act 10 had been ruled constitutional and there 
was no state supreme court seat up for election. 

\clearpage
\begin{center}
\begin{figure}[h!]
\caption{Wisconsin Politics 2011-2013 Timeline}
\label{fig:wiscotimeline2}
\includegraphics[width=\textwidth,height=1.75in]{img/wiscotimeline}
\end{figure}
\end{center}
\vspace{-48pt}

An additional advantage of this exogenous shock for the study of school board 
elections is that it creates three unique measures available statewide to peer 
into the preferences of communities. First, the level of polarization in the 
community in the recall election of Scott Walker. The result of this election can 
be seen largely as an opinion poll of voters on the issues of Act 10 and education 
funding in the state -- the two largest issues in the campaign.\footnote{While some have 
argued that another issue, the legitimacy of recalling the Governor in the first 
place was also important, this may also be a reflection on how strongly those 
voters felt about Act 10 in the first place.} All else equal, more polarized 
communities should exhibit greater contestation and turnout in school board 
elections due to the deeper conflict over the best way to manage public schools. 

A second measure that arises from this period is the level of turnout for the 
recall election itself. As with any election, voters without a strong preference 
either way were able to stay home. What's more, the election was at an unconventional 
time -- neither during the fall or the spring general election. Turnout was specifically 
driven by a desire to express support or opposition to the Governor. As such, 
it can be seen as an indication of the intensity with which a community was in 
favor of or against the policies of the Governor. \footnote{The recall election 
took place on June $5^{th}$, 2012. Turnout was 57.4\% with 2,516,065 voters 
casting votes for Governor out of a voting age population of 4,378,741. For more 
information see \url{http://gab.wi.gov/sites/default/files/Statewide\%20Percentage\%20Results_6.5.12\%20Recall\%20Election\_PRE\%20SEN21\%20RECOUNT.pdf}}

A final measure was created by the mechanics of Act 10 itself. Act 10 required 
public employee unions to recertify through an election process. Over the next 
two years all public employee unions in Wisconsin recertified. Recertification 
required unions to hold elections and that a majority of all members, not just 
of those who voted, must vote in favor of recertifying for the union to continue 
to operate. The results of these elections -- the margin by which the union 
recertified -- can be seen as a measure of latent union strength. While the 
vast majority of unions recertified, in many cases the elections were close. 

Unfortunately, the present study cannot distinguish between these two mechanism. 
More to the point, the study is limited by the reality that though school boards 
were given this freedom, it came coupled with historical cuts in state aid and 
a freeze on school district revenue limits. In practice this meant that though 
compensation policy may have been freed up, school boards had very little 
flexibility to innovate under such fiscal constraint. In some sense then, this 
leaves the elections post Act 10 as really a referendum on the opinion of voters 
and communities on both the changes to collective bargaining, but also reductions 
in school funding. 


\section{Theory}

The case of Wisconsin school boards can be framed two ways. First, school boards 
can be considered like any other elected office with elections that are responsive 
to the provision of information. Prior chapters have taken this approach. In those 
chapters, for the most part, I considered the school board election as an autonomous 
event without explicitly considering factors in neighboring local governments or 
state level policy directly. This follows somewhat the strategy of \citet{oliver12} 
in investigating local electoral influences. 

This approach, however, is not a complete picture. Special jurisdiction governments 
are indeed constrained by other governments. Legally, their existence is dependent 
upon authority granted by the state government. Fiscally, their existence is 
dependent on their ability to compete for tax revenues with other local governments. 

Another approach, however, is to view school boards as nested within a political 
system. When considering the influence of school boards on policy, it is common 
to consider them as constrained actors within a federal system. However, this 
same constraint is not accounted for when investigating the electoral behavior 
of these units. Within the larger literature on special district governments there 
is some consideration of the constraints of layered governments, but not particularly 
when it comes to electoral behavior. 

% Discussion of federalism, special district governance, and local elections


\begin{table}[h!]
\begin{center}
\begin{small}
\caption{Expected Relationships between Key Independent and Dependent Variables}
\label{act10hypo}
\begin{tabular}{| p{.16\textwidth} | p{.12\textwidth} | p{.12\textwidth} | p{.12\textwidth} |
                p{.12\textwidth} | p{.12\textwidth} | p{.12\textwidth} |} \hline
DV / Variable & treatment & treatment x polarization & 
  treatment x turnout & treatment x WERC & polarization & 
  WERC \\ \hline
Contested Race & + & + & null & + & null & null \\ \hline
Competitiveness & + & + & null & + & + & - \\ \hline
Turnout & + & + & + & + & null & - \\ \hline
Rolloff & - & - & - & - & null & + \\ \hline
\end{tabular}
\end{small}
\end{center}
\end{table}

% 
% Second, this study 
% explores the linkage between state level politics and local electoral participation. 
% Thus, the study represents an attempt to estimate the causal effect of a state 
% level policy shock on voter turnout in local elections by leveraging the unique 
% conditions in Wisconsin from 2010-2012. The present study presents an important 
% oppotunity to test theories of participation and cross-level linkages in a federal 
% system that previously were not available to political scientists.

\section{Literature Review}

\subsection{Exogenous State Level Policy Shocks and Voter Turnout}

There is one specific theory about voter turnout that this data can test is the 
linkage between voter turnout in school board elections and state level policy 
shocks. While there has recently been more attention on the linkage between 
national political trends and state level election returns (CITATION NEEDED), these 
studies have not been extended to the local level. However, the local level provides 
an interesting level of analysis because local elections are much more diverse than 
their state level counterparts in terms of the timing, partisanship of office, and 
structure of the elections. Where it is difficult to disentangle relationships between 
national legislature and state legislature composition from national trends in 
partisanship and strategic redistricting (CITATION NEEDED), the diversity of local 
elections allows more opportunities for exogenous variation to explore the causal 
transmission of voter preferences at the state level being expressed in local 
elections. 

Wisconsin from 2010-2012 provides an ideal test case for the transmission of 
state level political preferences to local non-partisan office. As discussed in 
Chapter \ref{chap:theoryreview} and illustrated in Figure \ref{fig:wiscotimeline} 
the election of Scott Walker to Governor and the subsequent passage of Act 10, the 
2011-13 biennial budget, and the mass protests in Madison, WI, state level politics 
in Wisconsin became suddenly extremely polarized.\footnote{Perhaps the most salient 
issue is the requirement under the law that any wage increase greater than a cost 
of living adjustment pegged to CPI be approved by a district wide referenda - 
effectively placing a firm ceiling on any salary negotiations2011 Wisconsin Act 10: 
https://docs.legis.wisconsin.gov/2011/related/acts/10} In addition to the sudden 
polarization, much of the rhetoric, protest, and contentiousness surrounding 
the Walker administration was focused squarely on education politics and labor 
relations - issues that school boards have great local influence over. In fact, 
Act 10 represented a sweeping expansion of the power of school boards away from 
local teachers' unions. Thus, the composition of the school board mattered more 
than ever after Act 10. Importantly, the passage of Act 10 was completely unforeseen 
by political observers and the public and represent an exogenous shock to the 
state political system. \footnote{This last point is somewhat disputed by some 
political observers and Scott Walker himself, but the consensus has been that 
this was not the case according to the \href{http://www.politifact.com/wisconsin/statements/2011/feb/22/scott-walker/wisconsin-gov-scott-walker-says-he-campaigned-his-/}{Milwaukee Journal Sentinel}.}

This paper leverages the unexpected passage of Act 10 as providing a natural 
experiment of the effect of state level policy shocks on local level electoral 
participation. In fact, in this case, the policy shock and surrounding political 
polarization was directly related to the powers of school boards, a locally 
elected non-partisan office. Even more interestingly, school board elections are 
held off-cycle in Wisconsin in the spring on the $2^{nd}$ Tuesday each April. This 
combination of non-partisan off-cycle elections and a wide and deeply salient policy 
shock provide an ideal test of whether or not state level policy actions can spur 
voters in local elections. Specifically, following \citet{Matsusaka}, the state 
level policy shock should have increased dramatically the information available to 
voters about school boards, school board members, and the impact of Act 10 on their 
community. Thus, turnout should have increased above historical levels. 
If there is no impact on voter turnout in the wake of such a broad expansion of 
school board power over an issue as polarizing as collective bargaining rights 
for local employees, we would expect smaller policy shocks to have no effect either. 
This would represent a rejection of the applicability of information theory to 
explain turnout in low-salience non-partisan elections. This would also provide 
evidence in support of dissatisfaction theory - with heightened stakes for board 
policy preferences.\footnote{One concern might be that the polarization was so 
extreme and the state so saturated with negative campaigning of all forms that 
voter turnout was suppressed even in the case of spring school board elections 
\citep{NegativeCamp1999}.}

\begin{table}[h!]
\begin{center}
\begin{small}
\caption{Theories of Turnout and Expected Evidence: Causal}
\label{turnoutH2}
\begin{tabular}{| p{.15\textwidth} | p{.2\textwidth} | p{.6\textwidth} |}
\hline
\textbf{Theory}  & \textbf{Citation} & \textbf{Expected Finding} \\ \hline
Information theory  & \citet{Matsusaka} & Large turnout increases after passage of Act 10\\ \hline
Dissatisfaction theory & \citet{RefWorks:297,RefWorks:271} & Large turnout increase after Act 10 \\ \hline
\end{tabular}
\end{small}
\end{center}
\end{table}

This follows along the work of \citet{Lassen2005} who leveraged an exogenous shock 
of an information campaign in some electoral districts and found that 
increasing voters' information also produced a sizeable effect on the propensity 
to vote. 

\section{Data}
 A final feature of this data set is that the years of the panel span 
an important and dramatic policy change for education in Wisconsin - the passage of 
Wisconsin Act 10 by Wisconsin Governor Scott Walker. While the political fallout 
over this legislation was nightly news across the nation, the implications of Act 10
were and continue to be particularly salient for school districts, school boards, 
and local policy regarding the governance of education in the state. Combined with 
unprecedented cuts in per-pupil-spending, Act 10 was framed as a set of "tools" 
to give local officials - elected school boards - the flexibility to reduce their 
fixed costs by renegotiating employee compensation and benefits with employees now 
with much weakened labor representation and substantial limits on their bargaining 
authority. \footnote{Perhaps the most salient 
issue is the requirement under the law that any wage increase greater than a cost 
of living adjustment pegged to CPI be approved by a district wide referenda - 
effectively placing a firm ceiling on any salary negotiations2011 Wisconsin Act 10: 
https://docs.legis.wisconsin.gov/2011/related/acts/10}

\subsection{Dependent Variables}

In this section I outline the key dependent variables for this investigation. 
Broadly, I am looking for evidence of the causal impact of state level policy 
shocks on the behavior of both candidates and voters. For candidates, I look 
for a change in the patterns of candidate contestation and seat competitiveness 
after the passage of Act 10 and the granting of additional powers to school boards. 
For voters, I look for changes in voter turnout and decreases in voter rolloff. 

<<minorContestPlot, fig.cap="Polarization and Contestation - Minor Contestation", out.height='3.18in'>>=
plotdf <- dist_turn[dist_turn$year > 2006, ]

qplot(contestMinor, RecallPolarization, data = plotdf, geom = 'boxplot') + 
  facet_wrap(~year) +
  scale_y_continuous() +
  theme_dpi(base_size=10) + coord_flip() + 
  labs(x= "Minor Contestation", y = "Polarization from 2012 Gov. Recall")
@


<<serContestPlot, fig.cap="Polarization and Contestation - Serious Contestation", out.height='3.18in'>>=
qplot(contestSer, RecallPolarization, data = plotdf, geom = 'boxplot') + 
  facet_wrap(~year) +
  scale_y_continuous() +
  theme_dpi(base_size=10) + coord_flip()+ 
  labs(x= "Serious Contestation", y = "Polarization from 2012 Gov. Recall")
@

Figures \ref{fig:minorContestPlot} and \ref{fig:serContestPlot} show the relationship 
between the community polarization in the Gubernatorial recall vote and contestation. 
There appears to be consistently little difference in the distribution of 
polarization between districts with contested and uncontested races across the 
years. 

Figure \ref{fig:blPlot} explores this same relationship but for the continuous 
measure of seat competitiveness -- the Blais-Lago quotient. Here there is a pattern 
of elevated contestation in 2011, and an increase in competitiveness, a lower 
B-L quotient, as seat polarization increases in year 2012. There is a similar 
pattern, though weaker in 2007 and 2010 as well. 

<<blPlot, fig.cap="Polarization and Seat Competitiveness">>=
plotdf <- dist_turn[dist_turn$year > 2006, ]
plotdf <- plotdf[!is.na(plotdf$turnout), ]
plotdf <- plotdf[plotdf$turnout < 0.8, ]
qplot(RecallPolarization, minBlaisLago, data = plotdf) + 
  facet_wrap(~year) + geom_smooth(method = 'lm', aes(group = 1)) +
  scale_y_continuous() +
  theme_dpi()+ 
  labs(y= "Seat Competitiveness", x = "Polarization from 2012 Gov. Recall")
@

Figures \ref{fig:turnoutPlot1} and \ref{fig:turnoutPlot2} show the relationship 
between polarization and school board turnout and voter rolloff. In 2011 and 2012 
there appears to be a negative relationship between increasing polarization and 
decreased turnout. For rolloff, the relationship appears to be the same across 
all the years. 

<<turnoutPlot1, fig.cap="Polarization and School Board Turnout">>=
qplot(RecallPolarization, turnout, data = plotdf, alpha = I(0.6)) + 
  facet_wrap(~year) + geom_smooth(method='lm') +
  scale_y_continuous(label=percent) +
  theme_dpi() + 
  labs(y = "School Board Turnout", x = "Polarization from 2012 Gov. Recall")
@

<<turnoutPlot2, fig.cap="Polarization and Spring Rolloff">>=
qplot(RecallPolarization, turnoutDiff, data = plotdf, alpha = I(0.6)) + 
  geom_smooth(method='lm') + 
   facet_wrap(~year) + 
   scale_y_continuous(label = percent) +
   theme_dpi() + labs(x= "Polarization from 2012 Gov. Recall", "School Board Rolloff")

# qplot(RecallPolarization, turnoutDiff/topTicketTurnoutSpring, data =plotdf) + 
#   geom_smooth(method = "lm") + 
#    facet_wrap(~year) + scale_x_continuous(label = percent) + 
#    scale_y_continuous(label = percent) +
#    theme_dpi()
@

\subsection{Independent Variables}

In addition to the suite of independent variables found in Chapters \ref{chap:candidacy} 
and \ref{chap:turnout}, this chapter features some additional key dependent variables 
drawn from results of Wisconsin's historic recall election. 

Figure \ref{fig:ivPlot1} shows the relationship between recall polarization and 
other variables for the year 2012. THe relationship between fall and recall election 
turnout and polarization is virtually identical. The top right panel shows the 
relationship between recall polarization and the Democratic share of the most 
recent presidential two-party vote - aside from a handful of outliers it follows 
in the expected direction. Finally, spring election turnout is fairly similar to 
the other turnout variables, but at a lower level with about half the turnout 
on average of the other elections. 

<<ivPlot1, fig.cap="Polarization and Other Variables">>=
plotdf <- dist_turn[dist_turn$year == 2012, ]

p1 <- qplot(RecallPolarization, GovTurnout_recall, data = plotdf) + 
  geom_smooth(method = 'lm') + 
   facet_wrap(~year) + 
   scale_y_continuous(label = percent) +
   theme_dpi() + labs(x= "Polarization from 2012 Gov. Recall", y="Recall Turnout")

p2 <- qplot(RecallPolarization, presTwoPartyShareDem, data = plotdf) + 
  geom_smooth(method = 'lm') + 
   facet_wrap(~year) + 
   scale_y_continuous(label = percent) +
   theme_dpi() + labs(x= "Polarization from 2012 Gov. Recall", y="Pres. Two Party Dem Share")

p3 <- qplot(RecallPolarization, recentFallTurnout, data = plotdf) + 
  geom_smooth(method = 'lm') + 
   facet_wrap(~year) + 
   scale_y_continuous(label = percent) +
   theme_dpi() + labs(x= "Polarization from 2012 Gov. Recall", y="Recent Fall Turnout")

p4 <- qplot(RecallPolarization, topTicketTurnoutSpring, data = plotdf) + 
  geom_smooth(method = 'lm') + 
   facet_wrap(~year) + 
   scale_y_continuous(label = percent) +
   theme_dpi() + labs(x= "Polarization from 2012 Gov. Recall",y= "Spring 2012 Turnout")

grid.arrange(p1, p2, p3, p4)
@

Figure \ref{fig:ivPlot2} explores the relationship between recall polarization 
and demographic variables to understand the ways party-polarization in the recall 
is similar to or different than partisan polarization in other elections. In the 
top left there is a strong relationship between the logged median income and 
polarization with higher polarization more strongly associated with lower income. 
Polarization appears to be consistent across the size of the Voting Age Population 
(VAP). There is a slight increase in polarization as the percentage of VAP over 
65 increases. 

<<ivPlot2, fig.cap="Polarization and Population Control Variables">>=
p1 <- qplot(median_incomeLOG, RecallPolarization, data = plotdf) + 
  geom_smooth(method = 'lm') + 
   facet_wrap(~year) + 
   scale_x_continuous(limits = c(9.5, 11.5)) + scale_y_continuous(limits=c(0, 100)) +
   theme_dpi() + labs(y= "Polarization from 2012 Gov. Recall", x= "Median Income (log)")

p2 <- qplot(VAP_adjLOG, RecallPolarization, data = plotdf) + 
  geom_smooth(method = 'lm') + 
   facet_wrap(~year) + 
   scale_x_continuous() +
   theme_dpi() + labs(y= "Polarization from 2012 Gov. Recall", x= "VAP (log)")

p3 <- qplot(PerBachelorOrAbove, RecallPolarization, data = plotdf) + 
  geom_smooth(method = 'lm') + 
   facet_wrap(~year) + 
   scale_x_continuous(label = percent) +
   theme_dpi() + labs(y= "Polarization from 2012 Gov. Recall", x="Per Bach. +")


p4 <- qplot(per65o, RecallPolarization, data = plotdf) + 
  geom_smooth(method = 'lm') + 
   facet_wrap(~year) + 
   scale_x_continuous(label = percent) +
   theme_dpi() + labs(y= "Polarization from 2012 Gov. Recall", x="% VAP 65+")

grid.arrange(p1, p2, p3, p4)
@

\subsubsection{WERC Elections}

This chapter introduces a new data source, the results of union certification 
elections. The Wisconsin Employment Relations Commission (WERC) maintains records of the 
annual recertification of unions. I use WERC records from each year following 
the passage of Act 10. After Act 10, unions in school districts had to recertify 
in waves as their existing union contracts expired. I take WERC election results 
from 2011, 2012, 2013, and 2014. After recertifying the first time, unions must 
hold an annual recertification election. I collapse the recertifcation elections 
for all unions in the district available in all years as a measure of union 
strength over time. I explore two separate measures of union strength -- the 
turnout in all union elections in the district, and turnout in teacher union 
only elections. 

Turnout is a strong proxy for union strength because such vote records are public 
record. % explain this


Figure \ref{fig:ivPlot3} shows the relationship between independent variables and 
the turnout in school district union certification elections after the passage 
of Act 10. Polarization is slightly negatively related with WERC turnout. 
Median income is slightly positively related with WERC turnout. VAP and \% of 
VAP over 65 are not really related to this. 

<<ivPlot3, fig.cap = "Polarization and WERC Elections">>=
p1 <- qplot(RecallPolarization, turnout_overall_werc, data = plotdf) + 
  geom_smooth(method='lm') + 
  facet_wrap(~year) + 
  scale_y_continuous(label = percent) + theme_dpi() + 
  labs(y = "WERC Election Turnout", x = "Polarization from 2012 Gov. Recall")

p2 <- qplot(median_incomeLOG, turnout_overall_werc, data = plotdf) + 
  geom_smooth(method='lm') + 
  facet_wrap(~year) + 
  scale_y_continuous(label = percent) + theme_dpi() + 
  scale_x_continuous(limits = c(9.5, 11.5)) +
  labs(y = "WERC Election Turnout", x = "Median Income Log")

p3 <- qplot(per65o, turnout_overall_werc, data = plotdf) + 
  geom_smooth(method='lm') + 
  facet_wrap(~year) + 
  scale_y_continuous(label = percent) + theme_dpi() + 
  scale_x_continuous(label = percent) +
  labs(y = "WERC Election Turnout", x = "% VAP 65+")

p4 <- qplot(VAP_adjLOG, turnout_overall_werc, data = plotdf) + 
  geom_smooth(method = 'lm') + 
   facet_wrap(~year) + 
   scale_x_continuous() + scale_y_continuous(label = percent) +
   theme_dpi() + labs(y= "WERC Election Turnout", x= "VAP (log)")

grid.arrange(p1, p2, p3, p4)
@


\clearpage

\section{Methods}

\subsection{Causal Inference Using Natural Experiments}

The approach here is to leverage the passage of Act 10 as an exogenous shock which 
allows us to reasonably assume that differences between the period prior to the shock 
and after the shock are causally attributable to the shock itself. 

% Citations: Shadish and Cook

\subsection{Candidacy}

Combining this information with returns from the late spring recall election of 
the Governor--certain to be a statewide referendum on the Governor's education policies--it is 
possible using data from all 424 school districts in the state to directly to test 
whether divided communities see greater participation by challenger candidates than 
unified communities. This would represent the first comprehensive test of the public 
choice theory of school board elections and represent the first test of Dissatisfaction 
Theory across an entire state using actual election results instead of self-reports 
of school board members and superintendents \citep{RefWorks:243,RefWorks:297}. The 
empirical model of candidate emergence (CE) would look something like: \\

\[ (2) \hspace{0.25 in}  CE_{t} = \alpha + \beta X_{t-1} + \gamma Z_{t} + \epsilon \] \\

Where $CE_{t}$ represents a measure of the number of candidates greater than one per seat, 
$\alpha$ is an intercept, $X_{t-1}$ is a vector of lagged covariates such as prior 
levels of contestation and district size, and $Z_{t}$ is the absolute value of the 
deviation from 50\% of the vote share for the Governor in a recall election aggregated 
to the school district from ward level returns.\footnote{Depending on the data and 
the prevalence of incumbent retirements candidate emergence may need to be measured a 
number of additional ways. \citet{RefWorks:337} discuss a number of possibilities for 
turnover that could be adapted to candidate emergence including: Seats available 
divided by incumbents + challengers minus retired candidates; seats available divided 
by all candidates; or seats available divided by challengers.} Thus, when $Z_{t} = 0$ 
the community is completely divided on the Governor. When $Z_{t}=.5$ the community is 
either united for or against the Governor. Thus, all things equal, we would expect 
$\gamma$ to have a negative value--as $Z_{t}$ increases, the number of challengers, 
$Y_{t}$ should decrease because the community is fairly homogeneous and the school 
board should reflect existing preferences for or against the Governor's reforms. 

\subsection{Turnout}

\subsection{The Impact of Salience and Information on Voter Turnout}

While the equations above can prove useful for providing evidence of various theories 
of voter turnout in non-partisan local elections, they cannot test some theories and 
they do not shed any light on causes of voter turnout. Table \ref{turnoutH2} demonstrates 
how two such models can be explicitly tested by leveraging the exogenous shock of 
the passage of Act 10. To estimate these effects, we estimate an equation like below: \\

\[(6) \hspace{0.4 in} VP_{t} = \alpha + \beta X_{lag} + \gamma W_{t} + \lambda P_{lag} +
      \tau 1- |W_{t} * P_{lag}| + \theta I_{lag} + \psi Ce_{t}+\epsilon \] \\

Here $VP_{t}$ is voter turnout in either the 2011 or 2012 Spring Elections by school 
district in Wisconsin. $\alpha$, $X_{lag}$ remain the same as above though now 
including some measure of prior turnout in the district such as turnout in the 
Gubernatorial election in 2010.  $Z_{t}$ is the absolute value of the deviation 
from 50\% of the vote share for the Governor. $I_{lag}$ representing an indicator 
of the strength of teachers' unions in the district--likely the most salient and 
relevant interest group in the spring elections \citep{RefWorks:320, RefWorks:207, RefWorks:218}.
Voters are unlikely to participate if presented with no choice, so $Ce_{t}$ represents 
a measure of the number of candidates per seat. $W_{t}$ represents the vote share 
for Governor Walker in the recall election--a measure of community support or opposition 
to the Governor's education policy. Thus it would be expected that $\theta$ should 
be positive--strong interest groups should drive political activity. The inclusion 
of partisanship predictors of voter turnout could also be explored here. The 
effects of $\gamma$  and $\lambda$ alone are uninteresting, but the interaction 
of $W_{t} * P_{lag}$ is of great interest. This essentially represents a measure 
of board policy alignment with voter preferences--taking the absolute value simplifies 
interpretation. As such, it should be expected that for large values of $W_{t} * P_{lag}$, 
voter participation would be small as the board policy and the community 
preferences would be aligned. As $W_{t} * P_{lag}$ approaches zero, voter 
participation will increase as predicted by \citep{RefWorks:243}--voters seeing 
dissonance between their preferences and board policy are more likely to vote. 
Thus $\tau$ should be negative.  %Add detail here


\clearpage
\section{Results}

<<walkerDataPrep1, results='asis', echo = FALSE>>=
moddat <- dist_turn[, c("contestSer", "contestMinor", "distid","year", 
                        "balance_member_lag", "turnout", "VAP_adjLOG_sq",
                        "PerBachelorOrAbove", "VAP_adjLOG", "per_white_all", 
                        "districtwide", "turnoutLag1", "topTicketTurnoutSpring",
                        "OOH_share", "median_incomeLOG", "per65o", 
                        "NonWhitePublicPupilPer", "NonPublicPupilPer", 
                         "locale2", "incumShare", "contestMinorLag", 
                        "contestSerLag", "incDefeats", "nonincumbRun", 
                        "onlyIncum",
                        "overrideYesPer", "partyDivisionRecent", "turnoutLag2",
                        "teachShareofVoters", "fallTurnout", 
                        "nraces", "schoolMillShare", "PROPERTYTAX_REV_SHARE", 
                        "TCEC_MEMBER", "millrate_delta", 
                        "ADMIN_SHARE_COMP", "NEW_SUP", 
                        "DEBT_ATTEMPT_CUMUL93", "OVERRIDE_ATTEMPT_CUMUL93", 
                        "member_delta_per", "GovTwoPartyShareDem_recall",
                        "GovTwoPartyShareRep_recall", "RecallPolarization",
                        "turnout_overall_werc", "minBlaisLago",
                        "eligvoters_werc", "fallTwoPartyShareDem",
                        "loss_werc", "worst_margin_werc", "WERC_elec", 
                        "GovTurnout_recall")]
# contestSerLag
moddat <- na.omit(moddat)
moddat <- moddat[moddat$year >= 2006,]
moddat <- moddat[order(moddat$distid, moddat$year),]
moddat$treatment <- ifelse(moddat$year > 2010, 1, 0)
moddat$treatment <- factor(moddat$treatment)
moddat$distid <- factor(moddat$distid)
moddat$year <- factor(moddat$year)
moddat <- moddat[order(moddat$distid, moddat$year),]
moddat$turnoutLag1 <- moddat$turnoutLag1 * 100
moddat$districtwide <- factor(moddat$districtwide)
moddat$per_white_all <- moddat$per_white_all * 100
moddat$per65o <- moddat$per65o * 100
moddat$PerBachelorOrAbove <- moddat$PerBachelorOrAbove * 100
moddat$OOH_share <- moddat$OOH_share * 100
# moddat$fallTurnout <- moddat$fallTurnout * 100
moddat$turnout_overall_werc <- moddat$turnout_overall_werc * 100
moddat$topTicketTurnoutSpring <- moddat$topTicketTurnoutSpring * 100
moddat$turnout <- moddat$turnout * 100
moddat$GovTurnout_recall <- moddat$GovTurnout_recall * 100
moddat$GovTwoPartyShareDem_recall <- moddat$GovTwoPartyShareDem_recall *100
moddat$member_delta_per <- moddat$member_delta_per * 100
moddat$WERC_elec <- factor(moddat$WERC_elec)
moddat$contestSer <- factor(moddat$contestSer)
moddat$contestMinor <- factor(moddat$contestMinor)
moddat$contestSerLag <- factor(moddat$contestSerLag)
moddat$contestMinorLag <- factor(moddat$contestMinorLag)
moddat$incDefeats <- factor(moddat$incDefeats)
moddat$districtwide <- factor(moddat$districtwide)
library(arm)
nums <- sapply(moddat, is.numeric)
#   for(i in unique(moddat$year)){
#     moddat[moddat$year == i, nums] <- 
#       apply(moddat[moddat$year == i, nums], 2, rescale)
#   }
moddat[, nums] <- apply(moddat[, nums], 2, rescale)
@

\subsection{Contestation}

To test the effect of the passage of Act 10 on participation in school board elections, 
we fit a simple longitudinal model of school districts. In this model, school district 
elections are treated as repeated measures, nested within the school districts 
themselves. Using this repeated measures framework allows us to estimate cross 
district and within district effects. Act 10 represented a statewide intervention 
in the relative power of school boards in Wisconsin by giving school boards much 
more authority and control over the compensation of teachers and staff, and by 
dramatically restricting the ability of the districts' employees to bargain over 
wages, working conditions, and benefits. This shift in power, in essence, raised 
the stakes for school board elections substantially and should have increased the 
overall contestation of school board elections. 

To evaluate this, a series of models of school board election contestation over 
time are fit to attempt to detect changes in contestation levels relative to the 
levels of contestation observed in school districts prior to the passage of 
Act 10. If levels of contestation increase after the introduction of Act 10, even 
after controlling for the factors that influenced this above, it would be strong 
evidence that the statewide policy lever pulled by Act 10 did spur a response 
from candidates in terms of increasing the attractiveness of school board seats. 

As in Chapter \ref{chap:candidacy}, I use three separate measures of contestation. 
First, I use the presence of any challenger either appearing on the ballot or receiving 
more than 10 votes as a write-in candidate. I code these races as ``minorly contested'' 
because they have a nominal level of contestation at a minimum. Next, I use a higher 
threshold where only races with challengers who receive 20 or more votes are 
considered as ``seriously contested`. Finally, I use a measure of race competitiveness, 
the Blais-Lago quotient. 


<<walkerGLM, results='hide'>>=
glmContestSer1 <- glm(contestSer ~ turnoutLag2 + VAP_adjLOG + VAP_adjLOG_sq + 
                 per_white_all + 
               per65o + PerBachelorOrAbove + OOH_share + median_incomeLOG +
               districtwide + 
                 RecallPolarization*treatment + treatment*GovTurnout_recall,
              data = moddat, family = 'binomial')

glmContestSer1SE <- get_CL_vcov(glmContestSer1, moddat$distid)
glmContestSer1$se <- sqrt(diag(glmContestSer1SE))

glmContestSer2 <- glm(contestSer ~ turnoutLag2 + VAP_adjLOG + VAP_adjLOG_sq + 
                  per_white_all + per65o + PerBachelorOrAbove +  
                    median_incomeLOG +
               districtwide + 
                 RecallPolarization*treatment + treatment*GovTurnout_recall,
              data = moddat, family = 'binomial')

glmContestSer2SE <- get_CL_vcov(glmContestSer2, moddat$distid)
glmContestSer2$se <- sqrt(diag(glmContestSer2SE))

glmContestSer3 <- glm(contestSer ~ turnoutLag2 + VAP_adjLOG + VAP_adjLOG_sq + 
                  per_white_all + 
               per65o + PerBachelorOrAbove + OOH_share + median_incomeLOG +
               districtwide + 
                 RecallPolarization*treatment + treatment*GovTurnout_recall + distid, 
              data = moddat, family = 'binomial')

glmContestSer3SE <- get_CL_vcov(glmContestSer3, moddat$distid)
glmContestSer3$se <- sqrt(diag(glmContestSer3SE))

seriousGLMtable <- apsrtable(glmContestSer1, glmContestSer2, glmContestSer3, 
          se = "robust", label="tab:serMod", 
          model.names=c("Naive Causal Model", "Overvote Model"), 
          caption = "Model of Causal Impact of Act 10 on School Board Candidacy",
          omitcoef=list("year", 
                        expression(grep("year", coefnames, value = TRUE)), 
                        "distid", expression(grep("distid", coefnames, 
                                                  value = TRUE))), 
          Sweave=TRUE)
@
<<walkerGLM2, results='hide'>>=
glmContestMinor1 <- glm(contestMinor ~ turnoutLag2 + VAP_adjLOG + VAP_adjLOG_sq + 
                 per_white_all + 
               per65o + PerBachelorOrAbove + OOH_share + median_incomeLOG +
               districtwide + 
                 RecallPolarization*treatment + treatment*GovTurnout_recall, 
              data = moddat, family = 'binomial')

glmContestMinor1SE <- get_CL_vcov(glmContestMinor1, moddat$distid)
glmContestMinor1$se <- sqrt(diag(glmContestMinor1SE))

glmContestMinor2 <- glm(contestMinor ~ turnoutLag2 + VAP_adjLOG + VAP_adjLOG_sq + 
                  per_white_all + per65o + PerBachelorOrAbove +  
                    median_incomeLOG + districtwide + 
                 RecallPolarization*treatment + treatment*GovTurnout_recall, 
              data = moddat, family = 'binomial')

glmContestMinor2SE <- get_CL_vcov(glmContestMinor2, moddat$distid)
glmContestMinor2$se <- sqrt(diag(glmContestMinor2SE))

glmContestMinor3 <- glm(contestMinor ~ turnoutLag2 + VAP_adjLOG + VAP_adjLOG_sq + 
                  per_white_all + 
                  per65o + PerBachelorOrAbove + OOH_share + median_incomeLOG +
               districtwide + 
                 RecallPolarization*treatment + treatment*GovTurnout_recall + 
                 distid, 
              data = moddat, family = 'binomial')

glmContestMinor3SE <- get_CL_vcov(glmContestMinor3, moddat$distid)
glmContestMinor3$se <- sqrt(diag(glmContestMinor3SE))

minorGLMtable <- apsrtable(glmContestMinor1, glmContestMinor2, glmContestMinor3, 
          se = "robust", label="tab:minMod", 
            caption = "Model of Causal Impact of Act 10 on School Board Candidacy",
          omitcoef=list("year", 
                        expression(grep("year", coefnames, value = TRUE)), 
                        "distid", expression(grep("distid", coefnames, 
                                                  value = TRUE))), 
          Sweave=TRUE)
@

\begin{tiny}
<<walkerMixedMod, results='asis'>>=
library(optimx)
ctrl2 <- glmerControl(optimizer = "optimx", calc.derivs = FALSE, 
                     optCtrl = list(method = "nlminb", starttests = FALSE, 
                                    kkt = FALSE, maxit = 10000))
ctrl <- glmerControl(optimizer = "Nelder_Mead", calc.derivs = FALSE)
moddat2 <- moddat[moddat$incumShare != max(moddat$incumShare) & 
                    !is.na(moddat$contestSerLag), ]

mod1MMserBIN <- glmer(contestSer ~ VAP_adjLOG + VAP_adjLOG_sq + 
                      per65o + PerBachelorOrAbove + 
                      per_white_all + OOH_share + locale2 + PROPERTYTAX_REV_SHARE + 
                        incumShare + nraces + 
                       RecallPolarization*treatment +
                       (1|distid), data = moddat2, family = "binomial", 
                      control = ctrl2) 

mod2MMserBIN <-  glmer(contestSer ~ VAP_adjLOG + VAP_adjLOG_sq + 
                      per65o + PerBachelorOrAbove + 
                      per_white_all + OOH_share + locale2 + PROPERTYTAX_REV_SHARE + 
                        incumShare + nraces + treatment*GovTurnout_recall + 
                        (1|distid), data = moddat2, family = "binomial", 
                      control = ctrl2)

mod3MMserBIN <- update(mod2MMserBIN, . ~ . +  RecallPolarization*treatment)

mod4MMserBIN <-  glmer(contestSer ~ VAP_adjLOG + VAP_adjLOG_sq + 
                      per65o + PerBachelorOrAbove + 
                      per_white_all + OOH_share + locale2 + PROPERTYTAX_REV_SHARE + 
                        incumShare + nraces + 
                       turnout_overall_werc*treatment + WERC_elec + 
                       (1|distid), data = moddat2, family = "binomial", 
                      control = ctrl2)
# coefnamesLag3 <- c("Intercept","Lagged Turnout (2)", "ln(VAP)", 
#                  "\\% White", 
#                   "\\% Over 65", "\\% Bach. +", "\\% OOH", 
#                   "ln(MedianIncome)", "District-wide", "Blais-Lago", 
#                   "Fall Turnout",  "$ln(VAP)^{2}$")

apsrtable(mod1MMserBIN, mod2MMserBIN, mod3MMserBIN, mod4MMserBIN, 
          caption = "Partial Pooling Model of Serious Contestation",
          model.names = c("Polarization", "Turnout", "Both", "WERC"), 
            label = "tab:meSer",  
           notes = list("All variables scaled and mean centered by year.", 
                       stars.note), 
          Sweave = TRUE, digits = 3, float = "longtable") #, coef.names = coefnamesLag3)
@
\end{tiny}

The results in Table \ref{tab:meSer} does not show much promise, like in Chapter 
\ref{chap:candidacy}. The models do not fit well, and though the effects of 
polarization and the post-recall effect are in the direction hypothesized, they 
are not statistically significant. There is evidence that polarization leads to 
greater contestation, and post-recall recall turnout is more strongly associated 
with increased contestation. One prediction that is in the wrong direction is that 
the effect of polarization decreases post-recall. Few other predictors are statistically 
significant and there is not much to conclude about a change in contested seats 
post recall, as shown above in Figure \ref{fig:serContestPlot}. 

% Serious contestation like in Chapter 3 does not show promise
% polarization is associated with greater contestation 
% Post-recall has greater contestation
% recall turnout ^ is associated with a decrease in serious contestation
% effect is magnified post recall
% none of these effects are statistically significant
% Models appear to fit poorly
% TODO: Consider refitting to demographics only + groups of interactions

<<walkerMixedModhide, eval=FALSE, results='hide'>>=

# politicMMserBIN <- update(demogsMMserBIN, . ~ . + incumShare +  contestSerLag + 
#                             overrideYesPer +  partyDivisionRecent + 
#                             teachShareofVoters + fallTurnout + nraces) 
# 
# policyMMserBIN <- update(demogsMMserBIN, . ~ . + ADMIN_SHARE_COMP + NEW_SUP + 
#                         NonPublicPupilPer + 
#                    DEBT_ATTEMPT_CUMUL93 + OVERRIDE_ATTEMPT_CUMUL93)
# 
# fullmodMMserBIN <- update(politicMMserBIN, . ~ . +  schoolMillShare + 
#                          PROPERTYTAX_REV_SHARE + TCEC_MEMBER + 
#                          balance_member_lag + millrate_delta + 
#                     ADMIN_SHARE_COMP + NEW_SUP + NonPublicPupilPer + 
#                    DEBT_ATTEMPT_CUMUL93 + OVERRIDE_ATTEMPT_CUMUL93)
# demogsMMminBIN <- glmer(contestMinor ~ VAP_adjLOG + VAP_adjLOG_sq + 
#                       per65o + PerBachelorOrAbove + 
#                       per_white_all + OOH_share + locale2 +  
#                        RecallPolarization*treatment + treatment*GovTurnout_recall + 
#                        (1|distid), data = moddat2, family = "binomial", 
#                       control = ctrl2) 

# politicMMminBIN <- update(demogsMMminBIN, . ~ . + incumShare +  overrideYesPer +  
#                        partyDivisionRecent + contestMinorLag + 
#                     teachShareofVoters + fallTurnout + nraces) 
# 
# policyMMminBIN <- update(demogsMMminBIN, . ~ . + ADMIN_SHARE_COMP + NEW_SUP + 
#                         NonPublicPupilPer + 
#                    DEBT_ATTEMPT_CUMUL93 + OVERRIDE_ATTEMPT_CUMUL93)
# 
# fullmodMMminBIN <- update(politicMMminBIN, . ~ . +  schoolMillShare + 
#                          PROPERTYTAX_REV_SHARE + TCEC_MEMBER + 
#                          balance_member_lag + millrate_delta + 
#                     ADMIN_SHARE_COMP + NEW_SUP + NonPublicPupilPer + 
#                    DEBT_ATTEMPT_CUMUL93 + OVERRIDE_ATTEMPT_CUMUL93)


@

\begin{tiny}
<<walkerMixedMod2, results='asis'>>=
mod1MMminBIN <- glmer(contestMinor ~ VAP_adjLOG + VAP_adjLOG_sq + 
                      per65o + PerBachelorOrAbove + 
                      per_white_all + OOH_share + locale2 + PROPERTYTAX_REV_SHARE + 
                        incumShare + nraces + 
                       RecallPolarization*treatment +
                       (1|distid), data = moddat2, family = "binomial", 
                      control = ctrl2) 

mod2MMminBIN <-  glmer(contestMinor ~ VAP_adjLOG + VAP_adjLOG_sq + 
                      per65o + PerBachelorOrAbove + 
                      per_white_all + OOH_share + locale2 + PROPERTYTAX_REV_SHARE + 
                        incumShare + nraces + treatment*GovTurnout_recall + 
                        (1|distid), data = moddat2, family = "binomial", 
                      control = ctrl2)

mod3MMminBIN <- update(mod2MMminBIN, . ~ . +  RecallPolarization*treatment)

mod4MMminBIN <-  glmer(contestMinor ~ VAP_adjLOG + VAP_adjLOG_sq + 
                      per65o + PerBachelorOrAbove + 
                      per_white_all + OOH_share + locale2 + PROPERTYTAX_REV_SHARE + 
                        incumShare + nraces + 
                       turnout_overall_werc*treatment + WERC_elec + 
                       (1|distid), data = moddat2, family = "binomial", 
                      control = ctrl2)
# coefnamesLag3 <- c("Intercept","Lagged Turnout (2)", "ln(VAP)", 
#                  "\\% White", 
#                   "\\% Over 65", "\\% Bach. +", "\\% OOH", 
#                   "ln(MedianIncome)", "District-wide", "Blais-Lago", 
#                   "Fall Turnout",  "$ln(VAP)^{2}$")

apsrtable(mod1MMminBIN, mod2MMminBIN, mod3MMminBIN, mod4MMminBIN,
          caption = "Partial Pooling Model of Any Contestation",
          model.names = c("Polarization", "Turnout", "Both", "WERC"),
            label = "tab:meMin",  
           notes = list("All variables scaled and mean centered by year.", 
                       stars.note), 
          Sweave = TRUE, digits = 3, float = "longtable") #, coef.names = coefnamesLag3)
@
\end{tiny}

In Table \ref{tab:meMin} the results are largely the same, suggesting nominal 
contestation is no easier to predict. Here, polarization is related to slightly 
decreasing contestation, but contestation is predicted to increase after the recall. 
Post-recall, polarization has a stronger effect, as projected. Recall turnout 
is related to reducted contestation, but this relationship changes post-recall. 
However, none of these effects are statistically significant. 

% Sign on recall polarization flips from seriousness
% Recall polarization ^ associated with less contestation nominally
% polarization is associated with greater contestation 
% Post-recall has greater contestation
% recall turnout ^ is associated with a decrease in serious contestation
% effect is magnified post recall
% none of these effects are statistically significant
% Models appear to fit poorly
% TODO: Consider refitting to demographics only + groups of interactions

The models in Tables \ref{tab:meMin} and \ref{tab:meSer} are disappointing, but 
this is in part due to the small sample size involved and the fact that few 
variables at all have been shown to be predictive of this measure of contestation. 
It is unsurprising that an effect on contestation was detectable in the small 
sample here. I now turn to models that have more promise. 

\subsection{Incumbent Defeat}

As in Chapter \ref{chap:candidacy} I fit incumbent defeat models on a subset of 
elections for which an incumbent is facing the possibility of defeat -- that is 
where there are more candidates than incumbents in the race. These models are the only 
models that show some promise. However, as was the case in Chapter \ref{chap:candidacy}, 
the sample size decreases as I restrict the data to cases where incumbents are 
running, but also a challenger is present as well. This reduced sample size 
is problematic for fitting a random-effect model as the number of group terms 
is approaching the number of observations. 

<<glmincDefeatmods, eval=TRUE, results='hide'>>=
moddat3 <- moddat[moddat$incumShare != max(moddat$incumShare) &
                              moddat$incumShare != min(moddat$incumShare) & 
                    !is.na(moddat$contestSerLag),]

glmIncDef1 <- glm(incDefeats ~ turnoutLag2 + VAP_adjLOG + VAP_adjLOG_sq + 
                 per_white_all + 
               per65o + PerBachelorOrAbove + OOH_share + median_incomeLOG +
               districtwide + 
                 RecallPolarization*treatment + treatment*GovTurnout_recall,
              data = moddat3, family = 'binomial')

glmIncDef1SE <- get_CL_vcov(glmIncDef1, moddat3$distid)
glmIncDef1$se <- sqrt(diag(glmIncDef1SE))

glmIncDef2 <- glm(incDefeats ~ turnoutLag2 + VAP_adjLOG + VAP_adjLOG_sq + 
                  per_white_all + per65o + PerBachelorOrAbove +  
                    median_incomeLOG +
               districtwide + 
                 RecallPolarization*treatment + treatment*GovTurnout_recall,
              data = moddat3, family = 'binomial')

glmIncDef2SE <- get_CL_vcov(glmIncDef2, moddat3$distid)
glmIncDef2$se <- sqrt(diag(glmIncDef2SE))

moddat3$distid <- factor(as.character(moddat3$distid))
glmIncDef3 <- glm(incDefeats ~ contestSerLag + VAP_adjLOG + VAP_adjLOG_sq + 
                  per_white_all + 
               per65o + PerBachelorOrAbove + OOH_share + median_incomeLOG +
               districtwide + RecallPolarization*treatment + 
                 treatment*GovTurnout_recall, 
              data = moddat3, family = 'binomial', 
              control = glm.control(maxit = 4000))

glmIncDef3SE <- get_CL_vcov(glmIncDef3, moddat3$distid)
glmIncDef3$se <- sqrt(diag(glmIncDef3SE))

incDefGLMtable <- apsrtable(glmIncDef1, glmIncDef2, glmIncDef3, 
          se = "robust", label="tab:incDefMod", 
          model.names=c("Naive Causal Model", "Overvote Model"), 
          caption = "Model of Causal Impact of Act 10 on Incumbent Defeat",
          omitcoef=list("year", 
                        expression(grep("year", coefnames, value = TRUE)), 
                        "distid", expression(grep("distid", coefnames, 
                                                  value = TRUE))), 
          Sweave=TRUE)

glmIncDefpolitic <- glm(incDefeats ~ contestSerLag + VAP_adjLOG + VAP_adjLOG_sq + 
                  per_white_all + 
               per65o + PerBachelorOrAbove + OOH_share + median_incomeLOG +
                incumShare + overrideYesPer +  partyDivisionRecent +
                    teachShareofVoters + fallTurnout + nraces +
               districtwide + RecallPolarization*treatment + WERC_elec + 
                 treatment*GovTurnout_recall, 
              data = moddat3, family = 'binomial', 
              control = glm.control(maxit = 4000))

glmIncDefpoliticSE <- get_CL_vcov(glmIncDefpolitic, moddat3$distid)
glmIncDefpolitic$se <- sqrt(diag(glmIncDefpoliticSE))

glmIncDeffisc <- glm(incDefeats ~ contestSerLag + VAP_adjLOG + VAP_adjLOG_sq + 
                  per_white_all + 
               per65o + PerBachelorOrAbove + OOH_share + median_incomeLOG +
               schoolMillShare + PROPERTYTAX_REV_SHARE + 
                TCEC_MEMBER + balance_member_lag + millrate_delta +
               districtwide + RecallPolarization*treatment + 
                 treatment*GovTurnout_recall, 
              data = moddat3, family = 'binomial', 
            control = glm.control(maxit = 4000))

glmIncDeffiscSE <- get_CL_vcov(glmIncDeffisc, moddat3$distid)
glmIncDeffisc$se <- sqrt(diag(glmIncDeffiscSE))

glmIncDefPoly <- glm(incDefeats ~ contestSerLag + VAP_adjLOG + VAP_adjLOG_sq + 
                  per_white_all + 
               per65o + PerBachelorOrAbove + OOH_share + median_incomeLOG + 
                 ADMIN_SHARE_COMP + NEW_SUP + NonPublicPupilPer + 
                   DEBT_ATTEMPT_CUMUL93 + OVERRIDE_ATTEMPT_CUMUL93 + 
               districtwide + RecallPolarization*treatment + 
                 treatment*GovTurnout_recall, 
              data = moddat3, family = 'binomial', 
            control = glm.control(maxit = 4000))

glmIncDefPolySE <- get_CL_vcov(glmIncDefPoly, moddat3$distid)
glmIncDefPoly$se <- sqrt(diag(glmIncDefPolySE))

rescalenote <- "All continuous variables rescaled to center 0 
                and divided by 2 standard deviations."
stars.note <- apsrtable:::stars.note

# coefnames3 <- c("Intercept", "VAP", "\\% Over 65", "\\% Bachelor +", 
#                "\\% White", "\\% OOH", "Exurb", "Rural", "Lagged Contestation", 
#                "\\% Incumbents", "\\% Yes Rev. Limit", 
#                "\\% Polarized", "\\% Teach. Voters", "Fall Turnout", "Number Seats", 
#                "\\% Millrate for Schl.", "\\% Revenue Prop. Tax", "Cost per Pupil", 
#                "Balance per Pupil", "Millrate $\\Delta$", "\\% Salary - Admin.", 
#                "New Superintendent", "\\% Private School", "Cumul. Bond Att.", 
#                "Cumul. Override Att.")

incDefGLMtable2 <- apsrtable(glmIncDeffisc, glmIncDefpolitic, glmIncDefPoly, 
                     se = "robust", float = "longtable", label="tab:glmModsD", 
                     model.names=c("Fiscal", "Politic", "Policy"), 
          caption = "Logit Models of Incumbent Defeat in School Board Elections",
          notes = list(stars.note, rescalenote),
          Sweave=FALSE, digits = 3)#, coef.names = coefnames3)
@

\begin{tiny}
<<defeatMerMod, results='asis'>>=
IncDef1mm <- glmer(incDefeats ~ turnoutLag2 + VAP_adjLOG + VAP_adjLOG_sq + 
                 per_white_all + per65o + PerBachelorOrAbove + OOH_share + 
                   median_incomeLOG + districtwide + RecallPolarization*treatment +
                   (1|distid),
              data = moddat3, family = 'binomial', control = ctrl2)

library(blme)
IncDef1mm <-bglmer(incDefeats ~ turnoutLag2 + VAP_adjLOG + VAP_adjLOG_sq + 
                 per_white_all + per65o + PerBachelorOrAbove + OOH_share + 
                   median_incomeLOG + districtwide + 
                   treatment*RecallPolarization + 
                 (1|distid),
              data = moddat3, family = 'binomial', control = ctrl2)

IncDef2mm <- glmer(incDefeats ~ turnoutLag2 + VAP_adjLOG + VAP_adjLOG_sq + 
                 per_white_all + per65o + PerBachelorOrAbove + OOH_share + 
                   median_incomeLOG + districtwide + 
                   treatment*GovTurnout_recall + 
                 (1|distid),
              data = moddat3, family = 'binomial')

IncDef3mm <- glmer(incDefeats ~ turnoutLag2 + VAP_adjLOG + VAP_adjLOG_sq + 
                 per_white_all + per65o + PerBachelorOrAbove + OOH_share + 
                   median_incomeLOG + districtwide + 
                   treatment*GovTurnout_recall + RecallPolarization*treatment +
                 (1|distid), 
              data = moddat3, family = 'binomial', 
              control = ctrl2)


IncDef3mm <- bglmer(incDefeats ~ turnoutLag2 + VAP_adjLOG + VAP_adjLOG_sq + 
                 per_white_all + per65o + PerBachelorOrAbove + OOH_share + 
                   median_incomeLOG + districtwide + 
                   treatment*GovTurnout_recall + RecallPolarization*treatment +
                 (1|distid), 
              data = moddat3, family = 'binomial', 
              control = ctrl2)

IncDef4mm <- bglmer(incDefeats ~ turnoutLag2 + VAP_adjLOG + VAP_adjLOG_sq + 
                  per_white_all + 
               per65o + PerBachelorOrAbove + OOH_share + median_incomeLOG +
               districtwide + turnout_overall_werc*treatment + WERC_elec + 
                 RecallPolarization +
                 GovTurnout_recall + (1|distid), 
              data = moddat3, family = 'binomial', 
              control = ctrl2)

class(IncDef3mm) <- "merMod"
class(IncDef1mm) <- "merMod"
class(IncDef4mm) <- "merMod"

apsrtable(IncDef1mm, IncDef2mm, IncDef3mm, IncDef4mm,
          caption = "Partial Pooling Model of Incumbent Defeat",
          model.names = c("Polar.", "Turnout", "Both", "WERC"), 
            label = "tab:meIncDef",  
           notes = list("All variables scaled and mean centered by year.", 
                       stars.note), 
          Sweave = TRUE, digits = 3)
@
\end{tiny}

The results in table \ref{tab:meIncDef} show a consistent negative effect of 
post-recall years on incumbent defeat, but this effect is not statistically 
significant. This is counter to expectations, but is perhaps offset by the 
specific effects of the recall results. Recall polarization is associated with 
greater incumbent defeat post-recall and recall turnout is as well -- but these 
effects are also not statistically significant. Turnout in union certification 
elections is positively related with incumbent defeat post-recall -- exactly as 
expected. This effect is statistically significnt, providing some evidence that 
union activity post-recall was active in both organizing union members and participating 
in school board elections. This effect can be attributed to a state-level policy 
decision, which has a clear impact on the behavior and results of local officials. 

% Note models built on a smaller subset
% Problems with convergence
% incumbent defeat seems to go down post recall
% Recall polarization negatively related to incumbent defeat
% incumbent defeat increases with polarization post election
% recall turnout negatively related to incumbent defeat
% recall turnout post recall positively related with incumbent defeat

\subsection{Competitiveness}

Looking at incumbent defeat as a binary measure of competitiveness downplays 
the significance of challenges that result in a narrow defeat by a challenger 
to an incumbent -- which would be coded as a 0 in Table \ref{meIncDef}. Using 
a consistent measure of competitiveness, 

<<blqLM, eval=TRUE, results='hide'>>=
moddat4 <- moddat[moddat$minBlaisLago < max(moddat$minBlaisLago), ]

demogsLMblq <- lm(minBlaisLago ~ VAP_adjLOG + VAP_adjLOG_sq + 
                      per65o + PerBachelorOrAbove + 
                      per_white_all + OOH_share + locale2 +  
                       RecallPolarization*treatment + treatment*GovTurnout_recall, 
                    data = moddat) 
demogsLMblqSE <- get_CL_vcov(demogsLMblq, moddat$distid)
demogsLMblq$se <- sqrt(diag(demogsLMblqSE))

politicLMblq <- update(demogsLMblq, . ~ . + incumShare +  overrideYesPer +  
                       partyDivisionRecent +
                    teachShareofVoters + fallTurnout + nraces) 
politicLMblqSE <- get_CL_vcov(politicLMblq, moddat$distid)
politicLMblq$se <- sqrt(diag(politicLMblqSE))

policyLMblq <- update(demogsLMblq, . ~ . + ADMIN_SHARE_COMP + NEW_SUP + 
                        NonPublicPupilPer + 
                   DEBT_ATTEMPT_CUMUL93 + OVERRIDE_ATTEMPT_CUMUL93)
policyLMblqSE <- get_CL_vcov(policyLMblq, moddat$distid)
policyLMblq$se <- sqrt(diag(policyLMblqSE))
fullmodLMblq <- update(politicLMblq, . ~ . +  schoolMillShare + 
                         PROPERTYTAX_REV_SHARE + TCEC_MEMBER + 
                         balance_member_lag + millrate_delta + 
                    ADMIN_SHARE_COMP + NEW_SUP + NonPublicPupilPer + 
                   DEBT_ATTEMPT_CUMUL93 + OVERRIDE_ATTEMPT_CUMUL93)
fullmodLMblqSE <- get_CL_vcov(fullmodLMblq, moddat$distid)
fullmodLMblq$se <- sqrt(diag(fullmodLMblqSE))

# coefnamesLag3 <- c("Intercept","Lagged Turnout (2)", "ln(VAP)", 
#                  "\\% White", 
#                   "\\% Over 65", "\\% Bach. +", "\\% OOH", 
#                   "ln(MedianIncome)", "District-wide", "Blais-Lago", 
#                   "Fall Turnout",  "$ln(VAP)^{2}$")

lmBLQtable <- apsrtable(demogsLMblq, politicLMblq, policyLMblq, fullmodLMblq, 
                        se="robust",
          caption = "Linear Models of Competitiveness",
          model.names = c("Demog.", "Politic", "Policy", "Full"), 
            label = "tab:lmBLQ",  
           notes = list("All variables scaled and mean centered by sample.", 
                       stars.note), 
          Sweave = TRUE, digits = 3) #, coef.names = coefnamesLag3)

@


\begin{tiny}
<<blqMods1, results='asis'>>=
ctrl <- lmerControl(optimizer = "Nelder_Mead", calc.derivs = FALSE)

demogsMMblq1 <- lmer(minBlaisLago ~ VAP_adjLOG + VAP_adjLOG_sq + 
                      per65o + PerBachelorOrAbove + 
                      per_white_all + OOH_share + incumShare + locale2 + 
                      treatment*GovTurnout_recall + 
                       (1|distid), data = moddat4, control = ctrl) 

demogsMMblq2 <- lmer(minBlaisLago ~ VAP_adjLOG + VAP_adjLOG_sq + 
                      per65o + PerBachelorOrAbove + 
                      per_white_all + OOH_share + incumShare + locale2 +  
                       RecallPolarization*treatment +
                       (1|distid), data = moddat4, control = ctrl) 


demogsMMblq3 <- lmer(minBlaisLago ~ VAP_adjLOG + VAP_adjLOG_sq + 
                      per65o + PerBachelorOrAbove + 
                      per_white_all + OOH_share + incumShare + locale2 +  
                       RecallPolarization*treatment + 
                       treatment*GovTurnout_recall + 
                       (1|distid), data = moddat4, control = ctrl) 

demogsMMblq4 <- lmer(minBlaisLago ~ VAP_adjLOG + VAP_adjLOG_sq + 
                      per65o + PerBachelorOrAbove + 
                      per_white_all + OOH_share + incumShare + locale2 +  
                       RecallPolarization + 
                       GovTurnout_recall + 
                       treatment * turnout_overall_werc + WERC_elec + 
                       (1|distid), data = moddat4, control = ctrl) 

politicMMblq <- update(demogsMMblq1, . ~ . + incumShare + 
                         overrideYesPer +  
                       partyDivisionRecent +
                    teachShareofVoters + fallTurnout + nraces) 

policyMMblq <- update(demogsMMblq1, . ~ . + ADMIN_SHARE_COMP + NEW_SUP + 
                        NonPublicPupilPer + 
                   DEBT_ATTEMPT_CUMUL93 + OVERRIDE_ATTEMPT_CUMUL93)

fullmodMMblq <- update(politicMMblq, . ~ . +  schoolMillShare + 
                         PROPERTYTAX_REV_SHARE + TCEC_MEMBER + 
                         balance_member_lag + millrate_delta + 
                    ADMIN_SHARE_COMP + NEW_SUP + NonPublicPupilPer + 
                   DEBT_ATTEMPT_CUMUL93 + OVERRIDE_ATTEMPT_CUMUL93)


# coefnamesLag3 <- c("Intercept","Lagged Turnout (2)", "ln(VAP)", 
#                  "\\% White", 
#                   "\\% Over 65", "\\% Bach. +", "\\% OOH", 
#                   "ln(MedianIncome)", "District-wide", "Blais-Lago", 
#                   "Fall Turnout",  "$ln(VAP)^{2}$")

apsrtable(demogsMMblq1, demogsMMblq2, demogsMMblq3, demogsMMblq4,
          caption = "Partial Pooling Model of Competitiveness",
          model.names = c("Turnout", "Polar", "Both", "WERC"), 
            label = "tab:meBLQ",  
           notes = list("All variables scaled and mean centered by sample.", 
                       stars.note), 
          Sweave = TRUE, digits = 3, float = "longtable", stars="default") #, coef.names = coefnamesLag3)
@
\end{tiny}

% Competitiveness appears to have increased post recall
% Increase was universal and not conditional on the polarization 
% or the participation in the recall
% Competition was steady across districts regardless of WERC election 
% Not much else is significant

Table \ref{tab:meBLQ} shows good things. 

\clearpage

\subsection{Turnout}

Using the election of Governor Walker and passage of Act 10 as an exogenous shock that 
increased the relevance and power of school boards, the following models seek to 
test the causal impact on turnout. In Figure \ref{fig:walkerplot} I examine the 
relationship between partisan polarization and turnout before and after the passage 
of Act 10. To test this relationship I restrict the sample to the two spring 
elections prior to the passage of Act 10 -- 2009 and 2010 -- and the two elections 
immediately after the passage of Act 10 -- 2011 and 2012. I code these latter 
years with a dummy variable indicating they are in the post-Act 10 era. The key 
theoretical contribution is that the polarization of the electorate should matter 
more after the passage of Act 10, when party lines for education issues became 
clear. 

<<walkerDataPrep2, results='asis', echo = FALSE, eval=FALSE>>=
## Grab Walker recall results
moddat <- dist_turn[, c("contestSer", "contestMinor", "distid","year", 
                        "balance_member_lag", "turnout", "VAP_adjLOG_sq",
                        "PerBachelorOrAbove", "VAP_adjLOG", "per_white_all", 
                        "districtwide", "turnoutLag1", "topTicketTurnoutSpring",
                        "OOH_share", "median_incomeLOG", "per65o", 
                        "NonWhitePublicPupilPer", "NonPublicPupilPer", 
                         "locale2", "incumShare", "contestMinorLag", 
                        "contestSerLag", "incDefeats", "nonincumbRun", 
                        "onlyIncum",
                        "overrideYesPer", "partyDivisionRecent", "turnoutLag2",
                        "teachShareofVoters", "fallTurnout", 
                        "nraces", "schoolMillShare", "PROPERTYTAX_REV_SHARE", 
                        "TCEC_MEMBER", "millrate_delta", 
                        "ADMIN_SHARE_COMP", "NEW_SUP", 
                        "DEBT_ATTEMPT_CUMUL93", "OVERRIDE_ATTEMPT_CUMUL93", 
                        "member_delta_per", "RecallPolarization",
                        "turnout_overall_werc", "minBlaisLago",
                        "eligvoters_werc", "fallTwoPartyShareDem",
                        "loss_werc", "worst_margin_werc", "WERC_elec", 
                        "GovTurnout_recall")]

moddat <- na.omit(moddat)
moddat <- moddat[moddat$year >= 2007,]
moddat <- moddat[order(moddat$distid, moddat$year),]
moddat$treatment <- ifelse(moddat$year > 2010, 1, 0)
moddat$distid <- factor(moddat$distid)
moddat$year <- factor(moddat$year)
moddat <- moddat[order(moddat$distid, moddat$year),]
moddat$distid <- factor(moddat$distid)
moddat$year <- factor(moddat$year)
moddat$turnout <- moddat$turnout * 100
moddat$districtwide <- factor(moddat$districtwide)
moddat$treatment <- factor(moddat$treatment)
# moddat$turnoutLag2 <- moddat$turnoutLag2 * 100
# moddat$turnoutLag1 <- moddat$turnoutLag1 * 100
# moddat$per_white_all <- moddat$per_white_all * 100
# moddat$per65o <- moddat$per65o * 100
# moddat$PerBachelorOrAbove <- moddat$PerBachelorOrAbove * 100
# moddat$OOH_share <- moddat$OOH_share * 100
# moddat$fallTurnout <- moddat$fallTurnout * 100
# moddat$VAP_adj <- log(moddat$VAP_adj)
# moddat$median_income <- log(moddat$median_income)
moddat$WERC_elec <- factor(moddat$WERC_elec)
centr <- mean(moddat$turnout)
stddev <- sd(moddat$turnout)
moddat$outflag <- (moddat$turnout - centr) / stddev
moddat <- moddat[moddat$outflag <= 5 & moddat$outflag >= -5,]

library(rms)
dd <<- datadist(moddat)
options(datadist="dd")

nums <- sapply(moddat, is.numeric)
#   for(i in unique(moddat$year)){
#     moddat[moddat$year == i, nums] <- 
#       apply(moddat[moddat$year == i, nums], 2, rescale)
#   }
moddat[, nums] <- apply(moddat[, nums], 2, rescale)
@

<<walkerTurnMod, results='hide', eval=TRUE>>=
demogsMod1 <- lm(turnout ~ turnoutLag2 + fallTurnout + VAP_adjLOG + 
                   VAP_adjLOG_sq + per_white_all + per65o + PerBachelorOrAbove + 
                   OOH_share + median_incomeLOG + minBlaisLago + 
                   districtwide + RecallPolarization * treatment + 
                   turnout_overall_werc, data = moddat)
demogsMod1SE <- get_CL_vcov(demogsMod1, moddat$distid)
demogsMod1$se <- sqrt(diag(demogsMod1SE))
demogsMod2 <- lm(turnout ~ turnoutLag2 + fallTurnout + VAP_adjLOG + 
                   VAP_adjLOG_sq + per_white_all + per65o + PerBachelorOrAbove + 
                   OOH_share + median_incomeLOG + minBlaisLago + 
                   districtwide + GovTurnout_recall * treatment + 
                   turnout_overall_werc, data = moddat)
demogsMod2SE <- get_CL_vcov(demogsMod2, moddat$distid)
demogsMod2$se <- sqrt(diag(demogsMod2SE))
demogsMod3 <- lm(turnout ~ turnoutLag2 + fallTurnout + VAP_adjLOG + 
                   VAP_adjLOG_sq + per_white_all + per65o + PerBachelorOrAbove + 
                   OOH_share + median_incomeLOG + minBlaisLago + 
                   districtwide + GovTurnout_recall * treatment + 
                    RecallPolarization * treatment + 
                   turnout_overall_werc, data = moddat)
demogsMod3SE <- get_CL_vcov(demogsMod3, moddat$distid)
demogsMod3$se <- sqrt(diag(demogsMod3SE))
demogsMod4 <- lm(turnout ~ turnoutLag2 + fallTurnout + VAP_adjLOG + 
                   VAP_adjLOG_sq + per_white_all + per65o + PerBachelorOrAbove + 
                   OOH_share + median_incomeLOG + minBlaisLago + 
                   districtwide + GovTurnout_recall +
                    RecallPolarization + 
                   turnout_overall_werc*treatment, data = moddat)
demogsMod4SE <- get_CL_vcov(demogsMod4, moddat$distid)
demogsMod4$se <- sqrt(diag(demogsMod4SE))

lmTurnoutTable <- apsrtable(demogsMod1, demogsMod2, demogsMod3, demogsMod4, 
          se = "robust", label="tab:lmTurnoutmod", 
          caption = "Model of Causal Impact of Act 10 on School Board Turnout",
          Sweave=FALSE, digits = 3)
@

Table \ref{tab:meTurnout} shows good things. 

\begin{tiny}
<<turnoutMM, results='asis', echo = FALSE, eval=TRUE>>=
demogsMod1mm <- lmer(turnout ~ turnoutLag2 + fallTurnout + VAP_adjLOG + 
                   VAP_adjLOG_sq + per_white_all + per65o + PerBachelorOrAbove + 
                   OOH_share + median_incomeLOG + minBlaisLago + 
                   districtwide + RecallPolarization * treatment + 
                   turnout_overall_werc + (1|distid), data = moddat)
demogsMod2mm <- lmer(turnout ~ turnoutLag2 + fallTurnout + VAP_adjLOG + 
                   VAP_adjLOG_sq + per_white_all + per65o + PerBachelorOrAbove + 
                   OOH_share + median_incomeLOG + minBlaisLago + 
                   districtwide + GovTurnout_recall * treatment + 
                   turnout_overall_werc+ (1|distid), data = moddat)
demogsMod3mm <- lmer(turnout ~ turnoutLag2 + fallTurnout + VAP_adjLOG + 
                   VAP_adjLOG_sq + per_white_all + per65o + PerBachelorOrAbove + 
                   OOH_share + median_incomeLOG + minBlaisLago + 
                   districtwide + GovTurnout_recall * treatment + 
                    RecallPolarization * treatment + 
                   turnout_overall_werc + (1|distid), data = moddat)
demogsMod4mm <- lmer(turnout ~ turnoutLag2 + fallTurnout + VAP_adjLOG + 
                   VAP_adjLOG_sq + per_white_all + per65o + PerBachelorOrAbove + 
                   OOH_share + median_incomeLOG + minBlaisLago + 
                   districtwide + GovTurnout_recall +
                    RecallPolarization + 
                   turnout_overall_werc*treatment + (1|distid), data = moddat)

tabnote <- "Model includes district random effects modeled as intercepts."

apsrtable(demogsMod1mm, demogsMod2mm, demogsMod3mm, demogsMod4mm,
          caption = "Partial Pooling Model of Post-Election Turnout",
          label = "tab:meTurnout", notes = list(tabnote, stars.note), 
          Sweave = TRUE, digits = 3)
@
\end{tiny}

Table \ref{tab:meTurnout} shows the results here.

% turnout definitely increases post recall
% more polarized communites had a relative decrease in turnout uptick
% prior to the recall, no effect of polarization
% Recall turnout positively related to turnout
% post recall, recall turnout leads to even greater increase in turnout
% WERC membership does not matter, post-recall WERC membership small 
% increase in turnout

% These effects are net of turnout lagged and fall turnout

\clearpage

\subsubsection{Rolloff}

<<rolloffDataSetup>>=
moddat <- dist_turn[, c("contestSer", "contestMinor", "distid","year", 
                        "balance_member_lag", "turnout", "VAP_adjLOG_sq",
                        "PerBachelorOrAbove", "VAP_adjLOG", "per_white_all", 
                        "districtwide", "turnoutLag1", "topTicketTurnoutSpring",
                        "OOH_share", "median_incomeLOG", "per65o", 
                        "NonWhitePublicPupilPer", "NonPublicPupilPer", 
                         "locale2", "incumShare", "contestMinorLag", 
                        "contestSerLag", "incDefeats", "nonincumbRun", 
                        "onlyIncum", "turnoutDiff", "topTicketTurnoutSpring",
                        "overrideYesPer", "partyDivisionRecent", "turnoutLag2",
                        "teachShareofVoters", "fallTurnout", 
                        "nraces", "schoolMillShare", "PROPERTYTAX_REV_SHARE", 
                        "TCEC_MEMBER", "millrate_delta", 
                        "ADMIN_SHARE_COMP", "NEW_SUP", 
                        "DEBT_ATTEMPT_CUMUL93", "OVERRIDE_ATTEMPT_CUMUL93", 
                        "member_delta_per", "RecallPolarization",
                        "turnout_overall_werc", "minBlaisLago",
                        "eligvoters_werc", "fallTwoPartyShareDem",
                        "loss_werc", "worst_margin_werc", "WERC_elec", 
                        "GovTurnout_recall")]

moddat <- na.omit(moddat)
moddat <- moddat[moddat$year >= 2007,]
moddat <- moddat[order(moddat$distid, moddat$year),]
moddat$treatment <- ifelse(moddat$year > 2010, 1, 0)
moddat$distid <- factor(moddat$distid)
moddat$year <- factor(moddat$year)
moddat <- moddat[order(moddat$distid, moddat$year),]
moddat$distid <- factor(moddat$distid)
moddat$year <- factor(moddat$year)
moddat$turnout <- moddat$turnout * 100
moddat$districtwide <- factor(moddat$districtwide)
moddat$treatment <- factor(moddat$treatment)
# moddat$turnoutLag2 <- moddat$turnoutLag2 * 100
# moddat$turnoutLag1 <- moddat$turnoutLag1 * 100
# moddat$per_white_all <- moddat$per_white_all * 100
# moddat$per65o <- moddat$per65o * 100
# moddat$PerBachelorOrAbove <- moddat$PerBachelorOrAbove * 100
# moddat$OOH_share <- moddat$OOH_share * 100
# moddat$fallTurnout <- moddat$fallTurnout * 100
# moddat$VAP_adj <- log(moddat$VAP_adj)
# moddat$median_income <- log(moddat$median_income)
centr <- mean(moddat$turnout)
stddev <- sd(moddat$turnout)
moddat$outflag <- (moddat$turnout - centr) / stddev
moddat <- moddat[moddat$outflag <= 5 & moddat$outflag >= -5,]

library(rms)
dd <<- datadist(moddat)
options(datadist="dd")

nums <- sapply(moddat, is.numeric)
#   for(i in unique(moddat$year)){
#     moddat[moddat$year == i, nums] <- 
#       apply(moddat[moddat$year == i, nums], 2, rescale)
#   }
moddat[, nums] <- apply(moddat[, nums], 2, rescale)

@

<<rolloffLM, results='hide'>>=
demogsMod1ro <- lm(turnoutDiff ~ turnoutLag2 + fallTurnout + VAP_adjLOG + 
                   VAP_adjLOG_sq + per_white_all + per65o + PerBachelorOrAbove + 
                   OOH_share + median_incomeLOG + minBlaisLago + 
                   districtwide + RecallPolarization * treatment + 
                   turnout_overall_werc, data = moddat)
demogsMod1roSE <- get_CL_vcov(demogsMod1ro, moddat$distid)
demogsMod1ro$se <- sqrt(diag(demogsMod1roSE))
demogsMod2ro <- lm(turnoutDiff ~ turnoutLag2 + fallTurnout + VAP_adjLOG + 
                   VAP_adjLOG_sq + per_white_all + per65o + PerBachelorOrAbove + 
                   OOH_share + median_incomeLOG + minBlaisLago + 
                   districtwide + GovTurnout_recall * treatment + 
                   turnout_overall_werc, data = moddat)
demogsMod2roSE <- get_CL_vcov(demogsMod2ro, moddat$distid)
demogsMod2ro$se <- sqrt(diag(demogsMod2roSE))
demogsMod3ro <- lm(turnoutDiff ~ turnoutLag2 + fallTurnout + VAP_adjLOG + 
                   VAP_adjLOG_sq + per_white_all + per65o + PerBachelorOrAbove + 
                   OOH_share + median_incomeLOG + minBlaisLago + 
                   districtwide + GovTurnout_recall * treatment + 
                    RecallPolarization * treatment + 
                   turnout_overall_werc, data = moddat)
demogsMod3roSE <- get_CL_vcov(demogsMod3ro, moddat$distid)
demogsMod3ro$se <- sqrt(diag(demogsMod3roSE))
demogsMod4ro <- lm(turnoutDiff ~ turnoutLag2 + fallTurnout + VAP_adjLOG + 
                   VAP_adjLOG_sq + per_white_all + per65o + PerBachelorOrAbove + 
                   OOH_share + median_incomeLOG + minBlaisLago + 
                   districtwide + GovTurnout_recall +
                    RecallPolarization + 
                   turnout_overall_werc*treatment, data = moddat)
demogsMod4roSE <- get_CL_vcov(demogsMod4ro, moddat$distid)
demogsMod4ro$se <- sqrt(diag(demogsMod4roSE))

lmRolloffTable <- apsrtable(demogsMod1ro, demogsMod2ro, 
                            demogsMod3ro, demogsMod4ro, 
          se = "robust", label="tab:lmTurnoutmod", 
          caption = "Model of Causal Impact of Act 10 on School Board Rolloff",
          Sweave=FALSE, digits = 3)

@

\begin{tiny}
<<rolloffMerMod, results='asis'>>=
demogsMod1roMM <- lmer(turnoutDiff ~ turnoutLag2 + fallTurnout + VAP_adjLOG + 
                   VAP_adjLOG_sq + per_white_all + per65o + PerBachelorOrAbove + 
                   OOH_share + median_incomeLOG + minBlaisLago + 
                   districtwide + RecallPolarization * treatment + 
                   turnout_overall_werc + (1|distid), data = moddat)
demogsMod2roMM <- lmer(turnoutDiff ~ turnoutLag2 + fallTurnout + VAP_adjLOG + 
                   VAP_adjLOG_sq + per_white_all + per65o + PerBachelorOrAbove + 
                   OOH_share + median_incomeLOG + minBlaisLago + 
                   districtwide + GovTurnout_recall * treatment + 
                   turnout_overall_werc + (1|distid), data = moddat)
demogsMod3roMM <- lmer(turnoutDiff ~ turnoutLag2 + fallTurnout + VAP_adjLOG + 
                   VAP_adjLOG_sq + per_white_all + per65o + PerBachelorOrAbove + 
                   OOH_share + median_incomeLOG + minBlaisLago + 
                   districtwide + GovTurnout_recall * treatment + 
                     RecallPolarization * treatment + 
                   turnout_overall_werc + (1|distid), data = moddat)
demogsMod4roMM <- lmer(turnoutDiff ~ turnoutLag2 + fallTurnout + VAP_adjLOG + 
                   VAP_adjLOG_sq + per_white_all + per65o + PerBachelorOrAbove + 
                   OOH_share + median_incomeLOG + minBlaisLago + 
                   districtwide + GovTurnout_recall +
                     RecallPolarization + WERC_elec + 
                   turnout_overall_werc * treatment + (1|distid), data = moddat)

apsrtable(demogsMod1roMM, demogsMod2roMM, demogsMod3roMM, demogsMod4roMM,
          caption = "Partial Pooling Model of Post-Election Turnout",
          label = "tab:meRolloff", notes = list(tabnote, stars.note), 
          Sweave = TRUE, digits = 3)
@
\end{tiny}

% rolloff increases post recall
% WERC turnout decreases rolloff (no differentiation post recall)
% Recall polarization has no effect on turnout, and none post recall
% recall turnout increases rolloff, post recall this is magnified
% Net of increased turnout, recall polarization leads to increased 
% voter rolloff

\clearpage

\subsection{Substantive Effects}

Next I demonstrate the substantive magnitude of the state level policy shock to 
contextualize the influence that state government can have on local elections. 

\section{Conclusion}


\section{Appendix}

\subsection{Fixed Effect Models}

\begin{tiny}
<<seriousGLMtable, results='asis'>>=
seriousGLMtable
@
\end{tiny}

\begin{tiny}
<<minorGLMtable, results='asis'>>=
minorGLMtable
@
\end{tiny}


\begin{tiny}
<<incDef2table, results='asis'>>=
incDefGLMtable
@
\end{tiny}

\begin{tiny}
<<incDef2table2, results='asis'>>=
incDefGLMtable2
@
\end{tiny}

\begin{tiny}
<<lmBLQtable, results='asis'>>=
lmBLQtable
@
\end{tiny}


\begin{tiny}
<<lmTurnoutTable, results='asis'>>=
lmTurnoutTable
@
\end{tiny}

\begin{tiny}
<<lmRolloffTable, results='asis'>>=
lmRolloffTable
@
\end{tiny}