\chapter{Assessing School Board Responsiveness to Voter Dissatisfaction}
\label{chap:walker}
\chapterstyle{deposit}

<<rsetup, results='hide', echo=FALSE, message=FALSE, warning=FALSE>>=
opts_chunk$set(fig.width=8, fig.height=6, message=FALSE, error=FALSE, 
               fig.path="../../phd_figs/chap6-",
               warning=FALSE, echo=FALSE, dev='pdf')

setwd("../../")
library(scales)
library(xtable)
library(eeptools)
source("R/thesis_functions.R")
source("data/cleanandprep_WALKER.R")
options(xtable.include.rownames = FALSE, xtable.table.placement = "ht")
# Set up tables
library(devtools)
# install_github("jknowles/apsrtable", subdir = "pkg", ref = "dev")
library(apsrtable)
stars.note <- apsrtable:::stars.note
# Quick variable transform
dist_turn$VAP_adjLOG_sq <- dist_turn$VAP_adjLOG^2
dist_turn$RecallPolarization <- 1 - abs(dist_turn$GovTwoPartyShareDem_recall - dist_turn$GovTwoPartyShareRep_recall)
dist_turn$RecallPolarization <- dist_turn$RecallPolarization * 100
dist_turn$contestMinor <- factor(dist_turn$contestMinor)
dist_turn$contestSer <- factor(dist_turn$contestSer)
dist_turn$onlyIncum <- ifelse(dist_turn$incumShare == 1, 1, 0)
dist_turn$nonincumbRun <- ifelse(dist_turn$onlyIncum == 1, 0, 1)
dist_turn$incDefeats <- ifelse(dist_turn$incDefeats > 0, 1, 0)
# consider diminishing returns to these
# dist_turn$minBlaisLago[dist_turn$minBlaisLago == 0] <- .0001
# dist_turn$minBlaisLago <- log(dist_turn$minBlaisLago)
# dist_turn$partyDivisionRecent <- log(dist_turn$partyDivisionRecent)

library(gridExtra)
@


\section{Introduction}

The previous two chapters do not make a strong case for the democratic nature 
of school boards. In Wisconsin from 2002-2012 it was nearly impossible to predict 
the emergence of challengers or competitive elections using measures of school 
district fiscal, political, or policy pressure. Turnout was more easily predicted 
by demographics and community factors, but rarely moved above 20-30\% and was 
not strongly responsive to fiscal, political, or policy inputs either. Thus, 
in many communities, school board elections can be best described as 20-30\% of 
voters nearly unanimously approving unopposed incumbents. 

Defenders of the democratic nature of school boards have three responses. First, 
measuring conditions for changes in turnout and contestation with the kind of 
statewide measures used will not work -- the issues that spark controversy for 
boards are local and idiosyncratic. Whether it is a protest over 
eliminating an AP course in the high school, or a scandal involving an employee, 
wedge issues in school boards campaigns are based on crises.\footnote{\citet{oliver} 
finds this to be the case exactly in suburban mayoral elections.} %TODO: add details on stories here
Second, turnout and contestation in the period of study chosen here may be low, but 
turnout and contestation increase when necessary -- a cornerstone of the 
dissatisfaction theory of school board democracy \citep{RefWorks:297}. Thus, 
perhaps it is the case that in the period of study, school boards 
were not under much pressure from community and were generally assessed as providing 
good stewardship of public schools. Only over a longer time period and a larger 
sample might we expect to find systematic patterns of voter dissatisfaction with 
boards. Finally, voters are more likely to participate when they are informed on 
the issues. Like the argument about non-voting in American presidential races, 
defenders of school boards might suggest that the preferences of voters and 
non-voters are not different, and thus despite the low turnout, the appropriate 
values and goals of the electorate are advanced by a subset of voters. 

This chapter seeks to answer these challenges directly. I use the political turmoil 
that followed the election of Governor Scott Walker in 2010 to explore these 
objections to the findings of the prior chapters. I argue that the events of this 
period formed an exogenous policy shock which a) raised awareness about the power 
of local school boards, b) placed school board issues on a familiar and polarized 
liberal-conservative issue dimension, and c) created a unified, contentious, and 
widely debated statewide issue on which all school board candidates and voters 
were focused across the state. While I still argue that overall the decade from 
2002-2012 in Wisconsin ranks as one of the most contentious decades of education politics in state history, this chapter sets that debate aside. Instead, I focus 
on examining the change in turnout and contestation during this period of political 
upheaval from 2010-2012. As I will show, the political focus on education politics 
and school boards provides a pure test of dissatisfaction theory on a statewide 
scale. 

This chapter proceeds as follows. First, I review the literature on dissatisfaction 
theory and its descendants to identify testable hypotheses. Next, I establish the 
Wisconsin context and describe the statewide political conditions in the period 
surrounding the passage of Wisconsin Act 10. Next, I establish the data and methods 
used to test dissatisfaction theory in Wisconsin. Finally, I assess the results 
in the context of existing theories of school board governance. 

% TODO: Add conclusion

\section{Literature Review}

\subsection{Dissatisfaction Theory}

As stated before, dissatisfation theory is the dominant theoretical lens developed 
for understanding school board elections. It grows out of \citet{RefWorks:348}'s
concept of critical elections, stating that the politics of school boards is 
characterized by long stretches of equilibrium punctuated by periods of upheaval,
contentious elections, and incumbent defeats \citep{RefWorks:297}. Proponents 
argue that the lack of two-party politics creates a closed system between 
administrators and the board to make decisions without strong feedback from the
community. As the distance between the community and the school 
district grows, eventually a fracture occurs and an outpouring of political activity 
leads to upheaval, incumbent defeat, and board and superintendent turnover 
\citep{RefWorks:271}. To operationalize this theory, \citet{RefWorks:297} identify 
a dimension of community characteristics that identify the level of activity in 
school board elections. They label this continuum the secular-to-sacred continuum. 
Sacred communities are insular, skeptical of outside expertise, and consensus 
driven. Secular communities are less monolithic, marked by more conflict and 
competition. Dissatisfaction theory, thus, seeks to explain the transition of 
communities when the monolithic power of the insular political community decays 
and is replaced by a new power structure before restabilizing. 

Much of the existing evidence supporting dissatisfaction theory relies on snapshot 
studies of a single year or small sample of school districts using survey items 
and interviews with board members \citep{RefWorks:311,RefWorks:245,RefWorks:247,RefWorks:341}. Many of these studies draw on some of the quantitative measures 
that \citet{RefWorks:297} argue may be associated with communities in transition such as school district size, urbanization, geographic mobility, the extent the district 
is coterminous with other local government units, the cosmopolitan character of 
the residents, and the political associations within the community. The authors 
suggest that communities in transition in these ways may move along the 
secular-to-sacred continuum. 

An important consensus emerges from these studies about the need to distinguish 
between incumbent defeat and retirement. Unfortunately, the way retirement is 
coded is not consistent across studies and coding retirement is not feasible 
at a large scale as the decision to retire may be encouraged politically. 
Additionally, these studies often rely on candidate or former board member 
self-reports of defeat or retirement. Another problem with the literature though 
voter dissatisfaction is talked about as an ``upwelling'' or ``rising tide'' of discontent, the most direct measure of this -- increased voter participation is 
not analyzed. Chapter \ref{chap:turnout} takes up this issue and finds some 
evidence that voter turnout is linked to measures of community dissatisfaction 
with local education policy. 

Empirical work on school board turnover, incumbent defeat, and subsequent 
superintendent turnover is relatively more common. \citet{RefWorks:259} attempted 
to predict school board turnover using socioeconomic factors and measures of 
dissatisfaction in Ohio but was unsuccessful. A re-analysis of this data by 
\citet{RefWorks:337} considers recalculating the dependent and independent 
variables of interest and finds that dissatisfaction is predictive. As I have 
shown previously in Chapter \ref{chap:candidacy}, observable district 
demographics do not predict emergence of challengers or incumbent defeat. Instead, across the sample, variance in the level of contestation of school boards appears 
to be due to district specific unobservable characteristics.

One explanation for the discrepancy between Chapter \ref{chap:candidacy} and prior 
studies is the that previous studies ignored the endogeneity inherent 
in predicting incumbent defeat by using the number of challengers. This 
endogeneity arises due to a simple fact that with more choices available, the 
win expectancy of the incumbent decreases as a function of available options to 
voters -- particularly in an uninformed environment. More problematic though, is 
the fact that the same forces that cause candidates to emerge for office 
(strategic candidates) are strongly associated with the likely defeat of an 
incumbent. These issues are addressed in Chapter \ref{chap:candidacy} where 
incumbent defeat is not found to be easily predicted by measures suggested by 
dissatisfaction theory. The other studies of incumbent school board defeat also 
rely on outdated statistical methods or substantial identification issues 
\citep{RefWorks:311,RefWorks:245,RefWorks:247,RefWorks:341}. Thus the empirical 
rigor of this literature is weak. 

% Partisan elections RefWorks:273
% ``The number of challengers is a reasonable operational indicator of public 
% dissatisfaction." \citep{RefWorks:337}

\subsection{Mediating Forces}
 
While dissatisfaction theory is the dominant lens through which most previous 
studies of school board elections have been conducted, it is not without its 
critics. One of the first and strongest criticisms came from \citet{RefWorks:281},
who argue that policy and political turnover in school districts is an illusion. 
Essentially, school districts are viewed as administrative bodies that are 
captured by the special interests with the most at stake in their decisions. 
This is known as continuous participation theory. 

Continuous participation theory agrees with dissatisfaction theory in the finding 
that periodic incumbent defeat and swells of participation exist. The theories 
diverge in their predictions about the result of these democratic outbursts. 
Dissatisfaction theory sees them resulting in a realignment of school board policy 
toward the preferences of the wider community. Continuous-participation theory 
sees them as a way to further entrench the interests of the narrow interest 
group behind the upwelling. Thus in one case challengers arise to defend the 
interests of the community, and in another challengers arise to better serve 
the interests of specific factions within the community. 

Recent work has picked up this thread and found evidence of special interest 
influence in school districts on employee wages 
\citep{RefWorks:207,RefWorks:218,anzia11}, curriculum content 
\citep{RefWorks:240,RefWorks:347}, and evidence on taxation in special jurisdiction 
governments analagous to school districts \citep{berry2}. Thus, any apparent 
increase in school board political activity observed is viewed as being in the 
best interest of the special interest groups which dial participation up and down 
depending on their policy goals. 

However, it is difficult to identify how these two theories are incongrous in 
their expectations. Without measures of the preferences of the community, the 
board, and the superintendent it is difficult to draw support for either model 
from the observation of political activity at the school board level. Both models 
see political activity as being mediated by the interests of different groups -- 
for dissatisfaction theory the community at large, and for continuous participation 
theory entrenched special interests. In the next section, I will describe a new 
lens of interpreting school board elections that draws from both of these 
traditions and can be tested using the events of 2010-2012 in Wisconsin. 

\section{Theory and Wisconsin Context}

\subsection{Democracy}

I suggest a reframing of dissatisfaction theory to provide more testable hypotheses 
and a stronger linkage to other theories of democracy. I conceptualize 
democracy of having two distinct dimensions -- potential and actualized democracy. 
Potential democracy describes the existence of conditions that allow citizens to 
voice their opinion, select their leaders, and influence policy. A democratic 
system can be considered to have high democratic potential when it has open and 
free elections, transparency in decision making, and high levels of information 
about candidate and citizen policy and preferences. However, a government may 
have these features, but they may not be being utilized at the moment. Actualized democracy describes the usage of these systems in the form of citizen 
participation, candidate choice, and information levels available to make 
decisions. This simple two dimensional model of democracy has important 
implications for the understanding of the political activity at the school board 
level. 

Like others, I focus on several sources of \emph{friction} which inhibit 
citizens from converting the potential of their democratic institutions into 
actualized democratic actions. The most important is the lack of information. 
Obtaining information about candidates is expensive and the more specialized the 
policy making, the more expensive the acquisition of knowledge on preferences of candidates can be \citep{RefWorks:351}. In this framework, the narrow and 
specialized issue brief of school boards, like other local and special jurisdiction 
governments, makes the actualization of democratic potential difficult for individual citizens \citep{fosterK,burnsN}. 

This informational deficit is a collective action problem. Interest groups then 
should rise to fill this void \citep{olson1965logic}. I consider three special 
interest groups that seek to organize information on school board to different 
degrees: district employees, property taxpayers, and parents. Each of these groups 
are different in their size, core issues, and preferences. These groups are also 
not mutually exclusive -- citizens can belong to any combination of them. 


% Table
\begin{table}[h!]
\begin{center}
\begin{small}
\caption{Potential Interest Groups in School Board Elections}
\label{tab:interests}
\begin{tabular}{| p{.2\textwidth} | p{.15\textwidth} | p{.15\textwidth} | p{.15\textwidth} p{.15\textwidth} |}
\hline
\textbf{Group}  & \textbf{Benefit} & \textbf{Cost} & \textbf{Cohesion}  & \textbf{size} \\ \hline
Teachers  & High & Lowest & Concentrated & Small \\ \hline
Parents & Medium & Moderate & Diffuse & Medium \\ \hline
Property Owners & Low & High & Diffuse & Large \\ \hline
\end{tabular}
\end{small}
\end{center}
\end{table}

Table \ref{tab:interests} describes these groups along the dimensions of their 
expected benefit from public schools, their relative share of the cost of schooling, 
their cohesion as a group, and their relative size. Teachers are the most cohesive group with the biggest benefit from district policies 
as the school district is their employer and provider of benefits. Thus teachers 
have the strongest incentives to participate in school board elections, organize 
others, and express their voice. Parents, on the other hand, are a diffuse group 
with generally lower resources (parents have less wealth and income than the other 
two groups in most communities), but a large connection to the benefit of schools 
through the provision of better education for their children. Property owners 
have an interest in school boards because of their ability to set a substantial 
portion of property tax rates. However, property owners face the greatest 
coordination problem because they are the most diffuse group and their coordination 
costs are the highest. 

Thus, while organized interest groups can be conceptualized as a way to overcome 
the friction involved in actualizing democracy, the incentives for these groups 
varies. School board elections can be interpreted as reflecting the preferences 
of those voters mobilized by these groups based on the intensity and homogeneity 
of each of their preferences multiplied by their size -- Dahl's polyarchy \citep{RefWorks:319}.

Dissatisfaction theory would agree with this reframing of the power 
structures of school boards and suggest that periodically if the board strays too 
far from the preferences of less represented groups, voters will punish them and 
adjust the board to reflect the preferences of the community. If this is the case, 
then if more individuals actualized their democratic behavior, voters would largely 
retain their current board members but with greater numbers. That is, if we could 
exogenously eliminate the coordination and information costs for each interest group, 
we should not expect to see great changes in school board membership. 

On the other hand, if community fractures do exist, then this injection of 
information should accelerate the process of actualizing democratic activity 
for broader swaths of the community. In these cases, the exogenous shock should 
accelerate the process of increased candidate and voter activity, culminating 
in heightened incumbent defeat. I now turn to describing the political conditions 
in Wisconsin from 2010-2012 that created such an exogenous provision of information 
to voters. I demonstrate how this statewide shock increased information for voters 
about school board candidates and lowered the cost to participating in school board 
elections. This allows me to explore whether the status quo prior to the exogenous
shock reflected the will of voters, or the will of a well-organized subset of 
voters who were not representative of the broader community interests. 

\subsection{Wisconsin from 2010-2012}

Wisconsin from 2012-2012 provides an ideal test case for testing the impact 
of increased voter information and decreased friction in the democratic process. 
As discussed in Chapter \ref{chap:intro} and illustrated in Figure 
\ref{fig:wiscotimeline} the election of Scott Walker to Governor and the 
subsequent passage of Act 10, the 2011-13 biennial budget, and the mass protests 
in Madison, WI, state level politics in Wisconsin became suddenly polarized. 
The precipitating event was the passage of a statewide reform restricting the 
power of public employee unions to collectively bargain. This reform was passed 
as part of Wisconsin Act 10, known as the budget repair bill. In practice, the 
bill was packaged as a set of ``tools'' to allow local and state government the
authority to extract concessions from employees on wages and benefits that would 
not be possible under collective bargaining. This was necessary, it was argued, 
to allow local governments to absorb the large budget reductions necessary to 
balance the state budget. 

School districts led by local school boards, and the teachers' unions they bargained 
with, made up a large proportion of those affected by the reforms in Act 10. In 
fact, Act 10 represented a sweeping expansion of the power of school boards away 
from local teachers' unions and as such was met with an unprecedented upwelling 
of political opposition. Madison was engulfed in protests for weeks ahead of the 
2011 spring elections as shown in Figures \ref{fig:protest1} and 
\ref{fig:protest2}. 

\begin{center}
\begin{figure}[h!]
\caption{Wisconsin Politics 2011-2013 Timeline}
\label{fig:wiscotimeline2}
\includegraphics[width=\textwidth,height=1.75in]{img/wiscotimeline}
\end{figure}
\end{center}

\begin{center}
\begin{figure}[h!]
\begin{framed}
\caption{Budget Protests at the Wisconsin Capitol.  \copyright\ Justin Ormont | Wikimedia Commons | CC-BY-SA-3.0}
\label{fig:protest1}
\includegraphics[width=4.425in,height=2.5in]{img/budgetProtest1}
\end{framed}
\end{figure}
\end{center}


\begin{center}
\begin{figure}[h!]
\begin{framed}
\caption{Budget Protests Inside the Capitol. \copyright\ Joe Rowley | Wikimedia Commons | CC-BY-SA-3.0 }
\label{fig:protest2}
\frame{\includegraphics[width=3in,height=4in]{img/budgetProtest2}}
\end{framed}
\end{figure}
\end{center}

The new freedom to determine employee compensation outside of collectively bargained 
agreements meant that school boards now had more power. Importantly, 
this grant of power and increased political discourse surrounding the power of 
school boards relative to their employees was unanticipated by political observers 
and the public. It represents an exogenous shock because voters, school board 
members, and public employee unions had no knowledge prior to the introduction 
of the budget repair bill that the right to collectively bargain would be 
modified in 2011. \footnote{This last point is disputed by some conservative 
political observers and Scott Walker himself who claim that candidate Walker 
campaigned on this issue. However, the consensus has been that there is no record 
of any proposal during the 2010 campaign according to an investigation 
by the \href{http://www.politifact.com/wisconsin/statements/2011/feb/22/scott-walker/wisconsin-gov-scott-walker-says-he-campaigned-his-/}{Milwaukee Journal Sentinel}.} 

The events of 2011 and 2012 are depicted in Figure \ref{fig:wiscotimeline2}. Key 
events are marked as well as the dates of the spring school board elections of 
2011 and 2012. As Act 10's introduction was the precipitating event, I refer to 
this political unrest as the Act 10 period, which stretches from February 11, 2011 
with the introduction of Act 10 to Scott Walker's successful defeat of Milwaukee Tom 
Barrett in the recall election on June 9, 2012. I argue that the exogenous shock 
to the school board election process persists throughout this period because of 
the continual focus on education policy, school board politics, and the sustained 
polarization around Act 10 and Governor Walker's education policy. For example, 
after Act 10 was passed it became entangled in court battles while protestors 
turned their attention to the Wisconsin 2011-2013 Biennial Budget and its  
substantial cuts to school funding. Additionally, a signature drive for recall 
elections against several state senators was underway through the spring and 
summer. After that, the 2012 spring primary election took 
place during the heart of the recall petition signature drive and the spring 
2012 general eletions took place after the recall petition signatures were made public 
at the start of the gubernatorial recall election campaign. I conclude that this 
period then represented an unprecedented period of contention over the politics 
of school districts and education policy in Wisconsin. I argue that this Act 10
period galvanized the debate around education policy in Wisconsin in three 
distinct ways. 

First, it forced school board members and teachers' unions to show their hands 
to the public with respect to bargaining agreements. After Act 10 
boards were given the ability to unilaterally set compensation plans for their 
staff, which account for approximately 90\% of their annual operating costs.
\footnote{SOURCE}. This 
new power strongly incentivized both employee unions and property owners to express 
their policy preference for school district expenditures to mobilize both candidates 
and voters. School boards now, more than ever, had the chance to actualize the 
preferences of voters either to hold down property taxes, or to protect school 
staff from budget cuts. Additionally, many school boards had the option of renewing 
their union contracts between the time that Act 10 was passed and the time the 
law took effect -- effectively honoring their existing compensation and working 
condition agreements into the future. The option to extend contracts or to enact 
changes in the compensation plan was a high profile decision faced by some school 
boards in the post Act 10 period. 

The second effect Act 10 had on school board elections is that it injected a 
partisan dimension into traditionally non-partisan school board races. Candidates 
had to take a position on Act 10 publicly, aligning themselves 
unfairly or not, with either Governor Walker and the Republican party or the 
Democrats in opposition. Thus, voters and candidates who may have faced informational 
deficits in participating in school board elections previously could quickly signal 
to one another their policy goals using a public statement in favor of or condeming 
Act 10. 

The third effect of Act 10 was an intensified public discourse over the 
stewardship of public schools. This statewide political debate surrounding
around Act 10, the historic protests, and the recall election campaign all 
increased the amount of information voters had about school boards, school board 
powers, and the positions of their local school boards on issues such as Act 10, 
school funding, and budget priorities. Thus the informational advantage possessed 
by members of some interest groups prior to Act 10 evaporated. 


\subsection{Expectations}

How might an exogenous shock like the Act 10 period affect school board elections? 
For candidates, it raises the potential benefit and lowers the cost of running. 
Challengers to current board members can now capitalize on the 
increased public awareness about school funding and compensation plans to distinguish 
themselves from incumbents. Additionally, these candidates have more information 
about the likelihood of their success based on the preferences 
of the voters in their school district for Governor Walker -- both in the 2010 
Gubenatorial race and in the 2012 recall. 

For voters, the advantages are perhaps even more clear. Now voters have a high 
profile polarizing issue into which to divide candidates. This increases the 
information available for voters, decreasing the costs of voting. Additionally, 
if boards are given more power, voters have more reason to believe that their 
policy preferences can be actualized by electing a candidate more closely related 
to their preferences. 

If school board members were already representing the preferences of the majority 
of their community, and not a majority of the spring election electorate, then 
this increased information would result in potential increases to participation, 
but not a substantive change in representation. Voters may be more active because 
of an increased interest in voting in general -- an issue we will return to later -- 
but the results should be largely the same. However, continuous participation 
theory suggests that by expanding the electorate and revealing more information 
about the preferences of board members, voters should be more likely to participate 
and reject candidates who represent the interests of those who were participating 
prior to the Act 10 period. On average, prior to Act 10, boards should have been 
representing the preferences of the few continual participants in the electoral 
process, and post Act 10 the expansion of information should increase the size 
of the electorate and diversify the preferences enough to result in new choices 
for voters. 

For dissatisfaction theory the story is more nuanced. Depending on where a 
community is in the cycle of insular policymaking to public dissatisfaction 
much change may not happen. That is, the impact of the Act 10 period will be 
mediated by the prior electoral activity in the school district. Specifically, 
if the board has already been made reflective of the interests of the broader 
community through a prior period of local upheaval, then the Act 10 period should 
have little effect on board membership. However, if the board was previously 
insular and little information about its position relative to those of the community 
was known, then the Act 10 period should result in larger impacts in these 
communities. As dissatisfaction theory suggests that these realignments 
of school boards to community preferences are rare, I expect that on average 
the Act 10 period should lead to an overall increase in competition, incumbent 
defeat, and voter participation. 

\begin{center}
\begin{figure}[h!]
\caption{A Theoretical Model of School Board Policy Shock}
\label{fig:model}
\includegraphics[width=.9\textwidth]{img/theory}
\end{figure}
\end{center}
\vspace{-48pt}

Figure \ref{fig:model} is reproduced from Chapter \ref{chap:intro}. It shows 
how preferences of the community and board policy in the pre-election period 
are related to the rise of challengers, voter participation, and incumbent defeat 
in the election period. Three potential indicators of the alignment of community 
and school board preferences are posited. The first is the level of support for 
Governor Walker's education policies in the Act 10 period. Second is the strength 
of support in the community for those preferences. Third is the relative strength 
of interest groups in the community -- specifically in this case teachers' 
unions. 

Table \ref{tab:act10hypo} summarizes these expectations. 

As in Chapter \ref{chap:candidacy}, I use three separate measures of contestation. 
First, I use the presence of any challenger either appearing on the ballot or receiving 
more than 10 votes as a write-in candidate. I code these races as ``minorly contested'' 
because they have a nominal level of contestation at a minimum. Next, I use a higher 
threshold where only races with challengers who receive 20 or more votes are 
considered as ``seriously contested''. Finally, I use a measure of race competitiveness, 
the Blais-Lago quotient. 

\begin{table}[h!]
\begin{center}
\begin{small}
\caption{Expected Relationships between Key Independent and Dependent Variables}
\label{tab:act10hypo}
\begin{tabular}{| p{.16\textwidth} | p{.12\textwidth} | p{.12\textwidth} | p{.12\textwidth} |
                p{.12\textwidth} | p{.12\textwidth} | p{.12\textwidth} |} \hline
DV / Variable & treatment & treatment x polarization & 
  treatment x turnout & treatment x WERC & polarization & 
  WERC \\ \hline
Contested Race & + & + & null & + & null & null \\ \hline
Incumbent Defeat & + & + & + & - & + & - \\ \hline 
Blais-Lago & + & + & null & + & + & - \\ \hline
Turnout & + & + & + & + & null & - \\ \hline
Rolloff & - & - & - & - & null & + \\ \hline
\end{tabular}
\end{small}
\end{center}
\end{table}

If there is no impact on voter turnout in the wake of such a broad expansion of 
school board power over an issue as polarizing as collective bargaining rights 
for local employees, we would expect smaller policy shocks to have no effect either. 
This would represent a rejection of the applicability of information theory to 
explain turnout in low-salience non-partisan elections. This would also provide 
evidence in support of dissatisfaction theory - with heightened stakes for board 
policy preferences.\footnote{One concern might be that the polarization was so 
extreme and the state so saturated with negative campaigning of all forms that 
voter turnout was suppressed even in the case of spring school board elections 
\citep{NegativeCamp1999}.} This follows along the work of \citet{Lassen2005} who leveraged an exogenous shock 
of an information campaign in some electoral districts and found that 
increasing voters' information also produced a sizeable effect on the propensity 
to vote. 
% 
% \begin{table}[h!]
% \begin{center}
% \begin{small}
% \caption{Theories of Turnout and Expected Evidence: Causal}
% \label{turnoutH2}
% \begin{tabular}{| p{.15\textwidth} | p{.2\textwidth} | p{.6\textwidth} |}
% \hline
% \textbf{Theory}  & \textbf{Citation} & \textbf{Expected Finding} \\ \hline
% Information theory  & \citet{Matsusaka} & Large turnout increases after passage of Act 10\\ \hline
% Dissatisfaction theory & \citet{RefWorks:297,RefWorks:271} & Large turnout increase after Act 10 \\ \hline
% \end{tabular}
% \end{small}
% \end{center}
% \end{table}



The 2011 election was also marked by a highly contested statewide Supreme Court 
election and the ultimate effect of Act 10 was in doubt due to multiple legal 
challenges. By the 2012 election, Act 10 had been ruled constitutional and there 
was no state supreme court seat up for election. 


Unfortunately, the present study cannot distinguish between these two mechanism. 
More to the point, the study is limited by the reality that though school boards 
were given this freedom, it came coupled with historical cuts in state aid and 
a freeze on school district revenue limits. In practice this meant that though 
compensation policy may have been freed up, school boards had very little 
flexibility to innovate under such fiscal constraint. In some sense then, this 
leaves the elections post Act 10 as really a referendum on the opinion of voters 
and communities on both the changes to collective bargaining, but also reductions 
in school funding. 





\section{Data}

The data in this chapter is drawn from a unique collection of school board election 
results in Wisconsin school districts from 2002-2012. In addition to the election 
results from over 75\% of Wisconsin school districts, administrative records are 
incorporated to include annual measures of school districts on fiscal, political, 
demographic, and educational dimensions.

\subsection{Dependent Variables}

In this section I outline the key dependent variables for this investigation. 
Broadly, I am looking for evidence of the causal impact of state level policy 
shocks on the behavior of both candidates and voters. For candidates, I look 
for a change in the patterns of candidate contestation and seat competitiveness 
after the passage of Act 10 and the granting of additional powers to school boards. 
For voters, I look for changes in voter turnout and decreases in voter rolloff. 

<<minorContestPlot, fig.cap="Polarization and Contestation - Minor Contestation", out.height='3.18in'>>=
plotdf <- dist_turn[dist_turn$year > 2006, ]

qplot(contestMinor, RecallPolarization, data = plotdf, geom = 'boxplot') + 
  facet_wrap(~year) +
  scale_y_continuous() +
  theme_dpi(base_size=10) + coord_flip() + 
  labs(x= "Minor Contestation", y = "Polarization from 2012 Gov. Recall")
@


<<serContestPlot, fig.cap="Polarization and Contestation - Serious Contestation", out.height='3.18in'>>=
qplot(contestSer, RecallPolarization, data = plotdf, geom = 'boxplot') + 
  facet_wrap(~year) +
  scale_y_continuous() +
  theme_dpi(base_size=10) + coord_flip()+ 
  labs(x= "Serious Contestation", y = "Polarization from 2012 Gov. Recall")
@

Figures \ref{fig:minorContestPlot} and \ref{fig:serContestPlot} show the relationship 
between the community polarization in the Gubernatorial recall vote and contestation. 
There appears to be consistently little difference in the distribution of 
polarization between districts with contested and uncontested races across the 
years. 

Figure \ref{fig:blPlot} explores this same relationship but for the continuous 
measure of seat competitiveness -- the Blais-Lago quotient. Here there is a pattern 
of elevated contestation in 2011, and an increase in competitiveness, a lower 
B-L quotient, as seat polarization increases in year 2012. There is a similar 
pattern, though weaker in 2007 and 2010 as well. 

<<blPlot, fig.cap="Polarization and Seat Competitiveness">>=
plotdf <- dist_turn[dist_turn$year > 2006, ]
plotdf <- plotdf[!is.na(plotdf$turnout), ]
plotdf <- plotdf[plotdf$turnout < 0.8, ]
qplot(RecallPolarization, minBlaisLago, data = plotdf) + 
  facet_wrap(~year) + geom_smooth(method = 'lm', aes(group = 1)) +
  scale_y_continuous() +
  theme_dpi()+ 
  labs(y= "Seat Competitiveness", x = "Polarization from 2012 Gov. Recall")
@

Figures \ref{fig:turnoutPlot1} and \ref{fig:turnoutPlot2} show the relationship 
between polarization and school board turnout and voter rolloff. In 2011 and 2012 
there appears to be a negative relationship between increasing polarization and 
decreased turnout. For rolloff, the relationship appears to be the same across 
all the years. 

<<turnoutPlot1, fig.cap="Polarization and School Board Turnout">>=
qplot(RecallPolarization, turnout, data = plotdf, alpha = I(0.6)) + 
  facet_wrap(~year) + geom_smooth(method='lm') +
  scale_y_continuous(label=percent) +
  theme_dpi() + 
  labs(y = "School Board Turnout", x = "Polarization from 2012 Gov. Recall")
@

<<turnoutPlot2, fig.cap="Polarization and Spring Rolloff">>=
qplot(RecallPolarization, turnoutDiff, data = plotdf, alpha = I(0.6)) + 
  geom_smooth(method='lm') + 
   facet_wrap(~year) + 
   scale_y_continuous(label = percent) +
   theme_dpi() + labs(x= "Polarization from 2012 Gov. Recall", "School Board Rolloff")

# qplot(RecallPolarization, turnoutDiff/topTicketTurnoutSpring, data =plotdf) + 
#   geom_smooth(method = "lm") + 
#    facet_wrap(~year) + scale_x_continuous(label = percent) + 
#    scale_y_continuous(label = percent) +
#    theme_dpi()
@


\subsection{New Measures}

An additional advantage of this exogenous shock for the study of school board 
elections is that it creates three unique measures available statewide to peer 
into the preferences of communities. First, the level of polarization in the 
community in the recall election of Scott Walker. The result of this election can 
be seen largely as an opinion poll of voters on the issues of Act 10 and education 
funding in the state -- the two largest issues in the campaign.\footnote{While some have 
argued that another issue, the legitimacy of recalling the Governor in the first 
place was also important, this may also be a reflection on how strongly those 
voters felt about Act 10 in the first place.} All else equal, more polarized 
communities should exhibit greater contestation and turnout in school board 
elections due to the deeper conflict over the best way to manage public schools. 

A second measure that arises from this period is the level of turnout for the 
recall election itself. As with any election, voters without a strong preference 
either way were able to stay home. What's more, the election was at an unconventional 
time -- neither during the fall or the spring general election. Turnout was specifically 
driven by a desire to express support or opposition to the Governor. As such, 
it can be seen as an indication of the intensity with which a community was in 
favor of or against the policies of the Governor. \footnote{The recall election 
took place on June $5^{th}$, 2012. Turnout was 57.4\% with 2,516,065 voters 
casting votes for Governor out of a voting age population of 4,378,741. For more 
information see \url{http://gab.wi.gov/sites/default/files/Statewide\%20Percentage\%20Results_6.5.12\%20Recall\%20Election\_PRE\%20SEN21\%20RECOUNT.pdf}}

A final measure was created by the mechanics of Act 10 itself. Act 10 required 
public employee unions to recertify through an election process. Over the next 
few years all public employee unions in Wisconsin held recertification elections. 
Recertification required unions to hold elections and that a majority of all 
members, not just of those who voted, must vote in favor of recertifying for 
the union to continue to operate. The results of these elections -- the margin 
by which the union recertified -- can be seen as a measure of latent union 
strength. While the vast majority of unions recertified, in many cases the 
elections were close. 

\subsection{Independent Variables}

In addition to the suite of independent variables found in Chapters \ref{chap:candidacy} 
and \ref{chap:turnout}, this chapter features some additional key dependent variables 
drawn from results of Wisconsin's historic recall election. 

Figure \ref{fig:ivPlot1} shows the relationship between recall polarization and 
other variables for the year 2012. THe relationship between fall and recall election 
turnout and polarization is virtually identical. The top right panel shows the 
relationship between recall polarization and the Democratic share of the most 
recent presidential two-party vote - aside from a handful of outliers it follows 
in the expected direction. Finally, spring election turnout is fairly similar to 
the other turnout variables, but at a lower level with about half the turnout 
on average of the other elections. 

<<ivPlot1, fig.cap="Polarization and Other Variables">>=
plotdf <- dist_turn[dist_turn$year == 2012, ]

p1 <- qplot(RecallPolarization, GovTurnout_recall, data = plotdf) + 
  geom_smooth(method = 'lm') + 
   facet_wrap(~year) + 
   scale_y_continuous(label = percent) +
   theme_dpi() + labs(x= "Polarization from 2012 Gov. Recall", y="Recall Turnout")

p2 <- qplot(RecallPolarization, presTwoPartyShareDem, data = plotdf) + 
  geom_smooth(method = 'lm') + 
   facet_wrap(~year) + 
   scale_y_continuous(label = percent) +
   theme_dpi() + labs(x= "Polarization from 2012 Gov. Recall", y="Pres. Two Party Dem Share")

p3 <- qplot(RecallPolarization, recentFallTurnout, data = plotdf) + 
  geom_smooth(method = 'lm') + 
   facet_wrap(~year) + 
   scale_y_continuous(label = percent) +
   theme_dpi() + labs(x= "Polarization from 2012 Gov. Recall", y="Recent Fall Turnout")

p4 <- qplot(RecallPolarization, topTicketTurnoutSpring, data = plotdf) + 
  geom_smooth(method = 'lm') + 
   facet_wrap(~year) + 
   scale_y_continuous(label = percent) +
   theme_dpi() + labs(x= "Polarization from 2012 Gov. Recall",y= "Spring 2012 Turnout")

grid.arrange(p1, p2, p3, p4)
@

Figure \ref{fig:ivPlot2} explores the relationship between recall polarization 
and demographic variables to understand the ways party-polarization in the recall 
is similar to or different than partisan polarization in other elections. In the 
top left there is a strong relationship between the logged median income and 
polarization with higher polarization more strongly associated with lower income. 
Polarization appears to be consistent across the size of the Voting Age Population 
(VAP). There is a slight increase in polarization as the percentage of VAP over 
65 increases. 

<<ivPlot2, fig.cap="Polarization and Population Control Variables">>=
p1 <- qplot(median_incomeLOG, RecallPolarization, data = plotdf) + 
  geom_smooth(method = 'lm') + 
   facet_wrap(~year) + 
   scale_x_continuous(limits = c(9.5, 11.5)) + scale_y_continuous(limits=c(0, 100)) +
   theme_dpi() + labs(y= "Polarization from 2012 Gov. Recall", x= "Median Income (log)")

p2 <- qplot(VAP_adjLOG, RecallPolarization, data = plotdf) + 
  geom_smooth(method = 'lm') + 
   facet_wrap(~year) + 
   scale_x_continuous() +
   theme_dpi() + labs(y= "Polarization from 2012 Gov. Recall", x= "VAP (log)")

p3 <- qplot(PerBachelorOrAbove, RecallPolarization, data = plotdf) + 
  geom_smooth(method = 'lm') + 
   facet_wrap(~year) + 
   scale_x_continuous(label = percent) +
   theme_dpi() + labs(y= "Polarization from 2012 Gov. Recall", x="Per Bach. +")


p4 <- qplot(per65o, RecallPolarization, data = plotdf) + 
  geom_smooth(method = 'lm') + 
   facet_wrap(~year) + 
   scale_x_continuous(label = percent) +
   theme_dpi() + labs(y= "Polarization from 2012 Gov. Recall", x="% VAP 65+")

grid.arrange(p1, p2, p3, p4)
@

\subsubsection{WERC Elections}

This chapter introduces a new data source, the results of union certification 
elections. The Wisconsin Employment Relations Commission (WERC) maintains 
records of the 
annual recertification of unions. I use WERC records from each year following 
the passage of Act 10. After Act 10, unions in school districts had to recertify 
in waves as their existing union contracts expired. I take WERC election results 
from 2011, 2012, 2013, and 2014. After recertifying the first time, unions must 
hold an annual recertification election. I collapse the recertifcation elections 
for all unions in the district available in all years as a measure of union 
strength over time. I explore two separate measures of union strength -- the 
turnout in all union elections in the district, and turnout in teacher union 
only elections. 

Turnout is a strong proxy for union strength because such vote records are public 
record. % explain this


Figure \ref{fig:ivPlot3} shows the relationship between independent variables and 
the turnout in school district union certification elections after the passage 
of Act 10. Polarization is slightly negatively related with WERC turnout. 
Median income is slightly positively related with WERC turnout. VAP and \% of 
VAP over 65 are not really related to this. 

<<ivPlot3, fig.cap = "Polarization and WERC Elections">>=
p1 <- qplot(RecallPolarization, turnout_overall_werc, data = plotdf) + 
  geom_smooth(method='lm') + 
  facet_wrap(~year) + 
  scale_y_continuous(label = percent) + theme_dpi() + 
  labs(y = "WERC Election Turnout", x = "Polarization from 2012 Gov. Recall")

p2 <- qplot(median_incomeLOG, turnout_overall_werc, data = plotdf) + 
  geom_smooth(method='lm') + 
  facet_wrap(~year) + 
  scale_y_continuous(label = percent) + theme_dpi() + 
  scale_x_continuous(limits = c(9.5, 11.5)) +
  labs(y = "WERC Election Turnout", x = "Median Income Log")

p3 <- qplot(per65o, turnout_overall_werc, data = plotdf) + 
  geom_smooth(method='lm') + 
  facet_wrap(~year) + 
  scale_y_continuous(label = percent) + theme_dpi() + 
  scale_x_continuous(label = percent) +
  labs(y = "WERC Election Turnout", x = "% VAP 65+")

p4 <- qplot(VAP_adjLOG, turnout_overall_werc, data = plotdf) + 
  geom_smooth(method = 'lm') + 
   facet_wrap(~year) + 
   scale_x_continuous() + scale_y_continuous(label = percent) +
   theme_dpi() + labs(y= "WERC Election Turnout", x= "VAP (log)")

grid.arrange(p1, p2, p3, p4)
@


\clearpage



\section{Methods}

I now describe the models fit to the data and how to understand parameter. 

\subsection{Causal Inference}

Extraordinary claims require extraordinary evidence, and there is no more 
extraordinary claim a quantitative analyst can make than causality from 
observational data. To credibly claim that the estimate of the effect of Act 10 
and the power granted to school boards, I must demonstrate both how this impact 
is exogenous and how I will operationalize it into a variable. Above, I have 
already described how the events surrounding the passage of Act 10 were 
unforeseen by the electorate and therefore not endogenous to school board 
elections post Act 10. 

To operationalize this exogenous shock I code all observations that occur after 
the passage of Act 10 as having a treatment condition of 1, and all of those 
observations in periods before Act 10 as having a treatment condition of 0. If 
this was a randomized experiment and exposure to Act 10 had been randomly 
distributed to school districts and years, I could stop and simply compute 
the average levels of the dependent variables for these two groups and perform 
a t-test. However, as the prior chapters have shown, there exist substantial observable characteristics that affect candidate and voter participation. Not 
taking these variables into account risks allowing them to confound the 
estimation of the treatment effect and bias estimates away from the true 
impact \cite{gelhill}. 

Though school districts in Wisconsin were not randomly assigned to greater power 
and more engaged voters at different time periods, they were all assigned to this 
treatment at exactly the same moment with perfect fidelity. This eliminates one 
potential bias to estimating the causal impact of the treatment -- assignment 
bias. Now, by comparing districts to themselves pre and post assignment, we can 
be more sure that we are picking up the impact of the treatment. 

\subsection{Modeling Strategy}

I use multiple methods to triangulate the causal impact under different 
identifying assumptions. Leveraging the panel nature of my data, I can use 
two different methods to control for unobservable characteristics in the 
data. Using a lagged dependent variable I can control for time-variant 
unobservables that have the potential to bias causal estimates. Using unit 
fixed effects, for school districts, I can control for time-invariant 
unobservable characteristics. \citet{mhecon} demonstrate how under certain 
assumptions a lagged dependent variable and an individual fixed effect model 
can serve as a lower and upper bounds on the causal effect respectively. 


However, I still need to control for the effects that lead to variation in 
participation from election to election that are observable. To do this, 
and to make comparisons within districts, I employ a fixed effect strategy.


The equation below depicts this approach with the \emph{i}'s representing 
individual observations and the \emph{j}'s representing the individual 
districts in the sample. $\lambda$ represents the conditional estimate 
of the treatment, taking into account the within district variation and 
conditional on the control variables in $X_{ij}$. 

\begin{align*} 
y_{it} &= \alpha + \gamma_{i} + \beta X_{it} + \lambda T_{it} + \epsilon_{it}  \\ 
\end{align*}

For robustness, I also provide results using district fixed effect estimation 
and clustered standard errors (at the school district level) in the Appendix. 

\subsection{Threats to Validity}

Claims of causality rest on assumptions. In addition to the assumption that the 
passage of Act 10 was exogenous, unforeseen, and universal, this approach also 
assumes that all confounding covariates are observable and included in the model 
and that no omitted variables may bias the estimation of the treatment effect 
\cite{gelhill}. In practice, this assumption is not empirically verifiable. I 
argue that instead that the treatment effect is a valid estimate given the 
inclusion of terms to capture within district variance, a lagged 
dependent variable, and substantively important predictors of 
each of the dependent variables as demonstrated in previous chapters. 

% Citations: Shadish and Cook


% TODO: Describe a lagged observational model
% TODO: Difference in difference strategy
% TODO: Interrupted time series with district random effects




\section{Results}

I organize the results as follows. In the first section, I review the results 
for the models that leverage the years 2011 and 2012 as treated by a causal 
shock and I fit lagged time models and differences-in-differences estimates 
of the impact of Act 10 across five distinct measures of actualized democracy -- 
contestation, competitiveness, incumbent defeat, voter turnout, and voter 
rolloff. In the next section, I then step away from the causal framework and 
fit longitudinal models which seek to explore evidence, if any, that this causal 
impact was mediated. 

\subsection{Causal Estimates}

I provide three sets of results for each dependent variable. The first is a 
regression with a lagged dependent variable and demographic controls, the second 
is a differences in differences estimate, and the third is a difference in 
differences estimate with district level random effects.\footnote{I tested the 
models on a restricted sample with only years after 2007, but this had no 
substantive impact on the results.}

%tab:causMinorCon
<<contestDID, eval=TRUE, results = 'hide'>>=
library(lme4)
library(optimx)
ctrl2 <- glmerControl(optimizer = "optimx", calc.derivs = FALSE, 
                     optCtrl = list(method = "nlminb", starttests = FALSE, 
                                    kkt = FALSE, maxit = 10000))
ctrl <- glmerControl(optimizer = "Nelder_Mead", calc.derivs = FALSE)

outdata <- dist_turn[, c("distid", "year", "contestMinor", "VAP_adjLOG_sq", 
                         "VAP_adjLOG", "per65o", "NonPublicPupilPer", 
                         "incumShare", "teachShareofVoters", 
                         "fallTurnout", "nraces", "schoolMillShare", "OOH_share",
                         "PerBachelorOrAbove", 
                         "PROPERTYTAX_REV_SHARE", "minBlaisLago", "per_white_all",
                         "GovTurnout_recall", "RecallPolarization", "locale2", 
                         "econ_disadv_per")]

preTreat <- outdata[outdata$year <= 2010,]
preTreat$year <- preTreat$year + 1
names(preTreat) <- paste(names(preTreat), "lag", sep = "_")

# Repeat 2010 data as pre-treatment for 2012
tmp <- preTreat[preTreat$year_lag == 2011,]
tmp$year_lag <- 2012
preTreat <- rbind(preTreat, tmp)
rm(tmp)

outdata <- outdata[, c("contestMinor", "distid", "year")]
outdata <- merge(outdata, preTreat, by.y = c("distid_lag", "year_lag"), 
                 by.x = c("distid", "year"))
outdata$treatmentDose <- ifelse(outdata$year >= 2011, abs(outdata$year - 2013), 0)
outdata$treatmentFactor <- ifelse(outdata$year >= 2011, 1, 0)
outdata$treatmentDiff <- ifelse(outdata$year >= 2011, abs(outdata$year - 2010), 0)
outdata$treatmentDiff <- factor(outdata$treatmentDiff)
partialPanel <- names(table(outdata$distid)[table(outdata$distid) == 1])
outdata <- outdata[!outdata$distid %in% partialPanel, ]

lagModcontest <- glm(contestMinor ~ contestMinor_lag + treatmentDiff + 
                       VAP_adjLOG_sq_lag + incumShare_lag +
             VAP_adjLOG_lag + per65o_lag + nraces_lag + OOH_share_lag + 
               PerBachelorOrAbove_lag +  locale2_lag, data = outdata, 
             family = "binomial")
lagModcontestSE <- get_CL_vcov(lagModcontest, outdata$distid)
lagModcontest$se <- sqrt(diag(lagModcontestSE))

DIDmodContest <- glm(contestMinor ~ contestMinor_lag * treatmentDiff + 
                       VAP_adjLOG_sq_lag + incumShare_lag + 
             VAP_adjLOG_lag + per65o_lag + nraces_lag + OOH_share_lag +  
               PerBachelorOrAbove_lag +
             locale2_lag, data = outdata, family = "binomial")
DIDmodContestSE <- get_CL_vcov(DIDmodContest, outdata$distid)
DIDmodContest$se <- sqrt(diag(DIDmodContestSE))

FEmodContest <- glm(contestMinor ~ treatmentDiff + nraces_lag +
                      incumShare_lag + distid, 
                    data = outdata, family = "binomial")
FEmodContest$se <- sqrt(diag(get_CL_vcov(FEmodContest, outdata$distid)))


# 
# MermodContest <- glmer(contestMinor ~ contestMinor_lag * treatmentDiff + 
#                          VAP_adjLOG_sq_lag + incumShare_lag + 
#              VAP_adjLOG_lag + per65o_lag + nraces_lag + OOH_share_lag +  
#                PerBachelorOrAbove_lag + locale2_lag + (1|distid), 
#              data = outdata, family = "binomial", control = ctrl)

# causMinorConTab <- apsrtable(lagModcontest, DIDmodContest, 
#                              MermodContest, se = "robust", 
#           model.names = c("Lag", "Diff in Diff", "Multilevel"), 
#           stars = "default", 
#           caption = "Causal Estimates of Act 10 Period on Minor Contestation", 
#           label = "tab:causMinorCon", notes = list(stars.note), digits = 3, 
#           Sweave = TRUE)

omitNote <- "Fixed effect model includes district fixed effects - not reported."
causMinorConTab <- apsrtable(lagModcontest, DIDmodContest, FEmodContest, 
                             se = "robust", 
          stars = "default", digits = 3, model.names = c("Lag", "DnD", "FE"), 
          caption = "Causal Estimates of Act 10 Period on Contestation", 
          label = "tab:causBL", notes = list(stars.note, omitNote), 
          Sweave = TRUE, 
           omitcoef=list("distid", 
                         expression(grep("distid", coefnames, value=TRUE))))

@


%tab:causSerCon
\begin{small}
<<contestDID2, eval=TRUE, results = 'asis'>>=
outdata <- dist_turn[, c("distid", "year", "contestSer", "VAP_adjLOG_sq", 
                         "VAP_adjLOG", "per65o", "NonPublicPupilPer", 
                         "incumShare", "teachShareofVoters", 
                         "fallTurnout", "nraces", "schoolMillShare", "OOH_share",
                         "PerBachelorOrAbove", 
                         "PROPERTYTAX_REV_SHARE", "minBlaisLago", "per_white_all",
                         "GovTurnout_recall", "RecallPolarization", "locale2", 
                         "econ_disadv_per")]

preTreat <- outdata[outdata$year <= 2010,]
preTreat$year <- preTreat$year + 1
names(preTreat) <- paste(names(preTreat), "lag", sep = "_")

# Repeat 2010 data as pre-treatment for 2012
tmp <- preTreat[preTreat$year_lag == 2011,]
tmp$year_lag <- 2012
preTreat <- rbind(preTreat, tmp)
rm(tmp)

outdata <- outdata[, c("contestSer", "distid", "year")]
outdata <- merge(outdata, preTreat, by.y = c("distid_lag", "year_lag"), 
                 by.x = c("distid", "year"))
outdata$treatmentDose <- ifelse(outdata$year >= 2011, abs(outdata$year - 2013), 0)
outdata$treatmentFactor <- ifelse(outdata$year >= 2011, 1, 0)
outdata$treatmentDiff <- ifelse(outdata$year >= 2011, abs(outdata$year - 2010), 0)
outdata$treatmentDiff <- factor(outdata$treatmentDiff)

partialPanel <- names(table(outdata$distid)[table(outdata$distid) == 1])
outdata <- outdata[!outdata$distid %in% partialPanel, ]


lagModcontest2 <- glm(contestSer ~ contestSer_lag + treatmentDiff + 
                        VAP_adjLOG_sq_lag + incumShare_lag +
             VAP_adjLOG_lag + per65o_lag + nraces_lag + OOH_share_lag + 
               PerBachelorOrAbove_lag +  locale2_lag, data = outdata, 
             family = "binomial")
lagModcontestSE <- get_CL_vcov(lagModcontest2, outdata$distid)
lagModcontest2$se <- sqrt(diag(lagModcontestSE))

DIDmodContest2 <- glm(contestSer ~ contestSer_lag * treatmentDiff + 
                        VAP_adjLOG_sq_lag + incumShare_lag + 
             VAP_adjLOG_lag + per65o_lag + nraces_lag + OOH_share_lag +  
               PerBachelorOrAbove_lag +
             locale2_lag, data = outdata, family = "binomial")
DIDmodContestSE <- get_CL_vcov(DIDmodContest2, outdata$distid)
DIDmodContest2$se <- sqrt(diag(DIDmodContestSE))

FEmodContest2 <- glm(contestSer ~ treatmentDiff + nraces_lag + incumShare_lag + 
                       distid, data = outdata, family = "binomial")
FEmodContest2$se <- sqrt(diag(get_CL_vcov(FEmodContest2, outdata$distid)))

# MermodContest2 <- glmer(contestSer ~ contestSer_lag * treatmentDiff + 
#                           VAP_adjLOG_sq_lag + incumShare_lag +
#              VAP_adjLOG_lag + per65o_lag + nraces_lag + OOH_share_lag +  
#                PerBachelorOrAbove_lag + locale2_lag + (1|distid), 
#              data = outdata, family = "binomial", control = ctrl)
# 
# apsrtable(lagModcontest2, DIDmodContest2, MermodContest2, se = "robust", 
#           model.names = c("Lag", "Diff in Diff", "Multilevel"), 
#           stars = "default", 
#           caption = "Causal Estimates of Act 10 Period on Serious Contestation", 
#           label = "tab:causSerCon", notes = list(stars.note), digits = 3, 
#           Sweave = TRUE)

apsrtable(lagModcontest2, DIDmodContest2, FEmodContest2, 
                             se = "robust", 
          stars = "default", digits = 3, model.names = c("Lag", "DnD", "FE"), 
          caption = "Causal Estimates of Act 10 Period on Contestation", 
          label = "tab:causBL", notes = list(stars.note, omitNote), 
          Sweave = TRUE, 
           omitcoef=list("distid", 
                         expression(grep("distid", coefnames, value=TRUE))))

@
\end{small}

%tab:causBL
\begin{small}

<<blDIDandLag, eval=TRUE, results = 'asis'>>=
outdata <- dist_turn[, c("distid", "year", "turnout", "VAP_adjLOG_sq", "VAP_adjLOG", 
                         "per65o", "NonPublicPupilPer", "incumShare", 
                         "teachShareofVoters", 
                         "fallTurnout", "nraces", "schoolMillShare", "OOH_share",
                         "PerBachelorOrAbove", 
                         "PROPERTYTAX_REV_SHARE", "minBlaisLago", "per_white_all",
                         "GovTurnout_recall", "RecallPolarization", "locale2", 
                         "econ_disadv_per")]

preTreat <- outdata[outdata$year <= 2010,]
preTreat$year <- preTreat$year + 1
names(preTreat) <- paste(names(preTreat), "lag", sep = "_")

# Repeat 2010 data as pre-treatment for 2012
tmp <- preTreat[preTreat$year_lag == 2011,]
tmp$year_lag <- 2012
preTreat <- rbind(preTreat, tmp)
rm(tmp)

outdata <- outdata[, c("minBlaisLago", "distid", "year")]
outdata <- merge(outdata, preTreat, by.y = c("distid_lag", "year_lag"), 
                 by.x = c("distid", "year"))
outdata$treatmentDose <- ifelse(outdata$year >= 2011, abs(outdata$year - 2013), 0)
outdata$treatmentFactor <- ifelse(outdata$year >= 2011, 1, 0)
outdata$treatmentDiff <- ifelse(outdata$year >= 2011, abs(outdata$year - 2010), 0)
outdata$treatmentDiff <- factor(outdata$treatmentDiff)
outdata$minBlaisLago <- ifelse(outdata$minBlaisLago == 0, 0.003, outdata$minBlaisLago)
outdata$minBlaisLago_lag <- ifelse(outdata$minBlaisLago_lag == 0, 0.003, 
                                   outdata$minBlaisLago_lag)
outdata$minBlaisLago <- log(outdata$minBlaisLago)
outdata$minBlaisLago_lag <- log(outdata$minBlaisLago_lag)
partialPanel <- names(table(outdata$distid)[table(outdata$distid) == 1])
outdata <- outdata[!outdata$distid %in% partialPanel, ]

lagModBL <- lm(minBlaisLago ~ minBlaisLago_lag + treatmentDiff + 
                 VAP_adjLOG_sq_lag + incumShare_lag + 
             VAP_adjLOG_lag + per65o_lag + nraces_lag + OOH_share_lag + 
               PerBachelorOrAbove_lag + 
             locale2_lag, data = outdata)
lagModBLSE <- get_CL_vcov(lagModBL, outdata$distid)
lagModBL$se <- sqrt(diag(lagModBLSE))

DIDmodBL <- lm(minBlaisLago ~ minBlaisLago_lag * treatmentDiff + 
                 VAP_adjLOG_sq_lag + incumShare_lag + 
             VAP_adjLOG_lag + per65o_lag + nraces_lag + OOH_share_lag +  
               PerBachelorOrAbove_lag +
             locale2_lag, data = outdata)
DIDmodBLSE <- get_CL_vcov(DIDmodBL, outdata$distid)
DIDmodBL$se <- sqrt(diag(DIDmodBLSE))

FEmodBL <- lm(minBlaisLago ~ treatmentDiff +  nraces_lag + incumShare_lag +
                distid, 
              data = outdata)
FEmodBL$se <- sqrt(diag(get_CL_vcov(FEmodBL, outdata$distid)))

merModBL <- lmer(minBlaisLago ~ minBlaisLago_lag * treatmentDiff +
                   VAP_adjLOG_sq_lag + incumShare_lag + 
             VAP_adjLOG_lag + per65o_lag + nraces_lag + OOH_share_lag +  
               PerBachelorOrAbove_lag +
             locale2_lag + (1|distid), data = outdata)

# apsrtable(lagModBL, DIDmodBL, merModBL, se = "robust", 
#           model.names = c("Lag", "Diff in Diff"), stars = "default", 
#           caption = "Causal Estimates of Act 10 Period on Competitiveness", 
#           label = "tab:causBL", notes = list(stars.note), digits = 3, 
#           Sweave = TRUE)

plotPred <- predict(DIDmodBL, newdata = outdata, type = "response")
plotdf2 <- cbind(outdata, plotPred)


apsrtable(lagModBL, DIDmodBL, FEmodBL, se = "robust", stars = "default", 
          digits = 3, model.names = c("Lag", "DnD", "FE"), 
          caption = "Causal Estimates of Act 10 Period on Competitiveness", 
          label = "tab:causBL", notes = list(stars.note, omitNote), 
          Sweave = TRUE, 
           omitcoef=list("distid", 
                         expression(grep("distid", coefnames, value=TRUE))))

@

\end{small}

%tab:causID
\begin{small}

<<incdefDIDandLag, eval = TRUE, results = 'asis'>>=
outdata <- dist_turn[, c("distid", "year", "incDefeats", "VAP_adjLOG_sq", 
                         "VAP_adjLOG", 
                         "per65o", "NonPublicPupilPer", "incumShare", 
                         "teachShareofVoters", "fallTurnout", "nraces", 
                         "schoolMillShare", "OOH_share", "PerBachelorOrAbove", 
                         "PROPERTYTAX_REV_SHARE", "per_white_all",
                         "GovTurnout_recall", "RecallPolarization", "locale2", 
                         "econ_disadv_per")]

preTreat <- outdata[outdata$year <= 2010,]
preTreat$year <- preTreat$year + 1
names(preTreat) <- paste(names(preTreat), "lag", sep = "_")

# Repeat 2010 data as pre-treatment for 2012
tmp <- preTreat[preTreat$year_lag == 2011,]
tmp$year_lag <- 2012
preTreat <- rbind(preTreat, tmp)
rm(tmp)

outdata <- outdata[, c("incDefeats", "distid", "year")]
outdata <- merge(outdata, preTreat, by.y = c("distid_lag", "year_lag"), 
                 by.x = c("distid", "year"))

outdata$treatmentDose <- ifelse(outdata$year >= 2011, abs(outdata$year - 2013), 0)
outdata$treatmentFactor <- ifelse(outdata$year >= 2011, 1, 0)
outdata$treatmentDiff <- ifelse(outdata$year >= 2011, abs(outdata$year - 2010), 0)
outdata$treatmentDiff <- factor(outdata$treatmentDiff)
partialPanel <- names(table(outdata$distid)[table(outdata$distid) == 1])
outdata <- outdata[!outdata$distid %in% partialPanel, ]
outdata2 <- outdata[outdata$incumShare != max(outdata$incumShare) & 
                      outdata$incumShare != min(outdata$incumShare) & 
                      !is.na(outdata$incumShare_lag), ]

lagModID <- glm(incDefeats ~ incDefeats_lag + treatmentDiff + VAP_adjLOG_sq_lag + 
             VAP_adjLOG_lag + per65o_lag + nraces_lag + OOH_share_lag + 
               PerBachelorOrAbove_lag + incumShare_lag + 
             locale2_lag, data = outdata, family = "binomial")

lagModIDSE <- get_CL_vcov(lagModID, outdata$distid)
lagModID$se <- sqrt(diag(lagModIDSE))

DIDmodID <- glm(incDefeats ~ incDefeats_lag * treatmentDiff + VAP_adjLOG_sq_lag + 
             VAP_adjLOG_lag + per65o_lag + nraces_lag + OOH_share_lag +  
               PerBachelorOrAbove_lag + incumShare_lag +
             locale2_lag, data = outdata, family = "binomial")
DIDmodIDSE <- get_CL_vcov(DIDmodID, outdata$distid)
DIDmodID$se <- sqrt(diag(DIDmodIDSE))

FEmodID <- glm(incDefeats ~ treatmentDiff + nraces_lag +   
               incumShare_lag +distid, 
             family = "binomial", data = outdata)
FEmodID$se <- sqrt(diag(get_CL_vcov(FEmodID, outdata$distid)))

# merModID <- glmer(incDefeats ~ incDefeats_lag * treatmentDiff + VAP_adjLOG_sq_lag + 
#              VAP_adjLOG_lag + per65o_lag + nraces_lag + OOH_share_lag +  
#                PerBachelorOrAbove_lag + incumShare_lag +
#              locale2_lag + (1|distid), data = outdata, family = "binomial")
# 
# apsrtable(lagModID, DIDmodID, merModID, se = "robust", 
#           model.names = c("Lag", "Diff in Diff", "Multilevel"), stars = "default", 
#           caption = "Causal Estimates of Act 10 Period on Incumbent Defeat", 
#           label = "tab:causID", notes = list(stars.note), digits = 3, 
#           Sweave = FALSE)

 apsrtable(lagModID, DIDmodID, FEmodID, se = "robust", stars = "default", 
          digits = 3, model.names = c("Lag", "DnD", "FE"), 
          caption = "Causal Estimates of Act 10 Period on Incumbent Defeat", 
          label = "tab:causID", notes = list(stars.note, omitNote), 
          Sweave = TRUE, 
           omitcoef=list("distid", 
                         expression(grep("distid", coefnames, value=TRUE))))
@

\end{small}

%tab:causTurn
\begin{small}
<<turnoutDIDandLag, eval=TRUE, results = 'asis'>>=
outdata <- dist_turn[, c("distid", "year", "turnout", "VAP_adjLOG_sq", 
                         "VAP_adjLOG", 
                         "PerBachelorOrAbove", "ImputedFlag", "median_incomeLOG", 
                         "per65o", "NonPublicPupilPer", "incumShare", 
                         "teachShareofVoters", 
                         "fallTurnout", "nraces", "schoolMillShare", "OOH_share",
                         "PROPERTYTAX_REV_SHARE", "per_white_all",
                         "GovTurnout_recall", "RecallPolarization", "locale2", 
                         "econ_disadv_per")]

outdata$ImputedFlag[is.na(outdata$ImputedFlag)] <- "No"
outdata$ImputedFlag <- ifelse(outdata$ImputedFlag == "Imputed2010", "Yes", "No")

preTreat <- outdata[outdata$year <= 2010,]
preTreat$year <- preTreat$year + 1
names(preTreat) <- paste(names(preTreat), "lag", sep = "_")

# Repeat 2010 data as pre-treatment for 2012
tmp <- preTreat[preTreat$year_lag == 2011,]
tmp$year_lag <- 2012
preTreat <- rbind(preTreat, tmp)
rm(tmp)

outdata <- outdata[, c("turnout", "ImputedFlag", "distid", "year")]
outdata <- merge(outdata, preTreat, by.y = c("distid_lag", "year_lag"), 
                 by.x = c("distid", "year"))
outdata$treatmentDose <- ifelse(outdata$year >= 2011, abs(outdata$year - 2013), 0)
outdata$treatmentFactor <- ifelse(outdata$year >= 2011, 1, 0)
outdata$treatmentDiff <- ifelse(outdata$year >= 2011, abs(outdata$year - 2010), 0)
outdata$treatmentDiff <- factor(outdata$treatmentDiff)
outdata <- outdata[!is.na(outdata$turnout_lag), ]
outdata <- outdata[!is.na(outdata$turnout), ]
outdata <- outdata[outdata$turnout > 0,]
outdata <- outdata[outdata$turnout_lag > 0,]
centr <- mean(outdata$turnout)
stddev <- sd(outdata$turnout)
outdata$outflag <- (outdata$turnout - centr) / stddev
outdata$outflag2 <- (outdata$turnout_lag - centr) / stddev
outdata <- outdata[outdata$outflag <= 5 & outdata$outflag >= -5,]
outdata <- outdata[outdata$outflag2 <= 5 & outdata$outflag2 >= -5,]
# outdata <- outdata[outdata$year > 2007, ]
outdata$turnout <- log(outdata$turnout)
outdata$turnout_lag <- log(outdata$turnout_lag)
partialPanel <- names(table(outdata$distid)[table(outdata$distid) == 1])
outdata <- outdata[!outdata$distid %in% partialPanel, ]


lagModturn <- lm(turnout ~ turnout_lag + treatmentDiff + VAP_adjLOG_sq_lag + 
             VAP_adjLOG_lag + per65o_lag + nraces_lag + OOH_share_lag + 
               median_incomeLOG_lag + ImputedFlag +
             locale2_lag + PerBachelorOrAbove_lag + fallTurnout_lag, 
             data = outdata)
lagModturnSE <- get_CL_vcov(lagModturn, outdata$distid)
lagModturn$se <- sqrt(diag(lagModturnSE))

DIDmodturn <- lm(turnout ~ turnout_lag * treatmentDiff + VAP_adjLOG_sq_lag + 
             VAP_adjLOG_lag + per65o_lag + nraces_lag + OOH_share_lag + 
               median_incomeLOG_lag+ ImputedFlag + 
             locale2_lag + PerBachelorOrAbove_lag + fallTurnout_lag, 
             data = outdata)
DIDmodturnSE <- get_CL_vcov(DIDmodturn, outdata$distid)
DIDmodturn$se <- sqrt(diag(DIDmodturnSE))

merModturn <- lmer(turnout ~ turnout_lag * treatmentDiff + VAP_adjLOG_sq_lag + 
             VAP_adjLOG_lag + per65o_lag + nraces_lag + OOH_share_lag + 
               median_incomeLOG_lag + ImputedFlag +
             locale2_lag + PerBachelorOrAbove_lag + fallTurnout_lag + 
               (1|distid), data = outdata)

FEmodTurn <- lm(turnout ~ treatmentDiff + VAP_adjLOG_sq_lag + 
                  VAP_adjLOG_lag + per65o_lag + nraces_lag + OOH_share_lag + 
                  median_incomeLOG_lag + ImputedFlag + locale2_lag + 
                  PerBachelorOrAbove_lag +
                  fallTurnout_lag + distid, data = outdata)
FEmodTurn$se <- sqrt(diag(get_CL_vcov(FEmodTurn, outdata$distid)))

# apsrtable(lagModturn, DIDmodturn, merModturn, se = "robust", 
#           model.names = c("Lag", "Diff in Diff", "Multilevel"), 
#           stars = "default", 
#           caption = "Causal Estimates of Act 10 Period on Turnout", 
#           label = "tab:causTurn", notes = list(stars.note), digits = 3, 
#           Sweave = TRUE)

 apsrtable(lagModturn, DIDmodturn, FEmodTurn, se = "robust", stars = "default", 
          digits = 3, model.names = c("Lag", "DnD", "FE"), 
          caption = "Causal Estimates of Act 10 Period on Turnout", 
          label = "tab:causTurn", notes = list(stars.note, omitNote), 
          Sweave = TRUE, 
           omitcoef=list("distid", 
                         expression(grep("distid", coefnames, value=TRUE))))

@
\end{small}

%tab:causRoll
\begin{small}
<<rolloffDIDandLag, eval=TRUE, results = 'asis'>>=
outdata <- dist_turn[, c("distid", "year", "turnoutDiff", "VAP_adjLOG_sq", 
                         "VAP_adjLOG", 
                         "PerBachelorOrAbove", "ImputedFlag", 
                         "median_incomeLOG", "per65o", "NonPublicPupilPer", 
                         "incumShare", "teachShareofVoters", 
                         "fallTurnout", "nraces", "schoolMillShare", "OOH_share",
                         "PROPERTYTAX_REV_SHARE", "per_white_all", "turnout", 
                         "GovTurnout_recall", "RecallPolarization", "locale2", 
                         "econ_disadv_per")]

outdata$ImputedFlag[is.na(outdata$ImputedFlag)] <- "No"
outdata$ImputedFlag <- ifelse(outdata$ImputedFlag == "Imputed2010", "Yes", "No")

preTreat <- outdata[outdata$year <= 2010,]
preTreat$year <- preTreat$year + 1
names(preTreat) <- paste(names(preTreat), "lag", sep = "_")

# Repeat 2010 data as pre-treatment for 2012
tmp <- preTreat[preTreat$year_lag == 2011,]
tmp$year_lag <- 2012
preTreat <- rbind(preTreat, tmp)
rm(tmp)

outdata <- outdata[, c("turnoutDiff", "ImputedFlag", "distid", "year")]
outdata <- merge(outdata, preTreat, by.y = c("distid_lag", "year_lag"), 
                 by.x = c("distid", "year"))

outdata$treatmentDose <- ifelse(outdata$year >= 2011, abs(outdata$year - 2013), 0)
outdata$treatmentFactor <- ifelse(outdata$year >= 2011, 1, 0)
outdata$treatmentDiff <- ifelse(outdata$year >= 2011, abs(outdata$year - 2010), 0)
outdata$treatmentDiff <- factor(outdata$treatmentDiff)
outdata <- outdata[!is.na(outdata$turnoutDiff), ]
outdata <- outdata[!is.na(outdata$turnoutDiff_lag), ]
centr <- mean(outdata$turnoutDiff)
stddev <- sd(outdata$turnoutDiff)
outdata$outflag <- (outdata$turnoutDiff - centr) / stddev
outdata$outflag2 <- (outdata$turnoutDiff_lag - centr) / stddev
outdata <- outdata[outdata$outflag <= 5 & outdata$outflag >= -5,]
outdata <- outdata[outdata$outflag2 <= 5 & outdata$outflag2 >= -5,]
partialPanel <- names(table(outdata$distid)[table(outdata$distid) == 1])
outdata <- outdata[!outdata$distid %in% partialPanel, ]


lagModroll <- lm(turnoutDiff ~ turnoutDiff_lag + treatmentDiff + 
                   VAP_adjLOG_sq_lag + 
             VAP_adjLOG_lag + per65o_lag + nraces_lag + OOH_share_lag + 
               median_incomeLOG_lag + ImputedFlag + 
             locale2_lag + PerBachelorOrAbove_lag + fallTurnout_lag, 
             data = outdata)
lagModrollSE <- get_CL_vcov(lagModroll, outdata$distid)
lagModroll$se <- sqrt(diag(lagModrollSE))

DIDmodroll <- lm(turnoutDiff ~ turnoutDiff_lag * treatmentDiff + 
                   VAP_adjLOG_sq_lag + 
             VAP_adjLOG_lag + per65o_lag + nraces_lag + OOH_share_lag + 
               median_incomeLOG_lag+ ImputedFlag +
             locale2_lag + PerBachelorOrAbove_lag + fallTurnout_lag, 
             data = outdata)
DIDmodrollSE <- get_CL_vcov(DIDmodroll, outdata$distid)
DIDmodroll$se <- sqrt(diag(DIDmodrollSE))

merModroll <- lmer(turnoutDiff ~ turnoutDiff_lag * treatmentDiff + 
                   VAP_adjLOG_sq_lag + 
             VAP_adjLOG_lag + per65o_lag + nraces_lag + OOH_share_lag + 
               median_incomeLOG_lag+ ImputedFlag +
             locale2_lag + PerBachelorOrAbove_lag + fallTurnout_lag + 
               (1|distid), data = outdata)

FEmodRoll <- lm(turnoutDiff ~ treatmentDiff  + 
                   VAP_adjLOG_sq_lag + 
             VAP_adjLOG_lag + per65o_lag + nraces_lag + OOH_share_lag + 
               median_incomeLOG_lag + ImputedFlag +
               PerBachelorOrAbove_lag + fallTurnout_lag +
               distid, data = outdata)
FEmodRoll$se <- sqrt(diag(get_CL_vcov(FEmodRoll, outdata$distid)))
# 
# apsrtable(lagModroll, DIDmodroll, merModroll, se = "robust", 
#           model.names = c("Lag", "Diff in Diff", "Multilevel"), 
#           stars = "default", 
#           caption = "Causal Estimates of Act 10 Period on Rolloff", 
#           label = "tab:causRoll", notes = list(stars.note), digits = 3, 
#           Sweave = TRUE)

apsrtable(lagModroll, DIDmodroll, FEmodRoll, se = "robust", stars = "default", 
          digits = 3, model.names = c("Lag", "DnD", "FE"), 
          caption = "Causal Estimates of Act 10 Period on Rolloff", 
          label = "tab:causRoll", notes = list(stars.note, omitNote), 
          Sweave = TRUE, 
           omitcoef=list("distid", 
                         expression(grep("distid", coefnames, value=TRUE))))
@
\end{small}

\begin{table}[h!]
\begin{center}
\begin{small}
\caption{Summary of Causal Relationship of Act 10 Reforms on Board Elections}
\label{tab:act10resSummary}
\begin{tabular}{| p{.24\textwidth} | p{.12\textwidth} | p{.12\textwidth} | 
      p{.24\textwidth} |} \hline
DV / Variable & expected & observed & evidence \\ \hline
Contested Race & + & null & no statistical significance, correct sign \\ \hline
Contesed Race (ser) & + & null & no statistical significance, correct sign on interaction \\ \hline
Incumbent Defeat & + & - & weakly negative, positive effect in diff-in-diff  \\ \hline 
Competitiveness & + & +  & weakly positive, weakly statistically significant \\ \hline
Turnout & + & - & diff in diff weakly negative, overall effect positive \\ \hline
Rolloff & - & null & correct sign, no statistical significance \\ \hline
\end{tabular}
\end{small}
\end{center}
\end{table}

Table \ref{tab:act10resSummary} summarizes the results in comparison to the 
expectations from Table \ref{tab:act10hypo}. Overall, there is some evidence 
of an effect of Act 10 on school board election activity. Specifically, the 
post-Act 10 period showed evidence of an increase in competitiveness, a 
decrease in turnout, and an increase in rolloff. 

<<bldiffindiff, fig.cap="Average Fitted Value over Realistic Value">>=
summPlot <- ddply(plotdf2, .(year), summarize, 
                  meanEff = mean(plotPred))

qplot(factor(year), exp(plotPred), data = plotdf2, geom = 'boxplot') + 
  geom_line(data = summPlot, aes(x = factor(year), y = exp(meanEff), group = 1)) + 
  theme_dpi() + 
  scale_y_sqrt(limits = c(0, 100)) + 
  labs(x = "Year", y = "Blais-Lago")
@

\clearpage

\subsection{Mediation Analysis}

While the results above can be interpreted as the causal estimate of the political 
upheaval surrounding Act 10 on democratic activity in school boards, questions 
remain. Most importantly, it is important to explore the potential for mediating 
factors on the causal estimate. To do this, I fit longitudinal models as above, 
but I include mediating factors as interactions with the treatment indicator. 

These mediating measures were observed post-treatment, but I argue that they 
can be interpreted as a consistent measure of school district attributes that 
existed pre-treatment. There is no empirical way to validate this assumption, but 
using this assumption allows me to explore a rich set of potential mediating 
factors to understand what conditions exacerbated or attenuated the actualization 
of political activity in school boards. 

I now analyze the impact of each mediating factor. 

\subsubsection{Polarization}

Polarization should matter. 

%tab:polarMed
\begin{small}
<<polarizationMediation, results = 'asis'>>=
outdata <- dist_turn[, c("distid", "year", "contestMinor", "contestSer", 
                         "VAP_adjLOG_sq", "turnout", "turnoutDiff", 
                         "RecallPolarization", "incDefeats", "ImputedFlag", 
                         "VAP_adjLOG", "per65o", "NonPublicPupilPer", 
                         "incumShare", "teachShareofVoters", 
                         "fallTurnout", "nraces", "schoolMillShare", "OOH_share",
                         "PerBachelorOrAbove", 
                         "PROPERTYTAX_REV_SHARE", "minBlaisLago", "per_white_all",
                         "GovTurnout_recall", "locale2", 
                         "econ_disadv_per")]

outdata$ImputedFlag[is.na(outdata$ImputedFlag)] <- "No"
outdata$ImputedFlag <- ifelse(outdata$ImputedFlag == "Imputed2010", "Yes", "No")

preTreat <- outdata[outdata$year <= 2010,]
preTreat$year <- preTreat$year + 1
names(preTreat) <- paste(names(preTreat), "lag", sep = "_")

# Repeat 2010 data as pre-treatment for 2012
tmp <- preTreat[preTreat$year_lag == 2011,]
tmp$year_lag <- 2012
preTreat <- rbind(preTreat, tmp)
rm(tmp)
outdata <- outdata[, c("contestMinor", "contestSer", "turnout", "turnoutDiff", 
                       "minBlaisLago", "incDefeats", "ImputedFlag", 
                       "distid", "year")]
outdata <- merge(outdata, preTreat, by.y = c("distid_lag", "year_lag"), 
                 by.x = c("distid", "year"))

outdata$treatment <- ifelse(outdata$year >= 2011, abs(outdata$year - 2013), 0)
outdata <- outdata[outdata$year > 2007, ]
outdata <- na.omit(outdata)
outdata <- outdata[!is.na(outdata$turnout_lag), ]
outdata <- outdata[!is.na(outdata$turnout), ]
outdata <- outdata[outdata$turnout > 0,]
outdata <- outdata[outdata$turnout_lag > 0,]
centr <- mean(outdata$turnout)
stddev <- sd(outdata$turnout)
outdata$outflag <- (outdata$turnout - centr) / stddev
outdata$outflag2 <- (outdata$turnout_lag - centr) / stddev
outdata <- outdata[outdata$outflag <= 5 & outdata$outflag >= -5,]
outdata <- outdata[outdata$outflag2 <= 5 & outdata$outflag2 >= -5,]
# outdata <- outdata[outdata$year > 2007, ]
outdata$turnout <- log(outdata$turnout)
outdata$turnout_lag <- log(outdata$turnout_lag)
outdata$minBlaisLago <- ifelse(outdata$minBlaisLago == 0, 0.003, outdata$minBlaisLago)
outdata$minBlaisLago_lag <- ifelse(outdata$minBlaisLago_lag == 0, 0.003, 
                                   outdata$minBlaisLago_lag)
outdata$minBlaisLago <- log(outdata$minBlaisLago)
outdata$minBlaisLago_lag <- log(outdata$minBlaisLago_lag)
outdata$incDefeats <- factor(outdata$incDefeats)
outdata$incDefeats_lag <- factor(outdata$incDefeats_lag)
library(arm)
nums <- sapply(outdata, is.numeric)
# nums["treatment"] <- FALSE
outdata[, nums] <- apply(outdata[, nums], 2, rescale)

simp1 <- glm(contestSer ~ contestSer_lag + treatment * RecallPolarization_lag, 
             data = outdata, family = 'binomial')
simp1$se <- sqrt(diag(get_CL_vcov(simp1, outdata$distid)))

simp2 <- glm(contestMinor ~ contestMinor_lag + treatment * RecallPolarization_lag, 
             data = outdata, family = 'binomial')
simp2$se <- sqrt(diag(get_CL_vcov(simp2, outdata$distid)))

simp3 <- lm(minBlaisLago ~ minBlaisLago_lag + treatment * RecallPolarization_lag, 
             data = outdata)
simp3$se <- sqrt(diag(get_CL_vcov(simp3, outdata$distid)))

simp4 <- lm(turnout ~ turnout_lag + treatment * RecallPolarization_lag + 
              ImputedFlag, 
             data = outdata)
simp4$se <- sqrt(diag(get_CL_vcov(simp4, outdata$distid)))

simp5 <- lm(turnoutDiff ~ turnoutDiff_lag + treatment * RecallPolarization_lag + 
              ImputedFlag, 
             data = outdata)
simp5$se <- sqrt(diag(get_CL_vcov(simp5, outdata$distid)))

simp6 <- glm(incDefeats ~ incDefeats_lag + treatment * RecallPolarization_lag, 
             data = outdata, family = "binomial")
simp6$se <- sqrt(diag(get_CL_vcov(simp6, outdata$distid)))

full1 <- glmer(contestMinor ~ contestMinor_lag + treatment + VAP_adjLOG_sq_lag + 
             VAP_adjLOG_lag + per65o_lag + nraces_lag + OOH_share_lag +  
               PerBachelorOrAbove_lag + locale2_lag + 
               treatment * RecallPolarization_lag + (1|distid), 
             data = outdata, family = "binomial", control = ctrl)

full2 <- glmer(contestSer ~ contestSer_lag + treatment + VAP_adjLOG_sq_lag + 
             VAP_adjLOG_lag + per65o_lag + nraces_lag + OOH_share_lag +  
               PerBachelorOrAbove_lag + locale2_lag + 
               treatment * RecallPolarization_lag + (1|distid), 
             data = outdata, family = "binomial", control = ctrl)

full3 <- lmer(minBlaisLago ~ minBlaisLago_lag + treatment + VAP_adjLOG_sq_lag + 
             VAP_adjLOG_lag + per65o_lag + OOH_share_lag +  nraces_lag +
               PerBachelorOrAbove_lag + locale2_lag + 
               treatment * RecallPolarization_lag + (1|distid), 
             data = outdata)

full4 <- lmer(turnout ~ turnout_lag + treatment + VAP_adjLOG_sq_lag + 
             VAP_adjLOG_lag + per65o_lag + OOH_share_lag +  nraces_lag +
               PerBachelorOrAbove_lag + locale2_lag + ImputedFlag +
               treatment * RecallPolarization_lag + (1|distid), 
             data = outdata)

full5 <- lmer(turnoutDiff ~ turnoutDiff_lag + treatment + VAP_adjLOG_sq_lag + 
             VAP_adjLOG_lag + per65o_lag + OOH_share_lag +  nraces_lag +
               PerBachelorOrAbove_lag + locale2_lag + ImputedFlag +
               treatment * RecallPolarization_lag + (1|distid), 
             data = outdata)

full6 <- glmer(incDefeats ~ incDefeats_lag + treatment + VAP_adjLOG_sq_lag + 
             VAP_adjLOG_lag + per65o_lag + OOH_share_lag +  nraces_lag +
               PerBachelorOrAbove_lag + locale2_lag + 
               treatment * RecallPolarization_lag + (1|distid), 
             data = outdata, family = "binomial")

apsrtable(simp1, simp3, simp4, simp5, simp6, se = "robust", digits = 3, 
          model.names = c("Ser. Cont.", "Compet.", 
                          "Turnout", "Rolloff", "Inc. Def."), 
          stars = "default", 
          caption = "Mediation Estimates of Polarization on Board Elections", 
          label = "tab:polarMed", notes = list(stars.note), Sweave = TRUE)

polarMedTable <- apsrtable(full1, full3, full4, full5, full6, 
                           se = "robust", digits = 3, 
          model.names = c("Ser. Cont.", "Compet.", 
                          "Turnout", "Rolloff", "Inc. Def."), 
caption = "Mediation Estimates of Polarization on Board Elections - Multilevel Models",           label = "tab:polarMedHLM", notes = list(stars.note), Sweave = TRUE, 
          stars = "default")
@
\end{small}

% Only evidence of mediation on turnout, where higher polarization attenuates the 
% turnout boost post-recall

\subsubsection{Union Strength}

%tab:unionMed
\begin{small}
<<unionStrength>>=
outdata <- dist_turn[, c("distid", "year", "contestMinor", "contestSer", 
                         "VAP_adjLOG_sq", "turnout", "turnoutDiff", 
                         "RecallPolarization", "incDefeats", "ImputedFlag", 
                         "VAP_adjLOG", "per65o", "NonPublicPupilPer", 
                         "incumShare", "teachShareofVoters", 
                         "fallTurnout", "nraces", "schoolMillShare", "OOH_share",
                         "PerBachelorOrAbove", "WERC_elec", 
                         "turnout_overall_werc", 
                         "PROPERTYTAX_REV_SHARE", "minBlaisLago", "per_white_all",
                         "GovTurnout_recall", "locale2", 
                         "econ_disadv_per")]
outdata$WERC_str <- outdata$turnout_overall_werc
outdata$turnout_overall_werc <- NULL

outdata$ImputedFlag[is.na(outdata$ImputedFlag)] <- "No"
outdata$ImputedFlag <- ifelse(outdata$ImputedFlag == "Imputed2010", "Yes", "No")

preTreat <- outdata[outdata$year <= 2010,]
preTreat$year <- preTreat$year + 1
names(preTreat) <- paste(names(preTreat), "lag", sep = "_")

# Repeat 2010 data as pre-treatment for 2012
tmp <- preTreat[preTreat$year_lag == 2011,]
tmp$year_lag <- 2012
preTreat <- rbind(preTreat, tmp)
rm(tmp)
outdata <- outdata[, c("contestMinor", "contestSer", "turnout", "turnoutDiff", 
                       "minBlaisLago", "incDefeats", "ImputedFlag", 
                       "distid", "year")]
outdata <- merge(outdata, preTreat, by.y = c("distid_lag", "year_lag"), 
                 by.x = c("distid", "year"))

outdata$treatment <- ifelse(outdata$year >= 2011, abs(outdata$year - 2013), 0)
outdata <- outdata[outdata$year > 2007, ]
outdata <- na.omit(outdata)
outdata <- outdata[!is.na(outdata$turnout_lag), ]
outdata <- outdata[!is.na(outdata$turnout), ]
outdata <- outdata[outdata$turnout > 0,]
outdata <- outdata[outdata$turnout_lag > 0,]
centr <- mean(outdata$turnout)
stddev <- sd(outdata$turnout)
outdata$outflag <- (outdata$turnout - centr) / stddev
outdata$outflag2 <- (outdata$turnout_lag - centr) / stddev
outdata <- outdata[outdata$outflag <= 5 & outdata$outflag >= -5,]
outdata <- outdata[outdata$outflag2 <= 5 & outdata$outflag2 >= -5,]
# outdata <- outdata[outdata$year > 2007, ]
outdata$turnout <- log(outdata$turnout)
outdata$turnout_lag <- log(outdata$turnout_lag)
outdata$minBlaisLago <- ifelse(outdata$minBlaisLago == 0, 0.003, outdata$minBlaisLago)
outdata$minBlaisLago_lag <- ifelse(outdata$minBlaisLago_lag == 0, 0.003, 
                                   outdata$minBlaisLago_lag)
outdata$minBlaisLago <- log(outdata$minBlaisLago)
outdata$minBlaisLago_lag <- log(outdata$minBlaisLago_lag)
outdata$incDefeats <- factor(outdata$incDefeats)
outdata$incDefeats_lag <- factor(outdata$incDefeats_lag)
library(arm)
nums <- sapply(outdata, is.numeric)
# nums["treatment"] <- FALSE
outdata[, nums] <- apply(outdata[, nums], 2, rescale)

simp1 <- glm(contestSer ~ contestSer_lag + treatment * WERC_str_lag+ 
              WERC_elec_lag, 
             data = outdata, family = 'binomial')
simp1$se <- sqrt(diag(get_CL_vcov(simp1, outdata$distid)))

simp2 <- glm(contestMinor ~ contestMinor_lag + treatment * WERC_str_lag+ 
              WERC_elec_lag, 
             data = outdata, family = 'binomial')
simp2$se <- sqrt(diag(get_CL_vcov(simp2, outdata$distid)))

simp3 <- lm(minBlaisLago ~ minBlaisLago_lag + treatment * WERC_str_lag + 
              WERC_elec_lag, 
             data = outdata)
simp3$se <- sqrt(diag(get_CL_vcov(simp3, outdata$distid)))

simp4 <- lm(turnout ~ turnout_lag + treatment * WERC_str_lag+ 
              WERC_elec_lag + ImputedFlag, 
             data = outdata)
simp4$se <- sqrt(diag(get_CL_vcov(simp4, outdata$distid)))

simp5 <- lm(turnoutDiff ~ turnoutDiff_lag + treatment * WERC_str_lag+ 
              WERC_elec_lag + ImputedFlag,  
             data = outdata)
simp5$se <- sqrt(diag(get_CL_vcov(simp5, outdata$distid)))

simp6 <- glm(incDefeats ~ incDefeats_lag + treatment * WERC_str_lag + 
               WERC_elec_lag, 
             data = outdata, family = "binomial")
simp6$se <- sqrt(diag(get_CL_vcov(simp6, outdata$distid)))


full1 <- glmer(contestMinor ~ contestMinor_lag + treatment + 
                 VAP_adjLOG_sq_lag + 
             VAP_adjLOG_lag + per65o_lag + nraces_lag + OOH_share_lag +  
               PerBachelorOrAbove_lag + locale2_lag + WERC_elec_lag +
               treatment * WERC_str_lag + (1|distid), 
             data = outdata, family = "binomial", control = ctrl)

full2 <- glmer(contestSer ~ contestSer_lag + treatment + VAP_adjLOG_sq_lag + 
             VAP_adjLOG_lag + per65o_lag + nraces_lag + OOH_share_lag +  
               PerBachelorOrAbove_lag + locale2_lag + WERC_elec_lag +
               treatment * WERC_str_lag + (1|distid), 
             data = outdata, family = "binomial", control = ctrl)

full3 <- lmer(minBlaisLago ~ minBlaisLago_lag + treatment + VAP_adjLOG_sq_lag + 
             VAP_adjLOG_lag + per65o_lag + OOH_share_lag +  nraces_lag +
               PerBachelorOrAbove_lag + locale2_lag + WERC_elec_lag +
               treatment * WERC_str_lag + (1|distid), 
             data = outdata)

full4 <- lmer(turnout ~ turnout_lag + treatment + VAP_adjLOG_sq_lag + 
             VAP_adjLOG_lag + per65o_lag + OOH_share_lag +  nraces_lag +
               PerBachelorOrAbove_lag + locale2_lag + WERC_elec_lag +
               ImputedFlag + 
               treatment * WERC_str_lag + (1|distid), 
             data = outdata)

full5 <- lmer(turnoutDiff ~ turnoutDiff_lag + treatment + VAP_adjLOG_sq_lag + 
             VAP_adjLOG_lag + per65o_lag + OOH_share_lag +  nraces_lag +
               PerBachelorOrAbove_lag + locale2_lag + WERC_elec_lag +
               ImputedFlag + 
               treatment * WERC_str_lag + (1|distid), 
             data = outdata)

full6 <- glmer(incDefeats ~ incDefeats_lag + treatment + VAP_adjLOG_sq_lag + 
             VAP_adjLOG_lag + per65o_lag + OOH_share_lag +  nraces_lag +
               PerBachelorOrAbove_lag + locale2_lag + WERC_elec_lag +
               treatment * WERC_str_lag + (1|distid), 
             data = outdata, family = "binomial")

apsrtable(simp1, simp3, simp4, simp5, simp6, se = "robust", digits = 3, 
          model.names = c("Ser. Cont.", "Compet.", 
                          "Turnout", "Rolloff", "Inc. Def."), 
           stars = "default", 
          caption = "Mediation Estimates of Union Strength on Board Elections", 
          label = "tab:unionMed", notes = list(stars.note), Sweave = TRUE)

unionMedtable <- apsrtable(full1, full3, full4, full5, full6, 
                           se = "robust", digits = 3, 
                  model.names = c("Ser. Cont.", "Compet.", 
                          "Turnout", "Rolloff", "Inc. Def."), 
          caption = "Mediation Estimates of Union Strength on Board Elections - Multilevel Models",           
          label = "tab:unionMedHLM", notes = list(stars.note), Sweave = TRUE, 
          stars = "default")
@
\end{small}

% Some evidence of union strength mediating turnout and incumbent defeat


\subsection{Recall Turnout}

%tab:recallTurnMed
\begin{small}
<<recallTurnout, results='asis'>>=
outdata <- dist_turn[, c("distid", "year", "contestMinor", "contestSer", 
                         "VAP_adjLOG_sq", "turnout", "turnoutDiff", 
                         "GovTurnout_recall", "incDefeats", 
                         "RecallPolarization", "ImputedFlag",
                         "VAP_adjLOG", "per65o", "NonPublicPupilPer", 
                         "incumShare", "teachShareofVoters", 
                         "fallTurnout", "nraces", "schoolMillShare",
                         "OOH_share", "PerBachelorOrAbove", 
                         "PROPERTYTAX_REV_SHARE", "minBlaisLago", 
                         "per_white_all", "GovTurnout_recall", 
                         "locale2", "econ_disadv_per")]

outdata$RecallTurnout <- outdata$GovTurnout_recall
outdata$GovTurnout_recall <- NULL
outdata$ImputedFlag[is.na(outdata$ImputedFlag)] <- "No"
outdata$ImputedFlag <- ifelse(outdata$ImputedFlag == "Imputed2010", "Yes", "No")

preTreat <- outdata[outdata$year <= 2010,]
preTreat$year <- preTreat$year + 1
names(preTreat) <- paste(names(preTreat), "lag", sep = "_")

# Repeat 2010 data as pre-treatment for 2012
tmp <- preTreat[preTreat$year_lag == 2011,]
tmp$year_lag <- 2012
preTreat <- rbind(preTreat, tmp)
rm(tmp)
outdata <- outdata[, c("contestMinor", "contestSer", "turnout", "turnoutDiff", 
                       "minBlaisLago", "incDefeats", "ImputedFlag", 
                       "distid", "year")]
outdata <- merge(outdata, preTreat, by.y = c("distid_lag", "year_lag"), 
                 by.x = c("distid", "year"))

outdata$treatment <- ifelse(outdata$year >= 2011, abs(outdata$year - 2013), 0)
outdata <- outdata[outdata$year > 2007, ]
outdata <- na.omit(outdata)
outdata <- outdata[!is.na(outdata$turnout_lag), ]
outdata <- outdata[!is.na(outdata$turnout), ]
outdata <- outdata[outdata$turnout > 0,]
outdata <- outdata[outdata$turnout_lag > 0,]
centr <- mean(outdata$turnout)
stddev <- sd(outdata$turnout)
outdata$outflag <- (outdata$turnout - centr) / stddev
outdata$outflag2 <- (outdata$turnout_lag - centr) / stddev
outdata <- outdata[outdata$outflag <= 5 & outdata$outflag >= -5,]
outdata <- outdata[outdata$outflag2 <= 5 & outdata$outflag2 >= -5,]
# outdata <- outdata[outdata$year > 2007, ]
outdata$turnout <- log(outdata$turnout)
outdata$turnout_lag <- log(outdata$turnout_lag)
outdata$minBlaisLago <- ifelse(outdata$minBlaisLago == 0, 0.003, outdata$minBlaisLago)
outdata$minBlaisLago_lag <- ifelse(outdata$minBlaisLago_lag == 0, 0.003, 
                                   outdata$minBlaisLago_lag)
outdata$minBlaisLago <- log(outdata$minBlaisLago)
outdata$minBlaisLago_lag <- log(outdata$minBlaisLago_lag)
outdata$incDefeats <- factor(outdata$incDefeats)
outdata$incDefeats_lag <- factor(outdata$incDefeats_lag)
library(arm)
nums <- sapply(outdata, is.numeric)
# nums["treatment"] <- FALSE
outdata[, nums] <- apply(outdata[, nums], 2, rescale)

simp1 <- glm(contestSer ~ contestSer_lag + treatment * RecallTurnout_lag, 
             data = outdata, family = 'binomial')
simp1$se <- sqrt(diag(get_CL_vcov(simp1, outdata$distid)))

simp2 <- glm(contestMinor ~ contestMinor_lag + treatment * RecallTurnout_lag, 
             data = outdata, family = 'binomial')
simp2$se <- sqrt(diag(get_CL_vcov(simp2, outdata$distid)))

simp3 <- lm(minBlaisLago ~ minBlaisLago_lag + treatment * RecallTurnout_lag, 
             data = outdata)
simp3$se <- sqrt(diag(get_CL_vcov(simp3, outdata$distid)))

simp4 <- lm(turnout ~ turnout_lag + treatment * RecallTurnout_lag + 
              ImputedFlag, 
             data = outdata)
simp4$se <- sqrt(diag(get_CL_vcov(simp4, outdata$distid)))

simp5 <- lm(turnoutDiff ~ turnoutDiff_lag + treatment * RecallTurnout_lag +
              ImputedFlag, 
             data = outdata)
simp5$se <- sqrt(diag(get_CL_vcov(simp5, outdata$distid)))

simp6 <- glm(incDefeats ~ incDefeats_lag + treatment * RecallTurnout_lag, 
             data = outdata, family = "binomial")
simp6$se <- sqrt(diag(get_CL_vcov(simp6, outdata$distid)))

full1 <- glmer(contestMinor ~ contestMinor_lag + treatment + VAP_adjLOG_sq_lag + 
             VAP_adjLOG_lag + per65o_lag + nraces_lag + OOH_share_lag +  
               PerBachelorOrAbove_lag + locale2_lag + 
               treatment * RecallTurnout_lag + (1|distid), 
             data = outdata, family = "binomial", control = ctrl)

full2 <- glmer(contestSer ~ contestSer_lag + treatment + VAP_adjLOG_sq_lag + 
             VAP_adjLOG_lag + per65o_lag + nraces_lag + OOH_share_lag +  
               PerBachelorOrAbove_lag + locale2_lag + 
               treatment * RecallTurnout_lag + (1|distid), 
             data = outdata, family = "binomial", control = ctrl)

full3 <- lmer(minBlaisLago ~ minBlaisLago_lag + treatment + VAP_adjLOG_sq_lag + 
             VAP_adjLOG_lag + per65o_lag + OOH_share_lag +  nraces_lag +
               PerBachelorOrAbove_lag + locale2_lag + 
               treatment * RecallTurnout_lag + (1|distid), 
             data = outdata)

full4 <- lmer(turnout ~ turnout_lag + treatment + VAP_adjLOG_sq_lag + 
             VAP_adjLOG_lag + per65o_lag + OOH_share_lag +  nraces_lag +
               PerBachelorOrAbove_lag + locale2_lag + ImputedFlag +
               treatment * RecallTurnout_lag + (1|distid), 
             data = outdata)

full5 <- lmer(turnoutDiff ~ turnoutDiff_lag + treatment + VAP_adjLOG_sq_lag + 
             VAP_adjLOG_lag + per65o_lag + OOH_share_lag +  nraces_lag +
               PerBachelorOrAbove_lag + locale2_lag + ImputedFlag +
               treatment * RecallTurnout_lag + (1|distid), 
             data = outdata)

full6 <- glmer(incDefeats ~ incDefeats_lag + treatment + VAP_adjLOG_sq_lag + 
             VAP_adjLOG_lag + per65o_lag + OOH_share_lag +  nraces_lag +
               PerBachelorOrAbove_lag + locale2_lag + 
               treatment * RecallTurnout_lag + (1|distid), 
             data = outdata, family = "binomial")

apsrtable(simp1, simp3, simp4, simp5, simp6, se = "robust", digits = 3, 
          model.names = c("Ser. Cont.", "Compet.", 
                          "Turnout", "Rolloff", "Inc. Def."), 
           stars = "default", 
          caption = "Mediation Estimates of Recall Turnout on Board Elections", 
          label = "tab:recallTurnMed", notes = list(stars.note), Sweave = TRUE)

recallTurnMedTable <- apsrtable(full1, full3, full4, full5, full6, 
                                se = "robust", digits = 3, 
          model.names = c("Ser. Cont.", "Compet.", 
                          "Turnout", "Rolloff", "Inc. Def."), 
          stars = "default", 
          caption = "Mediation Estimates of Recall Turnout on Board Elections - HLM", 
          label = "tab:recallTurnMedHLM", notes = list(stars.note), Sweave = TRUE)
@
\end{small}

% Turnout and rolloff see increased effect for turnout recall



\subsubsection{Full Mediation}

Least likely to work. 

%tab:recallAllMed
\begin{small}
<<turnandpolarRecall, results='asis'>>=
outdata <- dist_turn[, c("distid", "year", "contestMinor", "contestSer", 
                         "VAP_adjLOG_sq", "turnout", "turnoutDiff", 
                         "GovTurnout_recall", "incDefeats", 
                         "RecallPolarization", "ImputedFlag",
                         "VAP_adjLOG", "per65o", "NonPublicPupilPer", 
                         "incumShare", "teachShareofVoters", 
                         "fallTurnout", "nraces", "schoolMillShare",
                         "OOH_share", "PerBachelorOrAbove", 
                         "PROPERTYTAX_REV_SHARE", "minBlaisLago", 
                         "per_white_all", "GovTurnout_recall", 
                         "locale2", "econ_disadv_per")]

outdata$RecallTurnout <- outdata$GovTurnout_recall
outdata$GovTurnout_recall <- NULL
outdata$ImputedFlag[is.na(outdata$ImputedFlag)] <- "No"
outdata$ImputedFlag <- ifelse(outdata$ImputedFlag == "Imputed2010", "Yes", "No")

preTreat <- outdata[outdata$year <= 2010,]
preTreat$year <- preTreat$year + 1
names(preTreat) <- paste(names(preTreat), "lag", sep = "_")

# Repeat 2010 data as pre-treatment for 2012
tmp <- preTreat[preTreat$year_lag == 2011,]
tmp$year_lag <- 2012
preTreat <- rbind(preTreat, tmp)
rm(tmp)
outdata <- outdata[, c("contestMinor", "contestSer", "turnout", "turnoutDiff", 
                       "minBlaisLago", "incDefeats", "ImputedFlag", 
                       "distid", "year")]
outdata <- merge(outdata, preTreat, by.y = c("distid_lag", "year_lag"), 
                 by.x = c("distid", "year"))

outdata$treatment <- ifelse(outdata$year >= 2011, abs(outdata$year - 2013), 0)
outdata <- outdata[outdata$year > 2007, ]
outdata <- na.omit(outdata)
outdata <- outdata[!is.na(outdata$turnout_lag), ]
outdata <- outdata[!is.na(outdata$turnout), ]
outdata <- outdata[outdata$turnout > 0,]
outdata <- outdata[outdata$turnout_lag > 0,]
centr <- mean(outdata$turnout)
stddev <- sd(outdata$turnout)
outdata$outflag <- (outdata$turnout - centr) / stddev
outdata$outflag2 <- (outdata$turnout_lag - centr) / stddev
outdata <- outdata[outdata$outflag <= 5 & outdata$outflag >= -5,]
outdata <- outdata[outdata$outflag2 <= 5 & outdata$outflag2 >= -5,]
# outdata <- outdata[outdata$year > 2007, ]
outdata$turnout <- log(outdata$turnout)
outdata$turnout_lag <- log(outdata$turnout_lag)
outdata$minBlaisLago <- ifelse(outdata$minBlaisLago == 0, 0.003, outdata$minBlaisLago)
outdata$minBlaisLago_lag <- ifelse(outdata$minBlaisLago_lag == 0, 0.003, 
                                   outdata$minBlaisLago_lag)
outdata$minBlaisLago <- log(outdata$minBlaisLago)
outdata$minBlaisLago_lag <- log(outdata$minBlaisLago_lag)
outdata$incDefeats <- factor(outdata$incDefeats)
outdata$incDefeats_lag <- factor(outdata$incDefeats_lag)
library(arm)
nums <- sapply(outdata, is.numeric)
# nums["treatment"] <- FALSE
outdata[, nums] <- apply(outdata[, nums], 2, rescale)

simp1 <- glm(contestSer ~ contestSer_lag + treatment * RecallTurnout_lag + 
               treatment * RecallPolarization_lag, 
             data = outdata, family = 'binomial')
simp1$se <- sqrt(diag(get_CL_vcov(simp1, outdata$distid)))

simp2 <- glm(contestMinor ~ contestMinor_lag + treatment * RecallTurnout_lag + 
               treatment * RecallPolarization_lag, 
             data = outdata, family = 'binomial')
simp2$se <- sqrt(diag(get_CL_vcov(simp2, outdata$distid)))

simp3 <- lm(minBlaisLago ~ minBlaisLago_lag + treatment * RecallTurnout_lag+ 
               treatment * RecallPolarization_lag, 
             data = outdata)
simp3$se <- sqrt(diag(get_CL_vcov(simp3, outdata$distid)))

simp4 <- lm(turnout ~ turnout_lag + treatment * RecallTurnout_lag + 
              ImputedFlag + 
               treatment * RecallPolarization_lag, 
             data = outdata)
simp4$se <- sqrt(diag(get_CL_vcov(simp4, outdata$distid)))

simp5 <- lm(turnoutDiff ~ turnoutDiff_lag + treatment * RecallTurnout_lag +
              ImputedFlag + 
               treatment * RecallPolarization_lag, 
             data = outdata)
simp5$se <- sqrt(diag(get_CL_vcov(simp5, outdata$distid)))

simp6 <- glm(incDefeats ~ incDefeats_lag + treatment * RecallTurnout_lag + 
               treatment * RecallPolarization_lag, 
             data = outdata, family = "binomial")
simp6$se <- sqrt(diag(get_CL_vcov(simp6, outdata$distid)))


full1 <- glmer(contestMinor ~ contestMinor_lag + treatment + 
                 VAP_adjLOG_sq_lag + 
             VAP_adjLOG_lag + per65o_lag + nraces_lag + OOH_share_lag +  
               PerBachelorOrAbove_lag + locale2_lag + 
               treatment * RecallTurnout_lag + 
               treatment * RecallPolarization_lag +  (1|distid), 
             data = outdata, family = "binomial", control = ctrl)

full2 <- glmer(contestSer ~ contestSer_lag + treatment + VAP_adjLOG_sq_lag + 
             VAP_adjLOG_lag + per65o_lag + nraces_lag + OOH_share_lag +  
               PerBachelorOrAbove_lag + locale2_lag + 
               treatment * RecallTurnout_lag + 
               treatment * RecallPolarization_lag + (1|distid), 
             data = outdata, family = "binomial", control = ctrl)

full3 <- lmer(minBlaisLago ~ minBlaisLago_lag + treatment + VAP_adjLOG_sq_lag + 
             VAP_adjLOG_lag + per65o_lag + OOH_share_lag +  nraces_lag +
               PerBachelorOrAbove_lag + locale2_lag + 
               treatment * RecallTurnout_lag + 
               treatment * RecallPolarization_lag + (1|distid), 
             data = outdata)

full4 <- lmer(turnout ~ turnout_lag + treatment + VAP_adjLOG_sq_lag + 
             VAP_adjLOG_lag + per65o_lag + OOH_share_lag +  nraces_lag +
               PerBachelorOrAbove_lag + locale2_lag + ImputedFlag +
               treatment * RecallTurnout_lag + 
               treatment * RecallPolarization_lag + (1|distid), 
             data = outdata)

full5 <- lmer(turnoutDiff ~ turnoutDiff_lag + treatment + VAP_adjLOG_sq_lag + 
             VAP_adjLOG_lag + per65o_lag + OOH_share_lag +  nraces_lag +
               PerBachelorOrAbove_lag + locale2_lag + ImputedFlag +
               treatment * RecallTurnout_lag + 
               treatment * RecallPolarization_lag + (1|distid), 
             data = outdata)

full6 <- glmer(incDefeats ~ incDefeats_lag + treatment + VAP_adjLOG_sq_lag + 
             VAP_adjLOG_lag + per65o_lag + OOH_share_lag +  nraces_lag +
               PerBachelorOrAbove_lag + locale2_lag + 
               treatment * RecallTurnout_lag + 
               treatment * RecallPolarization_lag + (1|distid), 
             data = outdata, family = "binomial")


apsrtable(simp1, simp3, simp4, simp5, simp6, se = "robust", digits = 3, 
          model.names = c("Ser. Cont.", "Compet.", 
                          "Turnout", "Rolloff", "Inc. Def."),
           stars = "default", 
          caption = "Mediation Estimates of Recall on Board Elections", 
          label = "tab:recallAllMed", notes = list(stars.note), Sweave = TRUE)

recallMedTable <- apsrtable(full1, full3, full4, full5, full6, 
                            se = "robust", digits = 3, 
          model.names = c("Ser. Cont.", "Compet.", 
                          "Turnout", "Rolloff", "Inc. Def."), 
          stars = "default", 
          caption = "Mediation Estimates of Recall on Board Elections - Multilevel Models",           
          label = "tab:recallAllMedHLM", notes = list(stars.note), 
          Sweave = TRUE)
@
\end{small}
% Rolloff and turnout evidence for polarization and turnout on treatment

\subsection{Substantive Impact Size}


<<substEff1, eval=FALSE>>=


@



\subsection{Contestation}

To evaluate this, a series of models of school board election contestation over 
time are fit to attempt to detect changes in contestation levels relative to the 
levels of contestation observed in school districts prior to the passage of 
Act 10. If levels of contestation increase after the introduction of Act 10, even 
after controlling for the factors that influenced this above, it would be strong 
evidence that the statewide policy lever pulled by Act 10 did spur a response 
from candidates in terms of increasing the attractiveness of school board seats. 

The results in Table \ref{tab:meSer} does not show much promise, like in Chapter 
\ref{chap:candidacy}. The models do not fit well, and though the effects of 
polarization and the post-recall effect are in the direction hypothesized, they 
are not statistically significant. There is evidence that polarization leads to 
greater contestation, and post-recall recall turnout is more strongly associated 
with increased contestation. One prediction that is in the wrong direction is that 
the effect of polarization decreases post-recall. Few other predictors are statistically 
significant and there is not much to conclude about a change in contested seats 
post recall, as shown above in Figure \ref{fig:serContestPlot}. 

% Serious contestation like in Chapter 3 does not show promise
% polarization is associated with greater contestation 
% Post-recall has greater contestation
% recall turnout ^ is associated with a decrease in serious contestation
% effect is magnified post recall
% none of these effects are statistically significant
% Models appear to fit poorly
% TODO: Consider refitting to demographics only + groups of interactions


In Table \ref{tab:meMin} the results are largely the same, suggesting nominal 
contestation is no easier to predict. Here, polarization is related to slightly 
decreasing contestation, but contestation is predicted to increase after the recall. 
Post-recall, polarization has a stronger effect, as projected. Recall turnout 
is related to reducted contestation, but this relationship changes post-recall. 
However, none of these effects are statistically significant. 

% Sign on recall polarization flips from seriousness
% Recall polarization ^ associated with less contestation nominally
% polarization is associated with greater contestation 
% Post-recall has greater contestation
% recall turnout ^ is associated with a decrease in serious contestation
% effect is magnified post recall
% none of these effects are statistically significant
% Models appear to fit poorly
% TODO: Consider refitting to demographics only + groups of interactions

The models in Tables \ref{tab:meMin} and \ref{tab:meSer} are disappointing, but 
this is in part due to the small sample size involved and the fact that few 
variables at all have been shown to be predictive of this measure of contestation. 
It is unsurprising that an effect on contestation was detectable in the small 
sample here. I now turn to models that have more promise. 

\subsection{Incumbent Defeat}

As in Chapter \ref{chap:candidacy} I fit incumbent defeat models on a subset of 
elections for which an incumbent is facing the possibility of defeat -- that is 
where there are more candidates than incumbents in the race. These models are the only 
models that show some promise. However, as was the case in Chapter \ref{chap:candidacy}, 
the sample size decreases as I restrict the data to cases where incumbents are 
running, but also a challenger is present as well. This reduced sample size 
is problematic for fitting a random-effect model as the number of group terms 
is approaching the number of observations. 


The results in table \ref{tab:meIncDef} show a consistent negative effect of 
post-recall years on incumbent defeat, but this effect is not statistically 
significant. This is counter to expectations, but is perhaps offset by the 
specific effects of the recall results. Recall polarization is associated with 
greater incumbent defeat post-recall and recall turnout is as well -- but these 
effects are also not statistically significant. Turnout in union certification 
elections is positively related with incumbent defeat post-recall -- exactly as 
expected. This effect is statistically significnt, providing some evidence that 
union activity post-recall was active in both organizing union members and participating 
in school board elections. This effect can be attributed to a state-level policy 
decision, which has a clear impact on the behavior and results of local officials. 

% Note models built on a smaller subset
% Problems with convergence
% incumbent defeat seems to go down post recall
% Recall polarization negatively related to incumbent defeat
% incumbent defeat increases with polarization post election
% recall turnout negatively related to incumbent defeat
% recall turnout post recall positively related with incumbent defeat

\subsection{Competitiveness}

Looking at incumbent defeat as a binary measure of competitiveness downplays 
the significance of challenges that result in a narrow defeat by a challenger 
to an incumbent -- which would be coded as a 0 in Table \ref{meIncDef}. Using 
a general measure of competitiveness across districts, I examine if races 
become more or less competitive after the recall election, and if the impact 
of any recall related variables changes after the election. These models are 
again fit on a subset of models, those in which a competitive race is possible 
because voters are presented with a choice. 


Table \ref{tab:meBLQ} shows that there is little evidence that the events of 
2011 had an impact on the competitiveness of school board races in Wisconsin, and 
there is no evidence of differential impact between school districts. The only 
variables that show some impact are the measures of union strength, which show 
that unions that held a recertification election had less competitive races 
over the observation period, and those that had high turnout post Act 10 had 
more competitive races over the period. 

% Why might this be?

\clearpage

\subsection{Turnout}

Using the election of Governor Walker and passage of Act 10 as an exogenous shock that 
increased the relevance and power of school boards, the following models seek to 
test the causal impact on turnout. In Figure \ref{fig:walkerplot} I examine the 
relationship between partisan polarization and turnout before and after the passage 
of Act 10. To test this relationship I restrict the sample to the two spring 
elections prior to the passage of Act 10 -- 2009 and 2010 -- and the two elections 
immediately after the passage of Act 10 -- 2011 and 2012. I code these latter 
years with a dummy variable indicating they are in the post-Act 10 era. The key 
theoretical contribution is that the polarization of the electorate should matter 
more after the passage of Act 10, when party lines for education issues became 
clear. 

Table \ref{tab:meTurnout} shows the results for the impact of the Wisconsin recall 
on turnout in school board elections. First, there is a statistically significant 
and consistently positive effect post-recall on turnout. Pre-recall, neither 
polarization nor WERC election turnout seem to matter much. Post-recall, polarization 
is associated with a decrease in turnout and turnout in WERC certification elections 
is associated with a modest increase in turnout. Thus, polarization can be seen 
as mediating the impact of increased voter turnout overall -- with more divided 
communities having slightly less spring turnout. Turnout for the recall continues 
to exhibit that turnout is sticky -- even after controlling for both the previous 
fall turnout and the spring election turnout twice-lagged, recall turnout is 
still positively associated with higher turnout overall, and this effect is stronger 
in the post-recall period. WERC strength, measured by WERC election turnout in the 
post-recall period, is not associated with overall increased turnout, but in the 
post-recall period it is associated with a modest increase in school board election 
turnout. 


These results are a strong confirmation of the expectations described in Table 
\ref{tab:act10hypo}. However, as with the turnout models from Chapter \ref{chap:turnout}, 
these models do not capture solely turnout for school board elections as there 
are other key races which are higher profile in the spring. In order to better 
isolate the impact on school board elections themselves, I next isolate the effect 
on the gap between turnout on the top ticket race and school board turnout. 

\clearpage

\subsubsection{Rolloff}


Table \ref{tab:meRolloff} depicts the results for voter rolloff. The dependent 
variable is the gap between school board votes and top ticket votes -- the bigger 
the number, the fewer voters bothered to complete their ballot for school board and 
ostensibly were indifferent about school board and turned out to vote for another 
reason. First, the recall led to increased voter rolloff in the post-recall 
periods. This suggests that the spring elections post Act 10 had more voter 
activity, but these voters were less likely to complete their ballots. 

Second, recall polarization does not seem to matter. Polarized communities 
completed their ballots at roughly the same rate, though there is slight evidence 
of a small increase in ballot rolloff post-recall. Increased turnout for the recall 
leads to an increase in voter rolloff as well. This effect becomes sharper post-recall. 
The only dampening effect observed on rolloff is the strength of teacher's unions. 
In all periods, stronger unions exhibit a slight negative effect on rolloff. 
Unions that had a WERC election show a strong effect at dampening rolloff, but 
the stronger the union result in the election, the greater the rolloff. Neither 
of these effects was changed post-recall. 

% rolloff increases post recall
% WERC turnout decreases rolloff (no differentiation post recall)
% Recall polarization has no effect on turnout, and none post recall
% recall turnout increases rolloff, post recall this is magnified
% Net of increased turnout, recall polarization leads to increased 
% voter rolloff

These findings are remarkable because they indicate that while political activity 
in spring non-partisan elections was fundamentally altered by the events of 2011, 
school board elections themselves were not specifically affected. 

\clearpage

\subsection{Substantive Effects}

Next I demonstrate the substantive magnitude of the state level policy shock to 
contextualize the influence that state government can have on local elections. 

% Which models to simulate
% No models of contestation -- no results!
% WERC model for incumbent defeat IncDef4mm
% Treatment effect on competitiveness demogsMMblq1
%  Treatment effect on turnout demogsMod1mm
%  Polarization damper on turnout demogsMod3mm
%  Rolloff
% demogsMod3roMM for post-recall polarization impact
% demogsMod4roMM for post-recall WERC impact

\section{Conclusion}

\clearpage

\section{Appendix}

\subsection{Minor Contestation Models}

\begin{small}
<<causModelminor, results='asis'>>=
causMinorConTab
@
\end{small}

\subsection{Full Mediation Models}

HLM mediation models. 

\begin{small}
<<unionMedtable, results='asis'>>=
unionMedtable
@
\end{small}

\begin{small}
<<polarMedTable, results='asis'>>=
polarMedTable
@
\end{small}

\begin{small}
<<recallTurnMedTable, results='asis'>>=
recallTurnMedTable
@
\end{small}


\begin{small}
<<recallMedTable, results='asis'>>=
recallMedTable
@
\end{small}

